### ISSUE TITLE
Safari插件似乎不能安装

### ISSUE THREAD

**Issue by HatCloud** [acgotaku/BaiduExporter#100]
双击安装文件后，再在弹出窗口中选择信任后发现插件没有安装

**Comment by Cee** [comment]
卸载 115 和 BaiduExporter 后重新安装

**Comment by HatCloud** [comment]
我之前并没有在Safari上安装过BaiduExporter，而且在偏好设置的插件列表里也没有这两个插件

**Comment by HatCloud** [comment]
![Uploading 屏幕快照 2015-12-07 下午11.39.25.png…]()
我安装了这些插件

**Comment by acgotaku** [comment]
@Cee  图没传上来啊 @HatCloud

**Comment by HatCloud** [comment]
@acgotaku 更新了，而且我尝试把所有扩展都卸载掉安装，并没有用
<img width="740" alt="2015-12-08 11 19 32" src="https://cloud.githubusercontent.com/assets/7430550/11646940/a929fe70-9d9d-11e5-9c40-4d0687749144.png">

**Comment by HatCloud** [comment]
是我自己的问题。
我发现其他扩展也无法安装，正在排查哪里出错了

**Comment by acgotaku** [comment]
@HatCloud 囧

**Comment by HatCloud** [comment]
@acgotaku 删掉Safari的所有数据后问题解决了。
感谢你的扩展，很好用。

**Comment by acgotaku** [comment]
你应该谢 @Cee Safari版本不是我移植的

**Comment by GoldenNotebook** [comment]
你删除了Safari哪些数据了？我删了也不能安装！

**Comment by GoldenNotebook** [comment]
我重启后能用了。。看来重启也只治疗OS X抽风的一大方法！
