### ISSUE TITLE
工作异常: 自己的盘页面没有导出下载，其他人共享的有

### ISSUE THREAD

**Issue by laucenmi** [acgotaku/BaiduExporter#102]
打开自己的网盘看不到导出下载按钮，也没有初始化成功或者失败提示。
别人共享的资源链接打开后可以看到导出下载。

**Comment by donly** [comment]
I have the same issue.

**Comment by fortissimoX** [comment]
+1
似乎是百毒改版了？

**Comment by Cee** [comment]
Check #99

**Comment by acgotaku** [comment]
你们就不能看看之前的 issue么 QAQ @Cee 怎么换这么萌的头像了！
