### ISSUE TITLE
百度云代码里好玩的哈哈

### ISSUE THREAD

**Issue by leitwolf** [acgotaku/BaiduExporter#103]
我今天用了QQ浏览器，下的是0.5.7版本，发现选项没出来，然后查看控制台，发现好玩的东西哈哈。
![1](https://cloud.githubusercontent.com/assets/1720546/11800349/a4c0b67a-a316-11e5-9c5c-e23ae771f36f.png)
PS：刚才不小心关掉了之前的Issues

**Comment by Chu2koi** [comment]
还真是求贤若渴了，哈哈

**Comment by HarukaMa** [comment]
好多网站都这样的……

另外建议在 issue 里不要偏题……

**Comment by acgotaku** [comment]
@leitwolf 这玩意至少存在两年了 早就知道了 。。。。
然后你为啥加载不出来呢？ 说重点

**Comment by leitwolf** [comment]
@acgotaku 用0.5.5就可以了，可能 是qq浏览器里还没更新。我现在用chrome，0.5.7已经可以了。谢谢作者大人。

**Comment by acgotaku** [comment]
@leitwolf 0.5.8发布了 两个版本都支持 解决所有问题！
