### ISSUE TITLE
0.5.9 chrome 47.0.2526.80 m 还是不能用

### ISSUE THREAD

**Issue by dos2002** [acgotaku/BaiduExporter#105]
文件地址读取成功,发送post请求道aira时有异常.
![image](https://cloud.githubusercontent.com/assets/6613244/11846111/054e874c-a452-11e5-975b-ba6783a9fe74.png)

**Comment by joyfun** [comment]
这个貌似是baidu自己的问题 有时会出验证码 后来就没出现了

**Comment by acgotaku** [comment]
@dos2002 你能告诉我浏览器的地址么 还有 这个报错不是扩展的 你可以给我看看 network面板

**Comment by wenLiangcan** [comment]
我在 Chromium 47.0.2526.106 上用 0.5.9 也不能导出到 aria2

**Comment by dos2002** [comment]
@acgotaku 浏览器地址是什么意思啊 没看懂 
network截图见此:
![image](https://cloud.githubusercontent.com/assets/6613244/11863843/98ae8c82-a4d2-11e5-8e1f-202d6ca4faba.png)
![image](https://cloud.githubusercontent.com/assets/6613244/11863870/cffce0ee-a4d2-11e5-9b3f-b0925982e74a.png)

**Comment by acgotaku** [comment]
@dos2002 那你试试那个导出下载文本框里面有内容么？ 你这console不报错 还不下载好奇怪。。。

**Comment by acgotaku** [comment]
@dos2002 你这右下角的console内容就是往 aria2发的数据啊

**Comment by dos2002** [comment]
嗯...console里有 network没有 难道是我服务挂了啊 我去

**Comment by acgotaku** [comment]
@dos2002 不是 那个发送是交给后台的 background.js处理的 所以你得打开扩展的背景页才能看到请求

**Comment by acgotaku** [comment]
@dos2002 我觉得可能是 rpc地址的问题 你修改成 默认 不带 token的地址试试

**Comment by dos2002** [comment]
@acgotaku 我也开始怀疑的我aria了 等我测试下115的

**Comment by acgotaku** [comment]
@dos2002 也有可能是我解析 token出问题了

**Comment by dos2002** [comment]
@acgotaku 115的RPC能正常下载....需要我跟踪日志么,另外
"background.js处理的 所以你得打开扩展的背景页才能看到请求"
怎么操作啊?

**Comment by acgotaku** [comment]
@dos2002 GIthub下载源码 用开发者模式文件夹加载  好的 我知道了 我这就换 rpc地址开始调试

**Comment by dos2002** [comment]
哈哈哈 我也一起commiter吧 @acgotaku

**Comment by acgotaku** [comment]
@dos2002 问题找到了 token的原因 等修复

**Comment by dos2002** [comment]
@acgotaku 拼错了啊,好的...

**Comment by acgotaku** [comment]
@dos2002 不对 我 token测试了 也没问题啊。。。

**Comment by dos2002** [comment]
@acgotaku 我回家先确认下服务的问题吧 然后我加载源码跟踪吧 token不对会显示授权无效啊..

**Comment by acgotaku** [comment]
@dos2002 会在后台显示无效的

**Comment by dos2002** [comment]
@acgotaku  嗯 嗯 我慢慢调 我估计是我环境问题

**Comment by acgotaku** [comment]
@dos2002 你可以给我私信你的 rpc地址么 我试试？  acgotaku311 # gmail

**Comment by dos2002** [comment]
@acgotaku 我去开个DMZ 稍等 我现在都是VPN到家里

**Comment by dos2002** [comment]
@acgotaku 私你了 试试

**Comment by acgotaku** [comment]
@dos2002 不能用 QAQ

**Comment by dos2002** [comment]
@acgotaku  回家我自己跟源码吧 哈哈哈哈

**Comment by acgotaku** [comment]
@dos2002 大哥 你调试好了没? 好了就关掉这个 issue  ==

**Comment by rankjie** [comment]
Chrome： 48.0.2564.48 (64-bit)

也是遇到了类似问题，显示提示成功获取到文件信息，但是postMessage到aria2的时候就没反应了... console也没有报错，network只能看到往filemeta的请求成功，然后就没有了。

**Comment by acgotaku** [comment]
@rankjie 那导出下载的时候有问题么? 如果你的 aria2是公网地址可以私信给我测试测试么?

**Comment by rankjie** [comment]
已经发去您的邮箱

**Comment by dos2002** [comment]
@acgotaku @Cee  问题我已经基本定位,是百度自己埋的坑.
1.百度云盘默认会和自己的云管家通讯,当云管家未启动时SDK发出的URL为127.0.0.1:10000-10009.
http://127.0.0.1:10000/guanjia?method=GetVersion&bdstoken=*&channel=chunlei&clienttype=0&web=1&app_id=250528
2.新版CHROME无法自动调用云管家必须手动启动.
3.启动后通讯地址不变但是能连上.
4.然后就可以正常使用aria2RPC.
综合来说就是必要要启动云管家,并且和自己的网盘通讯上就好.

**Comment by acgotaku** [comment]
@dos2002 我 Linux 并没有云管家也可以正常使用啊？

**Comment by dos2002** [comment]
@acgotaku 可能是我原来用过 有历史数据吧 我也是猜测,你看这个请求
![image](https://cloud.githubusercontent.com/assets/6613244/11969950/366502a6-a95d-11e5-80d5-eb375417b20c.png)

**Comment by acgotaku** [comment]
@dos2002 我这边也有这个请求啊 只不过没装管家 请求失败了而已  这并没有什么关系啊。。。

**Comment by dos2002** [comment]
@acgotaku 说是这么说啊 ,但是我这边这个请求失败的时候 aria2 RPC响应.
这个请求OK了就好了,想不通.
是不是和这个监控的请求有关呢?
![image](https://cloud.githubusercontent.com/assets/6613244/11970175/1ccbc146-a961-11e5-9905-d01504338643.png)

**Comment by acgotaku** [comment]
@dos2002 我这边不管这个云管家请求与否 都是正常的...

**Comment by dos2002** [comment]
@acgotaku ok 那我这这个issue关了吧.

**Comment by acgotaku** [comment]
@dos2002 不过这个问题确实很多人存在 但 就是我 无法复现....

**Comment by Cee** [comment]
@acgotaku  @dos2002 请求监控感觉每次都会 Timed out 所以也不是一个人出现这种问题。

**Comment by acgotaku** [comment]
@Cee 但我电脑出现 不了 我就无法排查原因啊 为什么别人有问题 但我好好的 ...

**Comment by Cee** [comment]
@acgotaku 我这是 monitor.jpg 有 timeout 的问题，无论装不装云管家都不会有 timeout 的错误...

**Comment by rankjie** [comment]
First world problem: can not reproduce :)





On Tue, Dec 22, 2015 at 8:01 PM -0800, "Cee Cirno" <notifications@github.com> wrote:












@acgotaku 我这是 monitor.jpg 有 timeout 的问题，无论装不装云管家都不会有 timeout 的错误...
