### ISSUE TITLE
BaiduExporter disabled in Firefox 43.0

### ISSUE THREAD

**Issue by cnxsoft** [acgotaku/BaiduExporter#106]
BaiduExporter is now disabled in the latest Firefox 43.0 because "it could not be verified".
I could not find a workaround so far.

**Comment by acgotaku** [comment]
@cnxsoft So you can use the Chrome.

**Comment by beafuture** [comment]
xpinstall.signatures.required设置成false 可以安装，但是pan.baidu.com页面上不出现导来的按钮。为什么不提交到addons.mozilla.org 呢？

**Comment by acgotaku** [comment]
@beafuture FF版本目前彻底不能用了 别折腾了 不提交是因为他们说我的代码不符合规范 
等我重写了FF版本的扩展再折腾吧

**Comment by beafuture** [comment]
多谢辛苦！

**Comment by acgotaku** [comment]
@cnxsoft @beafuture firefox更新了 更新了!!!

**Comment by cnxsoft** [comment]
@acgotaku 谢谢你，现在可以工作!

Still need to set xpinstall.signatures.required to false with about:config. But that's OK :)

**Comment by acgotaku** [comment]
@cnxsoft 能用就关了 这个 issue !

**Comment by Cye3s** [comment]
一个小问题，附加组件列表那这个扩展没图标

**Comment by acgotaku** [comment]
@Cye3s 这么一说 还真的没有...

**Comment by Cye3s** [comment]
我x咧，作者你神出鬼没，马上就回消息了＝。＝

**Comment by acgotaku** [comment]
@Cye3s 有邮件提醒的 当然会看到啦

**Comment by Cye3s** [comment]
xpi根目录下放个icon.png
install.rdf和package.json里的icon定义删了就有图标了
还有设置界面我记得有个测试链接，成功显示版本号，比较方便，也干掉了？

**Comment by acgotaku** [comment]
@Cye3s 版本号 那个准备再加回去 还是挺好使的
