### ISSUE TITLE
百度云的个人专辑功能异常

### ISSUE THREAD

**Issue by JPLiu** [acgotaku/BaiduExporter#108]
[个人专辑链接](http://yun.baidu.com/pcloud/album/info?uk=187421154&album_id=5073017937955973544)
百度的专辑页这个扩展能够加载，单选一个文件下载时功能正常，但是只要**选两个以上的文件时就会出现下载的文件全部是同一个**（勾选的第一个）的情况。
希望能够完善一下。
环境是Win 8.1的Firefox 43

**Comment by acgotaku** [comment]
@JPLiu 已修复 等下个版本更新即可
