### ISSUE TITLE
RPC 下載error http response header was bad or unexpected 

### ISSUE THREAD

**Issue by ting2** [acgotaku/BaiduExporter#109]
這幾天用ARIA2 RPC 下載都出了下面的訊息，是不是我的設定上出錯了?
使用CHROME, EXTENSION也更新了,ARIA2版本是aria2-1.19.0

2016-01-02 23:52:16.803197 [ERROR] [AbstractCommand.cc:350] CUID#11 - Download aborted. URI=http://d.pcs.baidu.com/file/98dc4e67dce859c32253f31ffbc6a4b7?fid=893029987-250528-121947131083461&time=1451749917&rt=sh&sign=FDTAERVY-DCb740ccc5511e5e8fedcff06b081203-AhmvX7632af1v0qFY4k70LyP6E0%3D&expires=8h&chkv=1&chkbd=0&chkpc=et&dp-logid=46255981051042424&dp-callid=0&r=916641294
Exception: [AbstractCommand.cc:350] errorCode=22 URI=http://hk02ntt01.baidupcs.com/file/98dc4e67dce859c32253f31ffbc6a4b7?bkt=p3-0000d2055a0f80e3bf7f270a3333b7bfdab5&fid=893029987-250528-121947131083461&time=1451749917&sign=FDTAXGERLBH-DCb740ccc5511e5e8fedcff06b081203-Mbn8Rnq1fCSeGH6dUdVlcradQvg%3D&to=khtt&fm=Nan,B,U,on&sta_dx=463&sta_cs=33&sta_ft=mkv&sta_ct=0&fm2=Nanjing02,B,U,on&newver=1&newfm=1&secfm=1&flow_ver=3&pkey=0000d2055a0f80e3bf7f270a3333b7bfdab5&sl=78184526&expires=8h&rt=sh&r=916641294&mlogid=46255981051042424&vuk=3646224352&vbdid=-&fin=%E3%80%90DYZ%E5%AD%97%E5%B9%95%E7%BB%84%E3%80%91160101%20%E6%96%B0%E6%98%A5%20zip%EF%BC%81%EF%BC%88%E4%B8%AD%E6%96%87%E5%AD%97%E5%B9%95%EF%BC%89.mkv&slt=pm&uta=3&rtype=1&iv=0&isw=0&dp-logid=46255981051042424&dp-callid=0.1.1
  -> [HttpSkipResponseCommand.cc:228] errorCode=22 The response status is not successful. status=403

**Comment by iopop** [comment]
同上，而且用d.pcs.baidu.com或者www.baidupcs.com替换，显示host:bj.baidupcs.com 还有qd2.cache.baidupcs.com最慢

**Comment by ting2** [comment]
我也試過重置...但還是不行呀

**Comment by iopop** [comment]
可能需要在合适的时间段吧，重置后速度恢复了

**Comment by acgotaku** [comment]
@ting2 你这是下载一般出错了 还是导入进去直接不能下载?

**Comment by ting2** [comment]
@acgotaku 导入进去直接不能下载

**Comment by acgotaku** [comment]
@ting2 是自己网盘 还是分享页面? 所有文件都这样?

**Comment by luokar** [comment]
同是香港同胞啊。最近百度香港cdn十分不穩定，晚上10點後別想下載東西了，同時還有各種古怪現象:不能轉存，目錄刷不出來，file total length is 0。

**Comment by acgotaku** [comment]
如果真是地区问题就好了 我这边使用没啥问题

**Comment by ting2** [comment]
@acgotaku 分享頁面....所有文件都是這樣....以前成功下載的....現在也是出ERROR

**Comment by acgotaku** [comment]
@ting2 网盘主页面 没事的是么?

**Comment by ting2** [comment]
@acgotaku ..沒事....
無論是自己网盘 还是分享页面，按導出下載的時候，都會有"下載成功!趕緊去看看"的字樣
但在Aria就是出error

**Comment by acgotaku** [comment]
@ting2 你这话有点矛盾啊 自己网盘到底是好 还是坏啊 == 你用文本命令行的格式试试

**Comment by ting2** [comment]
@acgotaku 
.......都不好.......= =
用文本命令行的格式..(<--電腦小白...我不懂...T^T)

**Comment by acgotaku** [comment]
@ting2 现在还是不好么？ 我这边倒是一直正常。。。 

你可以把那个 导出下载的 文本贴出来 我在这边 终端里面测试测试

**Comment by ting2** [comment]
@acgotaku 

還不行......

http://pan.baidu.com/s/1geco1Zd
密码：g8lr

**Comment by lxlw1320** [comment]
@acgotaku 我这也是这样，下载成功率有点低，有些一开始就失败了，有些下一会也失败了，失败原因都是下载出错 HTTP 请求头错误或者无效.我把Log全拷出来了，能帮我看下吗。

**Comment by acgotaku** [comment]
@ting2 虽然一开始解析慢了点 但还是可以下载啊  == 是不是你网络状况问题?

@lxlw1320 LOG基本没意义 不如把文件分享出来看看 有些可能是文件本身的问题

**Comment by lxlw1320** [comment]
@acgotaku  问题主要是有些文件也不是每次都下不下来，这点比较纠结。
http://pan.baidu.com/s/1pKacEIf  zf6m 试试这个。。我试了好多次 要不然一开始就失败了，不然就是下没到100%就夭折，下不到100%这个是什么原因呢。。这个比较纠结。。有没办法自动删除未完成的任务。。到后面找失败的任务好麻烦。。

**Comment by acgotaku** [comment]
@lxlw1320 不可能完美的 下载失败 你就再导入一遍 成功的下载程序会直接跳过的 就这么简单 没有完美解决方案

**Comment by lxlw1320** [comment]
@acgotaku 就是失败的文件可以直接续传是

**Comment by acgotaku** [comment]
@lxlw1320 当然可以了 要不然用 aria2c有何意义

**Comment by lxlw1320** [comment]
@acgotaku 那像我刚刚发的那个一开始下载就失败的是文件有问题吗

**Comment by acgotaku** [comment]
@lxlw1320 文件本身没问题 我是可以正常下载的 失败了就重新导入就是了

**Comment by lxlw1320** [comment]
@acgotaku 这个文件我还没成功下载过。。每次都直接失败

**Comment by acgotaku** [comment]
@lxlw1320 我只能说是人品问题了么....

**Comment by lxlw1320** [comment]
@acgotaku T....T 能借点rp不

**Comment by lxlw1320** [comment]
@acgotaku 还有个问题呢，就是我最近批量下整个文件夹的文件的时候，aria2经常会挂掉，这个是aria的问题么

**Comment by lxlw1320** [comment]
@acgotaku 我试了一下，如果是新的文件夹 aria是正常的，但是如果我下一个之前下过但是有出错文件的文件夹内容aria2就会挂掉呢。。这个是在aria在启动续传的时候有问题吗
