### ISSUE TITLE
这几天突然不能用了，CORE没有定义……

### ISSUE THREAD

**Issue by sym233** [acgotaku/BaiduExporter#110]
chrome-extension://mjaenbjdjmgolhoafkohbhhbaiedbkno/js/share.js:11 Uncaught ReferenceError: CORE is not defined

//chrome47-64bit win10
插件的版本是0.6.1

**Comment by acgotaku** [comment]
@sym233 这种情况 刷新下基本可以解决 因为 JS加载的太快了....

**Comment by sym233** [comment]
orz……

**Comment by acgotaku** [comment]
@sym233 刷新是否能解决问题?

**Comment by sym233** [comment]
有点看人品啊

**Comment by acgotaku** [comment]
@sym233 很大情况都没问题啊 我基本上遇不到连续刷新两次还不出现的

**Comment by HerringtonDarkholme** [comment]
@acgotaku 可以通过打包 js 解决这个问题啊

**Comment by acgotaku** [comment]
@HerringtonDarkholme JS打包肯定可以搞定啊 但是又得折腾一堆前端工具好麻烦。。。（还是我太懒

**Comment by HerringtonDarkholme** [comment]
@acgotaku If the code is left for legacy, packaging/transpiling is indeed worthless.

**Comment by acgotaku** [comment]
@HerringtonDarkholme 快告诉我正确的姿势~
