### ISSUE TITLE
关于批量转存功能

### ISSUE THREAD

**Issue by Explorare** [acgotaku/BaiduExporter#111]
可以参考这个实现
[全新贪婪版#百盘度批量转存JS脚本 ～ 保持目录结构/差分/破5千限制/专辑/文件夹转存 - E-INK - Geek Talks · 奇客怪谈 - Hi!PDA Hi!PDA](http://www.hi-pda.com/forum/viewthread.php?tid=1745009)
亲测好用

**Comment by acgotaku** [comment]
这个屌啊 看来是花时间研究的了  你居然也逛 hi坛!

**Comment by Explorare** [comment]
版友推荐的

**Comment by acgotaku** [comment]
@Explorare 不过想注册个帐号都难... 嘛 这个实现还是超级用心的 连重试都有

**Comment by Explorare** [comment]
而且最重要的分步转存也实现了，实测可突破 500 转存限制。

**Comment by acgotaku** [comment]
好的 有空我来研究研究 差分转存是只保存没有的?

**Comment by Explorare** [comment]
应该是第一次执行会遍历建立本地缓存，然后记录文件的保存状态。

**Comment by acgotaku** [comment]
明白了 今天比较晚了 就不折腾 了

**Comment by Explorare** [comment]
辛苦了

**Comment by acgotaku** [comment]
@Explorare 这个的差分功能不是很完美? 我删了一个子文件夹 貌似检测到有主文件夹便跳过了...

**Comment by Explorare** [comment]
差分不是检测你的文件夹，而是已转存列表。

**Comment by acgotaku** [comment]
@Explorare 这个意思啊 不过这个线程池的实现很有意思 保证并发不会过多 学习到了 这个程序的思路

**Comment by acgotaku** [comment]
@Explorare 你有没有一个文件夹下 超过 5000文件的 分享测试用例?

**Comment by Explorare** [comment]
[高清书画_免费高速下载|百度云 网盘-分享无限制](http://yun.baidu.com/s/1o6wlZtg#path=%252F)
[百度云 网盘-yanhu831的分享](http://pan.baidu.com/share/home?uk=2214641459&view=share#category/type=0)

**Comment by acgotaku** [comment]
@Explorare 怎么又是这一个... 我说的指得是没有子文件夹 就是一个文件夹下5000以上的文件 不带文件夹

**Comment by Explorare** [comment]
这个没有。

**Comment by acgotaku** [comment]
@Explorare  4w粉丝 吓尿....

**Comment by fzhw88** [comment]
请问还有计划实现批量转存功能吗？楼上提供的Hi-Pda论坛的那个脚本已经失效了。

**Comment by acgotaku** [comment]
这个功能本来就不在计划内 新版本升级之后 我也没在测试了
