### ISSUE TITLE
通过局域网代理上网的，能否使用？

### ISSUE THREAD

**Issue by sishentibu** [acgotaku/BaiduExporter#116]
通过你的blog找到这里的，不知道发到这里是否合适。

win7 32位，在局域网中，通过代理才能上外网
同样的配置，在普通网络能用，但在代理上网的条件下，就无法下载了
Aria2 的代理是怎么设置的？我在webui中找到代理的设置，但设置了后还是不行。。

**Comment by halfu** [comment]
需要配置aria2c的启动参数，具体请参考https://aria2.github.io/manual/en/html/aria2c.html

On Thu, Jan 14, 2016 at 12:25 PM sishentibu <notifications@github.com>
wrote:

> 通过你的blog找到这里的，不知道发到这里是否合适。
>
> win7 32位，在局域网中，通过代理才能上外网
> 同样的配置，在普通网络能用，但在代理上网的条件下，就无法下载了
> Aria2 的代理是怎么设置的？我在webui中找到代理的设置，但设置了后还是不行。。
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/acgotaku/BaiduExporter/issues/116>.
>
-- 

--
周维
18602430237

**Comment by sishentibu** [comment]
@halfu 这个貌似不是win下的。
看了下，应该是这一段
<a href='http://tietuku.com/89053f5c39e30555'><img src='http://i4.tietuku.com/89053f5c39e30555.png'></a>
我参照这个，写到 .conf文件中，直接就启动不了了。。。
基本配置是参照 http://bbs.kafan.cn/thread-1686205-1-1.html 写的

有没有win下的教程？

**Comment by halfu** [comment]
应该是平台无关的。
你可以尝试开启debug看看日志，检查一下是否是配置文件写的不正确。

On Thu, Jan 14, 2016 at 5:38 PM sishentibu <notifications@github.com> wrote:

> @halfu <https://github.com/halfu> 这个貌似不是win下的。
> 看了下，应该是这一段
> <http://tietuku.com/89053f5c39e30555>
> 我参照这个，写到 .conf文件中，直接就启动不了了。。。
> 基本配置是参照 http://bbs.kafan.cn/thread-1686205-1-1.html 写的
>
> 有没有win下的教程？
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/acgotaku/BaiduExporter/issues/116#issuecomment-171586387>
> .
>
-- 

--
周维
18602430237

**Comment by acgotaku** [comment]
@sishentibu 代理的话 很大问题是  你的 aria2c的地址 是不是公网地址 如果内网地址 被转发出去了 就肯定错误的 所以 你干嘛搞这么复杂的网络环境。。。。

**Comment by sishentibu** [comment]
@halfu 这个，不会。。。刚开始用这个

**Comment by sishentibu** [comment]
@acgotaku 这个是公司网络这样啊，我也没办法选择啊。。

**Comment by acgotaku** [comment]
@sishentibu 老板的意思就是让你好好上班啊(   而且你也没说明你代理的具体方式啊 端口代理? 全局 VPN?
还有你 aria2c的使用方式  rpc模式 命令行模式? 无法下载 是 无法导入进 aria2c 还是导入之后下载没速度
详细描述下....

**Comment by sishentibu** [comment]
只是上网方式使用代理而已了
局域网代理，使用的是ccproxy。 代理方式是http代理，端口808
使用方式是使用rpc模式。配置基本是按照这个来的。http://bbs.kafan.cn/thread-1686205-1-1.html
无法下载的时候，在webui中能看到下载列表了。但是右上角会弹出个提示，说什么没连接上。具体提示要明天才能试试了。（aria2 是已经启动了的）

2016-01-15 

sishentibu1 



发件人：雪月秋水 <notifications@github.com>
发送时间：2016-01-15 18:17
主题：Re: [BaiduExporter] 通过局域网代理上网的，能否使用？ (#116)
收件人："acgotaku/BaiduExporter"<BaiduExporter@noreply.github.com>
抄送："sishentibu"<sishentibu1@163.com>

@sishentibu 老板的意思就是让你好好上班啊( 而且你也没说明你代理的具体方式啊 端口代理? 全局 VPN?
还有你 aria2c的使用方式 rpc模式 命令行模式? 无法下载 是 无法导入进 aria2c 还是导入之后下载没速度
详细描述下....

**Comment by acgotaku** [comment]
@sishentibu CCProxy这个软件就有监控所有流量的功能 老板可以随时切断你的任何连接  你还是死心吧

**Comment by sishentibu** [comment]
@acgotaku 我用浏览器下载可以的啊，只是最近百度云用浏览器下载也有问题，用管家速度也不行（除非用破解版）
我这没限制上网。只是上网的方式是用的cc。。。还有限了p2p，另外的http下载之类的可以的

**Comment by acgotaku** [comment]
@sishentibu 那你试试直接命令行下载可以不?

**Comment by sishentibu** [comment]
@acgotaku 这个，抽时间试试吧
刚才是了下百度云下载，导出了十几个文件之后，就开始谈验证码，然后就不能下载了（一个文件夹中有几千个文件），这个有解决办法没？

**Comment by acgotaku** [comment]
@sishentibu 转存到自己网盘再下载 不会出验证码

**Comment by sishentibu** [comment]
@acgotaku 好的。
但是还有个另外问题，普通账号一次好像只能是2000？超了的时候这个有办法一次性转过去吗？

**Comment by acgotaku** [comment]
https://github.com/acgotaku/BaiduExporter/issues/111
你先用这个脚本 之后我会移植到插件上

**Comment by sishentibu** [comment]
@acgotaku 好的 ，先谢谢了
