### ISSUE TITLE
Safari和firefox版导出时，文件名会截断。

### ISSUE THREAD

**Issue by giveup** [acgotaku/BaiduExporter#117]
原文件名：SW_DVD5_Office_Mac_Standard_2016_MultiLang_-3_.ISO_MLF_X20-52736.ISO
导出后：5_Office_Mac_Standard_2016_MultiLang_-3_.ISO_MLF_X20-52736.ISO 
查看导出链接时， 5\_Office\_Mac\_Standard\_2016\_MultiLang\_\-3\_\.ISO\_MLF\_X20\-52736\.ISO
进一步测试发现，当文件名比较长时就会出现文件名不完整的情况。
另外问下，现在主要维护的是chrome版么？ff和Safari都比较老旧了。

**Comment by acgotaku** [comment]
@giveup chrome没问题? 因为我平时都是用chrome啊 所以主要维护的肯定是chrome 话说可以把那个文件分享出来 我试试么?

**Comment by Cee** [comment]
@giveup Safari 现在是 0.5.9 功能上不会有很多区别
我这里下载长文件也没有什么问题...

**Comment by giveup** [comment]
@Cee 
链接：http://pan.baidu.com/s/1sjIfqyD
密码：avw0


＃aria2c -c -s10 -k1M -x10 -o 5\_Office\_Mac\_Standard\_2016\_MultiLang\_\-3\_\.ISO\_MLF\_X20\-52736\.ISO --header "User-Agent: netdisk;5.3.4.5;PC;PC-Windows;5.1.2600;WindowsBaiduYunGuanJia"  --header "Referer: http://pan.baidu.com/disk/home"  --header "Cookie: BDUSS=E2SllqNXloeUxCN0xCM0VhWWtidUUzV0JreWRqWjZOa1pxZ2g1UVFpTm9KcnRXQVFBQUFBJCQAAAAAAAAAAAEAAAB~p6UHztJZtcS-zcrHsNez1QAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGiZk1ZomZNWQm;BAIDUID=52E21933CC55D3BE96B37D158539F3B0:FG=1"  "http://d.pcs.baidu.com/file/6777abcad68dc38fbecab287ba77f296?fid=2802004346-250528-1096719038474586&time=1452846219&rt=pr&sign=FDTAER-DCb740ccc5511e5e8fedcff06b081203-A8fNKNKOkcwyrqQLaM2NZFSL6XE%3d&expires=8h&chkbd=0&chkv=0&dp-logid=340542226989723962&dp-callid=0&r=373485703"＃

**Comment by Cee** [comment]
@giveup 这个我下载很正常
![screenshot](https://cloud.githubusercontent.com/assets/5436953/12348761/190e5f4a-bba5-11e5-9088-0ae28dd45255.png)

**Comment by giveup** [comment]
@Cee 补充下，如果保存到自己空间再下载，就会出现文件名截断的情况。
我也是刚发现....

**Comment by Cee** [comment]
@giveup 我在自己里面也没有任何问题...
