### ISSUE TITLE
小白求助一下= =

### ISSUE THREAD

**Issue by DeveloperZhou** [acgotaku/BaiduExporter#118]
我将conf文件配置到/root/Documents/aria2.conf。然后在Terminal 中使用

```
aria2c --conf-path=/root/Documents/aria2.conf
```
弹出
```
[WARN] Neither --rpc-secret nor a combination of --rpc-user and --rpc-passwd is set. This is insecure. It is extremely recommended to specify --rpc-secret with the adequate secrecy or now deprecated --rpc-user and --rpc-passwd.

01/17 13:20:40 [NOTICE] IPv4 RPC: listening on TCP port 6800

01/17 13:20:40 [NOTICE] IPv6 RPC: listening on TCP port 6800
```

然后在浏览器中修改了下载的绝对路径，然后再选择文件选择`ARIA2 RPC`。然后在终端显示出

```
01/17 13:21:30 [ERROR] CUID#9 - Download aborted. URI=http://d.pcs.baidu.com/file/319d9c560e8973eec6a22ef0e988989d?fid=3610213317-250528-681331536732832&time=1453008091&rt=pr&sign=FDTAER-DCb740ccc5511e5e8fedcff06b081203-dZz56JNbxe3%2fKX2Ko1bXB9cJxQc%3d&expires=8h&chkbd=0&chkv=0&dp-logid=383994268027004944&dp-callid=0&r=431040169
Exception: [AbstractCommand.cc:869] errorCode=1 Failed to establish connection, cause: Connection refused

01/17 13:21:30 [NOTICE] Download GID#f6db8bca9d5679dc not complete: D:\Downloads/梦的解析.pdf
```

然后使用`ctrl + c`关闭线程。出现

Download Results:
gid   |stat|avg speed  |path/URI
======+====+===========+=======================================================
f6db8b|ERR |        n/a|D:\Downloads/梦的解析.pdf

－－－－

我不知道是遗漏了什么。所以来求助一下。

谢谢

**Comment by acgotaku** [comment]
@DeveloperZhou 那个 WARN是正常的 因为没加密而已 忽略即可 下载错误就奇怪了 你试试直接命令行?

**Comment by DeveloperZhou** [comment]
还有一个问题就是进入百度界面后。需要较长时间才能加载完毕，并且出现了插件没有显示在正确位置的情况。这个我用的是`Version 47.0.2526.106 (64-bit)`。不知是不是浏览器的问题还是百度的问题或者是我网络的问题。哈哈哈..

然后就是我再试一下。刚才没加载出来

**Comment by acgotaku** [comment]
@DeveloperZhou 能给个截图么....

**Comment by DeveloperZhou** [comment]
然后就是刚才又试了一下。现在是OK的。我猜想是一开始默认设置的是在WINDOWS下面的。然后在LINUX下面没有在找到盘符导致的错误。恩。现在OK了。

谢谢开发者啦。

在G+上关注你了。飘过－－－－－－－－－－

**Comment by DeveloperZhou** [comment]
然后我又试了一下插件的加载。应该是初始化的问题。第一次初始化会拖慢一些速度。但是第二次或者后面就不会问题了。

还是很好用哒。

**Comment by acgotaku** [comment]
@DeveloperZhou 好吧 你的G+ ID ?  用Linux居然还小白.... 囧

**Comment by DeveloperZhou** [comment]
我Google+用的少（好吧几乎没用过多少<https://plus.google.com/u/0/103016528399701338815/posts>

用linux本来就很白啊。我现在开机有的时候出现那个noneavu还是啥的，（google说是显卡的问题）然而我的解决方法是强制关机重启。Haha。囧= =

最近在学习拉，那个bcloud那个软件作者在reborn所以一直在找下载的。然而我使用这个导出的http拉到下载器里面下载只有5kB。。。。然后我就蒙了= =。。。。。

向大大学习。LOL
