### ISSUE TITLE
Firefox 版的 0.6.0的xpi好大，打开发现嵌套打包了

### ISSUE THREAD

**Issue by Cye3s** [acgotaku/BaiduExporter#119]
也就是xpi里打包了个xpi，里面的那个xpi又打包了个xpi.....
另外Firefox 44 签名问题，看看用这个行不，也不用提交新版到amo去
https://blog.mozilla.org/addons/2015/12/18/signing-firefox-add-ons-with-jpm-sign/

**Comment by acgotaku** [comment]
@Cye3s 这个已经解决了
