### ISSUE TITLE
插件已经安装，但是打开百度网盘，没有见到按钮.

### ISSUE THREAD

**Issue by zw963** [acgotaku/BaiduExporter#121]
火狐版本 43.

插件已正常安装，在工具栏也可以看到那个小伞，但是点击那个小伞，
进入百度网盘，我的设备那里并没有看到任何新增的按钮。
(仅有推送任务列表和添加设备两项)

**Comment by zw963** [comment]
难道我什么地方搞错了？ 为什么我在应用商店安装了 Chrome 版本，仍旧看不到？

忘记说了，我用 Linux 系统, 非 Windows 用户。

**Comment by zw963** [comment]
好吧，貌似需要初始化好久那个按钮才能出来，就像不翻墙，访问某些 google 服务似的。

请问这是正常的行为吗？

**Comment by acgotaku** [comment]
@zw963 这取决于你的网络状况 必须在网页加载完毕才能加载插件  所以你网络差 初始化就慢
这是没有办法的事情  因为插件本身依赖于网页 不能提前载入

**Comment by zw963** [comment]
明白了，非常感谢。
