### ISSUE TITLE
火狐扩展中心的版本，安装之后重启才能生效，刷新页面没用，只有我有这种现象吗？

### ISSUE THREAD

**Issue by yilksd** [acgotaku/BaiduExporter#122]

**Comment by Cee** [comment]
安装完打开新页面即生效。

**Comment by yilksd** [comment]
@Cee 我这里刷新原页面，打开新的百度网盘页面都不会生效，只有重启才能生效。你那里能够打开新页面即生效？那么可能是我自己的问题了

**Comment by acgotaku** [comment]
@yilksd 那你就重启呗 重启一下又能花多少时间呢,..... 这和软件没有啥关系吧....

**Comment by Cee** [comment]
@yilksd Yep. 
Firefox Developer Version 45.0a2 (2016-01-14)
检查一下你的版本，或者重装试一下。
