### ISSUE TITLE
aria2还是有必要加密吧

### ISSUE THREAD

**Issue by yilksd** [acgotaku/BaiduExporter#123]
“只是在自己电脑上使用的话,没必要启用任何加密方式”？
不加密的话，网页不是也有权限访问aria2 rpc了？虽然一般不会有网页这么去做，但总归是个漏洞

**Comment by Cee** [comment]
Not related to BaiduExporter. @acgotaku

**Comment by acgotaku** [comment]
@yilksd 那不关我事情啊 你觉得不爽 你开启加密就是了啊.....
