### ISSUE TITLE
百度云管家可以下载，可以在线播放，但是生成的下载链接不可用。

### ISSUE THREAD

**Issue by zw963** [acgotaku/BaiduExporter#124]
个别文件存在这个情况，如果拷贝下载命令出来, 在 Terminal 调用 aria2c 执行, 会发现下载百分之始终为 0, 而所需时间会一直往上加。反复几次之后，最后报错退出。

该文件在云中可以在线播放，通过官方客户端（wine  下模拟) 可以下载（虽然很慢）.

不是所有的文件都这样，可能下载一个目录，仅仅目录下某个文件如此。

谢谢。

**Comment by Cee** [comment]
提供一下具体的文件。

**Comment by zw963** [comment]
请问我该如何提供？ 是不是直接把生成的下载链接贴出到这里？

我刚刚又测试了下 https://github.com/oott123/bpcs_uploader 这个插件, 发现我自己传上去的文件可以下载，但是出问题的那个文件，下载速度总是 0 kb， 我怀疑是这个文件的问题。

该文件其实是一个外链，来自于其他人的分享。

**Comment by Cee** [comment]
@zw963 对
建议转存后使用。

**Comment by zw963** [comment]
我已经转存了， 这些文件，已经是我的网盘下的私有文件，只不过这些文件不是我传上去的
是从别人的分享那里转存过来的。

是一些视频，当然我很奇怪，一大堆视频文件， 大部分都下载下来了，唯独其中一个文件，各种途径无法下载。
(包括 wine 下官网客户端，下载到 80% 不动了)

**Comment by Cee** [comment]
@zw963 无法分享吗？

**Comment by zw963** [comment]
文件本身没啥了。 只是不确定链接中是否包含什么信息 ...

```sh
aria2c -c -s10 -k1M -x10 -o 339\_\爽\_\浅\谈\诗\词\格\律\(\三\)\辙\韵\.flv --header "User-Agent: netdisk;5.3.4.5;PC;PC-Windows;5.1.2600;WindowsBaiduYunGuanJia"  --header "Referer: http://pan.baidu.com/disk/home"  --header "Cookie: BDUSS=FNTeE81Q0VNVTFjUk1uUktRT2dOV2xRdG0tSnRwcWZqMjlubHJWLTRHcnptOGxXQVFBQUFBJCQAAAAAAAAAAAEAAABEOm4Aenc5NjMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPMOolbzDqJWd;BAIDUID=27CFC7E7D14D2C074BB7E469BC68C5AD:FG=1"  "http://d.pcs.baidu.com/file/d6ae3b97df1f1779d68ab440bea52f86?fid=973343409-250528-217018942011606&time=1453552179&rt=pr&sign=FDTAER-DCb740ccc5511e5e8fedcff06b081203-LK1Xm7d%2f1fdtM6Xr0aYwd1puv5g%3d&expires=8h&chkbd=0&chkv=0&dp-logid=530046971706860366&dp-callid=0&r=113524481"
```

谢谢。

**Comment by zw963** [comment]
我提供的信息仍然不够？

**Comment by acgotaku** [comment]
@zw963 建议提供源文件  因为下载链接只有8小时的有效期。。。 现在已经无效了。。。

**Comment by zw963** [comment]
不明白啊，我下载不下来，怎么提供源文件给您？

**Comment by acgotaku** [comment]
@zw963 网盘分享不可以么？

**Comment by zw963** [comment]
好吧， 非常抱歉， 终于明白你的意思了， 没想到中文沟通还这么困难， 呵呵.

你太高估我对云盘的认识了， 虽然我用过别人的分享， 但是自己还没创建过分享呢。

http://pan.baidu.com/s/1bt5wlC

**Comment by zw963** [comment]
晕， 前几天家里停暖气， 去丈母娘家住了几天， 那边移动的网络， 试了很多次都没有下载下来。

现在在家， 网通的网络， 刚刚试了下， 一次下载成功， 看样子是网络问题。 

非常感谢提供这么好的软件！！
