### ISSUE TITLE
Chrome版扩展，ARIA2 RPC 导出下载无效

### ISSUE THREAD

**Issue by AlwaysWithYou** [acgotaku/BaiduExporter#127]
Chrome扩展0.6.2在分享专辑页面上导出ARIA2 RPC下载没反应，如：http://yun.baidu.com/pcloud/album/info?uk=3457111272&album_id=140584661652393648
控制台提示：Uncaught TypeError: self.generateParameter is not a function
火狐版扩展0.6.0可以导出aria2 rpc下载，但是选中4个文件后，下载的都是第一个文件
Firefox 版本 43.0.4，32位；Chrome 版本 48.0.2564.97 (正式版本) （32 位）

**Comment by acgotaku** [comment]
@AlwaysWithYou 你这个专辑都不存在了吧...

**Comment by AlwaysWithYou** [comment]
@acgotaku 刚才右括号“）”也被识别成链接的一部分了……已更正

**Comment by acgotaku** [comment]
@AlwaysWithYou FF已经重新打包  chrome已经修复 等我之后版本更新 现在可以使用开发者模式载入最新的

**Comment by AlwaysWithYou** [comment]
@acgotaku 感谢修复！！

**Comment by AlwaysWithYou** [comment]
@
