### ISSUE TITLE
可能解决限速的方法

### ISSUE THREAD

**Issue by giveup** [acgotaku/BaiduExporter#129]
来源 http://mromm.wodemo.net/entry/376090

> pcs.baidu.com/rest/2.0/pcs/file?method=download&app_id=266719&path=

> 只能下载自己网盘目录下的文件，不限速，支持https，支持分段下载，支持断点重连

>该方法想扩散转载就扩散转载吧，已经有备用id了←_←

>127.0.0.1:59777/pcs/百度ID@pcs/files/

>在手机上使用时，可以在打开es后使用这个端口试试

>黑科技好用，不过扩散会有被封杀的可能

**Comment by acgotaku** [comment]
@giveup 我现在的 方法本来就不限速啊   ==

**Comment by giveup** [comment]
@acgotaku 会限....ua欺骗好像没什么用。
一般都是200～300kb／s

**Comment by acgotaku** [comment]
@giveup 为啥我的下载一直都是 1-2m ....

**Comment by Willian-Zhang** [comment]
這個問題同樣存在，希望增加會員登錄的標準指導（例如Cookie？）

**Comment by acgotaku** [comment]
@Willian-Zhang 会员登录啥意思?

**Comment by giveup** [comment]
@acgotaku 意思就是在下载时加入百度云会员的cookies,这样百度云就不会限速

**Comment by acgotaku** [comment]
@giveup 本来就已经加入的了啊

**Comment by Twilight** [comment]
我这里用16线程下到2~3M/s, 改到64线程能跑满百兆
