### ISSUE TITLE
可不可以让设置长久保存？

### ISSUE THREAD

**Issue by yilksd** [acgotaku/BaiduExporter#132]
目前只要清cookie，aria2 rpc 和下载路径设置就会丢失。我设置了退出时清除cookie, 这样每次都要重设一遍这两项了。作为一个浏览器扩展，还是让设置保存不依赖于cookie比较好吧？

**Comment by acgotaku** [comment]
@yilksd 不是 我存的是 localStorage 你可以开启同步试试 我没依赖  cookie

**Comment by yilksd** [comment]
刚试过，在firefox里，在选项-> 隐私中移除cookie的同时也会移除localstorage。localstorage 同样是网页存储内容的地方，扩展还是用扩展的方式保存设置较好吧？

**Comment by acgotaku** [comment]
@yilksd 那请问 什么是 扩展的保存方式?

**Comment by HarukaMa** [comment]
https://developer.mozilla.org/en-US/Add-ons/SDK/High-Level_APIs/simple-storage

Like this?

iPhoneから送信

H28/02/17 10:07、雪月秋水 <notifications@github.com> のメッセージ:

**Comment by yilksd** [comment]
https://developer.mozilla.org/en-US/Add-ons/SDK/High-Level_APIs/simple-prefs
可能是这个？

**Comment by acgotaku** [comment]
@yilksd 这个是 FF的独有方式... 我的扩展首先适配Chrome 然后兼容FF....

这样开发我会很困扰的啊
