### ISSUE TITLE
aborted by software in host machine

### ISSUE THREAD

**Issue by librix** [acgotaku/BaiduExporter#136]
chrome 48.0.2564.116 m
无防火墙，杀毒软件comodo；
两台路由器。
电脑提示[socketcore.cc:794] error code = 1,failed to receive data, cause: An established connection was aborted by the softwere in your host machine.，百度云无法下载……请问该怎么处理？

**Comment by acgotaku** [comment]
@librix 刚才测试了一下 下载没有问题 应该是你的网络原因导致的吧

**Comment by acgotaku** [comment]
@librix  话说你确定 真的是 softwere 而不是 software ?!

**Comment by librix** [comment]
???????????????????

?????????????????????????????????????????????

???????????????????????
Sent from ?(?_?)?

**Comment by acgotaku** [comment]
@librix  WTF?!!!
