### ISSUE TITLE
能不能支持配置参数

### ISSUE THREAD

**Issue by Twilight** [acgotaku/BaiduExporter#138]
在RPC URL里以Query String的方式指定, 比如http://localhost:6800/jsonrpc?max-connection-per-server=5

这样我加几个配置之后就可以比较自由的选择使用单线程下载还是五线程下载, 界面上也基本不用改

其实我本来想改了给你pull requests的, 不过看了一下你的结构真的比较乱...

**Comment by acgotaku** [comment]
@Twilight 你直接在 conf里面写 不就好了

**Comment by Twilight** [comment]
起多个aria2么...

**Comment by acgotaku** [comment]
@Twilight 我改起来更不方便........

**Comment by Twilight** [comment]
好么pull request已发

**Comment by acgotaku** [comment]
@Twilight 你这个变量名起的... 有时间我再改好了...

**Comment by Twilight** [comment]
啥变量名

**Comment by acgotaku** [comment]
@Twilight 函数的传入参数名 细节问题而已

**Comment by Twilight** [comment]
这种作用域非常小的变量我通常取这种名字, 给这想名字毫无意义...

你的结构方面的问题比方说三个平台大部分相同的代码居然就拷贝三份, 不同页面的也有很多重复的代码.

**Comment by acgotaku** [comment]
@Twilight 当初无限迭代的结果 代码还不够好...

**Comment by acgotaku** [comment]
@Twilight 你妹的 有的代码有 BUG 等我有时间再调 我说怎么下载不了文件了

**Comment by Twilight** [comment]
什么bug? 我这里测过几个文件

**Comment by acgotaku** [comment]
@Twilight RPC地址默认值 直接不能获取文件URL 闹哪样

**Comment by acgotaku** [comment]
@Twilight  core.js 的 70行  auth_str 哪里来的 都没见到赋值

**Comment by Twilight** [comment]
没测不带token的情况呗，多大个事儿

**Comment by acgotaku** [comment]
@Twilight 多大个事 也没见你修复 我还是自己来吧

**Comment by Twilight** [comment]
我fork的那个repo在pull request之后已经删掉了
