### ISSUE TITLE
提早插件加载的时间

### ISSUE THREAD

**Issue by fyears** [acgotaku/BaiduExporter#140]
问题：

我这里上百度网页比较慢，很多时候，尽管页面大部分已经加载完毕，但是 chrome 的 tab 上面依然有菊花在旋转。
![a](https://cloud.githubusercontent.com/assets/1142836/13345834/ea55d16e-dc16-11e5-8fa0-fafc1862788b.png)

而据我观察，这个插件似乎在页面完全加载完毕之后（菊花消失）才会载入。
并且有时候用了几分钟超时了，tab 的菊花消失了，插件也不会载入了。

请问能够改善插件加载的时间方式吗？

能否复现：
使用了代理插件加快网盘页面载入速度后，插件也顺利载入。

**Comment by fyears** [comment]
我又试验了一下，应该找到了问题所在和解决方法。

造成页面超时的主要原因是，页面试图不断连接 `http://127.0.0.1:10000/guanjia*`  而造成的（电脑并没有安装百度云盘管家）。

而使用代理插件时候，localhost 的资源全都自动断开，所以使用代理网页不会超时，插件顺利载入。

我在 adblock 里面添加了这个规则，插件顺利载入。

作者可以考虑在插件中加入屏蔽 ·http://127.0.0.1:10000/guanjia*` 连接的功能。

**Comment by alanwonder** [comment]
测试有效，谢谢分享

**Comment by 02015678** [comment]
测试有效，谢谢分享

**Comment by jiayiming** [comment]
http://127.0.0.1:1000*/guanjia*

**Comment by acgotaku** [comment]
@fyears 自己用 adblocker 屏蔽不久好了 我要屏蔽还得再申请权限 很不好
