### ISSUE TITLE
Firefox版本加載太慢了

### ISSUE THREAD

**Issue by gnhs** [acgotaku/BaiduExporter#142]
Firefox安裝了BaiduExporter的plugin之後，先在一個tab登入百度雲賬號
然後點選小降落傘（Visit Baidu Yun）頁面先是一片空白
要等十幾二十秒之後百度雲的頁面才會出現，再過一分多鐘以後
這個plugin的主功能按鍵“導出下載”才會出現，有時再過一分半都還不會出現。

是看到Closed issue裡面有人提過“插件已经安装，但是打开百度网盘，没有见到按钮. ”，
版主回應是說：“所以你网络差 初始化就慢
这是没有办法的事情 因为插件本身依赖于网页 不能提前载入”
我翻來覆去測試多遍，只能說這不太可能是網路的問題--
我一樣是FF43版，連網速是60mb/s--最簡單就拿同樣的百度雲主網頁來比較：
在FF工具欄按+新增一個空白網頁，然後貼上百度雲盤網址
http://pan.baidu.com/disk/home#list/path=%2F
這樣只要2、3秒網頁就更新完畢，但是等BaiduExporter插件初始化完成出現按鍵
一樣要至少要再等一分多鐘。

顯然這個插件本身初始化就要至少一分鐘，習慣了也沒什麼，提出來只是給版主參考，
也許代碼有地方可以優化。即使無法優化也可以在UI上做一些改進：
發現假如aria2沒有先啟動插件不會顯示“導出下載”的按鍵，
也許應該不論aria2有沒有先啟動，應該還是要先顯示“導出下載”的按鍵
再開始其他初始化的程序，只是讓ARIA2 RPC等到初始過程確定ARIA2已啟動才讓它激活。
另外就是我並沒有安裝YAAW，下載BaiduExporter的網頁說明說有支援YAAW，
所以不知道是不是因為沒有安裝YAAW，代碼一直在timeout偵測是否有YAAW，
等過了一分多鐘才放棄然後才終於顯示出“導出下載”的按鍵，
假如是這樣更好辦應該不難優化，畢竟這個插件主要只是導出下載資訊給ARIA2，
都是在本機的範圍，整個初始化根本不應該和網路有什麼關係。

**Comment by gnhs** [comment]
另外一個問題和另一位反映的Chrome插件一樣：在FF上開啟這個插件
大約三次會有一次“導出下載”完全不會出現

**Comment by acgotaku** [comment]
@gnhs  原因是FF对链接的处理机制  因为百度有个链接是需要很长时间加载的 Chrome的解决方案是先渲染整个页面 再等待这个链接  而 FF的机制是一直等待这个链接加载完毕或报错 所以导致加载会很慢
![2016-02-28-131623_1044x467_scrot](https://cloud.githubusercontent.com/assets/1191834/13377391/55b35f8c-de1d-11e5-8378-48237d5ad115.png)

**Comment by acgotaku** [comment]
@gnhs 你看到的那个 monitor.jpg 是用了判断最快的 CDN的节点的 所以肯定有加载失败的节点 在这个链接上 耗费了 大量时间

**Comment by gnhs** [comment]
原來如此，多謝說明。那個monitor.jpg檔兩個加載失敗的節點都是 cache.xxx的節點，即使沒有加載失敗，有的monitor.jpg檔也等了十幾、二十秒--根據度娘說要用ABP加一條過濾規則 **||*monitor.jpg?xcode**  就萬事OK--試了一下果然加了這一條ABP濾網在FF上開啟百度盤網頁就秒啟了，BaiduExporter的 “導出下載”按鍵也是立刻就出現不再會有加載（或初始化？）失敗的情形。不知道插件代碼是否可以優化，不過最起碼FF的問題是可以用ABP解決的，這個issue我先不關閉，版主認為應該關閉再留言告知。
![baiduyunpan](https://cloud.githubusercontent.com/assets/17516975/13378359/bc158f5e-de3e-11e5-9625-606fad5d8bdd.png)

**Comment by acgotaku** [comment]
@gnhs 那就用插件屏蔽嘛 毕竟这个功能牵涉到各种权限申请问题 我实现起来比较复杂  ==

**Comment by Twilight** [comment]
我觉得这个和#140一样你可以写在文档里作为tips, 这个issue可以close

**Comment by acgotaku** [comment]
@Twilight  已添加

**Comment by Twilight** [comment]
@acgotaku 建议加上到这两个issue的链接
