### ISSUE TITLE
下载失败，是不是没有开启aria2

### ISSUE THREAD

**Issue by caobinlight** [acgotaku/BaiduExporter#145]
chrome 0.6.6版本。
地址是设置好的（http://192.168.1.200:6800/jsonrpc），但无法下载。
导出地址后用yaaw是可以下的。

**Comment by acgotaku** [comment]
你有没有看这个？！ https://github.com/acgotaku/BaiduExporter/issues/128

你这样说我 也诊断不出来啊

**Comment by leitwolf** [comment]
我的也是这样，今天检测不到aira2了。
系统：win10
chrome:版本 49.0.2623.87 m (64-bit)
助手版本号：0.6.6
下面是控制台的一些信息：
![izyu8yfac db174iw 5sm3](https://cloud.githubusercontent.com/assets/1720546/13658633/db57fa32-e6b3-11e5-8bfa-763c354d1247.png)

**Comment by leitwolf** [comment]
我已经全部清过缓存，也卸载重装过了，还是不行。

**Comment by acgotaku** [comment]
@leitwolf 你这个是点测试连接出的问题？

**Comment by leitwolf** [comment]
先点下载，出现“下载失败，是不是没有开启aria2”，然后进入设置界面，点测试连接，出现“错误，请查看是否开启aria2”，应该是连接不到aria2了。我打开http://aria2c.com/是可以检测得到开启了aria2。

**Comment by srwgin** [comment]
同样显示获取地址失败 测试链接能显示版本号 清理过cookies 一样

**Comment by acgotaku** [comment]
@srwgin 给个截图 和 控制台的输出

**Comment by srwgin** [comment]
http://imgur.com/a/fsu1V

**Comment by acgotaku** [comment]
@srwgin 版本是 0.6.6??  网盘的网址告诉我 点 导出下载有问题么？

**Comment by srwgin** [comment]
OK 前面是0.6.5 现在更新过0.6.6后 能下了

**Comment by acgotaku** [comment]
@srwgin  有问题先自己检查看看 再来问。。。 大家时间都很宝贵。。。

**Comment by leitwolf** [comment]
我卸载掉0.6.6，重新安装了releases里的0.5.9版本可以用。。。
这样看起来应该是新版本引入新代码时产生的错误。

**Comment by acgotaku** [comment]
@leitwolf 那你还是用老的吧

**Comment by knightjun** [comment]
@acgotaku 我也出现同样的问题
0.6.4没问题，升级到0.6.6就出现这个问题了，现在release内的0.5.9版本可用

**Comment by leitwolf** [comment]
0.5.9会不断的升级，每次都要卸载重装，苦恼。。。

**Comment by wolfrost** [comment]
我这也是同样的问题，版本0.6.6

**Comment by acgotaku** [comment]
你们倒是说说怎么下载失败的？ 提供个截图也好啊

**Comment by wolfrost** [comment]
http://ww2.sinaimg.cn/large/40983e5ejw1f1srlpzrxmj20hd0f1jx8.jpg
http://ww2.sinaimg.cn/large/40983e5ejw1f1srmed7msj20i305t0t5.jpg
firefox上的0.6.0版可以正常加添下载。

**Comment by knightjun** [comment]
在设置页面点击检测按钮检测不到asia2

**Comment by ungrown** [comment]
> 你们倒是说说怎么下载失败的？ 提供个截图也好啊

我们很想提供详细信息，然而实在是没什么好提供的2333。
我这也是066无法下载，059正常使用，可惜它老是自动升级。
你问我066和059有何不同？嗯，除了aria2下载其他都一模一样。
要不趁此机会完善一下报错系统如何？

**Comment by moutian** [comment]
我在mac os x 10.9上，chrome，最新版的這個插件，提示失敗，問我是不是沒有打開aria2.  是最後這次升級後出現的新問題，原來很正常。

**Comment by acgotaku** [comment]
@ungrown https://github.com/acgotaku/BaiduExporter/issues/128 这个已经有详细说明了
你们倒是看看啊

**Comment by moutian** [comment]
請問“詳細說明”對應下邊哪條？

尝试安装最新版本插件
尝试清空浏览器缓存
尝试卸载插件后重新安装
发起 Issue 时，请最好提供：

您下载的内容地址
插件版本号，浏览器版本号，系统版本号
列举出现问题的详细步骤
描述能否复现问题

**Comment by acgotaku** [comment]
@moutian  您下载的内容地址
插件版本号，浏览器版本号，系统版本号
列举出现问题的详细步骤
描述能否复现问题

**Comment by indypan** [comment]
先謝謝 acgotaku 提供如此好用的插件。
我也有同樣的問題，確實是升級 0.6.6 版之後才發生的。連接不到 aria2c server。
YAAW 差件連接得到 aria2c server.

系统：win10
chrome:版本 49.0.2623.87 m (64-bit)
助手版本号：0.6.6

是否因為 aria2c 在另外 server ，不是在 localhost 的關係？

**Comment by indypan** [comment]
還有建議把 user-agent 改成 netdisk;5.2.6;PC;PC-Windows;6.2.9200;WindowsBaiduYunGuanJia
下載速度才會正常一些。
謝謝

**Comment by acgotaku** [comment]
终于有个人回答到 点子上了…… 我估计也是这个问题 请问你们有人可以提供个外网的 aria2 c让我测试一下么？

**Comment by leitwolf** [comment]
我的aria2c一直都是放在路由器上的啊，之前都用得好好的

**Comment by taozhijiang** [comment]
百度导出的是可用的。但是现在百度BT离线下载有问题，想本地进行BT下载，但是挂了好久一点速度都没有。贴上BT相关的设置：
#启用本地节点查找
bt-enable-lpd=true
#添加额外的tracker
#bt-tracker=<URI>,…
bt-tracker=http://bt2.careland.com.cn:6969/announce,https://www.siambit.tv/announce.php,http://www.todotorrents.com:2710/announce
#单种子最大连接数
#bt-max-peers=55
#强制加密, 防迅雷必备
#bt-require-crypto=true
#当下载的文件是一个种子(以.torrent结尾)时, 自动下载BT
follow-torrent=true
#BT监听端口, 当端口屏蔽时使用
#listen-port=6881-6999

#不确定是否需要，为保险起见，need more test
enable-dht=false
bt-enable-lpd=false
enable-peer-exchange=false
#修改特征
user-agent=uTorrent/2210(25130)
peer-id-prefix=-UT2210-
#修改做种设置, 允许做种
seed-ratio=0
#保存会话
force-save=true
bt-hash-check-seed=true
bt-seed-unverified=true
bt-save-metadata=true


能帮看看不啊/

**Comment by acgotaku** [comment]
@taozhijiang  BT我也没有经验啊 ... 这个怎么指导啊

**Comment by taozhijiang** [comment]
@acgotaku 
额，我意味你知道的。网上很多说设置bt-tracker就可以。但是我试了很久都不行。
有时间我再搜搜方案吧。
