### ISSUE TITLE
求教-命令语法不正确

### ISSUE THREAD

**Issue by yugit** [acgotaku/BaiduExporter#148]
命令语法不正确

C:\Users\saife>aria2c --conf-path=<c:\aria2\aria2.conf>
命令语法不正确。

aria2-1.20.0-win-64bit-build1
windows10
https://aria2.github.io
每次输入都能看见这个问题(我没用过这个软件,第一次安装,不知道怎么处理这个问题)

**Comment by acgotaku** [comment]
@yugit 能给个截图 和你自己操作的具体过程么？

**Comment by acgotaku** [comment]
@yugit 都去百度和谷歌搜相关的使用资料啊 应该有一大堆啊
