### ISSUE TITLE
插件无法链接到aria2c

### ISSUE THREAD

**Issue by SilverBut** [acgotaku/BaiduExporter#149]
之前的issue #145 太乱了，自作主张按照格式提交了一次

插件版本：0.6.6 from Chrome Extension Store
尝试了清空浏览器缓存/尝试卸载插件后重新安装

下载的内容地址：无关
浏览器版本号：Version 49.0.2623.87 m
列举出现问题的详细步骤：设定好后，点击测试链接，提示“错误,请查看是否开启Aria2”

* * * * *

我自己进行了一些调试，发现问题可能出在和后台通信的阶段。在Connect.js的20行：
```
        sendToBackground:function(method,data){
            port= chrome.runtime.connect(extensionId,{name: "BaiduExporter"});
            port.postMessage({
                method:method,
                data: data.data
            });
     //......
```

注意到使用了Port.postMessage。步过后发现，Network面板中没有任何网络活动。后台应该是没有反应。看了眼手册，试图找到这个postMessage的对端，然而并没有找到。可能是我没写过Chrome插件，不太了解通信机制……

**Comment by acgotaku** [comment]
@SilverBut 你能告诉我你的 RPC地址是多少么? 内部通讯是在Network上看不到的 你可以看看终端的报错信息

**Comment by SilverBut** [comment]
@acgotaku 
http://token:{HIDDEN TOKEN}@localhost:6700/jsonrpc
console里面，点击“连接测试”按钮后，只报了一条：
```
connect.js:45 Object {method: "rpc_version", status: false}
```

**Comment by SilverBut** [comment]
@acgotaku 我对比了aria2c的日志(--console-log-level=info)，发现了一个不同。
另外一个能正常使用的Aria2c客户端日志如下： 
> 03/18 01:34:41 [NOTICE] IPv4 RPC: listening on TCP port 6700
> 03/18 01:34:41 [INFO] CUID#9 - Using port 6700 for accepting new connections
> 03/18 01:34:41 [NOTICE] IPv6 RPC: listening on TCP port 6700
> 03/18 01:34:50 [INFO] RPC: Accepted the connection from ::1:60941.
> 03/18 01:34:50 [INFO] HTTP Server received request
> GET /jsonrpc HTTP/1.1
> Host: localhost:6700
> Connection: Upgrade
> Pragma: no-cache
> Cache-Control: no-cache
> Upgrade: websocket
> Origin: file://
> Sec-WebSocket-Version: 13
> User-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.87 Safari/537.36
> ...
> 03/18 01:34:50 [INFO] CUID#10 - HttpServer: all response transmitted.
> 03/18 01:34:50 [INFO] RPC: Accepted the connection from ::1:60942.
> 03/18 01:34:50 [INFO] HTTP Server received request
> GET /jsonrpc?jsoncallback=jQuery21306935636370914293_1458236089712&jsonrpc=2&id=webui&method=system.multicall&params=...&_=1458236089713 HTTP/1.1
> Host: localhost:6700
> Connection: keep-alive
> Accept: */*
> User-Agent: Chrome/49.0.2623.87 Safari/537.36
> Accept-Encoding: gzip, deflate, sdch
> Accept-Language: en-US,en;q=0.8,zh-CN;q=0.6,zh;q=0.4,zh-TW;q=0.2
> 03/18 01:34:50 [INFO] Executing RPC method system.multicall
> 03/18 01:34:50 [INFO] CUID#11 - HttpServer: all response transmitted.
> 03/18 01:34:50 [INFO] CUID#11 - Persist connection.
> 03/18 01:34:51 [INFO] Executing RPC method system.multicall
> ...
> 03/18 01:35:02 [INFO] CUID#10 - WebSocket session terminated.

而目前的BaiduExporter日志如下：
> 03/18 01:35:38 [INFO] RPC: Accepted the connection from ::1:63176.
> 03/18 01:35:38 [INFO] HTTP Server received request
> POST /jsonrpc HTTP/1.1
> Host: localhost:6700
> Connection: keep-alive
> Content-Length: 110
> User-Agent:Chrome/49.0.2623.87 Safari/537.36
> Origin: chrome-extension://mjaenbjdjmgolhoafkohbhhbaiedbkno
> Content-type: application/x-www-form-urlencoded; charset=UTF-8
> Accept: */*
> Accept-Encoding: gzip, deflate
> Accept-Language: en-US,en;q=0.8,zh-CN;q=0.6,zh;q=0.4,zh-TW;q=0.2
> 03/18 01:35:38 [INFO] Executing RPC method aria2.getVersion
> 03/18 01:35:40 [INFO] CUID#12 - HttpServer: all response transmitted.
> 03/18 01:35:43 [NOTICE] Serialized session to 'aria2.session' successfully.
> 03/18 01:36:43 [INFO] No change since last serialization or startup. No serialization is necessary this time.

似乎插件采用了POST方式传递了数据？我是否应该附上我aria的配置文件？

**Comment by acgotaku** [comment]
@SilverBut 如果你的Chrome开启了 扩展的开发者模式的话 可以看到扩展有个背景页 (Background Page)
你点开这个背景页 里面的network面板是最后和 aria2c通讯的记录  通过这个你应该能看到问题所在

**Comment by SilverBut** [comment]
@acgotaku 多谢指点。查看了下，报的400

请求如下：

> ...
> Content-type:application/x-www-form-urlencoded; charset=UTF-8
> Host:localhost:6700
> Origin:chrome-extension://mjaenbjdjmgolhoafkohbhhbaiedbkno
> User-Agent:Chrome/49.0.2623.87 Safari/537.36
> Form Data:
> {"jsonrpc":"2.0","method":"aria2.getVersion","id":1,"params":["token:1n%7BSuXU *HIDDEN* LU1UqD7GmBdl"]}

回应：

> {"id":1,"jsonrpc":"2.0","error":{"code":1,"message":"Unauthorized"}}

看来是认证的问题，我自己写了个小脚本验证了下。由于parser采用的是<a>，当token含有特殊字符的时候会被encodeURI()，但根据RPC协议，这种情况下是不需要编码的，因此报了400。

稍后提交一个Pull Request。

**Comment by acgotaku** [comment]
@SilverBut 原来是你们 token用了特殊字符啊。。。 顺便问下 用的啥字符？

**Comment by SilverBut** [comment]
@acgotaku 我用的是左花括号。但应该不止这个，所有在url中被转义的字符都会被处理。

**Comment by SilverBut** [comment]
@acgotaku 已发pr~

**Comment by acgotaku** [comment]
@SilverBut 收到！

**Comment by SilverBut** [comment]
@acgotaku 需要重开这个issue了。最新的0.8.3版本中这个问题又出现了，原因应该是一样的。

我还没有看代码，不过估计是同一个地方出了问题。

另辅调试记录（Wireshark抓的）：
插件请求：
```
POST /jsonrpc HTTP/1.1
Host: localhost:6700
Connection: keep-alive
Content-Length: 110
Origin: chrome-extension://mjaenbjdjmgolhoafkohbhhbaiedbkno
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.106 Safari/537.36
Content-type: application/x-www-form-urlencoded; charset=UTF-8
Accept: */*
Accept-Encoding: gzip, deflate
Accept-Language: en-US,en;q=0.8,zh-CN;q=0.6,zh;q=0.4,zh-TW;q=0.2

{"jsonrpc":"2.0","method":"aria2.getVersion","id":1,"params":["token:1n%7BSuXUTdE%7B%7BSMBdl"]}
```

curl请求：
```
POST /jsonrpc HTTP/1.1
Host: localhost:6700
User-Agent: curl/7.49.1
Accept: */*
Content-Length: 104
Content-Type: application/x-www-form-urlencoded

{"jsonrpc":"2.0","method":"aria2.getVersion","id":1,"params":["token:1n{SuXUTdE{{SMBdl"]}
```

**Comment by SilverBut** [comment]
Issues may related: #239 #244

**Comment by Mapaler** [comment]
你token搞那么复杂干啥，我就写的 闷声发大财

**Comment by sino1641** [comment]
字母加数字的token都打不开。。。

**Comment by SilverBut** [comment]
@sino1641 最新的版本里这个bug已经修好了，我这里看似乎没啥问题。升级下看看？
