### ISSUE TITLE
关于token多长能正常使用的探（坑）讨

### ISSUE THREAD

**Issue by zhurui1008** [acgotaku/BaiduExporter#151]
我直接上图
![image](https://cloud.githubusercontent.com/assets/5326746/13879781/9aed4d8a-ed5c-11e5-9e75-7c297b131da8.png)

**Comment by acgotaku** [comment]
@zhurui1008 把你的 RPC地址贴出来

**Comment by zhurui1008** [comment]
http://token:4c0343631be87bae898c62aa2f25cae630dafecad533e1818effb7e6eaee9994@localhost:6800/jsonrpc

![image](https://cloud.githubusercontent.com/assets/5326746/13880663/aa051092-ed60-11e5-8ea9-0504f7343698.png)

webui-aria2正常使用，baiduexporter设置一直通不过

![image](https://cloud.githubusercontent.com/assets/5326746/13880722/f0a57802-ed60-11e5-80aa-da9fb3a2107a.png)

测试连接，成功显示版本号。 这项点击没变化，ChromeConsole 报错core.js:75 Uncaught TypeError: Cannot read property '1' of null

Chrome版本:51.0.2679.0 dev-m (64-bit)
BaiduExporter版本:0.6.7

**Comment by acgotaku** [comment]
@zhurui1008 尼玛 这么长的 token地址 鬼测试过啊....

**Comment by zhurui1008** [comment]
之前的版本使用正常。。。。
另外这个token是`date | sha256sum` 生成的。。

**Comment by acgotaku** [comment]
@zhurui1008 最近的 pull request 写的不靠谱 我近期好好看看 你先用个正常点的 token凑合着

**Comment by zhurui1008** [comment]
我去试试短一点能不能通过。。

**Comment by zhurui1008** [comment]
短一点的也是这个问题。。。
![image](https://cloud.githubusercontent.com/assets/5326746/13881371/0d7be508-ed64-11e5-988b-666f1913f9d2.png)
![image](https://cloud.githubusercontent.com/assets/5326746/13881349/f08f9b2e-ed63-11e5-9f7a-d5de2389cb4f.png)

我再试试不要token的

**Comment by acgotaku** [comment]
@zhurui1008 不要 肯定可以的 最近这块代码 我再也不接受任何 PR了 坑

**Comment by zhurui1008** [comment]
不要token成功了。。
![image](https://cloud.githubusercontent.com/assets/5326746/13881497/773e620e-ed64-11e5-8557-fcee4308e867.png)
这是个北上的故事（摊手

**Comment by acgotaku** [comment]
@zhurui1008 新版更新了 要是没问题就把这个关了

**Comment by zhurui1008** [comment]
ok,等我做下token强度测试。没问题我就关掉这个issue

**Comment by zhurui1008** [comment]
不好意思作者君，强度测试通过。
token长度sha256正常使用
