### ISSUE TITLE
获取File失败!

### ISSUE THREAD

**Issue by SuZixiong** [acgotaku/BaiduExporter#152]
提示获取File失败!
配置和以前一样。yaaw连接正常。不知道这个错误具体是哪里的问题？

**Comment by acgotaku** [comment]
@SuZixiong 等新版本更新

**Comment by acgotaku** [comment]
@SuZixiong 新版更新了 没问题就自己主动关了这个 issue

**Comment by SuZixiong** [comment]
哪个版本？0.6.7？我就是昨天更新了以后出现的问题。

**Comment by acgotaku** [comment]
新版本 0.6.8

**Comment by SuZixiong** [comment]
我这里看商店里面目前还是0.6.7。

2016-03-19 17:33 GMT+08:00 雪月秋水 <notifications@github.com>:

> 新版本 0.6.8

**Comment by acgotaku** [comment]
推送要等一个小时 你可以自己载入最新的

**Comment by SuZixiong** [comment]
OK了，更新了，多谢
