### ISSUE TITLE
点选文件后插件按钮消失

### ISSUE THREAD

**Issue by Saddam0523** [acgotaku/BaiduExporter#154]
打开百度网盘的时候插件能正常加载，选中任意文件或打开文件夹之后插件按钮就会消失。

插件版本号：0.6.8
浏览器版本号：Chrome 49.0.2623.87
系统：openSUSE Tumbleweed (20160321)

**Comment by acgotaku** [comment]
@Saddam0523 还真是!!! 目前的解决方案是在当前文件夹下刷新 我最近会看看的

**Comment by Saddam0523** [comment]
@acgotaku 问题是刷新之后文件就不是勾选状态了，还是没法下载啊……

**Comment by acgotaku** [comment]
@Saddam0523 还真是 估计是百度故意的吧 上午用的还好好的 看来是采取手段了

**Comment by acgotaku** [comment]
@Saddam0523 百度现在只要触发任何操作都会重新刷新 上面导航栏 也是6 的不行

**Comment by acgotaku** [comment]
@Saddam0523 卧槽 这插件被百度知道了 人家直接就删我图标

**Comment by ouyangerbai** [comment]
@acgotaku 特意注册了个账号上来回复 百度这也太坟蛋了~

**Comment by acgotaku** [comment]
@ouyangerbai  更新了 等推送~
