### ISSUE TITLE
图标消失，以及Firefox/Safari插件版本号的问题

### ISSUE THREAD

**Issue by bravepetrelc** [acgotaku/BaiduExporter#155]
[issue154](https://github.com/acgotaku/BaiduExporter/issues/154)问题依然存在。
插件版本号：0.5.9 / 0.6.0
浏览器版本号: Safari 9.1 / Firefox 45.0.1
系统版本号: OS X 10.10.5

Safari和Firefox上的插件版本似乎落后很多？我注意到Chrome的已经是0.6.9，可以把另外两个浏览器的也更新一下吗？

**Comment by acgotaku** [comment]
@bravepetrelc 主力维护的是 Chrome 当Chrome版本没有问题的时候才会去移植和维护另外俩版本
三个平台同时维护是很耗费精力的  ==   @Cee C总快来维护啦!

现阶段还是您换个浏览器用比较省事吧

**Comment by Cee** [comment]
@acgotaku @bravepetrelc 最近在搞畢設所以時間比較少
這週末我看看維護一下吧！

**Comment by dogchild** [comment]
确实，safari没法用了，chrome在mac下还是与safari有不小差距啊，望修复，谢谢

**Comment by Cee** [comment]
@dogchild 好~

**Comment by Cee** [comment]
@bravepetrelc @dogchild Safari 版本已更新。

**Comment by bravepetrelc** [comment]
@Cee @acgotaku Thank you very much.
