### ISSUE TITLE
似乎使用https的度盘链接无法使用exporter？

### ISSUE THREAD

**Issue by fortissimoX** [acgotaku/BaiduExporter#156]
不知道在哪下东西的时候看到一个https的链接，发现进去之后插件没有加载，手动改成http之后正常了
不知道是百度的问题还是插件的问题
以下是示例链接
[->_<-](https://pan.baidu.com/s/1bnLq1Fx)

browser: Safari 9.1
OS: OS X 10.11.4
Verson: 0.5.9

**Comment by acgotaku** [comment]
@fortissimoX 你点地址栏立马的 那个卫士一样的图标 然后选择加载不安全的脚本 就可以了

**Comment by acgotaku** [comment]
@fortissimoX 不对.... 你的浏览器是 Safari  肯定是不支持的 

只有Chrome是支持 https的 解决方案 要么是换浏览器 要么是手动更改成 http链接

**Comment by fortissimoX** [comment]
原来如此，chrome 果然可以
其实一般真的不会见到 https 的，度盘自己生成的都是 http 的

**Comment by acgotaku** [comment]
那就关掉这个 issue吧

**Comment by fortissimoX** [comment]
吼！
