### ISSUE TITLE
刷新初始化成功，勾选文件后，导出下载消失

### ISSUE THREAD

**Issue by ykqmain** [acgotaku/BaiduExporter#157]
Mac上的 Safari 和 Chrome 都这样

**Comment by et2010** [comment]
我也是这个问题，而且是昨天开始的，是不是百度又更新了

**Comment by et2010** [comment]
我也是这个问题，而且是昨天开始的，是不是百度又更新了

**Comment by ykqmain** [comment]
@et2010  我星期天下载了一下午是正常的，就这几天失效的

**Comment by acgotaku** [comment]
@ykqmain 你看看是不是  0.6.9版本? @et2010

**Comment by ykqmain** [comment]
@acgotaku 0.5.9

**Comment by acgotaku** [comment]
@ykqmain 差了十个版本 肯定不能用啊!!!

**Comment by ykqmain** [comment]
@acgotaku 我星期天可以用，我刚刚在页面上再下载安装了一次，仍然还是0.5.9。
请问Safari的有更新吗？
请发一份到我的邮箱 ykqmain@gmail.com ，谢谢。

**Comment by ykqmain** [comment]
@acgotaku  mac 上的chrome 是0.6.6 版本，也不能用

**Comment by acgotaku** [comment]
@ykqmain 没有 目前只有 Chrome 能用 请换浏览器
https://chrome.google.com/webstore/detail/baiduexporter/mjaenbjdjmgolhoafkohbhhbaiedbkno

你手动更新啊...

**Comment by ykqmain** [comment]
@acgotaku 有Chrome能用也行，原来需要手动更新啊……
我以为插件都是自动更新的，我试试

**Comment by ykqmain** [comment]
@acgotaku  谢谢，删除 chrome的插件 再次安装，就是最新的了，已解决  感谢开发者 😁

**Comment by acgotaku** [comment]
@ykqmain 自动更新是根据你网络条件来的 你不翻墙 怎么更新....

**Comment by et2010** [comment]
@acgotaku 我用的firefox，0.60版本

**Comment by ykqmain** [comment]
@acgotaku 我用了ss，应该是翻了的

**Comment by acgotaku** [comment]
@et2010 目前除了 最新的Chrome 0.6.9 版本 其它版本 全部不能用

**Comment by acgotaku** [comment]
@ykqmain 如果你是 7*24全局翻墙 Chrome肯定会自动更新 但是没人会这么做 所以Chrome后台没法自动更新  不是最新的话 就手动更新就是了

**Comment by ykqmain** [comment]
@acgotaku 嗯，只要有这个插件能用，就不错了😑

**Comment by et2010** [comment]
请问firefox版本更新在计划中吗？

**Comment by acgotaku** [comment]
@et2010 基本上Chrome稳定一周不出问题 我就会更新 FF

**Comment by et2010** [comment]
@acgotaku 非常感谢！
