### ISSUE TITLE
续3月23日更新后，插件又一次被百度云干掉

### ISSUE THREAD

**Issue by Aniark** [acgotaku/BaiduExporter#159]
插件版本：0.6.9
浏览器：chrome  49.0.2623.108 m (64-bit)
系统：win7sp1 64bit 

![default](https://cloud.githubusercontent.com/assets/10991795/14038917/a361c916-f291-11e5-87b0-e99beeeca065.JPG)

**Comment by pcseed** [comment]
3/25 早上還可以用
下午使用出現初始化成功 , 但沒有按鈕

"有時" F5 refresh 後會出現
估計有屏蔽程式在運作

**Comment by acgotaku** [comment]
@pcseed 我这边还没收到屏蔽程序的推送.... 等等我收到了才能修复...

**Comment by maomihz** [comment]
确实被干掉了，按钮不见

**Comment by Mapaler** [comment]
火狐最近是分享的页面能用，自己的页面不能用。前几天开始只要一选中文件，按钮就会消失，所以页面加载完成之前先选中文件，等页面加载完后可以点下载。但是今晚回来一看，页面完全不出现按钮了。

**Comment by xjbeta** [comment]
同被干掉  Safari   chrome51   都没了

**Comment by acgotaku** [comment]
我已经知道 不用一个个都来汇报一次吧……

**Comment by phenix502** [comment]
加油。兄弟们的幸福生活就靠你了。

**Comment by acgotaku** [comment]
![2016-03-25-233121_1076x382_scrot](https://cloud.githubusercontent.com/assets/1191834/14046000/c6527de4-f2e1-11e5-8f62-7eb644a0b82d.png)

百度这回写了一个模块 用了封杀插件 真是牛逼 待我后续好好分析  最近真的很忙...

**Comment by acgotaku** [comment]
@Aniark  更新啦 更新啦! 专治百度!

**Comment by Aniark** [comment]
@acgotaku 谢谢大大的福利
