### ISSUE TITLE
下载速度现在变得非常慢

### ISSUE THREAD

**Issue by kashu** [acgotaku/BaiduExporter#160]
### 是什么原因？ 其他人也这样吗？

**Comment by acgotaku** [comment]
@kashu 你弄这么大字体干啥....  下载速度不仅和网速有关 还和资源有关 而且下载慢也不一定是我的锅...

**Comment by kashu** [comment]
### 没说是妳的原因，更没说是妳的锅。

### 我只是想问下是我一个人慢？还是所有人都变慢了？

### 妳想这么多干什么？

**Comment by acgotaku** [comment]
你在这发帖 除了我会收到邮件通知 还有别人呢??? 别人也不会闲着没事看我项目的 Issue啊....

**Comment by kashu** [comment]
……
### 你真的想多了。 
### 没说是你的锅，这实际是我的锅。
### 谢谢
