### ISSUE TITLE
嘿~ 关于下载速度。

### ISSUE THREAD

**Issue by ouyangerbai** [acgotaku/BaiduExporter#161]
虽然看到有人提问了类似的问题，但是似乎他讲的没有太明白。
从上一次与百度网盘抗争以后，也就是插件第二次更新以后（如果我没有记错，也有可能第三次）
你开发的插件提取的百度网盘下载链接在aria2会被不明原因的限速
一开始以为是aria2被限制了  所以我尝试了简单的修改了aria2里的百度客户端配置文件内容发现没有起色
然后偶然的机会，发现自己从浏览器下载里拷贝的下载链接放到aria2里手动添加任务就不会被限速，刚刚再次做了测试 确认无误
另外，鉴于这几次百度网盘的屏蔽速度，应该是有相关人员关注了你这边了吧，有没有打算先暂缓几天更新 避避风头之类的？

**Comment by acgotaku** [comment]
@ouyangerbai 我这边下载速度正常 1m/s左右  我自己就满足了 再封的话 我就自己更新自己用了

折腾不过来 人家写代码是领工资的 我没这么多时间陪它玩

**Comment by acgotaku** [comment]
@ouyangerbai 你可以贴出来 下载的文件 以及 插件导出的地址 和 浏览器下载的地址么?

**Comment by kashu** [comment]
@acgotaku
### 妳想多了……
### 放开那个锅，我的锅，谢谢！

@ouyangerbai 
### 你现在和我一样的症状，呵呵

**Comment by ouyangerbai** [comment]
@acgotaku 我不会提取插件导出的地址。。。。

**Comment by ouyangerbai** [comment]
@kashu 你也别斤斤计较了  人家毕竟做的是一个公益插件 你要怀有一颗感恩的心~

**Comment by kashu** [comment]
### @ouyangerbai  我从来都没计较过。我是真的怕她会多想……  因为我真的从头到尾都有点莫名其妙我到底哪句说错了？

**Comment by kashu** [comment]
### @ouyangerbai 现在的方法就是，改那个useragent，可明显提升一点速度
###下面是我随便改的
### User-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64; rv:42.0) Gecko/20100101 Firefox/42.0"

**Comment by ouyangerbai** [comment]
@kashu 卧槽~这是个啥  不是都是模拟百度云的客户端么？ 你这个怎么是模拟火狐浏览器  。。。。我也试着改过 只是把模拟客户端的版本号尝试修改了一下没有效果（一知半解）   效果不太明显。。。

**Comment by kashu** [comment]
### @ouyangerbai 你能写个Linux里面的Chromium浏览器的user agent试试吗？因为我发现直接用浏览器下载，速度是满的，所以我觉得是不是这个user agent有点问题？我不太懂……

**Comment by ouyangerbai** [comment]
@kashu 你太高估我的能力了。。。。我连提取插件的下载连接都不会怎么可能会写东西。。。
然后我刚刚测试了一下  你给的设置确实能满速下载
那么问题就来了，为什么插件提取的链接下载的时候就会被限速
但是浏览器下载里提取的链接在aria2里就不限速了呢。。。
难道是浏览器下载里提取的链接 会被百度识别成浏览器而跟useragent的设置无关了么？
@acgotaku 你参考一下？

**Comment by ouyangerbai** [comment]
@kashu 700k已经是正常速度了  因为百度云有一部分软件的资源速度不太好 或者被限制 到不了下载峰值速度  那么问题似乎也就是跟模拟的浏览器内核有关了。。。

**Comment by acgotaku** [comment]
@ouyangerbai 改UA有用的话 你就改成那个就是了 贴下载链接很简单 你点那个导出下载 把对话框的内容粘帖出来就好了

**Comment by ouyangerbai** [comment]
@acgotaku 因为改UA可以解决。。。这个问题算是解决了吧。。。

**Comment by acgotaku** [comment]
@ouyangerbai 恩  你关掉 issue吧

**Comment by Fredpata** [comment]
好像是被限速了-。- 我被限在50 ……之前早上还好好的……

**Comment by Fredpata** [comment]
额……奇葩的是……用 mac 自带的。。。好像有1M 多了……也够快了……虽然没以前 aria 那么快

**Comment by ouyangerbai** [comment]
@kashu 是的 我也偶尔会出现这个问题 不过不是说开始一个任务另一个任务就会中断 而是有一些任务就是会中途中断  跟多线程没有关系

**Comment by ouyangerbai** [comment]
@Fredpata 参考楼上修改 User-Agent 不要再使用默认的了 默认的被限速了

**Comment by Fredpata** [comment]
@ouyangerbai 我这边稍微改几个版本号没用……上面改成 Firefox 就是变成普通浏览器下载的速度（没有伪装成 PC 下客户端）……跟之前媲美会员的速度没法比。如果只是这样，其实 aria2就是变成一个普通的下载器了……百度也要挣钱-。-

**Comment by ouyangerbai** [comment]
@Fredpata  netdisk;Chrome Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.87 Safari/537.36 用这个吧 只要你设置的没有问题 就可以满速

**Comment by acgotaku** [comment]
@ouyangerbai 你的满速 指得是多快?

**Comment by ouyangerbai** [comment]
@acgotaku 我这里20M光纤 下载速度均速在2.1M/S

**Comment by acgotaku** [comment]
@ouyangerbai 我插件默认的 UA 我自己用也是 1m/s 你们先改UA吧 我暂不更新 更了还得封 你们自己知道就好

**Comment by Fredpata** [comment]
@ouyangerbai 有点效果……至少回到过去正常水平……1~1.5之间了……
@acgotaku 我过去一般能到2M，快的能满速……5M+   50M 魔都电信
我用MAC百度云，现在一般是200~500……大部分时间是200 但是有个问题……大文件……百度云 mac 客户端会出问题重新下载……或者下到一般停了，说同步出错……

**Comment by Fredpata** [comment]
@acgotaku 不改 UA 的话，还有一种错误是直接不允许下载……昨晚上 速度是刷刷标准50KB
百度云的会员现在有分一般和超级……也没明确速度提示划分……然后 mac 客户端现在还不知道是程序是不是本身也问题多多=。=问题反馈了，但是估计也没啥效果

**Comment by acgotaku** [comment]
@Fredpata 现在能用就好 我要是更新了 这个 UA估计也要被封 就这样放置吧

**Comment by Fredpata** [comment]
@acgotaku 差不多……暂时只能这样了……

**Comment by wuyuxin** [comment]
@Fredpata请问你是在那里改的UA？

**Comment by Fredpata** [comment]
插件设置啊，百度云页面

**Comment by zw963** [comment]
我确认是被限速， 已经试过好几天了。

目前，修改 User Agent 是有效的， 速度至少比不改快点，貌似用一用还是会慢下来。

大家就先偷着乐吧， 能用一天是一天，不定那天，完全封杀了 ....

**Comment by DimRacker** [comment]
BD看来是要赶尽杀绝啊！以前是账户被限速，退出账户下载就能快，现在退不退都那样，似乎改UA也不管用了，一律50K/S

**Comment by zw963** [comment]
我公司和家里下载速度都是蛮快的, 大家不要为难维护者了, 可能真是自己的问题.

**Comment by DDoSolitary** [comment]
试试最新版啊，那个目前还没限速吧

**Comment by PinkyJie** [comment]
我也是，从前几天开始都变成50k了
