### ISSUE TITLE
`Fuck Baidu` probably needs to be upgraded

### ISSUE THREAD

**Issue by rility** [acgotaku/BaiduExporter#162]
Plugin 0.7.0, Chrome 49 32bit, Windows 10 64bit, Cache wiped.
The button on the page flashes and disappears.

Huge fan of your work.
Thanks xxx

**Comment by HerringtonDarkholme** [comment]
Thanks for reporting. It seems some bastard is more atrocious than we are thinking.

![screenshot from 2016-03-29 20 51 58](https://cloud.githubusercontent.com/assets/2883231/14108464/23c08c12-f5f0-11e5-947b-79bb8ac5c745.png)

**Comment by rility** [comment]
Do we expect solutions any time soon? Going back to official downloader is more than aching after the wonderful tool you guys present here.

**Comment by acgotaku** [comment]
虽然已经修复 但是我不打算 公开了 我没那么多时间和百度折腾

**Comment by jtliaw** [comment]
不是吧！！！！！！！
以后都没得使用了？？？？？？
悲剧了！

**Comment by acgotaku** [comment]
@jtliaw 当然了 你可以选择付费使用 有付出才有收获  (但我目前还不打算收费

**Comment by jtliaw** [comment]
呜。。。。！
那没办法了，只能另外再找办法了！在linux下这些东西都相当麻烦，官方又不开发给linux！

**Comment by rility** [comment]
啊不会发展到这种程度吧。。。相信有更好的办法

**Comment by HerringtonDarkholme** [comment]
事到如今看这个代码已经能感受到百度明显的恶意了
我们这些维护者说到底也只是天朝屁民,真的百度律师敲上门就都不好了
确实抱歉了

**Comment by Leeiio** [comment]
也许百度只是不希望第三方插件植入造成的安全问题由百度来背？

**Comment by zhen-ke** [comment]
感觉百度这样做是为了强推所谓超级会员，想快速下载就得付费，想不付费就下载？慢慢挂吧您

**Comment by laputa6616** [comment]
G主别这么怂呀，独「Fuck 百度」不如众「Fuck 百度」！！付费我也愿意……！

**Comment by acgotaku** [comment]
你拉倒吧你， 人家写代码是领工资的。我这义务劳动，毕业论文你帮我写啊……我哪里有那么多时间

**Comment by laputa6616** [comment]
我们每多一份人力「Fuck」，都会加速这家公司早日灭亡！你这是在为中国互联网的春天早日到来做贡献！

**Comment by laputa6616** [comment]
刚下一个一百兆文件，下到现在还没下好，真是有种想死的感觉呀呀呀！！！我有良好的付费习惯，但绝不会在这家 Bitch
公司身上花上一分钱！G主这样放弃的话，那我也只能放弃百度网盘了……

**Comment by rility** [comment]
？？？@laputa6616 这是什么逻辑？？ 麻烦不要(愚蠢的)道德绑架维护者好吗到时间有可能吃传票的又不是你

**Comment by sunboman** [comment]
百度真贱。。。 G主收费吧 我把钱都给你也不给百度一分

**Comment by haodong** [comment]
劳动是有价值的 我支持你收费！

**Comment by laputa6616** [comment]
@rility 我的逻辑和我的意愿都很清楚：我愿意花钱买人家的劳动成果，但我很讨厌百度！！！然后我表达了出来了，就这样，很奇怪吗？！本人放弃百度网盘能对作者进行「道德绑架」，真是笑话！我认为作者所做的事情是在净化中国的互联网环境，这也算「道德绑架」，请问你的逻辑点在哪儿？！

**Comment by masahoshiro** [comment]
Thank you

**Comment by luokar** [comment]
的确,把精力花在和百度折腾上十分不值,但希望G主可以继续更新除fuck baidu其他的部分,让其他普罗大众提供折腾的hack. 我认为这才是让这个open source活下去的方法.

**Comment by logonod** [comment]
支持付费 一起fuck百度

**Comment by binux** [comment]
不往页面上插元素，直接加在右键菜单里面，百度应该就检测不到了。
插件的权限要大于页面脚本。。最终肯定是插件厉害啊。。

**Comment by Cee** [comment]
@binux 打算这么做👀

**Comment by HarukaMa** [comment]
打开邮箱发现很少见的被这个 repo 轰炸了……似乎百毒越来越恶心了啊

友情提示，收费会带来非常大的风险，包括但不限于直接被百毒艹死。

**Comment by HarukaMa** [comment]
@laputa6616 在天朝这个环境 不会适度地怂会死得很惨。

**Comment by yyfearth** [comment]
@HerringtonDarkholme seems like it only check for chrome ext.
So maybe we can change the insertion script using another protocol, e.g. from another http domain, or make it as data uri (not sure if chrome ext allow that or not)
An ultimate way to solve this, could be create a proxy to scripts and change what every we want.

貌似只检查了 chrome ext
是不是可以插入其它域名的脚本 或者把脚本变成 data uri （不清楚是非会被 chrome ext 阻止）
如果实在不行 可以用 proxy 方法 把 js 篡改掉

**Comment by luokar** [comment]
认真看了下百度的代码,感觉百度那边也挺无奈的,人家写了洋洋洒洒几百行的模组,几行就干掉了. 
懂javascript的应该不用一个小时就能解决这次的封杀.但把百度逼急了,可能就不会这么简单了.

**Comment by acgotaku** [comment]
@binux 右键菜单 JS也是可以修改的啊 解决肯定有办法 不过没有啥一劳永逸的办法 懒得陪百度耗了...

**Comment by binux** [comment]
@acgotaku 浏览器级的右键菜单啊

**Comment by acgotaku** [comment]
@binux  (感觉使用会变得更加不友好了....

**Comment by binux** [comment]
@acgotaku 举个例子，方法还很多。直接把百度搞到没辙就行了。

**Comment by acgotaku** [comment]
@binux 我没那么多时间就是了 万一百度给我邮寄律师函 我不就亏大了

**Comment by cjh-github** [comment]
@acgotaku   早上一来年看就听到这个坏消息，失去了这么个好东西，不过还是支持你的决定

**Comment by HerringtonDarkholme** [comment]
被封杀不是技术原因，更多是法律原因
如果有身处国外的大神估计还能持续吧

**Comment by acgotaku** [comment]
@HerringtonDarkholme 虽然我身处国外。。。 但是我还没准备定居。。。
还是不作死的好

**Comment by kingwkb** [comment]
这个用不着收费把，植入些广告，再弄个付费去广告，比直接收费好多了

**Comment by typcn** [comment]
来我Fork一个

**Comment by zanderzhng** [comment]
chrome web store 里的条目已经删除了。

**Comment by acgotaku** [comment]
@zanderzhng 不能用 就下架了

**Comment by HarukaMa** [comment]
@kingwkb 再次提请注意任何收费行为带来的风险。

有“非法”收入就有充足的理由搞死你。

**Comment by cjh-github** [comment]
baidu 有过针对个人的先例吗？

在 2016/3/30，Haruka Ma<notifications@github.com> 写道：

**Comment by HarukaMa** [comment]
@cjh-github 先例有什么用么……

**Comment by pentie** [comment]
能探讨下技术上的细节吗？
我尝试在DOMNodeInserted事件里面断点，unbind掉这个handler，但是虽然后续不再执行，但是手动执行CORE.addMenu.init('home') 后按钮依旧消失，还有哪里的事件处理？

**Comment by rility** [comment]
在技术方面百度已经在封杀了，完全没有理由怀疑百度在行政方向会软。

前例不是没有，看看珊瑚虫吧。

**Comment by acgotaku** [comment]
@pentie 百度手动实现了 https://developer.mozilla.org/en/docs/Web/API/MutationObserver 这个API
使用 timer loop监听DOM 然后进行删除 想绕过这个 办法也有很多

**Comment by pentie** [comment]
@acgotaku 太感谢了，把按钮插到侧栏去就可以用了，哈哈，只是没那么美观而已
百度手动实现DOM监听应该就不可能监听所有地方了，不然效率可就感人了，我暂时改来自用一下

**Comment by acgotaku** [comment]
@pentie 不客气 ，大家实现各种各样的解决方案 这样百度就封不掉了

**Comment by greatghoul** [comment]
@acgotaku 能规避风险就规避风险，百度真急了也会咬人的，支持你的决定。

**Comment by tamyiuchau** [comment]
既然打算停止开发，那么在README上加上现况说明吧，也能够为打算自行实现的童鞋一点方向

**Comment by silei862** [comment]
本来还打算升级百度网盘会员的，结果，好吧，放弃百度网盘......
