### ISSUE TITLE
网盘下载被限速了？

### ISSUE THREAD

**Issue by cjh-github** [acgotaku/BaiduExporter#165]
前阵子下载速度我限制900KB都能满速，但最近这2天下载速度才100KB都不到，
已经更新到今天的最新版了，还是很慢，

是我个例了还是大家都一样了？？
![Uploading 无标题.png…]()

**Comment by cjh-github** [comment]
![default](https://cloud.githubusercontent.com/assets/6256701/14132167/593b96b8-f675-11e5-8508-51846c2d9f69.png)

**Comment by wuyuxin** [comment]
我跟你一样，不管用哪个UA都这样

**Comment by acgotaku** [comment]
@cjh-github  @wuyuxin  看这个

**Comment by acgotaku** [comment]
https://github.com/acgotaku/BaiduExporter/issues/161
