### ISSUE TITLE
火狐插件失效

### ISSUE THREAD

**Issue by ckz1211** [acgotaku/BaiduExporter#167]
1、您下载的内容地址：Git的本项目地址主页
2、插件版本号0.6.0，浏览器版本号 Firefox 44.0.2，系统版本号 Win7 sp1 x64
3、列举出现问题的详细步骤：一个多月没用了，最近发现有问题，尝试退回老版本或32位版本、甚至新建一个空白配置文件的火狐再重新装插件都没用……

补充下——出现问题的页面是自己账号的网盘空间下（http://pan.baidu.com/disk/home ），这个页面下，虽然有提示插件初始化完成，但“导出下载”的按钮怎么也没能出现；
网盘分享链接的页面（http://pan.baidu.com/s/XXXXXXXXX ）目前还没问题，“导出下载”的按钮还是会出现……

**Comment by wfjsw** [comment]
Firefox的版本比现在HEAD的版本滞后了一个minor version大概是适配没跟上
然后收到提醒说这个项目快结束了（？
