### ISSUE TITLE
能不能整理一下源码减少重复……

### ISSUE THREAD

**Issue by Arthur2e5** [acgotaku/BaiduExporter#172]
现在三个源码树真的读起来、改起来都很烦。一个后果就是 FireFox 那边不被维护。预处理器 和/或 模块化大家应该都比我清楚，所以我就不仔细说了……

（话说谁想出来把 xpi 放在 firefox/ 下面的？）

**Comment by acgotaku** [comment]
@Arthur2e5 说起来简单 做起来难 谁不知道要改呢== 模块化我也知道 时间不是那么多 没时间做这个而已

**Comment by Arthur2e5** [comment]
（想了想还是不要出什么 diff 一下然后 ifdef 的馊主意了……）

**Comment by acgotaku** [comment]
我自己最近事情也挺多的 等我闲下来 肯定第三次 重构了 这个已经是第二次重构的了 第一次的更乱
