### ISSUE TITLE
Chrome下插件失效

### ISSUE THREAD

**Issue by suclogger** [acgotaku/BaiduExporter#173]
1. 您下载的内容地址

    **在勾选文件或者进入文件夹时都会出现,与文件内容无关**
2. 插件版本号，浏览器版本号，系统版本号

    **最新0.7.1,浏览器为chrome 48.0.2564.116 ,系统 OSXElcaptain10.11.4**
3. 列举出现问题的详细步骤
     
**在勾选文件或者进入文件夹时,导出下载按钮消失.**
![](http://ww2.sinaimg.cn/large/82324550gw1f2p19ew165g20b8070n12.jpg "")
4. 描述能否复现问题

    **始终出现**

**Comment by WongCM** [comment]
我的也是这样

**Comment by cjh-github** [comment]
昨天还好用的，今天就这样了，百毒又开始使坏了

**Comment by azureland** [comment]
暂时适用的方法：

在导出下载出现之前，勾选你要下载的文件就可以了。

考验手速。

**Comment by cjh-github** [comment]
#171 已经更新好了，都没看见

**Comment by lersh** [comment]
请问最新的更新怎么下载安装啊？

**Comment by acgotaku** [comment]
@lersh 删掉老的 直接去装新的 https://chrome.google.com/webstore/detail/baiduexporter/mjaenbjdjmgolhoafkohbhhbaiedbkno

**Comment by lersh** [comment]
@acgotaku 谢谢秋水
