### ISSUE TITLE
使用异常的原因是什么呢

### ISSUE THREAD

**Issue by iamxujian** [acgotaku/BaiduExporter#174]
不怎么懂js,只依葫芦画瓢尝试写过js,所以只好开口问问原因了

是不是因为rpc_export_list上挂载的事件被各种取消呢?

另外,解析下载地址获得的, 来自域名 d.pcs.baidu.com及baidupcs.com 的链接, 是不是不是优秀链接, 还需要进一步解析呢?

**Comment by acgotaku** [comment]
@iamxujian 你这说的啥 不明白啊 什么是 使用异常？ 什么是优秀链接？？

**Comment by iamxujian** [comment]
我主要是配合Aria2用, 异常表现在之前版本不更新则无法让aria2启动下载, 以及下载速度并不稳定. 差不多以前能稳定的满带宽下载, 现在有明显的被限速感觉.

我在想会不会是域名的缘故, 是不是可以解析出以前那种稳定速度的URL

**Comment by acgotaku** [comment]
@iamxujian  https://github.com/acgotaku/BaiduExporter/issues/161

**Comment by iamxujian** [comment]
换UA效果果然出乎意料的好.
感谢
