### ISSUE TITLE
OS X上Safari插件应该又被和谐了，但有个小技巧可继续使用，分享一下

### ISSUE THREAD

**Issue by chylqy** [acgotaku/BaiduExporter#176]
OS X最新版本，Safari上最新版本插件，插件可以成功初始化，但选中文件后导出按钮就被消失了。。
偶然机会发现有个小技巧可继续使用，特来分享
选中要下载的文件，然后创建分享，再打开此分享链接，duang 导出按钮神奇的出现了 （可批量下载）

不会用Github，如果这个issue不合适，请删除～

**Comment by acgotaku** [comment]
@chylqy  Chrome好好的你干嘛不用 分享页面可以用 大家都知道啊  ==

**Comment by chylqy** [comment]
😳 好囧啊 哈哈

选择Safari是觉得Safari更顺滑一些  还有一点就是develop菜单里可以快速地禁用javascript
