### ISSUE TITLE
uc浏览器使用插件问题

### ISSUE THREAD

**Issue by stevenjtx** [acgotaku/BaiduExporter#177]
你好，本人使用win7旗舰版64位，uc浏览器版本5.6.11815.13，百度云登录后初始化成功，“导出下载”按钮出现，但是选择要下载的文件时，按钮消失，刷新网页后按钮重新出现，无法实现下载。谢谢

目前环境无法上传截图，不好意思。

**Comment by WongCM** [comment]
windows不是有破解版客户端么 这个不行可以用破解版客户端呀

**Comment by Sasasu** [comment]
#176

>OS X最新版本，Safari上最新版本插件，插件可以成功初始化，但选中文件后导出按钮就被消失了。。
>偶然机会发现有个小技巧可继续使用，特来分享
>选中要下载的文件，然后创建分享，再打开此分享链接，duang 导出按钮神奇的出现了 （可批量下载）

WongCM <notifications@github.com>于2016年4月14日周四 01:40写道：

**Comment by acgotaku** [comment]
@stevenjtx 本插件不支持 UC 谢谢
