### ISSUE TITLE
Aria2下载不稳定的问题

### ISSUE THREAD

**Issue by YCYUNCNB** [acgotaku/BaiduExporter#178]
我使用的是PandoraBOX，有的时候直接导入下载，有的时候导入下载立即失败，需要重新导入下载，有的时候重启路由器会自动续传，有的时候就永远失败了……下载中途失败后从云盘再次导入N次又可以续传了，有什么办法能够提高百度云盘传输的稳定性呢？

**Comment by acgotaku** [comment]
@YCYUNCNB DNS问题??

**Comment by YCYUNCNB** [comment]
我没有开启shadowsocks和ChinaDNS，你这么一说我去试试

**Comment by YCYUNCNB** [comment]
@acgotaku 我没有开启 shadowsocks 和 ChinaDNS，你这么一说我去试试

**Comment by zw963** [comment]
应该是自己网络问题？

**Comment by YCYUNCNB** [comment]
@acgotaku  @zw963  显示的警告是：HTTP response header was bad or unexpected，我重新格式化了U盘，从YAAW换到了Aria2 WebUI，启动了China DNS 保证IP地址在中国，然后，还是出现这个问题……

**Comment by Mapaler** [comment]
路由用U盘不稳定，我之前也用的U，结果挂BT，1个小时就挂了，挂载点没东西了。后来换了移动硬盘，两天了还可以在办公室访问。

**Comment by zw963** [comment]
不懂， 应该没关系吧， 我啥都不用，直接复制下载链接到 Terminal 下运行之。

网络原因，时好时坏， 正常。

**Comment by YCYUNCNB** [comment]
@Mapaler 谢谢提醒，我重新量产了U盘，目前为止没有出现问题了
