### ISSUE TITLE
safari插件问题

### ISSUE THREAD

**Issue by CangJL** [acgotaku/BaiduExporter#179]
打开百度云是看得见插件下载按钮的,但是只要一勾选文件按钮就消失了.请问这个我用法有误还是bug呢?谢谢

**Comment by Sasasu** [comment]
#176
>OS X最新版本，Safari上最新版本插件，插件可以成功初始化，但选中文件后导出按钮就被消失了。。
>偶然机会发现有个小技巧可继续使用，特来分享
>选中要下载的文件，然后创建分享，再打开此分享链接，duang 导出按钮神奇的出现了 （可批量下载）

CangJL <notifications@github.com>于2016年4月16日周六 18:03写道：

**Comment by acgotaku** [comment]
@CangJL 目前只有 Chrome能正常使用 其它版本有待更新
