### ISSUE TITLE
Firefox 国际版 41.0b9 安装插件后网页没有增加菜单

### ISSUE THREAD

**Issue by qokelate** [acgotaku/BaiduExporter#180]
环境:
OSX 10.11.4
Firefox 国际版 41.0b9 (http://ftp.mozilla.org/pub/firefox/releases/41.0b9/mac/zh-CN/Firefox%2041.0b9.dmg)
BaiduExporter 0.6.0

1. 安装插件后 pan.baidu.com 没有出现菜单(菜单栏有图标,点击后跳转到百度盘)
2. 尝试禁用其它所有插件后也是没有出现菜单
3. 在Chrome中安装成功(有菜单,可成功添加下载)

求赐解~~~~~~   不胜感激

**Comment by HarukaMa** [comment]
So just use Chrome for now... until someone port the changes to ff extension

iPhoneから送信

H28/04/18 13:48、sma11case <notifications@github.com> のメッセージ:

**Comment by acgotaku** [comment]
@qokelate FF版本一般是 Chrome版本稳定一周以上才进行更新 
所以先用Chrome 目前插件正在被封杀中。。。 所以其它版本的更新会推迟。。。

**Comment by qokelate** [comment]
ok,非常感谢!
