### ISSUE TITLE
ARIA2搭配花生壳远程下载问题

### ISSUE THREAD

**Issue by z1989c** [acgotaku/BaiduExporter#181]
你好，下载了最新版的插件，在本地局域网使用插件填写局域网ip可以正常下载，使用花生壳DDNS可以登陆上aria2，显示连接成功，但是一下载就会显示“下载出错 HTTP 请求头错误或者无效.”
我又换上了v0.5.9版本的插件，使用完全正常，可以远程下载。
我用的华硕路由固件aria2 1.20.0，不知道这是什么原因，请求帮助。

**Comment by acgotaku** [comment]
这个环境 我不太好模拟啊。。。

**Comment by z1989c** [comment]
哈哈，今天在公司试了一下又能用了，你的插件搭配ddns远程下载很好用啊，谢谢哈。

**Comment by acgotaku** [comment]
你这。。。。

**Comment by z1989c** [comment]
(´･_･`)我发现了，我在公司用的是无痕版的浏览器，aria2就会出现“下载出错 HTTP 请求头错误或者无效.”的情况，用普通的浏览器就能正常下载了。

**Comment by acgotaku** [comment]
纳尼?! 你用的不是官方Chrome?!!!
