### ISSUE TITLE
BaiduExporter and --no-proxy

### ISSUE THREAD

**Issue by qweaszxcdf** [acgotaku/BaiduExporter#182]
I've already add "all-proxy=http://127.0.0.1
no-proxy=baidu.com,baidupcs.com,..and other China's IP blocks" to my config file. It works when I manually add a file to the download list,but when I use BaiduExporter's Aria2 RPC(firefox), the download still use the proxy. I'd appreciate it if someone could help solve this problem

**Comment by acgotaku** [comment]
Because the download process is controlled by the aria2c.exe not the BaiduExporter...

**Comment by qweaszxcdf** [comment]
I ran the command and it didn use the proxy. It seems that aria2rpc overrides the no-proxy setting

**Comment by acgotaku** [comment]
Please submit your question on aria2c...
