### ISSUE TITLE
百度云导出也开始限速了？

### ISSUE THREAD

**Issue by chenlz** [acgotaku/BaiduExporter#184]
从前天开始，单任务只有50kb/s 左右。是我个人如此还是百度升级了？

**Comment by acgotaku** [comment]
我这边还是1m/s 和地区 还有个人网络有关吧 

https://github.com/acgotaku/BaiduExporter/issues/161

**Comment by chenlz** [comment]
![1](https://cloud.githubusercontent.com/assets/721944/14948717/1ca58a72-1076-11e6-9d75-f359c33117ae.png)

个人网络没问题啊

**Comment by acgotaku** [comment]
@chenlz 你试试改UA？ 同一个网址 两个软件的下载速度不一样？

**Comment by chenlz** [comment]
确实是us的问题
更改为netdisk;Chrome Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.87 Safari/537.36 
单线程500kb/s 虽然不如idm 可以恢复使用。
