### ISSUE TITLE
safari装不上插件

### ISSUE THREAD

**Issue by Travical** [acgotaku/BaiduExporter#186]
点了插件后提示我是否要信任插件然后就  点击信任后什么也没发生  ｀｀｀

**Comment by acgotaku** [comment]
@Cee 菊苣召唤～

**Comment by Latias94** [comment]
重启按Shift键进入安全模式再安装

**Comment by Travical** [comment]
谢谢楼上巨巨的帮助   顺便求巨巨解释下为什么安全模式下就能安装成功

**Comment by Latias94** [comment]
百病成医..别问为什么..

**Comment by zanderzhng** [comment]
不需要安全模式，你用鼠标点那个信任是装不上的，得用 tab 切换到那个信任按钮再用空格确定。如果你用 tab 不能切换按钮，可以去系统设置里改一下。
