### ISSUE TITLE
百度云明着给开发者警告？

### ISSUE THREAD

**Issue by Mapaler** [acgotaku/BaiduExporter#189]
这是以前就有的还是现在才有的？之前还真没发现。
![image 4](https://cloud.githubusercontent.com/assets/6565860/15099045/8048774e-157e-11e6-8410-696122ac3a36.png)

**Comment by HarukaMa** [comment]
你会发现各大站都是这样……什么 x 宝啊 x 东啊

iPhoneから送信

H28/05/09 1:40、枫谷剑仙 <notifications@github.com> のメッセージ:

**Comment by acgotaku** [comment]
@Mapaler 这个东西都好多年了啊...

**Comment by Mapaler** [comment]
那是我孤陋寡闻了
