### ISSUE TITLE
0.2.1支持目录下载后无法满速

### ISSUE THREAD

**Issue by ghost** [acgotaku/BaiduExporter#19]
能不能提供原来的下载参数选项，现在所有的文件下载都是目录嵌套式的，因为未知的原因速度严重下降，thx！

**Comment by yjs13genius** [comment]
百度云管家被限速了，至少在我所在的地区是这样（北京），最终限制的速度是1.1-1.2m/s，和走aria2rpc是一样的速度，难道这就是罪魁祸首？命令行这个“User-Agent:
netdisk;4.4.0.6;PC;PC-Windows;6.2.9200;
WindowsBaiduYunGuanJia”是不是代表走百度云管家的代理（网络盲不知道怎么表述这个问题），看来是没有解决方案了？

2014-12-30 14:11 GMT+08:00 雪月秋水 <notifications@github.com>:

**Comment by acgotaku** [comment]
@yjs13genius  自己的产品都限速了 我也没办法啊 QAQ
