### ISSUE TITLE
百度云盘是不是屏蔽的xunlei，xunlei无法使用百度云盘的链接进行下载？

### ISSUE THREAD

**Issue by kidbai** [acgotaku/BaiduExporter#190]
BaiduExporter是不是针对迅雷无法下载百度云盘的链接，提供的使用aria2的解决方案？

**Comment by acgotaku** [comment]
迅雷我没用过不知道 但是这个需要传入 cookies参数的 所以拿到链接也不一定能下载

**Comment by Mapaler** [comment]
所以说导出的下载链接一点用也没有
