### ISSUE TITLE
火狐0.72 分享界面发送无法正常下载

### ISSUE THREAD

**Issue by Mapaler** [acgotaku/BaiduExporter#191]
![image 14](https://cloud.githubusercontent.com/assets/6565860/15133846/5d70273c-1699-11e6-9db4-eef664548fdb.jpg)
在分享页面发送的下载，就会同第一个一样，需要在自己网盘页面发送才能像第二个一样下载成功。
火狐ESR 45.0.1 & BaiduExporter v0.72

**Comment by Cee** [comment]
Chrome 中试一下最新的 0.7.3?

**Comment by Mapaler** [comment]
好像Chrome那边的没问题

**Comment by Iy204** [comment]
firefox还没更新么，真的好久都不能用了。

**Comment by acgotaku** [comment]
最近在面试 更新稍微等等。。。

**Comment by deartonym** [comment]
acgotaku 辛苦了。

**Comment by debiansid** [comment]
Ff还会更新么

**Comment by Mapaler** [comment]
应该不会？
