### ISSUE TITLE
好像度娘有动作了。

### ISSUE THREAD

**Issue by moonsn** [acgotaku/BaiduExporter#195]
同样的资源，同样的机器，不同的网络环境都测试了。
测试了两个资源都这样。
昨天还好好的，今天的就限速了。
是不是该重新抓个包了？

**Comment by ywwzwb** [comment]
工具又不能用了, 控制台提示错误 Cannot find module `disk-system:widget/context/context.js`

**Comment by lautis0503** [comment]
早上还好好的，现在不能用了

**Comment by mrcotter** [comment]
确实已经失效了

**Comment by xkillerz** [comment]
失效了，昨天大概这个时间还正常用来着。现在不能用了

**Comment by RayneHwang** [comment]
暂时可以手动下载文件然后获取链接添加到yaaw里面下载

**Comment by acgotaku** [comment]
更新啦

**Comment by lautis0503** [comment]
更新后测试正常

**Comment by RayneHwang** [comment]
@acgotaku  有意捐助，给个支付宝？

**Comment by acgotaku** [comment]
@RayneHwang YWhudXdhbmdiaWFvQHFxLmNvbQ==

**Comment by RayneHwang** [comment]
@acgotaku gotcha

**Comment by Cee** [comment]
Fixed.
