### ISSUE TITLE
2016.5.18目测已失效

### ISSUE THREAD

**Issue by panw3i** [acgotaku/BaiduExporter#196]
希望更新

**Comment by RayneHwang** [comment]
![image](https://cloud.githubusercontent.com/assets/6406592/15360275/8ac93366-1d3f-11e6-8148-2aa836ac8b0c.png)
目测是因为加载“disk-system:widget/context/context.js”这个文件失败引起的无法初始化，希望lz更新，有意捐助

**Comment by acgotaku** [comment]
更新啦

**Comment by myliyifei** [comment]
牛

2016-05-18 21:36 GMT+08:00 雪月秋水 <notifications@github.com>:
