### ISSUE TITLE
百度云开始限速

### ISSUE THREAD

**Issue by RayneHwang** [acgotaku/BaiduExporter#198]
插件版本0.7.4(5月18日更新)
aria2 1.18.8
更新后可以下载，但是似乎速度被限制在了50KiBps
![image](https://cloud.githubusercontent.com/assets/6406592/15363191/7b1e9f86-1d4a-11e6-9309-465af02d338f.png)

**Comment by RayneHwang** [comment]
目测是UA的问题。这个UA更换有什么规律吗？

**Comment by acgotaku** [comment]
都是抓包 看官方软件的UA
