### ISSUE TITLE
百度网盘是否被限速，请查证

### ISSUE THREAD

**Issue by xkillerz** [acgotaku/BaiduExporter#200]
百度网盘导出下载每个任务都在160KiB/s，而使用aria2下载普通的链接任务（试了ubuntu的镜像）速度可以达到1MiB/s以上。怀疑是否插件导出使用的agent失效，请查证

**Comment by HerringtonDarkholme** [comment]
Duplicate of https://github.com/acgotaku/BaiduExporter/issues/198
