### ISSUE TITLE
求解答

### ISSUE THREAD

**Issue by holoto** [acgotaku/BaiduExporter#201]
## 楼主江西的 使用百度云被限速了
# 求不限速ua 或者其他解限速的方法

**Comment by prenfic** [comment]
台北的表示，速度確實降到為30Mbps/1000Mbps
不確定是否是限速

此外，
開通百度雲的會員以後，
速度用百度雲盤為50Mbps/10000Mbps
估計跟SSHD的最大寫入速度有關

**Comment by holoto** [comment]
我的速度在60kb内徘徊...

**Comment by prenfic** [comment]
![screen shot 2016-05-21 at 11 39 00 pm](https://cloud.githubusercontent.com/assets/13857562/15449336/4c1e32d6-1fad-11e6-9976-241e21324e5b.png)
我覺得你需要檢查一下你aria2c的config

**Comment by holoto** [comment]
https://raw.githubusercontent.com/acgotaku/BaiduExporter/master/aria2c/aria2.conf
这个conf

**Comment by xf1** [comment]
![10m](https://cloud.githubusercontent.com/assets/6897578/15453293/f38a1dba-2042-11e6-8735-f683b3e6247d.png)
我这也是50-100KB/s

**Comment by acgotaku** [comment]
试试这个 UA  netdisk;Chrome Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.87 Safari/537.36

**Comment by v1-hermit** [comment]
netdisk;Chrome Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.87 Safari/537.36
这个一直在400K上下徘徊

**Comment by prenfic** [comment]
看來是寬帶太小，不會是只有5Mbps吧，作個netspeed測試看看，
http://speed.ntu.edu.tw/index_noflash.php

**Comment by Pockyee** [comment]
我也是同样的情况，用了acgotaku提供的UA依然稳定在100k，前天还是8MB/s

**Comment by prenfic** [comment]
用這個吧
要寫進aria2c的config裡面

> user-agent=netdisk;5.2.6;PC;PC-Windows;10.0.10240;WindowsBaiduYunGuanJia
> referer=http://pan.baidu.com/disk/home

國內的話DNS換成
114.114.114.114

然後重開機

**Comment by ocean521** [comment]
辽宁沈阳用户，同样发现已经被限速了，平均50KB。另外如何修改aria2c的config啊，在导出下载的“设置”里修改User-Agent就可以么，尝试修改了，但是速度没有改善。

**Comment by holoto** [comment]
转360网盘了
速度保持在2M/s

**Comment by acgotaku** [comment]
关键是我在日本都是 1m/s以上啊///  这让我怎么测试。。。

**Comment by jtliaw** [comment]
我这里是马来西亚也没有限速的现象！

**Comment by holoto** [comment]
改天试试搭梯子
导出百度云的下载链接~~
嘿嘿 好主意~

**Comment by prenfic** [comment]
修改config的方式，
以下是在intel mac 10.11.5上示範：

根據一開始的設置
在finder的Go to folder輸入：

> ~/.aria2
或是
> ~/.aria2c

在新彈出的頁面，
理論上會有以下三個文件
![screen shot 2016-05-27 at 1 26 34 am](https://cloud.githubusercontent.com/assets/13857562/15583830/1451a954-23aa-11e6-97cf-b1248c7043d9.png)

選擇aria2.config并用textedit.app或是bbedit.app或是textwrangler.app打開

在打開文件的最下端加入以下兩行：

![screen shot 2016-05-27 at 1 27 27 am](https://cloud.githubusercontent.com/assets/13857562/15583891/593ad7ca-23aa-11e6-88b0-cc62a2a40307.png)

> #百度盘
> user-agent=netdisk;5.2.6;PC;PC-Windows;10.0.10240;WindowsBaiduYunGuanJia
> referer=http://pan.baidu.com/disk/home

注意檢查上面是否已經有設置過，
有的話請刪除上面的

接著，
![screen shot 2016-05-27 at 1 29 42 am](https://cloud.githubusercontent.com/assets/13857562/15583924/851472f2-23aa-11e6-87dd-5963662167e9.png)
由於大部分人默認都是以daemon的形式在run的
要再run一次才會套用最新的設置

嫌麻煩的直接重新開機
然後再輸入一次enable rpc的指令
接著打開yaaw之類的客戶端檢查
設置是否已經改變

目前身處於台北
用著實驗室的1000Mbps學術網，
下載速度約8.73Mbps



#以上僅供參考

**Comment by ocean521** [comment]
不是小水管啊，115的速度在2MB，百度云却在40KB。我是在单位使用WINDOWS登陆家里的威联通NAS，刚才在单位爬梯后再次下载速度没有变化

**Comment by ocean521** [comment]
请问使用WINCP是否可以修改config,还是有其他方法，本人WIN用户。另外修改您插件里User-Agent 无效么？

**Comment by acgotaku** [comment]
@ocean521 插件里的UA的优先级是高于aria2c本身设置的 不是无效 是不知道正确的UA应该是多少
我来抓包看看

**Comment by ifreeswan** [comment]
netdisk;Chrome Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.87 Safari/537.36
速度达到2m多

**Comment by ocean521** [comment]
换成这个就好了，保持在2-3MB，谢谢楼上和楼主，我是直接修改插件设置里的UA。要是插件更新是不是这个UA就不会保存了

**Comment by ocean521** [comment]
重启了机器之后，就连不上了。显示“  HTTP response header was bad or unexpected”，大家有没有这种情况。不知道是我自己的问题（刚才尝试做ARIA2的自启动），还是共性问题

**Comment by acgotaku** [comment]
@ocean521 百度更新了 我也更新了

**Comment by holoto** [comment]
@acgotaku 真勤奋! 赞!
