### ISSUE TITLE
下载的速度很慢，而且还经常断

### ISSUE THREAD

**Issue by smellMagic** [acgotaku/BaiduExporter#203]
是百度封杀了嘛？

**Comment by acgotaku** [comment]
就没有详细的说明？ 我用着没问题啊？

**Comment by ocean521** [comment]
同样被限速了~

**Comment by yellowvii** [comment]
使用插件默认的 UA，下载一个 14G 的文件夹，最后有两个文件被限速在 30k 左右。使用
netdisk;Chrome Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.87 Safari/537.36
这个 UA 重新导入下载，可以保持在 400kb 左右
