### ISSUE TITLE
aria2 百度下载不稳定，其他都稳定

### ISSUE THREAD

**Issue by ifreeswan** [acgotaku/BaiduExporter#204]
树莓派安装raspbian，预编译的1.18不稳定，晚上下载源码编译的1.23也还是不稳定，但是其他的下载都没问题，是百度盘的问题吗？

**Comment by ifreeswan** [comment]
netdisk;Chrome Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.87 Safari/537.36
在插件里更换UA，速度达到2m+

**Comment by myliyifei** [comment]
感谢，确实改了UA就可以了

2016-05-27 10:15 GMT+08:00 ifreeswan <notifications@github.com>:
