### ISSUE TITLE
关于速度方面的一些问题

### ISSUE THREAD

**Issue by 1kevin335200** [acgotaku/BaiduExporter#205]
我是在国外学习的，非常感谢您的插件能让我有效地获取百度云资源。但在使用中发现一些事情：
环境：我的网络带宽是250m,目前使用aria2最好的成绩是单文件3m每秒左右。
1.速度波动比较大。下一个2g左右的压缩包，aria2显示连接资源5，但速度有时上3m，但大多在800k-1m左右。这种好像针对于热门度一般的资源。
2.很多资源需要挂代理。本身网络环境达到的速度只有几百k,一挂香港的ss速度就提升明显。因为ss和socks5好像aria2不兼容，目前我还是通过手机连接电脑来达到全局ss的。
虽然通过这些方法最终获得了还能接受的速度，但是原因还是不知道的，感觉就像之前的issues中所说网络环境有很大影响。
知乎对百度云限速的评论中很多教育网用户表示能上10m/s，我想知道能否找到其中原由并得以让大带宽用户同样拥有，因为实际速度和带宽还是差距很大。
3.有一个非常不成熟的想法，我不清楚百度云超级会员账号的下载所分配的不限速节点地址，加上cookie后能否在其他电脑上用，以达到建一个代转存>得到高速节点地址>下载的平台。
以上问题只是闲暇之余的一些想法，若问题毫无意义请谅解，谢谢！

**Comment by acgotaku** [comment]
速度波动和实际网络环境关系很大
我在日本下载的话 速度就没有限制 
而且 下载速度也很文件有关 有的文件就是速度很慢 可能最近的节点服务器上没这个资源

我不是超级会员 本身对会员的机制不是很了解 你想加速的话 就买个超级会员就是了
我要是给普通会员超级会员的地址 百度还不起诉我。。。
你这严重侵犯人家利益了啊

**Comment by 1kevin335200** [comment]
明白。非常感谢您的解释与见解。
