### ISSUE TITLE
是不是又不能用了？chrome插件发送过去直接就失败了

### ISSUE THREAD

**Issue by elicip** [acgotaku/BaiduExporter#206]
如题。都没有出现下载进度条直接失败。

**Comment by ocean521** [comment]
我也是，我还以为是我刚才想做ARIA2自启动错误引起的呢，是不是显示红色的“  HTTP response header was bad or unexpected  ”

**Comment by lautis0503** [comment]
同样问题，更改UA也没用

**Comment by rility** [comment]
same

**Comment by xf1** [comment]
[HttpSkipResponseCommand.cc:239] errorCode=22 The response status is not successful. status=403
百度又更新了吧 ( ╯□╰ )

**Comment by lautis0503** [comment]
大概又更新了，可以通过插件发送，但是下载完全没速度了

**Comment by acgotaku** [comment]
更新啦！！！

**Comment by lautis0503** [comment]
更新后仍然是导出下载直接403

**Comment by acgotaku** [comment]
你先看看版本号是0.7.5么？？

**Comment by rility** [comment]
:( chrome商店还要审核

**Comment by lautis0503** [comment]
是0.7.5无误，直接下载最新版然后手动导入到chrome的。未更新前分享页面可以成功导出下载

**Comment by acgotaku** [comment]
@lautis0503 我只更新了Home页面 分享页面还没  你先保存到自己网盘再下载

**Comment by guoyida** [comment]
chrome商店版本还是0.7.4，看来还没有同步过来，等待中

**Comment by lautis0503** [comment]
然而Home页面无法正常下载。分享页面一直有效

**Comment by acgotaku** [comment]
@lautis0503 ??!  你是不是同时启动了俩插件。。。 导致旧版本的也加载了。。 我这边是能用的

**Comment by lautis0503** [comment]
没有啊，删了旧版

**Comment by acgotaku** [comment]
@lautis0503 你点导出下载 然后把文本框的内容贴出来

**Comment by lautis0503** [comment]
aria2c -c -s10 -k1M -x10 -o "HOLYBREAKER2.part1.rar" --header "User-Agent: netdisk;Chrome Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.87 Safari/537.36"  --header "Referer: http://pan.baidu.com/disk/home"  --header "Cookie: BDUSS=F5MDl4Q21oQmdZWHNGU09RQ2cxcm91UH5zTWN0UTJyU3I5R20wcDhVZzZ2MTFYQVFBQUFBJCQAAAAAAAAAAAEAAABc90QJdmlqb3NseDExMTExAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADoyNlc6MjZXMj;BAIDUID=8400F438E7111A43973990B739261B73:FG=1"  "http://d.pcs.baidu.com/file/ed69262a76dedef5768a5861567e4e3c?fid=4144829083-250528-930450926329583&time=1464354747&rt=pr&sign=FDTAERVCY-DCb740ccc5511e5e8fedcff06b081203-k0rV5I4m2QdXLrnBNwZHmOhl1Lo%3D&expires=8h&chkv=1&chkbd=1&chkpc=et&dp-logid=3429839256677012454&dp-callid=0&r=517745235"

**Comment by rility** [comment]
@acgotaku 借issue问下 为什么不把这个 main button 做成 functional 的呢

**Comment by acgotaku** [comment]
@rility mian button是什么鬼  ？ functional又是啥？

**Comment by acgotaku** [comment]
@lautis0503 你试过其他文件么？

**Comment by guoyida** [comment]
更新后恢复正常，感谢作者的及时更新！

**Comment by rility** [comment]
觉得这个说成中文更别扭一些＝ ＝

就是纯设计角度来看，大多数人最主要功能（ARIA2 RPC）被藏在二级菜单下面，“导出下载”这个按钮本身没有功能，这样挺违和的。

  

On May 27 2016, at 9:15 pm, 雪月秋水 &lt;notifications@github.com&gt; wrote:  

> [@rility](https://github.com/rility) mian button是什么鬼 ？ functional又是啥？

>

> —  
You are receiving this because you were mentioned.  
Reply to this email directly, [view it on GitHub](https://github.com/acgotaku/
BaiduExporter/issues/206#issuecomment-222143199), or [mute the
thread](https://github.com/notifications/unsubscribe/AMlfvjlIg_8ZdByp38-j0DP-P
0MxNqMdks5qFu53gaJpZM4IoPJZ).![](https://github.com/notifications/beacon/AMlfv
tnLohK3-AJjpC-ZNrtbZdfXSHxTks5qFu53gaJpZM4IoPJZ.gif)

**Comment by acgotaku** [comment]
@rility 这个功能性意见 等我重构的时候会考虑改进的

**Comment by acgotaku** [comment]
@lautis0503 这个链接 点进去是可以直接下载的 但是导出会返回 403 我觉得应该是缺少其它的cookies但我没你的调试环境 别人还能正常用。。。 估计没法解决。。。

**Comment by rility** [comment]
感谢🙏更新后一切正常 换UA后速度也有一定提升

**Comment by lautis0503** [comment]
只有我一个人不能用么？
Windows 7 64bit + Chrome  51.0.2704.63 m (64-bit) + aria2 1.23 + BaiduExporter 0.7.5， 陕西联通
那我暂时只能通过分享页面导出了……

**Comment by z5864703** [comment]
@lautis0503 我也是，更新后依旧失败403

**Comment by lautis0503** [comment]
@z5864703 什么环境？我这里分享页面还是可以用的，或许是操作系统/浏览器版本/ISP的锅

**Comment by z5864703** [comment]
@lautis0503 我也是分享页面可以用，home页面不能，目测DNS缓存问题，浏览器和系统应该无法影响这个的

**Comment by acgotaku** [comment]
@lautis0503 对了 你可以把这个文件 分享给我 我来试试 自己是否能导出下载

**Comment by lautis0503** [comment]
@acgotaku 无论哪个文件都无法下载……然而分享页面就正常
http://pan.baidu.com/s/1bpbUeyr

**Comment by z5864703** [comment]
@acgotaku 链接:http://pan.baidu.com/s/1eSe5Ogq 密码:eqf7

**Comment by acgotaku** [comment]
确实是导出的链接不一样 你可以试试重新登录百度云 并且重置插件 和cookies

**Comment by chyiwen** [comment]
入口頁的导出下栽是空白的。可不可能是取得空的值的？
分享後取得的內文是可下載的。
試過重新登录但还是空的

**Comment by lautis0503** [comment]
重新登录/重置插件/清除cookies 均无效，而且连之前的文件都无法下载了，怀疑是ISP的锅

**Comment by 1kevin335200** [comment]
三清后同无效。只有主动分享后有效。
我是更新后发现问题后才来看这个issues的，昨晚还是好的。不知道是不是反而最新版的问题。

**Comment by chakfung2** [comment]
同樣Home頁面不能正常下載。要先分享再到分享頁面才可以正常下載。

**Comment by ocean521** [comment]
同样HOME页不能下载，分享页面正常

**Comment by panjunle** [comment]
感谢更新又可以用了
百度限速了吧？有没有提速的办法！！
50M电信下载稳定在100kb/s  好蛋疼啊。。。。

**Comment by jtliaw** [comment]
0.7.5 确实可以在home页下载了！昨天还不行，今天就可以了！
感谢更新！

**Comment by Leeiio** [comment]
可以了。感谢 @acgotaku 的及时更新。

**Comment by acgotaku** [comment]
@lautis0503  可能你的百度云还是老版本？？ 你试试回退到旧的老版本？

**Comment by dukedhx** [comment]
需要先分享才能下载+1
home界面都是403嗯

**Comment by ZhouZiY** [comment]
需要先分享才能下载+1

**Comment by jtliaw** [comment]
我发现chromium内核48使用插件0.7.5没有效果，必须要chromium内核50使用插件0.7.5才可以

**Comment by lautis0503** [comment]
@acgotaku 百度云web还能更改版本？客户端应该不影响吧？

**Comment by acgotaku** [comment]
@lautis0503 可以再贴一次 导出下载的链接么？ @jtliaw 因为使用了一个比较新的API 只支持 50以上的版本。。。

**Comment by lautis0503** [comment]
Home导出下载：
>aria2c -c -s10 -k1M -x10 -o "[QYQ][CODE_GEASS][25][AVC_FLAC][1080p].mkv" --header "User-Agent: netdisk;Chrome Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.87 Safari/537.36"  --header "Referer: http://pan.baidu.com/disk/home"  --header "Cookie: BDUSS=ktvcHFLUX5qa2ZscTA3aX5FUDNTcTBweXJQbzN0MDNSWnlOdG03SFBOUFZ3SEJYQVFBQUFBJCQAAAAAAAAAAAEAAABc90QJdmlqb3NseDExMTExAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAANUzSVfVM0lXW;BAIDUID=753DCB59C707E2A5F0FA2A65E58561DC:FG=1"  "http://d.pcs.baidu.com/file/2731c6d342e2b390953f7f1e279d326c?fid=4144829083-250528-614664368760334&time=1464432551&rt=pr&sign=FDTAERVCY-DCb740ccc5511e5e8fedcff06b081203-dkun67Luvx1PNGofNhOz0QBwdI4%3D&expires=8h&chkv=1&chkbd=1&chkpc=et&dp-logid=3450724646498586638&dp-callid=0&r=435619664"

Share导出下载：
>aria2c -c -s10 -k1M -x10 -o "[QYQ][CODE_GEASS][25][AVC_FLAC][1080p].mkv" --header "User-Agent: netdisk;Chrome Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.87 Safari/537.36"  --header "Referer: http://pan.baidu.com/disk/home"  --header "Cookie: BDUSS=ktvcHFLUX5qa2ZscTA3aX5FUDNTcTBweXJQbzN0MDNSWnlOdG03SFBOUFZ3SEJYQVFBQUFBJCQAAAAAAAAAAAEAAABc90QJdmlqb3NseDExMTExAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAANUzSVfVM0lXW;pcsett=1464519046-7f09fd2ea8d5a3731f70182fa26c756f"  "http://d.pcs.baidu.com/file/2731c6d342e2b390953f7f1e279d326c?fid=4144829083-250528-614664368760334&time=1464432649&rt=sh&sign=FDTAERVY-DCb740ccc5511e5e8fedcff06b081203-l5g6shPX1jjjRizclAKIdF%2FAUjU%3D&expires=8h&chkv=1&chkbd=0&chkpc=et&dp-logid=3450751082495330932&dp-callid=0&r=357264726"

前者导出后就403，后者下载正常

**Comment by acgotaku** [comment]
@lautis0503 问题知道了 等更新

**Comment by acgotaku** [comment]
@lautis0503 更新了 你再试试？

**Comment by lautis0503** [comment]
@acgotaku 更新后Home导出可以下载了。
之前为什么会有些人正常有些人不正常？

**Comment by acgotaku** [comment]
@lautis0503 因为没有设置正确的 cookies 我觉得还是和最终请求的百度服务器的cookies验证有关 不同的服务器节点 对 cookies的验证不一样

**Comment by xdujiang** [comment]
@lautis0503 你的BDUSS暴露了...

**Comment by lautis0503** [comment]
@xdujiang 不要在意这些细节
