### ISSUE TITLE
0.7.4版本safari插件，在home页面下载出现 HTTP response header was bad or unexpected

### ISSUE THREAD

**Issue by Chillbon** [acgotaku/BaiduExporter#207]
0.7.4版本safari插件，在home页面下载出现 HTTP response header was bad or unexpected

**Comment by acgotaku** [comment]
先用Chrome的 0.7.6的

**Comment by Chillbon** [comment]
还没装chrome的说

**Comment by Cee** [comment]
Safari extension is now under fixing. @Chillbon

**Comment by ahlixinjie** [comment]
嗯  safari的版本确实有这个问题，同一个文件用chrome版本的没问题，请问大大能升级一下Safari的版本么，升级到和chrome版本一样就行了，不怎么习惯用chrome

**Comment by ahlixinjie** [comment]
@Cee 大大 能不能修复一下safari版本的介个问题呀

**Comment by Cee** [comment]
@ahlixinjie Safari Extension 的安全機制比較奇葩...無法獲得全局 or 跨域的 cookie...

**Comment by ahlixinjie** [comment]
@Cee 大大，我不太懂这些，那现在safari版本的能修好吗

**Comment by Cee** [comment]
@ahlixinjie 暫時沒有辦法。不過你可以先分享一下再去下載，share 頁面的是好的。

**Comment by ahlixinjie** [comment]
@Cee 谢谢你的建议，之前我不知道还可以这样用的😄

**Comment by awaixp** [comment]
Firefox也出现了同样的问题，目前chrome版本可用

**Comment by williamlulian** [comment]
系统 环境：OS X EL Captian 10.11.6 、Safari 9.1.2、BaiduExporter.safariextz 0.7.3
问题：Safari 已安装了 BaiduExporter.safariextz 扩展插件，而且已经启用，前几天还好好，这几天就不能用了，打开百度去页面，页面不显示“导出下载 Aria2 PRC ” 标签，这样 Aria2 GUI 也没法用了，重启重装插件都没用。

**Comment by Cee** [comment]
@williamlulian GUI 和插件无关。

**Comment by sequencer** [comment]
@williamlulian 在插件调试把地址改到https就好了。
@Cee 不过现在没法直接导出到aria2c，只能复制链接。后台通讯貌似https上有点问题，有没有办法解决了？

**Comment by hufan-Akari** [comment]
issue 关闭了，是问题解决了吗？Safari 版的 baiduExporter 能用了吗？
