### ISSUE TITLE
获取File失败

### ISSUE THREAD

**Issue by 4ft35t** [acgotaku/BaiduExporter#215]
下午还能正常工作
Chrome: 51.0.2704.79
master 最新代码

**Comment by xkillerz** [comment]
是的，我也是这样，不能正常使用了

**Comment by chyiwen** [comment]
只剩私密分享可用了。度盤最近鉄了心的改革呀。

**Comment by cwbsw** [comment]
充了一个月会员，已搬运3TB，还差50GB就可以告别度盘了，还好私密分享还能用。

**Comment by KwToPA** [comment]
@chyiwen  我公共分享和私密分享那个按钮都消失了

**Comment by acgotaku** [comment]
他又更新 API了 我准备更新最后一版 和百度说 88了

**Comment by Leeiio** [comment]
@acgotaku 难道要转用115么？115速度快么

**Comment by jtliaw** [comment]
说坦白的！使用者的我百度一直这样我看到都累啊，更别说作者，更累！

**Comment by acgotaku** [comment]
百度都要给我发律师函了 我也不想惹麻烦 网盘多的是  我干嘛非要执着于这个

**Comment by KwToPA** [comment]
有个疑问 conf里面我写split=20 但是看demo里只有10线程

**Comment by acgotaku** [comment]
如果你是用的命令行下载 那默认参数就是 10  如果你是 RPC 应该没有这个限制  @KwToPA

**Comment by KwToPA** [comment]
@acgotaku 谢谢您的回复 
我是用aria2c --conf-path=/Users/chenbruce/Downloads/下载器/Aria2/aria2.conf  来下载，之前直接用您的extension导入，现在先手动提取下载链接，然后再粘贴到 http://binux.github.io/yaaw/demo/

```
# 最大同时下载任务数, 运行时可修改, 默认:5
max-concurrent-downloads=2
# 同一服务器连接数, 添加时可指定, 默认:1
max-connection-per-server=10
# 最小文件分片大小, 添加时可指定, 取值范围1M -1024M, 默认:20M
# 假定size=10M, 文件为20MiB 则使用两个来源下载; 文件为15MiB 则使用一个来源下载
min-split-size=10M
# 单个任务最大线程数, 添加时可指定, 默认:5
split=15
# 整体下载速度限制, 运行时可修改, 默认:0
max-overall-download-limit=0K
# 单个任务下载速度限制, 默认:0
max-download-limit=0K
# 整体上传速度限制, 运行时可修改, 默认:0
max-overall-upload-limit=1K
# 单个任务上传速度限制, 默认:0
max-upload-limit=1K
# 禁用IPv6, 默认:false
disable-ipv6=true
#Set interval in seconds to output download progress summary. Setting 0 suppresses the #output. Default: 60
summary-interval=1800
```

**Comment by acgotaku** [comment]
那你可以直接在 yaaw里面输入 split数量啊 而且导入参数的文件路径最好不要用中文

**Comment by KwToPA** [comment]
问题是 yaaw那边是灰色的  默认 10 不能修改

**Comment by acgotaku** [comment]
那就是因为你使用参数启动的 而参数是10  所以不能修改

**Comment by KwToPA** [comment]
这又回到最初的问题了，conf我贴了，写的是split=15

**Comment by lightsing** [comment]
作者准备啥时候更新下？

**Comment by acgotaku** [comment]
这就是你自己的问题了 你的aria2c显示是10 你说你启动的是 15 我只能说你自己可能出错了
请自己耐心的看看自己的配置和启动 而不是来问我 我只是开发插件的 不是负责维护 aria2c的

**Comment by acgotaku** [comment]
@lightsing 下周的某一天 更新也只是通知用户 这个软件到此为止了 我也不想吃官司

**Comment by KwToPA** [comment]
@acgotaku  麻烦您了  谢谢 

其实我用的配置就是你po到G+上的那个。https://blog.icehoney.me/posts/2015-01-31-Aria2-download

**Comment by acgotaku** [comment]
你麻烦我 我也解决不了 这是你电脑的问题 我也不知道具体症状
你是否正确启动了我也看不出来 @KwToPA

**Comment by KwToPA** [comment]
@acgotaku  抱歉，是我自己的问题。
刚看了配置，
```
The number of connections to the same host is restricted by the --max-connection-per-server option. See also the --min-split-size option
```
然后发现自己  max-connection-per-server=10

**Comment by acgotaku** [comment]
@KwToPA  (／‵Д′)／~ ╧╧   自己的问题就不要浪费别人时间

**Comment by KwToPA** [comment]
非常抱歉  ˊ_>ˋ

**Comment by jeromecy** [comment]
我是来支持作者的

**Comment by k1n** [comment]
看来要自己学习一下代码，自己动手丰衣足食了
