### ISSUE TITLE
一点小想法

### ISSUE THREAD

**Issue by 1kevin335200** [acgotaku/BaiduExporter#216]
目前在我的网络环境下aria2好像经常不是下载最快的方式，反而是用idm.因为aria2导出好像没有取到最快的服务器。
我是使用jp,hk,cn,sgp,usa,uk等代理idm后解析所需文件百度云导出地址，然后测试下载速度。一般来说，所选出的速度最快的服务器，关闭代理后直连速度也是最快的。也就是下这个文件最佳的服务器就是这个。当然我碰到过香港的服务器用代理能上5m/s但切直连就不让连的情况。。但大多数没问题
idm下载应该没有ua，2小时后会失效，这是对于aria2法来说很大的一个缺点。我不太清楚，
1.aria2是否可从百度云多个服务器共同取源？同一服务器对同一ip应该有总速度限制，不知多服务器取源可否叠加。（我其实不知道现在的连接数5是指5个服务器还是5个线程。。）
服务器尽管多且有些ip类型的，但是主要的好像也就几个，百度云自动补档助手里面就贴出来了不少。
2.自动测速自动选最优服务器下载。这个我可能想多了。

**Comment by acgotaku** [comment]
我这只是一个Chrome插件 没有这么多权限 和能力解析 最快服务器的  服务器完全是 DNS解析 
但是aria2c的DNS解析 好像不走系统的 这是 aria2c的问题 你在我这边 说 我也做不了什么
