### ISSUE TITLE
Owner不要放弃啊

### ISSUE THREAD

**Issue by xkillerz** [acgotaku/BaiduExporter#217]
在上上个issue下看到owner说准备更新最后一版就不再坚持更新了，希望不要这样做

aria2是我在linux下的主要下载工具，我一般就是用百度网盘离线后导入到aria2下载。这是我认为目前为止最好的linux和mac的下载方式了。如果放弃了这个项目，那么下载东西就麻烦多了

希望owner继续造福我们linuxer，继续坚持

**Comment by acgotaku** [comment]
不是我不维护 是百度要起诉我 请问你给我请律师么？

**Comment by xkillerz** [comment]
@acgotaku 可恶的百度，要不就只放在github上不知道可行不可行？怎么说呢，无论你做什么决定，我都衷心的感谢你一直以来的贡献。当然希望能在不被百恶纠缠的前提下继续下去的话就最好了～

**Comment by acgotaku** [comment]
Github也是公开的 你能看到 百度就看不到了么？ 我也不知道哪个用户是百度派来的卧底 
我这是何必呢。。。我只是一个普通人 我也不是圣人 没有这么大牺牲精神

**Comment by YongMan** [comment]
只供学习和交流，请学习后自行删除....
