### ISSUE TITLE
0.7.6 on Chrome 51.0／Safari 9.1.1  获取file失败

### ISSUE THREAD

**Issue by JasonQKidd** [acgotaku/BaiduExporter#220]
Request URL: `https://pan.baidu.com/api/download?sign=0FROuqPSiCV44k5P%2BwjWm8v%2BylzMCI130ZAexaY1/8caldyUB%2BMZIQ%3D%3D&timestamp=1465001280&fidlist=%5B261242682550374%5D&bdstoken=5604fadd3d1fab9326388c6b19b9a73c&type=dlink&channel=chunlei&web=1&app_id=250528&clienttype=0`

Got:  { errno : 113, request_id : 3603416961016301000}

**Comment by foxluqi** [comment]
Me too

**Comment by wuyafei** [comment]
Me too

**Comment by acgotaku** [comment]
只有 0.7.7 Chrome可用 不用汇报了
