### ISSUE TITLE
0.7.3 on Safari, Http response header was bad...

### ISSUE THREAD

**Issue by wuyafei** [acgotaku/BaiduExporter#221]
如果导出下载，直接报403
06/04 17:05:56 [NOTICE] IPv4 RPC: listening on TCP port 6800

06/04 17:05:56 [NOTICE] IPv6 RPC: listening on TCP port 6800
[#0e612b 0B/0B CN:1 DL:0B]                                                     
06/04 17:05:57 [ERROR] CUID#8 - Download aborted. URI=http://d.pcs.baidu.com/file/3ce0359a66dff6dca375bc69f73504dd?fid=3508864804-250528-2633801356&time=1465031138&rt=pr&sign=FDTAER-DCb740ccc5511e5e8fedcff06b081203-B%2bXfPWKnsRAw8XHsbFhLjKPMPOw%3d&expires=8h&chkbd=0&chkv=0&dp-logid=3611405362698389304&dp-callid=0&r=867803902
Exception: [AbstractCommand.cc:350] errorCode=22 URI=http://d.pcs.baidu.com/file/3ce0359a66dff6dca375bc69f73504dd?fid=3508864804-250528-2633801356&time=1465031138&rt=pr&sign=FDTAER-DCb740ccc5511e5e8fedcff06b081203-B%2bXfPWKnsRAw8XHsbFhLjKPMPOw%3d&expires=8h&chkbd=0&chkv=0&dp-logid=3611405362698389304&dp-callid=0&r=867803902
  -> [HttpSkipResponseCommand.cc:228] errorCode=22 The response status is not successful. status=403

**Comment by Cee** [comment]
Without cookie.
