### ISSUE TITLE
FF可以考虑加个随FF启动Aria2的选项吗？或者直接支持IDM链接？

### ISSUE THREAD

**Issue by OneWizard** [acgotaku/BaiduExporter#223]
Aria2间歇性抽风没速度，而且经常忘开（不过好像可以用UC脚本开启）
IDM下载的话导出再导入简直了，如果直接给出地址链接就能直接调用了

**Comment by acgotaku** [comment]
插件哪来这么大权限。。。 这个插件也不更新了
