### ISSUE TITLE
Chrome获取文件file失败 - "errno":113

### ISSUE THREAD

**Issue by dukedhx** [acgotaku/BaiduExporter#225]
插件调用百度api获取dlink时返回结果如下：
{"errno":113,"request_id":3685608094475177872}

是不是百度又改了得到合法sign字段的逻辑？

Chrome：
Version 50.0.2661.102
插件:
最新

-重新登入登出无效
-三清无效

**Comment by dukedhx** [comment]
才发现又更新了。。。抱歉

**Comment by dukedhx** [comment]
升级7.7之后问题依旧。。。:
BaiduExporter 0.7.7
Assistant for Baidu to export download links to aria2/aria2-rpc

**Comment by acgotaku** [comment]
你应该收到我不更新的推送了啊 还提什么 issue啊，。。。。

**Comment by dukedhx** [comment]
么有收到啊。。。下一个东西到95%断了所以才忍不住提的嗯。。。

**Comment by acgotaku** [comment]
我在更新 0.7.7的时候已经说了 因为再更新就吃官司了 我目前不打算更新

**Comment by dukedhx** [comment]
哦哦抱歉。。。插件什么的事小查水表事大。。。感谢!

**Comment by acgotaku** [comment]
@dukedhx 想用的话就把  Home.js 16行替换成
`var sign = btoa(encode(yunData.sign5, yunData.sign1)) ;`

**Comment by dukedhx** [comment]
依旧error 113...
观察变量发现sign3和sign4的值是相同的，sign1是恒定的。。。尝试了其他组合无效，是不是整个逻辑都改了。。。

**Comment by acgotaku** [comment]
@dukedhx 这个我就不知道了  我这边显示的是 sign5...

**Comment by dukedhx** [comment]
所以是根据节点不一样认证的sign也不一样咯。。。面到库赛义。。。
难道要抓包云管家和服务器的通信。。。。。。。。。-__________-

**Comment by acgotaku** [comment]
@dukedhx 那就不用百度就是了
