### ISSUE TITLE
0.77版本的BaiduExporter在Chrome下导出下载提示"获取File列表失败"

### ISSUE THREAD

**Issue by stevelee477** [acgotaku/BaiduExporter#229]
0.77版本的BaiduExporter在Chrome下导出下载提示"获取File列表失败"

**Comment by zelda0079** [comment]
放弃吧, 不会有新版, 不过这是OPEN SOURCE的, 不知有没有高手接力

**Comment by jshensh** [comment]
诶表示在看了。。不过就怕度受也给俺来封律师信

**Comment by elicip** [comment]
@jshensh 我觉得是因为维护者自己不想浪费时间在和百度周旋上才不维护的，况且百度也并没有给他发律师信，而且用email就可以注册的github帐号百度如何知道是谁？

**Comment by jshensh** [comment]
@elicip 这个就不知道了

**Comment by zelda0079** [comment]
@elicip 即使百度在网络上用官方帐号警告已够阻吓性了

**Comment by xkillerz** [comment]
@jshensh 不要怂，速度搞起

**Comment by sino1641** [comment]
@elicip 那么如何知道clowwindy
