### ISSUE TITLE
發送文件下載問題

### ISSUE THREAD

**Issue by moutian** [acgotaku/BaiduExporter#23]
更新到最新版了，可是現在又有了新問題。如果我選擇了一個目錄下所有文件，aria2rpc發送鏈接，但是只是發送部分鏈接下載了，會少發送很多文件。

**Comment by joutain** [comment]
同样的问题，现在24个文件要通过大概5～6次才能全部发送完。谢谢！

**Comment by acgotaku** [comment]
@moutian  @joutain 了解了我之后会更新下问题的，最近期末考试有点忙

**Comment by acgotaku** [comment]
@moutian  @joutain 已更新～

**Comment by joutain** [comment]
昨天测试了一下，没有再遇到问题

**Comment by acgotaku** [comment]
@joutain 那就关掉issue吧～

**Comment by joutain** [comment]
@moutian 这不是我提到issue啊。

**Comment by acgotaku** [comment]
@joutain 好吧 我手动关掉~
