### ISSUE TITLE
获取File失败!

### ISSUE THREAD

**Issue by TommyJerryMairo** [acgotaku/BaiduExporter#230]
插件版本:  0.7.7
浏览器: Chromium 51.0.2704.79 (64-bit)
系统: x86_64 Linux 4.5.4-1-ARCH
已经尝试清空缓存以及卸载插件并在webstore上重装，问题未解决。

欲下载文件: https://pan.baidu.com/s/1i43S5Hr 密码: s57e (后经测试,任何文件都无法通过插件下载)

![惨案现场](http://img.vim-cn.com/31/b850d5b1af70960cc1fcb019a211f3a0e724d1.png)

Reproduce:
- 进入https://pan.baidu.com/
- 提示`初始化成功`
- 选中下载目标,并点击导出下载
- 提示`获取File失败!`

**Comment by causlayer** [comment]
我是今天下午头一次配置，设置了token，这个问题还存在。
![2c82dc0c-62cf-4f35-b7b2-f58cd96550a4](https://cloud.githubusercontent.com/assets/7320355/15928600/6e6a9cb8-2e7a-11e6-9309-5a12e7a84227.png)
![7cf75386-aac4-494f-85dd-7e287539706b](https://cloud.githubusercontent.com/assets/7320355/15928601/6e6c44be-2e7a-11e6-8608-bab46d5a47ce.png)

这个问题，设置了token，还是不行。

**Comment by Leeiio** [comment]
此项目已死。已不再更新了。

**Comment by causlayer** [comment]
@Leeiio 请问有没有接替的项目，谢谢

**Comment by causlayer** [comment]
@TommyJerryMairo 我的问题解决了，是这样操作的，把这个文件保存到自己的盘里，然后创建公开链接，再点RPC下载就可以了，希望能帮到你，不过估计被封堵也就这两天的事了。

**Comment by zelda0079** [comment]
@causlayer 你的方法如果是用在一分享就被屏蔽的档案就不行了, 而且下载次数太多时会要求打验证码

**Comment by causlayer** [comment]
@zelda0079 每个人创建自己的公开链接下载量不会高，下载完之后可删除文件，步骤虽然繁琐，可解燃眉之急。

**Comment by siyanmao** [comment]
百度那边直接返回错误113，API被封了吗？

**Comment by taocwang** [comment]
求推荐新插件！

**Comment by KwToPA** [comment]
@causlayer  请问你的chrome 和 这个插件的版本是什么？  我这边导出消失了  我清空过cookies也没用

我的
Version 51.0.2704.84 (64-bit)
os x 10.10.10

baiduexpoter 0.77

**Comment by KwToPA** [comment]
我分享页面的按钮也没用

**Comment by zelda0079** [comment]
@causlayer 错了, 即使创建非公开链接, 如果那些东西已被百度禁了, 就不能分享, 这和是否多人下载无关, 而是档案是否曾被举布/百度发现

**Comment by gfzhai** [comment]
@zelda0079 确实无法分享，无论是公开的还是非公开的链接

**Comment by p1naster** [comment]
就不能压缩吗？

**Comment by p1naster** [comment]
压缩了再下载，创建公开链接确实可以添加任务！

**Comment by ywwzwb** [comment]
签名算法的问题, 百度最近一直疯狂的在改

**Comment by Peekinghills1** [comment]
I hope this issue can be fixed one day! I use your extension a lot because it can use the full speed of my internet connection. I guess Baidu's API changed? I also use bcloud and that program doesn't work anymore.

**Comment by zelda0079** [comment]
@p1naster 线上压缩功能好像要vip才有, 当然可以压缩后再上传, 不过百度云无力的上传速度(冷门文件方面)令人很困扰, 而且也不能用上秒传
