### ISSUE TITLE
A small trick to find sign

### ISSUE THREAD

**Issue by typcn** [acgotaku/BaiduExporter#232]
Sign 是通过 yunData.sign2  这个函数获取的，那么我们如何在不进行任何逆向的情况下，瞬间找到关键代码呢？

![image](https://cloud.githubusercontent.com/assets/8022103/15979288/b86b4d00-2f95-11e6-9eeb-0e88f49c0b81.png)

然后随便点一个文件下载，抛出异常之后，Chrome 就可以直接查看调用栈了

![image](https://cloud.githubusercontent.com/assets/8022103/15979319/ec412956-2f95-11e6-9e5c-782005123e2f.png)

![image](https://cloud.githubusercontent.com/assets/8022103/15979428/83d5fca6-2f96-11e6-8449-cd9aa58c272d.png)

这些都是一些调试中的小技巧，看似简单，但是非常节省时间，他们花几个小时来改，你一秒钟就定位了关键。

我还有数不清的方法，每次它失效之后，我都会不定时来更新。

Preety Easy , Good Luck

**Comment by acgotaku** [comment]
嘛 这个我也是知道的 只是最近不想更新 躲躲风头 也顺便打算重构下代码

**Comment by typcn** [comment]
嗯，留在这里，大家看到自己改

**Comment by kakalong** [comment]
谢谢@typcn ，已正常使用中

**Comment by kujingzaidi** [comment]
看不懂怎么用的

**Comment by HerringtonDarkholme** [comment]
@typcn 原来是CTF大大！

**Comment by acgotaku** [comment]
@HerringtonDarkholme  H菊苣！

**Comment by xkillerz** [comment]
@kakalong 可以给一下使用方法吗

**Comment by JasonQKidd** [comment]
奇怪了，我的console里没有抛出异常

**Comment by JasonQKidd** [comment]
为啥我这的调用栈现实的不一样？
![screen shot 2016-06-13 at 9 00 49 pm](https://cloud.githubusercontent.com/assets/3359899/16028124/04e9acc4-31aa-11e6-88c7-f51f23ae5fa8.png)

**Comment by ocean521** [comment]
如何解决呢，求大神指教

**Comment by simonliu009** [comment]
有没有给小白的使用方法，哪里要改?

**Comment by xuchenkai** [comment]
@simonliu009 分享要下载的文件 可获取

**Comment by YuningMiao** [comment]
为什么我的console 不会throw error。。。

**Comment by HerringtonDarkholme** [comment]
Intended for advanced users
