### ISSUE TITLE
0.7.9 chrome導出無反應

### ISSUE THREAD

**Issue by saeVirginia** [acgotaku/BaiduExporter#234]
以前有下載成功或者獲取失敗這樣的提示 現在什麼提示也沒有 也不能傳到aria 選擇導出下載連接也是空白  
而且導出按鈕那邊也少了一個離線下載不知道有沒有關係
<img width="536" alt="screen shot 2016-06-18 at 05 35 11" src="https://cloud.githubusercontent.com/assets/17364353/16169036/944d89fc-3516-11e6-93c4-c7a02ae3f049.png">
TTATT球修復

**Comment by acgotaku** [comment]
你难道不知道有句话 叫闷声发大财么？！  我都写了不更新了 你还来提 issue 非要做死么
