### ISSUE TITLE
0.7.8后增加了新的权限要求吗？

### ISSUE THREAD

**Issue by wuwenbin** [acgotaku/BaiduExporter#236]
项目都暂停更新了，为什么chrome插件还有新版本？我的chrome提示最新版百度网盘助手需要新的权限， 为什么？源代码也没见更新，就更新了几个小版本，我不敢启用，怕被查水表。希望能有个说明。
（抱歉刚刚还提了一个无效issue，题目没打完不小心按了回车什么的，结果发出来了。我不知道怎么删，只能先close了）

**Comment by acgotaku** [comment]
不敢用 就不用 就这么简单 权限更新是把权限缩小了 不相信就别用

**Comment by wuwenbin** [comment]
抱歉，听说百度发邮件警告了，我只是担心百度接手了这个项目来查水表。
我也一直是这个工具的忠实使用者，作者都出来说明了，我还是愿意相信的，已经启用了。
感谢你的这个项目，很好用哦。

**Comment by acgotaku** [comment]
我只是低调给你们升级 还关掉了升级提醒 你非得再这起哄 商店是我的帐号 还能被百度盗号了不成？！

就不能好好闷声发大财么！
