### ISSUE TITLE
好像被“调戏”了呀

### ISSUE THREAD

**Issue by wanglongqi** [acgotaku/BaiduExporter#237]
0.7.9，打开Console之后来那么一条：
> 咦！这么巧你也喜欢研究WEB技术！
> 又这么巧我们急需像你这样的专业WEB人士!
> 来百度云吧，和我们一起改变百度云！改变云存储！
> 职位介绍，前端：http://dwz.cn/mbufe 后端：http://dwz.cn/frvsI
> speed-disk-home_f684d8c.js:1 
> 请将简历发送至  spacehr@baidu.com（ 邮件标题请以“姓名-应聘XX职位-来自console-FE/SERVER”命名）

这程序员在调试界面卖萌也是感觉很有趣呀:)

**Comment by sino1641** [comment]
莫非是百度官方接受了这个项目。。。

**Comment by jshensh** [comment]
@sino1641 看来作者是被钦定了

**Comment by acgotaku** [comment]
这个早就是两年前百度就有的玩意了。。。

别闹 好么。。。。 反馈这个输出也是好几回了。。。

**Comment by wanglongqi** [comment]
@acgotaku 收到
