### ISSUE TITLE
提示下载失败！是不是没有开启aria2

### ISSUE THREAD

**Issue by goodryb** [acgotaku/BaiduExporter#239]
后台已经开启了，web-ui也能正常连接，但是提示下面这个

![](http://7xqpyi.com1.z0.glb.clouddn.com/2016-06-23_19:41:07.jpg)

MAC OSX  EI
扩展是chrome商店下载的最新版本，0.8.0

**Comment by sino1641** [comment]
建议自行Git 并加载到Chrome
原因你懂的

**Comment by goodryb** [comment]
研究了一下，应该是默认的连接地址要修改一下
导出设置里面的RPC地址要改成token形式的

http://token:<token>@localhost:6800/jsonrpc

**Comment by tsuriyu** [comment]
同求解决方法，试了楼上的，然并卵

**Comment by ykqmain** [comment]
@goodryb   @tsuriyu 
试试aria2gui 
https://github.com/yangshun1029/aria2gui

在导出之前，只要打开这个app就行了
