### ISSUE TITLE
下载被限速

### ISSUE THREAD

**Issue by xurubin** [acgotaku/BaiduExporter#24]
感觉伪造百度云4.x版本UserAgent的下载方式已被大大的限速，只有几十kb/s。即便是官方的4.x旧版本百度云客户端也是龟速。不知是因为官方发现太多人abuse这个办法，还是只是故意想要淘汰旧版本客户端。

同一时间同一IP下载同一个文件，用5.x的百度云客户端速度就是正常的。我试过人工改UserAgent到5.x，不过没有效果。用Wireshark粗粗的看了一眼，5.x的获取下载链接方式已经与旧版本不同。百度应该是彻底限速了旧版本的文件下载方式。想要突破限制，只有通过模拟新版本的下载方式。

**Comment by yjs13genius** [comment]
新版本的客户端也是限速的，吃白食的日子一去不返了

**Comment by acgotaku** [comment]
我这才更新又封啊...... 百度这个没节操的.....

**Comment by yellowvii** [comment]
我这边100M电信，速度稳定到5MB/s，速度也还好啊。几十KB的速度有可能是ISP的限制吧？

**Comment by xurubin** [comment]
Hmm，又试了下，用5.x官方客户端速度也非常低。看来的确和下载方式无关，上次速度高可能是碰巧官方客户端同时触发了p2p下载。

**Comment by k1n** [comment]
前几天还很愉快的下载，现在被限速了。另外如何查看更新？谢谢。

**Comment by acgotaku** [comment]
@k1n 点击设置 左下角会有版本号 和更新日期 最新版是 0.3.0版本
