### ISSUE TITLE
如果想接手这个插件,需要多深的功底.......

### ISSUE THREAD

**Issue by wszgrcy** [acgotaku/BaiduExporter#240]
自我感觉,看个网页的一些元素框架还能看的懂,一些JavaScript的基础知识也会一些,但是一看各大网站的JS,就根本不知道相关的功能是如何实现的.,我估计可能是我水平不高,那么有木有可以填补这部分空白的资料或者书籍?

**Comment by acgotaku** [comment]
嘛 我也不知道你的水平 这让我怎么说呢 

不懂的知识多查查这个网站就好 https://developer.mozilla.org/en-US/

**Comment by v1-hermit** [comment]
需要的功底不浅。只会JS和DOM的话，到实现这个插件 应该还有很大一段距离，比如chrome\firefox扩展开发相关知识
