### ISSUE TITLE
ourdvsss是哪家的服务器呢？

### ISSUE THREAD

**Issue by sino1641** [acgotaku/BaiduExporter#241]
最近使用插件发现部分资源会解析到ourdvsss的域名。
![ourdvsss](http://i2.piimg.com/4851/ba204810a01a2c2f.png)
目测是百度新增的cdn么？

**Comment by acgotaku** [comment]
哈？ 这为啥要问我。。。 我又不是全能的

**Comment by chenshaoju** [comment]
经查和反复研究。
这个可能是你使用的是中国电信的宽带。
而这个是电信的一个缓存服务器。

**Comment by BROBIRD** [comment]
@chenshaoju 不是，这是网宿的CDN

**Comment by skymods** [comment]
@chenshaoju 我在国外下载百度网盘的东西有时也会解析到这个地址

**Comment by chenshaoju** [comment]
Hmmm...

**Comment by sino1641** [comment]
@chenshaoju 并不是电信宽带
@acgotaku 只是因为NOD32会屏蔽，比较疑惑
