### ISSUE TITLE
最近是不是被百度封锁了？

### ISSUE THREAD

**Issue by searene** [acgotaku/BaiduExporter#242]
之前用的很好，感谢作者的辛苦付出。

最近下载过程中，下载速度从一定值开始递减，最后就一直维持在速度0或者n KB/s的速度上，这个现象持续很长时间了，换了网络环境也是一样，不知道我这是个例还是该扩展已被封杀。

**Comment by acgotaku** [comment]
我使用一切正常

**Comment by zelda0079** [comment]
是资源太冷门? 暂停之后再开始会不会变正常?

**Comment by searene** [comment]
@zelda0079 保存到百度网盘的话应该就不存在资源冷门的问题了吧，毕竟百度的服务器上已经存上去了。暂停之后也是一样，最近换了网络，暂时没有这个问题了，我等再出现这个问题的时候提供网络环境和资源。
