### ISSUE TITLE
在safari下安装此插件，然后卸载，会发现safari的默认百度搜索引擎失效

### ISSUE THREAD

**Issue by OnlyForFunTest** [acgotaku/BaiduExporter#243]
在将safari的默认搜索引擎设置为百度的情况下，安装了该插件，然后再卸载该插件。会发现，在登陆百度/百度云账号的情况下，直接在地址栏输入任意内容进行搜索，无法跳转～而且点击查看safari扩展相关功能，也是点击无效～～清除百度相关cookie后，则恢复正常。这是什么情况造成的？？？

**Comment by acgotaku** [comment]
Safari目前已经停止维护了。。。 我不清楚情况  @Cee

**Comment by Cee** [comment]
這個和我們一點關係都沒有啊...
