### ISSUE TITLE
百度网盘“保存到我的网盘”功能失效

### ISSUE THREAD

**Issue by nakiyami** [acgotaku/BaiduExporter#246]
你好

进别人的网盘，想把文件转存到自己的网盘，选好路径之后点击确定无效，页面没有反应。停用baiduexporter后正常。

chrome版本 51.0.2704.106 (64-bit)
windows10 64bit
baiduexporter版本 0.8.0
尝试过重启浏览器，重启电脑，重装插件。
插件其他功能一切正常。

**Comment by nakiyami** [comment]
清楚cookie之后好了，不知道什么原因

**Comment by nakiyami** [comment]
重启后又不能保存到我的网盘

**Comment by sino1641** [comment]
那就停用吧。

**Comment by acgotaku** [comment]
是保存了  但是没有提示了 这个问题之后我会修复的

**Comment by nakiyami** [comment]
谢谢的你回复
我再确认了一下，确实是没有保存的，那个保存界面的蓝色确定按钮按下去只有一个点击动画。
chrome开发者工具里面的报错是Uncaught TypeError: Cannot read property 'substr' of undefined                             

convert.js:233

**Comment by nakiyami** [comment]
saveConvertFile	@	convert.js:233
getConvertFile	@	convert.js:198
(anonymous function)	@	convert.js:318
dispatch	@	all_480f92a.js:4
s	@	all_480f92a.js:4
