### ISSUE TITLE
无法下载所有文件

### ISSUE THREAD

**Issue by sino1641** [acgotaku/BaiduExporter#247]
今天发现 无法使用插件下载所有文件。
与以往不同，目前解析到
`http://d.pcs.baidu.com/file/*`
并无法用内置浏览器或IDM下载。
尝试使用百度云管家发现MD5全部不对-_-||

**Comment by acgotaku** [comment]
==  你这说的什么问题我也不明白。。。

**Comment by donglin2000** [comment]
试试清空浏览器的cookie呢。

**Comment by sino1641** [comment]
@donglin2000 RP问题吧。。过几天就能下载了

**Comment by sino1641** [comment]
@acgotaku 使用IDM下载 提示403

**Comment by acgotaku** [comment]
@sino1641  IDM目前只能公开分享可以使用 其它已经无法解决了 因为有Cookies限制

**Comment by sino1641** [comment]
@acgotaku 
公开分享也不能用IDM
导入aria2的话下载回来的文件MD5大多不正确
不过发现改UA方法又能用了，大文件也可以直接用IDM
