### ISSUE TITLE
无法保存配置

### ISSUE THREAD

**Issue by troyliu0105** [acgotaku/BaiduExporter#249]
无法保存配置, 每次重新进入后都恢复成默认配置, 默认的rpc地址, 导致只能使用本地aria2
清除缓存,重新安装等无法解决

- 插件版本: 0.8.2
- 浏览器版本: Chrome 51.0.2704.103 (64-bit)
- 系统版本: MacOS 10.11.5

**Comment by acgotaku** [comment]
你看看终端是否有报错 我这边是没有问题的  ==

**Comment by troyliu0105** [comment]
也没有报错, 提示保存成功,但是一刷新网页, 又恢复默认设置了... 哎....😭

**Comment by acgotaku** [comment]
你是不是权限之类的设置有问题？？给个截图看看？ 整个演示一下

**Comment by troyliu0105** [comment]
[LOG.mov](http://7xk54v.com1.z0.glb.clouddn.com/log.mov)
录了一段屏......  😂

**Comment by acgotaku** [comment]
分享页面的设置确实有问题  但是个人主页上的是没有问题的

**Comment by troyliu0105** [comment]
soga... 先在个人页面上面设置好了, 在分享界面也可以生效...... 这样也算是解决了...😌

**Comment by acgotaku** [comment]
@troyliu0105 新版本更新解决了
