### ISSUE TITLE
User-agent配置失效

### ISSUE THREAD

**Issue by mikelei8291** [acgotaku/BaiduExporter#251]
文件地址: `http://d.pcs.baidu.com/file/4c308c326dd6945dd1c5768cfa621141?fid=3423548190-250528-218107573032634&time=1469522492&rt=pr&sign=FDTAERVCY-DCb740ccc5511e5e8fedcff06b081203-qmI78CUHFBNHY6IHwco0%2FLdH5h0%3D&expires=8h&chkv=1&chkbd=1&chkpc=et&dp-logid=4817045267897669922&dp-callid=0&r=875328377
`
插件版本号: `0.8.4`
浏览器版本号: `Chrome 54.0.2807.1 canary (64-bit)`
系统版本号: `Windows 10 (本地), Ubuntu 14.04 (服务器)`
aria2版本号: `1.24.0`

在插件的设置里修改了User agent，本来应该有很大的提速效果但是并没有出现，在aria2的配置文件里配置以后却可以达到本该有的效果，由此推断插件的user-agent配置失效

**Comment by acgotaku** [comment]
你用的UA发来 我试试

**Comment by mikelei8291** [comment]
用的是iPhone 6的UA，但是不知道现在被封了没。。

**Comment by acgotaku** [comment]
倒是发个UA过来啊。。。

**Comment by mikelei8291** [comment]
http://stackoverflow.com/questions/12305566/what-is-the-ios-6-user-agent-string

**Comment by haixinn** [comment]
netdisk;5.3.4.5;PC;PC-Windows;5.1.2600;WindowsBaiduYunGuanJia  之前3M 现在300k

**Comment by mikelei8291** [comment]
不能解决吗？另外换了UA以后直接点击下载的地址都和本扩展获得的不同，本扩展获得的地址就算换了UA下载也还是慢。而自己换UA打开网页后点击下载按钮获得的地址却很快

**Comment by acgotaku** [comment]
@mikelei8291 你不是换了 UA解决了么 主要是我这边默认UA一直满速的 我没法调试 QAQ

**Comment by mikelei8291** [comment]
那好吧。。
