### ISSUE TITLE
ARIA2无法下载

### ISSUE THREAD

**Issue by sino1641** [acgotaku/BaiduExporter#252]
使用默认配置下载，在webui上看到所有文件均显示

> × download was successful

且文件并没成功下载。

**Comment by acgotaku** [comment]
@sino1641 有没有详细的说明？

**Comment by yh127** [comment]
我也是这个问题，只能导出但下载失败。清空缓存甚至重装chrome后，再重新安装0.86插件仍然是这个问题。

**Comment by acgotaku** [comment]
没有具体错误输出啥的 我也很困扰啊 == 命令行运行看看日志？

**Comment by yh127** [comment]
09/10 16:43:48 [ERROR] CUID#10 - Download aborted. URI=https://d.pcs.baidu.com/file/93a2c9406b5d2d9fa147f5d0fbb85b55?fid=993888657-250528-192728970378037&time=1473497028&rt=pr&sign=FDTAERVC-DCb740ccc5511e5e8fedcff06b081203-ZkzNcwvEh1xhUEOtOhCbwinowPw%3D&expires=8h&chkv=1&chkbd=1&chkpc=&dp-logid=5883951750075727648&dp-callid=0&r=552548097
Exception: [AbstractCommand.cc:350] errorCode=1 URI=https://d.pcs.baidu.com/file/93a2c9406b5d2d9fa147f5d0fbb85b55?fid=993888657-250528-192728970378037&time=1473497028&rt=pr&sign=FDTAERVC-DCb740ccc5511e5e8fedcff06b081203-ZkzNcwvEh1xhUEOtOhCbwinowPw%3D&expires=8h&chkv=1&chkbd=1&chkpc=&dp-logid=5883951750075727648&dp-callid=0&r=552548097
  -> [SocketCore.cc:1015] errorCode=1 SSL/TLS handshake failure:  `not signed by known authorities or invalid' `issuer is not known'

**Comment by acgotaku** [comment]
@yh127  

`#不进行证书校验
check-certificate=false`

aria2c参数关掉证书

**Comment by acgotaku** [comment]
` 
check-certificate=false`
@yh127  关掉证书

**Comment by yh127** [comment]
我是导出到局域网，之前一直很正常，前段时间突然出现无法下载，现在加入 check-certificate=false 这个参数再重运行aria2就可以了。困扰了大半个月的问题终于解决了，多谢！！！

**Comment by bsdcpp** [comment]
最好的办法是安装证书，在~/.aria2/aria2.conf里指定证书路径
ca-certificate=/etc/ssl/certs/ca-certificates.crt

我在群晖NAS里就遇到这个问题，不指定，它找不到，加了就ok

**Comment by ChiaSang** [comment]
请尝试把file-allocation=none试试
