### ISSUE TITLE
Please add https support.

### ISSUE THREAD

**Issue by masterhou** [acgotaku/BaiduExporter#254]
Sometimes, baidu pan will be opened with https.
Thank you, it's very useful!

**Comment by acgotaku** [comment]
Of course. It is support https.

**Comment by masterhou** [comment]
Sorry, I said about Safari. In info.plist, it match "http*"

**Comment by Cee** [comment]
@masterhou Take it!
[BaiduExporter.safariextz.zip](https://github.com/acgotaku/BaiduExporter/files/405927/BaiduExporter.safariextz.zip)

**Comment by TypesTse** [comment]
It's so nice of you to update the Safari extension to help it accommodate with the "https" based Baidu Cloud, while the new version still does not work well to coordinate with aria2 on Safari, after checking the debug bar,it shows alarms with the following style:

[blocked] The page at https://pan.baidu.com/s/xxxxxxxx was not allowed to display insecure content from http://localhost:6800/jsonrpc.

**Comment by TypesTse** [comment]
@Cee
It's so nice of you to update the Safari extension to help it accommodate with the "https" based Baidu Cloud, while the new version still does not work well to coordinate with aria2 on Safari, after checking the debug bar,it shows alarms with the following style:

[blocked] The page at https://pan.baidu.com/s/xxxxxxxx was not allowed to display insecure content from http://localhost:6800/jsonrpc.

**Comment by masterhou** [comment]
@TypesTse 
yes, I use nginx as a https proxy to fix this block
also, i think may use iframe.
