### ISSUE TITLE
添加扩展, 但是Chrome打开百度云的时候, 压根就没有导出下载这个东西...

### ISSUE THREAD

**Issue by CainRun** [acgotaku/BaiduExporter#255]
添加扩展, 但是Chrome打开百度云的时候, 压根就没有导出下载这个东西...

**Comment by acgotaku** [comment]
????  我这边正常。。。

**Comment by cor961** [comment]
正常的，有的时候是不显示，刷新一下页面就出来了。

**Comment by CainRun** [comment]
好的, 我刷新了之后, 发现的确是有的, 谢啦

**Comment by river1** [comment]
我也发现这个问题，有时刷新好多次不显示，换了隐身状态又能显示，可能是跟某个插件有冲突吧
