### ISSUE TITLE
能否增加一个“关闭/开启 复制网盘文件夹结构”的选项开关？

### ISSUE THREAD

**Issue by yellowvii** [acgotaku/BaiduExporter#26]
有时候百度盘直接转存别人的文件夹，路径很深，下载到路由器上的时候就有些尴尬了。
火狐在更新到0.2.7 之后默认是不复制网盘文件夹结构了吗？好像找不到开启的方式，希望能够手动选择这个功能的启用或关闭~
非常感谢作者的付出！~

**Comment by acgotaku** [comment]
不对啊 默认下载是保存网盘文件夹结构的 符合要求啊? 
能否举个例子来说明啊 不太明白要表达什么

**Comment by yellowvii** [comment]
![image 1](https://cloud.githubusercontent.com/assets/5602263/5665628/b9a45a4e-9794-11e4-86ae-2fc8e2c42b1b.png)
这是Chrome 配合 0.2.5 版本插件截取的。
像这效果就是没有复制网盘文件夹结构，对于资源目录很混乱或者只想下载其中一部分的情况下很有用。

![image 3](https://cloud.githubusercontent.com/assets/5602263/5665961/36778ba2-9797-11e4-8967-d868ca4f2a81.png)
这是火狐 配合0.2.1版本插件截取的。
在火狐的0.2.1版本是从根目录到最深层的目录结构复制的，下载整理好的资源很方便。

我的意思就是加一个可以调整的开关，全保留和不保留之间切换，或者自定义一个保留层数。

**Comment by acgotaku** [comment]
@yellowvii  我这都更新到0.2.8版本了  亲 最新版早就解决这个问题了 火狐 0.2.7也没任何问题

**Comment by yellowvii** [comment]
@acgotaku 可能是我表达的不太清楚，我之前是用0.2.1，默认一直保存最完整的目录结构，下载一个文件，会有N个文件夹被创建。在整理好的网盘文件夹中取部分文件，这种策略很有用。
网盘路径为`/a/b/c/d.zip` 进入 `c`文件夹，下载`d.zip` ，路由器目录结构就是 `a/b/c/d.zip`。

后来升级到0.2.7，下载目录中的单文件，默认是不保存目录结构，只有在导出文件夹时保存此文件夹的目录结构。在整理好的网盘文件夹中取部分文件，就没有办法复制完整的目录结构了。
网盘路径为`/a/b/c/d.zip` 进入 `c`文件夹，下载`d.zip` ，路由器不保存目录结构，就是`d.zip`文件。
在`b`目录下载`c`文件夹，路由器目录结构是`c/d.zip`。

并不是说有什么BUG，就只是希望能让用户选择目录结构的复制策略。
请原谅我低下的表达水平……

**Comment by acgotaku** [comment]
@yellowvii 你是说你有时候需要完整的路径 有时候却只想要当前的文件 不生成文件夹路径？

**Comment by yellowvii** [comment]
是的，就是这个意思，如果能支持自定义保留几层就更棒了。
我现在写东西真是越来越也啰嗦了，囧 。

**Comment by acgotaku** [comment]
@yellowvii  保留几层是从前面保留 还是从后面保留？ 举个例子？

**Comment by yellowvii** [comment]
`b/a.zip`是一层，`c/b/a.zip`是两层，以此类推。
2015年1月9日 下午12:57于 "雪月秋水" <notifications@github.com>写道：

**Comment by acgotaku** [comment]
@yellowvii   0.2.9已经添加了这个功能 请更新~

**Comment by yellowvii** [comment]
已更新，看到设置项了，等晚上回家测试一下效果~~非常感谢！
还有一个小疑问，如果设置的层数大于实际层数，应该是按照实际层数来保留吧？

**Comment by acgotaku** [comment]
@yellowvii 对的,如果超过的话会有警告提示  但是会按照实际的最大层数显示

**Comment by yellowvii** [comment]
@acgotaku 资源收藏控的福音啊！超级棒~谢谢谢谢谢！~

**Comment by acgotaku** [comment]
@yellowvii 哇哇哇~ 好感动~
