### ISSUE TITLE
已安装的附加组件被 Firefox 禁用，我该怎么办？

### ISSUE THREAD

**Issue by fratcn** [acgotaku/BaiduExporter#260]
https://support.mozilla.org/zh-CN/kb/add-ons-signing-firefox?as=u&utm_source=inproduct#w_ihgoceoeoeoakekice-firefox-daeekunagcasinozka

**Comment by giveup** [comment]
release版不再允许安装未签名的addon.（除非自己编译）
其他版本可以

**Comment by acgotaku** [comment]
FireFox目前也不能用。。。等我忙完论文再更新啊 QAQ
