### ISSUE TITLE
 插件在 aria2_1.17下任务失败，1.19和1.25下正常

### ISSUE THREAD

**Issue by IMLR** [acgotaku/BaiduExporter#262]
Mac 上安装的是1.19版本，现在导出下载功能均正常，一般用于小文件的下载。

群晖 Nas 上安装的是1.17版本（目前能找到的最高版本），用于下载大的文件，之前一切正常，今天发现百度云导出下载任务全部失败，用手机的 aria2 客户端 Avee 登录百度盘点击下载可以添加任务，应该不是百度盘对于1.17做了屏蔽。但115导出下载正常。
怀疑插件问题，但导出到Mac 上安装的1.19版本 aria2正常， 升级到1.25也正常使用。
怀疑是配置文件问题，但修改了之后没有效果。

是否新版插件不兼容1.17版本？

**Comment by acgotaku** [comment]
你启用了 验证功能么？ 这种格式 --rpc-user=<username> --rpc-passwd=<passwd>

**Comment by IMLR** [comment]
并没有，之前是正常的，也没有启用验证

**Comment by acgotaku** [comment]
1.17版本的报错是什么？
