### ISSUE TITLE
提示Exception: [SocketCore.cc:874] errorCode=１请问怎么解决？

### ISSUE THREAD

**Issue by xiaofu1994** [acgotaku/BaiduExporter#264]
archlinux
浏览器chromium 版本 52.0.2743.85 (64-bit)
百度网盘助手0.84
aria2 版本 1.25.0

**部分文件能正常下载，部分不行**，出错提示“Exception: [SocketCore.cc:874] errorCode=1 接收数据失败，原因：连接被对方重设”，但是用浏览器能下载。

配置文件：
#允许rpc
enable-rpc=true
#允许所以来源，web界面跨域权限需要
rpc-allow-origin-all=true
#允许非外部访问
rpc-listen-all=true
#rpc端口，仅当默认端口被占用时修改
#rpc-listen-port=6800
#最大同时下载任务
max-concurrent-downloads=3
#断点续传
continue=true
#同服务器连接数
max-connection-per-server=5
#最小文件片大小，下载线程数上限取决于能分出多少片，对于小文件重要
min-split-size=10M
#单文件最大线程数
split=5
#下载速度限制
max-overall-download-limit=0
#单文件速度限制
max-download-limit=0
#上传速度限制
max-overall-upload-limit=0
#单文件速度限制
max-upload-limit=0
#文件保存路径，默认为当前启动位置
dir=/home/hzl/Downloads/aria2
#禁用ipv6
disable-ipv6=true
file-allocation=prealloc
#不进行证书验证
check-certificate=false

**Comment by acgotaku** [comment]
百度最近好像动手脚了  == 等我写完论文就看看。。。

**Comment by acgotaku** [comment]
请给一个 连接无法下载的例子我来调试

**Comment by Melee7** [comment]
[#e6b01f 0B/0B CN:1 DL:0B]
10/16 13:43:52 [ERROR] CUID#17 - Download aborted. URI=http://d.pcs.baidu.com/file/9ebe5101d3db7d2717c6184c704c0d7e?fid=4161866163-250528-1103599362509398&time=1476596630&rt=pr&sign=FDTAERVCY-DCb740ccc5511e5e8fedcff06b081203-c4Vi0ND1LRq%2BWX4qdgIQDm%2BJp0s%3D&expires=8h&chkv=1&chkbd=1&chkpc=et&dp-logid=6715994972126315789&dp-callid=0&r=129655736
Exception: [SocketCore.cc:874] errorCode=1 Failed to receive data, cause: An existing connection was forcibly closed by the remote host.
