### ISSUE TITLE
safrai的插件不能导入到aria2

### ISSUE THREAD

**Issue by wuyuxin** [acgotaku/BaiduExporter#268]
safrai的插件（0.7.6）提示是不是没有打开aria2c，但是chrome的却能导入。

**Comment by StefanShen** [comment]
+1, The safari extension is invalid

**Comment by loveallofyou** [comment]
+1

**Comment by wuyuxin** [comment]
解决了，touch /Users/baiyijun/Downloads/session.txt && aria2c --enable-rpc --rpc-listen-all --save-session=/Users/baiyijun/Downloads/session.txt --input-file=/Users/baiyijun/Downloads/session.txt -x16 -s16 -k1M --dir=/Users/baiyijun/Downloads

**Comment by StefanShen** [comment]
However, my extension still doesn't  work, I can't even find the button in my BaiduYun.
