### ISSUE TITLE
为什么可以导出，却下载失败？

### ISSUE THREAD

**Issue by yh127** [acgotaku/BaiduExporter#270]
从半月前开始 chromium 插件 0.84 0.85 都是可以导出，但是 aria2 下载全部是失败。我的 aria2 是 1.18，升级到 1.24、1.25 也是下载失败。普通下载链接用 YAAW for Chrome 可以正常下载。

**Comment by yh127** [comment]
刚又试了一下，删除 chromium 全部数据后（仅删除插件不行）重下插件或登录同步后，第一次访问百度设置 ARIA2 RPC 后导出可以成功下载，但F5刷新页面后设置立即被重置，再次设置 ARIA2 RPC 就只能导出但下载失败。

**Comment by acgotaku** [comment]
因为我没有 NAS 所以远程没详细测试。。。 我回头看看

**Comment by huangchengcheng** [comment]
我碰到一样的问题。error log：
-> [SocketCore.cc:875] errorCode=1 SSL/TLS handshake failure: unable to get local issuer certificate
2016-08-28 10:40:04.856149 [ERROR] [AbstractCommand.cc:350] CUID#25 - Download aborted. URI=https://d.pcs.baidu.com/file/9d15a62b49a7e93af08d8a922996ac07?fid=2705285723-250528-151132906204639&time=1472352004&rt=pr&sign=FDTAERVC-DCb740ccc5511e5e8fedcff06b081203-xYTZ9cNmlUz1wnUErxHyRtPs1Pk%3D&expires=8h&chkv=1&chkbd=1&chkpc=&dp-logid=5576586646108779039&dp-callid=0&r=677929289
Exception: [AbstractCommand.cc:350] errorCode=1 URI=https://d.pcs.baidu.com/file/9d15a62b49a7e93af08d8a922996ac07?fid=2705285723-250528-151132906204639&time=1472352004&rt=pr&sign=FDTAERVC-DCb740ccc5511e5e8fedcff06b081203-xYTZ9cNmlUz1wnUErxHyRtPs1Pk%3D&expires=8h&chkv=1&chkbd=1&chkpc=&dp-logid=5576586646108779039&dp-callid=0&r=677929289

**Comment by yilang0001** [comment]
是不是装了ExtensionHTTPS Everywhere 这个插件？ 我当时把所有插件禁用，只剩下Exporter,然后一个一个试开启其他插件，最终找到这货与exporter冲突。 
测试的时候有两个注意事项
1.需要关闭所有页面并且完全退出chrome后台
2.需要log off百度云账号再登陆

**Comment by huangchengcheng** [comment]
@yilang0001 谢谢分享。但是并没有安装这个。而且之前用的好好的。难道百度云最近强制https了？另，我用的aria2是这个版本：http://www.right.com.cn/forum/thread-157967-1-1.html

**Comment by yilang0001** [comment]
应该不是百度云的问题，我的aria2是局域网NAS。当时自己电脑的baidu exporter始终无法成功下载，只能导入下载链接。但是在aria页面手动添加一般的下载或是磁力链都可以成功下载，然后我又用老婆电脑安装exporter,发现可以成功导入并下载，所以怀疑是插件问题

**Comment by xinnyu** [comment]
我现在用的最新版也出现了这个问题，aria2在路由器上，用aria2的GUI可以正常下载，但是用Exporter只能导出，下载失败，也没有安装ExtensionHTTPS Everywhere这个插件，删除所有数据重装还是不行。

**Comment by AtomChen** [comment]
@xinnyu 

增加 --check-certificate=false 到 aria2c 配置中

[Downloads incorrect URL on some site](https://sourceforge.net/p/aria2/bugs/314/)

**Comment by ScuBioInfo** [comment]
# 

感谢大神的制作！现在用的是这个版本的拓展和aria2GUI

![2018-01-16 9 43 29](https://user-images.githubusercontent.com/28745030/34992043-c81424c8-fb06-11e7-920a-f5641eabdfa3.png)
![2018-01-16 9 43 23](https://user-images.githubusercontent.com/28745030/34992051-cc32eef4-fb06-11e7-9a3f-94bf00eb9c9c.png)


今天突然发现使用的时候显示导出成功，但是在aria2GUI中直接下载失败，
![2018-01-16 9 41 47](https://user-images.githubusercontent.com/28745030/34992070-df00666a-fb06-11e7-9306-57336829680c.png)
![2018-01-16 9 41 15](https://user-images.githubusercontent.com/28745030/34992077-e0db4f4a-fb06-11e7-826d-bc11eb41eeae.png)






选择文本导出选项在命令行也显示错误，请问是什么原因？该如何修改？

```
aria2c -c -s10 -k1M -x16 --enable-rpc=false -o "64当如.rar" --header "User-Agent: netdisk;5.3.4.5;PC;PC-Windows;5.1.2600;WindowsBaiduYunGuanJia" --header "Referer: https://pan.baidu.com/disk/home" --header "Cookie: pcsett=1516194191-e376e94748c36de62d5cb85354ffbc3c" "https://d.pcs.baidu.com/file/97e002c85ee93dfe9e03a23be8b3f0ed?fid=1513326471-250528-984987019891664&time=1516107822&rt=sh&sign=FDTAERV-DCb740ccc5511e5e8fedcff06b081203-4t9qjcrQ6f9rrKYaeh2zvd0U118%3D&expires=8h&chkv=1&chkbd=0&chkpc=&dp-logid=368245870589541947&dp-callid=0&r=308034388"

01/16 21:09:46 [NOTICE] Downloading 1 item(s)

01/16 21:09:47 [ERROR] CUID#7 - Download aborted. URI=https://d.pcs.baidu.com/file/97e002c85ee93dfe9e03a23be8b3f0ed?fid=1513326471-250528-984987019891664&time=1516107822&rt=sh&sign=FDTAERV-DCb740ccc5511e5e8fedcff06b081203-4t9qjcrQ6f9rrKYaeh2zvd0U118%3D&expires=8h&chkv=1&chkbd=0&chkpc=&dp-logid=368245870589541947&dp-callid=0&r=308034388
Exception: [AbstractCommand.cc:351] errorCode=22 URI=https://d.pcs.baidu.com/file/97e002c85ee93dfe9e03a23be8b3f0ed?fid=1513326471-250528-984987019891664&time=1516107822&rt=sh&sign=FDTAERV-DCb740ccc5511e5e8fedcff06b081203-4t9qjcrQ6f9rrKYaeh2zvd0U118%3D&expires=8h&chkv=1&chkbd=0&chkpc=&dp-logid=368245870589541947&dp-callid=0&r=308034388
  -> [HttpSkipResponseCommand.cc:239] errorCode=22 The response status is not successful. status=403

01/16 21:09:47 [NOTICE] Download GID#6d903fe00cca83f2 not complete: /Users/XXX/64当如.rar

Download Results:
gid   |stat|avg speed  |path/URI
======+====+===========+=======================================================
6d903f|ERR |       0B/s|/Users/XXX/64当如.rar

Status Legend:
(ERR):error occurred.

aria2 will resume download if the transfer is restarted.
If there are any errors, then see the log file. See '-l' option in help/man page for details.
```

**Comment by acgotaku** [comment]
@ScuBioInfo 你是分享页面 还是百度网盘主页？

**Comment by ScuBioInfo** [comment]
您好！是分享页面

**Comment by Owenscu** [comment]
> 您好！是分享页面
请问您解决了吗
