### ISSUE TITLE
现在能用回IDM下载了，望作者更新

### ISSUE THREAD

**Issue by sino1641** [acgotaku/BaiduExporter#273]
RT，现在能重新使用IDM下载，但是插件没更新，直接拷贝的链接还是不能导入IDM。

**Comment by acgotaku** [comment]
可以贴下 你能用  IDM下载的文本么？

**Comment by sino1641** [comment]
`https://%36%67%77%68%6E%68%63%74%74%67%61%7A%64%72%63%6A%71%67%61%61%31%34%61%35%72%70%61%61%64%79%6D%75%6E%63%66%77%73%65%37%6D%6F%63%70%33%31%68%61%35%78%70%77%2E%6F%75%72%64%76%73%73%73%2E%63%6F%6D/cdn00.baidupcs.com/file/7daff0c06c005db0714f90186bb79302?bkt=p-398a97dbeb1f0f4239df97427c1c3793&xcode=2bbcd09b9180cb92120983b4b4708cc4b198335ccbc98d5a9717ec4418c70769&fid=742138700-250528-186679983291400&time=1471747182&sign=FDTAXGERLBH-DCb740ccc5511e5e8fedcff06b081203-Cb491%2BHuv%2F90BS7KqmISo1MJhD0%3D&to=sd&fm=Yan,B,M,mn&sta_dx=3458422439&sta_cs=15590&sta_ft=exe&sta_ct=7&sta_mt=5&fm2=Yangquan,B,M,mn&newver=1&newfm=1&secfm=1&flow_ver=3&pkey=0000dd7cc7501d5e87bc94ffa1c5e498dfe7&sl=70975564&expires=8h&rt=pr&r=658124768&mlogid=5414230965419055046&vuk=742138700&vbdid=2764342616&fin=%5B110624%5D%5BKey%5DRewrite%20%5B%E6%B1%89%E5%8C%96%E7%A1%AC%E7%9B%98%E7%89%88%5D.exe&slt=pm&uta=0&rtype=1&iv=0&isw=0&dp-logid=5414230965419055046&dp-callid=0.1.1&hps=1&wshc_tag=0&wsts_tag=57b9146e&wsid_tag=df499c7d&wsiphost=ipdbm`

**Comment by acgotaku** [comment]
你这不带 Cookies  根本没法下载啊。。。

**Comment by sino1641** [comment]
![IDM](http://ww3.sinaimg.cn/large/4e077b55gw1f71fz7iu0pj20gt0d0ac4.jpg)
不知道原理，反正能下载……

**Comment by acgotaku** [comment]
你这是因为服务器缓存的原因吧。。。

**Comment by sino1641** [comment]
@acgotaku 有可能吧。个人对这些一无所知^-)

**Comment by acgotaku** [comment]
修复了

**Comment by sino1641** [comment]
@acgotaku 更新插件后使用idm依旧403
