### ISSUE TITLE
好像safari插件不再更新了？

### ISSUE THREAD

**Issue by 52mzd** [acgotaku/BaiduExporter#274]
现在safari下已经失效了😭。。。。。

**Comment by Cee** [comment]
Works when using http.

**Comment by giveup** [comment]
Chrome类似,但是Chrome的话无法关闭https,似乎无论如何设置都会跳转到https.

**Comment by HarukaMa** [comment]
Just a FYI, https is indeed forced on safari ( at least at last time I wanted to dl smth).

iPhoneから送信

2016/08/27 0:00、giveup <notifications@github.com> のメッセージ:

**Comment by giveup** [comment]
https无法下载的问题可能是因为aria2的问题.
分析aria2的日志就可以发现.
 -> [HttpSkipResponseCommand.cc:239] errorCode=22 The response status is not successful. status=403
2016-08-28 09:14:44.545655 [ERROR] [AbstractCommand.cc:350] CUID#43 - Download aborted. URI=https://pan.baidu.com/box-static/disk-system/widget/pageModule/aside/img/navigator_3e99a34.png
Exception: [AbstractCommand.cc:350] errorCode=1 URI=https://pan.baidu.com/box-static/disk-system/widget/pageModule/aside/img/navigator_3e99a34.png
  -> [SocketCore.cc:1015] errorCode=1 SSL/TLS handshake failure: unable to get local issuer certificate
因为主流浏览器强制使用https的原因,所以拓展导出的也是https连接.
