### ISSUE TITLE
V0.7.3在Safari下无法加载出导出下载

### ISSUE THREAD

**Issue by SmarmyWu** [acgotaku/BaiduExporter#275]
V0.7.3在Safari下无法加载出导出下载，在http下能加载出来。
BaiduExporter 0.7.3
Safari 9.12
OSX EI Capitan 10.11.6
————————————
我看了下相关提问都没有给出解决方案。
然后Google“防止http跳转https"，得到是如何让http跳转https的信息。
————————————
本人小白，能否解决在https下加载出导出下载，或是能否给出不跳转https的解决方案？
谢谢！
————————————

**Comment by IgniteWhite** [comment]
同样的问题

**Comment by giveup** [comment]
Same Issue https://github.com/acgotaku/BaiduExporter/issues/274
Add Option In Aria2.conf
check-certificate=false
