### ISSUE TITLE
安装了0.7.1谷歌插件，但是打开百度网盘没有出现导出按钮

### ISSUE THREAD

**Issue by lg1-09** [acgotaku/BaiduExporter#279]
![image](https://cloud.githubusercontent.com/assets/13133239/18242341/653284a0-7388-11e6-8d3f-f8b8b3a163f0.png)

![image](https://cloud.githubusercontent.com/assets/13133239/18242430/de210788-7388-11e6-96d9-a6eac46c2318.png)
我按照这个教程安装的，http://bbs.feng.com/read-htm-tid-9585996.html。不知道是不是步骤不对呢？

**Comment by acgotaku** [comment]
@lg1-09 请使用源代码载入 Release没有更新

**Comment by lg1-09** [comment]
好的谢谢！已经可以了！
