### ISSUE TITLE
chromium和firefox视频分类下无法导出,

### ISSUE THREAD

**Issue by giveup** [acgotaku/BaiduExporter#28]
测试了两个视频文件,类似于ABC/123.AVI这样的目录按导出没有任何反应...(在视频分类下)
回到全部文件,然后进入文件夹按导出才能下载,chromium和firefox都是0.29版本
然后..把两个视频文件移到根目录,无法导出....再然后,继续测试,发现全部文件分类下没一个能导出.
感觉添加了目录导出功能增加了好多BUG...

**Comment by acgotaku** [comment]
@giveup 毕竟换了 API

**Comment by acgotaku** [comment]
@giveup 全部文件分类下 啥 不能导出??

**Comment by acgotaku** [comment]
@giveup  0.3.0版本已经修复了这个问题

**Comment by giveup** [comment]
@acgotaku 测试成功。
