### ISSUE TITLE
为啥百度现在下载一堆checksum error？

### ISSUE THREAD

**Issue by gxizhe** [acgotaku/BaiduExporter#281]
用了破解版百度云和Aria2都是这样，不知道是不是度受修改了程序

**Comment by acgotaku** [comment]
为啥你们都出错 我用着好好的啊

**Comment by gxizhe** [comment]
我测试了一下，只要你用破解版百度云和Aria2肯定会有错误。用正式版反而没有任何错误

**Comment by acgotaku** [comment]
我测试了一下 IDM和 aria2都能下载啊 你出错的具体原因说说

**Comment by gxizhe** [comment]
具体原因我也不知道，但是下载压缩文件里面会有一些文件显示checksum error无法解压，用的是最新版。网络我5G 2G都试过了。仅仅是百度云会有这个问题，其他的下载源无问题

**Comment by acgotaku** [comment]
@gxizhe 下载可以 但是无法解压缩？

**Comment by gxizhe** [comment]
嗯，有一些文件在解压缩时报错，目前还没有发现规律。

**Comment by acgotaku** [comment]
@gxizhe 只是有一些文件出错的话 你找我报错也没用啊

**Comment by Sasasu** [comment]
铁通or长城网络?

**Comment by gxizhe** [comment]
@Sasasu 美国Comcast，刚刚可能没讲清楚不过只要是压缩文件，里面肯定会有文件在解压缩过程中报错

**Comment by acgotaku** [comment]
刚aria2c下载了一个文件 测试 没有任何问题

**Comment by gxizhe** [comment]
@acgotaku 麻烦能不能测试一下分卷文件

**Comment by acgotaku** [comment]
@gxizhe 是拆分成几个part的那种？

**Comment by gxizhe** [comment]
@acogtaku 嗯

**Comment by acgotaku** [comment]
@gxizhe 分享一个我试试？

**Comment by gxizhe** [comment]
@acgotaku https://pan.baidu.com/wap/link?surl=1c2LYJr6&errno=0&errmsg=Auth%20Login%20Sucess&stoken=211f34e26f0544f4c994d8bd84a80b2da7bf230215fb2fccd128040574fb4d3201184c25f0d3abc3f413e63d3fc93d057c203a255fae66222ad3f7196aa56731702e8c9f322a&bduss=4bafee989a87126f7cd0b9bdb2cf756855d5b59517a2a97dbd27fa54c70ac56beda1ff743709ee2b699bb58ec14f92017243d586e50f194005ee1be758d54452c9a2fdb6120dd19ffa1c5500e9441762907853bab7c7bcfd74356027f7fc7c5bcfa17e29de4f9684fd236b5ee664aea8641e2086fc4f725c90ccdc7aff04707bf700757ca570d7a29a5526a6d1743946cf854707b47468b10bd79937604d2caacff9fb483070733fed8246900a041056032551553769389b18f0d3142e91d479d47e0c43ef1e&ssnerror=0#list/path=%2F3DM游戏%2F2016年.9%2F9.5%2F3DMGAME-No_Mans_Sky.(up3).CHS.Green&page=1

**Comment by acgotaku** [comment]
@gxizhe 还是完美下载和解压了。。。

**Comment by lautis0503** [comment]
这个问题我也遇到过，下载几十上百G的分卷压缩包的时候，偶尔会出现几个有问题，破解百度云同样。一般情况只要重新下载就好了。也有遇到过aria2下载某几个文件无论多少次都有问题的情况，所以应该不是本项目的问题，可能是资源或者网络或者aria2本身的问题。

**Comment by gxizhe** [comment]
看来是我自己倒霉了

**Comment by gxizhe** [comment]
试了下Winrar的修复功能可以修复文件。

只不过二十多分卷的3D定制**要修复到何时啊
