### ISSUE TITLE
v0.8.5 出现   现在失败，是不是没有开启ariac2

### ISSUE THREAD

**Issue by KwToPA** [acgotaku/BaiduExporter#283]
作者您好，

chrome  53.0.2785.89 (64-bit)

os: os x 10.10

aria2c正常开启，清空过cookies

```
https://pan.baidu.com/api/analytics?_lsid=1473169497758&_lsix=1&clienttype=0&type=chrome-used&value=chrome53 net::ERR_BLOCKED_BY_CLIENT
jquery-2.2.3.min.js:4 XHR finished loading: GET "https://pan.baidu.com/api/download?type=dlink&fidlist=%5B%2243801640883332%…8xk5BFPCSML%2Bg3lZA%3D%3D&channel=chunlei&clienttype=0&web=1&app_id=250528".send @ jquery-2.2.3.min.js:4ajax @ jquery-2.2.3.min.js:4n.(anonymous function) @ jquery-2.2.3.min.js:4a @ home.js:1t @ home.js:1d.start @ home.js:1(anonymous function) @ home.js:1
```

```
POST http://localhost:6800/jsonrpc 400 (Bad Request)(anonymous function) @ background.js:48HttpSendRead @ background.js:7(anonymous function) @ background.js:64target.(anonymous function) @ extensions::SafeBuiltins:19EventImpl.dispatchToListener @ extensions::event_bindings:388target.(anonymous function) @ extensions::SafeBuiltins:19publicClassPrototype.(anonymous function) @ extensions::utils:151EventImpl.dispatch_ @ extensions::event_bindings:372EventImpl.dispatch @ extensions::event_bindings:394target.(anonymous function) @ extensions::SafeBuiltins:19publicClassPrototype.(anonymous function) @ extensions::utils:151messageListener @ extensions::messaging:207target.(anonymous function) @ extensions::SafeBuiltins:19EventImpl.dispatchToListener @ extensions::event_bindings:388target.(anonymous function) @ extensions::SafeBuiltins:19publicClassPrototype.(anonymous function) @ extensions::utils:151EventImpl.dispatch_ @ extensions::event_bindings:372EventImpl.dispatch @ extensions::event_bindings:394target.(anonymous function) @ extensions::SafeBuiltins:19publicClassPrototype.(anonymous function) @ extensions::utils:151dispatchOnMessage @ extensions::messaging:334
background.js:48 XHR finished loading: POST "http://localhost:6800/jsonrpc".(anonymous function) @ background.js:48HttpSendRead @ background.js:7(anonymous function) @ background.js:64target.(anonymous function) @ extensions::SafeBuiltins:19EventImpl.dispatchToListener @ extensions::event_bindings:388target.(anonymous function) @ extensions::SafeBuiltins:19publicClassPrototype.(anonymous function) @ extensions::utils:151EventImpl.dispatch_ @ extensions::event_bindings:372EventImpl.dispatch @ extensions::event_bindings:394target.(anonymous function) @ extensions::SafeBuiltins:19publicClassPrototype.(anonymous function) @ extensions::utils:151messageListener @ extensions::messaging:207target.(anonymous function) @ extensions::SafeBuiltins:19EventImpl.dispatchToListener @ extensions::event_bindings:388target.(anonymous function) @ extensions::SafeBuiltins:19publicClassPrototype.(anonymous function) @ extensions::utils:151EventImpl.dispatch_ @ extensions::event_bindings:372EventImpl.dispatch @ extensions::event_bindings:394target.(anonymous function) @ extensions::SafeBuiltins:19publicClassPrototype.(anonymous function) @ extensions::utils:151dispatchOnMessage @ extensions::messaging:334
```

谢谢

**Comment by KwToPA** [comment]
clone一份0.8.5到本地，再通过源代码加载到chrome://extensions中

还是不行

**Comment by KwToPA** [comment]
本地100M， 手动把下载链接添加到aria2中，速度只有100K

**Comment by acgotaku** [comment]
你这个 LOG我看不懂啊。。。

**Comment by Cee** [comment]
aria2c 沒有開啓 rpc？

**Comment by KwToPA** [comment]
@Cee  开了

conf设置为
```
# 启用RPC, 默认:false
enable-rpc=true
# 允许所有来源, web界面跨域权限需要 默认:false
rpc-allow-origin-all=true
# 允许非外部访问, 默认:false
rpc-listen-all=true
# 事件轮询方式, 取值:[epoll, kqueue, port, poll, select], 不同系统默认值不同
#event-poll=select
```

@acgotaku   第一个代码来自开发者工具里的console，，第二个代码来自chrome://extensions  的Inspect views: 里的console

**Comment by Cee** [comment]
@KwToPA 

`POST http://localhost:6800/jsonrpc 400 (Bad Request)`

這個看上去是沒開的樣子，命令行重新開一下試試？

**Comment by DimRacker** [comment]
抱歉插楼问一声，能不能不通过开发者模式加载，直接下载0.8.5的crx啊，昨天重做了系统，chrome没把这个扩展给我同步过来，装了0.7.1也不自动升级，到现在一直用不了，老郁闷了

**Comment by guliujian** [comment]
2016年9月7日 09:24，"DimRacker" <notifications@github.com>写道：
>
>
抱歉插楼问一声，能不能不通过开发者模式加载，直接下载0.8.5的crx啊，昨天重做了系统，chrome没把这个扩展给我同步过来，装了0.7.1也不自动升级，到现在一直用不了，老郁闷了
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.

建议把源码下载到本地通过chrome开发者模式本地加载

**Comment by DimRacker** [comment]
@guliujian 感谢回复！开发者模式本地加载，是不是就不能自动更新了？

**Comment by acgotaku** [comment]
@guliujian  https://github.com/acgotaku/BaiduExporter/releases/tag/v0.8.5  最后一个CRX 以后再也不会发布了

**Comment by acgotaku** [comment]
@DimRacker 不会自动更新

**Comment by DimRacker** [comment]
@acgotaku 哇！谢谢大神！无论怎样，我们都会一如既往支持你！

**Comment by wjiyang** [comment]
@acgotaku 这将会是最后一个版本吗？

**Comment by acgotaku** [comment]
@wjiyang CRX是最后一个版本 Github还会更新

**Comment by KwToPA** [comment]
@Cee  
我先打开百度盘，在开aria2c --conf-path=~/aria2.conf

度盘里这种   http://localhost:6800/jsonrpc  反馈的是是否没有打开aria2

我改为另一种  http://token:隐去@host:port/jsonrpc   正在在获取下载地址...   然后就没下文了

console里显示 home.js:1 Uncaught TypeError: Failed to construct 'URL': Invalid URL

**Comment by KwToPA** [comment]
@Cee  貌似我这边(南电信)限速了？ 2天前能到50M，都是手动http添加，昨天开始就100K。还有百度的链接变成了https://不知道有没有关系

**Comment by acgotaku** [comment]
@KwToPA 上面的错误显示你输入的URL是非法的 百度变成 https我也正常下载的

**Comment by KwToPA** [comment]
@acgotaku   方便说说您用的user-agent吗

**Comment by acgotaku** [comment]
@KwToPA 我的一直都是默认的啊

**Comment by acgotaku** [comment]
@KwToPA 插件里面有 测试连接的功能啊 你测试下就知道了啊 也可以用其他的aria2c工具查看是否成功启动啊  例如 YAAW

**Comment by KwToPA** [comment]
@acgotaku 检测结果  错误,请查看是否开启Aria2

我就是手动添加链接到YAAW下载的

**Comment by KwToPA** [comment]
@acgotaku  挂proxychains4  只有200K，不挂代理只有100K  

换UA

netdisk;2.4.3;MacBookPro9,2;MAC-OS X 10.10.3 (14D136);10.10.3;zh-Hans_HK@currency=CNY

也不行

**Comment by KwToPA** [comment]
https://nbct01.baidupcs.com/file/3fda1e1d170386631aeb045c89cdadc9?bkt=p3-000024d920495db4592ac1f079b201e6cf5a&fid=3191785514-250528-43801640883332&time=1473213991&sign=FDTAXGERLBH-DCb740ccc5511e5e8fedcff06b081203-o9CzmnZIc0GtnkrkDCMWEBTwMuM%3D&to=nbhb&fm=Nin,B,U,ny&sta_dx=13999947679&sta_cs=3&sta_ft=mkv&sta_ct=0&sta_mt=0&fm2=Ningbo,B,U,ny&newver=1&newfm=1&secfm=1&flow_ver=3&pkey=000024d920495db4592ac1f079b201e6cf5a&sl=79888463&expires=8h&rt=pr&r=880141361&mlogid=5807974713007799733&vuk=3191785514&vbdid=2770438919&fin=The.Graduate.1967.1080p.BluRay.x264.DTS-WiKi.mkv&fn=The.Graduate.1967.1080p.BluRay.x264.DTS-WiKi.mkv&slt=pm&uta=0&rtype=1&iv=0&isw=0&dp-logid=5807974713007799733&dp-callid=0.1.1&hps=1&csl=284&csign=e7OdptckdDb82JW55wq7u%2FhetXg%3D

下载链接

**Comment by acgotaku** [comment]
@KwToPA 爱莫能助。。。  顶多看看这个吧https://github.com/acgotaku/BaiduExporter/issues/251#issuecomment-244905796

**Comment by KwToPA** [comment]
@acgotaku  谢谢。

还是没成功，先200K凑活着吧

很抱歉 耽误您时间

**Comment by acgotaku** [comment]
@KwToPA 我只能保证是否正常下载 下载速度根据地区而异 我无法保证啊 。。。

**Comment by wjiyang** [comment]
@KwToPA  刚刚试了下CRX  还有打包安装 ..额 我是都可以的
 active    2.99 MB/s    12:05    2.199 GB    85.50 MB

**Comment by KwToPA** [comment]
@wjiyang    http://ziahamza.github.io/webui-aria2/  请问这边应该怎么设置才能显示？
[http://i.imgur.com/htZGgsc.png](http://i.imgur.com/htZGgsc.png)

我在YAAW上可以用 另一个上不行

**Comment by wjiyang** [comment]
@KwToPA 你是在自己电脑本地吗？本地不用改 外网 主机那里添加你的ar2运行的IP或域名啊.

**Comment by wjiyang** [comment]
@KwToPA 我测试是正常的...
![1](https://cloud.githubusercontent.com/assets/22034832/18301525/b8f35d1c-7504-11e6-9d97-e60d1d5a5b5c.png)

**Comment by wjiyang** [comment]
@KwToPA 不对  我没设置主机也是可以下载的.

**Comment by KwToPA** [comment]
最后找了一个缓存服务器，手动添加到aria，可以达到40M的速度
