### ISSUE TITLE
使用黑裙DDNS，外网webgui可连接，但无法在百度云导出下载到nas

### ISSUE THREAD

**Issue by chenxiccc** [acgotaku/BaiduExporter#286]
环境：
黑裙 DSM5.2，ipkg安装了aria2 1.14.1；
使用--rpc-usr=xxx --rpc-passwd=yyyyyy 设置了用户名和密码；
ddns 假设为aa.bb.cc，路由器已设置6800端口转发；
Chrome，BaiduExporter 0.8.4。

现象：
外网除BaiduExporter之外，都可正常使用，如下：
外网使用MAC本地（不是在NAS上）的webgui(ziahamza)，在configuration.js中设置host:'aa.bb.cc'，user:'xxx' pass:'yyyyyy' 后可正常连接NAS的aria2，可正常创建下载。

iPhone上在外网使用AVee，使用http://xxx:yyyyyy@aa.bb.cc:6800也可正常连接和创建下载

故障描述：
BaiduExporter中rpc1为localhost：http://localhost:6800/jsonrpc 。启动MAC的aria2c后可正常使用。--验证浏览器和扩展本身没问题。
新增一个rpc2，设置为http://xxx:yyyyyy@aa.bb.cc:6800/jsonrpc，百度云导出下载选择rpc2时，提示“下载失败，是不是没有开启aria2?”---如上所述，实际上MAC的本地webgui和iPhone是可以连接nas 的 aria2的。

请教，问题出在哪里？

**Comment by acgotaku** [comment]
在扩展安装页面 有个背景页 打开之后 在进行下载操作 失败的话 Console应该会有错误输出 Network面板也有失败的请求 截图之类的发来就行

**Comment by chenxiccc** [comment]
Console和Network以及BaiduExporter配置 如图：
![snip20160910_61](https://cloud.githubusercontent.com/assets/1096853/18408592/c2933888-7766-11e6-8b0a-a9d5deac9da4.png)
![snip20160910_71](https://cloud.githubusercontent.com/assets/1096853/18408593/c2957404-7766-11e6-9c53-29e552c81e98.png)
![snip20160910_81](https://cloud.githubusercontent.com/assets/1096853/18408594/c2a17d94-7766-11e6-9583-77611f39a6d7.png)

**Comment by chenxiccc** [comment]
信息量是否足够？是否需要展开Console里 object再次截图发上来？

**Comment by acgotaku** [comment]
重要的信息你都打码了我看个毛线 根本不知道你那个 RPC地址是默认的还是修改的
端口都一样。。。。 这个报错是没通过认证

**Comment by chenxiccc** [comment]
啊呜~~RPC地址写的是 http://user:password@mynas.synology.cn:6800/jsonrpc

**Comment by acgotaku** [comment]
@chenxiccc 这个格式是老的 推荐用 token格式
