### ISSUE TITLE
谷歌插件问题:

### ISSUE THREAD

**Issue by chaocool** [acgotaku/BaiduExporter#287]
@acgotaku 你好

https://chrome.google.com/webstore/detail/baiduexporter/mjaenbjdjmgolhoafkohbhhbaiedbkno

404。 这是一个错误。

所请求的URL不在此服务器上找到。 我们知道的就这些

**`你好,谷歌浏览器的插件哪里下载? 并没看到安装包啊  商店里找不到呢`**

**Comment by guliujian** [comment]
之前有一个最后的release，建议打开下载项目到本地然后用chrome的开发者模式加载本地的文件夹

2016年9月11日 23:52，"chaocool" <notifications@github.com>写道：

**Comment by tryeverything** [comment]
> 之前有一个最后的release，建议打开下载项目到本地然后用chrome的开发者模式加载本地的文件夹
加载本地文件夹，生成crx文件，安装插件。没多久，chrome就提示

> This extension is not listed in the Chrome Web Store and may have been added without your knowledge
小降落伞就变灰了。而且不能重新“enable”。

**Comment by acgotaku** [comment]
现在只能开发者模式导入使用了 具体请看 readme 不会再上架谷歌商店
