### ISSUE TITLE
token 问题还是没有解决嘛。。。。

### ISSUE THREAD

**Issue by mapleshadow** [acgotaku/BaiduExporter#288]
RT，0.8.5说解决了，结果没。。。0.8.6说解决了，结果还是没。。。。
作者不好意思我就想说明下，该BUG一直存在着。。。这个问题。。
另外，为什么删除google市场的crx呢？

**Comment by pingshunhuangalex** [comment]
请问你这边TOKEN方面有什么问题呢？我这边0.8.5-0.8.6TOKEN都可以正常使用 没有任何问题哦

Google Store怎么说呢 树大招风吧 放在Github这边直接更新维护起来也更加方便 大家直接pull就好了

**Comment by mapleshadow** [comment]
@pingshunhuangalex 建议还是google store，毕竟这里的正规更新也方便。PS：使用token验证，填写地址完毕，点击应用，点击测试，没反应。然后去测试几个加入aria2下载，也没反应。

**Comment by acgotaku** [comment]
谷歌市场是不会再上架了 Token问题之后我再测试测试

**Comment by acgotaku** [comment]
@mapleshadow 我这边测试了一下还是没有问题 没法复现这个BUG 麻烦你详细说明如何出现的问题 或者录制了小视频也行

**Comment by bf30075** [comment]
为什么不上架了呢  今天突然失效 特意来问问

**Comment by acgotaku** [comment]
@bf30075 被谷歌下架了 所以就再也不上架了

**Comment by UnluckyNinja** [comment]
谷歌没有说是因为什么原因下架的吗？

**Comment by acgotaku** [comment]
@UnluckyNinja 就说侵犯百度权利

**Comment by UnluckyNinja** [comment]
哦这样的话那就没办法了:joy:

**Comment by pingshunhuangalex** [comment]
不要贪恋Chrome Store，放在Github上多自由。都用Aria2了，干脆就在Geeky的道路上一路走下去吧~
