### ISSUE TITLE
下载一个目录下的所有文件时，有一个文件提示用户名密码错误，其他文件都ok

### ISSUE THREAD

**Issue by joutain** [acgotaku/BaiduExporter#29]
下载一个目录下的所有文件时，有一个文件提示用户名密码错误，其他文件都ok，是百度的问题？还是插件有些问题啊？之前从来没遇到过。

**Comment by acgotaku** [comment]
@joutain  用户名密码错误是谁提示的 能截图么? 实在不行 把那个文件分享给我 我来试试

**Comment by joutain** [comment]
OK，我晚些时候截图+分享给你

**Comment by joutain** [comment]
链接: http://pan.baidu.com/s/1sj3BvwL 密码: e07s

![image](https://cloud.githubusercontent.com/assets/9023645/5850642/67f7051a-a1c7-11e4-8c03-af9c9aaa871b.png)

**Comment by acgotaku** [comment]
@joutain 为啥我这边显示 分享不存在 ==

**Comment by joutain** [comment]
直接用web下载也提示失败，说下载的内容中有违规信息。故事是百度网盘把这个文件给封了。。。

On Thu, Jan 22, 2015 at 12:39 AM, 雪月秋水 <notifications@github.com> wrote:

> @joutain <https://github.com/joutain> 为啥我这边显示 分享不存在 ==
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/acgotaku/BaiduExporter/issues/29#issuecomment-70974057>
> .
>



-- 
Best Regards
Howard Jiang

**Comment by acgotaku** [comment]
@joutain 囧..原来是这样 那就关掉这个issue吧~
