### ISSUE TITLE
chrome0.8.6无法下载出现报错hostname not match

### ISSUE THREAD

**Issue by moonrailgun** [acgotaku/BaiduExporter#293]
插件版本0.8.6
浏览器Chrome 53.0.2785.116 m (64-bit)
Aria2版本 1.15.1
报错内容如下：
![image](https://cloud.githubusercontent.com/assets/6964737/18833458/4cb7ab8e-8423-11e6-85e5-16a9f531680a.png)

**Comment by acgotaku** [comment]
这种问题基本都是aria2c的锅。。。。 重新下载就好
