### ISSUE TITLE
百度云还有个企业版

### ISSUE THREAD

**Issue by Mapaler** [acgotaku/BaiduExporter#294]
今天在软件站看到的 https://eyun.baidu.com/s/3o8yE6i2

**Comment by acgotaku** [comment]
这和我也没啥关系啊 ==

**Comment by Mapaler** [comment]
就是感觉大结构是一样的，如果相对容易的话的话可以一并添加支持。

**Comment by sino1641** [comment]
企业版直接用idm下载就很快，不需要插件吧
