### ISSUE TITLE
chrome 屏蔽该扩展！

### ISSUE THREAD

**Issue by jijiucheng** [acgotaku/BaiduExporter#296]
因为该插件没有上架到 chrome 商店，造成了即使打开开发者模式添加，也会造成无法启动，尽管可以添加该扩展，但是不能够使用，而且每次启动浏览器也会提示无法使用，求解决办法；

**Comment by louy2** [comment]
每次启动的提示只是警告，可以正常启动插件。但是今天试了一下好像是失效了？

**Comment by zeroxia** [comment]
为啥官方商店找不到这个扩展了？

**Comment by louy2** [comment]
被百毒发了个DMCA

**Comment by jijiucheng** [comment]
我这边启动了之后提示已经无法使用了，只要一提示或者是只要重启电脑都会出现提示，但是只要有提示插件就不能用了！！！请问你是怎么解决的呀？我这边是 mac 系统

**Comment by acgotaku** [comment]
@jijiucheng 导入插件源码 而不是crx

**Comment by Rememberli** [comment]
@acgotaku 

chrome+最新版crx插件，今天刚刚安装的时候可以满速下载百度盘，过了半个小时下载别的时候就限速100KB了，好像别的网友还是可以下，难道baidu现在是按账号封杀了么？

**Comment by louy2** [comment]
@Rememberli 我不登录也能获取链接但是也差不多限速在100。

**Comment by acgotaku** [comment]
@Rememberli 这个就不清楚了。。。
