### ISSUE TITLE
How to resume download after error?

### ISSUE THREAD

**Issue by louy2** [acgotaku/BaiduExporter#297]
When downloading big files occasionally downloads would stop due to error and cannot be resumed from rpc. Is there a method to resume after such error? Does it involve refreshing the header?

**Comment by Cee** [comment]
This is a problem related to Aria2c.

**Comment by louy2** [comment]
Of course it's related to Aria2c. But whatever trick Baidu is using to prevent Aria2c from resuming the downloads can be solved here. I can implement, but I'd like some guidance.

**Comment by acgotaku** [comment]
@louy2 Maybe you said this https://github.com/acgotaku/BaiduExporter/issues/80
