### ISSUE TITLE
Edge浏览器没有出现按钮

### ISSUE THREAD

**Issue by ShekBoy** [acgotaku/BaiduExporter#298]
跟着这里做以后没有出现按钮
Edge: You need at least Windows 10 build 14342
Open about:flags, Check Enable extension developer features, Restart.
Clone repo to a local read-write folder.
Click More(...) -> Extensions -> Load extension, navigate to the chrome folder, click OK.
同样的资料夹Chrome载入后有出现按钮
已全清所有Edge缓存
插件版本号：0.8.6
浏览器版本号：38.14393.0.0
系统版本号：Windows 10 version 1607 build 14393.222
![image](https://cloud.githubusercontent.com/assets/22590886/19110078/d90c1788-8b2a-11e6-87ce-11f2e358d7a1.png)

**Comment by acgotaku** [comment]
@CnSimonChan 思萌来看看？

**Comment by CnSimonChan** [comment]
[inject.js#L28](https://github.com/acgotaku/BaiduExporter/blob/master/chrome/src/inject.js#L28) `window.addEventListener("load"...` 不要。已经在 $(function) 里面了所以没执行？

**Comment by CnSimonChan** [comment]
@acgotaku Any updates?

**Comment by acgotaku** [comment]
@CnSimonChan 我记得之前说过 这个要是不加 chrome就不执行 加了edge正常 不过我没有 edge的测试环境。。。  要不再开一个 edge的文件夹？

**Comment by CnSimonChan** [comment]
@acgotaku 改回原来的 `onload` function 吧，就是那个检测 `document.readyState` 的

明明之前在 fuck-baidu 的适合这个代码在 Edge 下好像没问题的

**Comment by acgotaku** [comment]
@CnSimonChan 可以换成那个 不过我没 Edge环境 能不能跑就不好保证了。。。

**Comment by CnSimonChan** [comment]
Edge 现在和 Chrome 一样每次启动就禁用非 Store 扩展，而且提交 Store 的方法还是没消息，只能说不推荐使用
