### ISSUE TITLE
Aria2c那边设置rpc-secret后，chrome里的aria按钮点击后就不能无法下载了，报：是不是没有启动aria2

### ISSUE THREAD

**Issue by Calabor-Hoc** [acgotaku/BaiduExporter#299]
您的插件我用的一直非常好！但是有一天之后就无法使用了。报的错是**导出失败，是不是没有开启aria2**，但我的aria2运行非常好，aria2的web-gui也能连上aria2啊！  
后来想想最近动过的只有把aria2的conf文件里加了rpc-secret=**** 把密码去掉后，再试，成了！

插件用的是[这个版本][1], chorme浏览器是mac版的53.0.2785.116

**借个机会非常表达对此插件作者的感谢！很多资料都放在百度云上，百度云也是我下载很多资源的渠道，后来mac版的百度同步盘停止更新一年后，现在在我机器上运行几分钟就会自动退出，导致我现在只能用浏览器自带的下载功能来下载存在百度云的资料，十分痛苦。幸亏有您的插件相助！当然还有aria2，哈哈。  
贴个让大家打赏的二维码吧，光是口头支持不行，生怕这个插件以后也停更了。**

[1]: https://github.com/acgotaku/BaiduExporter/commit/2727538c4a412e82e340fb33bff1429cdcfaac7c

**Comment by louy2** [comment]
设置密码以后需要在导出下面的设置里在 JSONRPC 的地址的 `http://` 后面 `localhost` 前面加上 `token:你的密码`。

**Comment by acgotaku** [comment]
@Calabor-Hoc 本项目不需要捐助。。。 捐助就变成商业利益了 会被百度起诉的

**Comment by yxs1112003** [comment]
Geeker

**Comment by louy2** [comment]
国内新《慈善法》之下都不止是被百度起诉的问题了。Sigh

**Comment by Calabor-Hoc** [comment]
@louy2 多谢指明，貌似这个在程序员中是很显然的吧，但是百度云的还是一般用户多啊，都不知道啊
@acgotaku 作者可以写在readme或者那个推荐的配置文件的注释里，那样挺好

**Comment by acgotaku** [comment]
@Calabor-Hoc  readme的usage里面有写啊  == 你倒是看看啊

**Comment by Calabor-Hoc** [comment]
@acgotaku 怪了，我真就没看到😓

**Comment by scutxd** [comment]
我也遇上了同样的问题，同样也是开始以为aria2c没有正确运行。后来看了.conf文件才发现这里有个token限制。
是否能够完善一下提示？
另外，谢谢作者！

**Comment by acgotaku** [comment]
@scutxd readme的提示还不够？
