### ISSUE TITLE
不知道如何获取你的联系方式，只能通过这里跟你沟通了

### ISSUE THREAD

**Issue by joutain** [acgotaku/BaiduExporter#30]
用了你的baiduexporter，感觉非常好，有没有可能也做一个115网盘的导出？目前有油猴脚本的方法获取115网盘的地址，如下。不知工作量大不大，能不能做，谢谢！

http://www.97world.com/archives/2994

**Comment by acgotaku** [comment]
@joutain 谢谢提供资料~  寒假我会抽时间研究下 尽力进行开发的~

**Comment by joutain** [comment]
非常感谢！

Best regards
Zhihao Jiang

**Comment by acgotaku** [comment]
@joutain 

https://github.com/acgotaku/115

项目目前已经完成初步导出功能了, 默认导出地址:http://localhost:6800/jsonrpc

鼠标悬浮到文件上会有导出按钮 目前还不完善 有时候加载不上去 需要多刷新 ==

**Comment by acgotaku** [comment]
@joutain 不过现在115貌似限制单文件速度200K了.... 我不是会员 没法测试高通道...

**Comment by joutain** [comment]
非常感谢！！

**Comment by acgotaku** [comment]
@joutain 
https://chrome.google.com/webstore/detail/115exporter/ojafklbojgenkohhdgdjeaepnbjffdjf

都发布产品了 这个issue关了吧 

使用方法看 readme :  https://github.com/acgotaku/115

**Comment by joutain** [comment]
谢谢！

**Comment by yellowvii** [comment]
@acgotaku 话说我可以赞助您一年 115 vip ~帐号发这里或我邮箱 ( github Id + gmail ) 都可以~
虽然不知道115作死模式还能撑多久，但是能用一天是一天~
如果有时间和精力，希望可以像百度盘工具一样支持火狐，非常感谢！

**Comment by k1n** [comment]
http://chunchu.org/web/2012/07/23/2118.html
希望这个有帮助。

**Comment by acgotaku** [comment]
@k1n  @yellowvii 谢谢你们的支持 你们的使用和点赞 是我开发最大的动力~ 喜欢就点个 star吧~
