### ISSUE TITLE
可以正常下载，但是在WEBUI处无显示

### ISSUE THREAD

**Issue by cielliyuanpeng** [acgotaku/BaiduExporter#304]
可以导出下载，但是在webui处没有提示
<img width="1275" alt="2016-10-10 10 29 52" src="https://cloud.githubusercontent.com/assets/15048475/19225780/9005eb7e-8ed4-11e6-8e66-73c13bc5c067.png">

**Comment by acgotaku** [comment]
@cielliyuanpeng 你这贴图毫无意义。。。 是确实在下载了 还是显示导出  其实没有导出到aria2c ？
具体是怎么导出的 自己网盘 还是分享页面？ 你这样只是浪费大家时间 ==

**Comment by cielliyuanpeng** [comment]
对不起……是确实在后台下载了，只能在本地静默的等待，不能在webui上进行暂停删除等操作。而且只有在我的网盘里出现导出下载的点击框，在其他百度云页面只有一个‘初始化成功！’的提示，并没有导出下载的框，请问如何解决呢？

**Comment by ShekBoy** [comment]
我用webui没这问题啊
那是因为百度云界面更新才没了按钮啊，耐心等更新就好

**Comment by acgotaku** [comment]
已更新
