### ISSUE TITLE
Failed to load resource: the server responded with a status of 414 (Request-URI Too Long)

### ISSUE THREAD

**Issue by Mygod** [acgotaku/BaiduExporter#306]
I was trying to download 646 files at the same time. And the link is 15703 characters long: https://pan.baidu.com/api/download?type=dlink&fidlist=...

Possibly split it up into several requests or somehow do a HTTP POST request?

**Comment by acgotaku** [comment]
Please share the file or fold, so I can test it.

**Comment by Mygod** [comment]
Sorry I'm not allowed to share these personal files. Perhaps you can find something else to test (e.g. downloading every file in your baidu pan perhaps) :stuck_out_tongue_closed_eyes:

**Comment by Mygod** [comment]
Why is this closed? :confused:

**Comment by acgotaku** [comment]
Because the path is too long, so the request error. It is not a issue

**Comment by Mygod** [comment]
And why isn't that an issue?

Based on my observations, you have to download a folder with lots and lots of files in it to reproduce this error.
