### ISSUE TITLE
Downloading medium-sized files can be optimized

### ISSUE THREAD

**Issue by Mygod** [acgotaku/BaiduExporter#307]
I'm currently downloading lots of medium-sized files (2M-6M) and the connection speed can be optimized by 4 times (from 500K to 2M) by adding `-k1M` or ` min-split-size=1M` in `aria2c.down` as binux does [in his repo](https://github.com/binux/lixian.xunlei). This will not influence download speed for large files. Perhaps add this option as well?

**Comment by acgotaku** [comment]
added it.

**Comment by Mygod** [comment]
Thanks.
