### ISSUE TITLE
百度云换了前端界面后 Exporter好像不能正常工作了

### ISSUE THREAD

**Issue by zazaluMonster** [acgotaku/BaiduExporter#308]
本来一进去初始化成功后就会跳出导出到aria2的按钮，现在只是显示一个初始化成功，然后什么都没有发生，不知道怎么弄了！qwq
比如我想下这个https://pan.baidu.com/share/link?shareid=1355889026&uk=3248159037

**Comment by zazaluMonster** [comment]
用的Chrome 最新的版本

**Comment by acgotaku** [comment]
@zazaluMonster 都不给我密码 我怎么搞。。。

**Comment by zazaluMonster** [comment]
@acgotaku 1113   抱歉。。。

**Comment by acgotaku** [comment]
@zazaluMonster 更新了

**Comment by zazaluMonster** [comment]
@acgotaku yes! 可以用了 谢谢！ 感谢付出！么么哒！！
