### ISSUE TITLE
已经更新了最新的版本，有出现按钮，但是好像不能导出

### ISSUE THREAD

**Issue by Danie1s** [acgotaku/BaiduExporter#309]
还有每次打开chrome都提示停用开发者模式，怎么破？

**Comment by acgotaku** [comment]
？？？ 分享页面不能导出？ 停用开发模式 你换非win系统可解

**Comment by li-xd** [comment]
下拉菜单里面只有 设置可以用 下载和导出下载点击按钮没反应 mac系统 已经停用开发模式

**Comment by acgotaku** [comment]
@Danie1s @li-xd   你是单文件还是 文件夹？ 给个例子？

**Comment by acgotaku** [comment]
单文件 已经解决了 看更新

**Comment by li-xd** [comment]
@acgotaku 我这里没有问题了 感谢 🙏

**Comment by Danie1s** [comment]
@acgotaku 单文件，mac系统，停用开发者模式就把插件就停用了

**Comment by acgotaku** [comment]
@Danie1s 那你每次就点击一下吧

**Comment by Danie1s** [comment]
@acgotaku 我知道怎么停用了，可以导出下载了，但是好像限速了

**Comment by acgotaku** [comment]
速度无法保证。。。

**Comment by Danie1s** [comment]
@acgotaku 
![ecc3fb56-f31d-432c-a1da-4846d1b902bc](https://cloud.githubusercontent.com/assets/19432029/19242257/ff0b0c50-8f44-11e6-813e-19a918f74ca4.png)
停用了开发者模式还是一样

**Comment by acgotaku** [comment]
@Danie1s 你每次点取消不就好了。。。。

**Comment by Danie1s** [comment]
@acgotaku 用户体验太差了。哈哈

**Comment by acgotaku** [comment]
@Danie1s 我查过 这个提示 是 取消不掉的。。。
不过你可以试试  http://www.javatang.com/archives/2015/04/26/34591223.html
