### ISSUE TITLE
这两天百度网盘升级, 好像BaiduExporter用不了

### ISSUE THREAD

**Issue by Daopr** [acgotaku/BaiduExporter#310]
昨天还能用, 今天网页上已经显示不出来了, 应该是换了代码了

**Comment by acgotaku** [comment]
@Daopr 你先更新代码试试好不？ 我昨天晚上都修复了。。。

**Comment by Vergil-Maro** [comment]
chrome 更新至 0.8.7 还是不行哎

**Comment by acgotaku** [comment]
@Vergil-Maro 那你至少描述清楚 怎么不行的啊 哪个页面啊？ 有试试多刷新几次么？ 有些时候加载不出来

**Comment by Daopr** [comment]
@acgotaku 刚学会, 更新到0.8.7, 解决了,:)

**Comment by Vergil-Maro** [comment]
@acgotaku 刚才是因为权限问题，感谢，已经好了

**Comment by oosaber** [comment]
谷歌浏览器不能加载应用商店外的插件   有什么办法吗 策略组的方法好像不行啊

**Comment by acgotaku** [comment]
@oosaber 源代码 载入 没有什么好的方法

**Comment by oosaber** [comment]
呃  怎么源代码 载入  用tampermonkey脚本加载吗

**Comment by acgotaku** [comment]
@oosaber 看 项目的readme啊

**Comment by oosaber** [comment]
Chrome : Click Settings -> Extensions -> Check Developer mode-> Load unpacked extension, navigate to the chrome folder, click OK.   就是加载chrome文件夹下的东西吧  这样刷新一下浏览器马上就会被禁用啊..

**Comment by acgotaku** [comment]
我这用的好好的。。。。 你不点禁用就不会被禁用

**Comment by oosaber** [comment]
x64稳定最新

**Comment by oosaber** [comment]
大神可以写个脚本吗
