### ISSUE TITLE
新版本不错，建议作者改下按钮样式

### ISSUE THREAD

**Issue by chenjun1119** [acgotaku/BaiduExporter#313]
![wechatimg634](https://cloud.githubusercontent.com/assets/2618148/19263200/b6e9b726-8fcd-11e6-8503-d63774fd44a4.jpeg)

我自己改了下分享界面的按钮。

另外建议n.show()的时候才添加button-open，否则按钮下面两个不是圆角了。
a.addClass("button-open");

**Comment by acgotaku** [comment]
已更新

**Comment by Calabor-Hoc** [comment]
给力！

**Comment by Danie1s** [comment]
@acgotaku 我觉得提问者的样式更好看啊，直接在已存在的按钮上添加，其他地方都不会出现偏移

**Comment by mkanako** [comment]
@acgotaku
![jietu](http://ww2.sinaimg.cn/large/94e640d3gw1f8prbn8c18j212q0cyq55.jpg)
UI是不是有问题啊，我刚刚才更新

**Comment by acgotaku** [comment]
@mkanako 网址发来 我看看

**Comment by mkanako** [comment]
https://pan.baidu.com/share/link?shareid=1027926625&uk=1798788396&from=hotrec#list/path=%2F
这个就正常
https://pan.baidu.com/s/191xx0
这个就有问题

**Comment by mkanako** [comment]
![jietu](http://ww1.sinaimg.cn/large/94e640d3gw1f8q3mw8t5sj21kw0ta7i4.jpg)
这样就正常了

**Comment by rcyggdra** [comment]
网盘主页左边多了一个上传样式，并且是点击无效的。
![image](https://cloud.githubusercontent.com/assets/8652464/19353570/5e4b25e4-9196-11e6-8aaf-a56b265c39c7.png)

**Comment by FenixSIS** [comment]
那個，分享頁面是不錯，但好像在自己的網盤主頁裡面並沒有導出下載的選項呀。。

**Comment by acgotaku** [comment]
@rcyggdra 这个好像是随机出发的 但不影响正常功能使用
