### ISSUE TITLE
新样式下的JS bug

### ISSUE THREAD

**Issue by sequencer** [acgotaku/BaiduExporter#314]
![screen shot 2016-10-11 at 22 33 32](https://cloud.githubusercontent.com/assets/5791019/19274456/c551c792-9002-11e6-9e5c-a48309ba181e.png)
无法出现下载按钮
感觉是百度云吧get的函数直接删除了？

**Comment by Cee** [comment]
Safari is not under maintenance, use Chrome extension instead.
