### ISSUE TITLE
求助加token连不上！！！

### ISSUE THREAD

**Issue by lbbboy** [acgotaku/BaiduExporter#315]
![qq 20161011235359](https://cloud.githubusercontent.com/assets/7271994/19278022/65880428-900e-11e6-8149-b12ef373be13.png)

 yaaw可以
![3](https://cloud.githubusercontent.com/assets/7271994/19278046/81b00402-900e-11e6-9ea1-3c8376f47ec7.png)

地址：http://token:92y#VnE3JFgH@babybeet.oicp.net/jsonrpc

**Comment by Calabor-Hoc** [comment]
作者很给力，已经更新了版本，你在装下新版本插件

**Comment by lbbboy** [comment]
![x](https://cloud.githubusercontent.com/assets/7271994/19294407/d41f7da8-905e-11e6-8daf-64b7187d3bf5.png)
@acgotaku 还是不行呢！

**Comment by acgotaku** [comment]
@lbbboy 把这个ariac服务器一直开着 我晚上调试 现在上班呢。。。

**Comment by acgotaku** [comment]
@lbbboy URL里面 #是有特殊意义的 所以请使用其他特殊字符。。你这个URL被认为是不合法的

**Comment by Calabor-Hoc** [comment]
@lbbboy 应该就是作者说的原因，关掉这个issue吧
