### ISSUE TITLE
百度网盘使用哪个版本的ua快?

### ISSUE THREAD

**Issue by shoyuf** [acgotaku/BaiduExporter#316]
使用code tips的netdisk;Chrome Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.87 Safari/537.36

还是使用自带的netdisk;5.3.4.5;PC;PC-Windows;5.1.2600;WindowsBaiduYunGuanJia

**Comment by shoyuf** [comment]
还有....谷歌商店的是不是被下架了?

**Comment by acgotaku** [comment]
@shoyuf  你自己测试下不就知道了  下架了 不会再上架
