### ISSUE TITLE
限速为1M每秒

### ISSUE THREAD

**Issue by 494895913** [acgotaku/BaiduExporter#317]
更改报头依旧被限速

**Comment by acgotaku** [comment]
我只保证能下载 不保证速度。。。。 因为速度这个太难测试了

**Comment by tmdhx** [comment]
百度云没线程限速100kb，导出到aria2gui是10线程，所以是100*10=1mb。建议改成20以上。。

**Comment by qweaszxcdf** [comment]
aria2c最多16线程

**Comment by tmdhx** [comment]
以前不知道，居然真的是16线程呀！不管是线程数，还是同一服务器连接数都是16。
