### ISSUE TITLE
Aria2下载报错

### ISSUE THREAD

**Issue by Daymond** [acgotaku/BaiduExporter#318]
在百度网盘同时下载3个文件，隔三差五报错。同时，会导致文件下载不完整。
配置：Win10 X64，已Git更新最新版Chrome插件+Aria2 1.27下载。
注：不清楚反映到这里合不合适，不合适就关掉问题吧。

![image](https://cloud.githubusercontent.com/assets/8046129/19298091/556fd362-907d-11e6-99cc-dc68a7673796.png)

**Comment by lautis0503** [comment]
百度云还会0KB/S呢
任务删了重下就好，只要路径相同文件没删，aria2会继续之前的下载

**Comment by Daymond** [comment]
嗯，多尝试了几下，发现可能真的是时间点不对。
