### ISSUE TITLE
能否提供crx，开发者模式导入总是会提示停用

### ISSUE THREAD

**Issue by one360** [acgotaku/BaiduExporter#319]
开发者模式导入，每次打开chrome都提示停用开发者模式。crx直接安装，不会提示。

**Comment by Danie1s** [comment]
同意

**Comment by lautis0503** [comment]
这和crx有什么关系……

**Comment by acgotaku** [comment]
提供crx也会说 不是商店的自动 禁用  所以不同意

**Comment by one360** [comment]
我和 上面的lautis0503  一样，直接crx，并不自动禁用

**Comment by lbbboy** [comment]
下载chrome.adm组策略模板，导入。然后把扩展ID填入白名单。自己打包一个crx。

**Comment by xjbeta** [comment]
不如做成油猴脚本？

**Comment by mzhboy** [comment]
哈哈哈，找到解决办法了，需要patch chrome.dll。
[How to hack chrome.dll to get rid of the “disable developer mode extensions” pop up](http://stackoverflow.com/questions/30287907)

**Comment by lautis0503** [comment]
用chromium不是最快捷的吗

**Comment by jeffjleung** [comment]
@mzhboy 请问 Mac 用户有解决方案吗？

**Comment by Explorare** [comment]
@jeffjleung [Guide on Packaging and Import Baidu Exporter to Chrome | HentaiCollection](https://hencolle.com/2016/10/16/baidu_exporter/)
[Set Chrome policies for devices - Chrome for business and education Help](https://support.google.com/chrome/a/answer/187202?hl=en)
