### ISSUE TITLE
将“保存下载链接”改为直接链接到下载地址会不会更好些？

### ISSUE THREAD

**Issue by KyonLi** [acgotaku/BaiduExporter#32]
现在的“保存下载链接”按钮是将地址保存到文件中，每次想调用下载工具下载时都要打开那个文件将地址复制出来，很不方便。可否将这个按钮改为直链或者再加入一个直链按钮，这样会方便很多。

**Comment by acgotaku** [comment]
@KyonLi 你是用什么下载工具调用的? 主要是下载的链接都需要Cookies和UA参数才行.直链一般不能使用吧?

**Comment by KyonLi** [comment]
@acgotaku 抱歉，是我没注意到这个链接和chrome直接下载的是不一样的，从chrome下载任务中得到的链接可以用于下载工具而这个不行。

**Comment by acgotaku** [comment]
@KyonLi  因为这个获取的是一个需要跳转的网址...chrome自动完成了这个过程

**Comment by KyonLi** [comment]
@acgotaku 原来是这样，谢谢解答 :)
