### ISSUE TITLE
最新版本的谷歌浏览器用不了

### ISSUE THREAD

**Issue by liubangjain** [acgotaku/BaiduExporter#320]
最新版本的谷歌浏览器用不了，请问有解决方案吗？

**Comment by acgotaku** [comment]
??? 多新？ 为啥用不了？

**Comment by dyang-7** [comment]
”无法添加来自此网站的引用、扩展程序和用户脚本“

**Comment by acgotaku** [comment]
你这说的不明不白。。。还是别用了吧

**Comment by liubangjain** [comment]
安装了谷歌浏览器（54.0.2840.59.m 64x）通过【打包扩展程序】方式安装插件，能成功安装和使用，在浏览器【扩展程序】显示“并非来自chrome网上应用店。”，完全关闭浏览器后，就不能正常开启了。请问作者这个问题如何解决？@acgotaku

**Comment by acgotaku** [comment]
@liubangjain 再来一次

**Comment by liubangjain** [comment]
@acgotaku 每次需要用的时候，都安装一次？

**Comment by Explorare** [comment]
Here is a solution for it.
https://hencolle.com/2016/10/16/baidu_exporter/

**Comment by liubangjain** [comment]
@Explorare thx
