### ISSUE TITLE
导出链接显示“网络请求失败”

### ISSUE THREAD

**Issue by Jason4774** [acgotaku/BaiduExporter#322]
您好，
![qq 20161014212140](https://cloud.githubusercontent.com/assets/19594338/19388990/bc3a5a26-9254-11e6-8870-80f78b16fb30.png)

1.不知道是不是因为文件太多才导致的这个错误。我在这个目录导出链接就会出现这个错误，但是进入这个目录后导出一个子目录的链接就是正常的，请问有解决办法吗？谢谢。
2.另外我导出为IDM文件后再导入到IDM中全部都识别不出来，显示Error。请问怎么解决？

**Comment by acgotaku** [comment]
居然是传智播客。。。。 你可以分享下这个文件 我试试

**Comment by Jason4774** [comment]
不知道链接会不会失效
https://pan.baidu.com/s/1jIuKhMm
谢谢

**Comment by acgotaku** [comment]
@Jason4774 路径实在太长 导致 无法下载 这时候只能从子文件开始下载了 文件太深了

**Comment by Jason4774** [comment]
我还以为是因为文件太多的问题，看你网站下面也有人遇到我这样的问题，

还有就是我导出为IDM文件后再导入到IDM中全部都识别不出来，显示Error。请问怎么解决？

**Comment by acgotaku** [comment]
IDM本来就问题很多 还是用aria2c吧

**Comment by Jason4774** [comment]
谢谢，还有请问一下比如我有时候要下载youtube视频的话，用IDM可以设置代理，那么用aria2c的话怎么才能设置代理呢？

**Comment by acgotaku** [comment]
@Jason4774  https://aria2.github.io/manual/en/html/aria2c.html 自己看文档

**Comment by Jason4774** [comment]
好的，谢谢你。

**Comment by Jason4774** [comment]
发现导出的链接就是有问题，之前用IDM导入链接下载不了，但是用其他的下载还是不行，应该是导出的链接有问题了，虽然我还能用aria2下载，但是如果导出的链接也能用的话就更好了
![image](https://cloud.githubusercontent.com/assets/19594338/19409604/f7fe2140-9309-11e6-882e-732316871432.png)
![image](https://cloud.githubusercontent.com/assets/19594338/19409606/0d798a5a-930a-11e6-83f5-a19c63553557.png)
谢谢

**Comment by acgotaku** [comment]
IDM有时间再修 只保证 aria2c能用
