### ISSUE TITLE
添加不要自动开始BT下载的选项

### ISSUE THREAD

**Issue by Mapaler** [acgotaku/BaiduExporter#323]
这样全选，都是种子离线下载的文件夹
![](http://ww2.sinaimg.cn/large/6c84b2d6gw1f8s5vai9fkj20qh0ivdju.jpg)
Aria2就会出现一些光是文件夹名字的下载（其他文件已经下载好了）
![](http://ww3.sinaimg.cn/large/6c84b2d6gw1f8s5w1j0obj20x20h1wjw.jpg)
点开是这个样子
![](http://ww3.sinaimg.cn/large/6c84b2d6gw1f8s5xge9l8j20rl0eh43r.jpg)
昨天单独点选都没有出现这个问题，今天晚上发现了这个问题
<hr>
后来想到是昨晚没有选中种子，今天选中种子后就会自动开始下载，所以多出来的都是BT下载任务。
所以给Aria2 post一个不要自动开始BT下载的选项。

当前用的版本
![](http://ww4.sinaimg.cn/large/6c84b2d6jw1f8s62w30y4j20hn0fuq60.jpg)

**Comment by acgotaku** [comment]
你可以直接在配置文件里面写上 没必要插件去开发

**Comment by acgotaku** [comment]
--follow-torrent=true|false|mem

**Comment by Mapaler** [comment]
好的，谢谢
