### ISSUE TITLE
文件夹结构层数问题

### ISSUE THREAD

**Issue by qweaszxcdf** [acgotaku/BaiduExporter#326]
当前已将文件夹结果层数设置为0，但在如https://pan.baidu.com/wap/link?shareid=3780700284&uk=2217698&third=0&dir=%2F%E6%88%91%E7%9A%84%E8%B5%84%E6%BA%90%2F%E5%A4%A7%E4%B8%80%E5%A4%A7%E4%BA%8C%E4%B8%B4%E5%BA%8A%E5%8C%BB%E5%AD%A6%E5%85%AB%E5%B9%B4%E5%88%B6%E6%95%99%E6%9D%90&page=1 下载时，保存的文件名为“大一大二临床医学八年制教材/临床医学第八版教材/人卫第八版病理学.pdf ”

**Comment by acgotaku** [comment]
可以分享个桌面版本的么？

**Comment by lautis0503** [comment]
我这里分享界面直接导出正常

**Comment by qweaszxcdf** [comment]
https://yun.baidu.com/share/link?shareid=3780700284&uk=2217698&third=0&dir=/%E6%88%91%E7%9A%84%E8%B5%84%E6%BA%90/%E5%A4%A7%E4%B8%80%E5%A4%A7%E4%BA%8C%E4%B8%B4%E5%BA%8A%E5%8C%BB%E5%AD%A6%E5%85%AB%E5%B9%B4%E5%88%B6%E6%95%99%E6%9D%90&page=1#list/path=%2F @acgotaku

**Comment by acgotaku** [comment]
这个有什么不对的么？ 就应该是这样的路径才对啊

**Comment by qweaszxcdf** [comment]
0与-1的区别在哪里，能否举例说明

**Comment by acgotaku** [comment]
0就是 保留到当前文件夹的路径 -1是 无论你在哪个文件夹 下载的都是从最外面的文件夹 到文件
