### ISSUE TITLE
目前火狐的加载方式，重启火狐之后扩展就没了

### ISSUE THREAD

**Issue by yulelong** [acgotaku/BaiduExporter#327]
虽然已经兼容了，但是用起来还是太不方便，每次要用的时候都切换到chrome去，唉。。没有更好的解决方案了吗？

**Comment by qweaszxcdf** [comment]
chrome文件夹重命名为{59f15a1c-8a61-4b60-b4f0-64eb531bcaa6} 形式，丢到/extension里 restart firefox

**Comment by yulelong** [comment]
50b7里面会提示“未通过针对是否适用于Firefox 的验证，现已被禁用”，好像是因为签名的问题？

**Comment by yulelong** [comment]
搞定了，用了卡饭的绕过签名补丁，然后再用二楼的方法重装扩展就OK了，非常感谢~

**Comment by debiansid** [comment]
怎么安装到火狐？

**Comment by yulelong** [comment]
下载后，解压，有个chrome文件夹。然后把这个文件夹重命名为{59f15a1c-8a61-4b60-b4f0-64eb531bcaa6} 形式，然后放到配置文件夹下面的extension文件夹里面，然后重启火狐。配置文件夹可以在about:support里面看到

**Comment by yulelong** [comment]
绕过签名可以看这里http://bbs.kafan.cn/thread-2052440-1-1.html  方法C，或者这个批处理http://bbs.kafan.cn/thread-2051375-1-1.html。一定要绕过签名后再装扩展，或者重新安装扩展，不然还是会提示未验证。
