### ISSUE TITLE
Nothing happened when load temporary addon with firefox esr 45.4

### ISSUE THREAD

**Issue by yunlhan** [acgotaku/BaiduExporter#329]
Hello, 

I followed your readme file and tried to load temporary add-on in firefox esr 45.4.0 but I didn't see the baiduexporter add-on showing up in the add-ons listed below. 

What I did was,

1. Checked out your latest code as a zip archive;
2. Extracted the archive;
3. Went to firefox and typed 'about:debugging' in the url bar;
4. Clicked 'load temporary add-on' and a window popped up saying 'select add-on directory or xpi file';
5. Went to chrome folder and picked any file in the chrome folder then clicked ok.

But nothing happened. Is there anything wrong with the above installation? Is it working for you with firefox?

Thanks.

**Comment by acgotaku** [comment]
What do you want happened?  Do you know  the extension?

**Comment by yunlhan** [comment]
Thanks for your reply. My question was using the installation method mentioned in the readme only works for newer firefox (e.g. firefox 49) but it won't work for older ones like the ESR firefox 45. So is it there any plan to support firefox ESR 45? Thanks.
