### ISSUE TITLE
The speed is too slow 20161017

### ISSUE THREAD

**Issue by chenzhiwei** [acgotaku/BaiduExporter#330]
When I use 115 vip download URL the speed is 15M~18M, but when I use BaiduExporter the speed is only 500KB.

500KB is the normal download speed in my environment, weird.

**Comment by R-L-T-Y** [comment]
i second that. I get 100-300KB/s when i'm supposed to run 3-5MB/s.

**Comment by giveup** [comment]
限速这个，因素太多。如个人网络环境，百度服务器限制。（需要VIP或者user agent伪装）

**Comment by R-L-T-Y** [comment]
用百度网盘第三方API下好像是现在的最优解。不用UA cookie 可以满速

**Comment by XhstormR** [comment]
@R-L-T-Y 推荐个第三方的吧。

**Comment by R-L-T-Y** [comment]
www.loveno.net/baiduyun 就是不如这个方便了 @XhstormR

**Comment by briankwon** [comment]
有类似的情况，连接数15，单任务下载速度最大150KB/S，用的默认UA。

**Comment by ocean521** [comment]
请问在哪里可以设置默认链接数和单任务速度啊。威联通装的ARIA2

**Comment by tryeverything** [comment]
现在百度云是不是限速了？刚开始才200k左右，一会儿就降到20k左右速度。
@ocean521 这个可以在配置文件里写。

**Comment by R-L-T-Y** [comment]
https://aria2.github.io/manual/en/html/aria2c.html

On Tue, Oct 25, 2016, 8:01 PM ocean521 <notifications@github.com<mailto:notifications@github.com>> wrote:

请问在哪里可以设置默认链接数和单任务速度啊。威联通装的ARIA2

**Comment by briankwon** [comment]
你好，

修改aria2.conf文件就可以了，具体方法可以百度下。
-------------------------------
Brian Kwon
briankwon14@gmail.com

**Comment by tryeverything** [comment]
度娘不好玩了。还不到100k的速度。还是扔迅雷了

**Comment by briankwon** [comment]
试了下办会员倒是能提不少速度…就是这事办的太操蛋了= =
-------------------------------
Brian Kwon
briankwon14@gmail.com

**Comment by tofuliang** [comment]
还是看资源的，我下载之前转存的Photoshop安装包，有3MB/s

briankwon <notifications@github.com>于2016年10月26日周三 下午11:42写道：

**Comment by ocean521** [comment]
我一般是使用这个  aria2c --enable-rpc --rpc-listen-all=true --rpc-allow-origin-all --dir=/share/Download --file-allocation=none -s 5 -j 3 -x 5 -c -D  来启动威联通的ARIA,我理解这个是按照5个连接下载的，非专业人事，还请赐教。另外威联通的AIRA2目前还是1.14.2版本么,非ARM。

**Comment by Biggulu** [comment]
[https://blog.icehoney.me/posts/2015-01-31-Aria2-download](https://blog.icehoney.me/posts/2015-01-31-Aria2-download)作者的blog里有教程，用配置文件

**Comment by Biggulu** [comment]
@ocean521  [https://blog.icehoney.me/posts/2015-01-31-Aria2-download](https://blog.icehoney.me/posts/2015-01-31-Aria2-download)作者blog中有教程，使用配置文件

**Comment by ocean521** [comment]
UA的话是不是就是在插件里改，配置文件里没有相应的设定。有什么好的UA么，用了两个速度都不行。而且发现百度云有的文件下载速度还行，有的就下载一会就失败。
