### ISSUE TITLE
被 chrome 禁用了

### ISSUE THREAD

**Issue by thescfai** [acgotaku/BaiduExporter#332]
直接提示并非来自 Chrome 网上应用店。然后就木有然后了，求破解。

**Comment by Explorare** [comment]
Search the issues before open a new one please.
[Guide on Packaging and Import Baidu Exporter to Chrome | HentaiCollection](https://hencolle.com/2016/10/16/baidu_exporter/)

**Comment by thescfai** [comment]
@Explorare 跳转过去看了下，是在win平台进行操作的，那问题来了，chrome for mac上如何操作呢？

**Comment by Explorare** [comment]
@thescfai [Set Chrome policies for devices - Chrome for business and education Help](https://support.google.com/chrome/a/answer/187202?hl=en)
