### ISSUE TITLE
遭遇百度云空文件夹，插件出错

### ISSUE THREAD

**Issue by arstum** [acgotaku/BaiduExporter#333]
子目录里只要存在一个空文件夹，都会出现 “X 未知错误” ，导致失败。

**Comment by arstum** [comment]
发起 Issue 时，请最好提供：

您下载的内容地址
几个账号都有这情况。
插件版本号
0.8.7
最新浏览器版本号
 53.0.2785.143 (64-bit)系统版本号

列举出现问题的详细步骤
描述能否复现问题

**Comment by acgotaku** [comment]
知道了 我抽空解决

**Comment by acgotaku** [comment]
虽然空的回 报错误 但是其他文件还是正常下载啊

**Comment by HerringtonDarkholme** [comment]
Close due to inactivity
