### ISSUE TITLE
firefox无法安装插件

### ISSUE THREAD

**Issue by Rogershenyc** [acgotaku/BaiduExporter#334]
firefox临时加载组件，选择chrome文件夹之后就直接打开了，不能像chrome那样直接安装，求解决，谢谢！

**Comment by acgotaku** [comment]
没有解决方案！ 就直接文件夹载入！

**Comment by Rogershenyc** [comment]
好吧，谢谢回复！

**Comment by Mapaler** [comment]
firefox怎么能安装chrome的插件呢

**Comment by acgotaku** [comment]
firefox兼容chrome的扩展开发API 所以可以安装 前提是 最新的Firefox
