### ISSUE TITLE
导出的IDM配置文件有问题

### ISSUE THREAD

**Issue by ysc3839** [acgotaku/BaiduExporter#335]
最后应该加上一个空行，否则IDM无法读取

**Comment by acgotaku** [comment]
啥意思？

**Comment by ysc3839** [comment]
你自己试试，导出一个IDM配置文件，看看能否读取。再用文本编辑器在导出的文件最后面加上一个空行(new line at end of file)，看看能否读取。

**Comment by LuckyJJ** [comment]
导出的idm.txt用idm打开时为什么都是error

**Comment by zzzz438** [comment]
对的，是这样的，导出文件，不在末尾加个空行，idm不读取

**Comment by acgotaku** [comment]
我的IDM过期了。。。 我默认已经在最后在末尾有个空行的

**Comment by ysc3839** [comment]
但实际导出的是没有的

**Comment by acgotaku** [comment]
![screenshot from 2016-11-06 15-18-41](https://cloud.githubusercontent.com/assets/1191834/20035978/f9a74560-a3be-11e6-825f-fef4b06abcdf.png)
我导出的是这个效果啊

**Comment by ysc3839** [comment]
检查代码，是不是写成了\n，应该写\r\n

**Comment by HerringtonDarkholme** [comment]
Please provide informative reproduction.

**Comment by acgotaku** [comment]
改成 \r\n了 你试试
