### ISSUE TITLE
safari到底是个什么情况。。。。

### ISSUE THREAD

**Issue by bAnonym** [acgotaku/BaiduExporter#336]
“全面支持 Chrome, Firefox, Edge 和 Safari：”
“Safari : Install Chrome or Firefox on Mac.”
？？？？

**Comment by ysc3839** [comment]
写错了吧，不支持

**Comment by Cee** [comment]
Used to be supported, but now we couldn't get cookies from Baidu.

**Comment by chaoqing** [comment]
可不可能把这个做成油猴脚本，然后让用户自己输入cookie？

**Comment by Explorare** [comment]
@chaoqing Sorry but the author don't have time to do this. You could try it yourself.

**Comment by ysc3839** [comment]
document.cookie no work?
