### ISSUE TITLE
可以上传到 Chrome Web Store 吗？

### ISSUE THREAD

**Issue by onestark** [acgotaku/BaiduExporter#337]
旧版的可以在 Chrome Web Store 下载和更新，现在好像在商店找不到了，不能方便地自动更新。

**Comment by Explorare** [comment]
No, this plugin is been removed due to complaint from Baidu. Please import the new version locally.
[Guide on Packaging and Import Baidu Exporter to Chrome | HentaiCollection](https://hencolle.com/2016/10/16/baidu_exporter/)
