### ISSUE TITLE
Chrome54版自动禁止这个插件的运行

### ISSUE THREAD

**Issue by anuxs** [acgotaku/BaiduExporter#338]
1、chrome store 里面找不到这个插件了，因为安全机制通不过吧；
2、直接装这个git里面的chrome.crx（在开发模式下拖进来），刚开始可以用，过一分钟不到chrome提示该插件处于不安全的开发模式，直接禁用并且无法手动启用。之前的53版是提示，但是不禁用。
3、现在没法用了，希望能修复这个问题。

**Comment by Explorare** [comment]
1. This plugin is removed due to complaint from Baidu. It may never upload to App Store again.
2. Please read README and issues before open a new issue. #332 
3. Which version do you use?

**Comment by acgotaku** [comment]
开启 开发者模式可以使用
