### ISSUE TITLE
导出下载失败

### ISSUE THREAD

**Issue by srwgin** [acgotaku/BaiduExporter#34]
链接：http://pan.baidu.com/s/1i3in5rB 密码：trlw
aria2和插件都是最新版 测试连接 能成功显示版本号 游览器是 chrome dev 版本 42.0.2292.0
user-agent 是 netdisk;4.4.0.6;PC;PC-Windows;6.2.9200;WindowsBaiduYunGuanJia
referer 是 http://pan.baidu.com/disk/home
点了导出下载后 YAAW不能下载
查了下aria2的log 如下
2015-02-08 11:51:01.332161 [ERROR] [AbstractCommand.cc:350] CUID#124 - Download aborted. URI=http://d.pcs.baidu.com/file/3361145761a7a3aa65bd77c8d5b9bc6f?fid=4013835717-250528-457850779889932&time=1423367488&rt=sh&sign=FDTAERVY-DCb740ccc5511e5e8fedcff06b081203-K20CCZcUXanIRPbbFeJS9WrjM8s%3D&expires=8h&prisign=GF6x2T2CVlRV01o7Pki028kp4XDNjnf6nYJvYvdmp+dC6iCzPtkM2aVC7McRJk1P9QVPB1kIp0CifNIlOMwtq9leEvhTVhjRcR83gRp4oLDRWmsGuAvcBYV8AuWyIY+MMgBGtp0Ig4RsGwreatsa2tnT0FmIWjcIXt3AZwr/EjOP33vWkpqj9AAuQPFb4kkLIagf7X6xM4C3yPqz/DWorP8NDqStnNmhLr6pwCepnkPWRTygQouwoNvlVHTxmi3P0dCdmzewkYg8L3LnlrwjPxf/hCNHfp6v&chkv=1&chkbd=0&chkpc=et&r=750557163
Exception: [AbstractCommand.cc:350] errorCode=22 URI=http://d.pcs.baidu.com/file/3361145761a7a3aa65bd77c8d5b9bc6f?fid=4013835717-250528-457850779889932&time=1423367488&rt=sh&sign=FDTAERVY-DCb740ccc5511e5e8fedcff06b081203-K20CCZcUXanIRPbbFeJS9WrjM8s%3D&expires=8h&prisign=GF6x2T2CVlRV01o7Pki028kp4XDNjnf6nYJvYvdmp+dC6iCzPtkM2aVC7McRJk1P9QVPB1kIp0CifNIlOMwtq9leEvhTVhjRcR83gRp4oLDRWmsGuAvcBYV8AuWyIY+MMgBGtp0Ig4RsGwreatsa2tnT0FmIWjcIXt3AZwr/EjOP33vWkpqj9AAuQPFb4kkLIagf7X6xM4C3yPqz/DWorP8NDqStnNmhLr6pwCepnkPWRTygQouwoNvlVHTxmi3P0dCdmzewkYg8L3LnlrwjPxf/hCNHfp6v&chkv=1&chkbd=0&chkpc=et&r=750557163
  -> [HttpSkipResponseCommand.cc:228] errorCode=22 The response status is not successful. status=403
------
session 如下
http://d.pcs.baidu.com/file/3361145761a7a3aa65bd77c8d5b9bc6f?fid=4013835717-250528-457850779889932&time=1423367488&rt=sh&sign=FDTAERVY-DCb740ccc5511e5e8fedcff06b081203-K20CCZcUXanIRPbbFeJS9WrjM8s%3D&expires=8h&prisign=GF6x2T2CVlRV01o7Pki028kp4XDNjnf6nYJvYvdmp+dC6iCzPtkM2aVC7McRJk1P9QVPB1kIp0CifNIlOMwtq9leEvhTVhjRcR83gRp4oLDRWmsGuAvcBYV8AuWyIY+MMgBGtp0Ig4RsGwreatsa2tnT0FmIWjcIXt3AZwr/EjOP33vWkpqj9AAuQPFb4kkLIagf7X6xM4C3yPqz/DWorP8NDqStnNmhLr6pwCepnkPWRTygQouwoNvlVHTxmi3P0dCdmzewkYg8L3LnlrwjPxf/hCNHfp6v&chkv=1&chkbd=0&chkpc=et&r=750557163	
 gid=1eb865d2d3c8ee53
 out=[TVBT]Onichan Gacha_EP_05_ChineseSubbed.rar
 header=User-Agent: netdisk;4.4.0.6;PC;PC-Windows;6.2.9200;WindowsBaiduYunGuanJia
 header=Cookie: BDUSS=??????;pcsett=1406947345-943aae467dc51cf71b6f758bc2c9900f
 header=Referer: http://pan.baidu.com/disk/home

**Comment by srwgin** [comment]
我现在直接点上面这3段一模一样的连接 游览器能直接下载
但是无论是复制到YAAW或者IDM 都是出错不能下载

**Comment by acgotaku** [comment]
@srwgin 我测试正常啊 
 
![2015-02-08-171215_1191x266_scrot](https://cloud.githubusercontent.com/assets/1191834/6096026/debaa282-afb5-11e4-98ed-11a45e1649e3.png)

可以贴一下导出下载的内容么？

我的是：

aria2c -c -s10 -k1M -x10 -o "[TVBT]Onichan Gacha_EP_05_ChineseSubbed.rar" --header "User-Agent: netdisk;4.4.0.6;PC;PC-Windows;6.2.9200;WindowsBaiduYunGuanJia" --header "Cookie: BDUSS=mVEM2hhQ01BSjZaNW9UNFpZN2dtd2xSRTZtV2tWejJ0LVA3VDkybWx5TUFsfkJUQVFBQUFBJCQAAAAAAAAAAAEAAADGtAcR0anUwsfvy64AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAKyVMACslTU;pcsett=1423473052-0618fc427c797ec925b0c65467fbeb42" --header "Referer: http://pan.baidu.com/disk/home" "http://d.pcs.baidu.com/file/3361145761a7a3aa65bd77c8d5b9bc6f?fid=4013835717-250528-457850779889932&time=1423386702&rt=sh&sign=FDTAERV-DCb740ccc5511e5e8fedcff06b081203-pmU4G30oMaXorY9aJtosrE8OmKo%3D&expires=8h&prisign=GF6x2T2CVlRV01o7Pki028kp4XDNjnf6CVWFyGHXfF1sw2F/MtZBrXv2VqJXJ/JF+Cp53dO5wKh9aUTnLtWrSAv2VCLwunz5GhdLr1OwKGECugcu65nW6jNQbuzkJJ0QTthWMjKwqVJ/K2FlEhR1ddKfxiciRCca/tIS6DrqIid232pW9BdEEXBtrRUCrJk24Z4PhlI9aaWmGWf45XtVqAe6B4JW0LQ1lU2PQZoi7T2Xy6Sw91TcJqD+SC8jUjogu5HCqEVngRLJ9Gm6Hk3KNtKlBeLe65tG&chkv=1&chkbd=0&chkpc=&r=297023451"

**Comment by srwgin** [comment]
aria2c -c -s10 -k1M -x10 -o "[TVBT]Onichan Gacha_EP_05_ChineseSubbed.rar" --header "User-Agent: netdisk;4.4.0.6;PC;PC-Windows;6.2.9200;WindowsBaiduYunGuanJia" --header "Cookie: BDUSS=B6T0MzdllpZEt2V2MyfkVUYTFncGRScEhXbXVmWUZaYkdkM1JBVEdBeGJwTjFVQVFBQUFBJCQAAAAAAAAAAAEAAACLhWoSc3J3Z2luAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAFsXtlRbF7ZULT;pcsett=1406947345-943aae467dc51cf71b6f758bc2c9900f" --header "Referer: http://pan.baidu.com/disk/home" "http://d.pcs.baidu.com/file/3361145761a7a3aa65bd77c8d5b9bc6f?fid=4013835717-250528-457850779889932&time=1423404344&rt=sh&sign=FDTAERVY-DCb740ccc5511e5e8fedcff06b081203-b7E0CBAMVuH8%2FrnXCgNQz58KMy4%3D&expires=8h&prisign=GF6x2T2CVlRV01o7Pki028kp4XDNjnf6nYJvYvdmp+dC6iCzPtkM2aVC7McRJk1P9QVPB1kIp0CifNIlOMwtq9leEvhTVhjRcR83gRp4oLDRWmsGuAvcBYV8AuWyIY+MMgBGtp0Ig4RsGwreatsa2tnT0FmIWjcIXt3AZwr/EjOP33vWkpqj9AAuQPFb4kkLIagf7X6xM4C3yPqz/DWorP8NDqStnNmhLr6pwCepnkPWRTygQouwoNvlVHTxmi3P0dCdmzewkYg8L3LnlrwjPxf/hCNHfp6v&chkv=1&chkbd=0&chkpc=et&r=526094248"

**Comment by srwgin** [comment]
順便貼下 aria2的設置
log=D:\software\aria2c\aria2c.log
log-level=warn
enable-rpc=true
rpc-allow-origin-all=true
rpc-listen-all=true
#rpc-listen-port=6800
#rpc-passwd=ftp123
#rpc-user=ftp
max-concurrent-downloads=1
continue=true
max-connection-per-server=5
min-split-size=10M
split=10
max-overall-download-limit=0
max-download-limit=0
max-overall-upload-limit=10
max-upload-limit=10
#lowest-speed-limit=0
#referer=*
input-file=D:\software\aria2c\aria2c.session
save-session=D:\software\aria2c\aria2c.session
save-session-interval=60
dir=D:\temp\old\
#disk-cache=0
#enable-mmap=true
file-allocation=prealloc
bt-enable-lpd=false
#bt-tracker=<URI>,…
#bt-max-peers=55
#bt-require-crypto=true
follow-torrent=true
#listen-port=6881-6999
enable-dht=false
dht-file-path=D:\software\aria2c\dht.dat
enable-peer-exchange=false
user-agent=uTorrent/3420(38429)
peer-id-prefix=-UT3420-
seed-ratio=1
seed-time=0
force-save=false
bt-hash-check-seed=true
check-integrity=true
bt-save-metadata=false

**Comment by acgotaku** [comment]
@srwgin 奇怪了 我把我的链接替换成你的能下载 把你的链接替换成我的也能下载
但是你的就是不能下载。。。

**Comment by srwgin** [comment]
會不會是 cooikes 問題？

**Comment by acgotaku** [comment]
@srwgin 你可以试试重新登录下

**Comment by srwgin** [comment]
果然 嘗試清空所有baidu的 cooikes 就能下了 - -
之前怎麼沒想到

**Comment by acgotaku** [comment]
@srwgin 噗 肯定是百度自己出问题了
