### ISSUE TITLE
照說明安裝在FireFox，but nothing happens

### ISSUE THREAD

**Issue by gnhs** [acgotaku/BaiduExporter#346]
照著說明“•Firefox : Open about:debugging in Firefox, click "Load Temporary Add-on" and navigate to the  chrome  folder, click OK.” 但是完全沒有任何動作也沒有任何訊息出現
試過點選 chrome  folder下的每一個檔案，結果都是沒有動作

**Comment by acgotaku** [comment]
请确保是最新版Firefox

**Comment by gnhs** [comment]
原Firefox版本v47無法安裝新版BaiduExporter，更新到v49.2可以了，但是只能暫時安裝每次重啟都要重新安裝，除非用開發人員版

**Comment by gnhs** [comment]
更新到Firefox v49.2虽然可以暂时安装BaiduExporter，可是在百度网盘的页面当选取了一个下载档案，“导出下载”会立刻消失不见，如果不选取任何档案则，“导出下载”会正常显现在“我的设备”右方

**Comment by qiangwushuang** [comment]
提示导出失败，是否没有开启ARIA2。

**Comment by gnhs** [comment]
不是 导出失败，是“导出下载”的下拉选单消失不见，ARIA2有开启
不过现在会正常出现没问题了

**Comment by firstuanl** [comment]
选 manifest.json 安装
