### ISSUE TITLE
为什么下个压缩包会分成那么多个部分？

### ISSUE THREAD

**Issue by WongCM** [acgotaku/BaiduExporter#348]
![2016-10-26 3 25 40](https://cloud.githubusercontent.com/assets/7736862/19717041/6302b098-9b91-11e6-88b5-9f2648b44ffb.png)

**Comment by WongCM** [comment]
总共有14个部分 这只是个60m的小文件呀

**Comment by acgotaku** [comment]
问你的 aria2c去 又不是我的锅

**Comment by HerringtonDarkholme** [comment]
This is split download feature which uses multiple connections.
