### ISSUE TITLE
在百度云中拷贝下载链接的问题

### ISSUE THREAD

**Issue by ubuntuwbw** [acgotaku/BaiduExporter#349]
选中百度云中的文件夹后，点击插件的导出下载中的导出下载，在弹出的对话框中点击拷贝下载链接，然后在远程迅雷中新建任务，粘贴后的中文都变成一长串数字了，下载后都不知道下载的是哪个

**Comment by ubuntuwbw** [comment]
不光中文，英文也一样，文件名都变成英文+数字了，类似UUID的东西

**Comment by acgotaku** [comment]
因为下载链接里面并没有包含文件名啊  所以文件名是错的也没有办法。。。
