### ISSUE TITLE
Firefox版添加任务失败

### ISSUE THREAD

**Issue by syazyz** [acgotaku/BaiduExporter#35]
我是把Aria2部署在路由器上的，没有设置账户密码和secret-token。用YAAW设置JSON-RPC Path为http://路由器IP:6800/jsonrpc可以正常监视和添加/删除任务。但是同样的方式设置在您写的插件上就不行了，一直提示“错误,请查看是否开启Aria2”。用http://hostname:port/jsonrpc?jsoncallback=1命令结果返回的是以下信息：
1({"id":null,"jsonrpc":"2.0","error":{"code":-32600,"message":"Invalid Request."}})

请问一下这是否因为路由器设置了登录账户的原因呢？我试着用http://username:password@路由器IP:6800/jsonrpc似乎也不行。

插件设置如下图所示：
![qq 20150220210653](https://cloud.githubusercontent.com/assets/11090567/6286620/80ab5630-b944-11e4-943f-05c609e5b007.png)

**Comment by syazyz** [comment]
找到原因了，是因为Noscript的XSS防护的问题，它禁止一切来自外部页面的对内网的Http访问请求，关掉就好。但是又有新问题了，每次设好Aria2 RPC之后只要一关掉Firefox就重新恢复默认的http://localhost:6800/jsonrpc，这样就会使得脚本失效。请问有锁定它的办法吗？

**Comment by acgotaku** [comment]
@syazyz 我在自己电脑上测试Firefox没有任何问题 请问你的版本是？

**Comment by syazyz** [comment]
版本是pcxfirefox x86 35.0.1。问题已经解决了……是我的Cookie策略限制太严的结果。
顺问下大大有没有类似script能够直接发送普通链接到Aria2的RPC监听口去的？

**Comment by acgotaku** [comment]
@syazyz  你是跑服务器上的啊。。这么小心翼翼啊 直接发普通链接的话 可以用

YAAW的界面添加啊

**Comment by syazyz** [comment]
主要是图方便，因为远程访问的时候复制链接——粘贴到YAAW上也有点慢的，能够直接从浏览器就完成这点就更好了。总之谢谢大大的script了，设置好了确实很方便

**Comment by acgotaku** [comment]
@syazyz 这个的话 我下次看看可不可以加上这个功能

**Comment by syazyz** [comment]
好，那我就静候佳音了

**Comment by acgotaku** [comment]
@syazyz 想了想这个功能得要所有网站的权限 目前暂时不添加 后续可能会写个新扩展
