### ISSUE TITLE
请问如何设置不保存百度云的目录？

### ISSUE THREAD

**Issue by sfrx520** [acgotaku/BaiduExporter#352]
之前版本的网盘助手，在百度盘的文件夹下，用aria2导出下载后，本地无文件夹，只下载文件。

新版本会同步创建百度云的文件夹。请问如何设置不同步文件夹？

因我所使用的aria2版本因为有目录权限的问题，aria2下载后的目录必须设置一次777，samba才可以删除。

谢谢！

**Comment by acgotaku** [comment]
那你就点进文件夹 选文件 就不带路径了。。。

**Comment by sfrx520** [comment]
选文件下载，下载到本地后，本地aria2的下载目录里就是跟百度云一样的目录路径了。

**Comment by lautis0503** [comment]
@acgotaku 以前的版本确实不带，最近更新后怎么点都带路径了

**Comment by ximellon** [comment]
因为自己网盘下的 API 改了，最近也一直出现这问题，昨天研究了下 code 。
`    function getSelected() {
        var path = getHashParameter("list/path");`
改成 getHashParameter("path") 就 OK 了。
