### ISSUE TITLE
火狐50.0beta提示“网络请求失败”

### ISSUE THREAD

**Issue by yulelong** [acgotaku/BaiduExporter#353]
好像是从beta8开始就这样的了，现在beta10还是这样的。
退回到了49.0.2就正常使用，是因为火狐又在程序上做了什么改动吗？有办法解决没？

**Comment by acgotaku** [comment]
火狐只是兼容而已。。。没那么多精力啊。。

**Comment by yulelong** [comment]
@acgotaku 了解了。。那暂时不更新火狐了。。

**Comment by TurnOffNOD** [comment]
@acgotaku 那么chrome是一直在更新兼容最新版吗？
