### ISSUE TITLE
The main download button "ARIA2 RPC" does not work

### ISSUE THREAD

**Issue by kitce** [acgotaku/BaiduExporter#354]
My browser engine is Chromium 53.0.2785.143

It says "正在获取下载地址..." but never succeeds.

Now I just save the download links as `aria2c.down` and download in command line, which is quite inconvenient.

Any solution?

**Comment by acgotaku** [comment]
Maybe this is your problem. Please press F12 and look console panel.

**Comment by HerringtonDarkholme** [comment]
Close due to inactivity

**Comment by kitce** [comment]
Finally found what's wrong. My `rpc-secret` had special characters.

In short, the RPC url cannot contain special characters if you want to use this plugin.
