### ISSUE TITLE
百度云目录嵌套多时下载失败

### ISSUE THREAD

**Issue by roycex** [acgotaku/BaiduExporter#356]
如果父目录下面有多级子目录，或者子目录内文件过多时，直接下载父目录在解析完目录结构和文件列表后会失败，提示“网络请求失败”， 只能在父目录下分批下载部分子目录或文件

**Comment by roycex** [comment]
补充一下，如果一次性选择文件超过300个会”网络请求失败”，导致无法下载

**Comment by t1mch0w** [comment]
遇到同样的问题 文件数多会报错 "网络请求失败"

**Comment by acgotaku** [comment]
请提供可测试的 分享文件。。。

**Comment by t1mch0w** [comment]
多级目录问题: https://pan.baidu.com/s/1cqrKMq

**Comment by t1mch0w** [comment]
我下载的文件都是照片 不好公开 但是文件个数超过300 就会报错 "网络请求失败"

**Comment by HerringtonDarkholme** [comment]
Close due to inactivity.
