### ISSUE TITLE
公司网络怎么在conf加入代理网络代码？

### ISSUE THREAD

**Issue by caleyzhang** [acgotaku/BaiduExporter#357]
我现在是拷贝你的conf，,但公司是代理网络没有办法下载，怎么在conf 加入代理网络代码？ 公司用的ccproxy代理软件，请指导，谢谢！

**Comment by tofuliang** [comment]
这个应该自行阅读aria2的使用手册.

2016-11-01 9:09 GMT+08:00, caleyzhang <notifications@github.com>:

**Comment by acgotaku** [comment]
自己去读  https://aria2.github.io/manual/en/html/aria2c.html

**Comment by caleyzhang** [comment]
我是小白，不会用命令呀！自己搞了半天，不是不能启动，就是启动了下载不了，求指导

**Comment by acgotaku** [comment]
@caleyzhang  --all-proxy=<PROXY>  使用这个参数  

自己要学会学习  没有人会喂饭给你吃的
