### ISSUE TITLE
OSX下的可行方案？

### ISSUE THREAD

**Issue by tt171g** [acgotaku/BaiduExporter#358]
OSX不可以更改组策略，所以作者提供的chrome pack ext行不通……
Safari的插件似乎也无效了，请问还有什么办法能在OSX下使用aria2下载百度云资源的方法吗？
直接用网页下载速度只有50k……下了两天的碟子一解压还是碎的otz

**Comment by acgotaku** [comment]
开发者模式载入是万能的 否则开发者怎么调试。。。

**Comment by acgotaku** [comment]
好好读读 这个 https://github.com/acgotaku/BaiduExporter/issues/277
