### ISSUE TITLE
最近经常会出现下载终端的情况

### ISSUE THREAD

**Issue by lingbaoboy** [acgotaku/BaiduExporter#359]
最近经常会出现下载中断的情况
就是下载到一半会停止下载
下载任务跑到“其他任务”中了

**Comment by Aidea** [comment]
就是下载失败的问题，我也经常遇到，不知道是因为文件大还是网速的原因！
另外，最近用Aria2下载也限速了？

**Comment by lingbaoboy** [comment]
**就是下载失败的问题，我也经常遇到**

**Comment by donglin2000** [comment]
我也经常碰到，原因大概是因为速度被限速，下载时间太长而引起失败。可以通过restart重新开始，如果不行就要重新导出下载，也可以续传。

**Comment by joyfun** [comment]
应该是baidu 的问题  限速很明显 500k 然后没一会就降到了100k左右 不到十分钟就断了  
看来得重新抓客户端的包了

**Comment by HerringtonDarkholme** [comment]
Close due to informative inactivity
