### ISSUE TITLE
求多个RPC地址支持

### ISSUE THREAD

**Issue by tofuliang** [acgotaku/BaiduExporter#36]
考虑到我公司一台电脑,家里一台NAS,宿舍一台路由器脱机,到处摆的nexus 7,都会用到aria2这神奇,能否想YAAW那样,在RPC地址框那里做成一个下拉列表的形式呢?

**Comment by acgotaku** [comment]
@tofuliang 可以考虑 但是最近比较忙 给我点时间 ==

**Comment by acgotaku** [comment]
@tofuliang Chrome已经率先更新了

**Comment by tofuliang** [comment]
@acgotaku 使用中！感谢！

**Comment by acgotaku** [comment]
@tofuliang  https://github.com/acgotaku/BaiduExporter/issues/37

现在是添加了多个RPC功能，这样应该会比下拉列表切换更方便吧？

我觉得这俩功能有点重复 准备只保留其中一个。
