### ISSUE TITLE
新版的分享界面没有 导出下载 选项

### ISSUE THREAD

**Issue by starriv** [acgotaku/BaiduExporter#360]
可能因为最近的更新导致的，不过在自己的文件中还可以用。

**Comment by Explorare** [comment]
插件版本？

**Comment by starriv** [comment]
Last Release v0.8.5
Chrome 版本 54.0.2840.71 (64-bit)

**Comment by Explorare** [comment]
Please update to v0.8.7 with the following guide.
https://hencolle.com/2016/10/16/baidu_exporter/
