### ISSUE TITLE
能解决下chrome浏览器每次启动时的提示吗？

### ISSUE THREAD

**Issue by since2004** [acgotaku/BaiduExporter#362]
每次提示 请关闭非开发者模式插件 ，真的是相当的不爽啊

**Comment by atempcode1** [comment]
能花点时间看看readme吗？

**Comment by since2004** [comment]
嗯。正在看了，全是英文，看着有些吃力

**Comment by since2004** [comment]
大神，win版本的我看明白自私取消提示了，mac版本的不太明白，能否详细指导下？

**Comment by acgotaku** [comment]
mac我也没有经验 买不起

**Comment by AquaHacker** [comment]
每次提示就提示呗，要求也太多了，这超出作者写插件的应用范围了。也不是插件的问题。

**Comment by HerringtonDarkholme** [comment]
Hi, 这是google chrome的特性，插件作者不可控

https://hencolle.com/2016/10/16/baidu_exporter/ 已有全部解释。
