### ISSUE TITLE
下载总是失败,提示403

### ISSUE THREAD

**Issue by liaobin** [acgotaku/BaiduExporter#363]
用的是最新0.8.8的扩展

11/08 12:01:32 [ERROR] CUID#184 - Download aborted. URI=https://d.pcs.baidu.com/file/0620e5c7e1e27e9e64197179b937044d?fid=1479915000-250528-678771983691211&time=1478577698&rt=pr&sign=FDTAERVCY-DCb740ccc5511e5e8fedcff06b081203-HpWEv49fME71Z2yC2LAbLZmb%2B%2Bw%3D&expires=8h&chkv=1&chkbd=1&chkpc=et&dp-logid=7247783741137543657&dp-callid=0&r=456148030
Exception: [AbstractCommand.cc:350] errorCode=22 URI=https://d.pcs.baidu.com/file/0620e5c7e1e27e9e64197179b937044d?fid=1479915000-250528-678771983691211&time=1478577698&rt=pr&sign=FDTAERVCY-DCb740ccc5511e5e8fedcff06b081203-HpWEv49fME71Z2yC2LAbLZmb%2B%2Bw%3D&expires=8h&chkv=1&chkbd=1&chkpc=et&dp-logid=7247783741137543657&dp-callid=0&r=456148030
  -> [HttpSkipResponseCommand.cc:239] errorCode=22 The response status is not successful. status=403

**Comment by kashu** [comment]
我这下载速度大概在 200-300KB/s 左右徘徊

你们的下载速度怎么样？快不？

**Comment by HerringtonDarkholme** [comment]
Please provide reproduciton.

**Comment by liaobin** [comment]
和https://github.com/acgotaku/BaiduExporter/issues/109一样

**Comment by prozyy** [comment]
下载速度慢可以通过调整aria2的最大线程数来提高下载速度，百度下载非会员对单个下载线程有限速
max-connection-per-server=16
split=20

**Comment by bravepetrelc** [comment]
出现跟楼主一样的情况

**Comment by bp0qd** [comment]
出现了 errorCode = 1 Got EOF from the server的错误。线程从10个慢慢降到1个了。

**Comment by Explorare** [comment]
错误表现是什么呢？我最近在下载 GnP 的专辑时发现体积大的下载项目会在中途自动断开，和速度无关，和时间有关，断开时间大概在 10min 左右，换 UA 也不行，换 IP 也不行。重新导入项目可继续下载，一定时间内没下载完又会断掉。

**Comment by bravepetrelc** [comment]
@Explorare 我下载不管下载什么基本上两分钟内都会断开，重新导入后两分钟后又断开，错误提示如下：
`[ERROR] CUID#15 - Download aborted. URI=http://d.pcs.baidu.com/file/06e6......`
`Exception: [AbstractCommand.cc:351] errorCode=22 URI=http://d.pcs.baidu.com/file/06e6.......`
 ` -> [HttpSkipResponseCommand.cc:239] errorCode=22 The response status is not successful. status=403`

**Comment by Explorare** [comment]
@bravepetrelc 我在记录中也找到了大量的类似错误，最早追溯到 2016-05-10.

**Comment by edwardiitii** [comment]
我也是，從昨天開始巳經這樣了

 `11/12 21:24:24 [ERROR] CUID#6 - Download aborted. URI=https://d.pcs.baidu.com/file/0b2508c5f784fcf398ad433f549ee972?fid=1580340762-250528-72826354526194&time=1478957044&rt=pr&sign=FDTAERVC-DCb740ccc5511e5e8fedcff06b081203-7dMLXdI9rboXf1VjkDCQ7r0f7J4%3D&expires=8h&chkv=1&chkbd=1&chkpc=&dp-logid=7349613665629233692&dp-callid=0&r=912171313
Exception: [AbstractCommand.cc:350] errorCode=1 URI=https://d.pcs.baidu.com/file/0b2508c5f784fcf398ad433f549ee972?fid=1580340762-250528-72826354526194&time=1478957044&rt=pr&sign=FDTAERVC-DCb740ccc5511e5e8fedcff06b081203-7dMLXdI9rboXf1VjkDCQ7r0f7J4%3D&expires=8h&chkv=1&chkbd=1&chkpc=&dp-logid=7349613665629233692&dp-callid=0&r=912171313
  -> [SocketCore.cc:875] errorCode=1 SSL/TLS handshake failure: unable to get local issuer certificate

11/12 21:24:24 [NOTICE] Download GID#6c611e212fec1844 not complete: /root/Murder,SheWrote女作家与谋杀案S03E13.译制组.abc

Download Results:
gid   |stat|avg speed  |path/URI
======+====+===========+=======================================================
6c611e|ERR |       0B/s|/root/Murder,SheWrote女作家与谋杀案S03E13.译制组.abc

Status Legend:
(ERR):error occurred.

aria2 will resume download if the transfer is restarted.
If there are any errors, then see the log file. See '-l' option in help/man page for details.`

**Comment by acgotaku** [comment]
我这边 速度都是1m/s 并且偶尔断开  但是重新导入就是了。。。

**Comment by Explorare** [comment]
@acgotaku 然而挂机下载的就遭殃了，早上起来一看发现任务全中断了 ( ´_ゝ`)

**Comment by acgotaku** [comment]
https://github.com/sunzhaoyang/BaiduAria2Resume

有人已经实现了这个

https://github.com/acgotaku/BaiduExporter/issues/80

**Comment by Explorare** [comment]
@acgotaku 感谢

**Comment by Explorare** [comment]
@acgotaku 似乎不支持 token 啊。

**Comment by acgotaku** [comment]
@Explorare 那只能请求原作者更新了。。。 这个我也无能为力。。。

**Comment by akska** [comment]
抱歉打擾一下 上面那堆錯誤 是因為baidu連結過期了所以error還是說aria2設定上有問題才出現的問題哦?
因為早幾個月一直在用都沒有出錯然後在某次baidu弄的aria2死機後便有這類報錯了.
程式碼什麼的真的不懂抱歉打擾了

**Comment by acgotaku** [comment]
出现错误 重新导入就好了  @akska

**Comment by acgotaku** [comment]
出现 错误 请先检查下自己启动 aria2c的配置 

我有提供 配置文件 https://github.com/acgotaku/BaiduExporter/blob/master/aria2c/aria2.conf

使用这个配置 还是出问题的话 再来提问 

80%的问题都是自己 aria2c的配置问题

**Comment by miaulightouch** [comment]
以下個人猜想

單用戶非高級會員應該會有一段期間內的流量限制，例如：一週 5GB
接著過量就會限制為單線程 10kb/s，所以增加線程的確有幫助。

至少剛才新建任務時，速度至少都有 1MB/s，直到幾個檔完成之後，速度才有降低的現象。
