### ISSUE TITLE
百度云下载限速

### ISSUE THREAD

**Issue by biu0w0** [acgotaku/BaiduExporter#365]
macOS Sierra 最新版本
Chrome Dev 56 最新版本
Git Pull & Checkout 最新版本

原来百度云Export到aria2c特别霸气不会限速，现在无论任何资源，导出下载均只有200KB/s，甚至频繁出现速度掉到0KB/s。

网速是千兆，应该和网络没关系，DNS试过多个（114DNS/腾讯DNS/阿里DNS）。

请问现在的版本是否能绕过百度云下载限速？还是只是我个例。

**Comment by Explorare** [comment]
这是两个问题，一个是速度限制，这个可以通过更改 aria2c 的 User Agent 解决。另一个是下载中断，还没找到可用的解决办法。

**Comment by sishuiliunian** [comment]
@Explorare 求新的useragent 速度很慢啊

**Comment by Explorare** [comment]
`netdisk;Chrome Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.87 Safari/537.36`
这个是我正在用的 UA，速度能达到 12Mbps，我的上行带宽上限。

**Comment by sishuiliunian** [comment]
我这里网络可能不行 最多500k左右

**Comment by Explorare** [comment]
多开几个线程？

**Comment by sishuiliunian** [comment]
能不能贴一下 你的配置文件

**Comment by Explorare** [comment]
配置分为两部分，一部分是 aria2 的，一部分是 BaiduExporter 的。
./aria2.conf
```
split=10
user-agent=netdisk;Chrome Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.87 Safari/537.36
```
第一行设定单文件下载线程为 10，第二行设定默认 UA。

BaiduExporter
```
UA: netdisk;5.3.4.5;PC;PC-Windows;5.1.2600;WindowsBaiduYunGuanJia
```
这里是默认的 UA，不需要改变。

更新配置后记得重载 aria2

**Comment by biu0w0** [comment]
这个好迷，我设置的也是10线程，也试了你的UA，仍然不会超过1MB/s。

**Comment by Explorare** [comment]
你确定 UA 生效了么？开 YAAW 或者 AiraNg 看一下配置。

**Comment by biu0w0** [comment]
生效了呀，YAAW显示也是新的了。

现在解决方案是淘宝买1小时会员，登客户端(26MB/s)，抓包下载地址，再丢入Aria2，就可以60MB/s了。

**Comment by Explorare** [comment]
那不如研究一下抓到的包的 UA 和 header，说不定有什么收获。

**Comment by sishuiliunian** [comment]
我的同时打开百度云客户端 速度就上来了

**Comment by sishuiliunian** [comment]
@Explorare @biu0w0

**Comment by Explorare** [comment]
@sishuiliunian 我就是不想装百度云才用这玩意的 ( ´_ゝ`)

**Comment by sishuiliunian** [comment]
两个一起下载 更快  不想研究的办法

**Comment by acgotaku** [comment]
我的默认 UA一直都很快。。。 这个问题说了很多遍了。。。

插件只保证能下载 无法保证速度 我没有限速的条件进行调试。。。

**Comment by Explorare** [comment]
@acgotaku 尝试了一下发现似乎不支持 token，尴尬不已。

**Comment by biu0w0** [comment]
@Explorare 支持token
http://token:xxxxx@localhost:6800/jsonrpc
conf里要设置：
`rpc-allow-origin-all=true`

**Comment by ocean521** [comment]
@Explorare  配置新UA,是需要在Aria.CONF中新增
user-agent=netdisk;Chrome Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.87 Safari/537.36（原来的conf中没有配置），然后在BaiduExporter插件中配置默认
UA: netdisk;5.3.4.5;PC;PC-Windows;5.1.2600;WindowsBaiduYunGuanJia。是这么理解么？

**Comment by Explorare** [comment]
@ocean521 是的

**Comment by ocean521** [comment]
感谢！

**Comment by ocean521** [comment]
优先级是如何呢，我记得作者好像说过一次，BaiduExporter插件的优先级是高于conf 的

**Comment by Explorare** [comment]
@ocean521 嗯，确实是这样。因为是通过 RPC 调用 Aria2c 的，参数会被重写吧。

**Comment by biu0w0** [comment]
@Explorare @ocean521 UA可以在运行时改变，所以插件优先

**Comment by 494895913** [comment]
@ocean521 请问下 BaiduExporter插件中配置文件 是哪个文件

**Comment by Explorare** [comment]
@494895913 
![image](https://cloud.githubusercontent.com/assets/5090766/20453400/7a6bc85c-ae5e-11e6-805c-2acd7b81fa49.png)

**Comment by gkaigk** [comment]
试试更换百度云 的账户，或者退出百度云，重新下载。
会有惊喜的，百度云最近是账号限速。
