### ISSUE TITLE
可否提供打包好的xpi？

### ISSUE THREAD

**Issue by fnscar** [acgotaku/BaiduExporter#366]
firefox中添加临时附加组件倒是可以用，不过重启firefox后又需要重新加载此“临时附加组件”，极为不便。
有第三方编译版的firefox似乎不强制验证签名，只要有xpi就可正常使用，故此请求。

**Comment by acgotaku** [comment]
似乎？？ 你确定？

**Comment by fnscar** [comment]
pcxfirefox x64
Compatible Changes different from Official Edition
1) Remove the plugin restriction in x64 edition ( back out Bug 1165981 )

**Comment by acgotaku** [comment]
加了

**Comment by Cye3s** [comment]
新下的xpi在45 esr上不能安装
xpi中好像少了install.rdf和chrome.manifest
是不是要支持WebExtensions的开发版？

**Comment by acgotaku** [comment]
版本至少是  48以上 @Cye3s

**Comment by fnscar** [comment]
在我日常使用的pcxfirefox45.0.2中显示“该附加组件无法安装，因为它似乎已损坏“。
在pcxfirefox和官方版48.0.2、49.0.2中则完全没有反应。

**Comment by firstuanl** [comment]
你好，xpi在哪里，没找到，
chrome商店上又没有，不能转

**Comment by acgotaku** [comment]
@firstuanl 现在不提供 XPI了

**Comment by firstuanl** [comment]
@acgotaku 

chrome 文件夹重命名为 {59f15a1c-8a61-4b60-b4f0-64eb531bcaa6} 形式，丢到 / extension 里 restart firefox,这样怎也不行了？

**Comment by acgotaku** [comment]
@fnscar 这种方式我也没说过行啊。。。。
