### ISSUE TITLE
proxy 问题

### ISSUE THREAD

**Issue by kenlo88** [acgotaku/BaiduExporter#367]
香港用户
d.pcs.baidu.com 连接到 hk02ntt01.baidupcs.com
但 dns 根本找不到 hk02ntt01
exception abstractcommand.cc:350 
errorcode=19

**Comment by adrianlaw666** [comment]
香港用戶 x2
原來不止我不能用
我也有相同問題
Chrome 54.0.2840.71 m (64-bit)
Aria2 1.28.0-win-64bit-build1
BaiduExporter 0.8.8

**Comment by acgotaku** [comment]
我不是香港用户。。。也没法解决啊。。。

**Comment by adrianlaw666** [comment]
因為我不太懂Program 這樣的Error有沒有可能是百度封鎖了香港的IP?
因為我用百度雲自家的軟件Download也只得5KB

**Comment by acgotaku** [comment]
估计是被屏蔽了吧
