### ISSUE TITLE
关于Mac Chrome每次开启禁用插件的问题

### ISSUE THREAD

**Issue by Eveninger** [acgotaku/BaiduExporter#368]
请确保以下几点：

1. 已经阅读过README
2. 尝试安装最新版本插件
3. 尝试清空浏览器缓存
4. 尝试卸载插件后重新安装

发起 Issue 时，请提供：

1. 您下载的内容地址
2. 插件版本号，浏览器版本号，系统版本号
3. 列举出现问题的详细步骤
4. 描述能否复现问题

----------

**不符合上述条件的Issue将被无理由关闭**
![image](https://cloud.githubusercontent.com/assets/12775863/20247283/65f640a0-aa03-11e6-8a6a-7c3bbf029063.png)
提示下载模板，但是并没有给下载地址啊？模板要在哪下载？

**Comment by acgotaku** [comment]
![screenshot from 2016-11-14 09-15-36](https://cloud.githubusercontent.com/assets/1191834/20250556/9e0aab1c-a9d5-11e6-8e18-af57e0e74433.png)

为啥不一样呢？？？ 你先检查下自己网络？

**Comment by Explorare** [comment]
模板代码托管在 gist 上，请挂代理访问谢谢。
