### ISSUE TITLE
HTTP response header was bad or unexpected - Aria2 WebUI

### ISSUE THREAD

**Issue by NPCHK** [acgotaku/BaiduExporter#369]
系統：Debian Jessie
Aria2 Version：1.18.8-1
WebUI：http://ziahamza.github.io/webui-aria2/

當使用命令模式時，下載正常。
但命令行模式使用上不太方便，所以直接用插件的「拷贝下载链接」。
然後把鏈接用於WebUI下載時，卻表示「HTTP response header was bad or unexpected」。
請問WebUI該如何設置呢？

**Comment by acgotaku** [comment]
拷贝没有 cookies  当然下载失败 不能RPC导入？

**Comment by goldmonkey163com** [comment]
昨天用RPC导入速度还挺快，今天我用IDM导出下载速度很快，用RPC导入速度很低
