### ISSUE TITLE
增加多个aria rpc导出选项

### ISSUE THREAD

**Issue by giveup** [acgotaku/BaiduExporter#37]
在笔记本上也安装了aria，下载的时候要修改127.0.0.1才能下载。略显麻烦，希望考虑增加多个aria rpc支持，谢谢！
PS：因为百度云客户端开始限速，浏览器另存为也很慢，一怒之下安装了aria，速度很快。。。
另外，拓展能不能考虑登陆firefox商店，第三方安装的拓展不能通过firefox同步。。
chrome商店是要收钱的都登陆了，mozilla应该不收费吧。。。

**Comment by acgotaku** [comment]
@giveup 什么叫多个支持？ 就是下拉菜单 Mozillla是人工审查代码 说我的不规范 ==
我懒得理他就没发布到商店。。。

**Comment by giveup** [comment]
![2015-03-16 11 12 31](https://cloud.githubusercontent.com/assets/2897585/6669226/bcc9b930-cc32-11e4-808c-94325a663a5d.png)
看图，希望的效果是有两个导出下载按钮，如导出下载到prc-1,导出下载到prc-2

**Comment by acgotaku** [comment]
@giveup 原来如此

**Comment by acgotaku** [comment]
@giveup 这个功能对代码整体架构需要修改 所以得需要点时间

**Comment by Paulreina** [comment]
新版本的好像下载后的文件名会有问题，会把百度文件夹的名字自动加到文件的最前面，如果下载多个文件，则会自动在下载目录新建百度里的同名文件夹。
是在自己的百度网盘中下载，非分享。

**Comment by acgotaku** [comment]
@Paulreina 这样不好么？ 只想裸文件夹下载的话 那就点进去文件夹下载啊

**Comment by giveup** [comment]
@acgotaku  @Paulreina it's a feature not a bug...我提出来的功能当成问题了...

**Comment by acgotaku** [comment]
@giveup 总有人有不同的嗜好啊 == 有人喜欢带文件夹的 但是有人不喜欢 但是这都是细节啊

我不可能都一一满足这些细节啊 ==

**Comment by giveup** [comment]
@chztv 导出时,是打包下载还是建立和百度云一样的目录结构,都是可选的,包括文件夹层级.
至于导出单个文件时,把文件夹名字添加到文件,这个可能确实是BUG,我目前firefox36+0.3版本插件,正常.
你可以汇报一下环境方便确定问题.

**Comment by chztv** [comment]
@giveup @acgotaku 我现在的环境是Chrome41(64位)+0.3.1版本插件，没有勾选“文件夹打包”，文件夹结构层数默认值“0”，基本上我都没设置，都是默认值。Aria2的版本是1.16.5

**Comment by acgotaku** [comment]
@chztv 这个BUG我看到了  回去修复

**Comment by acgotaku** [comment]
@giveup  多RPC支持以及更新了chrome的。先试用体验下吧

**Comment by acgotaku** [comment]
@giveup 多RPC支持已经率先支持Chrome，先体验下吧

**Comment by JimmyX59** [comment]
你好～感謝你開發這插件
之前的版本使用上一直正常
但更新為0.3.3版後
一直下載失敗，設定未變動過
原先設定也只設定PRC路徑而已
環境為Chrome(32位)

**Comment by acgotaku** [comment]
@JimmyX59 因为更新的东西较多 可以先重置之后重新配置 你的RPC地址是多少？是否有验证机制？

**Comment by JimmyX59** [comment]
＠acgotaku GitHub可以私訊嗎？ 因為我沒有設驗證 RPC地址不敢POST在公開場合
不過我確定RPC地址是沒問題的，因為同時使用你開發的115插件是可以成功下載的

**Comment by pawapuro66** [comment]
@acgotaku 我也像@JimmyX59一样的情况，装回0.3.0版都是可以下载的，0.3.3就一直失败。运行环境是Chrome32位，PRC没有验证，aria2是1.14.2版，重置过再设置情况一样。预谢顺利解决！

**Comment by acgotaku** [comment]
@JimmyX59 @pawapuro66 可以在Chrome里面百度网盘点击F12按钮 看看Console页面有什么错误输出 然后贴出来

**Comment by acgotaku** [comment]
@pawapuro66 现在更新到 0.3.4了 应该没啥问题了

**Comment by pawapuro66** [comment]
@acgotaku 更新0.3.4之后就正常了，非常感谢！！
