### ISSUE TITLE
下载失败

### ISSUE THREAD

**Issue by ocean521** [acgotaku/BaiduExporter#370]
是百度又更新了么，无法下载，显示ARIA2已经连接成功（Successfully connected to Aria2 through its remote RPC），但是点击Aria2 RPC后，并没有下载，下载失败。
插件版本为Version:0.8.8，ARIA2版本为： 1.25.0，chrom版本 53.0.2785.143 m

**Comment by ocean521** [comment]
之前是下载速度慢，尝试了一下在配置文件中增加UA,不知道是不是这个原因。不过已经把CONF中的UA删掉了啊，还是不行，目前115使用正常。

**Comment by welsen1982** [comment]
<img width="922" alt="2016-11-22 11 20 19" src="https://cloud.githubusercontent.com/assets/406716/20509745/d497050a-b0a5-11e6-8f9b-7bd2ef2923f6.png">

插件版本为Version:0.8.8，ARIA2版本为： 1.25.0  chrom版本： 53.0.2785.116 (64-bit)  mac下的

**Comment by jinfeng1985** [comment]
我也不行

**Comment by acgotaku** [comment]
亲测 可以使用。。。 估计是帐号的问题？

**Comment by ocean521** [comment]
如何能导出代码？请您看看？

**Comment by acgotaku** [comment]
你导出成文本 贴出来

**Comment by ocean521** [comment]
比较小白，怎么导出啊

**Comment by acgotaku** [comment]
到处下载按钮的第二个选项 可以导出成文本啊

**Comment by ocean521** [comment]
https://d.pcs.baidu.com/file/5218589b775464ad10f49a65bc7ab607?fid=4144894096-250528-705815141795542&time=1480157148&rt=pr&sign=FDTAERVCY-DCb740ccc5511e5e8fedcff06b081203-YxleQb8Pmm%2F2n%2B42Gx0ADcl%2Fg6s%3D&expires=8h&chkv=1&chkbd=1&chkpc=et&dp-logid=7671764184342505868&dp-callid=0&r=429095743

**Comment by ocean521** [comment]
https://d.pcs.baidu.com/file/5218589b775464ad10f49a65bc7ab607?fid=4144894096-250528-705815141795542&time=1480157148&rt=pr&sign=FDTAERVCY-DCb740ccc5511e5e8fedcff06b081203-YxleQb8Pmm%2F2n%2B42Gx0ADcl%2Fg6s%3D&expires=8h&chkv=1&chkbd=1&chkpc=et&dp-logid=7671764184342505868&dp-callid=0&r=429095743

**Comment by ocean521** [comment]
aria2c -c -s10 -k1M -x10 --enable-rpc=false -o "Mad.Max.4.Fury.Road.2015.BluRay.720p.x264.AC3-CMCT.mkv1" --header "User-Agent: netdisk;5.3.4.5;PC;PC-Windows;5.1.2600;WindowsBaiduYunGuanJia" --header "Referer: http://pan.baidu.com/disk/home" --header "Cookie: BDUSS=W83bnRIZldJeUNYMXB2LVI5MDZjWUtldXlnWTE0aG5JNUxIb05Oekdxckt1ejlZSVFBQUFBJCQAAAAAAAAAAAEAAABe908Kb2NlYW4yNTg1MjEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMouGFjKLhhYM;pcsett=1480243485-f44183bae358ec2a6e55a4824ff43e11" "https://d.pcs.baidu.com/file/5218589b775464ad10f49a65bc7ab607?fid=4144894096-250528-705815141795542&time=1480157148&rt=pr&sign=FDTAERVCY-DCb740ccc5511e5e8fedcff06b081203-YxleQb8Pmm%2F2n%2B42Gx0ADcl%2Fg6s%3D&expires=8h&chkv=1&chkbd=1&chkpc=et&dp-logid=7671764184342505868&dp-callid=0&r=429095743"

**Comment by ocean521** [comment]
aria2c -c -s10 -k1M -x10 --enable-rpc=false -o "Mad.Max.4.Fury.Road.2015.BluRay.720p.x264.AC3-CMCT.mkv1" --header "User-Agent: netdisk;5.3.4.5;PC;PC-Windows;5.1.2600;WindowsBaiduYunGuanJia" --header "Referer: http://pan.baidu.com/disk/home" --header "Cookie: BDUSS=W83bnRIZldJeUNYMXB2LVI5MDZjWUtldXlnWTE0aG5JNUxIb05Oekdxckt1ejlZSVFBQUFBJCQAAAAAAAAAAAEAAABe908Kb2NlYW4yNTg1MjEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMouGFjKLhhYM;pcsett=1480243485-f44183bae358ec2a6e55a4824ff43e11" "https://d.pcs.baidu.com/file/5218589b775464ad10f49a65bc7ab607?fid=4144894096-250528-705815141795542&time=1480157148&rt=pr&sign=FDTAERVCY-DCb740ccc5511e5e8fedcff06b081203-YxleQb8Pmm%2F2n%2B42Gx0ADcl%2Fg6s%3D&expires=8h&chkv=1&chkbd=1&chkpc=et&dp-logid=7671764184342505868&dp-callid=0&r=429095743"

**Comment by acgotaku** [comment]
你给我的链接 我放在终端里面是可以下载的  速度还挺快  你自己用就不行？

**Comment by ocean521** [comment]
对啊，不知道怎么贴图片,yaaw里面和aria2网页管理界面都是失败

**Comment by acgotaku** [comment]
你在终端里面下载试试？

**Comment by ocean521** [comment]
Yet Another Aria2 Web Frontend
Aria2 1.25.0
 0 KB/s /  0 KB/s
  Add
 Refresh
Active Tasks
No Active Tasks
Other Tasks
 Mad.Max.4.Fury.Road.2015.BluRay.720p.x264.AC3-CMCT.mkv1
 0 KB
0%
 [机械师2：复活].Mechanic.Resurrection.2016.BluRay.720p.x264.AC3-CMCT.mkv
 0 KB
0%
 机械师2：复活.jpg
 0 KB
0%
 [机械师2：复活].Mechanic.Resurrection.2016.BluRay.720p.x264.AC3-CMCT_s.jpg
 0 KB
0%
 机械师2：复活.txt
 0 KB
0%

**Comment by ocean521** [comment]
使用Aria2c Remote？还是IDM啊

**Comment by acgotaku** [comment]
aria2c的命令行模式啊

**Comment by ocean521** [comment]
我是一会计啊，完全靠百度研究出来的。老师还是按我是小白指导吧。是使用PUTTY连接NAS,然后敲aria2c -c -s10 -k1M -x10 --enable-rpc=false等等？

**Comment by acgotaku** [comment]
那你会用 Github也是不容易。。。 对 你的思路没问题

**Comment by ocean521** [comment]
11/26 19:11:37 [ERROR] CUID#7 - Download aborted. URI=https://d.pcs.baidu.com/file/5218589b775464ad10f49a65bc7ab607?fid=4144894096-250528-705815141795542&time=1480157148&rt=pr&sign=FDTAERVCY-DCb740ccc5511e5e8fedcff06b081203-YxleQb8Pmm%2F2n%2B42Gx0ADcl%2Fg6s%3D&expires=8h&chkv=1&chkbd=1&chkpc=et&dp-logid=7671764184342505868&dp-callid=0&r=429095743
Exception: [AbstractCommand.cc:350] errorCode=1 URI=https://d.pcs.baidu.com/file/5218589b775464ad10f49a65bc7ab607?fid=4144894096-250528-705815141795542&time=1480157148&rt=pr&sign=FDTAERVCY-DCb740ccc5511e5e8fedcff06b081203-YxleQb8Pmm%2F2n%2B42Gx0ADcl%2Fg6s%3D&expires=8h&chkv=1&chkbd=1&chkpc=et&dp-logid=7671764184342505868&dp-callid=0&r=429095743
  -> [SocketCore.cc:1015] errorCode=1 SSL/TLS handshake failure: unable to get local issuer certificate

11/26 19:11:37 [NOTICE] Download GID#b706e97ba0ded0c1 not complete: /root/Mad.Max.4.Fury.Road.2015.BluRay.720p.x264.AC3-CMCT.mkv1

Download Results:
gid   |stat|avg speed  |path/URI
======+====+===========+=======================================================
b706e9|ERR |       0B/s|/root/Mad.Max.4.Fury.Road.2015.BluRay.720p.x264.AC3-CMCT.mkv1

Status Legend:
(ERR):error occurred.

aria2 will resume download if the transfer is restarted.
If there are any errors, then see the log file. See '-l' option in help/man page for details.

**Comment by acgotaku** [comment]
你看看你的aria2c版本号 多少？

**Comment by ocean521** [comment]
1.25.0

**Comment by ocean521** [comment]
之前都没问题，就是速度在300K左右，现在就完全失败了

**Comment by acgotaku** [comment]
但是同样的链接 我这里没问题 我的是 1.28.0  每次导入都是失败？

**Comment by ocean521** [comment]
对。重来没有成功

**Comment by ocean521** [comment]
之前是1.14.2好像，我手欠给升级了，不过最好的是现在NAS重启，不用手动输入命令了，这点很激动

**Comment by ocean521** [comment]
使用Entware-ng 能升级到1.28.0不，我是11月刚升级的啊，又升了？

**Comment by acgotaku** [comment]
这个很尴尬 我没有你的网络环境 不好锁定原因

**Comment by acgotaku** [comment]
对了 你启动的配置文件里面有没有关掉证书校验？

#不进行证书校验
check-certificate=false

https://github.com/acgotaku/BaiduExporter/blob/master/aria2c/aria2.conf

**Comment by ocean521** [comment]
# Basic Options
dir=/share/CACHEDEV1_DATA/Download
input-file=/opt/var/aria2/session.dat
log=/opt/var/log/aria2.log
max-concurrent-downloads=5
check-integrity=true
continue=true

# HTTP/FTP/SFTP Options
max-connection-per-server=10
#min-split-size=10M
split=10

# BitTorrent/Metalink Options
bt-enable-lpd=true
bt-max-open-files=16
bt-max-peers=8
dht-file-path=/opt/var/aria2/dht.dat
dht-file-path6=/opt/var/aria2/dht6.dat
dht-listen-port=6801
#enable-dht6=true
listen-port=6801
max-overall-upload-limit=200K
#lowest-speed-limit=0
seed-ratio=1.0
seed-time=60

# RPC Options
enable-rpc=true
rpc-allow-origin-all=true
#rpc-certificate=/opt/var/aria2/aria2.pfx
rpc-listen-all=true
rpc-listen-port=6800
rpc-secret=******
#rpc-secure=true

# Advanced Options
daemon=true
disable-ipv6=true
disk-cache=32M
#enable-mmap=true
force-save=true
file-allocation=falloc
log-level=warn
max-overall-download-limit=0
max-download-limit=0
save-session=/opt/var/aria2/session.dat

**Comment by acgotaku** [comment]
@ocean521 你这不是没写 这个参数 么。。。  加上这个参数试试

**Comment by ocean521** [comment]
在哪个里面加呢？

**Comment by acgotaku** [comment]
在你配置文件里面加啊

**Comment by ocean521** [comment]
Basic Options？                HTTP/FTP/SFTP Options？

**Comment by acgotaku** [comment]
放在哪里不都是一样的么 你还纠结顺序啊。。。

**Comment by ocean521** [comment]
强迫症啊

**Comment by acgotaku** [comment]
大家的时间都很宝贵 你要强迫症 那就好好学学 把官方文档看完啊！ 
https://aria2.github.io/

放在第二个就好

**Comment by ocean521** [comment]
可以了，耽误楼主时间了，不好意思，再问最后一个问题，我这个CONF。不知道哪个设置的问题，下载完毕之后都保留AIRA文件，怎么调整

**Comment by acgotaku** [comment]
这个问题 你谷歌搜索下就知道了 不知道问了多少回了。。。  你要是有问题 就用我提供的CONF 我也不知道是怎么设置的

**Comment by ocean521** [comment]
好的。谢谢楼主
