### ISSUE TITLE
火狐无法导出下载链接

### ISSUE THREAD

**Issue by Misaka13645** [acgotaku/BaiduExporter#372]
火狐 50.0
插件版本 0.8.8
系统 OS X 10.12.1

在火狐下点击导出会显示 网络请求失败

**Comment by Misaka13645** [comment]
火狐50.0有这个问题, 退回旧版本以后又可以用里

**Comment by acgotaku** [comment]
那还是先用回旧版吧。。。 其他版本没有多大精力维护

**Comment by smartdj** [comment]
@Misaka13645 退回什么版本可用？我退回到火狐的49.0.2还是提示“网络请求失败”

**Comment by tontwen-lyn** [comment]
同。
FF 50.0.2
BaiduExporter 0.8.8 
OS X 10.12.1
整了半天附加组件不好使，没想到是浏览器的问题。现在暂时用Chrome版的，很不错，没问题，感谢！
最好能在README里说明一下，让其他人少走弯路。

**Comment by tywtyw2002** [comment]
@acgotaku 简单的debug了一下，目前发现是在ff 50下jquery的post无法使用造成的。

应该是ff block掉了$.post里面的call 从而导致了$.post抛出"SyntaxError: An invalid or illegal string was specified"

**Comment by acgotaku** [comment]
确实很诡异 不知道为啥会这样做

**Comment by acgotaku** [comment]
解决了 是同源的问题 

window.location.origin +

**Comment by Misaka13645** [comment]
@acgotaku 感谢作者
