### ISSUE TITLE
最新版0.88下载单文件不会保留完整路径了？

### ISSUE THREAD

**Issue by elicip** [acgotaku/BaiduExporter#373]
1. 下载内容：https://pan.baidu.com/s/1skJuntr
2. Mac系统10.12.1，chrome最新版浏览器，插件为0.88
3. 0.87版本下载时还会创建文件的相应目录，但是0.88版本不行了

![2016-11-24 3 29 53](https://cloud.githubusercontent.com/assets/8703880/20589976/ee77766a-b25a-11e6-8c58-bd314a78cd5f.png)
上面截图为0.87版本下载

![2016-11-24 3 35 11](https://cloud.githubusercontent.com/assets/8703880/20590044/9900b34e-b25b-11e6-8e2b-a386ee3dc34f.png)
上面截图为0.88版本下载

谢谢！

**Comment by acgotaku** [comment]
因为默认就不是全路径 你可以在插件的配置里面开启  设置成-1即可

**Comment by elicip** [comment]
![2016-11-24 10 07 09](https://cloud.githubusercontent.com/assets/8703880/20601210/6460a310-b292-11e6-9e79-5b53731b2855.png)

设置是-1的

**Comment by elicip** [comment]
我发现撤回这个更改就好了
https://github.com/acgotaku/BaiduExporter/commit/c49a3562bd195ea3eba8b40d3bfbdb9ac78c4e20#diff-70e0c6671b4dcb39f5bc49217ba909e9
把path改回list/path

**Comment by acgotaku** [comment]
更新了

**Comment by elicip** [comment]
已解决，多谢！
