### ISSUE TITLE
通过manifest.json实现自动更新

### ISSUE THREAD

**Issue by tofuliang** [acgotaku/BaiduExporter#375]
现在是订阅了这个项目的消息通知,每次都需要手动下载,安装.
如果能实现自动更新就好了,查了一下,的确有方法,,
[详见这里](http://serverfault.com/questions/354606/where-do-i-find-the-update-url-for-google-chrome-extensions)

**Comment by tofuliang** [comment]
[还有这里](https://developer.chrome.com/extensions/autoupdate#H2-2)

**Comment by acgotaku** [comment]
那你可以自己实现一个啊 我这源码都公开的
