### ISSUE TITLE
不知道是不是网盘助手不支持Websocket协议的aria2还是别的原因，设置一直不成功。

### ISSUE THREAD

**Issue by fzhw88** [acgotaku/BaiduExporter#377]
路由器固件里的aria2插件aria2版本是1.29.0,websocket协议，RPC地址ws://192.168.1.1:6800/jsonrpc，rpc-secre默认开启且无法关闭.

在这种情况下，百度网盘助手怎么都没法设置成功，尝试的地址有（假定rpc-secre为fzhw88）：
ws://192.168.1.1:6800/jsonrpc
ws://token:fzhw88@192.168.1.1:6800/jsonrpc
http://192.168.1.1:6800/jsonrpc
http://token:fzhw88@192.168.1.1:6800/jsonrpc
ws://fzhw88@192.168.1.1:6800/jsonrpc
http://fzhw88@192.168.1.1:6800/jsonrpc
（最后两个属于瞎蒙）

相同路由器状态下使用QQ旋风离线下载的aria2脚本（https://github.com/rhyzx/xuanfeng-userscript）则没有问题，配置方法见图：
![image](https://cloud.githubusercontent.com/assets/10646430/20867217/34128cf6-ba7a-11e6-9921-28824cd39f2f.png)

不知道我的问题出在哪儿？是插件不支持这种aria2的设置还是我自己设置错误？如果是不支持，能否考虑添加支持？如果是我设置错误，那请多多指教！

谢谢～

**Comment by acgotaku** [comment]
ws默认不支持
