### ISSUE TITLE
现在好像被百度和谐了

### ISSUE THREAD

**Issue by Ehend** [acgotaku/BaiduExporter#378]
通过rpc下载，链接很快就减少到0，初始速度也非常低了。。。所以想问问，谢谢

**Comment by acgotaku** [comment]
和谐了 就不用了 早就料到了

**Comment by bennyyip** [comment]
并没有和谐 , 刚刚试过速度正常.

**Comment by wxyzh** [comment]
刚试过，没速度了

**Comment by lautis0503** [comment]
我这里现在rpc满速，有时候会掉到200K/s上不去

**Comment by prozyy** [comment]
没有和谐，只是限速了，但任务最快1m/s

**Comment by goubo** [comment]
测试的确实和谐了，导出任务直接失败。

**Comment by liuchuangjun321** [comment]
请问现在还可以正常使用吗？

**Comment by prozyy** [comment]
可以导出下载啊，就是速度没以前快了，你们的都不能用了吗

**Comment by ouwenxxing** [comment]
可以用， 速度限制在100k per task。然后看了看超级会员有个极速下载权限。
大家不用想免费有极速了

**Comment by shoaly** [comment]
悲剧...我的crx一直用的google最后一版本...从昨天开始终于不行了, 速度之后50k 到80....
保证仅存的一线希望到github上来更新最新版...发现没有卵用...

**Comment by sequencer** [comment]
我在想是不是通过代理然后负载均衡可能会有更好的速度了？

**Comment by shoaly** [comment]
@sequencer 找到一个解决方案,  [这个tampermonkey](https://greasyfork.org/scripts/23635-%E7%99%BE%E5%BA%A6%E7%BD%91%E7%9B%98%E7%9B%B4%E6%8E%A5%E4%B8%8B%E8%BD%BD%E5%8A%A9%E6%89%8B/code/%E7%99%BE%E5%BA%A6%E7%BD%91%E7%9B%98%E7%9B%B4%E6%8E%A5%E4%B8%8B%E8%BD%BD%E5%8A%A9%E6%89%8B.user.js) 可以解析出多个不需要cookie的直链, 应该可以做到你说的 aria2c多源下载 

对于我个人而言, 有了直链之后, 直接放入迅雷顿时又跑满本地带宽了.

**Comment by daidaidaiyuanyi** [comment]
原来和谐了  我还以为是我个人问题

**Comment by YujiShen** [comment]
如果用cookie和header会直接返回406，用解析出的直链放到aria2里还可以下，虽然只有100K，也比我的Mac客户端快很多了。。。

**Comment by JasonQuu** [comment]
我这和@Ehend 一样，链接会依次aborted,知道链接为0的时候下载取消

**Comment by bbblucky** [comment]
貌似死了，现在我下载直接显示失败。

**Comment by akska** [comment]
感覺像是aria conf裡的任務連接數設定太多. 初速很快但是用了一會百度便會封掉你的ip. 所以連接再丟aria下載便會直接報錯404了

速度是很飄(0-100KB) ...... 倒是沒什麼所謂, 我只是不喜歡下載什麼管家才另外找方法下的(汗

**Comment by sail76** [comment]
最近一直都能正常使用，只是速度被百度限制了， 现在基本在100K左右， 有时只能稳定在50K

**Comment by shoaly** [comment]
100k 已经不叫正常使用了...要知道资源一般都是2个g...

**Comment by WongCM** [comment]
前几天还正常 今天突然就限速了

**Comment by mxyolande** [comment]
昨天还下了好多东西，刚才突然发现只有100k的速度，这怎么玩

**Comment by Ehend** [comment]
@JasonQuu 我估计是下载的东西过多过大，流量过大所以被封了，现在我用idm+tampermonkey 还是可以用，效果差不多，和原来用aria差不多，等下我再试试aria

**Comment by Conan1985** [comment]
之前一直好好的，从今天开始一直是显示“❌未知错误”。

**Comment by leoatchina** [comment]
@Ehend 能否说下你是怎么配置 的？我发现下载小文件还好（50m以下），文件一大，很快就没速度

**Comment by qianbinbin** [comment]
虽然我把连接数设置到最大16，但是aria2下载每个资源最多只有10个连接，每个连接就10KB/s，而且连接数还一直减少
从至少一个月之前就是这样了……

**Comment by dongdongdu** [comment]
现在大家是不是基本上速度都维持在100K/s 左右了啊？

开发者模式可以导出下载，但是速度被限制的死死的~ 从一开始500K~ 速降到400k，300k，然后100k，维持一会，0k，然后突然200k，速度不稳定…………

**Comment by dongdongdu** [comment]
<img width="332" alt="wx20170107-201927 2x" src="https://cloud.githubusercontent.com/assets/5832030/21741609/a0101854-d516-11e6-80a8-1e8c32f2eb81.png">

**Comment by Ldcr993519867** [comment]
昨天下载最高6个线程,其余全406错误,速度最多70kb/s=-=|||
但是今天似乎速度上来了,200kb+勉强能下

**Comment by shoaly** [comment]
别纠结了, 好像是由于没有vip的账号 即便是官方客户端也没有速度了.. 所以要么充值 要么忍

*---------------------------------------------------------------------------------*

*Xuli Xiao 肖旭立*Mobile: 18602309133 | QQ: 18295742
Email: shoalyxiao@gmail.com
重庆和信慧科技有限公司 | 重庆市栖霞路金茂时代12栋1012
九天友邦文化传媒有限责任公司 | 北京市朝阳区西坝河东里101-2
Website: www.hexinhui.cn

**Comment by ahjsrhj** [comment]
![2017-01-22 1 42 26](https://cloud.githubusercontent.com/assets/8666955/22180349/a4d6d394-e0a8-11e6-9372-94142126286e.png)
vip帐号的下载速度

**Comment by AurevoirXavier** [comment]
idm下载可以满速。。

**Comment by Cidge** [comment]
楼上，可是我IDM一直显示无权限

**Comment by acgotaku** [comment]
速度问题已解决 使用最新 0.9.0版本
