### ISSUE TITLE
最新版 谷歌浏览器 不支持非谷歌商店的插件了 相关链接:https://support.google.com/chrome/answer/2811969?visit_id=1-636172126936991286-740148964&p=ui_remove_non_cws_extensions&rd=1

### ISSUE THREAD

**Issue by Yoke123** [acgotaku/BaiduExporter#379]
请确保以下几点：

1. 已经阅读过README
2. 尝试安装最新版本插件
3. 尝试清空浏览器缓存
4. 尝试卸载插件后重新安装

发起 Issue 时，请提供：

1. 您下载的内容地址
2. 插件版本号，浏览器版本号，系统版本号
3. 列举出现问题的详细步骤
4. 描述能否复现问题

----------

**不符合上述条件的Issue将被无理由关闭**

**Comment by acgotaku** [comment]
不都说了 启用开发者模式么。。。

**Comment by brick713** [comment]
现在还能使用么？我这边开启了开发者模式，获取了链接但是aria2上没法下载。

**Comment by abszy** [comment]
我用开发者模式安装成功了0.8.8   但是打开pan.baidu.com根本不显示按钮啊

**Comment by acgotaku** [comment]
我用着还是好好的。。。
