### ISSUE TITLE
新版本(0.3.3)不支持旧版本的Aria2 1.15.1

### ISSUE THREAD

**Issue by LinusSong** [acgotaku/BaiduExporter#38]
本人路由器上安装的的是Aria2 1.15.1，PC上安装的是Aria2 1.18.1。
chrome自动更新0.3.3版本后，PC上的Aria2可以正常工作，但是将RPC地址指向路由器后，无法正常工作，点击“测试连接，成功显示版本号”这个按钮，返回“错误,请查看是否开启Aria2”。
从Release中下载0.3.0版本后重新安装，路由器一切正常。
故推测0.3.3版本可能不支持旧版本Aria2。
希望作者能够解决，谢谢！

**Comment by liuboemail** [comment]
我也遇到了相同的问题，望能帮忙解决。谢谢！

**Comment by k1n** [comment]
我路由器上安装的是1.18.5版本，点击“测试连接，成功显示版本号”这个按钮，返回“错误,请查看是否开启Aria2”

**Comment by acgotaku** [comment]
Usage
Recommend: Set --rpc-secret= if you are using aria2 1.18.4(or higher) with 'JSON-RPC PATH' like http://token:secret@hostname:port/jsonrpc

Set --rpc-user= --rpc-passwd= if you are using aria2 1.15.2(or higher) with 'JSON-RPC PATH' like http://username:passwd@hostname:port/jsonrpc

新版本修改了认证方式的使用，估计是这个问题吧？

@k1n @liuboemail @LinusSong

**Comment by LinusSong** [comment]
@acgotaku 0.3.3版本是一定要开啓rpc的密码认证吗？不能像之前那样不用密码直接使用吗？另外我的aria2版本号是1.15.1,低於Usage中的1.15.2的要求（而且由於路由器上运行着闭源软件，无法更换系统，而这个系统中aria2只有这个版本的）
以下是我运行aria2c的命令：
在0.3.0可以正常使用的：
>aria2c --event-poll=select --enable-rpc --rpc-listen-all=true --rpc-allow-origin-all --dir=/mnt/sda1/temp --file-allocation=none -c -D

这个命令可以通用与yaaw，xunleiexporter和您的baiduexporter，JSON-RPC Path为http://192.168.1.1:6800/jsonrpc

如果加上user和passwd的话：
>aria2c --event-poll=select --enable-rpc --rpc-listen-all=true --rpc-allow-origin-all --rpc-user=USER --rpc-passwd=PASSWD --dir=/mnt/sda1/temp --file-allocation=none -c -D

JSON-RPC Path设置为http://USER:PASSWD@192.168.1.1:6800/jsonrpc，0.3.3无法使用这个设置，yaaw，xunleiexporter也不行

**Comment by acgotaku** [comment]
@LinusSong 我的RPC路径规则就是参照YAAW设计的啊 所以YAAW能用的话 我的肯定也可以 不行的话 你打开F12看看Console里面有什么输出

**Comment by acgotaku** [comment]
@LinusSong 你的意思是加上用户名密码就不行了？ 但是无验证就可以？

**Comment by LinusSong** [comment]
@acgotaku 在0.3.0版本中，不加上用户名密码可以
在0.3.3.版本中，如果不加上用户名密码的话，点击"测试连接，成功显示版本号。"返回的是500错误
>OPTIONS http://192.168.1.1:6800/jsonrpc?tm=1427818495421 
home:1 XMLHttpRequest cannot load http://192.168.1.1:6800/jsonrpc?tm=1427818495421. Invalid HTTP status code 500

但是如果加上用户名密码，则会返回401错误。
>OPTIONS http://192.168.1.1:6800/jsonrpc?tm=1427818743213 
home:1 XMLHttpRequest cannot load http://192.168.1.1:6800/jsonrpc?tm=1427818743213. Invalid HTTP status code 401

但是正如我在五楼中所写的那样，用户名是USER，密码是PASSWD，无论是命令还是JSON-RPC Path都没有写错，不知为何返回401错误。

**Comment by LinusSong** [comment]
@acgotaku 另外还有一点，这是路由器上1.15.1版本独有的错误，我在PC上（Ubuntu 14.04）aria2版本是1.18.1,和路由器上使用完全相同的命令，JSON-RPC Path改为http://USER:PASSWD@127.0.0.1:6800/jsonrpc，
就会完全正常
可能是1.15.1版本独有的错误，所以也不必为了这个版本的密码认证而费心，希望您能够对新版本稍加恢复，使其在无密码的情况下可用即可，多谢

**Comment by acgotaku** [comment]
@LinusSong 加不加用户名密码是由你的后台的aria2c启动来决定的吧？前台只是对接而已，你启动参数没有密码 前台RPC PATH加了密码肯定不行的啊 我一直都是用的默认参数启动的 6800端口无认证方式 没有问题啊

**Comment by LinusSong** [comment]
@acgotaku 您没有明白我的意思，我当然不会忘记对aria2c命令加以修改。
如果是6800端口无认证方式，JSON-RPC Path设置为http://192.168.1.1:6800/jsonrpc，就会返回500错误。
如果在启动参数里加上 --rpc-user=USER --rpc-passwd=PASSWD，同时修改JSON-RPC Path设置为http://USER:PASSWD@192.168.1.1:6800/jsonrpc，就会返回401错误。
简单描述我的问题就是：之前0.3.0路由器用的好好的，现在更新后就不行了，所以希望您把这个扩展给改回来。

**Comment by acgotaku** [comment]
@LinusSong 问题是在我机器上无法复现这个BUG，我找不到原因所在。不知道该如何修复，如果你会使用Chrome的 F12查看 network 可以把那个请求 copy as cURL  贴出来 我看看

**Comment by LinusSong** [comment]
@acgotaku 这个是6800端口无认证方式，会返回500错误
![image of network](http://i.imgur.com/LmggaLc.png)
copy as cURL的结果：
>curl 'http://192.168.1.1:6800/jsonrpc?tm=1427854551797' -X OPTIONS -H 'Access-Control-Request-Method: POST' -H 'Origin: http://pan.baidu.com' -H 'Accept-Encoding: gzip, deflate, sdch' -H 'Accept-Language: en-US,en;q=0.8,zh-CN;q=0.6,zh;q=0.4,zh-TW;q=0.2' -H 'User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.101 Safari/537.36' -H 'Accept: */*' -H 'Referer: http://pan.baidu.com/disk/home' -H 'Connection: keep-alive' -H 'Access-Control-Request-Headers: authorization, content-type' --compressed

**Comment by acgotaku** [comment]
@LinusSong BUG已经找到 这就更新

**Comment by acgotaku** [comment]
@LinusSong BUG已经找到 这就更新 现在无认证的话肯定没问题

**Comment by acgotaku** [comment]
@LinusSong 1.15.1版本只能无认证方式使用，现在已经支持了。
@k1n @liuboemail 你们俩使用还出现问题么？
