### ISSUE TITLE
最新发现~批量下载无视限速.......

### ISSUE THREAD

**Issue by wszgrcy** [acgotaku/BaiduExporter#381]
某酷安上有人说的.结果果然如此.批量下载,哪怕源文件加空白文件夹,都会使速度达到1-2M/S,并且多个批量下载也不会导致速度降低.....大牛可以着手改进下,油猴上有个大文件直接下载的JS,我猜是不是把这个获取的地址的函数直接替换过去,就又可以复活了?

**Comment by 2ndMessiah** [comment]
说的没错 今天早上要下一个开发的toolchain 只有mac，死马当活马医吧。批量一下载，速度小伙伴们都惊呆了！但是单个文件下载还是100kb··

**Comment by 2ndMessiah** [comment]
我现在单个大文件下载用百度直链

**Comment by exxfzc** [comment]
选中两个以上的文件会发生错误，不能下载...

**Comment by nujabse** [comment]
尝试了一下，确实如此

**Comment by acgotaku** [comment]
但是批量下载会把所有文件都变成 zip格式

**Comment by wszgrcy** [comment]
错误也看脸....今天解压了一个用油猴大文件脚本下载批量包,弹出来有错误但是还是解压完了.....至少比10K党好一点,脸好一般不出错误

**Comment by reemshx** [comment]
大概从前天开始，度盘用网盘助手导入进aria2最高速只能处于150K/s，请问是最近度盘限速了吗，有什么办法可以解决不，我试了批量下载两个文件，可是单个文件的速度依旧只有150左右

**Comment by ArcherCX** [comment]
有两次大概晚上12点左右吧，反正挺晚了，发现下载的时候，速度限制在0.9M左右而不是100kb，不过没有具体测试过
