### ISSUE TITLE
出现"未知错误"是什么原因?

### ISSUE THREAD

**Issue by exxfzc** [acgotaku/BaiduExporter#382]
baiduexporter是最新的0.8.8版本,配合aria2gui,前两天还可以用的,今天选中多个文件下载时提示"未知错误",是什么原因的?
<img width="1280" alt="2016-12-28 12 24 34" src="https://cloud.githubusercontent.com/assets/23161815/21513950/a45900da-ccf9-11e6-945a-3a704b9d7131.png">

**Comment by dongdongdu** [comment]
图片亮了 😁😁

**Comment by bitqiu** [comment]
求分享 😄

**Comment by acgotaku** [comment]
你的文件本身就被屏蔽了吧  所以下载不下来 不信的话 可以点击播放 或手动下载试试

**Comment by Conan1985** [comment]
我也遇到了同样的问题。同样的版本

**Comment by acgotaku** [comment]
我的下载 还是好好的。。。

**Comment by exxfzc** [comment]
从别人里转过来的...果然被屏蔽了，悲剧
