### ISSUE TITLE
希望能有效解决限速问题，谢谢

### ISSUE THREAD

**Issue by xtronaltic** [acgotaku/BaiduExporter#383]
1. 您下载的内容地址：
**本页面**
2. 插件版本号，浏览器版本号，系统版本号：
**0.8.8，Chrome 55.0.2883.87 m (64-bit)，Win 7 SP1 64-bit（6.1，7601）**
3. 列举出现问题的详细步骤：
**百度网盘页面——需要下载的文件夹——插件导出下载——保存批量下载链接（.txt）——IDM导入txt——已反复测试，每个文件下载速度稳定制约在100 KB/S左右。（四个1G文件同时下载，以往速度在1MB/S左右）**
4. 描述能否复现问题
**基本最近，继其他百度网盘直链网站失效后，你的插件也出现了限速100 KB/S左右的情况**

**希望能有效解决限速问题，谢谢**

**Comment by acgotaku** [comment]
下载限速这个吧 如果是服务器端做了限制 基本上是无解的

我顶多只能再抓包看看

**Comment by xtronaltic** [comment]
谢谢你的回复，想再多问一个问题：

1，经常大批量下载，目前时间节点，有没有什么办法能解决百度网盘时效性问题。

2，经常大批量下载，非冷门资源，有时同时下载的同大小各文件速度差异很大，这是为什么

**Comment by acgotaku** [comment]
1. 百度不是我开发的 我也不知道它是怎么设计的啊 时效性问题未知
2. 速度差异与本地网络环境和 CDN关系很大，原因那也得问百度啊。。。

我只不过是耍了一个小花样把下载链接放在专业的下载器里面了而已，并没有什么高大上的地方。

**Comment by prozyy** [comment]
现在有个安卓手机的app，山寨云 导出的网盘直链复制到aria2下载不限速

**Comment by AnClark** [comment]
但是山寨客户端安全性不一定能保证啊。。。万一被盗号可怎么办

**Comment by conanwhf** [comment]
实在忍不住了……这里是github，开源是用来给大家共同改进的，不是给作者提意见和要求的！
限速、用不了什么的，可以报问题、讨论原因、自己动手修复上传，但作者没义务给你解决啊，说实话作者耐心够好的了

**Comment by acgotaku** [comment]
终于有人说了大实话了。。。

**Comment by jemyzhang** [comment]
@acgotaku 山寨云中, 如果使用他的nb.cache.baidupcs.com, 感觉速度特别快, 比pcs.dcdn.baidu.com要快很多. 能否在导出链接时,优先考虑nb.cache(如果存在的话)

另外,感谢作者的无私付出.
限速的问题就不必讨论了, 买个百度会员可以不限速 2333

**Comment by xtronaltic** [comment]
@jemyzhang 呵呵
