### ISSUE TITLE
希望能修复火狐网络请求失败的问题？

### ISSUE THREAD

**Issue by haibin88** [acgotaku/BaiduExporter#384]
火狐50..0.2
win8
打开百度盘，导出下载网络请求失败？
![screenshot00424](https://cloud.githubusercontent.com/assets/12547795/21550650/8c4cdf96-ce36-11e6-9a88-fa83b0d8f98a.png)

**Comment by acgotaku** [comment]
已经解决 请试试最新的开发版 还没打包
