### ISSUE TITLE
max file not found 和 http response header error 

### ISSUE THREAD

**Issue by kang0024** [acgotaku/BaiduExporter#385]
用aria2下载时出现HTTP response header was bad or unexpected和aria2 saw the specified number of "resource not found" error. See --max-file-not-found option，改过aria.conf的max-file-not-found=0或100, max-tries=100，retry-wait=5都无效。

用的是baiduexporter最新版本。比较奇怪的是conf里enable-rpc=true可是导出显示enable-rpc=false。手动继续下载可以继续，但是不久还是会弹出error，有时多次手动继续才能下载完。

下载链接如下：
aria2c -c -s10 -k1M -x10 --enable-rpc=false -o "水彩画工作室/水彩画工作室 I.pdf" --header "User-Agent: netdisk;5.3.4.5;PC;PC-Windows;5.1.2600;WindowsBaiduYunGuanJia" --header "Referer: http://pan.baidu.com/disk/home" --header "Cookie: BDUSS=kFkRFBQM1Zqek40UVRlUlVMV3ZtUWN5eFlwR2h1NGhHSkdlRFhBWUdBMWx6bzVZSVFBQUFBJCQAAAAAAAAAAAEAAAAXrpJhy8S088uiv6i7-gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGVBZ1hlQWdYb;pcsett=1483249178-d50aa802c7c37fa004ddc8ac9c5829ed" "https://d.pcs.baidu.com/file/0db2399b9a62eab22c1a3e7d9f5c926c?fid=2925877581-250528-353723539974519&time=1483164934&rt=pr&sign=FDTAERVCY-DCb740ccc5511e5e8fedcff06b081203-cuNsORjDY9lLZdBY8%2B2cC68nLSY%3D&expires=8h&chkv=1&chkbd=1&chkpc=et&dp-logid=8479160643732860479&dp-callid=0&r=562013496"
aria2c -c -s10 -k1M -x10 --enable-rpc=false -o "水彩画工作室/水彩画工作室 II.pdf" --header "User-Agent: netdisk;5.3.4.5;PC;PC-Windows;5.1.2600;WindowsBaiduYunGuanJia" --header "Referer: http://pan.baidu.com/disk/home" --header "Cookie: BDUSS=kFkRFBQM1Zqek40UVRlUlVMV3ZtUWN5eFlwR2h1NGhHSkdlRFhBWUdBMWx6bzVZSVFBQUFBJCQAAAAAAAAAAAEAAAAXrpJhy8S088uiv6i7-gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGVBZ1hlQWdYb;pcsett=1483249178-d50aa802c7c37fa004ddc8ac9c5829ed" "https://d.pcs.baidu.com/file/bc4131c4e4c7b34c704c635971d6cb6b?fid=2925877581-250528-700033202714100&time=1483164934&rt=pr&sign=FDTAERVCY-DCb740ccc5511e5e8fedcff06b081203-PZJtpcXIEY6z7XNzF7bX21pvxgQ%3D&expires=8h&chkv=1&chkbd=1&chkpc=et&dp-logid=8479160643732860479&dp-callid=0&r=465496902"

**Comment by acgotaku** [comment]
导出下载 是命令行模式 RPC模式 当然是开启RPC的

这个问题基本是自己的网络原因 无法修复 提问之前可以看看之前的issue

**Comment by wwulfric** [comment]
问题相同，可能是百度的原因?

**Comment by ugvf2009** [comment]
我也是同样的问题，配置没有问题。
aria2 saw the specified number of "resource not found" error. See --max-file-not-found option
估计是被百度和谐了。
