### ISSUE TITLE
大批量下载出现“网络请求失败”问题

### ISSUE THREAD

**Issue by jackeymai** [acgotaku/BaiduExporter#387]
我查询过之前的Issue关于请求失败的但是也没有解答。
想请问大概大于多少的时候下载会失败？我想下载照片。

![2017-01-02 8 23 39](https://cloud.githubusercontent.com/assets/18753761/21583643/f7f079de-d0c4-11e6-86fe-3eed5de47a92.png)

现在插件版本是：Version:0.8.7 更新日期: 2016/10/10
浏览器是：chrome 版本 55.0.2883.95 (64-bit)
系统是：Mac 10.11.6 (15G1004)

**Comment by acgotaku** [comment]
最新是  0.8.8 大批量下载出现问题 就只能一半一半 的下载 
大概多少会出现 你测试一下也知道了啊

**Comment by kang0024** [comment]
http header error 只能用重新导入解决吗？

**Comment by Sang0214** [comment]
以前下学习资料的时候测试过
没有测试过最大值，大概超过100就会出现这样的情况
你这样干脆用插件打成一个压缩包下载

**Comment by acgotaku** [comment]
@kang0024 只能重新导入。。。

**Comment by kang0024** [comment]
@acgotaku 试过了，重新导入和刷新的效果一样。几mb的书要刷新好几次，几百mb的火影啥的直接就能下载完，好诡异。。。

**Comment by acgotaku** [comment]
@kang0024 这个无解  有些资源就是不好下载

**Comment by jackeymai** [comment]
我大概有1000多个图片是否也不行？

**Comment by acgotaku** [comment]
你自己试试不就知道了 @jackeymai

**Comment by jackeymai** [comment]
我使用0.8.9来下载680多个都不可以，怎么样解决？

**Comment by acgotaku** [comment]
这个没法解决。。。我也很难复现这个问题。。。

**Comment by 007pig** [comment]
![image](https://cloud.githubusercontent.com/assets/508723/22360938/ea3579e6-e48f-11e6-916a-b34bf3c3af93.png)
看控制台输出是百度服务器报错，url too long

解决方法应该是大批量文件分批请求。
