### ISSUE TITLE
发现会影响tampermonkey里的一些脚本的运行

### ISSUE THREAD

**Issue by ted423** [acgotaku/BaiduExporter#388]
VM546:3 ERROR: Execution of script 'searchEngineJump-NextStage' failed! Cannot assign to read only property 'addEventListener' of object '#<HTMLDocument>'

https://greasyfork.org/zh-CN/forum/discussion/13497/安装了插件可是根本没有出现下载助手按钮啊-重启浏览器也没有用

似乎只要是用了addEventListener就会报错

**Comment by acgotaku** [comment]
是的 因为百度会删除我的插件 所以没法兼容 不知道那段删除代码去掉了没

**Comment by acgotaku** [comment]
fixed
