### ISSUE TITLE
使用最新插件，aria2GUI下载百度盘文件，会生成无数个下载任务？

### ISSUE THREAD

**Issue by choonwook** [acgotaku/BaiduExporter#389]
下载115网盘没有问题，但是用在百度盘的时候，点一个文件下载，会出现很多个相同文件，而且感觉删不完，会不停的出现，不知道是百度盘插件的问题，还是aria2GUI（1.3）的问题？谢谢

**Comment by acgotaku** [comment]
很明显 不是插件的问题啊 ==

要不然不会就你一个人来发issue的

**Comment by choonwook** [comment]
哈哈 好吧 我再找找问题 也许就是新版本aria2GUI的问题 原来用的1.19 还好 更新到1.3 就有这个问题了

**Comment by DeanChan** [comment]
请问一下，同一个文件下载时出现 `文件.1` , `文件.2` , `文件.3` 等多个重复文件是怎么回事？

aria2 version 1.19.3
BaiduExpoter version 0.8.9 
使用插件保存成`aria2c.down`后下载

**Comment by acgotaku** [comment]
@DeanChan 我也不知道。。。
