### ISSUE TITLE
点击ARIA2 RPC无反映

### ISSUE THREAD

**Issue by SuZixiong** [acgotaku/BaiduExporter#39]
之前试用正常，插件更新后无反映。
在隐身模式中已经测试过，应该不是我chrome的问题。
根据ARIA2导出的命令ssh可以下载成功

**Comment by acgotaku** [comment]
@SuZixiong 新版本更新了 RPC的认证方式，
Usage
Recommend: Set --rpc-secret= if you are using aria2 1.18.4(or higher) with 'JSON-RPC PATH' like http://token:secret@hostname:port/jsonrpc

Set --rpc-user= --rpc-passwd= if you are using aria2 1.15.2(or higher) with 'JSON-RPC PATH' like http://username:passwd@hostname:port/jsonrpc

**Comment by gutenye** [comment]
@Suzixiong 我用0.3.3版本, 也有同样的问题。 不过[0.3.4](https://github.com/acgotaku/BaiduExporter/commit/5450b77c6d5f96837ce587d59ba3d52a96db11bd) 已经修复了. 现在还在master上面, 你等更新把。

**Comment by SuZixiong** [comment]
已经更新0.3.4，ARIA2 RPC 地址设置为 :“ http://token:xxxxxxxx@192.168.1.207:6800/jsonrpc ”（xxxxxxxx）为Set --rpc-secret，点击ARIA2 RPC还是无反映。

**Comment by gutenye** [comment]
@SuZixiong 试试这个  https://github.com/acgotaku/BaiduExporter/pull/40#issuecomment-88506061

**Comment by SuZixiong** [comment]
应该不是这个问题，以下为我的conf。

## '#'开头为注释内容, 选项都有相应的注释说明, 根据需要修改 ##
## 被注释的选项填写的是默认值, 建议在需要修改时再取消注释  ##

## 文件保存相关 ##

# 文件的保存路径(可使用绝对路径或相对路径), 默认: 当前启动位置
dir=/home/pi/downloads
# 启用磁盘缓存, 0为禁用缓存, 需1.16以上版本, 默认:16M
#disk-cache=32M
# 文件预分配方式, 能有效降低磁盘碎片, 默认:prealloc
# 预分配所需时间: none < falloc ? trunc < prealloc
# falloc和trunc则需要文件系统和内核支持
# NTFS建议使用falloc, EXT3/4建议trunc, MAC 下需要注释此项
#file-allocation=none
# 断点续传
continue=true

## 下载连接相关 ##

# 最大同时下载任务数, 运行时可修改, 默认:5
max-concurrent-downloads=5
# 同一服务器连接数, 添加时可指定, 默认:1
max-connection-per-server=5
# 最小文件分片大小, 添加时可指定, 取值范围1M -1024M, 默认:20M
# 假定size=10M, 文件为20MiB 则使用两个来源下载; 文件为15MiB 则使用一个来源下载
min-split-size=10M
# 单个任务最大线程数, 添加时可指定, 默认:5
split=5
# 整体下载速度限制, 运行时可修改, 默认:0
#max-overall-download-limit=0
# 单个任务下载速度限制, 默认:0
#max-download-limit=0
# 整体上传速度限制, 运行时可修改, 默认:0
#max-overall-upload-limit=0
# 单个任务上传速度限制, 默认:0
#max-upload-limit=0
# 禁用IPv6, 默认:false
disable-ipv6=true

## 进度保存相关 ##

# 从会话文件中读取下载任务
input-file=/etc/aria2/aria2.session
# 在Aria2退出时保存`错误/未完成`的下载任务到会话文件
save-session=/etc/aria2/aria2.session
# 定时保存会话, 0为退出时才保存, 需1.16.1以上版本, 默认:0
#save-session-interval=60

## RPC相关设置 ##

# 启用RPC, 默认:false
enable-rpc=true
# 允许所有来源, 默认:false
rpc-allow-origin-all=true
# 允许非外部访问, 默认:false
rpc-listen-all=true
# 事件轮询方式, 取值:[epoll, kqueue, port, poll, select], 不同系统默认值不同
#event-poll=select
# RPC监听端口, 端口被占用时可以修改, 默认:6800
#rpc-listen-port=6800
# 设置的RPC授权令牌, v1.18.4新增功能, 取代 --rpc-user 和 --rpc-passwd 选项
rpc-secret=suzixiong
# 设置的RPC访问用户名, 此选项新版已废弃, 建议改用 --rpc-secret 选项
#rpc-user=<USER>
# 设置的RPC访问密码, 此选项新版已废弃, 建议改用 --rpc-secret 选项
#rpc-passwd=<PASSWD>

## BT/PT下载相关 ##

# 当下载的是一个种子(以.torrent结尾)时, 自动开始BT任务, 默认:true
#follow-torrent=true
# BT监听端口, 当端口被屏蔽时使用, 默认:6881-6999
listen-port=51413
# 单个种子最大连接数, 默认:55
#bt-max-peers=55
# 打开DHT功能, PT需要禁用, 默认:true
enable-dht=false
# 打开IPv6 DHT功能, PT需要禁用
#enable-dht6=false
# DHT网络监听端口, 默认:6881-6999
#dht-listen-port=6881-6999
# 本地节点查找, PT需要禁用, 默认:false
#bt-enable-lpd=false
# 种子交换, PT需要禁用, 默认:true
enable-peer-exchange=false
# 每个种子限速, 对少种的PT很有用, 默认:50K
#bt-request-peer-speed-limit=50K
# 客户端伪装, PT需要
peer-id-prefix=-TR2770-
user-agent=Transmission/2.77
# 当种子的分享率达到这个数时, 自动停止做种, 0为一直做种, 默认:1.0
seed-ratio=0
# 强制保存会话, 话即使任务已经完成, 默认:false
# 较新的版本开启后会在任务完成后依然保留.aria2文件
#force-save=false
# BT校验相关, 默认:true
#bt-hash-check-seed=true
# 继续之前的BT任务时, 无需再次校验, 默认:false
bt-seed-unverified=true
# 保存磁力链接元数据为种子文件(.torrent文件), 默认:false
bt-save-metadata=true

**Comment by gutenye** [comment]
那肯定不是和我同一个问题， 呼叫 @acgotaku

**Comment by acgotaku** [comment]
@gutenye 你的Aria2c的版本号多少？可以试试在百度云盘页面按F12 看Console页面有没有什么异常的输出

**Comment by gutenye** [comment]
aria2 version 1.15.1

我并没有设置 `--rpc-secret` 或` --rpc-user= --rpc-passwd=`, 所以我是用`http://aria2.lan:6800/jsonrpc`的， 是成功的。

**Comment by acgotaku** [comment]
@SuZixiong 你的Aria2c的版本号多少？可以试试在百度云盘页面按F12 看Console页面有没有什么异常的输出

@gutenye 我问错人了。。。 那个1.15.1版本压根不支持验证 所以肯定不能这样玩

**Comment by ExinCoda** [comment]
@acgotaku 我和 @gutenye 是一样的情况，1.15.1版本的aria2，
我点击Aria2 PRC按钮后在控制台刷出了以下信息（抱歉不会弄格式）：

Mixed Content: The page at 'https://pan.baidu.com/disk/home' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://aria2.cc:6801/jsonrpc'. This request has been blocked; the content must be served over HTTPS.VM358:62 HttpSendReadVM358:884 baidupan.aria2send_dataVM358:877 baidupan.aria2_rpcVM358:251 baidupan.get_infospeed-disk-home_d4a21e4.js:6 (anonymous function)all_a077317.js:3 dall_a077317.js:3 p.fireWithall_a077317.js:5 rall_a077317.js:5 r

地址栏上的小锁是带黄色警告的。
请问是您的插件的问题吗？如何解决？

**Comment by ExinCoda** [comment]
上面粘贴的内容有误，以下面的为准(勉强整理了一下)：
Mixed Content: The page at 'https://pan.baidu.com/disk/home' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://aria2.cc:6801/jsonrpc'. This request has been blocked; the content must be served over HTTPS.
HttpSendRead                                                                       VM358:62
baidupan.aria2send_data                                                      VM358:884
baidupan.aria2_rpc                                                                VM358:887
baidupan.get_info                                                                  VM358:251
(anonymous function)                             speed-disk-home_d4a21e4.js:6 
d                                                                                      all_a077317.js:3 
p.fireWith                                                                         all_a077317.js:5
r                                                                                      all_a077317.js:5 r
r                                                                                     all_a077317.js:5 r

**Comment by acgotaku** [comment]
@ExinCoda 应该是启用了 https加密导致的问题 你先用 Http的网盘

**Comment by ExinCoda** [comment]
@acgotaku 现在百度盘是强制https的吧？

**Comment by gutenye** [comment]
@acgotaku 解决方法只能用Chrome扩展的XMLHttpRequest的把?
@ExinCoda 我就是用http://的.

**Comment by acgotaku** [comment]
@ExinCoda http我照样可以使用啊

**Comment by ExinCoda** [comment]
@acgotaku @gutenye 我都忘了自己装了HTTPS everywhere的插件了，哈哈，糊涂了
感谢回复

**Comment by SuZixiong** [comment]
我也是用了HTTPS everywhere导致的。。。
已经解决了。
谢谢各位！

**Comment by acgotaku** [comment]
@ExinCoda  @SuZixiong 现在 aria2c支持使用https通信了 前提是你得有证书。。。

**Comment by SuZixiong** [comment]
我的百度云被限制500kb/s的下载速度了。
不知道怎么办才好。。。
雪月秋水 <notifications@github.com>于2015年6月10日 周三16:54写道：

**Comment by acgotaku** [comment]
@SuZixiong 你可以看看你的UA参数 贴出来

**Comment by SuZixiong** [comment]
netdisk;4.4.0.6;PC;PC-Windows;6.2.9200;WindowsBaiduYunGuanJia

上面是我百度网盘助手设置里的UA，我没有改，用的默认的。

2015-06-10 17:40 GMT+08:00 雪月秋水 <notifications@github.com>:

**Comment by acgotaku** [comment]
@SuZixiong 你重置 下插件 UA会自动的更新到最新的就解决了

**Comment by SuZixiong** [comment]
好的，我试试看。谢谢！

2015-06-11 11:14 GMT+08:00 雪月秋水 <notifications@github.com>:
