### ISSUE TITLE
请问 那个 extension id 是多少来着？

### ISSUE THREAD

**Issue by LiHanGuang** [acgotaku/BaiduExporter#390]
Hello acgotaku：

https://hencolle.com/2016/10/16/baidu_exporter/

请问上面这个教程里的 extension id  是多少， 因为我看到的网页里面的图片显示不出来， 谢谢。

**Comment by sqc1999** [comment]
你直接往自己浏览器里装一下不就可以看到了吗

**Comment by acgotaku** [comment]
启动开发者模式就可以看到啊

**Comment by LiHanGuang** [comment]
谢谢， 另外 Safari 那个要怎么弄？没看懂下面的教程， 还是说目前只能用 chrome？

>Safari : Install Chrome or Firefox on Mac.

**Comment by acgotaku** [comment]
@LiHanGuang Safari现在已不再支持

**Comment by LiHanGuang** [comment]
@acgotaku

谢谢， 您的解答 #
