### ISSUE TITLE
firefox、edge浏览器无法使用插件?

### ISSUE THREAD

**Issue by jizeta** [acgotaku/BaiduExporter#392]
开发者你好，首先谢谢你提供如此棒的插件并悉心维护。
目前使用上碰到了一些问题，已尝试卸载重新安装、清空浏览器cookie等方法皆无法解决。

1.firefox，版本:50.1.0
baiduexporter版本:0.8.8
问题1:显示网路请求失败
问题2:安装教学写进入about:debugging后，点选载入暂用附加元件将路径指向chrome资料夹，但却无法载入元件，后来改在安装附加元件时，将BaiduExporter-master资料夹内的firefix.xpi载入即可安装，但版本显示为0.8.8且出现问题1的情形。

2.microsoft edge，版本:38.14393.0.0
baiduexporter版本:0.8.9
问题1:叫出导出下载视窗时，点选存为aria2、idm文件等四个选项时皆无反应。

麻烦开发者帮忙，谢谢!

**Comment by acgotaku** [comment]
FF已经不支持 XPI安装  载入文件夹测试是可以的

edge浏览器是 @CnSimonChan 维护的 我并没有测试过。。。

**Comment by CnSimonChan** [comment]
我能在 14393 上重现，15007 上正常，但是在 14393 之前的 Insider Preview 上绝对是正常的。

去 developer.microsoft.com 看了下， `navigator.msSaveBlob` 在 Content Scripts 里问题非常多。

总之暂时的 workaround 是放到页面里执行，把 [core.js L426-431](https://github.com/acgotaku/BaiduExporter/blob/master/chrome/src/core.js#L426-L431) 替换成

```` JavaScript
$("#aria2c_btn, #idm_btn, #download_txt_btn").data("href", "").click(function (e) {
    var $this = $(this);

    var s = document.createElement("script");
    s.textContent = 'navigator.msSaveBlob(new Blob(["' + $this.data("href").replace(/\r/g, "\\r").replace(/\n/g, "\\n") + '"]), "' + $this.attr("download") + '")';
    document.body.appendChild(s);
});
````

（这里之前还有个 bug 导致下载的文件开头有个 `undifined` ，之前居然没测出来

15007 上 Edge 已经能识别 `a[download]` 了，但是 Edge 是不支持 `data:` 的，比较好的跨平台解决方案是 `URL.createObjectURL()` ，但是因为是下载所以没法及时 revoke 会导致内存泄漏，所以下载文件暂时还是判断平台吧。

**Comment by jizeta** [comment]
@acgotaku 开发者你好，
还是不太懂如何可以指向chrome资料夹?
例如此图:http://i.imgur.com/XOdFde7.jpg
当我点选chrome资料夹时他会要求我开启一个档案而不是整个资料夹写入，
还是我根本误会说明的意思了?

如果是我误会，可否将正确步骤叙述一次?
谢谢!

**Comment by jizeta** [comment]
@CnSimonChan 开发者你好，
在下程式小白，撇开程式码部分不说，
意思是得先等微软更新edge到15007版本就可以正常使用了?

谢谢你详尽的解说!

**Comment by acgotaku** [comment]
@jizeta 你就在那个文件夹下随便点个文件点打开就好了啊

**Comment by CnSimonChan** [comment]
@jizeta 我是回给 @acgotaku 的，因为我现在没装 git

@acgotaku 你改下还是我 pr 给你？

**Comment by acgotaku** [comment]
@CnSimonChan 那我改下更快吧

**Comment by CnSimonChan** [comment]
@acgotaku 好

**Comment by jizeta** [comment]
@acgotaku 开发者你好，
安装完成后，每次只要重开firefox附加元件就会自动被删除，
得要重装一次才能再使用，请问这是正常的吗?

**Comment by acgotaku** [comment]
@jizeta  是的
