### ISSUE TITLE
关于用百度插件下载ARIA2，被百度检测，并拉黑账号限速0K的问题。

### ISSUE THREAD

**Issue by s123077** [acgotaku/BaiduExporter#393]
我前天已更新到最新百度插件，并新申请的百度云账号A，ARIA2离线下载，开始速度很快能到1.4M左右的速度，昨天还是这个账号A，再用百度云ARIA2下载，就变成50K,无论什么资源都是如此。我把账号B给同学用，他也是50K，说明不是网络问题，他自己账号B用自己网络能500K，用我的网络他账号B百度加ARIA2下载也1.3M左右，到下午他的账号无论在哪下载都被限速50K。说明他的账号也被百度检测拉黑了限速50K，同时我在网络搜索到很多用百度破解管家或者第三方下载百度的都会被拉黑限速10K或者50K, （文章https://www.zhihu.com/question/51849528    ）搜索百度限速10k 或者搜索百度限速50K都是最近的事，我的一个老账号是被限速了10K，我不知道老大您是否能破解这个检测，百度云插件现在不怎么敢用我都被拉黑了3个账号了，百度检测太厉害了。

**Comment by conanwhf** [comment]
我觉得好像不是帐号的问题，不清楚检测机制。我就一个帐号，被限制的时间完全是随机的，有时候完全没限制速度很好；有时候限制线程，多开几个线程速度就上去了；有时候多开线程也没用，几K的速度在跑。并且这个跟网速无关，反而跟文件有关，因为我有一次同时下不同的文件，会有不同的表现，并且cancel重新下载也是一样。这个很奇怪，估计跟服务器的cache有关。
我想这个问题除非是百度的人来讲到底是靠什么检测，否则我们是猜不出来的。

**Comment by acgotaku** [comment]
我也不是万能的啊。。。

**Comment by jsdtt** [comment]
我今天偶然发现，在不登陆百度账号的情况下导出下载基本都是满速-只要一登陆账号就只有100k左右

**Comment by boy404** [comment]
早上满速，下午就限的死死了，无奈

**Comment by Ldcr993519867** [comment]
好像现在加了账号黑名单机制?
超了就拉黑名单,限速到10k/s

我也被限速过
不过我一周没下载,之后速度又恢复了

**Comment by yh127** [comment]
确实取消登录之后速度更快，登录反而只有50k/s。不过只能下载别人分享的资源，离线什么的就只能慢慢下了。

**Comment by acgotaku** [comment]
速度问题已解决 更新到 0.9.0版本

**Comment by venkate123** [comment]
@acgotaku 老大你果然是万能的。。

**Comment by lautis0503** [comment]
检测机制更进了……
0.9.3版本下载十多个G后，导出下载速度为0，勾选SVIP导出才有160K/s。
更换账号速度正常。

**Comment by acgotaku** [comment]
@lautis0503 帐号限速是无解的。。。

**Comment by lingiori** [comment]
通过插件解析出来的url和账号有什么关系吗？通过aria2下载的时候也不绑定账号啊？

**Comment by ElfSundae** [comment]
被限速了N天的路过..  不登录就好了

**Comment by lizyn** [comment]
所以我想说 README 里关于非 SVIP 会员要先保存到自己网盘的这一点, 是不是写错了?

**Comment by LiHanGuang** [comment]
@acgotaku 
> 我也不是万能的啊。。。
> @lautis0503 帐号限速是无解的。。。

这些用的人都不知道"插件不是万能的, 只是用来导出链接", 他们只问结果, 你就不用计较了.....

**Comment by XXonline** [comment]
我昨天刚配置好使用了一个小时，之后速度就一直都是50kb左右了😢
