### ISSUE TITLE
mac使用aria2gui可以满速下载，能否提取这个链接给予别人！真正意义上的破解限速

### ISSUE THREAD

**Issue by ElvinYan** [acgotaku/BaiduExporter#396]
我有个想法就是：
我是百度超级云会员，然后我打开我的网盘进入了我的账号使用百度云插件导出下载链接，复制下载链接，然后手动添加到了aria2gui下载器，之前这个方法可行，下载速度也非常快，但是最近几天复制的这个链接已经不能用于下载了，只能通过粘贴到浏览器，然后，浏览器会识别这个链接，产生出一个另外的下载链接，要复制这个下载链接再粘贴到aria2gui下载器中才可以有效下载，但是这样速度就被限制了。
我是想如果导出下载的时候直接选者第一个aria rpc导出下载这样下载速度非常快（以测试过）但是如何才能过把这个链接的信息提取出来发给别人，让别人也可以下载。这是我的一个想法！是否有工具可以提取？

**Comment by ElvinYan** [comment]
![2017-01-24 11 53 22](https://cloud.githubusercontent.com/assets/25326192/22254912/d6eedd4c-e290-11e6-86a4-4138a6d6a62a.jpg)

**Comment by acgotaku** [comment]
导出成文本不就可以发给别人了么

**Comment by ElvinYan** [comment]
不行啊。导出成文本然后上传种子对吧。这样也下载不了。就是不知道为什么到处点击导出aria rpc这个选项是正常的，导出其他。什么拷贝链接啊。到处下载文本，导出来的都不是有效的链接

**Comment by acgotaku** [comment]
![screenshot from 2017-01-25 12-25-58](https://cloud.githubusercontent.com/assets/1191834/22277820/20d78cfe-e284-11e6-9943-503a337ac549.png)
就是点上面的导出 aria2c文件就好了啊

**Comment by ElvinYan** [comment]
村委arira2文件之后怎么使用呢。我把这个文件拉到下载器没反应啊

**Comment by acgotaku** [comment]
命令行导入用的啊。。。  你可以查查aria2c手册

**Comment by AurevoirXavier** [comment]
我一般都把账号直接借给别人用。

**Comment by ypwu1** [comment]
我也是超级会员，但我的ip是在国外。我有一个问题，每个链接好像有时效的，我批量下载的时候，后面的文件就下不了。请问大家有碰到这问题吗？

**Comment by HerringtonDarkholme** [comment]
> 把这个链接的信息提取出来发给别人

会暴露账号Cookie，不安全

**Comment by acgotaku** [comment]
速度问题已解决 在自己网盘下试试
