### ISSUE TITLE
建议加入axel的支持

### ISSUE THREAD

**Issue by jianglin332** [acgotaku/BaiduExporter#397]
aria2c最多只能开16个连接，而每个连接百度限速500KB/s，即最大速度只有8MB/s。而axel并没有最大连接数的限制，所以可以达到10MB/s。

axel -n 连接数 -o 文件名 -U "netdisk;5.3.4.5;PC;PC-Windows;5.1.2600;WindowsBaiduYunGuanJia" -H "Referer: http://pan.baidu.com/disk/home" -H "Cookie: pcsett=xxxxxx" url

**Comment by Gordon-shin** [comment]
aria2c 有不限制线程的版本的。百度一下就有

**Comment by acgotaku** [comment]
目前还没有这个的强烈需求。。。
