### ISSUE TITLE
无法使用token在同一局域网中链接aria2下载机

### ISSUE THREAD

**Issue by lincolnguang** [acgotaku/BaiduExporter#399]
![snipaste20170129_133927](https://cloud.githubusercontent.com/assets/23733891/22402170/63311f64-e628-11e6-9ad4-c91e36650c61.png)

尝试用android创建了aria2下载机，不使用token可以链接，使用以后，插件无法链接，其他方法依旧可以。求告知是否是jsonrpc设置错误，或者是其他原因

![image](https://cloud.githubusercontent.com/assets/23733891/22402174/7073c9ec-e628-11e6-9352-7e61c497906d.png)
![image](https://cloud.githubusercontent.com/assets/23733891/22402176/7bf3b084-e628-11e6-96e9-e4b27dc9a584.png)

谢谢

#EOF

**Comment by acgotaku** [comment]
确认下 yaaw是不是能正常连接？

**Comment by lincolnguang** [comment]
#YAAW token
##使用http时
无法链接
##使用websocket
可以
#本插件
均不可以

**Comment by acgotaku** [comment]
本插件不支持 ws 以上

**Comment by lincolnguang** [comment]
好的，那就可以关闭这个issue了，谢谢
