### ISSUE TITLE
某资源下载出现错误，文件大小不符

### ISSUE THREAD

**Issue by xdujiang** [acgotaku/BaiduExporter#401]
发现了一个奇怪的资源，体积1.93G，但导出下载后aria2显示只有4MB
尝试过开隐身模式，问题一样，其他资源是正常的

插件版本：0.8.9
浏览器版本：chrome x86 53.0
系统：win10 10240

资源地址：https://pan.baidu.com/share/link?shareid=1115777564&uk=3842487466&fid=11534599096938

**Comment by acgotaku** [comment]
针对某个资源的下载错误 这是百度的错误 不是插件的问题
