### ISSUE TITLE
最新的版本虽然解决了速度问题，但是引入了新的问题

### ISSUE THREAD

**Issue by sqc1999** [acgotaku/BaiduExporter#402]
最新版本使用的那个方法必须要有Cookies的支持，所以导出时的“保存下载链接”和“拷贝下载链接”已经意义不大。建议针对这两个按钮使用旧方法，或者索性去掉那两个按钮。

**Comment by dukedhx** [comment]
可以判断一下是否有cookie支持在决定是否disable按钮：

`var cookieEnabled = (navigator.cookieEnabled) ? true : false;

	if (typeof navigator.cookieEnabled == "undefined" && !cookieEnabled)
	{ 
		document.cookie="testcookie";
		cookieEnabled = (document.cookie.indexOf("testcookie") != -1) ? true : false;
	}
	return (cookieEnabled);`

**Comment by sqc1999** [comment]
不是这个意思的说。。我是说如果有直接复制下载链接的按钮的话，正常思路不就是“复制链接->打开迅雷->粘贴链接下载”之类的，这样不就爆炸了吗

**Comment by linhua55** [comment]
应该  右键点击链接---> 用迅雷下载    ，这样可以导入cookie

**Comment by sqc1999** [comment]
然而不是只有复制和保存的按钮吗。。

**Comment by Alicture** [comment]
表示复制地址迅雷下载不了。望修复，考研狗急需。

**Comment by acgotaku** [comment]
@Alicture 换 aria2c！

**Comment by Alicture** [comment]
@acgotaku 好的！

**Comment by linhua55** [comment]
https://greasyfork.org/zh-CN/scripts/23635-%E7%99%BE%E5%BA%A6%E7%BD%91%E7%9B%98%E7%9B%B4%E6%8E%A5%E4%B8%8B%E8%BD%BD%E5%8A%A9%E6%89%8B

**Comment by sqc1999** [comment]
@linhua55 什么意思。。

**Comment by v1-hermit** [comment]
@linhua55 不知所云。。

**Comment by linhua55** [comment]
就是 右键点击链接，不是会弹出  浏览器右键菜单栏吗。 如果浏览器右键菜单栏里有  使用迅雷下载  的话，使用这种方法下载链接，会把浏览器的cookie也传递过去。从而实现在迅雷中正常下载

**Comment by acgotaku** [comment]
嘛 最新版可以通过选择 是否是 SVIP来切换下载链接
