### ISSUE TITLE
Cannot find module `common:widget/moveSaveDialog/moveSaveDialog.js`

### ISSUE THREAD

**Issue by sunzy** [acgotaku/BaiduExporter#404]
1. 下载的内容地址: http://pan.baidu.com/s/1i3gxwkX 密码: 95pb
2. 插件版本号(v0.8.5)，浏览器版本号(chrome 56.0.2924.87 (64-bit))，系统版本号（OS X EI Capitan 10.11.6）
3. 列举出现问题的详细步骤
安装完插件后右上角的降落伞图标是灰色的。
打开网盘下载页面，并没有导出链接的按钮
通过chrome的开发者工具查看显示如下错误信息：
Uncaught Error: Cannot find module `common:widget/moveSaveDialog/moveSaveDialog.js`
    at require (mod_15bd44a.js:1)
    at convert.js:307
    at convert.js:347
    at convert.js:348
4. 描述能否复现问题
能复现

**Comment by acgotaku** [comment]
？？？ 现在插件都 0.9.1版本了？ 你逗我呢？？？

**Comment by ipodtun** [comment]
百度会封IP吗？我100M带宽，用了两天一直10M下载速度，突然这两天成1M了，还挺稳定。
感谢~

**Comment by acgotaku** [comment]
@ipodtun 这我怎么知道。。。

**Comment by ipodtun** [comment]
user-agent默认那个是什么，换了一个没速度了，原来的忘存了:) 3Q~

**Comment by acgotaku** [comment]
@ipodtun 你可以点重置按钮 重置啊

**Comment by sunzy** [comment]
@acgotaku 
 https://github.com/acgotaku/BaiduExporter/releases

我是搜索到这个链接下载的Last Release(v0.8.5)

**Comment by acgotaku** [comment]
@sunzy 那去code页面下载最新的去

**Comment by sunzy** [comment]
@acgotaku 好的，谢谢
