### ISSUE TITLE
0.9.1 插件在 chrome 里启用不了

### ISSUE THREAD

**Issue by IAMJ** [acgotaku/BaiduExporter#405]
1. 插件版本号: 0.9.1 ，浏览器版本号: chrome 56.0.2924.87 (64-bit)，系统版本号: macOS 10.12.3
2. 启用的勾选是灰色的，0.8.9 则可以勾选
后续更新： 是直接把 crx 文件拖进去扩展界面安装的，不是通过加载已解压的方式。通过加载已解压的方式安装可以正常勾选。感觉这个可以 close 了。。

![01](https://cloud.githubusercontent.com/assets/2928760/22776631/658c2ada-eeeb-11e6-8fe9-c01c2b52f6ae.png)
![02](https://cloud.githubusercontent.com/assets/2928760/22776632/65a94534-eeeb-11e6-924d-4916ed6ed070.png)

**Comment by tofuliang** [comment]
第一次看到可以同时安装两个id相同的扩展,感觉你可以向Google chrome报bug了.

J <notifications@github.com>于2017年2月9日周四 下午5:16写道：

**Comment by IAMJ** [comment]
@tofuliang 
不是，那是两张截图

**Comment by dongdongdu** [comment]
没启用开发者模式？

**Comment by tofuliang** [comment]
到 chrome://policy/ 检查下是不是你的 ExtensionInstallWhitelist 没加好吧, macOS 10.11.6
chrome 56.0.2924.87 (64-bit) 正常使用.

J <notifications@github.com>于2017年2月9日周四 下午5:22写道：

**Comment by IAMJ** [comment]
@tofuliang @dongdongdu 
通过加载已解压的方式安装可以正常勾选了，通过拖放 crx 文件的方式就不行

**Comment by tofuliang** [comment]
都说了,看policy里面的值.

J <notifications@github.com>于2017年2月9日周四 下午5:30写道：

**Comment by IAMJ** [comment]
@tofuliang
ExtensionInstallWhitelist 确实没设置，但为什么之前的 0.8.9 的 crx 就可以？

**Comment by cjh-github** [comment]
我也遇到了相同的问题，之前版本没问题，0.9.1就是启用不了，灰的。
暂时加载文件夹用着。

2017年2月9日 18:42，"雪月秋水" <notifications@github.com>写道：

**Comment by acgotaku** [comment]
@cjh-github 老的有删掉么？

**Comment by cjh-github** [comment]
![sp170210_091513](https://cloud.githubusercontent.com/assets/6256701/22810117/c542421c-ef71-11e6-9a98-68b74f5714aa.png)

问题应该在这里，设置的白名单没生效，再找找原因了

**Comment by acgotaku** [comment]
crx的扩展 ID应该是 padhohbdomknelobmiphhcafepnfipaa 才对 不知道你的为什么这么怪

**Comment by cjh-github** [comment]
@acgotaku  我是自己用chrome打包的

**Comment by acgotaku** [comment]
@cjh-github 那你还是自己解决吧。。。 自己动手 丰衣足食。。。

**Comment by AnClark** [comment]
开发者模式安装插件无限制。实在不行的话，试试360极速浏览器这样的第三方Chrome内核浏览器。个人感觉谷歌官方Chrome做的是越来越坑

**Comment by sqc1999** [comment]
我不想吵架，所以就点个`-1`吧
