### ISSUE TITLE
Issue while accessing `pan.baidu.com` via HTTPS

### ISSUE THREAD

**Issue by rankjie** [acgotaku/BaiduExporter#406]
下载的内容地址 [https://pan.baidu.com/s/1gfmjoUR](https://pan.baidu.com/s/1gfmjoUR)

根据 Chrome 的安全限制，HTTPS 页面内脚本内访问 localhost 的请求由于是 HTTP 的就被阻断了

虽然可以手动改 HTTPS 回到 HTTP 来解决问题，但是不排除百度网盘以后会全面转向 HTTPS，而且这样挺麻烦的 눈_눈

FYI:
Mixed Content: The page at 'https://pan.baidu.com/s/1gfmjoUR' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://localhost:23330/rpc'. This request has been blocked; the content must be served over HTTPS.
(anonymous) @ inject.js:12

**Comment by InsulationSMT** [comment]
chrome的安全策略导致的？？？不能下载的原因竟然是这个么……

**Comment by acgotaku** [comment]
??? 你用的哪个版本？ 这个问题最新版应该是不存在才对

**Comment by rankjie** [comment]
抱歉，更新版本后没重启浏览器。现在已确认0.9.1不存在该问题
