### ISSUE TITLE
无法进行下载

### ISSUE THREAD

**Issue by InsulationSMT** [acgotaku/BaiduExporter#407]
插件版本号:0.9.1
浏览器版本号:chrome 56.0.2924.87
系统版本号：windows 10 14393.693
无法通过该插件使用Aria2c或者IDM下载，查看控制台发现报错和下载链接进行了比对但是不清楚问题在哪
[https://1drv.ms/i/s!AkTdWfdZVjY7ldh-J0qT_JCKRvRjRw](url)

**Comment by acgotaku** [comment]
？？？ 附带的链接是 404？？

**Comment by InsulationSMT** [comment]
不清楚为什么需要选中右键转到才能打开……

**Comment by InsulationSMT** [comment]
这个链接和下载链接的一部分是一样的……

**Comment by acgotaku** [comment]
我打不开。。。

**Comment by InsulationSMT** [comment]
图片内容是一个报错：
Fail to load resource：https://pcs.baidu.com/rest/2.0/pcs/file(后面省略，
这一段网址刚好是IDM解析的网址的一部分……

**Comment by sqc1999** [comment]
首先，你给出的这个错误应该不是由这个插件产生的
然后，这个错误说明你无法连接到`pcs.baidu.com`，而插件的下载依赖于它。这是你的网络环境的问题
