### ISSUE TITLE
疑似百度限速

### ISSUE THREAD

**Issue by hongzai1994** [acgotaku/BaiduExporter#408]
登录百度账号导出下载时速度只有10到20kb／s
退出登录后下载能达到满速。这是被百度限速了么？

1. 您下载的内容地址
https://yun.baidu.com/s/1i3CAYyx?errno=0&errmsg=Auth%20Login%20Sucess&&bduss=&ssnerror=0
2. 插件版本号，浏览器版本号，系统版本号
0.9.1， 56.0.2924.87 (64-bit)，macOS 10.12.3

----------

**不符合上述条件的Issue将被无理由关闭**

**Comment by acgotaku** [comment]
你保存到自己网盘再下载速度就上去了
