### ISSUE TITLE
资源下载完成只有6B，内容为abcd

### ISSUE THREAD

**Issue by LarkinZero** [acgotaku/BaiduExporter#409]
链接：http://pan.baidu.com/s/1nvwg3OX 密码：qspe
OSX 10.12.3
Chrome 56.0.2924.87
BaiduExporter 0.9.1

下载后立即完成了，检查大小只有6B，内容看了下只有abcd
新安装的Chrome，插件也是新安装的。多次尝试后仍旧下载出错

**Comment by acgotaku** [comment]
部分资源 可能服务器本身就是有问题 如果所有资源下载都是有问题的话 那估计是插件获取问题

**Comment by acgotaku** [comment]
![screenshot from 2017-02-15 11-40-21](https://cloud.githubusercontent.com/assets/1191834/22959735/386ece9c-f2fe-11e6-9216-a8256a15f6cc.png)

我这里测试正常

**Comment by LarkinZero** [comment]
我再试试

**Comment by LarkinZero** [comment]
下载另外一个资源后暂停，然后再下这个资源就正常了，好奇怪

**Comment by o2chan** [comment]
我也遇到过这种情况，不过好像极少出现的样子
