### ISSUE TITLE
貌似失效了。。没按钮了

### ISSUE THREAD

**Issue by iwfq** [acgotaku/BaiduExporter#41]
貌似失效了。。没按钮了

**Comment by iwfq** [comment]
http没问题，如果是https://pan.baidu.com，则没有按钮。

**Comment by acgotaku** [comment]
@iwfq https://pan.baidu.com/disk/home  这个网址应该没问题吧？

还有你的运行环境是什么呢？ 这点信息我是无法判断原因的。。。

**Comment by acgotaku** [comment]
@iwfq  https下插件是不能RPC的，这个有待处理 目前只能使用 http

**Comment by ghostry** [comment]
发现很奇怪的问题.在http下.直接进网盘-全部文件是没有按钮的.但是先进一个分享出按钮,然后再回来全部文件也有了.
谷歌版本 41.0.2272.118 (64-bit)

**Comment by acgotaku** [comment]
@ghostry 这个应该不会吧？ 刷新下试试看 我用的就是64位Chromium啊

**Comment by ghostry** [comment]
@acgotaku 所以说时奇怪的问题。刷新时解决不了的。目前的做法只能是先进一个分享的页面。然后再进全部文件。我也试着禁用别的扩展，只留这一个。仍然如此。

**Comment by acgotaku** [comment]
@ghostry F12 Console里面出现错误提示了么？ 开隐身模式会不会出现？

**Comment by ghostry** [comment]
@acgotaku 隐身模式也不行。错误
??common-cdn/pkg/other-async_0fcc6ae.js,common-cdn/pkg/speed-disk-home_ce51ff3.js,common-cdn/widget…:3 
??common-cdn/pkg/other-async_0fcc6ae.js,common-cdn/pkg/speed-disk-home_ce51ff3.js,common-cdn/widget…:3 
??common-cdn/pkg/other-async_0fcc6ae.js,common-cdn/pkg/speed-disk-home_ce51ff3.js,common-cdn/widget…:3 
all_7c99282.js:5 Resource interpreted as Script but transferred with MIME type text/html: "https://d.pcs.baidu.com/rest/2.0/pcs/manage?method=listhost&t=1430483128116&callback=jQuery17208267584410496056_1430483126035&_=1430483128117".

**Comment by acgotaku** [comment]
@ghostry 这个是正常输出。。。
