### ISSUE TITLE
更改导出aria2命令的并发连接数为16

### ISSUE THREAD

**Issue by zh99998** [acgotaku/BaiduExporter#410]
在百度网盘有限速，本地带宽充足的场景，连接数跟最终下载成比较严格的正比例关系。
这里测试默认10连接速度有4.6M/s，而16连接速度能到7.5M/s

16是aria2允许的最大值

**Comment by acgotaku** [comment]
菊苣出现啦！

**Comment by badsirius** [comment]
辛苦你了，一直在用！
请问有Donate渠道吗？

**Comment by diggerdu** [comment]
留给支付宝帐号吧
