### ISSUE TITLE
无法下载文件

### ISSUE THREAD

**Issue by xingezhang** [acgotaku/BaiduExporter#412]
请确保以下几点：

1. 已经阅读过README
2. 尝试安装最新版本插件
3. 尝试清空浏览器缓存
4. 尝试卸载插件后重新安装

发起 Issue 时，请提供：

1. 您下载的内容地址
http://pcs.baidu.com/rest/2.0/pcs/file?method=download&app_id=250528&path=%2Ffmpa_15.0.1.119.dmg
2. 插件版本号，浏览器版本号，系统版本号
插件0.92 浏览器chrome56.0.292487(64bit) 系统windows10
3. 列举出现问题的详细步骤
导出下载到Aria2，提示找不到Aria2，但是可以导出下载地址，手工添加到Aria2，无法下载
4. 描述能否复现问题
是
----------

**不符合上述条件的Issue将被无理由关闭**

**Comment by acgotaku** [comment]
你开了 RPC模式？ 还是使用命令行模式？

**Comment by xingezhang** [comment]
rpc模式，用token

**Comment by acgotaku** [comment]
那为啥会提示找不到？ 你确认开了？ 给个演示视频或截图？

**Comment by xingezhang** [comment]
![aria2](https://cloud.githubusercontent.com/assets/13484700/23340908/78102e0e-fc79-11e6-81a2-ade73b026017.PNG)

**Comment by acgotaku** [comment]
@xingezhang 
![screenshot from 2017-02-27 10-39-43](https://cloud.githubusercontent.com/assets/1191834/23346864/bbf2bd82-fc63-11e6-86cc-437ae4e620e7.png)

你点击那个测试连接试试

**Comment by acgotaku** [comment]
从界面上也看不出来  你的RPC地址 以及配置是否正确

**Comment by xingezhang** [comment]
我的配置正常下载没问题

**Comment by xingezhang** [comment]
是否因为不支持加密？

**Comment by acgotaku** [comment]
浏览器接管是YAAW插件的功能吧？ 你在说什么？？？ 大家时间都很宝贵

**Comment by xingezhang** [comment]
很抱歉占用了你宝贵的时间，我删除了

**Comment by xingezhang** [comment]
很抱歉占用了你宝贵的时间，我删除了
