### ISSUE TITLE
Edge中无法使用

### ISSUE THREAD

**Issue by zhg-em** [acgotaku/BaiduExporter#413]
插件下载地址：https://github.com/acgotaku/BaiduExporter
插件版本：Version:0.9.2 
系统版本：win10 pro 14393.726，Microsoft Edge 38.14393.0.0
按照说明在Edge中安装正常，但在百度云导出设置测试连接时没有反应。配置应该是正确的，在chrome中是正常的。

**Comment by acgotaku** [comment]
我其实没有Edge的测试环境。。。。 Edge的适配是另外一个同学做的。。。

**Comment by otakuchiyan** [comment]
可以用“导出下载”手动复制命令到 cmd 来下载（
