### ISSUE TITLE
老大,用最新版本下载速度只有10k 求助

### ISSUE THREAD

**Issue by chenfengfeng** [acgotaku/BaiduExporter#414]
<img width="900" alt="qq20170301-161721 2x" src="https://cloud.githubusercontent.com/assets/6957977/23451419/d029f700-fe9a-11e6-87e5-436cdf607438.png">
<img width="900" alt="qq20170301-161739 2x" src="https://cloud.githubusercontent.com/assets/6957977/23451431/e0db76be-fe9a-11e6-8699-9af1f4e53daa.png">
用 chrome 最新版本,插件也是最新的0.9.2
系统 Mac10.12.3

**Comment by acgotaku** [comment]
![screenshot from 2017-03-01 21-20-38](https://cloud.githubusercontent.com/assets/1191834/23461456/9f0be94e-fe4f-11e6-99fd-9d7d3e628681.png)


那我这个该怎么解释呢？ 你是分享界面导出还是 自己网盘？

**Comment by chenfengfeng** [comment]
分享界面直接导出,第一个选项,我也很无奈,不知道哪里出错

**Comment by acgotaku** [comment]
@chenfengfeng 保存到自己网盘 再下载
