### ISSUE TITLE
关于下载链接的问题

### ISSUE THREAD

**Issue by acgsky** [acgotaku/BaiduExporter#417]
菊苣大大，最近发现下载速度变慢了很多，简单调试了一下，发现是下载链接的问题。
好像从0.9.0版本开始就是用app_id的方式来获取下载链接。
下面是用app_id的方式获取的下载链接的下载速度，单线程被限制在了500KB/s左右,16线程最多到9MB/s左右。
![appid](https://cloud.githubusercontent.com/assets/26134597/23578841/b4281ee2-011a-11e7-8ea3-f83b824956a6.jpg)
下面是0.8.9版本用原始链接(包含sign等参数)的速度（单线程可以达到4-5MB/s，大概8个线程就可以达到物理带宽峰值26MB/s）。
![origin_all_speed](https://cloud.githubusercontent.com/assets/26134597/23578867/33d42a6e-011b-11e7-9f26-7e532c00128c.PNG)
很显然SVIP用户使用原始链接可以直接达到物理带宽峰值 ，用app_id的方式反而会成为拖累。
所以我想菊苣是不是加一个配置选项，默认使用app_id的方式获取下载链接，SVIP用户可以配置为使用原始下载链接的方式。

**Comment by acgotaku** [comment]
你们这些土豪会员。。。。真是够了！

**Comment by acgsky** [comment]
那菊苣到底是打算加还是不加?不加的话我先用0.8.9版本，等不能用了再说吧！

**Comment by acgotaku** [comment]
![screenshot from 2017-03-04 23-08-18](https://cloud.githubusercontent.com/assets/1191834/23579762/2038b6fc-00ba-11e7-8651-20198c95a0d7.png)

你在终端里输入 yunData  我看看 VIP 和 SVIP标签  还有 这俩级别会员有区别么？

**Comment by acgsky** [comment]
![aaa](https://cloud.githubusercontent.com/assets/26134597/23579793/08b52904-0130-11e7-8b92-7bce5e3d15a7.JPG)
SVIP会员不限速，非会员和会员都限速。

**Comment by acgotaku** [comment]
已更新

**Comment by acgsky** [comment]
不知道算不算是bug，加载扩展后，第一次导出是原始链接的模式。之后如果刷新页面，或者重新打开一个新的百度云页面，即便选中

> 我是SVIP会员

还是会导出app_id模式的链接。

解决办法是在配置面板再点一次

> 应用



补充说明，只有刷新或者重新打开页面后才会出现这种情况。
例如，A页面导出的是原始链接，刷新A页面，A页面导出的就是app_id形式的链接。如果不刷新A页面，打开B页面，那么A页面导出的仍然是原始链接，B页面导出的是app_id形式的链接。

另外，在分享页面（不保存到我的网盘），不管选中不选中

> 我是SVIP会员

导出的都是原始链接而不是app_id模式的链接。


 我看了一下LocalStorage里的svip值，刷新或者打开新页面
svip的值还是
> true

我对js和chrome也不是很熟悉，到底哪里出了问题我也不知道，麻烦菊苣大大看一下。

**Comment by acgotaku** [comment]
你的意思 是你勾了 SVIP 却不点击 应用？！ 不点击 应用怎么保存啊！ 又不是自动保存的。。。

**Comment by acgsky** [comment]
菊苣大大误会我的意思了。
我认为这个扩展的设计理念是，只要LocalStorage中SVIP的值是'true'，那导出的链接就应该是原始链接而不是app_id形式的链接。
而在实际操作的过程中就像我上面描述的，在第一次点击应用后，LocalStorage中的值变成'true'，导出的链接是原始链接。以后（例如刷新页面，关闭浏览器再打开等操作后）再导出，导出的链接就会变成app_id的形式（这期间并没有取消'我是SVIP‘的选项）。我想这应该算是个bug吧。
如果我现在的描述菊苣还不明白，那我录一段视频给菊苣大大。

**Comment by acgsky** [comment]
又调试了一下，发现原因了。
下面是第一次保存配置后
`LocalStorage的SVIP值` 以及`$("#svip").prop("checked")`，`localStorage.getItem("svip")` 两个函数的结果

![true](https://cloud.githubusercontent.com/assets/26134597/23585017/3de39606-01ad-11e7-9e21-cd734b098965.PNG)

可以看到`LocalStorage的SVIP值`，`$("#svip").prop("checked")`，`localStorage.getItem("svip")` 三者一致。


下面是刷新或者新建标签页（重新加载扩展）后的结果

![false](https://cloud.githubusercontent.com/assets/26134597/23585022/6ca1e5b0-01ad-11e7-98c2-3e452e056679.PNG)

可以看到`LocalStorage的SVIP值`，`ocalStorage.getItem("svip")`都是'true'，`$("#svip").prop("checked")`的结果变成了'undefined'
而在扩展中是用
`if ($("#svip").prop("checked"))`
来判断是否使用原始链接的。
所以我把
`if ($("#svip").prop("checked"))`
改成
`if (localStorage.getItem("svip") == 'true')`
后，导出的结果就正确了。

问题是为什么重新加载扩展后保存的变量会消失？我搜索了一下也没找到比较好的解释，不知道菊苣知不知道原因？

**Comment by acgotaku** [comment]
我知道原因了 是因为没点击按钮 不会初始化 菜单

**Comment by acgotaku** [comment]
修复 了

**Comment by acgsky** [comment]
好的，那我close了。
