### ISSUE TITLE
下载限速能否作为可配置项

### ISSUE THREAD

**Issue by luxin88** [acgotaku/BaiduExporter#419]
目前限速写死在1MB  ，但是通过尝试发现，限速10MB的话，一般可以达到5MB以上的速度，能否调高默认限速值，或者把限速项作为可配置

**Comment by acgotaku** [comment]
哪里写死的？？？

**Comment by luxin88** [comment]
[https://github.com/acgotaku/BaiduExporter/blob/master/chrome/src/core.js#L468](https://github.com/acgotaku/BaiduExporter/blob/master/chrome/src/core.js#L468)

**Comment by acgotaku** [comment]
![screenshot from 2017-03-07 22-02-56](https://cloud.githubusercontent.com/assets/1191834/23659693/95a853ee-030c-11e7-9ee1-57acb9021d84.png)

这个只是在小文件的情况下 不去分片下载而已吧。。。

**Comment by luxin88** [comment]
但是实际情况是，使用默认值，下载，速度一直在1MB/s以下，我手动改为10之后，有时候可以满速，平均在5MB/s左右，操作系统是mac，安装aria使用brew

**Comment by acgotaku** [comment]
那你就手动改好了。。。 证明不了这个参数是错误的。。。
