### ISSUE TITLE
错误,请查看是否开启Aria2

### ISSUE THREAD

**Issue by k1n** [acgotaku/BaiduExporter#42]
系统：MAC OS X 10.10.2
浏览器：Chrome 42.0.2311.68 beta (64-bit)
BaiduExporter: 0.3.4

点击“测试连接，成功显示版本号。”，返回“错误,请查看是否开启Aria2”。

调测窗口显示：
XMLHttpRequest cannot load http://192.168.31.1:6800/jsonrpc?tm=1427992093814. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://pan.baidu.com' is therefore not allowed access.

**Comment by acgotaku** [comment]
你这个明显是aria2c配置参数里没有加  rpc-allow-origin-all=true

**Comment by acgotaku** [comment]
@k1n 你的aria2c的版本号是多少？

**Comment by k1n** [comment]
@acgotaku  rpc-allow-origin-all=true，应该就是这个原因。
