### ISSUE TITLE
8号开始速度就没有了

### ISSUE THREAD

**Issue by googooog** [acgotaku/BaiduExporter#420]
似乎被封了，刚开始速度很快，几秒后没有速度，然后速度起来一点点，几秒后又没有速度

实验了好几个资源都是这样的问题

昨天使用满速没有问题

**Comment by R-L-T-Y** [comment]
同样的问题。还以为是升版本升坏了，checkout回之前working的版本还是一样的情况。

**Comment by LiHanGuang** [comment]
退出百度登录账号,刷新界面, 再下载:

1) 2G以上的文件下载才快...

2) 2G以下有点慢

3) 几十MB的超慢

**Comment by liudaliuda6** [comment]
@LiHanGuang 貌似不行，昨天测了过 15G 的 和 2G 的文件，症状都跟 @googooog 描述的一样。

**Comment by acgotaku** [comment]
我这边还能下载  试试进入设置页面 切换会员？

**Comment by LiHanGuang** [comment]
@liudaliuda6 

换换 IP 和 退出百度登陆账号试试?

另外 @acgotaku

请问百度那边的检测机制大改是怎么做的?, 我们可以采取某些手段规避(如清除cookie 换换IP之类的)吗?

**Comment by liudaliuda6** [comment]
@acgotaku 嗯，勾选和不勾选 SVIP 都不行了；
@LiHanGuang 换 IP 和 清cookie 也试过，也不行。

**Comment by latinpegasus** [comment]
失效了.

**Comment by acgotaku** [comment]
@LiHanGuang 我又不是百度的！大改我怎么知道。。。

**Comment by googooog** [comment]
@acgotaku @LiHanGuang 按照两位的设置后还是一样的情况，后来发现原因了

@liudaliuda6 换一个百度账号就好了，不知道是什么原因……同样的资源，A账号是我描述的情况，B账号下载没有问题，下载速度飞快……

这是什么原因啊

**Comment by zhongfly** [comment]
百度采用的是黑名单制度，机制不明，大流量下载的就会被加入到里面去。

**Comment by latinpegasus** [comment]
感覺很厲害的樣子！！！

**Comment by devAstr** [comment]
今天凌晨 自家
數個約1G檔案
下載0.20%就沒速度了
暫停後再下載同 每次都是剛好0.20%
不同大小也是

剛剛 台灣學術網路
百度帳號登出後登入再下載 約1.5G檔案
速度5M

**Comment by ZHL0147** [comment]
![image](https://cloud.githubusercontent.com/assets/26295323/23739251/8169f4c8-04d8-11e7-88a2-91d42450c5d7.png)
我的下载速度是锯齿型的……

**Comment by M1p0** [comment]
同样的问题. 切换过账号了 还是没用  插件也重装了

**Comment by BROBIRD** [comment]
@ZHL0147 一模一样

**Comment by hexianfu** [comment]
确实昨天开始速度就慢了！不稳定 而且很慢了

**Comment by GoGoogle** [comment]
百度玩不起就别玩网盘啊，真是恶心啊，动不动就开始限速。

**Comment by septingenti** [comment]
限速 is real! 气死了！！！

**Comment by acgotaku** [comment]
无意义的comment就不要再说了

**Comment by liudaliuda6** [comment]
@LiHanGuang @acgotaku 换了一个正常了。

**Comment by vitaminzz** [comment]
svip好几个服务器资源，普通的只能随机走一个

**Comment by vitaminzz** [comment]
一朋友提供svip走的域名
"yqall01.baidupcs.com","nj02all02.baidupcs.com","nj01ct02.baidupcs.com","allall01.baidupcs.com","allall02.baidupcs.com","yqall01.baidupcs.com","nj02all02.baidupcs.com","nj01ct02.baidupcs.com","allall01.baidupcs.com","allall02.baidupcs.com"

**Comment by chunyuy** [comment]
@liudaliuda6 我换了账号还是一样，sad，你除了换账号还进行别的操作了吗，比如清楚cookie之类的

**Comment by RouRouChina** [comment]
从今天下午开始就不行了。

单线程只能10K了，5线程50K，能把线程提高点不。。。

**Comment by wszgrcy** [comment]
百度又掌握了新的BAN技能,估计可能是IP地址或者机器码?我刚才下载了大概有30-40G就开始做过山车了.估计限速到最后就是每个费账号多少流量,没了的话10KB走起

**Comment by ddbxyrj** [comment]
游览器应无权限获取机器码 可能是由账号绑定完成

**Comment by liudaliuda6** [comment]
@chunyuy 一直隐身窗口登录的。话说昨晚主账号又正常了一阵子，这就尴尬了~

**Comment by Ldcr993519867** [comment]
linux aria2 1.18.1下载速度正常

另外提供一个可能有用的被10kb黑名单限速的脱离黑名单方法
一周别从百度网盘下东西,非要下载登出账号清掉cookies

我就是这么脱黑的

**Comment by wszgrcy** [comment]
@Ldcr993519867 可能就是一周清空一次数据.不管下不下载..........

**Comment by Fomovet** [comment]
同样问题，今天使用Mac下载速度才20K～～求解

**Comment by boy404** [comment]
这几天下载也是出现差不多情况，我用的是学校的网络，因此不可能限制整个学校的IP，所以只能通过限制账号和资源，百度网盘有一定的额度，超过这个额度才限速，因此通过更换账号，下载，或者清除cookie不要登录

**Comment by lingiori** [comment]
通过插件解析出来的url和账号有什么关系吗？通过aria2下载的时候也不绑定账号啊？

**Comment by LiHanGuang** [comment]
@acgotaku 

把此条 issue 关闭掉吧, 省的被人不停无意义的闲聊.


另外,  @之前评论的人和将要评论的人

百度限速跟此插件没有任何关系, 是百度服务器端那边的限制,  此插件作为终端是无能为力突破限制的,  所以继续问这个问题无意义....

**Comment by lingiori** [comment]
@LiHanGuang
并不觉得没有意义，百度服务端的限制也是靠http请求的参数来做的（猜测），那么这个请求的参数作为插件是可以修改的

**Comment by LiHanGuang** [comment]
@lingiori 

下面是插件导出地址的相关信息,  确定那个参数后,就不要再闲聊下去了...

http://pcs.baidu.com/rest/2.0/pcs/file?method=download&app_id=250528&path=%2Fmac%2FDiffMerge.4.2.1.1013.intel.stable.dmg	
 gid=a7b2b96c99c0fbe6
 out=DiffMerge.4.2.1.1013.intel.stable.dmg
 header=User-Agent: netdisk;5.3.4.5;PC;PC-Windows;5.1.2600;WindowsBaiduYunGuanJia
 header=Referer: http://pan.baidu.com/disk/home
 header=Cookie: BDUSS=E5EdGFNMHNhVzVpcG1XblNjUE9rdUdyYndnTG53MWpMT3NaZk5ialJvcEMtZUZZSVFBQUFBJCQAAAAAAAAAAAEAAADpkbMKbGloYW5zZXkAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEJsulhCbLpYd; pcsett=1489472415-30e5177d046a2b08846f40a3f900f83c

**Comment by BROBIRD** [comment]
@LiHanGuang 把你自己的BDUSS放出来真的大丈夫？

**Comment by wszgrcy** [comment]
个人无责任建议:可以通过建一个超小型服务器,里面有个超级会员的账号,然后通过访问服务器获得要下载的链接,但是估计时间一长可以针对特定账号BAN

**Comment by chunyuy** [comment]
可以把文件做个私密分享，然后清楚cookies，不登录下载

**Comment by wszgrcy** [comment]
6天前我说的下接近了50G,然后速度过山车了,今天发现又满速了,推测是一个星期内有流量限制,我在此期间没有清空cookie,该登陆照样登陆
