### ISSUE TITLE
插件无法启用，图标暗显

### ISSUE THREAD

**Issue by TheKiteRunning** [acgotaku/BaiduExporter#421]
你好，发起issue前已经完成4项要求，以下是相关信息：

1 希望使用aria2下载百度云文件，于是安装您这个插件，尚未下载。
2 插件版本0.95，chrome版本55.0.2883.87 m (64-bit)
3 因为crx不能直接安装，将后缀改为rar后解压加载，安装成功；但图标暗显，选项无效。

![image](https://cloud.githubusercontent.com/assets/24802332/23743792/f7ca0a18-04ec-11e7-8a6b-dacdd0c14507.png)

旁边的提示信息应该与插件无关，是flash的

![image](https://cloud.githubusercontent.com/assets/24802332/23743825/11bc5980-04ed-11e7-9df0-53f43d94557e.png)

另外，切换到cent browser 版本 2.4.2.19 (Chromium 56.0.2924.87),问题依旧.

烦请帮助,非常感谢!

**Comment by acgotaku** [comment]
这就是正常的。。。 无法启用的话 图标都没有。。。。

**Comment by TheKiteRunning** [comment]
爱死你了!
