### ISSUE TITLE
关于win10“Tips  不想每次开启Chrome都提示”

### ISSUE THREAD

**Issue by yilang0001** [acgotaku/BaiduExporter#422]
插件版本号0.95，浏览器版本号56.0.2924.87，系统版本号win10education1607

按照Tip步骤将ID添加whitelist打开chrome依旧会看到关闭开发模式插件的提示。
当时怀疑导入的ADM不是最新版本，于是在[Chrome for business and education Help](https://support.google.com/chrome/a/answer/187202?hl=en)下载最新版本。然后发现官方提供的有两种格式，分别为.adm和.admx。于是搜索这两格式区别和使用方式，偶然看到[Antony Hatchkins的回答](http://stackoverflow.com/questions/23055651/disable-developer-mode-extensions-pop-up-in-chrome)
步骤是：将ADMX文件夹中的chrome.admx，google.admx和对应语言包（"%SystemRoot%\PolicyDefinitions"出现的，我的是en-US与zh-CN）全部复制到"%SystemRoot%\PolicyDefinitions文件夹下，然后再将baiduexporter的id加入白名单。现在重启chrome不再会出现开发者插件的提示了。

**Comment by rule2c** [comment]
换成chromium浏览器，什么提示都不会有
