### ISSUE TITLE
下载出错

### ISSUE THREAD

**Issue by Vicriss** [acgotaku/BaiduExporter#423]
请确保以下几点：

1. 已经阅读过README
2. 尝试安装最新版本插件
3. 尝试清空浏览器缓存
4. 尝试卸载插件后重新安装

发起 Issue 时，请提供：

1. 下载的内容地址

> aria2c -c -s10 -k1M -x16 --enable-rpc=false -o '【更多免费考研资料分享请加QQ群：462233807】019.mp4' --header "User-Agent: netdisk;5.3.4.5;PC;PC-Windows;5.1.2600;WindowsBaiduYunGuanJia" --header "Referer: http://pan.baidu.com/disk/home" --header "Cookie: BDUSS=RaMlZDWWM1eFN6Qk5hcVFXejhKSVpCanFIU2N4M3haVkRJazdNQ0JKaXpadk5ZSVFBQUFBJCQAAAAAAAAAAAEAAAC7VckbX1ZpY3Jpc3MAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAALPZy1iz2ctYNW; pcsett=1489840954-f6768d6bb57967dffacd353785e3e4a4" "https://pcs.baidu.com/rest/2.0/pcs/file?method=download&app_id=250528&path=%2F2018%E8%80%83%E7%A0%94%2F%E3%80%90%E5%BC%BA%E5%8C%96%E7%8F%AD%E3%80%912017%E7%A0%94%E5%A4%A7%E8%80%83%E7%A0%94%E8%8B%B1%E8%AF%AD%E9%95%BF%E9%9A%BE%E5%8F%A5%E4%B8%93%E9%A1%B9%E3%80%9014%E8%AF%BE%E6%97%B6%E6%95%B0%E3%80%91%E3%80%90%E4%B8%BB%E8%AE%B2%EF%BC%9A%E9%99%88%E6%AD%A3%E5%BA%B7%E3%80%91%2F%E3%80%90%E6%9B%B4%E5%A4%9A%E5%85%8D%E8%B4%B9%E8%80%83%E7%A0%94%E8%B5%84%E6%96%99%E5%88%86%E4%BA%AB%E8%AF%B7%E5%8A%A0QQ%E7%BE%A4%EF%BC%9A462233807%E3%80%91019.mp4"

2. 插件版本号0.9.5，浏览器版本号Version 57.0.2987.98 (64-bit)，系统版本号Linuxmint 3.19.0-32-generic 
3. 列举出现问题的详细步骤
我没有aira2的ui界面,是在终端运行的,配置也是用的github提供的默认配置
4. 描述能否复现问题

> 03/17 20:45:26 [ERROR] CUID#7 - Download aborted. URI=https://pcs.baidu.com/rest/2.0/pcs/file?method=download&app_id=250528&path=%2F2018%E8%80%83%E7%A0%94%2F%E3%80%90%E5%BC%BA%E5%8C%96%E7%8F%AD%E3%80%912017%E7%A0%94%E5%A4%A7%E8%80%83%E7%A0%94%E8%8B%B1%E8%AF%AD%E9%95%BF%E9%9A%BE%E5%8F%A5%E4%B8%93%E9%A1%B9%E3%80%9014%E8%AF%BE%E6%97%B6%E6%95%B0%E3%80%91%E3%80%90%E4%B8%BB%E8%AE%B2%EF%BC%9A%E9%99%88%E6%AD%A3%E5%BA%B7%E3%80%91%2F%E3%80%90%E6%9B%B4%E5%A4%9A%E5%85%8D%E8%B4%B9%E8%80%83%E7%A0%94%E8%B5%84%E6%96%99%E5%88%86%E4%BA%AB%E8%AF%B7%E5%8A%A0QQ%E7%BE%A4%EF%BC%9A462233807%E3%80%91019.mp4
> Exception: [AbstractCommand.cc:351] errorCode=1 URI=https://pcs.baidu.com/rest/2.0/pcs/file?method=download&app_id=250528&path=%2F2018%E8%80%83%E7%A0%94%2F%E3%80%90%E5%BC%BA%E5%8C%96%E7%8F%AD%E3%80%912017%E7%A0%94%E5%A4%A7%E8%80%83%E7%A0%94%E8%8B%B1%E8%AF%AD%E9%95%BF%E9%9A%BE%E5%8F%A5%E4%B8%93%E9%A1%B9%E3%80%9014%E8%AF%BE%E6%97%B6%E6%95%B0%E3%80%91%E3%80%90%E4%B8%BB%E8%AE%B2%EF%BC%9A%E9%99%88%E6%AD%A3%E5%BA%B7%E3%80%91%2F%E3%80%90%E6%9B%B4%E5%A4%9A%E5%85%8D%E8%B4%B9%E8%80%83%E7%A0%94%E8%B5%84%E6%96%99%E5%88%86%E4%BA%AB%E8%AF%B7%E5%8A%A0QQ%E7%BE%A4%EF%BC%9A462233807%E3%80%91019.mp4
>   -> [SocketCore.cc:1015] errorCode=1 SSL/TLS handshake failure: The signature algorithm is not supported.
>

**Comment by acgotaku** [comment]
#不进行证书校验
check-certificate=false


缺少了这个参数

**Comment by Vicriss** [comment]
我用的就是你们提供的conf啊,里面有这个参数的

**Comment by acgotaku** [comment]
你用的命令行下载 没有生效这个参数

使用RPC下载应该没问题

**Comment by Vicriss** [comment]
我在命令行打开aria2c之后,就在百度网盘的导出下载选择aria2 rpc

**Comment by acgotaku** [comment]
启动参数是？

**Comment by Vicriss** [comment]
没加参数,就是直接打开
`aria2c`

**Comment by acgotaku** [comment]
你这样 姿势是不对的

`aria2c --conf /home/×××/.config/aria2/aria2.conf -D`

这样指定配置文件才行

**Comment by Vicriss** [comment]
我把配置文件放到${HOME}/.aria2/aria2.conf下了,启动时候是已经加载了的,不然也进不了rpc模式,然而我确实是进入了rpc模式

**Comment by acgotaku** [comment]
那你还是自己检查下吧。。。 问题确实是 证书参数。。。

**Comment by Vicriss** [comment]
好吧...

**Comment by DDoSolitary** [comment]
这不一定是证书参数的问题吧
就算是设置了不检查证书，TLS协议还是需要加密的，而看错误信息，应该是没有对应的加密库作为支持，应该是缺了什么库吧（`openssl`？）

**Comment by Vicriss** [comment]
刚chrome又推了一波更新,然后重新装了一下插件,现在可以用了2333333
