### ISSUE TITLE
似乎被限速了？

### ISSUE THREAD

**Issue by Stevenclc** [acgotaku/BaiduExporter#424]
下载的内容已经保存在自己的网盘里了，然后导出用IDM下载，下载速度只能到800K/s左右，上次用还能到6M/s，是不是被百度限速了。
　　我的系统版本是Win10 14393.693 插件版本是0.9.5 浏览器是Edge

**Comment by oosaber** [comment]
导出后怎么用idm下载啊 拖拽那个文件到idm不能下载啊

**Comment by Conan1985** [comment]
我这里也是和@Stevenclc 一样的情况。几天前还能达到6M/s，现在就只有几百K了。和IDM无关。
系统版本：macOS Sierra 10.12.3, 插件版本：0.9.5, 浏览器：Chrome

**Comment by leoatchina** [comment]
我也一样，macOS 10.11.6系统, 0.95版本，用的是1.30的aria2

**Comment by acgotaku** [comment]
速度问题是百度服务器做了限制 所以类似速度的issue 就不要再提了
我这边目前没有好的解决办法
