### ISSUE TITLE
百度云好像已经不限速了？

### ISSUE THREAD

**Issue by Fomovet** [acgotaku/BaiduExporter#425]
今天早上进行下载测试发现速度跟以前一样？
求解？8号以后下载速度一直20KB，今天居然下载那么多文件可以达到满速6M！
![image](http://oltfdm7e0.bkt.clouddn.com/QQ20170320-100100@2x.png)

**Comment by leoatchina** [comment]
我这里还是不行， 很慢

**Comment by acgotaku** [comment]
这种算问题么？？？ 这里又不是BBS。。。
