### ISSUE TITLE
与aria2 RPC的连接似乎不稳定

### ISSUE THREAD

**Issue by chris00789** [acgotaku/BaiduExporter#427]
插件版本号：0.9.5
浏览器版本号：chrome 57.0.2987.110 (64-bit)
系统：win7 SP1

现象：进入百度网盘后，在插件提供的“导出下载->设置”中输入我的RPC地址：http://token:Chris0o789@chris00789.asuscomm.com:6800/jsonrpc
及下载路径后，点击测试连接，少数情况能正确返回aria2版本号：1.29.0，但大多数情况下是：错误,请查看是否开启Aria2
而且导出下载时也会提示“下载失败，是不是没有开启aria2?”，但有时又能成功。
但我用http://aria2.me/webui-aria2访问控制台时，又每次都能连上。
不知是不是我路由器上装的aria2设置不对，还是网络环境不好。我的路由器是公网IP，没有做内网穿透。

**Comment by acgotaku** [comment]
你出错的时候看看控制台 有没有什么输出

**Comment by chris00789** [comment]
这是我点击测试按钮后控制台报的信息，似乎是只有我点击按钮的动作，并未看见有返回的信息。
即使在少数返回成功的情况下，控制台报的信息似乎也是一样的。
![default](https://cloud.githubusercontent.com/assets/26613766/24229564/09a95e96-0fb5-11e7-9743-ebbd14cf3457.png)

**Comment by acgotaku** [comment]
这个是正常的日志信息 可能是你的网络状况有问题吧。。。

**Comment by chris00789** [comment]
意思是我家里路由器所处的网络环境不太好吗？所以导致控制台和路由器的连接不稳定？

**Comment by acgotaku** [comment]
应该是这样的 要不然不会时好时坏的

**Comment by chris00789** [comment]
可是现在貌似我用导出链接的方式，在webui里直接添加链接也是各种不行。
刚随便试了一个磁力链接：magnet:?xt=urn:btih:4e58713665c2ca39f714b97ddcd1c5e5e4a057b9&dn=The.Great.Wall.2016.720p.KORSUB.HDRip.XviD.MP3-STUTTERSHIT&tr=http%3A%2F%2Ftracker.trackerfix.com%3A80%2Fannounce&tr=udp%3A%2F%2F9.rarbg.me%3A2710&tr=udp%3A%2F%2F9.rarbg.to%3A2710发现居然又可以，但百度网盘导出的就是不行
![default](https://cloud.githubusercontent.com/assets/26613766/24230648/1e0f0812-0fbb-11e7-8615-3ff4c4b6f6b7.png)

**Comment by acgotaku** [comment]
你这表述能力。。。

还有你的RPC地址我这边都连接不上去。。。

**Comment by chris00789** [comment]
我现在怀疑是否是我的ddns不稳定，印象中好像都对华硕自带的ddns反响不太好，我再看看

**Comment by acgotaku** [comment]
如果真有这个问题肯定会有很多人来发issue的。。。 所以你还是自己检查下吧

**Comment by guitoushayan** [comment]
前段时间时间连接确实不稳定，经常显示服务出错，0.95的插件 aria 2 最新的，win10 64位，chrome 也是最新的

**Comment by guitoushayan** [comment]
百毒好像会检测账户了，每个非会员的如果高速下载内容的话过一段时间速度就被限制了，完了转存到另一个账户上，同样的文件，同样的网络环境，速度又上来了，但是好像不如上一个版本速度快了，上一个版本可以满速

**Comment by acgotaku** [comment]
这个事情我早就知道了 但是人家服务器限制了 我没法突破 所以不要再说了 没有意义
