### ISSUE TITLE
在公网使用DDNS rpc时，提示下载成功，但是实际下载失败

### ISSUE THREAD

**Issue by physalis7** [acgotaku/BaiduExporter#430]
1、下载内容为百度云盘里的文件
2、插件0.85、0.9.5；浏览器Chrome49.0-56.0，系统版本xp、win7
3、在局域网内使用http://192.168.1.x:6800//jsonrpc或者http://动态域名:6800//jsonrpc时，可以正常下载；在公网上使用http://动态域名:6800//jsonrpc时，测试正常，可以正常显示“ARIA2版本为： 1.18.7”，导出下载也提示下载成功，但是实际是下载失败，下载目录中也没有任何临时文件产生。
本以为是aria2或者自身网络问题，但是chrome的迅雷离线Aria2插件无论是公网还是内网都能正常下载，有点不太明白问题出在哪里。
4、在多台电脑上均出现这个问题，可以复现

**Comment by acgotaku** [comment]
你可以录制个视频 或截图 复现下
