### ISSUE TITLE
能否支持aria2的rpc令牌？

### ISSUE THREAD

**Issue by lersh** [acgotaku/BaiduExporter#432]
我用的最新的0.9.5版本，发现设置里并没有设置rpc令牌的地方，为了安全起见我的aria2开启了tls和令牌，这些在Aria2 WebUI里都是提供可以设置的地方的。

**Comment by jim9606** [comment]
https://token:password@example.com:port/jsonrpc

**Comment by lersh** [comment]
并不能用，我没有密码，只有token，使用https://token@example.com:port/jsonrpc就是提示失败

**Comment by acgotaku** [comment]
你这个理解有问题。。。 如果token是123 那么你就写 https://token:123@example.com:6800/jsonrpc

**Comment by lersh** [comment]
非常感谢，这样设置成功了
