### ISSUE TITLE
[脑洞]或许多登录 cookie 可以突破限速

### ISSUE THREAD

**Issue by est** [acgotaku/BaiduExporter#434]
讨论一下，pan.baidu.com的限速应该是 per session的，用多个帐号同时登录，n 个不同的session 并发下载同一个文件应该可以突破限速。

如果是按帐号限速的，那么我们用10个不同的帐号的 session 来下载同一个文件呢？

**Comment by wszgrcy** [comment]
idm开32线程,发现每线程10KB,如果idm能支持更多的线程,那么也可以相当于破解了

**Comment by guliujian** [comment]
为什么不选择付费呢？

**Comment by lambdaq** [comment]
@guliujian 
付费了你还会用这个插件？

**Comment by guliujian** [comment]
刚才好像有个@我的，不过进来就不见了，但是付费了跟用不用插件没有什么关系啊，百度云盘并没有linux版啊，你可能不会去或者很少用，但我在Linux下只能这么用啊，懒得开一台windows只跑这个，包括之前mac没出的时候也得这么用啊。

**Comment by acgotaku** [comment]
想快速就付费  我只是做导出  不是做破解的

关于速度的问题不想太多讨论了

**Comment by lambdaq** [comment]
理解作者意思了。那这个 issue 关了吧
