### ISSUE TITLE
速度不行了

### ISSUE THREAD

**Issue by sandyplus** [acgotaku/BaiduExporter#435]
用baiduexporter配合aria2下载视频，以前可以达到1M/s，现在好像百度更新算法了，再怎么下载都是100-200k/s. 这个能解决吗？
请确保以下几点：

1. 已经阅读过README
2. 尝试安装最新版本插件
3. 尝试清空浏览器缓存
4. 尝试卸载插件后重新安装

发起 Issue 时，请提供：

1. 您下载的内容地址
2. 插件版本号，浏览器版本号，系统版本号
3. 列举出现问题的详细步骤
4. 描述能否复现问题

----------

**不符合上述条件的Issue将被无理由关闭**

**Comment by HarukaMa** [comment]
#424 #434

引用作者：
> 想快速就付费 我只是做导出 不是做破解的
>
> 关于速度的问题不想太多讨论了
