### ISSUE TITLE
添加插件以后是灰色的，用不了

### ISSUE THREAD

**Issue by ThomasLiaoQian** [acgotaku/BaiduExporter#436]
请确保以下几点：

1. 已经阅读过README
2. 尝试安装最新版本插件
3. 尝试清空浏览器缓存
4. 尝试卸载插件后重新安装

发起 Issue 时，请提供：

1. 您下载的内容地址
2. 插件版本号，浏览器版本号，系统版本号
3. 列举出现问题的详细步骤
4. 描述能否复现问题

----------

**不符合上述条件的Issue将被无理由关闭**

**Comment by acgotaku** [comment]
你这说的等于没说。。。。

**Comment by weqeo** [comment]
chrome上已经用不了，变成灰色的了，请问怎么搞才行。。

**Comment by Xwai** [comment]
不要用crx，在chrome扩展程序里选择`加载已解压的扩展程序...`，选择`BaiduExporter/chrome/`文件夹就好了

**Comment by R-L-T-Y** [comment]
Guide on Packaging and Import Baidu Exporter to Chrome

这个链接只适用于crx啊

**Comment by acgotaku** [comment]
@R-L-T-Y 是 的
