### ISSUE TITLE
Safari 10 没办法用？

### ISSUE THREAD

**Issue by ElfSundae** [acgotaku/BaiduExporter#438]
Safari 10 下无解还是需要额外做什么？

**Comment by ElfSundae** [comment]
Maybe I should ping @Cee 😈

**Comment by Cee** [comment]
Safari 作为一个安全性比较高的软件...现在插件模式下不支持获取 *.baidu.com 下的 cookie 内容，所以插件用不了...

可以尝试使用 Chrome 的，等有机会或者其他方法再来做 Safari 这部份事情。

**Comment by ElfSundae** [comment]
OK, Thanks!
