### ISSUE TITLE
提示获取验证码失败

### ISSUE THREAD

**Issue by Gizeta** [acgotaku/BaiduExporter#439]
![default](https://cloud.githubusercontent.com/assets/1572561/25951264/bb9ae6b4-368f-11e7-94b9-701584f76fdc.png)

看样子是 https://github.com/acgotaku/BaiduExporter/blob/master/chrome/src/share.js#L263 漏掉了`window.location.origin`？

**Comment by acgotaku** [comment]
这么一说还真是

**Comment by acgotaku** [comment]
已修复
