### ISSUE TITLE
token secret doesn't work for me

### ISSUE THREAD

**Issue by lightingland** [acgotaku/BaiduExporter#44]
aria2启用token，客户端为webui-aria2正常连接，但是云盘导出到aria2失效（前一版是正常的）。
提示为：下载失败！是不是没有开启aria2？

我的RPC填写 http://token:xxxx@192.168.1.1:6800/jsonrpc
（xxxx为11位数字）
其余不改

**Comment by acgotaku** [comment]
@lightingland  aria2c版本号多少？

**Comment by lightingland** [comment]
@acgotaku 1.18.10发布以后的某个thunk自行编译。会是这个原因吗？

**Comment by acgotaku** [comment]
@lightingland 出现错误提示的时候，你按F12看看Console里面有没有异常输出？

**Comment by lightingland** [comment]
看到原因了，rpc-allow-origin-all=true这一项没加，不知为何前一版是成功的。感谢

**Comment by acgotaku** [comment]
@lightingland 可能这一版默认参数变了吧
