### ISSUE TITLE
error resource was not found. 

### ISSUE THREAD

**Issue by kirorow** [acgotaku/BaiduExporter#440]
1. 您下载的内容地址
http://pan.baidu.com/s/1czpBYY
2. 插件版本号，浏览器版本号，系统版本号
Aria2 1.31.0
Exporter 0.9.5
58.0.3029.110 (64-bit)
Windows [Version 10.0.14393]
3. 列举出现问题的详细步骤
尝试在百度网盘导出下载大型文件，在开始几秒有速度后会失败，提示error resource was not found. See-lowest -speed-limited option
4. 描述能否复现问题
重装插件不能解决问题
把lowest -speed-limited从0改成1不能解决问题
一个猜想，我的帐号是否已被baidu拉黑

**Comment by acgotaku** [comment]
这种情况下你可以退出登录来下载

我这边下载正常。。。

**Comment by kirorow** [comment]
problem solved, 果然是被拉黑~
退出后一切正常，可顶速下载，感谢~

**Comment by oosaber** [comment]
请问是先登陆下载内容 然后再退出 还是分享后退出 下载分享内容？

**Comment by kirorow** [comment]
我現在是不登陸，直接下載的

**Comment by oosaber** [comment]
那就是下载分享的内容？

**Comment by chengluyu** [comment]
今天遇到了同样的问题，同样使退出账号后就可以继续下载了。@acgotaku 我身边也有人遇到此问题，考虑一下要不要写进 README 里？
