### ISSUE TITLE
无限导出的问题

### ISSUE THREAD

**Issue by zhangyubaka** [acgotaku/BaiduExporter#441]
请确保以下几点：

1. 已经阅读过README
2. 尝试安装最新版本插件
3. 尝试清空浏览器缓存
4. 尝试卸载插件后重新安装

发起 Issue 时，请提供：

1. 您下载的内容地址
2. 插件版本号，浏览器版本号，系统版本号
3. 列举出现问题的详细步骤
4. 描述能否复现问题

----------

**不符合上述条件的Issue将被无理由关闭**

插件直接拉的 Github 代码。
插件 0.9.5 Chrome  58.0.3029.110 64bit
出现问题：
打开一个百度网盘页面，点击导出下载->导出下载，显示 aria2c 命令的框会生成许多链接
或者生成许多验证码。
可稳定复现

**Comment by acgotaku** [comment]
你倒是给个分享的网盘链接啊 QAQ

**Comment by zhangyubaka** [comment]
我直接在 pan.baidu.com 下载自己的文件也会这样啊
雪月秋水 <notifications@github.com>于2017年5月18日 周四下午9:03写道：

**Comment by acgotaku** [comment]
@zhangyubaka 自己网盘没这毛病啊。。。

**Comment by zhangyubaka** [comment]
今天症状消失...
雪月秋水 <notifications@github.com>于2017年5月19日 周五下午9:48写道：

**Comment by acgotaku** [comment]
2333333333333333333333
