### ISSUE TITLE
问题反馈

### ISSUE THREAD

**Issue by zhaoqianganhei** [acgotaku/BaiduExporter#442]
@acgotaku 能否增加百度云企业版网盘的支持
gxvv制作的EX-百度云盘油猴脚本可以在企业版使用，能否参考他的思路
https://greasyfork.org/zh-CN/scripts/26638-ex-%E7%99%BE%E5%BA%A6%E4%BA%91%E7%9B%98

**Comment by acgotaku** [comment]
此项目不再添加新功能。。。
