### ISSUE TITLE
下载链接中无法识别文件名，批量时搞不清楚哪个是哪个了

### ISSUE THREAD

**Issue by walkthetalk** [acgotaku/BaiduExporter#443]
请确保以下几点：

1. 已经阅读过README
2. 尝试安装最新版本插件
3. 尝试清空浏览器缓存
4. 尝试卸载插件后重新安装

发起 Issue 时，请提供：

1. 您下载的内容地址
2. 插件版本号，浏览器版本号，系统版本号
3. 列举出现问题的详细步骤
4. 描述能否复现问题

----------

**不符合上述条件的Issue将被无理由关闭**

**Comment by acgotaku** [comment]
??? 不是吧 你连个例子都不说。。。

**Comment by walkthetalk** [comment]
https://pan.baidu.com/s/1hrTW560#list/path=%2F2017%2F2017-06%2F2017-06-06%2F3DMGAME-TEKKEN.7.Deluxe.Edition.Cracked-BALDMAN&parentPath=%2F2017%2F2017-06%2F2017-06-06

拷贝链接到迅雷里面后，发现文件名是一串英文加数字，发现链接中没有文件名，虽然能下载，但是下载多个文件时，重命名就比较费劲了，尤其是分卷压缩包。

**Comment by acgotaku** [comment]
你这样直接拷贝肯定是不行啊 aria2c指定了文件名的

**Comment by walkthetalk** [comment]
关掉吧
