### ISSUE TITLE
怎样才能在firefox不用重复加载过程

### ISSUE THREAD

**Issue by wsgdlhy** [acgotaku/BaiduExporter#444]
每次打开firefox都要重复这个过程：
Firefox : Open about:debugging in Firefox, click "Load Temporary Add-on" and navigate to the chrome folder, select manifest.json, click OK.
怎样才可以不用重复加载？

**Comment by acgotaku** [comment]
https://github.com/acgotaku/BaiduExporter/issues/437

用这个

**Comment by wsgdlhy** [comment]
非常感谢！！！
