### ISSUE TITLE
关于速度的问题

### ISSUE THREAD

**Issue by troyliu0105** [acgotaku/BaiduExporter#445]
发现清空Referer和User-Agent等各种Header参数，速度就恢复了。。。

额。。。会被直接关掉么，whatever 😃

**Comment by acgotaku** [comment]
你能详细的举个例子么？

**Comment by troyliu0105** [comment]
偶然发现的。
家里的带宽是100M的
最开始任何文件的速度都锁定在了50k左右。
但是直接拷贝下载链接去aria2下载的话，速度在700k/s到3M/s。使用导出的命令行，去除Cookie，User-Agent和Referer等header参数后也是类似的。

后来发现，清空设置里面的Referer和User-Agent，好像并没有用，保存，刷新后又回来了==

![2017-06-11 10 37 44](https://user-images.githubusercontent.com/5518286/27007789-14204a30-4e92-11e7-840e-185b3a6866a3.png)
![2017-06-11 10 36 56](https://user-images.githubusercontent.com/5518286/27007790-19fe484e-4e92-11e7-835a-0ac03b22ccbb.png)

第一张是带了header参数，第二张是没有的。
不知道其他人那边会有类似的效果么？还是只是这边的网络因素

**Comment by acgotaku** [comment]
你是在分享页面 还是自己网盘页面？？

**Comment by troyliu0105** [comment]
额。。。是在分享界面

**Comment by acgotaku** [comment]
我就说。。。 分享页面的话 私密分享 肯定要cookie的

不过我试了下 正常也有几百k的

**Comment by troyliu0105** [comment]
你是指，下载私密分享的话，必须带有Cookie参数么？

**Comment by acgotaku** [comment]
恩  这个修改意义不大 个人意见

**Comment by troyliu0105** [comment]
原来如此，thx。。。另外，在分享界面下修改设置（比如清除UA，和Referer）依然无效，刷新后又恢复原来的样子了。好像以前也有类似的问题（之前是无法保存rpc url）

**Comment by troyliu0105** [comment]
额。。。在个人网盘界面也是一样的，请问这是什么情况呢？

**Comment by acgotaku** [comment]
为空的时候 会设置默认值  你可以填一些非法数据就是了。。

**Comment by acgotaku** [comment]
因为这俩个地方都是复用的同一个设置啊。。。当然一样
