### ISSUE TITLE
问题反馈

### ISSUE THREAD

**Issue by hweining** [acgotaku/BaiduExporter#446]
1.chrome extension下载地址失效，无论是少数派还是你博客里的链接地址
https://chrome.google.com/webstore/detail/baiduexporter/mjaenbjdjmgolhoafkohbhhbaiedbkno
[](https://chrome.google.com/webstore/detail/baiduexporter/mjaenbjdjmgolhoafkohbhhbaiedbkno)
2.aria2c --conf-path="/Users/xxxxxx/.aria2/aria2.conf" -D ，已经使用绝对路径还是失败。

**Comment by acgotaku** [comment]
早就失效了啊。。。。

**Comment by zelda0079** [comment]
楼上早说了直接在这边下载......
