### ISSUE TITLE
aria2c 下载一直间接来个0KB，然后速度提上去又降到0KB

### ISSUE THREAD

**Issue by linjikai** [acgotaku/BaiduExporter#447]
![image](https://user-images.githubusercontent.com/21253413/27279734-251c2264-5518-11e7-87af-fe073eeab7c2.png)

我觉得作者一定有什么隐藏的conf，来吧。。帮我解决它，我不想看到0KB了

**Comment by linjikai** [comment]
另外补充一点，我用的是最新版的。1.32

**Comment by acgotaku** [comment]
.... 我是欠你的啊。。。  你这一脸大爷的说话方式。。。

**Comment by linjikai** [comment]
有这么明显吗？我以为我隐藏得很好了。

那………………求求你了~~求你了~

**Comment by conanwhf** [comment]
忍不住了，楼上的有毛病！

**Comment by FradSer** [comment]
22333 @linjikai 有点搞笑。
这个问题，我这里也有。
希望谁能解决一下。
------------------------
可以看看[这篇文章](https://www.drupal.org/issue-queue/how-to "How to create a good issue")，如果做不到至少尊重一下别人。

**Comment by AnClark** [comment]
楼上这位@FradSer，我理解你，可以参透你给别人发这种文章的用意，但是总觉得你这个行为值得商榷。

**Comment by jostyee** [comment]
Don't feed the troll.

**Comment by AnClark** [comment]
@jostyee 我特地查了一下这句英文俗语，也理解了您的意思。不过不是所有人都懂这句俗语的。而且这个项目的开发者和使用者都是华人。
I checked this slang on Google, and comprehended what you wanna say to me. But this project is a Chinese project. I am afraid that others may not comprehend such a slang.

**Comment by AnClark** [comment]
> 对于我在先前的评论中指出的那个问题，我只是就事论事，并不是针对任何人。
---
当然对于这个issue提问者的问题，我持反对意见。开发者开发这款软件，旨在让用户能获取百度网盘中资源的下载地址，但并不对下载的稳定做出保证。这一点Acgotaku大大在以往的issue中都有明确提到过，提问者如果对我的解释不满意，先翻翻这个项目的issue列表吧。
