### ISSUE TITLE
能在 【拷贝下载链接 】 拷出来的链接添加-o 文件名吗？ 

### ISSUE THREAD

**Issue by ystyle** [acgotaku/BaiduExporter#448]
能在 【拷贝下载链接 】 拷出来的链接添加 【--out 文件名】 吗？ 现在好多下载的文件名都是一串数字

**Comment by acgotaku** [comment]
正如意思所说 是拷贝的链接。。。 所以没有文件名
对于只想简单下载的用户来说很方便

**Comment by ystyle** [comment]
呃，那再加个按钮？😂

**Comment by acgotaku** [comment]
没必要啊 软件又不是为了你一个人开发的。。。 想要文件名就直接从文本框拷贝就是了

**Comment by ystyle** [comment]
主要是文件太多了。。。这怎么设置token ？

**Comment by acgotaku** [comment]
那干嘛不直接RPC下载。。。

**Comment by ystyle** [comment]
没看到哪有设置token或用户信息的地方。。。

**Comment by acgotaku** [comment]
Set --rpc-secret=<secret> if you are using aria2 1.18.4(or higher) with 'JSON-RPC PATH' like http://token:secret@hostname:port/jsonrpc
Set --rpc-user=<username> --rpc-passwd=<passwd> if you are using aria2 1.15.2(or higher) with 'JSON-RPC PATH' like http://username:passwd@hostname:port/jsonrpc
Use http://localhost:6800/jsonrpc#max-connection-per-server=5&split=10 set download options for specific file.

你有好好读readme么！！！
