### ISSUE TITLE
Chrome 59,chrome://plugins页面被移除，已经不能用现有的办法导入插件了

### ISSUE THREAD

**Issue by arcbishopw** [acgotaku/BaiduExporter#449]
浏览器版本chrome 59.0.3071.115，已经没有插件管理页面，不能导入插件或者开启插件了qwq

**Comment by acgotaku** [comment]
chrome://extensions

是这个才对吧？

**Comment by arcbishopw** [comment]
惊了，搜到一堆chrome://plugins的回复。。感谢菊苣回答这个没营养的问题qwq
