### ISSUE TITLE
近期百度限速的一些解决办法

### ISSUE THREAD

**Issue by giveup** [acgotaku/BaiduExporter#45]
百度限速越来越厉害了，限速没所谓，反正是挂机下载。关键是经常出错中断了下载。
![qq20150429-1](https://cloud.githubusercontent.com/assets/2897585/7383811/7fdebbc2-ee58-11e4-98e6-a1acb47f9a15.png)
依样画葫芦，把插件里面的ua改成“netdisk;5.2.6;PC;PC-Windows;6.2.9200;WindowsBaiduYunGuanJia”
也没用。最后突然想起，我的aria2也设置了ua欺骗，再yaaw里改成526的ua，马上全速下载。
结论，aria2的ua设置优先于拓展导出时的设置。

**Comment by acgotaku** [comment]
@giveup 老版本的百度云UA不行了 是么 我回去测试

**Comment by acgotaku** [comment]
@giveup 测试了一下 果然是的 我更新版本 更改下默认UA好了

**Comment by acgotaku** [comment]
@giveup 已经更新了 重置下插件就行了

**Comment by giveup** [comment]
@acgotaku firefox版0.3.5无法加载插件。
很奇怪，使用之前的版本时，偶尔也会出现插件加载不了的情况，只要刷新几次就能解决。
0.3.5反复测试，没有一次成功出现导出按钮。
还好留着0.3.4，把0.3.5卸载了，完全关闭firefox，重新安装0.3.4就能加载插件了。
按理说0.3.5只是更新了ua，什么也没动，不会弄的加载不了才对。
但我反复测试了就是这样。
firefox beta 38.0，最近只是更新了beta8和beta9，难道是firefox自己的原因？

**Comment by acgotaku** [comment]
@giveup 晚上回去看看

**Comment by blowaway** [comment]
Firefox 下 0.3.5 版确实刷不出按钮，试了好多次，Linux和win下都不行。期待解决一下，非常感谢！

**Comment by jiayiming** [comment]
我试下来aria2的UA改不改都一样   只改扩展UA后大概1.2~1.4m左右速度。。

**Comment by acgotaku** [comment]
@giveup  0.3.5版本的BUG已经修好了

**Comment by acgotaku** [comment]
@blowaway 0.3.5修好啦～

**Comment by Dereshi** [comment]
我只想问，如果买渣度的会员，但是依然用aria2的方式下载，服务器的api能够识别账户的vip的级别从而跑满带宽吗？其实价格真心不贵

**Comment by acgotaku** [comment]
@Dereshi 115的会加速 但是百度的应该不会

**Comment by Dereshi** [comment]
@acgotaku 这个结论是怎么推测的呢？另外求推荐115会员的经济获取姿势，以及115的加速到底能达到什么程度，能跑慢物理带宽吗？（100M光纤达到11、12m/s这样）

**Comment by acgotaku** [comment]
@Dereshi  115非会员限速 我是20M宽带 115会员可以满速下载 2.5m/s左右 百度非会员也是满速下载

115会员肯定是去 某宝充值啦 据说20元一年。。。

**Comment by Dereshi** [comment]
你用的什么UA设置才能做到百度满速？我试过很多，包括4.6.2，5.6.2的云管家，以及mac的，都只能1m/s左右的速度

雪月秋水 <notifications@github.com>于2015年5月9日星期六写道：

**Comment by acgotaku** [comment]
@Dereshi 刚才测试了一下 发现确实限速了 最多1m...115可以跑到2m  不知道充值会员会不会有效果

**Comment by cwbsw** [comment]
@acgotaku 115非会员也经常是2MB的速度呀。

**Comment by acgotaku** [comment]
@cwbsw  我自己物理带宽也就 2m... 所以我也不好测试了

**Comment by cwbsw** [comment]
@giveup 你的这种情况是否是因为下载速度慢导致链接超时失效了？百度的下载链接有时间限制，到时间了你还没下完就出错了。

**Comment by Dereshi** [comment]
@acgotaku 我亲身测试的结论，115网盘的会员毛用都没有，大家不要上当了

**Comment by acgotaku** [comment]
@Dereshi 政策又改了么。。。我当年非会员  只有200k的速度。。。

**Comment by giveup** [comment]
@Dereshi 我自己的测试情况。20m基本跑满。
当然不同地区网络情况不一样，例如到百度下载服务器的速度等，
可以参考一下[这里](https://github.com/PeterDing/iScript/wiki/%E8%A7%A3%E5%86%B3%E7%99%BE%E5%BA%A6%E7%BD%91%E7%9B%98%E4%B8%8B%E8%BD%BD%E9%80%9F%E5%BA%A6%E9%97%AE%E9%A2%98)的说明。

**Comment by gz0007** [comment]
貌似直接115浏览器上的客户端下载已经离线好的资源也限速了，我昨晚试过，我是充了年费vip的

**Comment by gz0007** [comment]
对了，那115网盘的插件设置又如何修改好呢？想试试看如果修改过之后看速度回复正常没有

**Comment by acgotaku** [comment]
@gz0007 115的话不是UA限制的吧？

**Comment by gz0007** [comment]
115网盘从上星期开始已经出现好像百度网盘一样的下载速度慢，而且时间限制，到一定时间就出错下载不了，要手动断点续传才行，对于经常要下载20几G起步的remux等资源的我来说，简直是不能忍受，况且我已经是通过淘宝充值到vip了

**Comment by gz0007** [comment]
我也不知道是否是ua造成的限制，我刚才也用百度网盘aria2插件设置按你的教程修改ua，发现下载速度仍然没有改观，不知道是什么原因了，当然，我百度的账号是免费的。

**Comment by gz0007** [comment]
对了，我发现现在115浏览器官方已经升级到5.2.1.45版了，不知道ua修改到这个版本有没有帮助呢？

**Comment by gz0007** [comment]
![qq 20150520101343](https://cloud.githubusercontent.com/assets/3072477/7717744/ed04fcee-fed8-11e4-9167-fc02401f66e1.png)
看来还是会限速的，200k以内速度

**Comment by acgotaku** [comment]
@gz0007 百度的话首先重置下插件 UA就自动更新了 然后再进行其它设置 115的话我回去再实际测试测试
你发的图是 115还是百度？

**Comment by gz0007** [comment]
刚才的图是115网盘已经离线完毕的资源

**Comment by gz0007** [comment]
对了，你说的重置插件就是在ua那里修改再保存就行了？

**Comment by acgotaku** [comment]
@gz0007 百度网盘 默认的UA已经保存在插件里了 所以重置下就是最新的UA了

**Comment by gz0007** [comment]
明白，我刚才也就是在ua上按你的上面的修改内容复制粘贴过去，最后保存，不过效果出来也是一样，不知道其他人是不是这样子

**Comment by Dereshi** [comment]
115的教育网下载速度就是很慢的，如果是电信，没有限速的问题，假期在家里的100M电信网上试过，7M/s~12M/s
http://www.v2ex.com/t/189966#reply7

在 2015年5月20日 上午10:31，gz0007 <notifications@github.com>写道：

**Comment by giveup** [comment]
@Dereshi @gz0007 我是电信。没vip，下载就是这个速度。（ua是百度云的。）
另外说一句题外话，下载这个本来就是盗版，还花钱买速度下载。有钱任性？
要么低调下载盗版，要么高调花钱正版。这个和打着团购的名义去买一些软件的授权（如alfred）
实际上那是Family License，和盗版没多大区别。
以上，如有冒犯，请多包涵。

**Comment by gz0007** [comment]
xx特色xx主义@giveup

**Comment by acgotaku** [comment]
@gz0007  115我是 VIP可以跑满自己20M带宽 百度云 不是会员 用插件默认的UA 还是可以跑满的
我是电信网络 不知道你的是什么问题？ 你是百度云和115下载都是200k？
