### ISSUE TITLE
被百度限速到50KB速度了，非常稳定，怎么都是50KB，求解

### ISSUE THREAD

**Issue by zjhong** [acgotaku/BaiduExporter#451]
请确保以下几点：

1. 已经阅读过README
2. 尝试安装最新版本插件
3. 尝试清空浏览器缓存
4. 尝试卸载插件后重新安装

如上都已经尝试过

发起 Issue 时，请提供：

1. 您下载的内容地址
https://pan.baidu.com/s/1boX6Mdx
2. 插件版本号，浏览器版本号，系统版本号
aria2/1.18.8/Chrome59/Windows 10 最新/BaiduExplorter2017年7月20日最新gitClone
3. 列举出现问题的详细步骤
下载后，速度被限制在了50KB
4. 描述能否复现问题
每天都这样

----------

**不符合上述条件的Issue将被无理由关闭**

**Comment by Explorare** [comment]
退出百度云账号再导入任务。

**Comment by ElfSundae** [comment]
@Explorare 求教：如果是下载自己网盘的资源，退出后怎么导入？

**Comment by Explorare** [comment]
先获取分享链接, 退出登录后打开分享页面.

Sent from my BlackBerry - the most secure mobile device

**Comment by ElfSundae** [comment]
谢谢。希望有更简单的方式..

Best Regards,
---------------------
Elf Sundae
http://0x123.com

**Comment by acgotaku** [comment]
@ElfSundae 最简单的方式就是充钱

**Comment by Kyle-Kyle** [comment]
@acgotaku 更好的方式是在发包时删除cookie。包发出去以后恢复cookie。

**Comment by Kyle-Kyle** [comment]
@acgotaku 因为网盘客户端的优化不是太好。有时候svip也会被限速（优化问题）。

**Comment by acgotaku** [comment]
速度问题我已经重申了好多遍 不属于本插件职责范围之内
