### ISSUE TITLE
edge 无法使用

### ISSUE THREAD

**Issue by weiyideai520** [acgotaku/BaiduExporter#452]
Microsoft Edge 40.15063.0.0
Microsoft EdgeHTML 15.15063
插件版本：Version:0.9.4 更新日期: 2017/03/05
导出下载：aria2c -c -s10 -k1M -x16 --enable-rpc=false -o "救世.Salvation.S01E02.720p.HDTV.X264.双语字幕精校版-深影字幕组.mp4" --header "User-Agent: netdisk;5.3.4.5;PC;PC-Windows;5.1.2600;WindowsBaiduYunGuanJia" --header "Referer: http://pan.baidu.com/disk/home" --header "Cookie: " "https://pcs.baidu.com/rest/2.0/pcs/file?method=download&app_id=250528&path=%2F%E6%95%91%E4%B8%96.Salvation.S01E02.720p.HDTV.X264.%E5%8F%8C%E8%AF%AD%E5%AD%97%E5%B9%95%E7%B2%BE%E6%A0%A1%E7%89%88-%E6%B7%B1%E5%BD%B1%E5%AD%97%E5%B9%95%E7%BB%84.mp4"

现象：点击aria2 后，显示：正在获取下载地址... 然后就没有然后了

**Comment by acgotaku** [comment]
是 RPC模式？

**Comment by weiyideai520** [comment]
是的，是不是不能这样啊，我已经换回 chrome，使用正常。

**Comment by acgotaku** [comment]
EDGE我暂时不好维护。。。
