### ISSUE TITLE
分享页面 转存报错

### ISSUE THREAD

**Issue by acgotaku** [acgotaku/BaiduExporter#454]
mod_6f61578.js:1 Uncaught Error: Cannot find module `common:widget/moveSaveDialog/moveSaveDialog.js`

转存插件出错 请求 @CnSimonChan 菊苣支援～

**Comment by CnSimonChan** [comment]
最近有些忙，明天会尽量找点时间研究下。

**Comment by acgotaku** [comment]
@CnSimonChan 社畜之后都忙了 QAQ 我准备抽时间全部用es6 重构了吧。。。

**Comment by CnSimonChan** [comment]
主要的逻辑在 [这个文件](http://s1.pan.bdstatic.com/box-static/disk-share-cdn/widget/plugin/shareFileSave/util/transferFilesService_07bb33b.js)。

整个复制到 `convert.js` 里，替换掉旧的 hook，然后修改 `serviceInit` function 接上原来的转存逻辑应该就可以了。

最近比较忙，如果可以的话你弄一下，我还不知道什么时候能空下来。

**Comment by acgotaku** [comment]
@CnSimonChan 辛苦！
