### ISSUE TITLE
为什么会显示两个上传按钮？

### ISSUE THREAD

**Issue by shikkoku** [acgotaku/BaiduExporter#455]
![capture](https://user-images.githubusercontent.com/4697177/28752778-17756f50-755a-11e7-94e2-b279ccd23065.JPG)

Chrome Version 61.0.3163.14 插件版本 0.9.5 （在Github刚下载打包的）。未启用其他百度盘相关的其他脚本。

**Comment by acgotaku** [comment]
这个神奇的BUG也没影响功能 所以就没分析 而且这个上传按钮偶尔出现俩

**Comment by shikkoku** [comment]
😂 我这里经常会出现俩，偶尔才不会出现。

**Comment by acgotaku** [comment]
有人提 （被我关了

**Comment by zelda0079** [comment]
不影响使用就没差

**Comment by acgotaku** [comment]
主要是逆向百度代码太费劲 而且修了也没啥收获。 。。

**Comment by acgotaku** [comment]
最新版本已经修复这个问题
