### ISSUE TITLE
md5 error

### ISSUE THREAD

**Issue by qweaszxcdf** [acgotaku/BaiduExporter#457]
https://pan.baidu.com/s/1geJlFG3#42pm
作者提供的MD5: 6E0A9B56A008A00F79E132A3D44147FA
baiduexporter获取的md5 1cdf1ffa42f6929b4a1085cc11cd2dc7
但实际下载后 文件md5与作者所提供的相同

**Comment by acgotaku** [comment]
那你关掉校验不就好了 ==

**Comment by qweaszxcdf** [comment]
关键在于baiduexporter获取的md5是否为文件真实的md5

**Comment by acgotaku** [comment]
关键这是依据百度的API。。。

**Comment by qweaszxcdf** [comment]
https://www.v2ex.com/t/222296
仅供参考

**Comment by Explorare** [comment]
今天遇到了同样的问题，开了校验之后发现部分下载失败。比如这张专辑 
`6ZO+5o6l4oCJOiBodHRwOi8vcGFuLmJhaWR1LmNvbS9zLzFtaVIwOGVXIOWvhueggeKAiTogMjloNQ==`
同时提供了压缩档和未压缩的文件夹，我全部下载后发现其中未压缩的 ISO 档案和 WAV 档案都校验失败了，然而和压缩包里的档案比较，WAV 档案的 HASH 值是一致的，也就是说实际上根本没损坏。而 ISO 档案确实损坏了，HASH 不一致。

那么问题就来了，这个 MD5 校验功能是否可靠呢？虽说这是百度的 API 就是了。

**Comment by acgotaku** [comment]
@Explorare 不可靠就在选项里关掉就是了 正是因为不可靠 所以我才不默认开启。。。

**Comment by Explorare** [comment]
可惜很多人意识不到百度云容易坏档的问题，也不加 parchive，没法检测完整性和修复，除非用了带恢复记录的 RAR 压缩档。
