### ISSUE TITLE
能否在更新代码的时候顺带重新打包一下crx?

### ISSUE THREAD

**Issue by tofuliang** [acgotaku/BaiduExporter#459]
我的多台电脑都都用到这个扩展,首先是不知道作者什么时候更新代码,其次是每次都要自己打包...
所以希望作者能继续使用Chrome扩展的自动更新机制...

**Comment by zelda0079** [comment]
其实现在CRX没什么用...直接将CRX拉入去之后CHROME又会不让你用, 让不如用载入未封装的方法, CHROME就会容许你当作测试来一直使用

**Comment by Sam0523** [comment]
虽然 Google Chrome 禁止直接安装 crx ，但是基于 chromium 的浏览器大都是可以直接安装的，比如 Vivaldi ，以及一大票国产浏览器，也就是说 crx 还是有点用的。不过自动更新应该是没戏，基本没可能再登陆扩展商店。

**Comment by Ehend** [comment]
在2017年08月07日 10:36 ，tofuliang写道：

**Comment by acgotaku** [comment]
不能上架商店  打包也是多余的

**Comment by tofuliang** [comment]
最起码可以让自己添加了签名的人享受自动更新啊.

雪月秋水 <notifications@github.com>于2017年8月7日周一 下午7:52写道：

**Comment by tofuliang** [comment]
你的说法不妥,只要在系统导入签名后,是可以直接拖进去安装的,跟在webstore上安装没有两样.

zelda0079 <notifications@github.com>于2017年8月7日周一 下午1:02写道：

**Comment by tofuliang** [comment]
上架webstore只是自动更新的一个途径而已.即时不上架webstore,单靠GitHub就可以做到自动更新,具体可以看这个pr
https://github.com/acgotaku/BaiduExporter/pull/403 作者自己都测试通过了的.

Sam Yu <notifications@github.com>于2017年8月7日周一 下午4:20写道：

**Comment by acgotaku** [comment]
更新了！

**Comment by tofuliang** [comment]
自动更新所依赖的
https://github.com/acgotaku/BaiduExporter/blob/master/chrome/updates.xml
 没有更新版本号😂😂

雪月秋水 <notifications@github.com>于2017年8月8日周二 下午8:57写道：

**Comment by yujincheng08** [comment]
不如弄个自动集成吧😂

**Comment by acgotaku** [comment]
@yujincheng08 好主意 但打包能自动集成？

**Comment by yujincheng08** [comment]
@acgotaku 看一下我做的demo repo? 用circleci实现提交代码之后自动打包并且重新push一个新的crx文件。
PS: 我在circleci后台的里面的环境变量设置了$KEY是我的pem文件内容

**Comment by tofuliang** [comment]
早上回来看到扩展自动更新了,上来GitHub看到是0.9.7,但是在Chrome扩展页面看到是0.9.6,猛点 立即更新扩展程序 版本号死活不变,
看来下本地的代码,才发现时 update.xml 和 manifest.json 的版本号对不上 😂

**Comment by zelda0079** [comment]
@tofuliang 你说到的签名具体是要怎做到? 是CRX作者自己做的, 还是自己也能做到的?

**Comment by acgotaku** [comment]
@yujincheng08 貌似用这个的比较多？ https://travis-ci.com/

**Comment by tofuliang** [comment]
@zelda0079 只要是用chrome打包的扩展都会有一个签名,正确来说是唯一ID,例如,作者打包的扩展的ID就是 padhohbdomknelobmiphhcafepnfipaa ;
只要将这个ID加到系统的白名单就可以正常使用,顶多就在扩充管理页面标示 "并非来自 Chrome 网上应用店。";
怎么将这个ID加到系统白名单,请认真阅读readme及readme中的外链,各个系统都有详细的说明.

**Comment by yujincheng08** [comment]
@acgotaku 其实都可以的😊我用这个只是因为学生免费而已。配置上都差不多，关键只是打包的脚本而已。自动继承的主要步骤就是：
1. 检测到commit
1. 安装依赖
1. 通过后台设置的环境变量不便公开的生成pem文件
1. 打包出crx文件到git目录
1. 进行新的commit，并且跳过这次commit的集成
现在的CI基本上都能提供实现上面步骤的环境的

**Comment by acgotaku** [comment]
@yujincheng08 demo已经删了啊 我还想在重构的版本中加入呢  QAQ

**Comment by yujincheng08** [comment]
@acgotaku 我又重新把它弄回来了了^v^

**Comment by acgotaku** [comment]
@yujincheng08 谢谢！ 我要好好学习一个！

**Comment by acgotaku** [comment]
@yujincheng08 貌似私钥设置的有问题。。通过不了  QAQ

**Comment by yujincheng08** [comment]
@acgotaku 可能是你换行符的问题？密钥要有换行符\n的

**Comment by acgotaku** [comment]
所以你是手动把文件里的换行改成 \n 然后再设置的？ @yujincheng08

**Comment by yujincheng08** [comment]
@acgotaku 是的！那个echo有个-e参数就是为了这个

**Comment by acgotaku** [comment]
@yujincheng08 默认的deploy key没有push权限 https://circleci.com/docs/1.0/adding-read-write-deployment-key/
我按照这个来配置新的SSH key 可还是用的默认的deploy key...

**Comment by acgotaku** [comment]
@yujincheng08 好吧 把老的key删了就行

**Comment by yujincheng08** [comment]
👍 解决了就好
