### ISSUE TITLE
能否提供一个Firefox版的0.3版？

### ISSUE THREAD

**Issue by syazyz** [acgotaku/BaiduExporter#46]
今天心血来潮把BaiduExporter从0.3升级到0.3.5，就刷不出按钮了。之前一直都好好的。

**Comment by giveup** [comment]
同学。。。能认真看看吗？
https://github.com/acgotaku/BaiduExporter/releases

**Comment by syazyz** [comment]
我错了……我不熟悉github的结构……

**Comment by acgotaku** [comment]
@syazyz 没事没事 0.3.5的BUG我会尽快修复的

**Comment by acgotaku** [comment]
@syazyz 0.3.5版本的BUG已经修复
