### ISSUE TITLE
百度下载一断一断的，你们也是这样的吗？

### ISSUE THREAD

**Issue by weiyideai520** [acgotaku/BaiduExporter#460]
![snipaste20170809_092744.png](https://i.loli.net/2017/08/09/598a66bb80e22.png)

**Comment by weiyideai520** [comment]
忘记说了，我的Version:0.9.4 更新日期: 2017/03/05 ，chrom浏览器，aria2 1.31.0 版本

**Comment by Mikudes** [comment]
我的也是唉

**Comment by Elaoed** [comment]
你试试不登录的用这个下载

**Comment by Mikudes** [comment]
不登录特别慢只有几十k

**Comment by acgotaku** [comment]
不充钱怎么能变强。。。

**Comment by lonelykid** [comment]
问题是不愿意给百度充钱，另外就算冲了以百度的“人品”也不知道能用几天。
分享之后，不登陆下载，可以绕开账号被限速的情况，不过遇上不能分享的资源就不知道怎么办了。

**Comment by cololi** [comment]
可以试一试淘宝的租百度云会员

**Comment by zcy85611** [comment]
我也是一样的情况

**Comment by lonelykid** [comment]
我弃疗了，搜了下网上相关的帖子，各种方法都试了试，开始还能勉强下，但不多久就不行了，我IP被封了？对了，用Eagleget还是有一百多kb，我用aria2c直接死了，原因不明。还是考虑下用哪家的付费服务吧。

**Comment by qk98** [comment]
加上 -m0 -t1 参数，能稳定在1m

**Comment by lonelykid** [comment]
我加上这个参数了，但似乎aria2c不会再这种情况下reconnect，
errorCode=1 SSL/TLS handshake failure: Error: An existing connection was forcibly closed by the remote host.
链接数一直在变少，最后就停了。我猜aria2c应该没有允许这种情况下reconnect。eagleget激进的多，应该是任何情况断了都reconnect

**Comment by lonelykid** [comment]
其实改一下aria2c的source就好了，log里面连抛出异常的位置都给了，retry的方法也是aria2c本来就有的。虽然很讨厌百度，不过这么搞好像也是有点过分了。还是找找别的服务吧。

**Comment by aiwonanjing** [comment]
把自己的文件开启私密分享，退出自己账号，5个文件同时下时就能满速下载。

**Comment by lonelykid** [comment]
问题是很多文件百度不让分享。

**Comment by redapple0204** [comment]
解决方法：
在参数后面加上-t1 -m0

**Comment by redapple0204** [comment]
用一个不限制线程的版本

**Comment by zcy85611** [comment]
请教一下什么是不限制线程的版本？是Aria2吗？我用的是官方的1.32版

**Comment by redapple0204** [comment]
@zcy85611 https://github.com/redapple0204/my-boring-python/blob/master/%E7%A0%B4%E8%A7%A3%E7%99%BE%E5%BA%A6%E4%BA%91%E9%99%90%E9%80%9F.md#%E6%96%B9%E6%B3%95%E5%85%AD%E9%87%87%E7%94%A8aria2%E4%B8%8D%E9%99%90%E5%88%B6%E7%BA%BF%E7%A8%8B%E7%89%88%E6%9C%AC

**Comment by baojia** [comment]
应该是哪个参数不对， 用百度下载器不断，就是个aria2壳

**Comment by AshtonCoop** [comment]
+1
之前下载速度很快的，但是不知道为什么最近就会有类似情况。
前几天换了modem，然后下载的时候能达到6MB。结果现在就不行了。

**Comment by UnluckyNinja** [comment]
发现保存到自己网盘和直接下载相同的文件，进度几乎保持一致。保存速度快但下没多少就断开，直接下载不断但速度慢，一段时间下来两者流量差不多，应该是达到免费用户的流量限制了。解决办法应该是：要么充钱，要么用回官方客户端，要么等十几天不用度盘，等流量攒够了再下。

**Comment by Jephen** [comment]
> @zcy85611 https://github.com/redapple0204/my-boring-python/blob/master/%E7%A0%B4%E8%A7%A3%E7%99%BE%E5%BA%A6%E4%BA%91%E9%99%90%E9%80%9F.md#%E6%96%B9%E6%B3%95%E5%85%AD%E9%87%87%E7%94%A8aria2%E4%B8%8D%E9%99%90%E5%88%B6%E7%BA%BF%E7%A8%8B%E7%89%88%E6%9C%AC

把这个方法里面提供的不限制线程的aria2c.exe替换掉自己的aria2c.exe（好像官方的程序当配置max-connection-per-server大于16时会无法启动，但是配置split好像不受限制），其中有一个步骤是

>注意：这步是关键：把参数-s10 -k1M -x16 改成 -s256 -k2M -x256 ,不过这只是建议，如果你的网速还要快的话，建议把-s和-x改成更高，如果你改成很高了还是觉得不够快，你可以更改-k后面的参数，变成-k3M甚至-k5M，-k10M,然后在这些参数后面按一下空格加上-t1 -m0这个参数

这里面，-s指split，-k指min-split-size，-x指max-connection-per-server，-t指timeout，-m指max-tries，这些可以写在在配置文件中，之后就可以直接使用BaiduExporter的ARIA2 RPC下载了，我不是很了解这些，大概和那个方法达到的效果是一样的吧。

**Comment by Jephen** [comment]
不过有一些服务器应该会限制同一IP同时连接的数量，当连接数量较多时，可能会封IP什么的吧，这么一想还是那个链接里的方法好一些。

**Comment by zlf179** [comment]
我用路由器端的aria rpc下载设置的16线程 最高速度只能到155KB/s 怎么解决？

**Comment by redapple0204** [comment]
@zlf179 换不限制线程版本上256线程

**Comment by sdssly** [comment]
@redapple0204  这个aria不限制线程的版本，哪里有啊？

**Comment by Jephen** [comment]
@sdssly 

> https://github.com/redapple0204/my-boring-python/blob/master/%E7%A0%B4%E8%A7%A3%E7%99%BE%E5%BA%A6%E4%BA%91%E9%99%90%E9%80%9F.md#%E6%96%B9%E6%B3%95%E5%85%AD%E9%87%87%E7%94%A8aria2%E4%B8%8D%E9%99%90%E5%88%B6%E7%BA%BF%E7%A8%8B%E7%89%88%E6%9C%AC

**Comment by sdssly** [comment]
谢谢@Jephen 我的aria是路由器上的 好像是ARM还是MIPS的版本，我要再找找看有没有了

**Comment by Jephen** [comment]
@zlf179 这个可能是因为百度服务器限制单个连接速度为10Kbps左右，之前我使用最小速度限制为10K的aria2配置下载百度云文件，基本上每个文件都是未下载完成所有连接就都断了。解决方法就是

> @zlf179 换不限制线程版本上256线程

不过线程数对路由器CPU和内存的影响我不是很了解。

**Comment by redapple0204** [comment]
@sdssly 你看看我后面有个linux&mac的编译版本，你试试自己去编译？

**Comment by zcy85611** [comment]
@redapple0204 请问是否有openwrt版不限线程的源码？我用的是openwrt版的aria2c，现在是官方最新版的1.3.2，不知可否帮助修改源码以支持256线程？

**Comment by redapple0204** [comment]
@zcy85611 我有修改好的源码，在这里
*https://cpneteroster-my.sharepoint.com/personal/redapple0204_c4o_me/_layouts/15/guestaccess.aspx?docid=1f9cd8658119c4d2aad258c34ad8000d2&authkey=AbLnYSgl8MPehq213ZgDyZ4
<https://cpneteroster-my.sharepoint.com/personal/redapple0204_c4o_me/_layouts/15/guestaccess.aspx?docid=1f9cd8658119c4d2aad258c34ad8000d2&authkey=AbLnYSgl8MPehq213ZgDyZ4>*

*编译的话嘛.....看看里面的readme文档吧*

2017-08-26 9:45 GMT+08:00 zcy85611 <notifications@github.com>:

**Comment by zlf179** [comment]
@sdssly  你找到openwrt的mips的256线程的版本了吗

**Comment by JQuu** [comment]
@acgotaku 会员可以杜绝这种情况吗？

**Comment by acgotaku** [comment]
@JQuu 我没充过会员 但理论上是可以的

**Comment by anymee** [comment]
哪位有编译好的不限线程的openwrt版的aria2c吗？最好是带luci安装的，直接装进luci

**Comment by zlf179** [comment]
@anymee  我也在找 不过我找的都是pandorabox的固件的

**Comment by csrutil** [comment]
![screen shot 2017-10-23 at 10 00 40 pm](https://user-images.githubusercontent.com/6078291/31893515-5cf7e418-b7d1-11e7-87bf-df8b5e4c4951.png)

```
 -j, --max-concurrent-downloads=N Set maximum number of parallel downloads for
                              every static (HTTP/FTP) URL, torrent and metalink.
                              See also --split and --optimize-concurrent-downloads options.

                              Possible Values: 1-*
                              Default: 5
                              Tags: #basic
```

https://www.dropbox.com/s/orxy2ab6yygrg0a/aria2_1.33.0-1_mipsel_24kc.ipk?dl=0

@zlf179 @anymee

**Comment by anymee** [comment]
@csrutil 出现这个问题
![default](https://user-images.githubusercontent.com/31944592/32001571-bd8175fe-b9cc-11e7-9b47-fd406de35d03.png)

**Comment by csrutil** [comment]
@anymee 之前有安装aria2 ? 你命令行看看版本是多少。

**Comment by zlf179** [comment]
@csrutil  没有luci吗？ 没有luci用不了啊

**Comment by csrutil** [comment]
@zlf179 我不用luci。

**Comment by zlf179** [comment]
@csrutil  好吧

**Comment by anymee** [comment]
@csrutil 有aria2 1.30
照理说低于1.33啊

**Comment by csrutil** [comment]
@anymee 没明白你的意思。
```
# 看下输出啥
aria2c -v

# 查看max-connection-per-server
aria2c -h
```

**Comment by anymee** [comment]
@csrutil 我的openwrt路由原来已经装了aria2，版本1.30，但是再装你的1.33版的无法升级，显示已是最新版了。

**Comment by csrutil** [comment]
@anymee 删除重新安装。

**Comment by anymee** [comment]
@csrutil 我的路由是网件4300，刷的openwrt，ipk可能需要ar71xx的，你的mipsel的ipk不知道能不能通用

**Comment by zlf179** [comment]
@anymee  不能通用 需要自己编译ipk或者叫别人帮你编译

**Comment by anymee** [comment]
不会，俺小白：（
