### ISSUE TITLE
发现火狐自己签名打包扩展简单不少，就是每次更新要手动自己重新打包上传比较烦

### ISSUE THREAD

**Issue by OneWizard** [acgotaku/BaiduExporter#461]
首先前提是有firefox账号
1.登录https://addons.mozilla.org # 右上角，工具，提交新的附加组件
2.在 如何分发此版本 选择中
选择第二项（自用，不公开发布）
我自己托管。您的提交将被立即签名以供自行分发。更新应该由您通过 updateURL 或外部应用的更新来处理。
3.打包chrome文件夹，zip格式，保证打开压缩包后直接看见manifest.json（就是在文件夹下打包，别打包文件夹），上传，应该是秒过的
4.最好在https://addons.mozilla.org/zh-CN/developers/addons 中点击你上传的附加组件名称，把附加组件名字、网址啥的给改了。。。防止不必要的占id的毛病
5.更新在 管理状态和版本 中，打包的zip上传即可，下载是点名字

其实我挺希望作者弄个自签名版的。。。。

**Comment by acgotaku** [comment]
我当然知道 百度去举报了 被火狐下架了
