### ISSUE TITLE
Mac OS

### ISSUE THREAD

**Issue by s0fx2** [acgotaku/BaiduExporter#462]
请确保以下几点：

1. 已经阅读过README
2. 尝试安装最新版本插件
3. 尝试清空浏览器缓存
4. 尝试卸载插件后重新安装

发起 Issue 时，请提供：

1. 您下载的内容地址
2. 插件版本号，浏览器版本号，系统版本号
3. 列举出现问题的详细步骤
4. 描述能否复现问题

----------

**不符合上述条件的Issue将被无理由关闭**

**Comment by s0fx2** [comment]
cheome和插件都是最新版，只要装上插件，youtube视频就卡顿，自动降到114p，即使这样也很难播放，卸载插件，开两个1080p播放无压力，再三台mac上测试都是这个问题，测试过程中该插件是唯一安装的插件。我觉得这个问题太玄幻了

**Comment by tofuliang** [comment]
科科
![20170810-143411](https://user-images.githubusercontent.com/1814685/29157444-95834ef8-7dd9-11e7-985c-4c115fc0a538.png)

**Comment by s0fx2** [comment]
刚才出门了，回来又继续研究了一下，找到问题的所在了，不是咱们插件的问题，是纯Chrome的问题，因为chrome默认开启了quic协议，在://flags里面找到 Experimental QUIC protocol ，关闭了就可以
