### ISSUE TITLE
baiduexporter无法导出下载链接

### ISSUE THREAD

**Issue by LiFangCoding** [acgotaku/BaiduExporter#463]
你好, 已做过以下几点但没用：
2. 尝试安装最新版本插件
3. 尝试清空浏览器缓存
4. 尝试卸载插件后重新安装

1 从github直接下载的 
2 插件版本号:  0.9.6
   浏览器版本号: chrome Version 60.0.3112.90
    系统版本号: mac 10.12.6

3. 列举出现问题的详细步骤
插件有带有少女头像的提示版本号, 大概安装成功了.
<img width="777" alt="screen shot 2017-08-10 at 2 27 54 am" src="https://user-images.githubusercontent.com/21252042/29157163-9d5d30e6-7d73-11e7-8ed5-c6fe25610d23.png">

 但右键插件出现的菜单中exporter和options均为灰色, 无法点击. 在百度云盘中, 无法导出下载链接.

<img width="202" alt="screen shot 2017-08-10 at 2 28 05 am" src="https://user-images.githubusercontent.com/21252042/29157165-a3a7c2e0-7d73-11e7-9c4d-154a92266fc6.png">

百度云盘无法导出下载链接.  

另外, readme中的
"插件的设置必须保存之后才会生效。
推荐设置：
Set --rpc-secret=<secret> if you are using aria2 1.18.4(or higher) with 'JSON-RPC PATH' like http://token:secret@hostname:port/jsonrpc
Set --rpc-user=<username> --rpc-passwd=<passwd> if you are using aria2 1.15.2(or higher) with 'JSON-RPC PATH' like http://username:passwd@hostname:port/jsonrpc
Use http://localhost:6800/jsonrpc#max-connection-per-server=5&split=10 set download options for specific file."

请问是指baiduexporter需要在options里设置这些吗?  谢谢.

**Comment by LiFangCoding** [comment]
可以导出了 好像是

**Comment by acgotaku** [comment]
那是设置的RPC路径 不能自己查查么？？？

**Comment by LiFangCoding** [comment]
我的意思是aria2里的rpc路径 还是 yaaw里的rpc?

**Comment by LiFangCoding** [comment]
解决了, 应该是在aria2里配置rpc.  reademe中的 Usage直接写推荐设置, 以为是在baiduexporter里设置rpc.  有时间把readme那里改成aria2推荐设置吧, 避免歧义. 谢谢.

**Comment by milohuang** [comment]
想问一下是如何解决的，今天我也出现一摸一样的问题，进入网盘的时候还显示有到处下载，选定一个文件后就消失了。

**Comment by ChicBrother** [comment]
你还好，我是可以导出下载，但下载总失败。一直摸不清

**Comment by LiFangCoding** [comment]
如果你是用mac, 直接下这个里面的aria2 https://github.com/yangshun1029/aria2gui. 不需要配置路径,直接就能用了.

如果是windows, 你看下readme文档里, 配置aria2的 set- private之类的config 做了没有, 作者post了个自己的配置文件在readme里面, 你也可以看下.

如果还不行, 你就直接create a issue, 发帖问作者吧.

**Comment by acgotaku** [comment]
作者又不是客服。。。
