### ISSUE TITLE
8/8 号最新版的插件配置后只要在百度网盘一选择文件 导出下载的按钮就消失了

### ISSUE THREAD

**Issue by ChicBrother** [acgotaku/BaiduExporter#464]
已安装最新版本插件
已清空浏览器缓存
已卸载插件后重新安装，打包的与解包的都试了

插件版本：Version:0.9.6 更新日期: 2017/08/08 
Chrome 版本： 60.0.3112.90（正式版本） （64 位）

问题描述 ：

登陆百度网盘后，插件会在加载完网页后显示 导出下载的下拉列表按钮，但在选择文件准备下载时发现这个按钮消失了。

得重新刷新网页才显示 按钮，但只要一选择文件就又消失。

查了一下网页源代码，发现那 export_menu 那个div 一起消失了。

试过网盘根目录与各级子目录页面，发现都有这个问题。

**Comment by xuev** [comment]
我也是同样的情况

**Comment by dnf5320** [comment]
一样，我发生的时间是：2017-08-11 11点多

**Comment by Runjuu** [comment]
有一个零时解决方法，把 id="export_menu" 换成其他的，比如说abc什么的，在选择文件导出的时候就不会被百度移除这个元素了

@dnf5320 
@xuev 
@ChicBrother

**Comment by xuev** [comment]
@Runjuu 嗯，在网页源文件改掉以后确实能用，多谢！

**Comment by redapple0204** [comment]
@Runjuu 欸，请问怎么改？

**Comment by SethCody** [comment]
@xuev 请问在哪个源文件改，谢谢

**Comment by xinlangiOS** [comment]
@Runjuu  修改之后确实能显示，但是同一个文件会下载8次，这个是什么情况

**Comment by Runjuu** [comment]
@xinlangiOS 你是怎么下载的，我是直接扔 terminal 的，目前没发现会多次下载

**Comment by SethCody** [comment]
@Runjuu 请问在哪个源文件改，谢谢

**Comment by Runjuu** [comment]
@SethCody @redapple0204 
打开浏览器控制台，然后跑下面的script

```js
document.querySelector('#export_menu').id = 'export_menu2';
```

**Comment by redapple0204** [comment]
@Runjuu 非常感谢~
正好急着用呢

**Comment by acgotaku** [comment]
怎么百度又来一遍。。。是还没玩够么。。。

**Comment by Runjuu** [comment]
@acgotaku 如果只是简单地根据 id 名来移除元素的话..其实我们只要在每次载入的时候随机生成一个 id
 就好了？（我猜

**Comment by acgotaku** [comment]
去年他们就干过这事。。。后来封不掉 不干了。。

今年又来。。。

**Comment by Runjuu** [comment]
😂 （百度现在的内心可能是这样的 => “我能怎么办呀，我也很绝望啊”

**Comment by jkxuan** [comment]
今天上午也遇到这个问题，我是刷新一下页面在提示初始化成功的时候快速点选要下载的文件，导出下载虽然会被其他按钮阻挡但不会消失……:joy:

**Comment by iwenbin** [comment]
昨天还好好的，今天就遇到了上面的情况

**Comment by ChicBrother** [comment]
@Runjuu  好办法。

**Comment by xinlangiOS** [comment]
@Runjuu 我是直接搜索到修改的，只不过中午睡觉之前是每一个文件下载8次，现在没有了。。。也不知道什么原因

**Comment by abmyz** [comment]
@Runjuu 执行document.querySelector('#export_menu').id = 'export_menu2'; 报下面的错什么原因啊，谢谢
Uncaught TypeError: Cannot set property 'id' of null
    at <anonymous>:1:43

**Comment by Runjuu** [comment]
@abmyz 你是在「导出下载」按钮被移除了之后才跑的？你需要在提示「初始化成功」之后就跑那个 script

**Comment by abmyz** [comment]
@Runjuu 解决了 谢谢！就是有点麻烦每次都要执行这个，等大神更新

**Comment by abmyz** [comment]
@Runjuu 请教一个问题Aria2 是不是必须要有公网的IP 在家里面用路由器都是提示DNS错误，谢谢！

**Comment by redapple0204** [comment]
@abmyz 既然是家用的直接用命令行不就好了==

**Comment by abmyz** [comment]
@redapple0204 等晚上截图错误代码请教

**Comment by ShenChuanwei** [comment]
我重装了几次这个插件,还是不行,来这里才发现原来是百度在搞幺蛾子!
经过半天的摸索,我发现挂接一个 VPN 就能用了~

**Comment by gxbyws** [comment]
现在url通过改id，提取了url，但是下载的时候，从满速一直递减降到0，还是限速了

**Comment by redapple0204** [comment]
@gxbyws 你需要用aria2 不限制 线程版本来下载

**Comment by Shu-0** [comment]
@Runjuu 多谢！
@gxbyws 速度和这个问题大概无关，我改了 id 以后在满速跑

**Comment by jimleestone** [comment]
请教下
document.querySelector('#export_menu').id = 'export_menu2'; 
这行脚本怎么执行？Chrome的控制台不太熟悉...

**Comment by redapple0204** [comment]
@jimleestone 浏览器中按下f12，然后把这段代码输入进去，回车

**Comment by max210** [comment]
跑了那个脚本，点击了 ARIA2 RPC  但是aria2没反应，这是什么原因

**Comment by redapple0204** [comment]
@max210 那就用命令行咯....

**Comment by max210** [comment]
怎么操作，大神教教我吧 @redapple0204

**Comment by lyd87880938** [comment]
@jimleestone F12 console

**Comment by redapple0204** [comment]
@max210 去下载一个aria2，然后复制到c:\windows\system32里面，然后打开cmd，把生成的一长串命令复制进去，回车，下载。

**Comment by Runjuu** [comment]
https://github.com/Runjuu/BaiduExporter

简单地打了个包，如果觉得每次都得手动改id的话可以先用这个，但记得隔段时间来看一下主仓库有没有更新，这个只能临时用一下

**Comment by antonqiu** [comment]
另一个暴力一点的做法：刷新页面，趁页面还未加载完（趁JS还不能删元素）选中你的文件，点菜单下载... 需要点手速

**Comment by mo-han** [comment]
@Runjuu 

.crx文件
[BaiduExporter-patch-random_id.zip](https://github.com/acgotaku/BaiduExporter/files/1218002/BaiduExporter-patch-random_id.zip)

**Comment by Chino-Ryuko** [comment]
export_menu在
src/core.js 126/127/129行
src/baidu.js 58行
js/share.js 8231/8264/8308 column处
js/home.js 5824/58575901 column处
js/core.js 2566/2599/2643 column处
js/baidu.js 1026 column处
嗯 差不多全了2333

**Comment by ChicBrother** [comment]
既然大家都放出招式了，就暂用 @Runjuu 的方法了。 具体 等 开发大神重新修改更新后再下载代码。我关闭issue了。

**Comment by Yoncise** [comment]
Mac:
在插件目录下执行 `find . -type f -print0 | LC_ALL=C xargs -0 sed -i '' -e 's/export_menu/<自己取个名字>/g'`

**Comment by acgotaku** [comment]
@exoticknight ??? 这个问题早就解决了好么

**Comment by exoticknight** [comment]
@acgotaku 嗯嗯感谢
