### ISSUE TITLE
只要点击具体的文件，导出就自动消失了，是我一个人这样吗？

### ISSUE THREAD

**Issue by lyd87880938** [acgotaku/BaiduExporter#465]
今天突然发现我无法使用这个插件，一点具体的文件导出按钮就自动消失……

其实我是SVIP，就是下载到Linux服务器需要这个插件啊……

**Comment by Runjuu** [comment]
临时解决方法见 https://github.com/acgotaku/BaiduExporter/issues/464

**Comment by lyd87880938** [comment]
@Runjuu 谢谢

**Comment by KingOldFive** [comment]
早上用时还没这问题，下午就出现了

**Comment by delusionxb** [comment]
码农参考:
1. git clone git@github.com:Runjuu/BaiduExporter.git ~/Downloads/be-pack
2. 打开chrome的扩展程序, 选中 '开发者模式'
3. finder里面打开 下载->be-pack
4. 拖动 chrome 文件夹到chrome
搞定 收工

**Comment by acgotaku** [comment]
更新最新版 解决问题

**Comment by enjelbeteu** [comment]
目前只能用
https://chrome.google.com/webstore/detail/%E6%B7%BB%E5%8A%A0%E5%88%B0aria2/nimeojfecmndgolmlmjghjmbpdkhhogl?utm_source=chrome-app-launcher-info-dialog
代替

**Comment by guohaomiao** [comment]
感谢大大 目前正常
