### ISSUE TITLE
选中文件后，下载按钮消失

### ISSUE THREAD

**Issue by jcx70100** [acgotaku/BaiduExporter#467]
请确保以下几点：

1. 已经阅读过README
2. 尝试安装最新版本插件
3. 尝试清空浏览器缓存
4. 尝试卸载插件后重新安装

发起 Issue 时，请提供：

1. 您下载的内容地址
   > 还没下载就出问题
2. 插件版本号，浏览器版本号，系统版本号
   > 插件版本0.0.5
   > 浏览器版本版本 60.0.3112.90（正式版本） （32 位）
   > 系统版本 win10 1703 
3. 列举出现问题的详细步骤
   1. 打开网盘后，可以正常加载，出现`导出下载`按钮
   2. 当选中文件后，`导出下载`按钮消失，前几天还是正常的。
4. 描述能否复现问题

----------

**不符合上述条件的Issue将被无理由关闭**

**Comment by freedomlang** [comment]
有更新到最新版本吗？

**Comment by qiangwa** [comment]
same problem for me

**Comment by Lugic1993** [comment]
我也出现了这样的问题

**Comment by Lugic1993** [comment]
在替换为最新的版本以后问题解决
