### ISSUE TITLE
无法下载

### ISSUE THREAD

**Issue by xingezhang** [acgotaku/BaiduExporter#468]
请确保以下几点：

1. 已经阅读过README
2. 尝试安装最新版本插件
3. 尝试清空浏览器缓存
4. 尝试卸载插件后重新安装

发起 Issue 时，请提供：

1. 您下载的内容地址
2. 插件版本号0.96，浏览器版本号Firefox54.0.1，系统版本号windows7
3. 列举出现问题的详细步骤
命令行运行aria2c，打开浏览器，进入百度网盘，选中文件，点击导出下载-ARIA2C RPC
![snipaste_20170814_101705](https://user-images.githubusercontent.com/13484700/29256043-e00d7d4c-80d9-11e7-8d44-b5a6591f74f4.png)
![snipaste_20170814_101523](https://user-images.githubusercontent.com/13484700/29256050-e9c99604-80d9-11e7-99c1-f9d673e8db40.png)

导出下载地址，手动添加也是失败
4. 描述能否复现问题
 
可以复现
----------

**不符合上述条件的Issue将被无理由关闭**

**Comment by xingezhang** [comment]
升级到0.9.7版本，Firefox问题依旧，但是Chrome可以正常使用了

**Comment by slinerd** [comment]
要改一下 aria2的 config，没记错的话是
`--check-certificate=false`

**Comment by UnluckyNinja** [comment]
之前度盘可https可http，https下插件不能直接一键下载（可以手动导出下载地址到yaaw下载），http一切正常，但现在百度强制HTTPS了，每次都得手动导出，就很难受。一直启用的`--check-certificate=false`参数，但感觉没有效果

**Comment by acgotaku** [comment]
FF问题 延缓 处理  先用Chrome吧
