### ISSUE TITLE
修改ua建议

### ISSUE THREAD

**Issue by giveup** [acgotaku/BaiduExporter#47]
修改ua为Mac客户端，尝试解决需要经常修改ua来避免限速。
netdisk;2.4.3;MacBookPro9,2;MAC-OS X 10.10.3 (14D136);10.10.3;zh-Hans_HK@currency=CNY
Github真是不适合我这种智商的人玩，搞半天都不能提交代码。老实发issue算了。

**Comment by acgotaku** [comment]
@giveup  51出去玩了一趟 回来了 Ua修改为Mac就可以一劳永逸？

**Comment by HarukaMa** [comment]
不是应该 fork 一份改完了回来发 pull request 么……

iPhoneから送信

H27/05/06 21:54、giveup <notifications@github.com> のメッセージ:

**Comment by jiayiming** [comment]
我这里试了下   macUA大概是900k左右速度    管家是1.2m~1.3m左右   还是用管家吧   不过以后管家限速了可以当备胎

**Comment by acgotaku** [comment]
@jiayiming 管家的速度还是最快的....

**Comment by giveup** [comment]
@acgotaku 因为mac客户端更新慢.win版经常要更新.算是半一劳永逸.
根据我自己的测试情况,基本都能跑满带宽.

**Comment by giveup** [comment]
@HarukaMa 玩不来啊.我是clone到桌面,修改完了按sync提交.死活不行,懒得折腾.

**Comment by acgotaku** [comment]
@giveup 那就手动在配置菜单改UA不就好了 没必要修改源码啊~

**Comment by HarukaMa** [comment]
直接 clone 的话不是这个项目的 collaborator 应该是不能直接提交代码的……

iPhoneから送信

H27/05/09 1:15、giveup <notifications@github.com> のメッセージ:

**Comment by gz0007** [comment]
请问在群晖环境下的aria2如何修改ua？

**Comment by leitwolf** [comment]
刚试了下，果然给力啊。
插件是刚下载下来的，下载还是300KB左右，换了MAC的UA马上上到900KB左右。：）

**Comment by acgotaku** [comment]
@leitwolf 可能不同地区情况不一样吧 我用插件默认的UA 是能 2m/s满速的。。。
