### ISSUE TITLE
关于0.9.7导出下载链接重复的问题

### ISSUE THREAD

**Issue by izuolan** [acgotaku/BaiduExporter#471]
0.9.7，已尝试重装插件，Chrome 60，Linux

如图：

![Screenshot_20170819_092027.png](https://i.loli.net/2017/08/19/5997933e06567.png)

无论是导出下载链接还是直接选择下载到本地，都会新建几十个任务（重复的）。

0.9.5没有这个问题，但是0.9.5导出下载按钮不能显示。

**Comment by acgotaku** [comment]
你确定不是自己多装了之类的？

**Comment by izuolan** [comment]
是我装多了，原来还有这种情况，能装多个重复的插件啊。

没事了。谢谢。

**Comment by maonx** [comment]
原来还有重装的问题。。
