### ISSUE TITLE
插件不支持超过有100个文件或者子目录的文件夹。The plugin can not support folders with more than 100 files and sub-folders. 

### ISSUE THREAD

**Issue by samhjn** [acgotaku/BaiduExporter#473]
需要下载的文件不方便公开，需要的话请私信。
插件版本：最新版（0.97）
浏览器：Google Chrome 60.0.3112.101
操作系统：Microsoft Windows 7 Ultimate SP1 64bit

当我尝试下载一个超过30000个子目录的文件夹时插件只能下载前100个子文件夹及子文件夹中的文件。这个问题100%复现。

经过简单的分析该问题应该是由于`src\home.js`忽略分页操作导致的。

希望能尽快修复这个问题。

Content is private, so I am not able to provide content URL here. Please contact me directly.
Plugin version: newest version (0.97)
Browser: Google Chrome 60.0.3112.101
OS: Microsoft Windows 7 Ultimate SP1 64bit

When I try to download a folder which contains more than 30000 sub-folders, the plugin only managed to download only 100 folders and its content. The problem happened every time I download this folder.

The problem may lay in `src/home.js` for it ignored the page separating. 

Hoping the problem could be fixed ASAP.

**Comment by acgotaku** [comment]
这么大的也不好测试。。。。 你就分开下吧。。。

**Comment by samhjn** [comment]
正是因为我之前往百度云上某个目录存了几万个文件夹，每个文件夹下都有一个文件，所以分开下载不太可能，百度云自己的App也无法实现那么大量的批量下载，才找插件的。。。
自己魔改了一下最后实现了这个下载功能，在这里谢过了。
不过说几万个实在太多，用原来的流程会导致内存消耗过大，我迫不得已改了整个插件的工作流程，所以感觉自己的修改不适合提交回原分支。在这里简单介绍一下自己的修改思路：
1. 把遍历文件夹的FIFO队列更换为文件夹+页码的形式进行遍历
2. 解决内存爆炸的问题，在爬文件夹的同时进行下载操作
