### ISSUE TITLE
不管用多少线程，下载速度被限速到1m/s

### ISSUE THREAD

**Issue by redapple0204** [acgotaku/BaiduExporter#474]
大家又遇到么？

**Comment by terryxuwen** [comment]
1m/s 你就偷着笑吧，我无论下载多少任务，每个任务无论多少线程，都是下载150K/S,精确无比，不多不少。活活气死，已经持续多个月了，更新了网盘助手也没用。

**Comment by redapple0204** [comment]
@terryxuwen 我现在好了，上次的1m/s可能是因为我自己网络问题，现在能搞到8m/s了，已经满速了

在 2017年8月26日 上午8:00，terryxuwen <notifications@github.com>写道：

**Comment by terryxuwen** [comment]
看来我是进入百度黑名单了，切换多个账号下载都一样，一律每个下载150K/s 汗

**Comment by redapple0204** [comment]
@terryxuwen  我觉得你用的是默认配置的16线程吧，现在想要破解限速必须用256线程

2017-08-26 8:10 GMT+08:00 terryxuwen <notifications@github.com>:

**Comment by redapple0204** [comment]
还有，如果还是不行的话，就试试不要带cookies

**Comment by terryxuwen** [comment]
你是说aria2 单任务设置成256线程？

**Comment by redapple0204** [comment]
@terryxuwen yes

2017-08-26 8:24 GMT+08:00 terryxuwen <notifications@github.com>:

**Comment by terryxuwen** [comment]
我试试。另外不带cookie是啥意思，就是说不登录百度云网盘（不保存到自己网盘），直接用助手导出下载？

**Comment by redapple0204** [comment]
@terryxuwen 不，就是说换一个插件（例如baidudl）或者说直接从本插件生成的命令后面提取出链接然后下载（但是很可能失败）

2017-08-26 8:27 GMT+08:00 terryxuwen <notifications@github.com>:

**Comment by terryxuwen** [comment]
谢谢哈，根据你的方法，修改最大线程数后，单任务速度已经上涨到 1m/s ，虽然我是百m光纤，但是这速度我已满足，

**Comment by redapple0204** [comment]
@terryxuwen 恩.....其实你愿意折腾下的话可以弄到7-8m/s的，如果这样能将就着用就算了吧.....

2017-08-26 8:34 GMT+08:00 terryxuwen <notifications@github.com>:

**Comment by terryxuwen** [comment]
你是说换插件，可以达到7m/s ?

**Comment by redapple0204** [comment]
@terryxuwen 据我目前的观察来说，应该没什么问题，除非你已经被百度拉入三层黑名单

2017-08-26 8:38 GMT+08:00 terryxuwen <notifications@github.com>:

**Comment by terryxuwen** [comment]
baidudl是chrome插件还是油猴脚本？有下载地址吗

**Comment by redapple0204** [comment]
@terryxuwen google商店直接连接：（需要翻墙）
https://chrome.google.com/webstore/detail/baidudl/mccebkegnopjehbdbjbepjkoefnlkhef?hl=zh-CN
国内下载：
http://www.jb51.net/softs/555933.html


2017-08-26 8:44 GMT+08:00 terryxuwen <notifications@github.com>:

**Comment by terryxuwen** [comment]
用了感觉速度还不如网盘助手啊。是不是这么操作：安装插件后，在网盘页面点击，出现窗口后选择生成hlink，然后copy，然后在aria2里面添加下载任务，复制黏贴。这样的结果一方面速度并不如网盘助手快，一方面文件名是一串很长的编码。

**Comment by redapple0204** [comment]
@terryxuwen 不是hink，是glink，而且必须设置256线程（线程设置指的是-s -x后面都改成256）

**Comment by redapple0204** [comment]
hink生成的是被限速的连接........

**Comment by terryxuwen** [comment]
我是设置 split 为256 ，还有哪个参数啊？

**Comment by terryxuwen** [comment]
额，我用的是openwrt里面的aria2，汗，直接在路由器上下载的

**Comment by redapple0204** [comment]
@terryxuwen 这个....我就没办法了，除非你用电脑下载修改版本的aria2，原版aria2最高只能16线程，你设置再多还是16.....

2017-08-26 9:24 GMT+08:00 terryxuwen <notifications@github.com>:

**Comment by redapple0204** [comment]
@terryxuwen 当然啦，如果你技术比较高的话可以自己去编译....但是很麻烦就对了

在 2017年8月26日 上午9:25，Bc A <redapple02041@gmail.com>写道：

**Comment by terryxuwen** [comment]
好的。谢谢，跟你交流受益匪浅，下次有问题再行请教

**Comment by terryxuwen** [comment]
@redapple0204  请问能够修改 max server connection 超过16 的win下的aria2 版本在哪儿下？

**Comment by terryxuwen** [comment]
已经下载到了，发现确实可以修改连接数，下载初期速度很快，7m，但是不到一会儿，速度直线下降，最后变红，重试，进入下载详细信息看，发现一开始是百多个链接，然后连接数迅速下降，最后归零。看来是百度下了杀手。使用别人的办法，即私密共享，然后退出下载，此时连接数会从256下降到80后不再下降，速度稳定在4m左右。

**Comment by redapple0204** [comment]
@terryxuwen 你加了-t1 -m0 参数了吗

**Comment by terryxuwen** [comment]
没加，我赶紧试试

**Comment by redapple0204** [comment]
@terryxuwen 恩，不加的话我这里完全没法下

**Comment by terryxuwen** [comment]
加了，没多大变化。匿名下载仍然能保持80多的连接，速度能达到7m。保存到本身网盘再下载，连接很快全部关闭，然后变红无法下载。百度这是啥逻辑，鼓励匿名下载？

**Comment by redapple0204** [comment]
@terryxuwen 奇怪...可能你被百度拉入三层黑名单了，要么匿名下载要么用别的不带cookies的插件下载吧

在 2017年8月26日 下午5:28，terryxuwen <notifications@github.com>写道：

**Comment by terryxuwen** [comment]
对哦，其实说白了就是黑名单账户登陆状态下载就禁止多连接。以后都匿名下了~

**Comment by redapple0204** [comment]
@terryxuwen yes，差不多就是这个意思，等你过多几天来用了说不定就又可以了

2017-08-26 17:32 GMT+08:00 terryxuwen <notifications@github.com>:
