### ISSUE TITLE
[技术交流] 请问有没有办法获得网盘中视频文件能够live stream播放的地址

### ISSUE THREAD

**Issue by wilsonwu** [acgotaku/BaiduExporter#475]
就像一个视频文件百度可以支持点击后打开一个新页面在浏览器播放，这个资源的链接不知道能不能拿到呢？

**Comment by wilsonwu** [comment]
初步研究了一下，基本上是这个API去获取待播放资源的streaming的：
`http://pan.baidu.com/api/streaming?path=%2FTVs%2F%E5%9B%BD%E8%AF%AD%E7%89%88%2FEP14.mp4&app_id=250528&clienttype=0&type=M3U8_FLV_264_480`

这个调用需要cookie，看看朋友们有没有百度盘自动登录并设置cookie的经验，可能可以节省我这边的工作量。
当登录状态并调用网盘内的视频上述API后会返回如下记录：
```
#EXTM3U
#EXT-X-TARGETDURATION:15
#EXT-X-DISCONTINUITY
#EXTINF:10,
http://video.cdn.baidupcs.com/video/netdisk-videotran-yangquan/ade8de76539ab3245c8070378864055a_8242_1_ts?iv=0&uo=ct&to=vcb&range=0-657901&xcode=1a71ce06366dc7990d3a6f81f37e11c413c25a3b0a8326140b2977702d3e6764&fid=551dd3df4165860bee40ce05d70f8e51-3305403029&ouk=3305403029&len=657902&time=1503998651&r=300740695&sign=BOUTHNF-F3530edecde9cd71b79378b290804a96-nJaypHz7%252B2Zfxcl%252BC5JsRiMflPk%253D&sta_dx=480&sta_cs=2917&app_id=250528&logid=5579229560872600550&region=yangquan&isplayer=&devuid=&uva=3040105334&ic=2221887696
#EXTINF:10,
http://video.cdn.baidupcs.com/video/netdisk-videotran-yangquan/ade8de76539ab3245c8070378864055a_8242_1_ts?iv=0&uo=ct&to=vcb&range=657902-1367161&xcode=1a71ce06366dc7990d3a6f81f37e11c413c25a3b0a8326140b2977702d3e6764&fid=e3d85bafe319452653b5dfac8168fa44-3305403029&ouk=3305403029&len=709260&time=1503998651&r=300740695&sign=BOUTHNF-F3530edecde9cd71b79378b290804a96-21tx%252FnIiSfPntG6p5HTZe0wki8E%253D&sta_dx=480&sta_cs=2917&app_id=250528&logid=5579229560872600550&region=yangquan&isplayer=&devuid=&uva=3040105334&ic=2221887696
#EXTINF:10,
http://video.cdn.baidupcs.com/video/netdisk-videotran-yangquan/ade8de76539ab3245c8070378864055a_8242_1_ts?iv=0&uo=ct&to=vcb&range=1367162-1954285&xcode=1a71ce06366dc7990d3a6f81f37e11c413c25a3b0a8326140b2977702d3e6764&fid=b0d48865abd0fa00a5a387e738b7a856-3305403029&ouk=3305403029&len=587124&time=1503998651&r=300740695&sign=BOUTHNF-F3530edecde9cd71b79378b290804a96-pTtMWmIZ9zZpHiuA3y7LpSoI5ro%253D&sta_dx=480&sta_cs=2917&app_id=250528&logid=5579229560872600550&region=yangquan&isplayer=&devuid=&uva=3040105334&ic=2221887696
#EXTINF:10,
http://video.cdn.baidupcs.com/video/netdisk-videotran-yangquan/ade8de76539ab3245c8070378864055a_8242_1_ts?iv=0&uo=ct&to=vcb&range=1954286-2578407&xcode=1a71ce06366dc7990d3a6f81f37e11c413c25a3b0a8326140b2977702d3e6764&fid=09fb551c0bd2b49a408f0521a40de736-3305403029&ouk=3305403029&len=624122&time=1503998651&r=300740695&sign=BOUTHNF-F3530edecde9cd71b79378b290804a96-Be89gaS9VYY9nxQR3FEr%252FlZ7E6g%253D&sta_dx=480&sta_cs=2917&app_id=250528&logid=5579229560872600550&region=yangquan&isplayer=&devuid=&uva=3040105334&ic=2221887696
#EXTINF:10,
http://video.cdn.baidupcs.com/video/netdisk-videotran-yangquan/ade8de76539ab3245c8070378864055a_8242_1_ts?iv=0&uo=ct&to=vcb&range=2578408-2955106&xcode=1a71ce06366dc7990d3a6f81f37e11c413c25a3b0a8326140b2977702d3e6764&fid=66a2fd48be72e594a4396b17386a11f5-3305403029&ouk=3305403029&len=376699&time=1503998651&r=300740695&sign=BOUTHNF-F3530edecde9cd71b79378b290804a96-AmoXE%252F1LF5k%252BTX5jJhG3FC%252BTi%252F0%253D&sta_dx=480&sta_cs=2917&app_id=250528&logid=5579229560872600550&region=yangquan&isplayer=&devuid=&uva=3040105334&ic=2221887696
```
...... 后面是省略的，很长的，都是streaming链接的重复，这一步不需要任何验证，可以直接播放，我们只要找到对应的播放实现就完成了。

**Comment by wilsonwu** [comment]
仍然发现一个问题，播放：http://video.cdn.baidupcs.com/video/netdisk-videotran-yangquan/ade8de76539ab3245c8070378864055a_8242_1_ts?iv=0&uo=ct&to=vcb&range=0-657901&xcode=1a71ce06366dc7990d3a6f81f37e11c413c25a3b0a8326140b2977702d3e6764&fid=551dd3df4165860bee40ce05d70f8e51-3305403029&ouk=3305403029&len=657902&time=1503998651&r=300740695&sign=BOUTHNF-F3530edecde9cd71b79378b290804a96-nJaypHz7%252B2Zfxcl%252BC5JsRiMflPk%253D&sta_dx=480&sta_cs=2917&app_id=250528&logid=5579229560872600550&region=yangquan&isplayer=&devuid=&uva=3040105334&ic=2221887696

尝试播放上面的内容时会出现302错误，但是在postman调用则没有问题。

**Comment by wilsonwu** [comment]
伪造了本地DNS，解决了跨域，但是还是无法播放，不知道什么原因，一直在加载视频
![image](https://user-images.githubusercontent.com/1269496/29811530-6b9620e6-8cd6-11e7-9d02-c9e70f1eb046.png)

**Comment by wilsonwu** [comment]
不知道怎么弄了，可能还是百度的视频streaming的编码方式比较特殊，求高手指导。

**Comment by larry011** [comment]
@wilsonwu 我也来蹭一下，最近对视频直播技术很感兴趣，哈哈。

我先说下我观察到的百度云播放视频流的过程

首先先调接口，获取视频片段列表

![image](https://user-images.githubusercontent.com/10259971/30773964-02bba47e-a0ae-11e7-8fe2-52722edcc293.png)

下图是其中一个流的内容，可以看出是一个flv格式的文件
![image](https://user-images.githubusercontent.com/10259971/30773912-09d59310-a0ad-11e7-857e-a92acc3cfa35.png)

我们将其导出成文件，用ffprobe分析，其实就是一个视频片段，时长为10s
![image](https://user-images.githubusercontent.com/10259971/30774011-ce13b490-a0ae-11e7-9cd2-bf6a176a8e9f.png)

![image](https://user-images.githubusercontent.com/10259971/30774027-e9e0b57e-a0ae-11e7-8aba-bc220ee10804.png)

然后使用mpv测试播放一下，可以正常播放
![image](https://user-images.githubusercontent.com/10259971/30774040-27436272-a0af-11e7-98a8-687e251c2a9a.png)

个人感觉这播放思路借鉴了hls协议，只是百度播放器稍微做了下修改，因为默认chrome是不支持hls协议的

如果说要脱离百度云来播放视频流的话，理论上是可以的，就是分析接口参数这些比较麻烦。。。

**Comment by wilsonwu** [comment]
感谢楼上的同学，我也能顺利拿到，能通过JS封装一下然后在浏览器里播放吗？

**Comment by larry011** [comment]
@wilsonwu 完全可以的，使用flv.js可以完美播放

**Comment by wilsonwu** [comment]
@larry011 我试试，谢谢

**Comment by zzz6519003** [comment]
cool, 顺便请教下aria2是啥。。。

**Comment by zihengcat** [comment]
@zzz6519003 
*Aria2*是一款轻量级，多协议，跨平台（超好用）的**下载工具**哦。
GitHub项目地址：https://github.com/aria2/aria2

**Comment by KellyHwong** [comment]
对，这是个不错的topic。但是有个问题，百度云会把原视频压缩处理的，只有标清和高清。貌似没有超高清的在线播放（其实也是跟百度云服务器带宽限制有关），所以实际使用的时候我都是挂个主机把视频原件下下来的，所以是伪需求，除非百度云解除带宽限制。但是在标清和高清上还是可以应用的，有需求，也有意义。

**Comment by Larry-u** [comment]
@wilsonwu 请问试成功了吗，能否分享下经验，感谢~
