### ISSUE TITLE
更新最新版本后不能下载

### ISSUE THREAD

**Issue by yangting** [acgotaku/BaiduExporter#476]
日志如下

09/07 17:32:50 [NOTICE] CUID#148 - Redirecting to http://d7.baidupcs.com/file/9d730aa0b0739c5e9b91ff35804ec484?bkt=p3-000023d1dbcfdf1ab32c733b77de7ac59dcc&xcode=f968c4f2e36d831f2ac81f943481680b68383760ea2f3a3294b92e463168dc1b&fid=2689951248-250528-899878416119346&time=1504776770&sign=FDTAXGERLQBHSK-DCb740ccc5511e5e8fedcff06b081203-ZcG7T41EwjpdSDUGx7Eb9ujtu94%3D&to=d7&size=1114548696&sta_dx=1114548696&sta_cs=1831&sta_ft=zip&sta_ct=7&sta_mt=1&fm2=MH,Nanjing02,Netizen-anywhere,,beijing,cmnet&newver=1&newfm=1&secfm=1&flow_ver=3&pkey=000023d1dbcfdf1ab32c733b77de7ac59dcc&sl=71499854&expires=8h&rt=pr&r=791578512&mlogid=5791970244025986472&vuk=2689951248&vbdid=-&fin=2.5.8-2016031900-user-511.zip&rtype=1&iv=0&dp-logid=5791970244025986472&dp-callid=0.1.1&tsl=156&csl=156&csign=w2CAPzQ%2FPSdAAaWet1wnZHJb5xI%3D&so=1&ut=6&uter=1&serv=0&uc=2923846618&ic=569907155&ti=f952e1e8796d39133b756d7e5d43018fb900df66aa05b515&by=themis

09/07 17:32:50 [ERROR] CUID#148 - Download aborted. URI=https://pcs.baidu.com/rest/2.0/pcs/file?method=download&app_id=250528&path=%2F2.5.8-2016031900-user-511.zip
Exception: [SocketCore.cc:874] errorCode=1 Failed to receive data, cause: Connection reset by peer

先是跳传到一个地方下载 在来下载不了 好怪阿

**Comment by evolutionjay** [comment]
新版本 chrome 61 禁止了不是Google 商店下载的 crx ， 办法是： 直接吧crx扩展名改为 zip， 然后解压， 然后 chrome 插件面板点 开发者模式， 然后 点 加载已经解压的扩展程序

**Comment by yangting** [comment]
好像这个模块被封杀，目前不能用了。
