### ISSUE TITLE
关于路由无法导入下载（https）

### ISSUE THREAD

**Issue by yilang0001** [acgotaku/BaiduExporter#478]
问题已解决，建议加入Issue 须知
------------------
百度云下载连接为ssl，需检查aria是否支持https连接的下载。（下载测试链接：https://raw.githubusercontent.com/acgotaku/BaiduExporter/master/README.md）

------------------
当时用插件导入下载，路由器(R1d)始终显示error,但电脑版本的aria或IDM确可以满速下载，偶然发现（https://github.com/aria2/aria2/issues/779）是路由器aria缺少部分组件造成。缺少openssl或其他相关文件。
验证：aria下载https的文件看是否会error例如（https://raw.githubusercontent.com/acgotaku/BaiduExporter/master/README.md）
解决（仅tomato）：备份删除opt下的lib文件夹，然后重新下载更新相关组件
```
cd /usr/sbin
sh entware-install.sh
ipkg update
opkg install aria2
```

**Comment by acgotaku** [comment]
你这个是少数。。。
