### ISSUE TITLE
请问aria2.down文件在命令行下怎么用？

### ISSUE THREAD

**Issue by davyzhu** [acgotaku/BaiduExporter#48]
@acgotaku 请问大神，“ARIA2导出”后的aria2.down文件怎么用，我用
$ aria2c aria2c.down 
Exception caught
Exception: [download_helper.cc:417] errorCode=1 Unrecognized URI or unsupported protocol: aria2c.down
谢谢。

**Comment by acgotaku** [comment]
@davyzhu aria2c  -i aria2c.down

**Comment by 1265578519** [comment]
感谢大佬，查了aria2c官方手册都没看到有这个-i参数说明，试了下果然报错，可能版本太低了，，，我升级一下aria2c试试
