### ISSUE TITLE
突然无法通过baiduexporter通过aria2下载文件至openwrt路由器的usb口插入的移动硬盘

### ISSUE THREAD

**Issue by anymee** [acgotaku/BaiduExporter#480]
1. 已经阅读过README
2. 尝试安装最新版本插件
3. 尝试清空浏览器缓存
4. 尝试卸载插件后重新安装

发起 Issue：

1. 下载的baiduexporter来自acgotaku
2. 插件版本号 0.97，浏览器版本号chrome 60 以及firefox 52.3，系统版本号 win8，aria2版本openwrt aria2 1.30
3. 问题：之前使用均正常，可以通过openwrt路由器的aria2下载文件至路由usb口插入的移动硬盘，但在我换了u盘插到路由后，无法下载百度盘的文件到u盘，显示successful，但失败，如图：
![default](https://user-images.githubusercontent.com/31944592/30410226-5a4d1f2a-993c-11e7-8896-b00707609aa6.png)
但可以直接通过把URL(不是百度盘的下载链接)粘贴到aria2 webui的方式下载其他网页(不是百度盘的下载链接)的文件到u盘，设置均没有问题，以为u盘有问题，换移动硬盘后也出现同样问题，无法下载，本来是可以下载的。
另外，用aria2c.exe可以电脑运行下载百度盘的文件至电脑。
4. 问题一直如此，无法解决

请高手指教！谢谢！

**Comment by anymee** [comment]
移动硬盘和U盘的挂载均没有问题，可以通过SMB访问

**Comment by freedomlang** [comment]
直接下载没问题，估计和插件没有关系吧。尝试一下其他的百度盘文件，是不是文件名有特殊字符经过你的webui 后变了

**Comment by anymee** [comment]
@freedomlang 应该没有特殊字符，试过文件夹及单文件（如上图）均无法下载。问题是以前插移动硬盘是可以下载的，换了U盘就不行了，再换成移动硬盘也不行了。其他什么设置都没有改的

**Comment by rijejt523** [comment]
我从上个星期五也是这样，openwrt挂载硬盘，突然不能下载了，所以现在也是很被动。只能直接下载种子，有些种子的速度真是让人难受。

**Comment by freedomlang** [comment]
有没有尝试ui 那里指向aria2 的地址换成本机或者其他机器的看看？

**Comment by anymee** [comment]
@rijejt523 一样的问题，看来不是我一个人有这问题

**Comment by anymee** [comment]
@freedomlang 本机电脑可以下载，通过aria2c.exe

**Comment by acgotaku** [comment]
这个问题 怎么看也不太可能是我的插件问题。。。
你应该去问 aria2c

**Comment by anymee** [comment]
@acgotaku 我也觉得插件没问题的

**Comment by freedomlang** [comment]
在插件那里的地址换个aria2 试试，换成你本机的，不要用路由那个地址试试

**Comment by anymee** [comment]
@freedomlang 本机电脑可以下载，通过aria2c.exe，在插件那里的地址换个aria2 ，可以下载的

**Comment by anymee** [comment]
关键是前些日子还可以下载的，aria2也没有升级或怎样，设置什么都没有改的

**Comment by freedomlang** [comment]
会不会是rpc 挂了

**Comment by anymee** [comment]
咋解决？

**Comment by anymee** [comment]
aria2 webui可以粘贴URL下载文件到u盘或移动硬盘，此处的URL是其他网页的下载链接，不是百度盘的下载链接。

**Comment by freedomlang** [comment]
如果可以的话，openwrt 上的aria2c 有运行记录？
有的话，查查运行记录看看

**Comment by anymee** [comment]
不知道怎么查，我再鼓捣鼓捣看看能不能找到运行记录啥的

**Comment by rijejt523** [comment]
这个应该不是扩展的问题，因为我同时使用baidudl扩展和Ex百度云盘脚本都试过，下载链接直接复制到chrome可以直接使用浏览器下载，但复制到aria2 webui会下载失败，可能百度通过什么方式判断下载器是openwrt的aria2就不给下载了。这块我完全是外行，只能等大神解决了。

**Comment by anymee** [comment]
综合判断应该是百度搞的鬼，路由器挂盘aria下载的好日子到头了

**Comment by dddddavy** [comment]
我现在进入百度网盘插件会显示加载成功 一切正常 但是选中一个文件/文件夹之后 插件的按钮就没有了
进入分享页面也会显示加载成功 但是插件的按钮也没有出来

**Comment by anymee** [comment]
@dddddavy  你的这个问题通过升级浏览器和插件可以解决的

**Comment by rijejt523** [comment]
今天无聊再次测试使用**EX-百度云盘**脚本使用aria2下载百度云，发现只要将生成的下载链接https改为http就可以下载了，16线程，每线程80k，单任务1.2m左右，你可以试试

**Comment by anymee** [comment]
试了下，可以下载，但会断断续续的，速度也不快的。

**Comment by rijejt523** [comment]
aria2要设置单任务16个线程才行，因为百度限速单线程80K，16个线程刚好可以跑到1.25m/s左右。openwrt的aria2单任务最高设置16个线程。

**Comment by anymee** [comment]
好的，我试试

**Comment by tristanSIF** [comment]
我也遇到这红叉问题,看了下aria2的日志, 不支持https导致 [errorCode=1 https is not supported yet.
然后在aria2的git上翻到了说明,(aria2git页搜索with-ca-bundle出来的那附近一段)
需要在编译aria2时加证书路径或者运行时添加选项

**Comment by freedomlang** [comment]
既然这样，执行aria2c --version 检查一下，看Enabled Features: 里面是否有HTTPS ？
<img width="682" alt="2017-10-21 00 08 33" src="https://user-images.githubusercontent.com/11409069/31830895-37807994-b587-11e7-91f1-5704cf45009c.png">

没有的话，重新编译安装？

**Comment by anymee** [comment]
@tristanSIF 编译不会，请问你所说的运行时添加选项如何操？谢谢！

**Comment by anymee** [comment]
@tristanSIF 编译不会，请问你所说的运行时添加选项如何操？谢谢！

**Comment by anymee** [comment]
@不会编译，请问有编译好的openwrt可用的最新版aria2吗？谢谢！

**Comment by anymee** [comment]
@freedomlang

**Comment by tristanSIF** [comment]
@freedomlang 安装了libssl-dev(或libgnutls-dev)之后重新编译, 现在不会出现红叉了^.^  
@anymee 运行时添加选项那个,我理解错了,和这个红叉问题不是同一个..还是需要重新编译....你先看看你的aria2是否支持https, 像freedomlang图里那样

**Comment by freedomlang** [comment]
@anymee 没在openwrt 上用过aria2，爱莫能助。。。也许可以下载到U 盘，然后再编译安装？

**Comment by anymee** [comment]
@freedomlang 谢谢啦！

@tristanSIF 我不会编译，有没有编译好的openwrt可以直接luci安装的可用的aria2，现在用的是上面提到的会出错的，谢谢啦！
