### ISSUE TITLE
百度网盘选择需要下载的文件后，导出下载button消失，只有刷新页面才出来

### ISSUE THREAD

**Issue by RyanZhu1024** [acgotaku/BaiduExporter#481]
1. 您下载的内容地址
百度网盘个人主页
2. 插件版本号，浏览器版本号，系统版本号
0.8.5
3. 列举出现问题的详细步骤
打开主页，button显示，选择文件，button消失
4. 描述能否复现问题
百度网盘个人主页选择需要下载的文件后，导出下载button消失

**Comment by acgotaku** [comment]
最新的都 0.9.7了好么。。。

**Comment by laris** [comment]
confirmed with Version:0.9.1 更新日期: 2017/02/07
