### ISSUE TITLE
百度云盘失效

### ISSUE THREAD

**Issue by AnthonyZhai** [acgotaku/BaiduExporter#482]
1. 您下载的内容地址
2. 插件版本号，浏览器版本号，系统版本号
    网盘助手 0.8.5
    浏览器版本 Chrome 61.0.3163.91
    系统版本 macOS Sierra 10.12.6
    aria2 1.32.0
3. 列举出现问题的详细步骤
    a.打开百度云主页，能够正常显示“导出下载”按钮
    b.选择具体文件或文件夹后，“导出下载”按钮消失，可能是被百度云盘自己的按钮“下载”、“删除”、“重命名”等顶替掉
4. 描述能否复现问题
    已经出现很长时间了，大概从17年9月初开始就一直这样了
----------

**不符合上述条件的Issue将被无理由关闭**

**Comment by acgotaku** [comment]
???

**Comment by Saul-Mirone** [comment]
是出现了这个问题，当选择文件后，“导出下载”按钮就消失了。

**Comment by Saul-Mirone** [comment]
升级一下就好了

**Comment by qianbinbin** [comment]
楼上，已经一个多月没更新了，哪来的升级
