### ISSUE TITLE
百度云多文件点击ARIA2 RPC，显示成功，但实际并不能全部下载，会漏掉很多地址

### ISSUE THREAD

**Issue by hahaapi** [acgotaku/BaiduExporter#483]
如一部剧20集，点击ARIA2 RPC，提示成功，但是aria2实际只下载了16集左右，中间有些集没有下载

**Comment by acgotaku** [comment]
那就再点一次（

**Comment by waeshang** [comment]
滚动页面内“文件列表”至底端再全选就不会漏了哦。
另外我发现，导出为“aria2.down”文件后加载下载列表竟然能满速。可惜仅限分享状态下才能满速，而且要退出登录才行。
不知道作者能不能实现在登陆状态下直接获取分享下载地址呢

**Comment by acgotaku** [comment]
@waeshang 获取分享地址次数过多百度服务器会出验证码的 自己网盘的请求 没有限制
