### ISSUE TITLE
如何更改-s10 -k1M -x16 这个默认配置

### ISSUE THREAD

**Issue by mr0112358** [acgotaku/BaiduExporter#484]
因为在aria2编译的时候把最大线程数调高了, 所以想在插件里把-s10 -k1M -x16 改一下, 不知道需要修改何处的代码

**Comment by qianbinbin** [comment]
aria2c启动时有参数可以控制
如果你是用配置文件启动的，就在文件里改

**Comment by mr0112358** [comment]
问题在于插件推给RPC的配置不是和启动文件那个没什么关系啊

**Comment by acgotaku** [comment]
RPC模式 是没有限制的 用的软件默认设置。。。
