### ISSUE TITLE
请问“要获取Cookies”具体指哪些，是否可以手动输入？

### ISSUE THREAD

**Issue by hguandl** [acgotaku/BaiduExporter#485]
我是 Safari 用户，说明里写到“因为要获取Cookies，无法单纯使用脚本实现，必须插件模式加载”，可能因此这个拓展就没有能跨各种浏览器的 Tampermonkey 脚本的版本。请问这些 Cookies 具体指哪些？我看导出的链接里面有 BDUSS 和 pcsett。如果能手动添加这两项 cookies 的话，此拓展的纯脚本移植是否可行？

**Comment by alemonmk** [comment]
嗯...
> 可以**方便**的把百度网盘的下载地址导出

自己找 cookie 手動輸入還能叫方便嗎?

> Safari : Install Chrome or Firefox on Mac.

系統裏有多瀏覽器不是罪...
