### ISSUE TITLE
不能下载了

### ISSUE THREAD

**Issue by BH1ENO** [acgotaku/BaiduExporter#486]
您好。首先感谢您的工作，一直用你的插件下载网盘，很方便。
但最近几个月 ，磁力链接可以正常下载，百度盘直接报错。

已经更新到时最新的0.9.7插件+YAAW，在路由器上有Aria2 1.18.7。
报“下载成功，赶紧去看看吧”，但过去看就已经出错停止了了。

下面是百度盘下载：
 Warriors S01E02 Shogun.mkv
 0 KB
0%
Status
Files
Size: 0 KB (0 @ 1.00 MB)
Status: error
Dir: /mnt/sda1/_Aria2
Bitfield:

下面是磁力：
BBC.British.Empire.Heroes.And.Villains.A.Timewatch.Guide.720p.HDTV.x264.AAC.MVGroup.org.mp4
 233.58 MB / 879.73 MB ETA: 2h34m18s
26.55%
 71.46 KB/s  2  2
Status
Files
Options
Peers
Size: 879.73 MB (880 @ 1.00 MB)
Status: active
Dir: /mnt/sda1/_Aria2
Bitfield

**Comment by BH1ENO** [comment]
![default](https://user-images.githubusercontent.com/17289895/31044454-2c475d2a-a602-11e7-92cf-d1af46b90e23.png)

**Comment by BH1ENO** [comment]
![clip000](https://user-images.githubusercontent.com/17289895/31044540-d57b3262-a603-11e7-8ca9-941b757395ab.jpg)

**Comment by acgotaku** [comment]
@BH1ENO 我这边随便测试了一个资源 是可以下载的 你确定不是自己资源问题？

**Comment by BH1ENO** [comment]
资源已经在我百度盘里面了，以前下载都没问题。你看看我的设置有什么问题吗？

**Comment by acgotaku** [comment]
你不先试试其他资源有没有问题？

**Comment by BH1ENO** [comment]
不行，我又试了一下。换了一个账号也不行。你有日志吗？

**Comment by acgotaku** [comment]
我哪来的你电脑的日志。。。。

**Comment by BH1ENO** [comment]
我是说你的插件有没有错误日志，可以看到哪个地方出了问题。

**Comment by acgotaku** [comment]
没有 你这个 基本上是aria2c的问题 和插件没关系

**Comment by BH1ENO** [comment]
我切换到本地电脑的aria2c，可以正常下载了。
可是很奇怪，路由器一直没动过，之前正常下载。而且路由器下载磁力链和其它文件都正常。我重启了路由器也不行。

**Comment by acgotaku** [comment]
那你重置下所有设置 试试

**Comment by BH1ENO** [comment]
我把插件卸了重新安装了。我再重置一下试试。

**Comment by BH1ENO** [comment]
我把路由器固件换了一个，现在正常了。非常感谢。
