### ISSUE TITLE
我发现一个有趣的问题。。

### ISSUE THREAD

**Issue by SanFordy** [acgotaku/BaiduExporter#487]
请确保以下几点：

1. 已经阅读过README
2. 尝试安装最新版本插件
3. 尝试清空浏览器缓存
4. 尝试卸载插件后重新安装

发起 Issue 时，请提供：

1. 您下载的内容地址
2. 插件版本号，浏览器版本号，系统版本号
3. 列举出现问题的详细步骤
4. 描述能否复现问题

----------

**不符合上述条件的Issue将被无理由关闭**

账号 A 开百度超级会员之前用这个下载速度很快，开过超级会员且到期之后再用这个进行下载，速度变得很慢。作为对比，我用账号 B 下载同一资源：一个200K，一个2M。

<img width="747" alt="2017-10-01 8 05 22" src="https://user-images.githubusercontent.com/12559436/31050542-f53db61a-a612-11e7-9df8-32573279b2d0.png">

**Comment by acgotaku** [comment]
不是废话么。。。。 只有充钱了才能变强。。。
