### ISSUE TITLE
Chrome  61.0.3163.100 64bit 无法加载安装，显示“无法为内容脚本加载 JavaScript“dist/js/inject.js””

### ISSUE THREAD

**Issue by santaclausbaby** [acgotaku/BaiduExporter#488]
1.直接选择“加载已解压的扩展程序”，显示：
无法为内容脚本加载 JavaScript“dist/js/inject.js”。

2.选择“打包扩展程序”，依然显示：
无法为内容脚本加载 JavaScript“dist/js/inject.js”。

请解决，谢谢！

**Comment by acgotaku** [comment]
??? dist 那个是dev分支的东西吧 你下载错了吧。。。。

**Comment by santaclausbaby** [comment]
好的，我以为dev分支可以当night build来用的，那我去下载主分支，谢谢！

**Comment by acgotaku** [comment]
开发分支 是因为现在主分支的代码太乱了 所以重构中。。。 目前还不能用
