### ISSUE TITLE
firefox异常

### ISSUE THREAD

**Issue by qweaszxcdf** [acgotaku/BaiduExporter#489]
请确保以下几点：

1. 已经阅读过README
2. 尝试安装最新版本插件
3. 尝试清空浏览器缓存
4. 尝试卸载插件后重新安装

发起 Issue 时，请提供：

1. 您下载的内容地址
2. 插件版本号，浏览器版本号，系统版本号
3. 列举出现问题的详细步骤
4. 描述能否复现问题

----------

**不符合上述条件的Issue将被无理由关闭**
链接：http://pan.baidu.com/s/1dFjcGBv 密码：jr54
firefox 未知错误
chrome 正常下载

**Comment by acgotaku** [comment]
firefox的支持在dev分支重构完成之后进行 目前先用 Chrome吧

**Comment by OscarGong** [comment]
Firefox 57 已经 release 了，请问有计划吗？

**Comment by acgotaku** [comment]
这个月支持

**Comment by acgotaku** [comment]
@OscarGong 试试载入 项目里的release文件夹

**Comment by OscarGong** [comment]
@acgotaku 我试下，感谢工作 🙏

**Comment by qweaszxcdf** [comment]
firefox 52.4 
个人主页正常
分享页面导出下载 控制台显示 Array [ Object ]  share.js:1:25762

**Comment by acgotaku** [comment]
@qweaszxcdf 给个分享页面的地址？

**Comment by qweaszxcdf** [comment]
加密的有问题 
链接: https://pan.baidu.com/s/1nviiEST 密码: vpv4

**Comment by acgotaku** [comment]
@qweaszxcdf 为啥我依旧可以成功导出。。。
要不是运行下开发版？ https://github.com/acgotaku/BaiduExporter/blob/master/.github/CONTRIBUTING.md

**Comment by qweaszxcdf** [comment]
更新至52.5esr 问题似乎解决了
