### ISSUE TITLE
新打开的百度网盘都要等很久

### ISSUE THREAD

**Issue by leitwolf** [acgotaku/BaiduExporter#49]
我每次打开网盘，都要等很久才初始化完成。
加载的地址类似为：http://qd.cache.baidupcs.com/monitor.jpg?xcode=1a81b0bbd448fc36f65202d7e8f159404c932f26aaa77f9c&t=14321216011432121603023
这是什么原因呢？

环境：os x 10.10.3 firefox 38

**Comment by acgotaku** [comment]
@leitwolf 这网址哪来的。。。  我打开都好慢

**Comment by leitwolf** [comment]
监听百度网盘网页加载的东西，加载完这个插件才初始化完成。

**Comment by acgotaku** [comment]
@leitwolf 我在百度网盘首页怎么没有发现 我百度盘主页加载的也很快啊

**Comment by leitwolf** [comment]
那可能只是个人情况了。

**Comment by CzBiX** [comment]
我也有这个问题，而且这个问题和插件无关。是网页上用于测试你连接哪个 CDN 最快的方法，
可能是百度自己的 DNS 配置有问题，导致这个域名 IP 没法正常访问。
由于扩展是等待页面载入完成才会加载，所以要等这个请求超时才会初始化完成。

你可以手动添加条 host 记录，IP 用 nj.cache.baidupcs.com 解析出来的即可。(大致有 bj/qd/nj 等)

**Comment by leitwolf** [comment]
好像没什么用啊。设置了之后它还是在那里解析。
10.215.7.38  nj.cache.baidupcs.com
111.13.100.100  bj.cache.baidupcs.com
27.221.38.117  qd.cache.baidupcs.com
27.221.36.19  small.cdn.baidupcs.com

**Comment by CzBiX** [comment]
@leitwolf 设置成一个你能在浏览器中快速打开的 IP。
比如我设置的是 58.217.200.14

**Comment by leitwolf** [comment]
这些IP我是用域名解析查询到的：http://tool.chinaz.com/dns/
你这个IP是怎么得到的？

**Comment by acgotaku** [comment]
@leitwolf 是windows的话 直接打开 cmd 使用nslookup nj.cache.baidupcs.com 啊

不过我这边貌似也解析不出来。。。

**Comment by CzBiX** [comment]
想起来了，尝试解析这些域名得到的：

 * p.baidupcs.com
 * nj.baidupcs.com
 * bj.baidupcs.com
 * qd.baidupcs.com
 * qd.cache.baidupcs.com
 * nj.cache.baidupcs.com
 * cdn.baidupcs.com
 * hot.baidupcs.com
 * hot.cdn.baidupcs.com
 * www.baidupcs.com
 * d.pcs.baidu.com
 * pcs.baidu.com

参考：http://www.aikaiyuan.com/7276.html

**Comment by leitwolf** [comment]
都木有用。。。
10.215.7.38 nj.cache.baidupcs.com
111.13.100.100 bj.cache.baidupcs.com
27.221.38.117 qd.cache.baidupcs.com
27.221.36.19 small.cdn.baidupcs.com
119.75.219.40 p.baidupcs.com
58.217.200.14 nj.baidupcs.com
220.181.164.59 bj.baidupcs.com
27.221.36.17 qd.baidupcs.com
180.149.131.62 cdn.baidupcs.com
58.217.200.18 hot.baidupcs.com
180.149.131.62 hot.cdn.baidupcs.com
180.97.33.211 www.baidupcs.com
220.181.164.59 d.pcs.baidu.com
58.217.200.16 pcs.baidu.com

**Comment by acgotaku** [comment]
@leitwolf 那就直接写成 127.0.0.1 反正也没啥用

**Comment by leitwolf** [comment]
@acgotaku，哈哈，就这样办，果然好使
127.0.0.1 nj.cache.baidupcs.com
127.0.0.1 bj.cache.baidupcs.com
127.0.0.1 qd.cache.baidupcs.com

**Comment by acgotaku** [comment]
@leitwolf 搞定了的话 就关掉这个 issue吧
