### ISSUE TITLE
mac os 10.13 无法使用了

### ISSUE THREAD

**Issue by since2004** [acgotaku/BaiduExporter#492]
请确保以下几点：

1. 已经阅读过README
2. 尝试安装最新版本插件
3. 尝试清空浏览器缓存
4. 尝试卸载插件后重新安装

发起 Issue 时，请提供：

大神，在这个版本的mac os系统下面，safari 、chrome版本皆无法使用了。chrome不勾选百度云盘文件的情况下会显示出来“导出”选项，如果勾选皆不显示了
----------

**不符合上述条件的Issue将被无理由关闭**

**Comment by Gabrielvon** [comment]
@since2004 请问你safari上的插件是怎么设置的？尤其是user-agent这个，需要修改成百度盘的吗？

顺便问一下，我装了safari的插件后，打开百度盘的网页，没有新的按钮出现。是新版本的问题，还是我没设置正确？

**Comment by AMENOMORI** [comment]
我也遇到了相同的问题。希望能够尽快解决。

**Comment by renyufei8023** [comment]
我的可以正常使用的

**Comment by Gabrielvon** [comment]
@renyufei8023 请问你用的是safari的插件吗？想请教下插件里面装了就能用吗？需要在设置里面改什么参数吗？

**Comment by renyufei8023** [comment]
我用的chrome  用的master分支的  dev分支的在10.13上面好像就是不能用  你先确定看看是不是用的dev分支  是的话切换分支试一下

**Comment by Gabrielvon** [comment]
谢谢，chrome我试过了，装了0.9.7版本，之后按照步骤点到Aria RPC那里然后提示说“没打开aria”，我在terminal检查了进程确定打开了，不知道是不是需要翻墙。我再研究下，谢谢。

**Comment by scaactk** [comment]
chrome Mac 10.13 各项均为最新版，aria2 本地报错Intelnet server error 百度云网页端报错未启动aria2

**Comment by acgotaku** [comment]
试试新版本？

**Comment by Melaleucake** [comment]
<img width="761" alt="570c3739-9394-4431-b3e5-44ab62a40e9a" src="https://user-images.githubusercontent.com/17722672/32854449-940160b4-ca79-11e7-87ca-a97394d8754c.png">
最新版chrome; MacOS 10.13.1

**Comment by acgotaku** [comment]
都写了说明是 release文件夹………
