### ISSUE TITLE
Windows Server 2016 无法使用

### ISSUE THREAD

**Issue by Setsuna-Kitahara** [acgotaku/BaiduExporter#493]
可以新建任务，但是速度为0，把任务交给同网络下的linux主机即可正常下载
内容地址：https://pan.baidu.com/s/1o7b3Sqm?errno=0&errmsg=Auth%20Login%20Sucess&&bduss=&ssnerror=0 密码：nfpf
插件版本 0.9.7 浏览器版本 chrome 61.0.3163.100 系统版本 Windows Server 2016 Essentials (14393.1770)
出现问题的详细步骤：就是正常下载文件
描述能否复现问题：该问题必然出现

**Comment by acgotaku** [comment]
即使你这么说。。。 你这个环境我也很难测试啊 QAQ

**Comment by Setsuna-Kitahara** [comment]
是系统版本太特别了吗……
一般我都是当作服务器版本的WIN10用的

**Comment by acgotaku** [comment]
我觉得应该是你自己服务器的网络 原因 这个插件的职责只是把任务交给Aria2c而已
