### ISSUE TITLE
请问添加了多个RPC，怎样对应配置下载路径？

### ISSUE THREAD

**Issue by KingOldFive** [acgotaku/BaiduExporter#494]
您好，感谢您开发分享的插件！
添加了两个RPC
怎样对应配置第二个的下载路径呢？

**Comment by acgotaku** [comment]
你要配置啥？ token？

**Comment by KingOldFive** [comment]
“下载路径”这项配置可以留空是吧！
刚刚试了下，留空就下载到aria2服务端配置的路径了。
网上教程都配置“下载路径”了，本以为是必须配置项
添加多个RPC，没法单独配置各自的“下载路径”。

**Comment by acgotaku** [comment]
下载路径默认为空 会下载到服务器指定的位置 如果你要下载到特殊的位置 再制定

**Comment by acgotaku** [comment]
默认多RPC 下载到每个RPC指定的默认路径啊。。。

**Comment by KingOldFive** [comment]
以为“下载路径”是必须配置项，配置了第一个RPC的路径，第二个不知道该怎么配置了。
现在都留空默认设置了，谢谢！！
