### ISSUE TITLE
(已修复！感谢大神的努力！)0.9.9一直显示在“获取下载地址中”无法下载，MacOS 10.13.1

### ISSUE THREAD

**Issue by kb24mvp** [acgotaku/BaiduExporter#498]
今天早上自动更新了0.9.9，然后就出现这个问题，之前0.9.5-0.9.7都没有问题。

求问，如何下载历史版本？

好快就解决了，真的不得不佩服大神，这个插件永久了真是离不开了，太方便太好用，感谢大神的无私奉献！

**Comment by crystoneme** [comment]
同问，我也遇到了，然后git pull后就没法用了

**Comment by yujincheng08** [comment]
look at my pull request #497

**Comment by zczyzi** [comment]
同样问题，我还以为是自己设置有问题

**Comment by acgotaku** [comment]
0.9.9 重构了 可能没考虑一些特殊情况
这就更新。。。 老版本在 bak分支下

**Comment by 1368129224** [comment]
0.9.9 chrome x64 win10一直在"获取下载地址"
（用了很久了，今天才找到原作者。。。来晚的感谢！）

**Comment by acgotaku** [comment]
@1368129224 你再试试  0.9.10?

**Comment by 1368129224** [comment]
@acgotaku 已经可以导出下载了，谢谢！

**Comment by mukaiu** [comment]
0.9.10 没问题，赞一个

**Comment by Redroof** [comment]
插件版本0.9.10，系统MacOS Sierra 10.12，下载文件不出错，下载文件夹会显示“正在获取文件列表a/b”，其中a的增速小于b，不断增加而不停止（即使文件夹里只有一个文件）。
BTW，谢谢作者们的无私奉献～

**Comment by acgotaku** [comment]
@Redroof 分享页面还是自己网盘页面？

**Comment by e11evenChan** [comment]
macOS 10.13.2 Chrome版本 64.0.3260.2Dev 插件版本0.9.10，可以下载文件，但无法打开插件设置，还有插件位置会把二维码和举报按键挤错位
![1510659009925](https://user-images.githubusercontent.com/19811317/32777790-85f37596-c972-11e7-964e-2be6c5daf7ef.jpg)

**Comment by acgotaku** [comment]
@Redroof 这个问题已经修复
