### ISSUE TITLE
导出下载时提示输入验证码

### ISSUE THREAD

**Issue by Mizuheart** [acgotaku/BaiduExporter#50]
你好，请问，导出下载时提示要输入验证码是什么情况？是不是我电脑上什么地方的设置不对了？
详细信息如下：

所下载的文件链接（这个链接不是我的，是别人分享的，在自己的网盘页面里面下载东西没有验证码提示）： pan.baidu.com/s/1eQAOpSu

已登录自己的百度账号（后来我又退了重新试，还是要验证码）

我的设置：

RPC：
http://token:Assass1n@localhost:6800/jsonrpc
文件夹打包下载:	否
文件夹结构层数：0	(默认 0 表示不保留,-1 表示保留完整路径)
递归下载延迟：300	(单位: 毫秒) 测试连接，成功显示版本号。
下载路径:	（这个没设置）
User-Agent :	netdisk;5.2.6;PC;PC-Windows;6.2.9200;WindowsBaiduYunGuanJia（默认没动）
Referer ：http://pan.baidu.com/disk/home（默认没动）

**Comment by acgotaku** [comment]
@Mizuheart  需要的话你就输入不就好了 提示输入验证码是因为你在一段时间的下载请求过于频繁导致的

自己网盘的话 再频繁也属于合理范围 所以不会提示输入验证码  输入验证码之后就正常下载了啊

不影响你使用啊

**Comment by Mizuheart** [comment]
话虽这么说没错。。。。

是这样的，上次我也遇到过一次这样类似的问题，那次也是别人的外链，忘记登没登录了，但是下载时提示有验证码（那次是一大串文件啊QAQ）。。。我也考虑过请求过于频繁的原因，可是其余的外链下载起来没有提示，而且最关键的，那天出验证码前我没有下过度盘的东西，验证码就莫名其妙的出来了→_→

上次那个验证码问题持续了几天，就莫名其妙的好了，你敢信么。。。他自己好了。。。qwq（难不成只是度盘抽风么 = =||||）

刚好这次遇到同样的问题，顺路来打听一下开发者有没有线索。。没别的意思，你这个插件超好使的，完美解决了度盘限速限下载的问题 - -+


2015-06-06 10:19 GMT+08:00 雪月秋水 <notifications@github.com>:

**Comment by acgotaku** [comment]
@Mizuheart 正因为是一大串文件 每个文件的下载地址我都会请求一次

所以会导致出现验证码的问题 这时候就可以先保存到自己网盘 然后再下载就可以啦～

百度的出现验证码机制我也不是太清楚  但是遇到频繁出现验证码的情况我也是保存到自己网盘再下载的

**Comment by Mizuheart** [comment]
这样啊。了解了。
Close了吧。 =)

2015-06-06 10:36 GMT+08:00 雪月秋水 <notifications@github.com>:
