### ISSUE TITLE
Could not load javascript 'js/start.js' for content script

### ISSUE THREAD

**Issue by GambitX3** [acgotaku/BaiduExporter#500]
I have issue on installing the newer version of 0.9.10. When i load the "chrome" folder into the extension using the "Load unpacked extension" in Google Chrome, I obtained the following error:
"Failed to load extension from: D:\Libraries\Desktop\chrome
Could not load javascript 'js/start.js' for content script."

This issue does not happen when I installed the older version of 0.9.7.
My current Google Chrome version is 62.0.3202.94, using Windows 8.1.

Please advise. Thanks in advance.

![image](https://user-images.githubusercontent.com/33653470/32771905-3d015b22-c95f-11e7-933d-2da12457097d.png)

**Comment by acgotaku** [comment]
Please read : https://github.com/acgotaku/BaiduExporter/blob/master/.github/CONTRIBUTING.md

**Comment by GambitX3** [comment]
Thanks for commenting. Actually, I am not a programmer and don't understand all the languages. Do you mind explain what is causing the error of loading the extension?

**Comment by acgotaku** [comment]
Because the new version only support install by CRX file.
If you want to load from fold, you have to run a little of command to compile code.

**Comment by GambitX3** [comment]
I have tried to drag and install using the BaiduExporter.crx according to the readme.md, however, Google Chrome said that the extension isn't from the web store and disabled it.

**Comment by acgotaku** [comment]
You can not enable it? Can you give me a screenshot about this situation  and your chrome version.

**Comment by GambitX3** [comment]
Is it only me who cannot install the crx file? I enabled developer mode when dragging the .crx file into Chrome. Still the extension is disabled by Chrome. If you look at the image below, the enable button is greyed out, which cannot be clicked and ticked. Please help! Thanks!
![image](https://user-images.githubusercontent.com/33653470/32775089-6b35d392-c969-11e7-9034-b0d982ba0d2b.png)

**Comment by GambitX3** [comment]
My Chrome version is 62.0.3202.94

**Comment by acgotaku** [comment]
@GambitX3 OK. I knew. I will release a developer version for you.

**Comment by GambitX3** [comment]
@acgotaku OMG! You are really kind and helpful. Thanks alot!

**Comment by acgotaku** [comment]
@GambitX3 At Now, you can load from release folder. https://github.com/acgotaku/BaiduExporter/tree/master/chrome/release

**Comment by GambitX3** [comment]
@acgotaku Thanks again! It works like a charm!
