### ISSUE TITLE
添加aria2c RPC密钥支持

### ISSUE THREAD

**Issue by a17uk** [acgotaku/BaiduExporter#504]
目前使用的版本是0.9.10版，我的aria2c部署在VPS上，设置了RPC密钥，这个版本好像只是为本地aira2c设计的，并不支持密钥，所以无法连接VPS上的aria2c。

建议以后版本添加aria2c RPC密钥支持。

**Comment by guliujian** [comment]
支持在rpc 里边使用token啊 例如 http://token:xxxxx@xxx <http://token:xxxxx@xxx/>
On Nov 16, 2017 4:56 PM, "a17uk" <notifications@github.com <mailto:notifications@github.com>> wrote:
目前使用的版本是0.9.10版，我的aria2c部署在VPS上，设置了RPC密钥，这个版本好像只是为本地aira2c设计的，并不支持密钥，所以无法连接VPS上的aria2c。

建议以后版本添加aria2c RPC密钥支持。

**Comment by a17uk** [comment]
谢谢，原来rpc连接可以这样用
