### ISSUE TITLE
manifest.json 里静态资源的路径不对吧，chrome 无法加载扩展

### ISSUE THREAD

**Issue by falconchen** [acgotaku/BaiduExporter#505]
使用的commit 
9d5a5e401f9

**Comment by acgotaku** [comment]
我测试了是可以的 报错的截图有么？

**Comment by falconchen** [comment]
![snip20171118_1](https://user-images.githubusercontent.com/981375/32980469-d027caae-cca1-11e7-9aa2-5ee74e56be22.png)

![snip20171118_2](https://user-images.githubusercontent.com/981375/32980475-f49a0a8c-cca1-11e7-8f91-2d0203d79471.png)

**Comment by JasonKhew96** [comment]
@falconchen 是 "./chrome/release/" 文件夹吧

**Comment by falconchen** [comment]
可以了，谢谢～ 
我弄错了，不好意思
