### ISSUE TITLE
指定下载使用的线程数

### ISSUE THREAD

**Issue by kkren** [acgotaku/BaiduExporter#506]
1. 您下载的内容地址 适用于任何内容
2. 插件版本号，浏览器版本号，系统版本号 0.9.10 ，Firefox 59a , windows 10 1709

----------
能否在添加任务的时候选择64线程下载（max-connection-per-server=64），我希望在下载其他任务的时候使用16线程，但在百度云任务使用64线程

**Comment by acgotaku** [comment]
Use http://localhost:6800/jsonrpc#max-connection-per-server=5&split=10 set download options for specific file.
我这不是有说明么。。。

**Comment by sarkdavidson** [comment]
超线程相关；

- BaiduExporter Version: 0.9.10
- aria2 1.33.1 

#max-connection-per-server=10 可以正常导出下载；
#max-connection-per-server=16 可以正常导出下载，实际线程数为10；
#max-connection-per-server=64 无法正常导出下载失败! 是不是没有开启 Aria2?；


_而使用 baidudl 相同环境下，默认就是使用128线程下载，速度稳定，满速_ 
请问作者是我哪里设置不正确吗？
