### ISSUE TITLE
Firefox 版本出現「已封鎖跨來源請求」的問題

### ISSUE THREAD

**Issue by ivangundampc** [acgotaku/BaiduExporter#51]
已確定 rpc-allow-origin-all 設置為 true，但主控台仍然顯示著「已封鎖跨來源請求: 同源政策不允許讀取 http://localhost:6800/jsonrpc 的遠端資源。（原因: CORS 請求失敗）。」的字樣，無法導出至 aria2，求解，謝謝！

**Comment by acgotaku** [comment]
@ivangundampc  可能是你firefox安全策略过高？

**Comment by acgotaku** [comment]
@ivangundampc 有没有装 Noscript？

**Comment by ivangundampc** [comment]
似乎的確是 Noscript 的問題，問題已經解決了，感謝啊
