### ISSUE TITLE
可以添加配置secret的选项吗

### ISSUE THREAD

**Issue by DogeWatch** [acgotaku/BaiduExporter#510]
最新版本，我手动搜索所有的rpc链接，在前面添加了secret，但是下载时获取下载地址就没有然后了。因为不太清楚该怎么修改，所以希望能出一个可配置的文件来配置secret就好了。

**Comment by acgotaku** [comment]
Set --rpc-secret=<secret> if you are using aria2 1.18.4(or higher) with 'JSON-RPC PATH' like http://token:secret@hostname:port/jsonrpc

不都说了。。。
