### ISSUE TITLE
保留目录结构跟SVIP的选项被拿掉了吗？

### ISSUE THREAD

**Issue by buliaoyin** [acgotaku/BaiduExporter#511]
Windows 10， chrome

发现新版本的选项中没有SVIP跟是否保留目录结构的选项了，是新的版本专门删掉了还是出bug了呢？

**Comment by acgotaku** [comment]
删除掉了 SVIP和普通用户没必要区分 下载速度不会有很大差距
保留目录结构考虑重新添加 但感觉只需要对自己网盘生效 分享链接没有太大意义

**Comment by buliaoyin** [comment]
嗯，对自己的网盘来说，保留目录结构还是挺有用处的

**Comment by acgotaku** [comment]
@buliaoyin 近期会重新加上 期待更新吧（

**Comment by buliaoyin** [comment]
好的，辛苦了！
