### ISSUE TITLE
BaiduExporter for Android

### ISSUE THREAD

**Issue by pac20** [acgotaku/BaiduExporter#513]
Hi acgotaku.I free user Baidu Cloud.Currently I'm testing cloud.Could you, or yourself, create or advise whom to contact about creating an application or an add-on to a mobile browser for the system android?

**Comment by acgotaku** [comment]
I do not have any android develop ability, so I can not help you.

**Comment by pac20** [comment]
Very sorry. But I want you to know that Aria2 is trying to work in android.

**Comment by acgotaku** [comment]
Of course. I knew. But I can use Baidu Cloud on PC. Why I have to use android for download?

**Comment by pac20** [comment]
Just came into my situation it was necessary to transfer 160 GB of working software.Well, I dug and found 1TB.And decided to test not only on the PC but also on Android.I prefer to use a verified software and it's not always possible for a client to put anything on past what is required.And as I understand the PC world is gradually shifting to the android platform.Or maybe it's not like that?

**Comment by shui288** [comment]
安卓手机一直BaiduExporter与yaaw配合在用着。

请更新yaaw-----下载youtube视频，
如视频文件名称是---中文的，不正常，文件名为backvedio，
如视频文件名称是---英文的，为正常，文件名为Despacito - Luis Fonsi Cover Trung Luong version (Dan Nguyet).mp4

谢谢

**Comment by shui288** [comment]
将yaaw换成https://chrome.google.com/webstore/detail/aria2c-integration/jpogdnhieffjholfeomcnbjanmgahndg
Aria2c Integration_1.7.1，其它不变，下载youtube视频中英文件名都正常。

请参考下，谢谢！

**Comment by pac20** [comment]
I found how to download via firefox on Android.I'm testing.

**Comment by shui288** [comment]
@pac20 
Yandex  browser

**Comment by pac20** [comment]
shui288 
Oh no.Firefox steers.Downloading firefox for android.You put in it addition BaiduExporter.
Downloading Aria2 for Android https://play.google.com/store/apps/details?id=net.sf.aria2 or
https://sourceforge.net/projects/aria2-android/files/?source=navbar .For the settings you download https://play.google.com/store/apps/details?id=com.gianlu.aria2app or http://website.gianlu.xyz/apps/?id=aria2app .
Installing Aria2 for Android.And you do the initial settings.
If Android 6.0 with an integrated memory card in the system, then the application must be moved to the memory card.And after transferring to the memory card, you must reset the application settings.
Setting Aria2 for Android
In Aria2 : 
Download catalog : storage/emulated/0/Download/Aria2Download (for Android 6.0)
Keep the processor active: yes
When you stop: yes
Access from outside: no
Network Selection: aria2
In Graphical interface: 
Secret token: null
And I recommend downloading the terminal for android.To have a visual download tracking process available.
After the configuration, you need to start and stop Aria2 so that the aria2c.txt file is created in the Aria2Download.
Next, you need to open the aria2c.txt and write in her check-certificate = false .And save.
It is necessary that there is no verification of the ssl certificates.
Next, install Aria2app.And set it up.
Setting Aria2app for Android.
Terms of connection: Any
Profile name: What we want
Сonnection: 
HTTP
Ip address : 127.0.0.1
Port: 6800
SSL Encryption: no
Authentication: no
DirectDownload: no
And Test
Adding a profile
After the launch we go to Global settings: 
connect-timeout: 1
max-connection-per-server-:16
After we go to firefox.
In firefox we work only in the full version of the site.
Go to your account in the cloud.
Make a download link.
Open the link in a new tab.
Sign out of your account.
Go to the tab with an open link and update the page.
Next, choose what we need to download.
Click on BaiduExporter and choose Aria2 RCP.
And we are waiting for the download.

**Comment by shui288** [comment]
@pac20

你自己搞定吧，不知你说啥？

**Comment by pac20** [comment]
shui288
I tested BaiduExporter with Firefox and Aria2 for Android.I speak a little English.Chinese do not speak.
