### ISSUE TITLE
打包扩展程序错误

### ISSUE THREAD

**Issue by chibuhu** [acgotaku/BaiduExporter#515]
无法加载扩展程序图标“img/logo16.png”。

**Comment by acgotaku** [comment]
请 加载 release文件夹

**Comment by chibuhu** [comment]
下好BaiduExporter-master.zip解压出chrome文件夹打包，以前都没问题，今天下的打包就是这个提示

**Comment by acgotaku** [comment]
那是以前。。。。 你都不看readme的么？？
