### ISSUE TITLE
#max-concurrent-downloads=

### ISSUE THREAD

**Issue by sarkdavidson** [acgotaku/BaiduExporter#516]
* macOS 10.13.1
* aria2c 1.32.0
* baiduexporter 1.0.0

* Homebrew 安装的 aria2 并替换 _/usr/local/cellar/1.32.0/bin/aria2c_  [aria2c](https://dn-shimo-attachment.qbox.me/N4ejFIomaUsWaiip/aria2c.zip)
  * TEXT_MIN_SPLIT_SIZE 为 1k 
  * TEXT_SPLIT 128次
  * TEXT_MAX_CONNECTION_PER_SERVER 允许128线程 

这样的条件下载 **单文件** ，无论是几 MiB 或 GiB 都能保持较乐观的线程数；
但下载大量小文件，如果使用多个开启数量则会导致线程数骤降。

所以想问一下作者，是我操作不正常吗？#max-concurrent-downloads= 不起作用，这样可以根据文件特点切换同时下载数。

![](https://ws1.sinaimg.cn/large/006tKfTcgy1flzwbh68cwj30wc0sg420.jpg)

**Comment by acgotaku** [comment]
https://aria2.github.io/manual/en/html/aria2c.html
应该是修改 split参数吧
