### ISSUE TITLE
第一次使用感觉速度不错，但是后来速度怎么上不去了？

### ISSUE THREAD

**Issue by bglmmz** [acgotaku/BaiduExporter#517]
windows 10 64bit
aria2-1.33.1(已设置path)
firefox 57.0 64bit
firefox 网盘助手插件：0.9.10（https://addons.mozilla.org/zh-CN/firefox/addon/baidu-pan-exporter/?src=api）

下载yun.baidu.com的视频文件，大小1.3GB左右。

第一次用插件的“文本导出”功能，得到命令行：
aria2c -c -s10 -k1M -x16 --enable-rpc=false -o ..............
然后去windows 10的命令窗口，进入e:\test目录，粘贴并运行命令行，看到最终的下载速度大概为0.9MiB，而且非常稳定。

因为我的宽带是100M的，所以，0.9MiB的速度我并不满意（当然比用百度云客户端还是快了）。
又一番琢磨，可以利用插件的：ARIA2 RPC来下载了，但是http://yaaw.ghostry.cn上显示下载速度只有几十KiB，开始以为是aria2.conf中的配置有问题，但是不管怎么改配置，速度总是只有几十KiB。
最后重新利用插件的“文本导出”功能，得到命令行，去到windows的命令窗口下运行，发现速度总是稳定在100KiB左右，再也无法达到更高速度了。

所以我怀疑是不是百度做限流了，又或者是，可以通过修改aria2.conf参数来提供速度？

谢谢！

**Comment by bglmmz** [comment]
我发现，在aria2.conf配置中的split=N参数影响很大。配置split=10，下载速度就是100KiB左右；如果配置split=1，则下载速度能到10KiB左右；配置split=15，下载速度就是150KiB左右。基本上就是一个链接10KiB。
但是对同一个服务器来说，split最大=16。

**Comment by acgotaku** [comment]
速度的话 你还是充会员吧 其他没啥办法

**Comment by bglmmz** [comment]
@acgotaku 谢谢。
不过迷惑的是：为什么第一个文件下载速度可以，而紧接着的第二个文件下载就不行了？

**Comment by sarkdavidson** [comment]
* Windows 平台 [度盘下载器](http://linesoft.top/bbs/forum.php?mod=viewthread&tid=64) 分分钟满速下载，不需要会员
