### ISSUE TITLE
已废？

### ISSUE THREAD

**Issue by zjsywcc** [acgotaku/BaiduExporter#52]
已经用不了了吗

**Comment by acgotaku** [comment]
@zjsywcc 啥？ 百度的插件 不能单独使用JS

**Comment by acgotaku** [comment]
@zjsywcc 我在上面就直接写了 

// ==UserScript==
//单纯的JS是无法运行的,必须使用扩展才行.


你难道看不见？！

**Comment by zjsywcc** [comment]
我用了拓展的 没显示

**Comment by acgotaku** [comment]
@zjsywcc 刷新下试试？ 或者告诉我你的运行环境 并贴张截图

**Comment by zjsywcc** [comment]
![image](https://cloud.githubusercontent.com/assets/2769312/8328510/df8084b2-1aa3-11e5-855f-fff8f227c870.png)
User-Agent:Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.124 Safari/537.36
有一次刷新出来了按钮 但是后来一直没能重现出来

**Comment by acgotaku** [comment]
@zjsywcc  截图不能大点么。。。 我看不到网址 还有 f12看 sources 面板的左侧  content scripts 有没有插件加载

**Comment by lihuixian001** [comment]
我的也用不了了，，，路由器里面的aria2版本是1.5.1

**Comment by acgotaku** [comment]
@lihuixian001 具体情况是？

**Comment by lihuixian001** [comment]
我现在用这个插件推送不了下载任务到aria2，，单独通过yaaw是可以下载的

当我设置成：ws://root:newifi@192.168.99.1:6800/jsonrpc
错误信息：
VM272:62 XMLHttpRequest cannot load ws://192.168.99.1:6800/jsonrpc. Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https, chrome-extension-resource.HttpSendRead @ VM272:62baidupan.aria2send_data @ VM272:886baidupan.aria2_rpc @ VM272:879baidupan.get_info @ VM272:251(anonymous function) @ speed-disk-home_2a694f0.js:6d @ all_9d9092b.js:3p.fireWith @ all_9d9092b.js:3r @ all_9d9092b.js:5r @ all_9d9092b.js:5
VM272:62 Uncaught NetworkError: Failed to execute 'send' on 'XMLHttpRequest': Failed to load 'ws://192.168.99.1:6800/jsonrpc'.


设置成http://root:newifi@192.168.99.1:6800/jsonrpc
错误信息
VM272:62 OPTIONS http://192.168.99.1:6800/jsonrpc 401 (Unauthorized)HttpSendRead @ VM272:62baidupan.aria2send_data @ VM272:886baidupan.aria2_rpc @ VM272:879baidupan.get_info @ VM272:251(anonymous function) @ speed-disk-home_2a694f0.js:6d @ all_9d9092b.js:3p.fireWith @ all_9d9092b.js:3r @ all_9d9092b.js:5r @ all_9d9092b.js:5
home:1 XMLHttpRequest cannot load http://192.168.99.1:6800/jsonrpc. Invalid HTTP status code 401

**Comment by lihuixian001** [comment]
@acgotaku  上面是错误信息

**Comment by acgotaku** [comment]
@lihuixian001 应该是用户名密码认证出现问题了  你试试不加验证试试？

**Comment by zjsywcc** [comment]
![image](https://cloud.githubusercontent.com/assets/2769312/8344816/c8507796-1b18-11e5-82b0-791501681aba.png)
确实没加载到

**Comment by acgotaku** [comment]
@zjsywcc  请用这个网址访问 http://pan.baidu.com/disk/home

**Comment by zjsywcc** [comment]
可以了
