### ISSUE TITLE
aria2可以建立任务，但是直接停止

### ISSUE THREAD

**Issue by wanglinjie168** [acgotaku/BaiduExporter#520]
大神 请教 。已经尝试过read me里的方法  aria2版本为1.18.8  操作系统为openwrt  网盘可以导出  提示已经导出成功。
但是在aria2任务列表直接就任务失败、停止。

**Comment by ivo-wang** [comment]
我跟你的情况一样

**Comment by ivo-wang** [comment]
您下载的内容地址         链接: https://pan.baidu.com/s/1c2nmpcW 密码: 2usf
插件版本号，浏览器版本号，系统版本号       插件1.0.1  浏览器chrome Version 63.0.3239.84 (Official  
Build) (64-bit)      操作系统 ubuntu-gnome 16.04 lts
列举出现问题的详细步骤      导出后直接就是失败的
描述能否复现问题             能够复现
