### ISSUE TITLE
1.0.0在Chrome dev 64.0版本下无法打开设置界面

### ISSUE THREAD

**Issue by travison** [acgotaku/BaiduExporter#521]
请确保以下几点：

1. 已经阅读过README
已经阅读
2. 尝试安装最新版本插件
已尝试
3. 尝试清空浏览器缓存
已尝试
4. 尝试卸载插件后重新安装
已尝试

发起 Issue 时，请提供：

1. 您下载的内容地址

https://pan.baidu.com/share/link?shareid=514675&uk=4261522371

2. 插件版本号，浏览器版本号，系统版本号

1.0.0/Chrome dev 64.0.3269.3（正式版本） （64 位）/ WIn10 1703 x64

3. 列举出现问题的详细步骤

页面菜单加载后点击 导出下载-设置 无反应

4. 描述能否复现问题

是，在隐身模式下关闭其他插件依旧复现。在FIrefox下无此问题。

----------

**不符合上述条件的Issue将被无理由关闭**

**Comment by acgotaku** [comment]
F12打开Console页面 看看有没有报错？ 多加载几次试试？

**Comment by travison** [comment]
@acgotaku  在正常浏览界面点了之后按f12弹出了 关闭也是要切一下f12才能关闭 神奇
 f12 log挺正常

**Comment by acgotaku** [comment]
那你看可以录一个小视频 或者截图么？

**Comment by travison** [comment]
最新chrome 65正常 应该是chrome问题
