### ISSUE TITLE
Safari 没有出现导出下载

### ISSUE THREAD

**Issue by lucyya** [acgotaku/BaiduExporter#522]
1. 下载的内容地址：GitHub
2. 插件版本号：0.7.3，
    浏览器版本号：11.0.1 (13604.3.5)，
    系统版本号： macOS High Sierra 10.13.1 (17B1003)，
3. 列举出现问题的详细步骤
    1） 在 GitHub 选择Tag v0.8.5，
    2）在 README 里面使用 Safari 链接下载后安装，**Safari 显示无法安装**
    3）在 Safari 文件夹中找到 BaiduExporter.safariextz 文件并下载，成功安装
    4）打开百度云盘网页版，**没有发现导出下载按钮**
    5）下载了 Chrome 的拓展程序，成功出现导出下载按钮
4. 描述能否复现问题
    尝试卸载再安装数次，没有效果。Safari 删除过缓存，也重启过，都没有导出下载按钮

**Comment by acgotaku** [comment]
老版本已经不能用了 请安装Chrome
