### ISSUE TITLE
请问我怎么在Safari上安装这个插件？

### ISSUE THREAD

**Issue by sariel89** [acgotaku/BaiduExporter#525]
请确保以下几点：

1. 已经阅读过README
2. 尝试安装最新版本插件
3. 尝试清空浏览器缓存
4. 尝试卸载插件后重新安装

发起 Issue 时，请提供：

1. 您下载的内容地址
2. 插件版本号，浏览器版本号，系统版本号
3. 列举出现问题的详细步骤
4. 描述能否复现问题

----------

**不符合上述条件的Issue将被无理由关闭**

**Comment by JasonKhew96** [comment]
@sariel89 发起 Issue 时，请先搜索，避免重复 Issue。

> acgotaku: 因为Safari变成了新的 IE6.。。。 无法支持
> acgotaku: 被 Baidu 干了，等合适的有 workaround 的方法会更新。暂时请使用 Chrome。
> cee: Used to be supported, but now we couldn't get cookies from Baidu.

**Comment by acgotaku** [comment]
不支持
