### ISSUE TITLE
mac的chrome插件加载一直提示加载扩展程序时出错

### ISSUE THREAD

**Issue by chunyuy** [acgotaku/BaiduExporter#526]
1. 您下载的内容地址 百度网盘
2. 插件版本号，浏览器版本号，系统版本号，安装1.0.0和1.0.1时，浏览器版本 63.0.3239.84（正式版本），系统os10.12.6
3. 列举出现问题的详细步骤

加载插件每次都提示如下
加载扩展程序时出错
无法加载以下来源的扩展程序： ~/GitHub/BaiduExporter/chrome
无法加载扩展程序图标“img/logo16.png”。

4. 描述能否复现问题

**Comment by JasonKhew96** [comment]
@chunyuy `./chrome/release/` 文件夹?
