### ISSUE TITLE
无法获取下载地址

### ISSUE THREAD

**Issue by bzvew** [acgotaku/BaiduExporter#527]
最新版本插件，内容已经保存到本地百度盘。osx 10.12.6.
chrome Version 62.0.3202.94 (Official Build) (64-bit)

每次点击导出下载，显示完正在获取下载地址后，页面自动消失。无法导出。点击文本导出也一样，无法显示出下载地址。

**Comment by acgotaku** [comment]
是网盘主页 还是分享页面？

**Comment by bzvew** [comment]
这个页面：
https://pan.baidu.com/disk/home?#list/path=%2F&vmode=list

**Comment by king4leo** [comment]
网盘主页和楼主情况一样无法获取下载地址，分享页面正常

**Comment by acgotaku** [comment]
搜索下载 目前不在支持范围内。。。

你就多点几下吧
