### ISSUE TITLE
 无法加载扩展程序

### ISSUE THREAD

**Issue by kukuhuihao** [acgotaku/BaiduExporter#531]
插件版本  在code里最新下载的版本
浏览器版本 chrome 63.0.3239.84
系统版本 mac os 10.13.1

问题：拖入BaiduExporter-master文件夹进扩展程序时，显示

> 无法加载以下来源的扩展程序： /Users/lch/Downloads/BaiduExporter-master. 清单文件缺失或不可读。

**Comment by acgotaku** [comment]
加载 release文件夹！ 请先读 readme！
