### ISSUE TITLE
下载到93%失败

### ISSUE THREAD

**Issue by shawnthu** [acgotaku/BaiduExporter#532]
[#d2fc36 6.0GiB/6.4GiB(93%) CN:2 DL:201KiB ETA:35m14s]                                                                                                                      
12/19 00:20:54 [ERROR] CUID#37 - Download aborted. URI=https://pcs.baidu.com/rest/2.0/pcs/file?method=download&app_id=250528&path=%2F%E8%BD%AF%E4%BB%B6%2FR2016b_glnxa64_dvd1.iso
Exception: [AbstractCommand.cc:350] errorCode=24 URI=http://www.baidupcs.com/401.html
  -> [HttpSkipResponseCommand.cc:211] errorCode=24 Authorization failed.
[#d2fc36 6.0GiB/6.4GiB(93%) CN:1 DL:151KiB ETA:46m48s]                                                                                                                      
12/19 00:21:01 [ERROR] CUID#35 - Download aborted. URI=https://pcs.baidu.com/rest/2.0/pcs/file?method=download&app_id=250528&path=%2F%E8%BD%AF%E4%BB%B6%2FR2016b_glnxa64_dvd1.iso
Exception: [AbstractCommand.cc:350] errorCode=24 URI=http://www.baidupcs.com/401.html
  -> [HttpSkipResponseCommand.cc:211] errorCode=24 Authorization failed.

12/19 00:21:01 [NOTICE] Download GID#d2fc36b616d55cdf not complete: /home/shawn/Downloads/R2016b_glnxa64_dvd1.iso
问题是下载百度网盘里的大文件至93%就异常了，如上所见。
版本号：1、aria2c 1.19；2、插件是昨天clone的最新master
复现：无法复现，因为下载6个多G的大文件到93%才异常

请确保以下几点：

1. 已经阅读过README
2. 尝试安装最新版本插件
3. 尝试清空浏览器缓存
4. 尝试卸载插件后重新安装

发起 Issue 时，请提供：

1. 您下载的内容地址
2. 插件版本号，浏览器版本号，系统版本号
3. 列举出现问题的详细步骤
4. 描述能否复现问题

----------

**不符合上述条件的Issue将被无理由关闭**

**Comment by acgotaku** [comment]
无法 复现  我也无法修复。。。 
本插件只负责导出。。。
