### ISSUE TITLE
发布到 Chrome 应用商店

### ISSUE THREAD

**Issue by JixunMoe** [acgotaku/BaiduExporter#533]
如果作者不介意的话，我可以代上传到 Chrome 应用商店，以后就不会发生 “开启Chrome都提示禁用” 的问题了。

不保证永远都是最新版（收到邮件提醒后我会尽快更新，但没有任何时间上的保证）。

**Comment by JasonKhew96** [comment]
> gzshasha: 能不能换个开发者上传到chrome商店呢？
> acgotaku: `@`gzshasha 没有意义 被发现了 还是得封

#277 @JixunMoe

**Comment by acgotaku** [comment]
自己发布一个非公开版本吧 否则还是被删 搞不好还会丢了自己谷歌账户 不划算。

**Comment by JixunMoe** [comment]
感谢提醒，知道了。

**Comment by Jephen** [comment]
“每次开启Chrome都提示禁用” 的问题有一个解决方案是, 使用类似于[二管家](https://chrome.google.com/webstore/detail/nooboss/aajodjghehmlpahhboidcpfjcncmcklf)的拓展管理软件, 添加一条自动规则, 只有当开启网盘页面时打开拓展.
