### ISSUE TITLE
突发错误：HTTTP响应状态503

### ISSUE THREAD

**Issue by Xiangsong-Guan** [acgotaku/BaiduExporter#534]
# 具体问题
问题是在几天前突然出现的，无论导出RPC还是拷贝连接手动添加都会有如下错误：\
`2017-12-24 10:46:13.419334 [ERROR] [AbstractCommand.cc:351] CUID#13 - Download aborted. URI=https://d.pcs.baidu.com/file/56cf537be9654c68a5f533110254ea60?fid=4201519420-250528-480103251976133&time=1514083571&rt=sh&sign=FDTAERVY-DCb740ccc5511e5e8fedcff06b081203-gXq0KeebXuJCPHXDx5J9bXVaZx4%3D&expires=8h&chkv=1&chkbd=0&chkpc=et&dp-logid=8290245450394533444&dp-callid=0&r=244564445`\
`Exception: [AbstractCommand.cc:351] errorCode=29 URI=http://d7.baidupcs.com/file/56cf537be9654c68a5f533110254ea60?bkt=p3-0000646f4520fffcd74094424e02ab0ce1b1&xcode=d0ed96d48e2439258c393a4fd2b8c521fcf2673d36cfa55e47d8b03a191c30f96f71ad9eb4c885ea&fid=4201519420-250528-480103251976133&time=1514083571&sign=FDTAXGERLQBHSKa-DCb740ccc5511e5e8fedcff06b081203-L8dNgfW%2Bh6HOG%2FUE2PaHS9YwNs0%3D&to=d7&size=196314031&sta_dx=196314031&sta_cs=1965&sta_ft=mp4&sta_ct=7&sta_mt=7&fm2=MH,Ningbo,Anywhere,,shanghai,cnc&vuk=282335&iv=0&newver=1&newfm=1&secfm=1&flow_ver=3&pkey=0000646f4520fffcd74094424e02ab0ce1b1&sl=79364174&expires=8h&rt=sh&r=244564445&mlogid=8290245450394533444&vbdid=-&fin=Saki3+%284%29.mp4&rtype=1&dp-logid=8290245450394533444&dp-callid=0.1.1&tsl=100&csl=100&csign=azJdY%2B10Z49b0LbASthGmxMFU9c%3D&so=1&ut=6&uter=-1&serv=1&uc=2923846618&ic=653900195&ti=220620fd8d32b1151a7c98ff4bde14621c94deaaf0c1521d&by=themis`\
`  -> [HttpSkipResponseCommand.cc:231] errorCode=29 The response status is not successful. status=503`

在度盘的页面，助手有提示：“下载成功……”之类的。但web-ui中则是一如既往的：\
`remote server was unable to handle the request due to a temporary overloading or maintenance`

尝试清除cookie/会话/缓存之后没有效果，看这个错误日志，是度娘的锅？
另外挂代理可以下载……很快。

# 附一些信息
RPC地址（其它配置默认，测试连接能够成功显示版本号）：`http://token:nihaoshijie@localhost:6800/jsonrpc`\
win10 家庭版 1709\
chrome 63（64位）\
百度网盘助手 1.0.1

# 附 aria2-v1.33.1 配置
`log=aria2.log`\
`log-level=error`\
`enable-rpc=true`\
`rpc-allow-origin-all=true`\
`rpc-listen-all=true`\
`rpc-listen-port=6800`\
`rpc-secret=nihaoshijie`\
`max-concurrent-downloads=5`\
`continue=true`\
`max-connection-per-server=6`\
`min-split-size=10M`\
`split=10`\
`input-file=aria2.session`\
`save-session=aria2.session`\
`dir=C:\\Users\\xxx\\Downloads`\
`file-allocation=falloc`

**Comment by acgotaku** [comment]
这个错误一直都有。。。 但可以正常下载，，，

**Comment by Xiangsong-Guan** [comment]
但是以前能下，现在什么文件都下不下来了。现在我只有在代理的情况下才有正常下载文件。

**Comment by Xiangsong-Guan** [comment]
补充：个别文件居然可以正常下载……我也搞不懂什么跟什么了……可能是度娘抽风吧？

**Comment by acgotaku** [comment]
代理能下载这不就是明显的网络问题么。。。

**Comment by Xiangsong-Guan** [comment]
我只是再想有没有可能有其它的问题……我多心了，不好意思。
是我个人的网络问题。这个问题关闭吧。
