### ISSUE TITLE
"文本导出"方式 下载问题

### ISSUE THREAD

**Issue by netcaf** [acgotaku/BaiduExporter#535]
插件版本最新：BaiduExporter 1.0.1
Chrome Version 63.0.3239.108 (Official Build) (64-bit)

操作：
进入百度云，选择一个目录，然后文本导出成 aria2c.down，然后执行 “aria2c -i aria2c.down”

问题：
aria2c 自动创建 文件目录 多了一个双引号“，下载文件结尾多了另一个双引号”
例如：在aria2c.down 中 内容包含  out="亡录像系列（1-4）/第4部 中英双字 .rmvb"
则下载结果：
创建目录名： "亡录像系列（1-4）
下载文件名：第4部 中英双字 .rmvb"

显然是out中指定的双引号被错误的使用，不知道这是BaiduExporter导出的问题还是aria2c本身的问题。

RPC方式没有问题。

**Comment by acgotaku** [comment]
新版本更新了 这回应该没有问题了

**Comment by netcaf** [comment]
嗯，试了一下。还有一个小问题："ABC/CDE/aaa.txt" 中，导出的第一个目录会第一个字符会被去掉了。
例如变成："BC/CDE/aaa.txt"

**Comment by acgotaku** [comment]
可是我没有测试出来啊 ==  你录制个小视频看看？
