### ISSUE TITLE
aria2 rpc 下载失败

### ISSUE THREAD

**Issue by wsw109** [acgotaku/BaiduExporter#538]
已完成操作
1. 已经阅读过README
2. 尝试安装最新版本插件
3. 尝试清空浏览器缓存
4. 尝试卸载插件后重新安装

Issue 信息：

1. 您下载的内容地址： 
https://pcs.baidu.com/rest/2.0/pcs/file?method=download&app_id=250528&path=%2F%E5%90%B4%E6%81%A9%E8%BE%BE%E8%AF%BE%E5%90%8E%E4%BD%9C%E4%B8%9A%2F%E7%AC%AC%E4%B8%80%E8%AF%BE%E7%BC%96%E7%A8%8B%E4%BD%9C%E4%B8%9A%2F%E7%AC%AC%E4%B8%80%E8%AF%BE%E7%AC%AC%E4%BA%8C%E5%91%A8%E7%BC%96%E7%A8%8B%E4%BD%9C%E4%B8%9A.zip
2. 插件版本号：百度网盘助手 1.0.2，浏览器版本号：chrome 63.0.3239.108（正式版本） （64 位）
，系统版本号 window 7 Enterprise
![image](https://user-images.githubusercontent.com/29395111/34475073-e12ffe86-efc2-11e7-86ea-767961a8da1f.png)

3. 列举出现问题的详细步骤
![image](https://user-images.githubusercontent.com/29395111/34475051-8a99d150-efc2-11e7-8eb5-aedc0f6c87cc.png)
![image](https://user-images.githubusercontent.com/29395111/34475063-ba57cfe6-efc2-11e7-8e41-26a9eb9c5d2b.png)

4. 描述能否复现问题
firefox 同样复现
----------

**不符合上述条件的Issue将被无理由关闭**

**Comment by kkren** [comment]
user agent 留空试试
![default](https://user-images.githubusercontent.com/23287823/34606870-fbfb502c-f24b-11e7-94b3-91362d532d57.png)

**Comment by wsw109** [comment]
谢谢回复！ 我回家连家里的网络就好了， 也许公司的网络对百度网盘做了限制
