### ISSUE TITLE
是否可以添加 RPC 密钥以及 HTTPS 方式支持

### ISSUE THREAD

**Issue by zhaojun1998** [acgotaku/BaiduExporter#539]
插件版本 1.0.2
浏览器 chrome

**Comment by acgotaku** [comment]
这个本来就支持的啊。。。

你有没有看radme。。。

**Comment by zhaojun1998** [comment]
可并不能链接成功，已按照 readme 配置，
aria 版本 1.33.1
chrome 内核版本 Chromium 62.0.3202.94

**Comment by zhaojun1998** [comment]
对不起，我又完整的做了一遍，可以使用了，谢谢。
