### ISSUE TITLE
如何下载的时候指定文件名？

### ISSUE THREAD

**Issue by sunzhaoyang** [acgotaku/BaiduExporter#54]
在百度网盘下载的时候，文件名都是pack.zip，如何能够指定下载时候的文件名？

谢谢~

**Comment by meritozh** [comment]
貌似这个是百度云网页下载时，多文件自动打包吧。可以批量导出，这样下载的时候应该就是原文件名了

**Comment by sunzhaoyang** [comment]
不好意思，批量导出是个什么东西？只见到RPC和导出下载

**Comment by meritozh** [comment]
[百度下载助手](https://greasyfork.org/zh-CN/scripts/294-baidupandownloadhelper/)

或者导出设置里不是有**文件夹层数结构**和**是否打包**的选项嘛，你可以试试。

**Comment by sunzhaoyang** [comment]
非常感谢，我之前用的是旧版本，更新了下就有相应的设置了。

**Comment by acgotaku** [comment]
@sunzhaoyang  亲 搞定了就关闭这个issue吧

**Comment by sunzhaoyang** [comment]
OK，多谢~
