### ISSUE TITLE
恩，现在不仅谷歌商店下架了，而且chrome也直接禁止第三方插件

### ISSUE THREAD

**Issue by qq938403611** [acgotaku/BaiduExporter#540]
……于是现在的唯一办法就是添加chrome组策略，然后把插件的白名单id添加上了么……

**Comment by whour** [comment]
不是还有Firefox么😎

**Comment by JasonKhew96** [comment]
打勾 Developer mode -> Load unpacked extension, 选择 `chrome/release` 文件夹

chrome用户，请使用开发者模式。

**Comment by acgotaku** [comment]
开发者模式载入 readme也说了。。。

**Comment by KasunaStony** [comment]
https://www.zhihu.com/question/24027794
chrome的话看这个问题下面的回答就行
