### ISSUE TITLE
无法显示导出下载的按钮

### ISSUE THREAD

**Issue by zhiqiang21** [acgotaku/BaiduExporter#541]
安装了插件以后，现在在百度云上选择文件以后无法显示导出下载的按钮。刷新页面会显示。但是选中文件以后，导出下载的按钮又会被隐藏。麻烦看下这个是不是问题。
<img width="1012" alt="qq20180108-103849 2x" src="https://user-images.githubusercontent.com/3990411/34657385-8293cc02-f460-11e7-9aef-511d8c3da0de.png">

**Comment by acgotaku** [comment]
你确定安装的是 1.0.2版本么？

**Comment by zhiqiang21** [comment]
ok，安装了最新的插件以后可以了
