### ISSUE TITLE
目前单个文件被限速至100KB/S，大家是否有这种情况

### ISSUE THREAD

**Issue by sagexy** [acgotaku/BaiduExporter#542]
请确保以下几点：

1. 已经阅读过README
2. 尝试安装最新版本插件
3. 尝试清空浏览器缓存
4. 尝试卸载插件后重新安装

发起 Issue 时，请提供：

1. 您下载的内容地址 :就在这里下载的
2. 插件版本号（1.0.2），浏览器版本号（Chrome 63.0.3239.132），系统版本号(macOS 10.13.2)
3. 列举出现问题的详细步骤：
单个文件被限速至100KB/S
![image](https://user-images.githubusercontent.com/4734448/34804083-b7b17c06-f6b1-11e7-8b6e-35d978ddd22a.png)

4. 描述能否复现问题
貌似从2017年12月x日后开始单个文件被限速至100KB/S，之前单个文件速度在1~2MB/S左右，不知道大家是否这个情况，因此开个issues了解下

附上aria2.conf文件
![image](https://user-images.githubusercontent.com/4734448/34804206-4bfc6dbc-f6b2-11e7-83ff-f803192ce72c.png)

----------

**不符合上述条件的Issue将被无理由关闭**

**Comment by zihengcat** [comment]
@sagexy 
没有出现问题，单文件下载速度在1~2MB/S左右。
**怀疑: 你的帐号上了百度云的限速黑名单...**
![screenshot from 2018-01-11 03-32-34](https://user-images.githubusercontent.com/19472493/34820663-cf4a14a2-f686-11e7-95b4-bceb9f17aff1.png)
## 测试环境
-  插件版本:  *0.9.6*
- 浏览器版本: *Chrome 60.0.3112.90 (Official Build) (64-bit)*
- 操作系统: *Linux (内核版本 3.10.0)*

**Comment by iwater** [comment]
我也被限速在100k

**Comment by sagexy** [comment]
@zihengcat 有没有啥办法洗白？洗白后有啥稳妥下载之策？求分享技能

**Comment by zihengcat** [comment]
@sagexy 

**洗白建议:** 
- 换马甲号
- 买百度云会员？
- [反馈给百度...](https://www.zhihu.com/question/36589282/answer/153453223)

**下载建议：**
- 文件保存到个人百度云盘后下载
- 同时下载文件数不要过多(文件一个一个下)
- 使用aria2命令下载(不启用RPC)

**Comment by acgotaku** [comment]
我都不知道说了多少遍了。。。 限速不在本插件的功能范围。。。
