### ISSUE TITLE
RPC-secret & RPC-user/password無法連接成功

### ISSUE THREAD

**Issue by gino21430** [acgotaku/BaiduExporter#543]
请确保以下几点：

1. 已经阅读过README
2. 尝试安装最新版本插件
3. 尝试清空浏览器缓存
4. 尝试卸载插件后重新安装

发起 Issue 时，请提供：

1. 您下载的内容地址
GITHUB這裡來的
2. 插件版本号，浏览器版本号，系统版本号
1.0.2   Chrome 63.0.3239.132 (正式版本) (64 位元) Win10 Pro 1709
3. 列举出现问题的详细步骤
baiduExporter導出Aria2 RPC失敗 
(我有設rpc-secret但不知道Exporter去哪裡設定對應
![baiduexportersetting](https://user-images.githubusercontent.com/33756847/34825054-f1cb3a80-f70b-11e7-811b-c37fce6a43f4.PNG)

4. 描述能否复现问题
開rpc-secret 導出Aria2 RPC
----------

**不符合上述条件的Issue将被无理由关闭**

**Comment by acgotaku** [comment]
请好好 阅读 readme
