### ISSUE TITLE
下载出错：errorCode=22 The response status is not successful, status=403

### ISSUE THREAD

**Issue by indigo4x** [acgotaku/BaiduExporter#545]
首先谢谢作者！！

请确保以下几点：

1. 已经阅读过README
2. 尝试安装最新版本插件
3. 尝试清空浏览器缓存
4. 尝试卸载插件后重新安装

发起 Issue 时，请提供：

1. 您下载的内容地址
https://d.pcs.baidu.com/file/f61e2adcd6e1e58f7b36e12c08167ca3?fid=2134105315-250528-549006297892168&time=1516047437&rt=sh&sign=FDTAERV-DCb740ccc5511e5e8fedcff06b081203-Z%2FeryJScXlBfkw9b7RCc7or%2FReE%3D&expires=8h&chkv=1&chkbd=0&chkpc=&dp-logid=352036422453569799&dp-callid=0&r=699956488

2. 插件版本号，浏览器版本号，系统版本号
BaiduExporter 1.0.2
Chrome Version 63.0.3239.132 (Official Build) (64-bit)
Ubuntu 16.04
Aria2 1.19.0

3. 列举出现问题的详细步骤
这两天一直在用，没问题，也不是用自己的帐号登录的，所以应该不存在被限制帐号的问题，不然就是百度检查IP? 
浏览器cookie已清，conf文件直接从这里拿的，而且前两天一直没问题。今天早上有一个文件下了大概90%突然停了，虽然之前也有，但基本重新下载就能续上，现在什么也下不下来

错误信息：
`01/15 15:16:30 [ERROR] CUID#12 - Download aborted. URI=https://d.pcs.baidu.com/file/f61e2adcd6e1e58f7b36e12c08167ca3?fid=2134105315-250528-549006297892168&time=1516047388&rt=sh&sign=FDTAERV-DCb740ccc5511e5e8fedcff06b081203-uQy5AZO7h08%2F5X3lcOmEAjtRsfo%3D&expires=8h&chkv=1&chkbd=0&chkpc=&dp-logid=352023193663987865&dp-callid=0&r=280328691`
`Exception: [AbstractCommand.cc:350] errorCode=22 URI=https://d.pcs.baidu.com/file/f61e2adcd6e1e58f7b36e12c08167ca3?fid=2134105315-250528-549006297892168&time=1516047388&rt=sh&sign=FDTAERV-DCb740ccc5511e5e8fedcff06b081203-uQy5AZO7h08%2F5X3lcOmEAjtRsfo%3D&expires=8h&chkv=1&chkbd=0&chkpc=&dp-logid=352023193663987865&dp-callid=0&r=280328691`
`-> [HttpSkipResponseCommand.cc:228] errorCode=22 The response status is not successful. status=403`

4. 描述能否复现问题
找了不同度盘的文件尝试，都一样，aria2c下载其他非度盘http下没问题

----------

**不符合上述条件的Issue将被无理由关闭**

**Comment by zuiyixifeng2006** [comment]
同样问题

1.您下载的内容地址
分享页面(非登陆状态)
文本导出下载
"cn_windows_10_enterprise_2016_ltsb_x64_dvd_9060409.iso" --header "User-Agent: netdisk;5.3.4.5;PC;PC-Windows;5.1.2600;WindowsBaiduYunGuanJia" --header "Referer: https://pan.baidu.com/disk/home" "https://d.pcs.baidu.com/file/0343dc55184a406af9a8ab0d964cccc6?fid=3831464433-250528-113174394953966&time=1516060903&rt=sh&sign=FDTAERVY-DCb740ccc5511e5e8fedcff06b081203-B2oenuT1oFIc5VkiZxwgIMRyT2g%3D&expires=8h&chkv=1&chkbd=0&chkpc=et&dp-logid=355651130002174098&dp-callid=0&r=685047460"

2.插件版本号，浏览器版本号，系统版本号
BaiduExporter 1.0.2
Chrome版本63.0.3239.132（官方版本）（64位）
WIN 7 SP1 
aria2-1.33.1-win-64bit-build1

3.列举出现问题的详细步骤
2018.01.15 22:00左右，使用1.0.2 （Commits on Dec 30, 2017的版本），文本导出方式下载过文件，成功。
2018.01.16 07:00左右，使用1.0.2 （Commits on Dec 30, 2017的版本），失败。
发现出现新版本
使用1.0.2 （Commits on Jan 15, 2018的版本），文本导出方式下载文件，失败。

以下为下载过程
C:\Users\用户名>E:

E:\>CD E:\Downloads

E:\Downloads>D:\Progra~1\Aria2\aria2c -c -s5 -x5 -k1M -o "cn_windows_10_enterpri
se_2016_ltsb_x64_dvd_9060409.iso" --header "User-Agent: netdisk;5.3.4.5;PC;PC-Wi
ndows;5.1.2600;WindowsBaiduYunGuanJia" --header "Referer: https://pan.baidu.com/
disk/home" "https://d.pcs.baidu.com/file/0343dc55184a406af9a8ab0d964cccc6?fid=38
31464433-250528-113174394953966&time=1516060903&rt=sh&sign=FDTAERVY-DCb740ccc551
1e5e8fedcff06b081203-B2oenuT1oFIc5VkiZxwgIMRyT2g%3D&expires=8h&chkv=1&chkbd=0&ch
kpc=et&dp-logid=355651130002174098&dp-callid=0&r=685047460"

01/16 08:02:45 [NOTICE] Downloading 1 item(s)

01/16 08:02:46 [ERROR] CUID#7 - Download aborted. URI=https://d.pcs.baidu.com/fi
le/0343dc55184a406af9a8ab0d964cccc6?fid=3831464433-250528-113174394953966&time=1
516060903&rt=sh&sign=FDTAERVY-DCb740ccc5511e5e8fedcff06b081203-B2oenuT1oFIc5VkiZ
xwgIMRyT2g%3D&expires=8h&chkv=1&chkbd=0&chkpc=et&dp-logid=355651130002174098&dp-
callid=0&r=685047460
Exception: [AbstractCommand.cc:351] errorCode=22 URI=https://d.pcs.baidu.com/fil
e/0343dc55184a406af9a8ab0d964cccc6?fid=3831464433-250528-113174394953966&time=15
16060903&rt=sh&sign=FDTAERVY-DCb740ccc5511e5e8fedcff06b081203-B2oenuT1oFIc5VkiZx
wgIMRyT2g%3D&expires=8h&chkv=1&chkbd=0&chkpc=et&dp-logid=355651130002174098&dp-c
allid=0&r=685047460
  -> [HttpSkipResponseCommand.cc:239] errorCode=22 The response status is not su
ccessful. status=403

01/16 08:02:46 [NOTICE] Download GID#7dfc89a4719adeba not complete: E:/Downloads
/cn_windows_10_enterprise_2016_ltsb_x64_dvd_9060409.iso

Download Results:
gid   |stat|avg speed  |path/URI
======+====+===========+=======================================================
7dfc89|ERR |       0B/s|E:/Downloads/cn_windows_10_enterprise_2016_ltsb_x64_dvd_
9060409.iso

Status Legend:
(ERR):error occurred.

aria2 will resume download if the transfer is restarted.
If there are any errors, then see the log file. See '-l' option in help/man page
 for details.




其他:
使用网盘网页登陆（非分享界面），使用1.0.2 （Commits on Jan 15, 2018的版本），导出文本下载，cn_windows_10_enterprise_2016_ltsb_x64_dvd_9060409.iso成功，SHA1正确。

**Comment by JasonKhew96** [comment]
#547

**Comment by acgotaku** [comment]
不登陆 貌似是没法下载的？

**Comment by indigo4x** [comment]
嗯，之前通过别人分享不登陆是可以下的，现在按#547 的办法登录了load cookie是可以的，但是由于前两天下载太多，应该超过10g了，所以登录自己账号被限速在10k/s了…… 不知道有没有办法绕过自己登录的流量限制

**Comment by acgotaku** [comment]
那看起来 大家是能下载 只是速度有限制？

**Comment by indigo4x** [comment]
是的，除非暴力开很多线程，不然就是大文件100k, 小文件10k

**Comment by youyiqin** [comment]
登录了，按照#547的说法去做了，还是同样的错误，是凉了吗。

**Comment by snowdream** [comment]
遇到同样问题，有解决方案吗？
