### ISSUE TITLE
下载根目录文件时 prefix 的值是错的

### ISSUE THREAD

**Issue by gywn** [acgotaku/BaiduExporter#546]
1. **您下载的内容地址**
自己云盘根目录下的一个文件，比方说 `'test.mp4'`

2. **插件版本号，浏览器版本号，系统版本号**
插件：1.0.2
浏览器：Chrome 63.0.3239.132
系统：macOS Sierra 10.12.6

3. **列举出现问题的详细步骤**
    a. 勾选根目录下的 `'test.mp4'`
    b. 点击「导出下载」
    c. aria2c 的 -o 项里面，文件名的首字母丢失，为 `'est.mp4'`

4. **描述能否复现问题**
能

推测：
-----
`chrome/src/js/home.js` 中
  * 行 80 拿到的 `path` 值为 `'/'`
  * 行 85 的 `dir` 值为 `['', '']`，返回值为 `2`
  * 行 97 拿到的 `files[key].path` 值为 `'/test.mp4'`，理想的 `prefix` 值应该为 `1`

**Comment by acgotaku** [comment]
更新了
