### ISSUE TITLE
昨天还能正常使用，今天无法下载了

### ISSUE THREAD

**Issue by hanuse** [acgotaku/BaiduExporter#547]
1. 任意百度网盘文件地址都无法下载
2. 插件版本号1.02，浏览器版Google Chrome 版本 63.0.3239.132和firefox quantum 57.04 ，系统版本号mac os 10.13.2
3. 正常操作步骤：先打开aria2gui ，打开百度链接页，选择文件--导出下载--aria2 prc，下载列表直接是x,aria2gui提示的状态是：
任务大小: 0 KB (0 @ 1.00 MB)
任务状态: error
保存路径: /Users/xx/Downloads
文件区块:
4. 换了几个文件、浏览器、wifi都是这样，昨天所有浏览器都还可以正常使用

**Comment by yzyvl** [comment]
百度云的第三方下载工具全部都不能用了，手机上有山寨云，电脑端的油猴脚本，aria2都不能用了。哎，伤心啊

**Comment by kevinwenyu** [comment]
貌似是的哦，我的下载也不行了。

**Comment by offwalk** [comment]
从今天开始，百度网盘下载需要登录帐号。
而非付费用户下载超过10G会限速10k一个星期左右。登录后(获取BDUSS)用插件导出cookies.txt,aria2c --load-cookies 就可以下载。

**Comment by river1** [comment]
在导出下载-设置-headers里面填cookie
cookie可以在登陆百度时发的包里查看，格式是
Cookie:BAIDUID=xxx;BDUSS=xxx;xxxxx=xxxxx;xx=x

**Comment by yijinbandouya** [comment]
@river1 楼上这位兄台，我已尝试这种方法但是无法下载。能否给个详细教程。
![image](https://user-images.githubusercontent.com/34211937/34986113-4fb6c1b2-faf1-11e7-8e2c-afd9242e1424.png)

**Comment by bluestar800** [comment]
今天下载任何百度文件全部直接 error，封锁的太厉害了

**Comment by rilyuuj** [comment]
也是httpheaderror报错，按照 @river1  提供的方法，测试使用pan.baidu.com登录的cookie，与下载链接登录账户后的cookie，都无法下载，看到 @river1 的描述中还有两个分号，怀疑参数不全，希望还能提供下详细的设置。

aria的日志就不放了，看到大家都有问题，baidu的锅是背定了。抵制百度从我做起，今天就吧资料全挪出来

**Comment by dogos1** [comment]
Today,I also failed to download any files on baidu cloud with BaiduExporter 1.0.2. whenever aria2c is executed, It only showing "errorCode=22"..

**Comment by qweaszxcdf** [comment]
当前测试 需要BDUSS及STOKEN

**Comment by river1** [comment]
![capture](https://user-images.githubusercontent.com/2911604/34988373-8ba6b3dc-faf9-11e7-8adc-a20eb74b1439.PNG)
右键检查，打开network，刷新一下页面，然后就可以看到cookie了

**Comment by acgotaku** [comment]
为啥我测试还能用。。。 难道是我访问的服务器还没更新？

**Comment by rilyuuj** [comment]
A大您大神护体>_<

**Comment by rilyuuj** [comment]
@river1 回复R神，按你的方法测试可用。更换资源会跳验证码，不过不碍事。。非常感谢！@yijinbandouya 同学可以测试下。
但是这个超过10G限速10k真是无解啊。。

**Comment by acgotaku** [comment]
结论来说 就是百度换了验证的cookies

**Comment by dogos1** [comment]
Thank you very much for your screenshot which shows how to gain baidu's Cookie from chrome(ctrl+shift+i).After I paste copied whole cookie into headers tab,It start to download from baidu cloud! But From now on, Is it impossible to download any file from baidu cloud without login ?

**Comment by qweaszxcdf** [comment]
问题在于现在不登陆下载不了

**Comment by acgotaku** [comment]
@rilyuuj https://github.com/acgotaku/BaiduExporter/tree/dev 
你可以试试 dev分支的 release文件夹 这里更新了cookies 看看可以不可以解决问题

**Comment by rilyuuj** [comment]
@acgotaku 回雪大，测试更换资源后不会跳验证码了，不过还是必须填cookies到headers (((φ(◎ロ◎;)φ)))

**Comment by acgotaku** [comment]
那还是等我这边 也出BUG了 再测试吧

**Comment by qweaszxcdf** [comment]
@acgotaku  我这边测试分享页面需要BDUSS和STOKEN,网盘主页仅需要BDUSS

**Comment by rilyuuj** [comment]
好的。谢雪大，辛苦了。
@dogos1 as @offwalk explanation. it is not possible download resource with extension if anonymous login.
The speed will be limited to 10k for one week if novip account download exceed 10G...

**Comment by qweaszxcdf** [comment]
[chrome.zip](https://github.com/acgotaku/BaiduExporter/files/1635364/chrome.zip)
可以测试一下能不能使用

**Comment by yzyvl** [comment]
@qweaszxcdf thank you! it can work, but the download speed is limited.

**Comment by qweaszxcdf** [comment]
@yzyvl 当前无法规避百度的单线程限速，你可以多开点线程

**Comment by yzyvl** [comment]
@qweaszxcdf ok.thank you!

**Comment by indigo4x** [comment]
@qweaszxcdf 求问有没有办法不登录下载，或者突破10g限制

**Comment by ccw1996** [comment]
@rilyuuj 你好，具体的格式是什么样的？能举个例子吗？

**Comment by RicardoKlose** [comment]
![image](https://user-images.githubusercontent.com/16949419/35001418-ab4c47a6-fb21-11e7-866f-3ff6add7452c.png)
设置里面加上这个，然后在aria2的配置里面加上load-cookies=true重启就可以了

**Comment by zihengcat** [comment]
我还能用...（将文件保存至个人百度云盘，使用文本导出，aria2命令行下载）
![slice 1](https://user-images.githubusercontent.com/19472493/35020615-9ab59750-faf2-11e7-9c12-f999fcfd66ca.png)
用到的Cookies有`BDUSS`和`pcsett`
## 测试环境

- 插件版本: *0.9.6*
- 浏览器版本: *Chrome 60.0.3112.90 (Official Build) (64-bit)*
- 操作系统: *Linux (内核版本 3.10.0)*

**Comment by ccw1996** [comment]
@RicardoKlose 是直接将cookie的那一长串全部复制过来，加上设置load-cookies=true，还是不行。。
T_T

**Comment by ccw1996** [comment]
@RicardoKlose 解决了，谢谢

**Comment by woshichenchuana** [comment]
@offwalk 怎么导出cookies.txt再用aria2c --load-cookies

**Comment by offwalk** [comment]
@woshichenchuana --load-cookies 有问题不实用，可以直接用 @zihengcat 的 aria2c --header "Cookie: BDUSS=xxxxxx"
BDUSS 值在 cookies.txt中，用插件[https://www.chromefor.com/cookies-txt_v1-14-1/]导出。
参考前几楼大神的方法

**Comment by qweaszxcdf** [comment]
当前疑似对分享页面限制120线程

**Comment by woshichenchuana** [comment]
@offwalk 知道了，谢了

**Comment by rocdeng** [comment]
我这里能下，不过速度只有100KB了

**Comment by acgotaku** [comment]
所以你们不能用是主页 还是网盘页面？

**Comment by waeshang** [comment]
今天影视论坛里好多人讨论度盘又开始不让下载了，看来度娘子这锅背定了。
可我这里真的能用。。。版本号0.97，一直就没更新过。

**Comment by alfredmeow** [comment]
自己的网盘主页,还是他人分享的网盘页面也用不了

**Comment by YangAi** [comment]
所有页面都无法使用。

**Comment by Bubbab123** [comment]
Aria2 WebUI一直显示HTTP response header was bad or unexpected。有知道怎么解决的吗？？？

**Comment by yorks** [comment]
看起来是ua的问题。。。把ua改成浏览器就好了。


```bash
$ curl  -H 'netdisk;5.3.4.5;PC;PC-Windows;5.1.2600;WindowsBaiduYunGuanJia'     -k -I 'https://d11.baidupcs.com/file/cce***ffd8?bkt=p3-****&xcode=***&fid=**-**-**&time=1516250828&sign=***&to=d11&size=312226062&sta_dx=312226062&sta_cs=91&sta_ft=mp4&sta_ct=4&sta_mt=0&fm2=MH,Yangquan,Anywhere,,guangdong,cnc&vuk=**&iv=0&newver=1&newfm=1&secfm=1&flow_ver=3&pkey=***&sl=79364174&expires=8h&rt=pr&r=773034629&mlogid=**&vbdid=***&fin=*S03E09.mp4&=*S03E09.mp4&rtype=1&dp-logid=****&dp-callid=0.1.1&hps=1&tsl=100&csl=100&csign=****0%3D&so=0&ut=6&uter=4&serv=1&uc=**&ic=***&ti=***&by=themis' 
HTTP/1.1 302 Moved Temporarily
Server: bfe/1.0.8.13-sslpool-patch
Date: Thu, 18 Jan 2018 04:59:21 GMT
Content-Type: text/html
Content-Length: 160
Connection: keep-alive
Location: http://www.baidupcs.com/403.html
Access-Control-Allow-Origin: *
Access-Control-Allow-Methods: GET, PUT, POST, DELETE, OPTIONS, HEAD


$ curl  -H 'User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:57.0) Gecko/20100101 Firefox/57.0'     -k -I 'https://d11.baidupcs.com/file/cce***ffd8?bkt=p3-****&xcode=***&fid=**-**-**&time=1516250828&sign=***&to=d11&size=312226062&sta_dx=312226062&sta_cs=91&sta_ft=mp4&sta_ct=4&sta_mt=0&fm2=MH,Yangquan,Anywhere,,guangdong,cnc&vuk=**&iv=0&newver=1&newfm=1&secfm=1&flow_ver=3&pkey=***&sl=79364174&expires=8h&rt=pr&r=773034629&mlogid=**&vbdid=***&fin=*S03E09.mp4&=*S03E09.mp4&rtype=1&dp-logid=****&dp-callid=0.1.1&hps=1&tsl=100&csl=100&csign=****0%3D&so=0&ut=6&uter=4&serv=1&uc=**&ic=***&ti=***&by=themis' 
HTTP/1.1 200 OK
Server: bfe/1.0.8.13-sslpool-patch
Date: Thu, 18 Jan 2018 04:59:32 GMT
Content-Type: application/octet-stream
Content-Length: 312226062
Connection: keep-alive
ETag: b3643d22015737334d367fb5a196fa4a
Last-Modified: Mon, 25 Dec 2017 10:02:50 GMT
Expires: Fri, 19 Jan 2018 12:49:27 GMT
Cache-Control: max-age=259200
Accept-Ranges: bytes
x-bs-file-size: 312226062
x-bs-meta-crc32: 2342608628
x-bs-client-ip: **==
x-bs-request-id: ****zA=
Content-Disposition: attachment;filename=***.mp4
Content-MD5: b3643d22015737334d367fb5a196fa4a
superfile: 2
Ohc-Response-Time: 1 0 0 0 0 0
Access-Control-Allow-Origin: *
Access-Control-Allow-Methods: GET, PUT, POST, DELETE, OPTIONS, HEAD
```

**Comment by ChicBrother** [comment]
@yorks  试了，也不行。

**Comment by ChicBrother** [comment]
每个人的情况都不一样，我的是普通 会员的页面哪里都可以直接导出下载，只不过是限速的。登陆了SVIP后反倒任何文件一导出下载就失败。无语

**Comment by msongz** [comment]
我的情況：
登錄-個人文件-aria2-空header # 有速度 100k/s 
登錄-個人文件-私密分享-登出-aria2 # 沒有速度，報http error

**Comment by ArcherCX** [comment]
不登陆的情况直接报header错误
登录后，第一次会弹验证码，之后就正常了
限速的问题改了aria2c的 PREF_MAX_CONNECTION_PER_SERVER 也可以解决
测试环境：
1.0.2的插件，chrome 63.0.3239.132，OSX

**Comment by tEstCJN** [comment]
https://github.com/acgotaku/BaiduExporter/issues/547#issuecomment-357942255

刚才测试，这个方法成功，把整段复制了进来，43个文件同时下载，vps上的总下载速度到了62.88 MB/s

**Comment by bastetnote** [comment]
下载不了就上来看看，真是的，登录帐号就能下载了，如果每个月10G不够就再注册几个帐号吧。好像也没别的方法了。

**Comment by acatcat86** [comment]
全都不行。。。登录了也无法用aria2下载

**Comment by acatcat86** [comment]
登录下载只能达到1M, 可以用但是比不过以前动辄4,5M的速度。。。

**Comment by acgotaku** [comment]
不能登录的情况下  麻烦大家贴一下 到处下载的文本 我好分析分析原因  QAQ

**Comment by acatcat86** [comment]
@acgotaku 
随便搜了一个百度云文件 不登录情况下 下面的文本无法下载 （登录后cookier变成BDUSS 但是也最多1M/sec ）感谢!

aria2c -c -s10 -k1M -x16 --enable-rpc=false -o "Quiver_3.1.2_xclient.info.dmg" --header "User-Agent: netdisk;5.3.4.5;PC;PC-Windows;5.1.2600;WindowsBaiduYunGuanJia" --header "Referer: https://pan.baidu.com/disk/home" --header "Cookie: pcsett=1516583087-b59ff7f0e6ddc12f6c7aab25be2138ff" "https://d.pcs.baidu.com/file/e9770b0206027c44d55334739767f2bf?fid=4185473307-250528-298709841616373&time=1516496693&rt=sh&sign=FDTAERV-DCb740ccc5511e5e8fedcff06b081203-8TbSXfe80d%2FSKr3dNPLu8pUULFY%3D&expires=8h&chkv=1&chkbd=0&chkpc=&dp-logid=472632364466655571&dp-callid=0&r=812839129"

**Comment by acgotaku** [comment]
@acatcat86 不登录的情况下 没有 BDUSS这个 cookies 是无法下载的。。。
这是百度的限制 我这边无能为力。。。

**Comment by acatcat86** [comment]
@acgotaku 恩 看来是这样。。。1M的速度也算凑合着可以用了。。。

**Comment by YangAi** [comment]
登陆之后很容易被限速，但是也没办法。

**Comment by alfredmeow** [comment]
不登录:
aria2c -c -s10 -k1M -x16 --enable-rpc=false -o "9784862695307 4000.rar" --header "User-Agent: netdisk;5.3.4.5;PC;PC-Windows;5.1.2600;WindowsBaiduYunGuanJia" --header "Referer: https://pan.baidu.com/disk/home" "https://d.pcs.baidu.com/file/2a9d392c8fc9d0df8ca290e9048f0c1d?fid=3931249531-250528-844730655580894&time=1516506790&rt=sh&sign=FDTAERVY-DCb740ccc5511e5e8fedcff06b081203-9I%2FN2Jt3vD7rOCGy6dTbsgcYyGA%3D&expires=8h&chkv=1&chkbd=0&chkpc=et&dp-logid=475342943577210489&dp-callid=0&r=412353756"

登录:
aria2c -c -s10 -k1M -x16 --enable-rpc=false -o "9784862695307 4000.rar" --header "User-Agent: netdisk;5.3.4.5;PC;PC-Windows;5.1.2600;WindowsBaiduYunGuanJia" --header "Referer: https://pan.baidu.com/disk/home" "https://d.pcs.baidu.com/file/2a9d392c8fc9d0df8ca290e9048f0c1d?fid=3931249531-250528-844730655580894&time=1516506875&rt=sh&sign=FDTAERVY-DCb740ccc5511e5e8fedcff06b081203-RtXiaqLnmKvwqOAxGeVyQqcVE%2FE%3D&expires=8h&chkv=1&chkbd=0&chkpc=et&dp-logid=475365637989008357&dp-callid=0&r=434252482"

TMD, 8xkb速度也算凑合?

**Comment by zynkchen** [comment]
@river1  多谢，终于成功了。

**Comment by huanxiu** [comment]
实践反馈如下：
使用环境：Windows10专业版，版本1709,OS内部版本16299.192；Google Chrome版本 63.0.3239.132（正式版本 64 位）；BaiduExporter插件版本号1.02；Aria2版本1.33.1-win-64bit-build1；Aria2前端显示软件AriaNg Native v0.2.0

【一】
使用方法：
在aria2的配置里面加上load-cookies=true
登录百度网盘后，在网盘所有文件主页选择导出下载-设置-headers里面填cookie，格式是
Cookie:BAIDUID=xxx;BDUSS=xxx;pcsett==xxx;
复制下载链接至Aria2进行下载
结果：可以添加下载，网速5-40kb/s，非常容易断点，续传后继续断点

【二】
使用方法：将文件保存至个人百度云盘，使用文本导出，aria2命令行下载
结果：可以下载，下载速度在100k/s，可以下载完成

![image](https://user-images.githubusercontent.com/11550805/35194994-ca5cd6d6-fef7-11e7-9294-3106b33a46d9.png)

![image](https://user-images.githubusercontent.com/11550805/35195003-f48bcdae-fef7-11e7-9ced-5cf3945dfc11.png)

**Comment by kitce** [comment]
請問百度目前是暫停帳號申請服務嗎？
我想申請一個帳號來試試看拿Cookie來下載
但是出現"百度正在进行系统升级，暂时不能提供服务，敬请谅解"

**Comment by acatcat86** [comment]
@alfredmeow 可能是因为我现在人在国外的缘故 估计我在国内速度也和你一样 因为我的下载方法和你的没有区别

**Comment by alfredmeow** [comment]
可能小黑屋了,小弟有一次1MB,之後<100kb....

**Comment by nanzi** [comment]
在pan.baidu.com/s/*页面，登录帐号后使用"文本导出"功能下载是正常的。"文本导出"下载地址包含个人cookie信息。频繁刷新、重复导出，会跳出验证码。

**Comment by acgotaku** [comment]
限速 这个前端是无法解决的， 所以抱歉。

**Comment by NIONKI** [comment]
![2018-01-22 18_33_14](https://user-images.githubusercontent.com/11434827/35216480-bb551152-ffa2-11e7-8451-4d6f5d2789dc.gif)
emmmmm 登录后可以下载，但是有个神奇的现象是点刷新，速度蹭蹭蹭的，我是不是要被小黑屋了。。。。

**Comment by acgotaku** [comment]
@NIONKI 下载速度快 不不该偷着乐么！

**Comment by NIONKI** [comment]
@acgotaku emmmm肉身在墙外嘛，所以登录后下载然而不做任何设置的话，后期是不是要观察有没有被限速了，作为菜鸡瑟瑟发抖

**Comment by yzyvl** [comment]
@NIONKI 最开始速度的确很快，下载超过10g之后速度应该有明显的下降。我的就是这样。

**Comment by Cappuccin0** [comment]
带账号信息下载会被限速应该是很久以前（起码半年）就这样了 唯一办法是用多个账号 或者间隔较长时间再重新下载

**Comment by yzyvl** [comment]
@acgotaku 昨天晚上还能下载，今天早上起来就无法下载了，把该帖下面的方法又重新来了一遍还是不行。请问一下，还有其他人出现这样的情况吗？谢谢

**Comment by yorks** [comment]
之前限制 100k/s 也就算了，现在限制10k/s 疯了。。。

**Comment by woshichenchuana** [comment]
@yzyvl 登录帐号也无法下载

**Comment by ArcherCX** [comment]
@NIONKI 为什么你能开那么多线程？我最多只有40个

**Comment by ladychili** [comment]
导出到aria2后秒提示下载成功 但是什么都没有哇 T-T 有和我一样的吗

**Comment by ChicBrother** [comment]
现在用普通 用户可以下，svip 却是一导出就马上失败了。前天的release 刚发布时试了可以的呀。

**Comment by mzjlq1** [comment]
插件版本号1.02，浏览器Chrome，系统版本号mac os 10.13.2，Aria2GUI 版本1.4
请问在不登陆的情况下怎么才能正常下载？
dev分支的插件，Chrome无法安装

**Comment by HOHOOO** [comment]
10k 的速度简直要杀人了🙄

**Comment by huanxiu** [comment]
![image](https://user-images.githubusercontent.com/11550805/35378311-4baaf6b2-01ed-11e8-81c7-b193d9f06847.png)
提供一个思路，单文件下载限速10k/s，用IDM批量下载或下载文件夹不限速。
如果要下载一个单文件，最好和一个空文件夹一起下这样就不限速了。

**Comment by fablelu** [comment]
的确！按3楼的说法登录之后能正常下载速度的话还可以。速度在380-500KB/S。

**Comment by acatcat86** [comment]
太机智了……

还休 <notifications@github.com>于2018年1月25日 周四03:34写道：

**Comment by Cappuccin0** [comment]
@huanxiu 请教一下是必须用IDM么？试了选择一个文件和一个空文件夹一起导出到aria2 限速还是10k没变

**Comment by kitce** [comment]
請問可以整理一下目前成功下載的方法嗎？
必需要已登陸的百度帳號Cookie？

**Comment by acatcat86** [comment]
@huanxiu 

刚在家试了一下 （用VM虚拟机加载IDM）还是100k的速度。。。
算了不折腾了 -，-

**Comment by huanxiu** [comment]
@Cappuccin0  我自己测试用BaiduExporter直接导出到aria2的话还是分开下载的，并不是一起下载的，如果是导出到IDM一起下载的链接复制到aria2去下载的话，是会快一些，但是不如IDM
![image](https://user-images.githubusercontent.com/11550805/35422729-1bb35bd2-0285-11e8-821a-99a6042ffcc3.png)

**Comment by huanxiu** [comment]
@acatcat86 我现在已经堕落到只要不是10k我就谢天谢地了，感觉再这样折腾下去可能只能去开会员了。。

**Comment by ChicBrother** [comment]
@huanxiu  现在我的svip 会员一导出下载就失败！！！普通 会员起码还可以下。

**Comment by wyjxm** [comment]
我目前用的一个脚本不登陆403无权限，登陆了16线程限速100K/s。如果无法绕过cookies的登录认证感觉无解

**Comment by kitce** [comment]
剛剛註冊了一個百度帳號
然後甚麼Headers都沒有設定就直接成功導出到aria2下載
速度維持500KB/s左右

Version : 1.0.2
Browser : Chrome 63.0.3239.132

**Comment by huanxiu** [comment]
@acatcat86 你到IDM设置看一下下载线程设置是多少，我今天改为32线程，下载速度到了2M多

**Comment by sijiniuge** [comment]
你好，我的aria2不管是网盘里面的文件 还是其他的 [都出现错误，提示http返回头无效或无法识别，发生错误（22）]

**Comment by ArcherCX** [comment]
导出文本，“ aria2c -c -s10 -k1M -x16 ” 这块我修改成 “ aria2c -c -s100 -k1M -x160 ” 后，放到命令行里执行可以跑到700k-1M的速度，昨天还满速跑过
但是用rpc线程数会被限制到1，速度10k

**Comment by florid2** [comment]
下载小文件可以，但是速度只有10k。下载大文件比如4g的一个文件，也不提示错误，直接下载了15k就提示完成了。。。
通过百度盘网页点击下载按钮会提示“正在启动网盘客户端，请稍后”，然后跳出“你下载的文件过大，请使用百度网盘客户端。”
<img width="245" alt="screen shot 2018-02-01 at 10 18 50 pm" src="https://user-images.githubusercontent.com/25091279/35675919-f4799522-079d-11e8-8e0b-3b2dfd591331.png">

**Comment by dogos1** [comment]
I just noticed that Baidu begin to limit download speed lower than 100kb/s today,But It is possible to boost speed upto 400kb/s by using Internet  downloader manager (IDM)
The screenshot below illustrate how to use Baiduexporter in conjunction with IDM
![baiduexporter1](https://user-images.githubusercontent.com/26139424/35683793-680a191c-07a8-11e8-83a2-c7d360bc3c62.png)
![baiduexporter2](https://user-images.githubusercontent.com/26139424/35683791-67c4a8d2-07a8-11e8-965d-e1a4346114ef.png)
![baiduexporter3](https://user-images.githubusercontent.com/26139424/35683790-6772e498-07a8-11e8-9a5c-0a6dd8f40af5.png)
![baiduexporter4](https://user-images.githubusercontent.com/26139424/35683789-67274380-07a8-11e8-8223-f5ae756e0a5f.png)
![baiduexporter5](https://user-images.githubusercontent.com/26139424/35683787-66c8efc4-07a8-11e8-977a-c64c987def1c.png)

![baiduexporter6](https://user-images.githubusercontent.com/26139424/35683796-685c5894-07a8-11e8-949c-cfccd445bc80.png)

**Comment by ttimasdf** [comment]
日常抽风。我这里测试已经恢复了。没有cookie也能下，aria2c 10线程跑满

**Comment by dfbgp** [comment]
确实活过来了，现在正常

**Comment by rilyuuj** [comment]
所以现在不用登录也能下载了？

**Comment by acgotaku** [comment]
@river1 你试试不就知道了。。

**Comment by machsix** [comment]
太奇怪了==本地windows破解线程的可以满速下载，vps上10kb下载几秒就会断，传递了cookie也没用，两边都是破解线程的版本。另外没有看到pcsset这个cookie啊

**Comment by rilyuuj** [comment]
删除cookie，退出账号，重启路由器（aria装这上面的），测试连接https://pan.baidu.com/s/1bqCa99l
5线程能满速下载，可以确定没问题了，不用登录也不用cookie了=。=
所以百度和大家开了个玩笑么

**Comment by alexching1202** [comment]
你好我用的是Aria2-EZ 1.1.1免安裝版的，但是裝BaiduExporter-master是這裡下的
Chrom外掛https://github.com/acgotaku/BaiduExporter
Google Chrome 目前是最新版本版本 64.0.3282.186 (正式版本) (64 位元)
但是卻無法在Google Chrome安裝他出現無法載入下列來源的擴充功能： D:\Downloads\BaiduExporter-master\chrome無法載入擴充功能圖示「img/logo16.png」。因為不是很懂程式也不知道如何處理說！

**Comment by zlf179** [comment]
我照着前面方法加BDUSS，STOKEN都不行啊，直接报错HTTP请求头错误或者无效

**Comment by paysmartly** [comment]
今天又测试了一番，但是115expoter和baidu exporter一转到ariagui就死掉，查看了一下，百度cookie 多了一句代码，PANWEB=1; 其他的与之前一样，但是删除干净重装也是同样的结果，用了各种工具做一个干净的重装aria2gui也是一样，是不是这两天baidu和115做了什么cookie验证更新啊？

**Comment by Cappuccin0** [comment]
@paysmartly 试试看登录以后转存到自己网盘再从自己网盘下载？ 没研究过baidu更新过什么 但碰过几次最近新生成的共享无法在非登录状态下下载 转存后都正常 以前生成的共享倒是可以仍然可以在分享页面非登录状态下下载

**Comment by paysmartly** [comment]
@Cappuccin0 就是在自己的网盘里面下载的。赶紧是MacOS里面的某些设置导致的，因为同一个plugin在win里面都是正常的，还请有MacOS的同学们能给一下结局方案。已经尝试了的有，用Clean My Mac进行彻底删除Aria2，但是都是一样的结果。

**Comment by chengjianhao** [comment]
> 在导出下载-设置-headers里面填cookie
> cookie可以在登陆百度时发的包里查看，格式是
> Cookie:BAIDUID=xxx;BDUSS=xxx;xxxxx=xxxxx;xx=x
想问一下，BDUSS 只有一行数据，怎么按照格式里面这个填呢？

**Comment by mortalBibo** [comment]
大家都是什么情况？
我原先是满速，大约下了20个资源之后ariaGUI报header错误
复制整个cookie到导出设置依然error
pcsett一定要加吗？

**Comment by pixystone** [comment]
只能被限速下载，但是有个很有趣的现象：

如果同时开客户端试用加速，ariaGUI那里暂停再重连，会把客户端试用的加速一直延续下去（而客户端试用的加速会变慢），非常有趣。

![image](https://user-images.githubusercontent.com/3050696/52535758-2c658480-2d8d-11e9-8c9f-bdf80bd0ef39.png)

**Comment by MrPoopyLobster** [comment]
在Mac客户端上，从百度云上导入aria2以后，下载速度就很慢。只有一百几十k

Version : 1.0.2
Browser: Chrome 72.0.3626.119
