### ISSUE TITLE
导出地址为IDM后，下载失败

### ISSUE THREAD

**Issue by AlanTR** [acgotaku/BaiduExporter#55]
导出地址-导出为IDM.txt后，用IDM导入该文件，提示error，无权限访问该文件，求解决 0.0

**Comment by meritozh** [comment]
文件权限问题？你看下导出的文件属性

**Comment by acgotaku** [comment]
@AlanTR 多半是文件权限的问题 你右键管理员运行 IDM 再导入试试

**Comment by acgotaku** [comment]
@AlanTR 新升级的百度网盘 修复 了这个问题  你再试试看
