### ISSUE TITLE
Could not download（完全下不下来）

### ISSUE THREAD

**Issue by aiwonanjing** [acgotaku/BaiduExporter#551]
errorCode=22 The response status is not successful. status=403
完全下不下来，都提示这句话

下载地址https://pan.baidu.com/s/1eSA6AdW
插件版本号1.0.2（今天才下的），浏览器版本 65.0.3322.3（chrome dev x64），win10 1709 x64
点击导出下载，复制链接到aria2c所在文件夹的cmd，就出现这个bug了
我的电脑上任意百度云链接都会出现这个问题。

**Comment by yanqiyu** [comment]
建议查看#547的issue

**Comment by acgotaku** [comment]
分享页面 如果没有登录应该是无法下载的

**Comment by acgotaku** [comment]
登录 试试  或者帖一下 导出文本的内容 我看看

**Comment by fablelu** [comment]
登录了可以下载，速度在100KB/S。不过现在比较坑了，原来我知道登录用aria2下载会被百度记录账号加入黑名单，然后下载速度就降到100KB/S，不登录的话，百度没办法记录你的ID，就无法限速到100，下载速度都在500KB/S，现在能突破不登录也能下载么？
