### ISSUE TITLE
照著#547的做了 但還是沒法下載 (登陸也一樣) [status=400]

### ISSUE THREAD

**Issue by nok1126** [acgotaku/BaiduExporter#552]
1.您下载的内容地址
https://pcs.baidu.com/rest/2.0/pcs/file?method=download&app_id=250528&path=%2F%EF%BC%88%E7%91%9E%E6%A0%91X%E8%90%8C%E4%BD%A0%E5%A6%B9%E7%89%88%EF%BC%89%E7%BE%8E%E5%B0%91%E5%A5%B3%E4%B8%87%E5%8D%8E%E9%95%9C%20%E7%BD%AA%E4%B8%8E%E7%BD%9A%E7%9A%84%E5%B0%91%E5%A5%B3.rar

2.插件版本号：1.0.2
   浏览器版本号：Google Chrome 63.0.3239.132 (x64)
   系统版本号：Windows Education version 1709ver (16299.192) x64

3.列举出现问题的详细步骤：
已照 #547 的方法增加Cookies，也在aria2的設置文件裡加入"load-cookies=true"。

雖然排除了，403的錯誤，但是又跳出400這個：
[HttpSkipResponseCommand.cc:239] errorCode=22 The response status is not successful. status=400

4.描述能否复现问题
不管換了多少方式都無法下載。

*IDM也失效。

謝謝大神了

**Comment by acgotaku** [comment]
你下载的是自己网盘的 还是分享页面？

可以帖一下导出文本的内容么？

**Comment by nok1126** [comment]
自己網盤的
aria2c -c -s10 -k1M -x16 --enable-rpc=false -o "（瑞树X萌你妹版）美少女万华镜 罪与罚的少女.rar" --header "User-Agent: netdisk;5.3.4.5;PC;PC-Windows;5.1.2600;WindowsBaiduYunGuanJia" --header "Referer: https://pan.baidu.com/disk/home" --header "Cookie: BDUSS=FFzdXpOam9kUVhSVUJOSjVORm9PbW9aVmxoY1ZST35NQ0NIUlR2eWtRSG8wSXRhQVFBQUFBJCQAAAAAAAAAAAEAAAD0lRA-RnNCX05vawAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAOhDZFroQ2Rae; pcsett=1516623297-a5b5784ff014ddd4638ee44763616982" --header "BAIDUID=6D98628278206A32A55A5CB6A04940A1:FG=1; PANWEB=1; FP_UID=5e0447c5545b8328b36f63c8b5b1f17c; panlogin_animate_showed=1; BDUSS=FFzdXpOam9kUVhSVUJOSjVORm9PbW9aVmxoY1ZST35NQ0NIUlR2eWtRSG8wSXRhQVFBQUFBJCQAAAAAAAAAAAEAAAD0lRA-RnNCX05vawAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAOhDZFroQ2Rae; pan_login_way=1; STOKEN=07c2120e9a2c1ec5deed68b8de1f4455c3ff32cafd834ea5f7c1f4ecfa4042e4; SCRC=d96384af762416802b050f2bcadffe11; PANPSC=8202105811385972096%3AC1EvAaxZsiBpckYrHBox3u%2FVvwJ0ndn1S8l2hGYR2yMwwo4y0uRbvS5UsGXlM7WGqwl78pdae0xkCTdhdzCkvDXo9flvA%2Ba4tI3uD9NzBYSbl0ryJpDG5atj1wHCmalR73o7%2Borj02QrWOqA3q3PCcDuiFJchHVyObuDsIux8jhE%2BhLVkDMtikks6x2KH49U; cflag=15%3A3" "https://pcs.baidu.com/rest/2.0/pcs/file?method=download&app_id=250528&path=%2F%EF%BC%88%E7%91%9E%E6%A0%91X%E8%90%8C%E4%BD%A0%E5%A6%B9%E7%89%88%EF%BC%89%E7%BE%8E%E5%B0%91%E5%A5%B3%E4%B8%87%E5%8D%8E%E9%95%9C%20%E7%BD%AA%E4%B8%8E%E7%BD%9A%E7%9A%84%E5%B0%91%E5%A5%B3.rar"

**Comment by aiwonanjing** [comment]
可以考虑在设置界面加一项：读取cookie
表示实在没看懂怎么弄，但愿修改后能暂时解决吧。

**Comment by SdtElectronic** [comment]
小白初次使用遇到一奇葩问题，自己瞎折腾解决了，贴上来以防有人遇到相同问题，也请大大分析一下原因（非专业相关，所以不懂）
Aria2服务部署在路由器上，使用YAAW客户端，直接RPC创建任务错误。使用ssh创建任务，提示错误：SSL/TLS handshake failure: unable to get local issuer certificate.
搜索后有同样错误的人可以在配置里附加：check-certificate=false
可以解决
似乎是跳过了证书的某种审查机制，不知道对安全性方面有无影响

**Comment by acgotaku** [comment]
这个我说过好多回了 而且也提供示例的配置文件了。。。
