### ISSUE TITLE
rpc设置无法正常连接

### ISSUE THREAD

**Issue by ZTielong** [acgotaku/BaiduExporter#553]
在百度网盘中可以导出文本链接并使用aria2c命令行正常下载，但是设置中检查rpc连接时，无论怎么都显示“请查看是否开启aria2”，冒昧请教一下作者，非常感谢。
rpc设置：http://192.168.3.2:6800/jsonrpc

插件通过chrome/release加载到chrome， version 1.0.2
aria2 version 1.33.1
aria2启动：aria2c --enable-rpc --rpc-listen-all --rpc-allow-origin-all=true --dir=/tmp
平台：树莓派
telnet 树莓派6800端口正常，且使用yaaw等web ui都可以正常连接并创建任务。
清空过浏览器缓存。
之前版本应该是0.9.x的时候也尝试过，那时候以为是自己开启了https等其他因素导致校验不行，这次尝试只用基础配置启动，还是没能成功。

**Comment by acgotaku** [comment]
这种情况下只能自己调试看看了 你给的私网地址 我也无法查询啊

可以看看载入扩展的开发者页面 是否有异常输出 或者看看前端有没有异常

**Comment by ZTielong** [comment]
经测试，虽然测试连接显示“请查看是否开启aria2”，但是，忽略这个提醒，直接保存后，下载是可以正常调起rpc请求的。

**Comment by acgotaku** [comment]
那就好
