### ISSUE TITLE
勾选某个文件后，下载按钮没了

### ISSUE THREAD

**Issue by junjian-yuan** [acgotaku/BaiduExporter#554]
1. 下载的内容地址
https://pan.baidu.com/s/1kVsm94V#list/path=%2F%E5%AE%98%E7%BD%91%E4%B8%8B%E8%BD%BD%E8%B5%84%E6%96%99%2F20170601%E6%9B%B4%E6%96%B0%2F%E5%85%B3%E4%BA%8E%E5%AE%98%E7%BD%91%E5%8D%87%E7%BA%A7%2FD600S-GD%20%E5%89%8D%E5%90%8E%E5%8F%8C%E5%BD%95%E8%AE%B0%E5%BD%95%E4%BB%AA%E7%94%B5%E5%AD%90%E7%8B%97%E5%8D%87%E7%BA%A7%E5%8C%8520170601%2FADAS-GD%20Update&parentPath=%2F%E5%AE%98%E7%BD%91%E4%B8%8B%E8%BD%BD%E8%B5%84%E6%96%99%2F20170601%E6%9B%B4%E6%96%B0%2F%E5%85%B3%E4%BA%8E%E5%AE%98%E7%BD%91%E5%8D%87%E7%BA%A7

2. 插件版本号：0.9.5，浏览器版本号63.0.3239.84（正式版本） （64 位），系统版本号 macOS

3. 列举出现问题的详细步骤

在带有勾选列表的画面中，勾选某个文件，下载按钮没了。

4. 描述能否复现问题
每次都这样

<img width="712" alt="qq20180124-170125 2x" src="https://user-images.githubusercontent.com/10084420/35323400-4b9247d6-0128-11e8-83a2-e6660806f63e.png">
<img width="831" alt="qq20180124-170146 2x" src="https://user-images.githubusercontent.com/10084420/35323401-4bc7e422-0128-11e8-8497-d65dcf7ec393.png">

**Comment by acgotaku** [comment]
现在已经1.0.2 版本了
记得更新。。。

**Comment by Inori-Lover** [comment]
可以close issue……

**Comment by laike9m** [comment]
升级后就好了

**Comment by jiujiubad** [comment]
刚刚想下载东西，跟@junjian-yuan一样的情况，更新到1.0.2并重启chrome，还是一样。。大家的都没问题吗？？

**Comment by jiujiubad** [comment]
解决了！！！重启电脑后就可以。

**Comment by junjian-yuan** [comment]
刚刚看见，升级后问题解决，感谢！
