### ISSUE TITLE
最新版登陆普通会员后可导出下载，但SVIP一导出马上出错403

### ISSUE THREAD

**Issue by ChicBrother** [acgotaku/BaiduExporter#555]
请确保以下几点：

1. 已经阅读过README 已读
2. 尝试安装最新版本插件 已安
3. 尝试清空浏览器缓存 已清
4. 尝试卸载插件后重新安装 已做

发起 Issue 时，请提供：

1. 您下载的内容地址  https://pcs.baidu.com/rest/2.0/pcs/file?method=download&app_id=250528&path=%2F%E7%A5%9E%E5%A5%87%E5%A5%B3%E4%BE%A0.2017.1080p.%E5%9B%BD%E8%8B%B1%E5%8F%8C%E8%AF%AD.%E4%B8%AD%E8%8B%B1%E5%AD%97%E5%B9%95%EF%BF%A1CMCT%E6%97%A0%E5%B0%BD%2F%5B%E7%A5%9E%E5%A5%87%E5%A5%B3%E4%BE%A0%5D.Wonder.Woman.2017.BluRay.1080p.x264.AC3.2Audios-CMCT.mkv
2. 插件版本号，浏览器版本号，系统版本号 Chrome  63.0.3239.132正式版
3. 列举出现问题的详细步骤
4. 描述能否复现问题 可以

我于三天前更新了最新版插件，刚更新那会SVIP会员可导出下载，速度正常。但昨天开始SVIP一导出马上出错，复制导出文本命令行测试返回403.

但登陆普通会员后可导出下载正常，速度为普通 会员的限速速度。

SVIP 导出的文本是

`
aria2c -c -s10 -k1M -x16 --enable-rpc=false -o "[神奇女侠].Wonder.Woman.2017.BluRay.1080p.x264.AC3.2Audios-CMCT.mkv" --header "User-Agent: netdisk;5.3.4.5;PC;PC-Windows;5.1.2600;WindowsBaiduYunGuanJia" --header "Referer: https://pan.baidu.com/disk/home" --header "Cookie: BDUSS=39PM2I4V2tIVWVhNnJtandLcHpIYk0yVVRDQW90VHZkWTVHdTNhdk0tZ0R4SkJhQVFBQUFBJCQAAAAAAAAAAAEAAACKPAtlc2Rhc3ZhZ2dkZmgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAM3aVoDN2laY; pcsett=1516938806-835130fb1c7e92ef6c4416bd2e510b20" "https://pcs.baidu.com/rest/2.0/pcs/file?method=download&app_id=250528&path=%2F%E7%A5%9E%E5%A5%87%E5%A5%B3%E4%BE%A0.2017.1080p.%E5%9B%BD%E8%8B%B1%E5%8F%8C%E8%AF%AD.%E4%B8%AD%E8%8B%B1%E5%AD%97%E5%B9%95%EF%BF%A1CMCT%E6%97%A0%E5%B0%BD%2F%5B%E7%A5%9E%E5%A5%87%E5%A5%B3%E4%BE%A0%5D.Wonder.Woman.2017.BluRay.1080p.x264.AC3.2Audios-CMCT.mkv"
`
命令行执行后的错误是：

`01/25 11:54:58 [NOTICE] Downloading 1 item(s)

01/25 11:54:58 [ERROR] CUID#7 - Download aborted. URI=https://pcs.baidu.com/rest/2.0/pcs/file?method=download&app_id=250528&path=%2F%E7%A5%9E%E5%A5%87%E5%A5%B3%E4%BE%A0.2017.1080p.%E5%9B%BD%E8%8B%B1%E5%8F%8C%E8%AF%AD.%E4%B8%AD%E8%8B%B1%E5%AD%97%E5%B9%95%EF%BF%A1CMCT%E6%97%A0%E5%B0%BD%2F%5B%E7%A5%9E%E5%A5%87%E5%A5%B3%E4%BE%A0%5D.Wonder.Woman.2017.BluRay.1080p.x264.AC3.2Audios-CMCT.mkv
Exception: [AbstractCommand.cc:351] errorCode=22 URI=https://pcs.baidu.com/rest/2.0/pcs/file?method=download&app_id=250528&path=%2F%E7%A5%9E%E5%A5%87%E5%A5%B3%E4%BE%A0.2017.1080p.%E5%9B%BD%E8%8B%B1%E5%8F%8C%E8%AF%AD.%E4%B8%AD%E8%8B%B1%E5%AD%97%E5%B9%95%EF%BF%A1CMCT%E6%97%A0%E5%B0%BD%2F%5B%E7%A5%9E%E5%A5%87%E5%A5%B3%E4%BE%A0%5D.Wonder.Woman.2017.BluRay.1080p.x264.AC3.2Audios-CMCT.mkv
  -> [HttpSkipResponseCommand.cc:239] errorCode=22 The response status is not successful. status=403

01/25 11:54:58 [NOTICE] Download GID#8aa4a04a5e95a7c1 not complete: D:/Program Files/aria2/[神奇女侠].Wonder.Woman.2017.BluRay.1080p.x264.AC3.2Audios-CMCT.mkv

Download Results:
gid   |stat|avg speed  |path/URI
======+====+===========+=======================================================
8aa4a0|ERR |       0B/s|D:/Program Files/aria2/[神奇女侠].Wonder.Woman.2017.BluRay.1080p.x264.AC3.2Audios-CMCT.mkv

Status Legend:
(ERR):error occurred.`

真是搞不懂，SVIP反倒不能导出下载了。

**Comment by acgotaku** [comment]
我没  SVIP  还真不好测试

**Comment by ChicBrother** [comment]
@acgotaku 雪大我发svip帐号给你吧，以后你也可以一直用来测试。用什么方式发给你呢？

**Comment by acgotaku** [comment]
@ChicBrother  acgotaku 311 gmail com  我并不保证测试了 能修好啊  ==

**Comment by minosss** [comment]
我的不是vip也一样，提示403   会不会被封了 T_T  在线也完全看不了了

**Comment by y2kbug-hk** [comment]
上星期試，沒有登入不能下載，登入後可，但很多任務都不能一次完整下載好，百度好像不太穩定

**Comment by minosss** [comment]
> 新注册帐号后发现可以在线看，估计是帐号限额了吧  🤣

**Comment by y2kbug-hk** [comment]
弄了好多天終於可以使用支款寶的結餘了，買了百度盤三個月超級會員。經Exporter用Aria下載沒有問題啊！
