### ISSUE TITLE
下载到99%之后速度逐渐减少到0

### ISSUE THREAD

**Issue by ashcorn** [acgotaku/BaiduExporter#556]
请确保以下几点：

1. 已经阅读过README
2. 尝试安装最新版本插件
3. 尝试清空浏览器缓存
4. 尝试卸载插件后重新安装

发起 Issue 时，请提供：

1. 您下载的内容地址：https://pan.baidu.com/s/1c19f76C
2. 插件版本号：1.0.2，浏览器版本号：Chrome 63.0.3239.132 ，系统版本号：OS X 10.13.2
3. 列举出现问题的详细步骤：清理浏览器缓存后导出下载ARIA2 PRC
4. 描述能否复现问题：开始速度在2m/s左右一直维持到99%，99%之后资源连接数和速度都开始下降，最后在99.5%左右速度彻底没了，重复下载了多次都是这个结果

----------

**不符合上述条件的Issue将被无理由关闭**

**Comment by acgotaku** [comment]
下载速度这个问题 不属于本插件的功能范围
