### ISSUE TITLE
被谷歌标记为恶意扩展程序

### ISSUE THREAD

**Issue by yedajiang44** [acgotaku/BaiduExporter#557]
下载后准备安装，但是尴尬的一幕发生了。。。。
![image](https://user-images.githubusercontent.com/25813145/35489588-79ec24ae-04d3-11e8-9d77-45834360888b.png)

**Comment by Sak94664** [comment]
git clone源码，然后chrome://extensions.
然后启用开发者模式。
之后加载打包的扩展程序。
转到源码目录>chrome>release。
选择该文件夹。
然后确认就行啦。

**Comment by acgotaku** [comment]
这种情况下就只能开发者模式载入了。。。
