### ISSUE TITLE
造福大家：火狐 安装扩展方法

### ISSUE THREAD

**Issue by guoluke1000** [acgotaku/BaiduExporter#558]
1.首先你的火狐是非正式版，可以是长期维护版（ESR）、开发者版本（developer）、每夜版（Nightly editions）、无认证版（Unbranded Builds）、普通人还是推荐ESR版本吧，地址栏about:config，并将“xpinstall.signatures.required”值设为 false，来跳过扩展的验证机制强行启用
https://bbs.kafan.cn/thread-2052440-1-1.html  参考网址
2.下载chrome扩展crx（废话）
3.下载火狐扩展Chrome Store Foxified  https://addons.mozilla.org/zh-CN/firefox/addon/chrome-store-foxified/
4.打开Chrome Store Foxified，上传你的crx扩展，期间要求注册或登录你的火狐账号（选择同意的操作），刷新页面，上传成功后将转换成xpi扩展，点击Signed的链接下载到本地安装（进入附加组件拖拽安装，不要在线安装，巨坑)
5.打开附加组件和百度云看看，是不是成功啦
6.提示：现在百度抓得严，还是不要登录用户名下载啦，把要下载的东西分享出去在下载，目前成功

**Comment by helmholts** [comment]
适用于Firefox 57+
https://addons.mozilla.org/en-US/firefox/addon/acg-baiduexporter/
https://addons.mozilla.org/en-US/firefox/addon/baidu-pan-exporter/
网页上的Version History里有适用于Firefox 48+的

**Comment by GarrisonBaird** [comment]
- the first step is unnecessary, the step 4 gets the addon signed.
- if you switch `xpinstall.signatures.required` to `false`, you don't have to follow these steps, just zip [BaiduExporter/chrome/release/*](/acgotaku/BaiduExporter/tree/master/chrome/release) to a `.xpi` file, drag into firefox, and then you should be good to go.

**Comment by lindichao** [comment]
@GarrisonBaird I followed your instruction by typing zip -r BaiduExporter.xpi ./BaiduExporter/chrome/release/*, when I installed from file, it showed "This add-on could not be installed because it appears to be corrupt", after tried debugging add-ons, it showed "There was an error during installation: File /home/whatever/Downloads/BaiduExporter.xpi does not contain a valid install manifest", any advice will be appreciated.

**Comment by GarrisonBaird** [comment]
@lindichao I suggest you to redownload it from github and try again. dc457a63d0598caa13dd1de1cbd18cd7e4214397 this should work. 
Also, make sure that you remove the old one from the browser before installing the new one.
If you just wanna make it work, try my signed xpi #437

**Comment by guoluke1000** [comment]
@GarrisonBaird I have also tried your idea, but encountered the same problem as lindichao. In addition, the first step is somewhat unnecessary, but you can also choose to install unsigned extensions in the step 4 , which facilitate the installation of other unsigned extensions later.

**Comment by GarrisonBaird** [comment]
@guoluke1000 @lindichao I find it out.
According to [MDN](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/WebExtensions_and_the_Add-on_ID), we have to add an `ID` to `manifest.json` if we wanna install an unsigned addon.
> If you are loading the add-on from it's XPI file, are not loading it temporarily using about:debugging and it is not signed.

So just add something like this to `manifest.json` before zipping it:
``` json
  "author": "acgotaku",
  "version": "1.0.2",
  "applications": {
    "gecko": {
      "id": "addon@example.com"
    }
  }
}
```
> The extension ID must be one of the following:
> * GUID
> * A string formatted like an email address: `extensionname@example.org`
> 
> For example:
> ``` json
> "id": "extensionname@example.org",
> "id": "{daf44bf7-a45e-4450-979c-91cf07434c3d}"
> ```

**Comment by fnscar** [comment]
Chrome Store Foxified似乎在较新版本的firefox上已失效，作者也说不再继续开发了。
只能麻烦一点自己手动通过AMO签名了，方法如下：
https://blog.csdn.net/freedomswings/article/details/81747886
