### ISSUE TITLE
不是本地運行 aria2， 『导出下载』 不显示 "ARIA2 RPC"

### ISSUE THREAD

**Issue by samsonluk** [acgotaku/BaiduExporter#559]
2. 插件版本号，浏览器版本号，系统版本号
BaiduExporter 1.0.2,  Chrome Version 49.0.2623.112,  Win XP

3. 列举出现问题的详细步骤
导出下载 不显示 "ARIA2 RPC" 选项，本文导出没有问题

4. 描述能否复现问题
能复现问题

可能是因为 aria2 不是本地运行， 尝试本地运行是会显示的

![untitled0](https://user-images.githubusercontent.com/11514471/35763827-d32620f4-08ef-11e8-9978-2d90d111ffb4.jpg)

![untitled1](https://user-images.githubusercontent.com/11514471/35763828-d78daa36-08ef-11e8-9197-2a9224145dce.jpg)

![untitled2](https://user-images.githubusercontent.com/11514471/35763831-dcecf2de-08ef-11e8-9dbc-6bcbfb525278.jpg)

**Comment by acgotaku** [comment]
点击重置呢？

打开开发者模式看看有没有错误？

**Comment by samsonluk** [comment]
点击重後置就再也聯絡不上 aria2
![mstsc_2018-02-03_18-36-50](https://user-images.githubusercontent.com/11514471/35766342-590bd9c2-0911-11e8-8adf-f078d1748078.jpg)

要從新輸入 "aria2 RPC"  "http://192.168.11.152:6800/jsonrpc"  再按"應用"才可以連接
![mstsc_2018-02-03_18-34-29](https://user-images.githubusercontent.com/11514471/35766360-e5fd7cf0-0911-11e8-8ade-428dbdbe68c7.jpg)

但是如果關閉 Chrome, 重新進入百度再開 "設置" 就發現一切清空, 雖然按測試還是能連上, 如上圖

**Comment by samsonluk** [comment]
打开开发者模式後可以做什麼?

**Comment by acgotaku** [comment]
就是点击 F12 看看Console面板有没有报错
你是用的CRX安装 还是用的release文件夹？

**Comment by samsonluk** [comment]
我是用release文件夹
![mstsc_2018-02-03_23-55-10](https://user-images.githubusercontent.com/11514471/35768908-c3dc435a-093d-11e8-96c0-bb2e69769963.jpg)

点击 F12
![1](https://user-images.githubusercontent.com/11514471/35768927-30293892-093e-11e8-9fd1-181e9c8b4227.jpg)
![2](https://user-images.githubusercontent.com/11514471/35768930-35774866-093e-11e8-84d5-ef7bd0738fa2.jpg)

**Comment by acgotaku** [comment]
应该是你的Chrome版本太低了  更新下试试？

**Comment by samsonluk** [comment]
更新至 Chrome Version 49.0.2623.112， 已經是 XP 可安裝的最後版本:(
![mstsc_2018-02-04_10-04-26](https://user-images.githubusercontent.com/11514471/35773650-2ab304ec-0993-11e8-8f72-0d6bd1cb2986.jpg)

最後 Uncaught TypeError ... forEach is not a function 是按下"應用"出的

**Comment by acgotaku** [comment]
恩 我知道  那个forEach是在Chrome51之后才支持的。所以更新到51之后就没毛病了

**Comment by samsonluk** [comment]
Chrome51 不容許安裝

**Comment by acgotaku** [comment]
你再下载最新的， 我应该修复了这个BUG

**Comment by samsonluk** [comment]
修復了,謝謝!!
