### ISSUE TITLE
依旧不能下载，不论是分享界面还是home界面。谢谢

### ISSUE THREAD

**Issue by CoYangJR** [acgotaku/BaiduExporter#562]
请确保以下几点：

1. 已经阅读过README:ok
2. 尝试安装最新版本插件:ok
3. 尝试清空浏览器缓存:ok
4. 尝试卸载插件后重新安装:ok

发起 Issue 时，请提供：

## 1. 您下载的内容地址
不论是home还是分享的都存在，例如：
> https://pan.baidu.com/s/1smARLqX

## 2. 插件版本号，浏览器版本号，系统版本号
>插件Version: 1.0.2
浏览器 Google Chrome | 64.0.3282.140 (正式版本) （64 位）
系统 macOS 10.13.3

## 3. 列举出现问题的详细步骤
> 导出下载 -> ARIA2 RPC 

然后回到路由器的aria2 的管理界面，发现下载出错

> ![image](https://user-images.githubusercontent.com/25633151/36074427-b68923d8-0f7a-11e8-8738-aaac68588c84.png)

## 4. 描述能否复现问题
可以

不知道是不是和[issue #547 ](https://github.com/acgotaku/BaiduExporter/issues/547)的原因一样。
谢谢

**Comment by acgotaku** [comment]
![screenshot from 2018-02-11 23-34-33](https://user-images.githubusercontent.com/1191834/36074518-26b240d2-0f84-11e8-9274-458cabfb82ac.png)

你给我的链接 我可以直接下载

你确认下 是不是自己配置问题 或者储存文件权限问题？

或者贴出 导出下载的文本？

查看下 Aria2c 日志？

**Comment by CoYangJR** [comment]
我在web上可以直接下载其他的文件，应该不是权限问题。
文本如下
> aria2c -c -s10 -k1M -x16 --enable-rpc=false -o "Minecraft.dmg" --header "User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36" --header "Referer: https://pan.baidu.com/disk/home" --header "Cookie: BDUSS=YwZ2hmMnNsfm9kTmh1a2JSSUlmWS1vUE5Da3RoT2NscUhhcmFsMUZ3U3lhS05hQVFBQUFBJCQAAAAAAAAAAAEAAADycogOvfXI2Tg4OAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAALLbe1qy23taVz; pcsett=1518446298-cb014c015f5a17e7d5bda31fe9659ea6" "https://d.pcs.baidu.com/file/7f264959d437afcf58c668c0922a530d?fid=1913306199-250528-828187444317235&time=1518360333&rt=sh&sign=FDTAERV-DCb740ccc5511e5e8fedcff06b081203-WVUG4odB9ULV0wnHkD%2Brbc7zMW0%3D&expires=8h&chkv=1&chkbd=0&chkpc=&dp-logid=972899469189990239&dp-callid=0&r=148227928"

 日志：
> 2018-02-11 23:06:07.538619 [ERROR] [AbstractCommand.cc:351] CUID#10 - Download aborted. URI=https://d.pcs.baidu.com/file/7f264959d437afcf58c668c0922a530d?fid=1913306199-250528-828187444317235&time=1518361482&rt=sh&sign=FDTAERV-DCb740ccc5511e5e8fedcff06b081203-q8OYG5h4570molHrKOT1eiwLYMM%3D&expires=8h&chkv=1&chkbd=0&chkpc=&dp-logid=973208042637600496&dp-callid=0&r=269944342
Exception: [AbstractCommand.cc:351] errorCode=1 URI=https://d.pcs.baidu.com/file/7f264959d437afcf58c668c0922a530d?fid=1913306199-250528-828187444317235&time=1518361482&rt=sh&sign=FDTAERV-DCb740ccc5511e5e8fedcff06b081203-q8OYG5h4570molHrKOT1eiwLYMM%3D&expires=8h&chkv=1&chkbd=0&chkpc=&dp-logid=973208042637600496&dp-callid=0&r=269944342
  -> [SocketCore.cc:1015] errorCode=1 SSL/TLS handshake failure: unable to get local issuer certificate

我重新安装aria2后依旧不行。。

**Comment by zihengcat** [comment]
苹果的锅，最新 macOS High Sierra（10.13）系统的本地CA证书支持有问题，许多开源项目（似乎是用了 Apple TLS 库的，[例如这个](https://discussions.apple.com/thread/8125746)）都遇到了类似的问题：**无法正确获取本地CA证书** `unable to get local issuer certificate` 
据说是苹果在最新的系统中升级了SSL/TLS模块，让用户上网更加安全可靠 23333

> 上面那个例子也很有意思，系统自带的`cURL`出问题，`brew`安装的`cURL`没问题 
> 估计`brew`版`cURL`编译时没用系统Apple TLS库，用了其他认证库

这个问题其实和 *BaiduExporter* 没有关系，**aria2** macOS版编译默认使用系统 Apple TLS 库，所以嘛...

## 解决方案
- 添加`--check-certificate=false`选项，取消证书核对
> 文档：https://aria2.github.io/manual/en/html/aria2c.html#cmdoption-check-certificate
> **参考**：https://github.com/aria2/aria2/issues/889

- 手动指定CA证书（比较麻烦，也不确定是否有效）
> 文档：https://aria2.github.io/manual/en/html/aria2c.html#cmdoption-certificate

- 重编译*aria2*，换SSL认证库
> 文档：https://github.com/aria2/aria2#how-to-build

**Comment by acgotaku** [comment]
@CoYangJR 楼上已经给你解决方案了。。。

**Comment by CoYangJR** [comment]
好的,谢谢.
