### ISSUE TITLE
我这里网速挺快的，为啥下载东西都是稳定150-160K之间，用的是最新chrome和最新aria2和插件

### ISSUE THREAD

**Issue by XavierXuV5** [acgotaku/BaiduExporter#563]
我这里网速挺快的，为啥下载东西都是稳定150-160K之间，用的是最新chrome和最新aria2和插件，求告知是为什么，谢谢大佬们了。

**Comment by XavierXuV5** [comment]
还有我的是Mac OS X 10.10.5

**Comment by acgotaku** [comment]
因为你没有充值会员啊。。。

百度早就服务器端限制速度了。。。

**Comment by bravo227090** [comment]
https://yqall02.baidupcs.com/file/
https://allall01.baidupcs.com/file/
https://allall02.baidupcs.com/file/
http://nj02all01.baidupcs.com/file/

上面是有VIP直连的网址

把鏈接中的 http://d.pcs.baidu.com/file/ 替換為上面几个试试

开发大 可以试试导出的直连 改为上面4个试试

**Comment by XavierXuV5** [comment]
谢谢，但是按照楼上的导出来，换过了，都好像失败了

**Comment by bravo227090** [comment]
这是令一个油猴插件导出的直连 更换可以

不过用雪月大的导出的直连 我也不太晓得怎更换
看雪月大是不是可以研究下

**Comment by XavierXuV5** [comment]
好的 我去试试，谢谢你

**Comment by XavierXuV5** [comment]
谢谢你，真的可以，谢谢了哈。

**Comment by bravo227090** [comment]
我没有要推其他插件的..
我只用雪月的，只是希望雪月大能试试把导出来的直连 改成上面那4个试试

这样速度上就没有限制了

**Comment by sarkdavidson** [comment]
50兆电信网络，亲测 http://nj02all01.baidupcs.com/file/ 可以轻松跑3M/s

**Comment by samsonluk** [comment]
近日發現無登錄下載，最大連接數不能超過10

**Comment by troyliu0105** [comment]
最新的aria2的相同服务器连接数被限制在了16，需要自己修改。
然后，我发现如果使用BaiduExporter添加任务总是很慢，链接数被限制在了15左右...，速度也在100kb上下

另外，[baidudl](https://github.com/Kyle-Kyle/baidudl)这个插件相比之下速度快了好多，链接数一般在80左右，速度一般为4Mb左右

网络环境：重庆电信，100M

**Comment by sarkdavidson** [comment]
@troyliu0105 [aria2c 128 线程版本](https://link.jianshu.com/?t=https%3A%2F%2Fdn-shimo-attachment.qbox.me%2FN4ejFIomaUsWaiip%2Faria2c.zip) 替换/usr/local/cellar/aria2c/xxx/bin 对应进程，当然 BaiduExporter 也需要调整，`设置` - `http://localhost:6800/jsonrpc#max-connection-per-server=128&split=128` 
_（具体参考简书这篇文 https://www.jianshu.com/p/6df3663fb472）_

**Comment by samsonluk** [comment]
連線限制似乎是在百度方面造成，和修改 aria2c 參數無關

**Comment by ufo7851376** [comment]
@bravo227090 您好 麻烦问下 MAC电脑在哪里修改连接啊？ 谢谢您 麻烦您有空的话回复下。我下载的aira2GUI直接拖进应用程序的  没看见设置里面有修改连接的地方 拜托了

**Comment by troyliu0105** [comment]
新版的已经添加了设置选项，按CMD+，调出Preferences，在Web标签下的。。。。

On 21 Feb 2018, at 11:45 PM, ufo7851376 <notifications@github.com<mailto:notifications@github.com>> wrote:


@bravo227090<https://github.com/bravo227090> 您好 麻烦问下 MAC电脑在哪里修改连接啊？ 谢谢您 麻烦您有空的话回复下。我下载的aira2GUI直接拖进应用程序的 没看见设置里面有修改连接的地方 拜托了

**Comment by rilyuuj** [comment]
@bravo227090 请问这些vip的油脚猴本哪里找的？

**Comment by lweo** [comment]
@bravo227090 您好，是替换home.js里的
`link: `${location.protocol}//pcs.baidu.com/rest/2.0/pcs/file?method=download&app_id=250528&path=${encodeURIComponent(files[key].path`

这里的链接吗？

**Comment by lweo** [comment]
@bravo227090 这些链接都失效了吗？我试了在session里替换，都是400，

**Comment by acgotaku** [comment]
@bravo227090 经过我的测试 会自动重定向到 yqall02.baidupcs.com 这个域名 所以还是没啥意义？

**Comment by OliverLew** [comment]
我的没什么问题，我的方法是直接下载分享出来的文件（不要从自己的网盘页下，自己的文件也要分享出去）。之前也是下自己的文件，结果只有100k。
必要的话在导出的链接或文件中去掉header里的cookie，不知道有没有坏处，不过有些时候确实管用了。（我觉得cookie只是在下载自己的文件时有用，因为链接是网盘的相对路径）

所以我的经验是和建议的用法相反的，恰恰要尽量不和自己的账号有联系，而usage第一句话就是

> 非SVIP用户下载分享文件须先将文件保存到自己网盘以获得较快的下载速度。

不知道 @acgotaku 具体是为什么。

**Comment by eexpress** [comment]
要是能改成axel作后台就好了。

**Comment by louislou123** [comment]
那mac版要怎么做才能突破下载限制呢？本人在国外，下载速度之前可以达到2mb/s，现在只有150kb/s还时不时断线，谢谢。

**Comment by acgotaku** [comment]
@louislou123 充钱

**Comment by Alalalalaki** [comment]
@acgotaku  充了超级会员还被限速怎么办、、、、、、

**Comment by JasonKhew96** [comment]
https://github.com/acgotaku/BaiduExporter/issues/563#issuecomment-365156220

这楼的方法是有效的，如果是自己的网盘的文件，需要分享链接过后下载，不能直接在自己网盘下。
UA应该没关系，试过yqall02.baidupcs.com，是满速的。
