### ISSUE TITLE
aria2 连接测试

### ISSUE THREAD

**Issue by forest0** [acgotaku/BaiduExporter#564]
在配置 RPC 地址后，**未点击下方的应用按钮**，然后立即点击*测试连接*，似乎此时测试使用的 RPC 地址是上一次保存后的 RPC 地址，而不是当前输入框中的地址。

![image](https://user-images.githubusercontent.com/20063987/36350977-131afe98-14dd-11e8-9e47-01895462fb82.png)

个人认为使用输入框中的最新 RPC 地址测试连接也许更为合理。

刚刚自己配置时，填完 RPC 地址就立即*测试连接*，然而未点击*应用*之前，测试连接永远得到"错误，请查看是否开启Aria2"。开始还以为自己 token 填错了。。。

- BaiduExporter: 1.0.2
- OS: Win 10
- Chrome: 64.0.3282.167

**Comment by acgotaku** [comment]
目前没有自动保存功能。。。。

你就多费心 点击一下吧。。。

**Comment by samsonluk** [comment]
請問『配置同步』是什麼意思？

**Comment by JasonKhew96** [comment]
@samsonluk 
https://github.com/acgotaku/BaiduExporter/blob/master/chrome/src/js/lib/store.js#L55
chrome的同步功能

**Comment by acgotaku** [comment]
@samsonluk 配置同步 是在你同一个账户的多个Chrome浏览器中 同步你所有的配置数据。
