### ISSUE TITLE
请问，chrome如何安装呢？？

### ISSUE THREAD

**Issue by hyyzhuceyong** [acgotaku/BaiduExporter#566]
商店貌似已经搜索不到了，直接拖BaiduExporter.crx显示灰色无法启用，加载已解压的扩展程序到文件夹chrome，显示错误，请教应该如何安装呢？？
![20180225005842](https://user-images.githubusercontent.com/26433019/36632914-9e824510-19c7-11e8-9f13-d22ca87d2ce5.png)
![20180225005903](https://user-images.githubusercontent.com/26433019/36632917-a50ea9aa-19c7-11e8-8e32-65016442e043.png)

**Comment by JasonKhew96** [comment]
`chrome/release` 文件夹

**Comment by hyyzhuceyong** [comment]
已经解决，谢谢楼上、、
