### ISSUE TITLE
为什么我在安转过程中总提示“无法加载扩展程序图标“img/logo16.png””呀

### ISSUE THREAD

**Issue by Lancelotstar** [acgotaku/BaiduExporter#567]
各位过年好，最近电脑新安装了系统，重新下载了chrome和aria2gui，今天下载雪大插件的时候为什么安装不能呢，总提示无法加载扩展程序图标“img/logo16.png”，谢谢。

**Comment by JasonKhew96** [comment]
`chrome/release` 文件夹
