### ISSUE TITLE
不显示的问题

### ISSUE THREAD

**Issue by ioojcn** [acgotaku/BaiduExporter#569]
请确保以下几点：

1. 已经阅读过README
2. 尝试安装最新版本插件
3. 尝试清空浏览器缓存
4. 尝试卸载插件后重新安装

发起 Issue 时，请提供：

1. 您下载的内容地址
百度网盘
2. 插件版本号，浏览器版本号，系统版本号
最新GITHUB. CHROME.WIN10
3. 列举出现问题的详细步骤
能看见导出下载按钮,但是选择一个文件以后.这个按钮就没有了..最右侧的图标是推送到云设备
4. 描述能否复现问题

----------

**不符合上述条件的Issue将被无理由关闭**

**Comment by acgotaku** [comment]
最新是多新啊  ==

我测试的是没问题啊

**Comment by ioojcn** [comment]
抱歉是我的原因...我用的是releases0.8.5
