### ISSUE TITLE
正在获取下载地址后就没反应了

### ISSUE THREAD

**Issue by ouyangqifeng** [acgotaku/BaiduExporter#570]
1. 您下载的内容地址
https://pcs.baidu.com/rest/2.0/pcs/file?method=download&app_id=250528&path=%2F4.%E7%BB%98%E7%94%BB%E8%B5%84%E6%96%99%2F%E8%9A%82%E8%9A%81%E7%AD%89%E5%A4%9A%E4%B8%AA%E6%96%87%E4%BB%B6%2F%E8%9A%82%E8%9A%81%2F20160904%2F01.mp4

2. 插件版本号1.0.2，浏览器版本号chrome64.0.3282.186，系统版本号OSX EI Capitan10.11.6
ARIA2版本号1.4

3. 列举出现问题的详细步骤
在百度网盘网页下，选择文件或文件夹，点导出下载，然后选ARIA2 RPC，弹出正在获取下载地址，然后消失了，什么也没发生。
可以文本导出，复制到ARIA2添加，无法下载。
但是通过分享页面的可以下载

4. 
试了好多次都出现这个问题

**Comment by acgotaku** [comment]
能不能给个分享页面的地址？ 话说 你都获取到 mp4地址了。。。 为啥会没反应？

**Comment by acgotaku** [comment]
不过现在那个地址已经过期了 既然解决了 就close了

**Comment by devymex** [comment]
搜索出来的文件就会出现这样的现象。
