### ISSUE TITLE
已加check-certificate=false,报错 SSL/TLS handshake failure: Connection aborted

### ISSUE THREAD

**Issue by nightsnack** [acgotaku/BaiduExporter#571]
1.  下载的内容地址：https://pan.baidu.com/s/1dGoqEA1 
     任何一个百度网盘的地址均是如此
2. 插件版本号：Version: 1.0.2 Update date: 2017/12/30 github主分支上最新版本
    aria2版本：1.33.1，
    浏览器版本：Chrome Version 64.0.3282.186 (Official Build) (64-bit)
    系统：macOS High Sierra 10.13.3

3. 列举出现问题的详细步骤：aria2 GUI中直接添加链接，可以下载，
    百度网盘导出下载，无速度，无文件大小，进度条不动，只显示文件名，过几秒文件显示错误
    日志：

> 2018-03-04 14:53:44.964329 [ERROR] [AbstractCommand.cc:351] CUID#18 - Download aborted. URI=https://pcs.baidu.com/rest/2.0/pcs/file?method=download&app_id=250528&path=%2FSSH.txt
Exception: [AbstractCommand.cc:351] errorCode=1 URI=https://pcs.baidu.com/rest/2.0/pcs/file?method=download&app_id=250528&path=%2FSSH.txt
  [SocketCore.cc:1015] errorCode=1 SSL/TLS handshake failure: Connection aborted

    aria2.conf已添加check-certificate=false,

    终端已挂代理，ss打开，终端curl谷歌正常。

4. 能否复现问题
    可以复现问题。

**Comment by WangWanglin** [comment]
也遇到此问题。

**Comment by acgotaku** [comment]
添加的链接 是导出的链接？

**Comment by nightsnack** [comment]
不是，直接添加导出的链接直接下载失败，添加一个别的地方的链接，非百度云的，比如邮件附件之类的都可以下

**Comment by tofuliang** [comment]
Mac自带的加密库有问题,导致编译出来的aria2有问题,我在下载BT的时候遇到过,换成OpenSSL就好.

在 2018/3/5，Nightsnack Cai<notifications@github.com> 写道：

**Comment by nightsnack** [comment]
@tofuliang 也就是说不要用homebrew安装了，自己手动编译吗？
在哪里换OpenSSL

**Comment by tofuliang** [comment]
在终端执行
```bash
brew edit aria2
```

然后将formula改成下文
```ruby
class Aria2 < Formula
  desc "Download with resuming and segmented downloading"
  homepage "https://aria2.github.io/"
  url "https://github.com/aria2/aria2/releases/download/release-1.33.1/aria2-1.33.1.tar.xz"
  sha256 "2539e4844f55a1f1f5c46ad42744335266053a69162e964d9a2d80a362c75e1b"

  bottle do
    cellar :any_skip_relocation
    sha256 "1992d39c07ad9de977413b71dedbc78cc83943dc2597a159ab0fc15784310dfd" => :high_sierra
    sha256 "464a54003a4f8d177065113650f4da67b3fd608c219640a0088ccc955759e43c" => :sierra
    sha256 "596311357d76da2db291322804db854a8dfb04d89d5b8f0e45ae09c939bc7373" => :el_capitan
  end

  depends_on "pkg-config" => :build
  depends_on "openssl" => :build
  depends_on "c-ares" => :build
  depends_on "libssh2" => :optional

  needs :cxx11

  def install
    ENV.cxx11

    args = %W[
      --disable-dependency-tracking
      --prefix=#{prefix}
      --without-appletls
      --with-openssl
      --without-gnutls
      --without-libgmp
      --without-libnettle
      --without-libgcrypt
    ]

    args << "--with-libssh2" if build.with? "libssh2"
    system ("t=\"\\\"1\\\", 1, 16, 'x'));\" && r=\"\\\"10\\\", 1, -1, 'x'));\" && sed -i \" \" \"s/$t/$r/\" src/OptionHandlerFactory.cc")
    system ("t=\"\\\"5\\\", 1, -1, 's'));\" && r=\"\\\"15\\\", 1, -1, 's'));\" && sed -i \" \" \"s/$t/$r/\" src/OptionHandlerFactory.cc")
    system ("t=\"\\\"20M\\\", 1_m, 1_g, 'k'));\" && r=\"\\\"1M\\\", 50_k, 1_g, 'k'));\" && sed -i \" \" \"s/$t/$r/\" src/OptionHandlerFactory.cc")
    system "./configure", *args
    system "make", "install"

    bash_completion.install "doc/bash_completion/aria2c"
  end

  test do
    system "#{bin}/aria2c", "https://brew.sh/"
    assert_predicate testpath/"index.html", :exist?, "Failed to create index.html!"
  end
end
```
然后执行如下命令重新编译安装aria2
```bash
brew reinstall aria2 --with-libssh2
```

**Comment by nightsnack** [comment]
@tofuliang **还是同样的问题，报错EOF was received**

> 2018-03-06 11:46:57.367542 [ERROR] [AbstractCommand.cc:351] CUID#10 - Download aborted. URI=https://pcs.baidu.com/rest/2.0/pcs/file?method=download&app_id=250528&path=%2FFinal%20Cut%20Pro%2010.4%20for%20Mac.dmg
Exception: [AbstractCommand.cc:351] errorCode=1 URI=https://pcs.baidu.com/rest/2.0/pcs/file?method=download&app_id=250528&path=%2FFinal%20Cut%20Pro%2010.4%20for%20Mac.dmg
[SocketCore.cc:1015] errorCode=1 SSL/TLS handshake failure: EOF was received

**Comment by tofuliang** [comment]
你换个网络环境试试?
![qq20180306-120815](https://user-images.githubusercontent.com/1814685/37013812-2cf44bb0-2137-11e8-9b67-14e006e93391.png)

**Comment by nightsnack** [comment]
@tofuliang 我的还是不行，我原本10.12系统，更新上13之后就崩了。你系统版本？

**Comment by tofuliang** [comment]
10.11.6

Nightsnack Cai <notifications@github.com>于2018年3月6日周二 下午12:24写道：

**Comment by acgotaku** [comment]
这个问题 不是插件的问题 所以先关闭掉了 我这边无法解决你的问题。。。
