### ISSUE TITLE
有关MD5检查功能

### ISSUE THREAD

**Issue by zelda0079** [acgotaku/BaiduExporter#572]
百度云有一个特性是上传一个没有秒传的文件, 好像会记录了一个与文件本身MD5不同的MD5(我也不太理解), 之后好像要再用同一个文件秒传一次, 那么第2个文件才是正确的MD5(第1个仍然是错误的)
以上情况是大文件才会有, 小文件没事

所以, 如果开了MD5检查功能, 去下载一个之前没有秒传上传的大文件, 百度云本身记录错误的MD5, 之后再用MD5检查功能在下载100%后会出现交叉, 但是关掉MD5检查功能下载会没问题, 打勾的

希望有发生这问题的用家可以看一下这边

**Comment by acgotaku** [comment]
所以这个 MD5功能是个 附加选项  就是因为这种情况啊

**Comment by acgotaku** [comment]
issue不是 BBS。。。 大家也没几个能看到的 ==
