### ISSUE TITLE
插件安装成功，测试显示ARIA2版本号，就是下载错误

### ISSUE THREAD

**Issue by pinoyo** [acgotaku/BaiduExporter#574]
![default](https://user-images.githubusercontent.com/37075925/37035540-d983e656-2187-11e8-814e-7452e0133958.jpg)
![default](https://user-images.githubusercontent.com/37075925/37035547-dc7c65b8-2187-11e8-8792-e003a9b27c2d.jpg)
控制台中上面一个115下载没有问题！！！下面一个百度出错

[插件版本号1.0.2，浏览器版本号chrome64.0.3282.186，系统版本win10，ARIA2版本号1.23。用了“雪大”几年的115插件。百度搜了好多帖子，实在没辙了，最近115下载不给力。跟我百度不是超级会员有关系吗？](
@acgotaku

**Comment by pinoyo** [comment]
今天继续尝试，补充一下，115和百度我都是路由脱机下载。今天下载了ARIA2直接在电脑后台运行，用雪大的插件，百度成功了。难道路由不能同时使用115和百度插件aria下载？

**Comment by acgotaku** [comment]
我觉得 这应该是你配置的问题吧。。。

**Comment by acgotaku** [comment]
你可以试试其他 资源 如果所有资源都有问题的话 我再看看

**Comment by pinoyo** [comment]
谢谢您的回复，我已经找到原因，确实是配置的问题，非常感谢雪神的热心与技术

在 2018-03-25 21:33:00，"雪月秋水" <notifications@github.com> 写道：


我觉得 这应该是你配置的问题吧。。。

**Comment by eason0108** [comment]
插件版本最新的不是16年的0.85 吗 ，哪里来的1.0.2 ？  我用0.85，在百度网盘页面上没有出现导出下载的按钮

**Comment by acgotaku** [comment]
@eason0108 自己不看看 最新的源代码？？ 就知道当伸手党？？？
