### ISSUE TITLE
已加check-certificate=false，一次性导出文件较多（如10个左右），会出错

### ISSUE THREAD

**Issue by itrustmchow** [acgotaku/BaiduExporter#576]
版本信息：
Aria2 1.15.1
BaiduExporter：1.0.2

下载网站80音乐网：http://www.pt80.net/
下载链接：https://pan.baidu.com/s/1i5ZmIkH 密码：0jcz

问题可重现

点击链接，输入提取码，进入网盘，点击”导出aria2“，在未登录个人百度网盘帐号的前提下导出。

导出的目录文件数量大概在10个左右，导出成功，各个文件大概下载10%左右（不规律，有些进度长，有些短），即出错，点击出错提示链接，显示一行字：{“error_code":31326,"error_msg":"anti hotlinking,hitcode:109","request_id":XXXXXXXXX}，下载文件较少时，如3-4左右，一般没有问题。

aria2.conf之前已经加了：check-certificate=false

麻烦帮我看一下是什么问题，感谢。

**Comment by itrustmchow** [comment]
我再补充一下信息，可能不是因为文件太多，而是文件太大，刚刚我下载一个压缩包，1.7G，也出现了以上的提示，烦请帮忙看一下，谢谢。

**Comment by itrustmchow** [comment]
把在Yaaw里面看到的提示错误链接也发出来：https://d.pcs.baidu.com/file/2d2a828a01892f53d48569dda0e3b2ef?fid=606624104-250528-976840420856672&time=1520566484&rt=sh&sign=FDTAERVY-DCb740ccc5511e5e8fedcff06b081203-C6gtLAx6hjl0phM31RZ8kY%2BAlpM%3D&expires=8h&chkv=1&chkbd=0&chkpc=et&dp-logid=1565108624212430947&dp-callid=0&r=803860465

**Comment by acgotaku** [comment]
下载失败是常有的事情  再导出一次 继续断点下载就是了

**Comment by itrustmchow** [comment]
好的，谢谢你
