### ISSUE TITLE
请问现在有没有除了保存到自己的云盘后再导出IDM下载链接的方法？

### ISSUE THREAD

**Issue by Yuki-Chen** [acgotaku/BaiduExporter#577]
1. 您下载的内容地址

    https://pan.baidu.com/share/link?shareid=31231&uk=2117063023&errno=0&errmsg=Auth%20Login%20Sucess&&bduss=&ssnerror=0&traceid=#list/path=%2F

2. 插件版本号，浏览器版本号，系统版本号

    插件版本号1.0.2，浏览器版本号chrome64.0.3282.186，系统版本win 8.1

3. 列举出现问题的详细步骤 

    最近不保存到自己的网盘就导不出IDM的下载链接 但是怕被封号 请问有没有什么好的方法或建议 我只知道分享链接再导出这一个方法 但是不知道靠不靠谱

4. 描述能否复现问题

**Comment by acgotaku** [comment]
确实有这个问题发生  我最近修复一下 估计是分享页面API换掉了

**Comment by acgotaku** [comment]
这个文件你点击 普通的下载按钮 会出错 没有下载权限。。。
所以这不是我扩展的问题 是本来不转存就没法下载。。。

**Comment by Yuki-Chen** [comment]
@acgotaku 的确如大大您所说 那转存到自己的网盘之后再导出会有风险吗？还有怎么做来降低风险呢？

**Comment by acgotaku** [comment]
啥风险？ 你只是下载东西为啥会被封号。。。

**Comment by Yuki-Chen** [comment]
@acgotaku 没有风险那就最好了 谢谢
