### ISSUE TITLE
IDM 下载顯示403

### ISSUE THREAD

**Issue by alfredmeow** [acgotaku/BaiduExporter#578]
请确保以下几点：

1. 已经阅读过README
2. 尝试安装最新版本插件
3. 尝试清空浏览器缓存
4. 尝试卸载插件后重新安装

发起 Issue 时，请提供：

1. 您下载的内容地址
https://d.pcs.baidu.com/file/9fea6245262385cdc95271feac19635f?fid=2184054296-250528-277319267371373&time=1520783861&rt=sh&sign=FDTAERVY-DCb740ccc5511e5e8fedcff06b081203-Ru0TCg0pckwaZdaiEeAnb04AzlY%3D&expires=8h&chkv=1&chkbd=0&chkpc=et&dp-logid=1623460320877525142&dp-callid=0&r=232265334
2. 插件版本号，浏览器版本号，系统版本号
插件版本号1.0.2，浏览器版本号chrome 64.0.3282.186 ，系统版本win 10
3. 列举出现问题的详细步骤
拷贝下载链接及在IDM输入後顯示403,但下载地址可以用Chrome下....
IDM URL顯示 http://www.baidupcs.com/403.html 而不是下载地址及文件
4. 描述能否复现问题

**Comment by acgotaku** [comment]
你应该分享下 自己下载的资源的分享地址 源地址没有意义。。。
如果没有cookies 也是无法下载的

**Comment by alfredmeow** [comment]
不知為何今天再試一試後, 又能用idm下載, 可能是那段時間下載太多...... 抱歉打擾了
算是bug嗎
