### ISSUE TITLE
旧版本遗留的localStorage导致0.3.7不能加载。

### ISSUE THREAD

**Issue by Nelson-Law** [acgotaku/BaiduExporter#58]
估计受影响代码：
var rpc_list=JSON.parse(localStorage.getItem("rpc_list")||'[{"name":"ARIA2 RPC","url":"http://localhost:6800/jsonrpc"}]')

临时解决办法：清空pan.baidu.com的localStorage

**Comment by acgotaku** [comment]
@Nelson-Law 已经更新了 你看看～

**Comment by Nelson-Law** [comment]
没问题了。
