### ISSUE TITLE
插件无法使用，目测在获得地址过程中出现问题

### ISSUE THREAD

**Issue by louislou123** [acgotaku/BaiduExporter#580]
您好，我一直在用您的插件，但是今天不能用了。在网盘里的所有东西在点击‘导出下载’后会显示
‘正在获取下载地址’，随后就什么也不发生了。目测是获取地址过程中出现问题，因此没有下载内容地址。
我在网上找到另一个插件，http://www.zdfans.com/7088.html，中的描述说
‘2018/03/22今天凌晨度盘服务器上改了css样式和js文件,目前所有脚本全挂！’是否是这个问题的原因呢？如果是百度方面的修改，能否问下这个问题是否有望修复？
我一直在用您的插件，对我帮助非常大。很感谢您开发这样的插件，谢谢您！
另，本人重新安装了插件问题没有解决，因此插件，浏览器与系统都是最新的。

请确保以下几点：

1. 已经阅读过README
2. 尝试安装最新版本插件
3. 尝试清空浏览器缓存
4. 尝试卸载插件后重新安装

发起 Issue 时，请提供：

1. 您下载的内容地址
2. 插件版本号，浏览器版本号，系统版本号
3. 列举出现问题的详细步骤
4. 描述能否复现问题

----------

**不符合上述条件的Issue将被无理由关闭**

**Comment by CaiPeterCai** [comment]
对的，打开Consoel可以看到发生以下错误
home.js:1 Uncaught TypeError: Cannot read property 'split' of null
    at t.value (home.js:1)
    at t.value (home.js:1)
    at t.value (home.js:1)
    at t.value (home.js:1)
    at home.js:1
value @ home.js:1
value @ home.js:1
value @ home.js:1
value @ home.js:1
(anonymous) @ home.js:1
postMessage (async)
(anonymous) @ baidu.js:1
postMessage (async)
value @ home.js:1
(anonymous) @ home.js:1

**Comment by CaiPeterCai** [comment]
可以从这里获得灵感，自己先改一下
https://greasyfork.org/zh-CN/scripts/39776-%E7%99%BE%E5%BA%A6%E7%BD%91%E7%9B%98%E9%AB%98%E9%80%9F%E4%B8%8B%E8%BD%BD%E5%8A%A9%E6%89%8B

**Comment by markx** [comment]
似乎是URL里面hash有了改动，更新一下parse的方法就好了。

**Comment by acgotaku** [comment]
貌似我的版本还是没有更新？ 你们可以载入开发版看看出错位置

**Comment by CaiPeterCai** [comment]
或者release里面/BaiduExporter/chrome/release/js/home.js
var t=window.location.hash.substr(1)
改成
var t=window.location.hash.substr(6)

**Comment by dantmnf** [comment]
```patch
diff --git a/chrome/src/js/home.js b/chrome/src/js/home.js
index 2ddbc17..39c7cd5 100644
--- a/chrome/src/js/home.js
+++ b/chrome/src/js/home.js
@@ -77,7 +77,7 @@ class Home extends Downloader {
     window.postMessage({ type: 'getSelected' }, location.origin)
   }
   getPrefixLength () {
-    const path = Core.getHashParameter('list/path') || Core.getHashParameter('path')
+    const path = Core.getHashParameter('list/path') || Core.getHashParameter('path') || Core.getHashParameter('/all?path')
     const fold = Core.getConfigData('fold')
     if (fold === -1 || path === '/') {
       return 1
```

**Comment by eckl** [comment]
作者你好，请问能捎带把firefox的扩展也更新一下吗？

**Comment by acgotaku** [comment]
已经修复

**Comment by CaiPeterCai** [comment]
@acgotaku 还有一个老问题，云盘内搜索出来的文件没法获取地址

**Comment by acgotaku** [comment]
@CaiPeterCai 这个功能不打算做。。。 搜到再去找那个文件就是了。。
我又不是做商业商品的 保证核心功能才是重点
