### ISSUE TITLE
Mac 下很方便的安装使用步骤（非问题）！

### ISSUE THREAD

**Issue by hscspring** [acgotaku/BaiduExporter#581]
1. 下载 GitHub 上[插件！安装到浏览器](https://minhaskamal.github.io/DownGit/#/home?url=https://github.com/acgotaku/BaiduExporter/blob/master/BaiduExporter.crx)。我发现 release 里的版本和 chrome 商店里的都不能用（版本太老了）。

2. 安装：`https://github.com/yangshun1029/aria2gui，release` 里直接[下载](https://github.com/yangshun1029/aria2gui/releases)，解压后拖入 应用程序 后打开。  

3. 登陆百度盘选中文件，点 ![image](https://user-images.githubusercontent.com/7485553/37866556-274da9a6-2fc7-11e8-9577-72c52e86311b.png)，`导出下载-ARIA2 RPC` 就开始下载了。

建议：  
- 提 Issue 前看下作者的提醒，希望作者能有更多时间做出更好的东东：）~~~
- 不要网上乱看教程，以官方介绍为准

以上。

---

请确保以下几点（**仔细看**）：

1. 已经阅读过README
2. **尝试安装最新版本插件**
3. 尝试清空浏览器缓存
4. 尝试卸载插件后重新安装

发起 Issue 时，请提供：

1. 您下载的内容地址
2. 插件版本号，浏览器版本号，系统版本号
3. 列举出现问题的详细步骤
4. 描述能否复现问题

----------

**不符合上述条件的Issue将被无理由关闭**

**Comment by three1bro** [comment]
我也是使用的这种操作，可是在导出到rpc后提示获取下载地址后就什么反应都没有了

**Comment by acgotaku** [comment]
你写的这个步骤也太粗糙了吧。。。

**Comment by three1bro** [comment]
是这样，我在导出的的设置里测试发现可以出现版本号，那么命令行下的aria2也许要配置吗，还是只要确定aria2gui的rpcpath和设置里的一样呢

**Comment by sarkdavidson** [comment]
#### 以下仅适用于 Mac 平台 
没有 SVIP 的看过来啦
- [发布于远景的 `aria2c` + `BaiduExporter` 使用教程](http://bbs.pcbeta.com/viewthread-1777922-1-1.html)
- [ aria2c 128 进程版本并搭配 `BaiduExporter` 使用教程 ](https://github.com/sarkdavidson/aria2c-macOS-128-threads)

**Comment by hscspring** [comment]
@three1bro 不需要的，安装了 gui 版本，插件会自动获取到 gui 里面。  
@acgotaku 不好意思……可能每个人的环境不一样，我确实只做了这两步就安好了。
