### ISSUE TITLE
插件是否可以进行配置？

### ISSUE THREAD

**Issue by ForeverOpp** [acgotaku/BaiduExporter#582]
如图，选项是灰色的。
如果不能对插件进行设置，是否就需要对Aria 2或者Web进行设置？
![image](https://user-images.githubusercontent.com/9302540/38040460-27219af0-32e2-11e8-951b-9fa764d24ff0.png)

1.在github下载的插件
2.插件版本号最新，浏览器版本 65.0.3325.181（正式版本） （64 位），系统版本号macOS 10.13.3
3.没有步骤

**Comment by acgotaku** [comment]
在百度网盘页面可以配置！

**Comment by ForeverOpp** [comment]
感谢！
