### ISSUE TITLE
這幾天的速度回到30-70 kb/s 了

### ISSUE THREAD

**Issue by kelvinsiuzzz** [acgotaku/BaiduExporter#583]
请确保以下几点：

1. 已经阅读过README
2. 尝试安装最新版本插件
3. 尝试清空浏览器缓存
4. 尝试卸载插件后重新安装

发起 Issue 时，请提供：

1. 您下载的内容地址: https://www.gdaily.org/
2. 插件版本号，浏览器版本号，系统版本号: Aria2-EZ V1.1.1, Chrome 65.0.3325.181 (正式版本) (64 位元)
3. 列举出现问题的详细步骤: 這幾天的速度回到30-70 kb/s 了
4. 描述能否复现问题

----------

**不符合上述条件的Issue将被无理由关闭**

**Comment by acgotaku** [comment]
https://www.gdaily.org/   这个不是百度网盘吧？？？
