### ISSUE TITLE
百度的新大招导致插件无效了

### ISSUE THREAD

**Issue by zlf179** [acgotaku/BaiduExporter#584]
插件版本1.0.2   Cent浏览器 Chromium 64.0.3282.140 系统版本 win10 1803
由于最近百度搞得防盗链机制导致插件无效了 具体表现是在aria web端界面 任务创建完成之后直接报错 提示如下错误

![tim 20180406154651](https://user-images.githubusercontent.com/26280126/38424565-c0e45ac6-39b1-11e8-9f85-9d5dbb94c9fd.png)

**Comment by nok1126** [comment]
暴死+1 跳的是error400 bad request

**Comment by yaosysu** [comment]
同样的情况
插件版本1.0.2；MacOS Sierra 10.12.5; Chrome Version 65.0.3325.162 (Official Build) (64-bit)；Aria 2 GUI2 V1.4.1 
在导出下载选择时候需要再次输入一个验证码，输完后一直显示“下载失败，请确认是否打开了Aria2"

**Comment by fengluoye** [comment]
我的怎么可以用了呢。。。

**Comment by acgotaku** [comment]
我这边也是可以使用 你确定 不是自己配置问题？ 

check-certificate=false

这个参数有没有？ 

https://github.com/acgotaku/BaiduExporter/blob/master/aria2c/aria2.conf#L53

**Comment by zlf179** [comment]
@acgotaku  我的check-certificate=false是写的true，难道改成false就行了？

**Comment by zlf179** [comment]
@acgotaku 我试了一下 改成false就不报错了，以前我装了cacertificate和cabundle加上check-certificate=true是不会出现这个错误的。就是百度更新了防盗链才出现的。

**Comment by acgotaku** [comment]
@zlf179 这个是自己系统的证书问题。。。 百度更新了 我也没办法解决啊。。。

**Comment by acgotaku** [comment]
@zlf179 https://aria2.github.io/manual/en/html/aria2c.html#cmdoption-ca-certificate
