### ISSUE TITLE
又出现HTTP请求头错误

### ISSUE THREAD

**Issue by zlf179** [acgotaku/BaiduExporter#585]
插件版本1.0.2 Cent浏览器 Chromium 64.0.3282.140 系统版本 win10 1803
由于最近百度搞得防盗链机制导致插件无效了 具体表现是在aria web端界面 任务创建完成之后直接报错 提示如下错误
![image](https://user-images.githubusercontent.com/26280126/38766687-b658016e-3fd5-11e8-9c67-f963e4263afd.png)
参考Issue里的添加BDUSS和STOKEN在Header的方法 无效

**Comment by acgotaku** [comment]
???  

https://github.com/acgotaku/BaiduExporter/blob/master/aria2c/aria2.conf#L53

你确定不是没加这个参数的问题？

**Comment by zlf179** [comment]
看来是路由器好像每次重启 重置了这个false的选项导致的

**Comment by zlf179** [comment]
@acgotaku 但是加了这个参数 在aria web端界面显示check-certificate为否 还是不能下载啊

**Comment by sangyue174** [comment]
我也是同样的错误，这个和度娘的更新有关系？

**Comment by acgotaku** [comment]
@zlf179 可以分享下这个文件? 或者把详细的日志贴出来？

**Comment by zlf179** [comment]
@acgotaku https://pan.baidu.com/s/1HTbxednAq1qSieZj-lpsGw  找了一个

**Comment by lidaof** [comment]
can reproduce same error:
```
 *** Download Progress Summary as of Mon Apr 23 21:02:42 2018 ***              
===============================================================================
[#00e11f 0B/0B CN:1 DL:0B]
FILE: ./downloads/The.Good.Fight.S02E06.INTERNAL.720p.WEB.H264-DEFLATE.mkv
-------------------------------------------------------------------------------

[#00e11f 0B/0B CN:1 DL:0B]                                                     
04/23 21:02:43 [ERROR] CUID#11 - Download aborted. URI=https://d.pcs.baidu.com/file/a27ad8adff45fb9dd6918e756011c60f?fid=1312071949-250528-394805730513224&dstime=1524535361&rt=sh&sign=FDtAERV-DCb740ccc5511e5e8fedcff06b081203-gGyqP78m%2B%2BZF%2FctVVTWO9UAltkc%3D&expires=8h&chkv=1&chkbd=0&chkpc=&dp-logid=2630496086762363665&dp-callid=0&r=591615375
Exception: [../../../src/AbstractCommand.cc:351] errorCode=22 URI=https://d.pcs.baidu.com/file/a27ad8adff45fb9dd6918e756011c60f?fid=1312071949-250528-394805730513224&dstime=1524535361&rt=sh&sign=FDtAERV-DCb740ccc5511e5e8fedcff06b081203-gGyqP78m%2B%2BZF%2FctVVTWO9UAltkc%3D&expires=8h&chkv=1&chkbd=0&chkpc=&dp-logid=2630496086762363665&dp-callid=0&r=591615375
  -> [../../../src/HttpSkipResponseCommand.cc:239] errorCode=22 The response status is not successful. status=403

04/23 21:02:43 [NOTICE] Download GID#00e11fe37b6c634e not complete: ./downloads/The.Good.Fight.S02E06.INTERNAL.720p.WEB.H264-DEFLATE.mkv
```

**Comment by yorks** [comment]
![403.png](https://i.loli.net/2018/04/24/5adf157e10dcb.png)

我估计没救，因为本身在浏览器里面点击下载 返回是 403。

**Comment by zlf179** [comment]
@yorks 我感觉是获取的链接问题 因为我用ex获取的链接 直接丢aria下 是满速的

**Comment by zlf179** [comment]
是不是凉了 这个软件(⊙︿⊙)

**Comment by acgotaku** [comment]
@zlf179 你没发现默认页面里面 的下载链接都不可以下载么？ 应该是这个资源的问题

**Comment by zlf179** [comment]
@acgotaku 默认页面里的下载链接是指啥？ 但是我试过好几个不同的资源 全是这个错误 总不能是说所有资源都有问题吧

**Comment by acgotaku** [comment]
yorks说了 本身就是403.。。 就是点击右边的下载

**Comment by zlf179** [comment]
@acgotaku  那意思就是 软件凉了吧

**Comment by acgotaku** [comment]
我一直用的好好的 可能你帐号凉了吧  @zlf179

**Comment by zlf179** [comment]
@acgotaku  那就非常有意思了 我用度盘下载器一样能下载啊 没有报错

**Comment by acgotaku** [comment]
@zlf179 那你就继续用就是了 度盘下载器不是开源的 我也没法比较和分析原因

**Comment by zlf179** [comment]
@acgotaku  但是我想用这个软件是因为我想挂载路由器上下载 方便 用度盘下载器麻烦一些

**Comment by acgotaku** [comment]
@zlf179 目前没有什么有价值的信息可以解决这个问题 我也无能为力

**Comment by gohergo** [comment]
遇到一模一样的问题，http请求头错误或无效，如果在文本导出里面拷贝下载链接，然后直接粘贴转到，返回信息是：
{"error_code":31326,"error_msg":"user is not authorized, hitcode:119","error_info":"","request_id":6890384844839689200}
用户没有被授权，是帐号的问题？如果得到的链接和帐号有关，岂不是会导致帐号被封？

**Comment by sym233** [comment]
> 遇到一模一样的问题，http请求头错误或无效，如果在文本导出里面拷贝下载链接，然后直接粘贴转到，返回信息是：
> {"error_code":31326,"error_msg":"user is not authorized, hitcode:119","error_info":"","request_id":6890384844839689200}
> 用户没有被授权，是帐号的问题？如果得到的链接和帐号有关，岂不是会导致帐号被封？

我也遇到了这个问题，复制地址到浏览器显示这个。
换了几个文件试，有的可以用，有的提示这个。
难道是因为h的原因，但是加密压缩包应该不会挂吧
