### ISSUE TITLE
同样用的是aria2，为何pandownload的速度快这么多？

### ISSUE THREAD

**Issue by terryxuwen** [acgotaku/BaiduExporter#587]
用的是最新版的chrom以及插件（开发模式安装的那个最新版本），aria2使用破解了99线程的版本
平时下载速度一般就是1-2m之间，即使设置了很高的连接数，下载时显示的连接数也就十多左右，不稳定。
今天试用了一下前段时间比较火的pandownload，发现它用的其实也是aria2，但是同一台电脑上，居然速度能达到9m！连接数设置了32后，下载时连接就一直是32....
为虾米，为虾米？

**Comment by zlf179** [comment]
这也是我也想问的问题。
另外百度服务器只会给16个线程，这是服务器定死的

**Comment by CR2025** [comment]
线程太高也会被ban的少年，另外aria默认参数不适用于度盘下载，请仔细了解各项参数含义后针对自己的网络情况设置，AriaNg的设置中附有全部参数的翻译与说明

**Comment by terryxuwen** [comment]
用了pandownload一段时间，下载了几十个g后，速度开始降下来了，看来是百度发现了，呵呵，果然天下没有免费的午餐啊

**Comment by acgotaku** [comment]
那个是闭源的 你这么说 我也不知道啊 我又不是万能的。。。

**Comment by Haruhi-Suzumiya** [comment]
大家心目中A大从Coding到女装无所不能吧（大概

**Comment by sherlocknieh** [comment]
因为原版的 Aria2 最大线程数是16，而 PanDownload 用的是自己魔改的超高线程版，所以下载速度快
