### ISSUE TITLE
無法導出下載

### ISSUE THREAD

**Issue by laichiaheng** [acgotaku/BaiduExporter#588]
请确保以下几点：

1. 已经阅读过README
`是`
2. 尝试安装最新版本插件
`是`
3. 尝试清空浏览器缓存
`是`
4. 尝试卸载插件后重新安装
`是
`
发起 Issue 时，请提供：

1. 您下载的内容地址
`https://pan.baidu.com/s/1BqFDkwOpDZyl4mSgcG7NxA`
2. 插件版本号，浏览器版本号，系统版本号
```
1.0.2.2
Firefox 59.0.2
Linux User-PC 4.16.5-1-ARCH #1 SMP PREEMPT Thu Apr 26 16:53:40 UTC 2018 x86_64 GNU/Linux
```
3. 列举出现问题的详细步骤
`嘗試導出下載無反應，嘗試文本導出也無反應，過去這些都是沒問題的`
4. 描述能否复现问题
`是`

**Comment by acgotaku** [comment]
Chrome可以？

**Comment by laichiaheng** [comment]
@acgotaku 結果發現用 github 頁面下方的 Load Temporary Add-on 可以使用，但用安裝附加元件的方法就不行

**Comment by laichiaheng** [comment]
看來只能夠等 Firefox 這邊的 Add-on 更新了

**Comment by laichiaheng** [comment]
自從用了 Load Temporary Add-on 的方法後，剛剛測試安裝 Add-on 突然可以運作了，見鬼！

**Comment by laichiaheng** [comment]
如果不用 Load Temporary Add-on 的方法就無法在 Firefox 使用

**Comment by acgotaku** [comment]
如果不张嘴就无法吃饭
