### ISSUE TITLE
怎样保存百度云完整路径？

### ISSUE THREAD

**Issue by fengbrute** [acgotaku/BaiduExporter#589]
下载百度云文件夹嵌套很多时，希望能保存完成的文件夹路径。现在的情况是文件在一起，文件夹在一起。文件夹层数 已设置为-1

**Comment by acgotaku** [comment]
例如？ 举个例子？

**Comment by fengbrute** [comment]
多谢关注！比如百度云目录结构如下  /a/b/c/d/a.pdf /a/b/c/d/b.pdf /a/b/c/d/c.pdf 此时我下载a文件夹时a.pdf b.pdf c.pdf在文件在一起了，文件夹在_dll下面。要的效果是和百度云完全一样的结构 ![f09e1021e21377c3e5288d420d603835.png](http://nasx.top:90/images/2018/05/04/f09e1021e21377c3e5288d420d603835.png)

**Comment by KellyHwong** [comment]
Mark一下

**Comment by acgotaku** [comment]
@fengbrute 我测试了一下是没问题的啊 为啥会出来一个 DLL文件夹

你可以使用文本导出测试一下路径 然后贴出来 我看看

**Comment by KellyHwong** [comment]
我刚也试了一下，没问题，目录结构能保存完整，这是示意图：
![image](https://user-images.githubusercontent.com/5453534/39966960-9d71f51a-56e6-11e8-9100-dbc98b4100d8.png)
![image](https://user-images.githubusercontent.com/5453534/39966967-b0d1cefa-56e6-11e8-9ae3-3ff3c7b0e432.png)
这是百度云上的，百度云没有树状图就不弄了，反正目录结构是一样的。
当然deep1folderA位于百度云的根目录，所以下下来是一样的；待会儿试一试不在根目录里下载的情况，能不能读取上一级目录到下载配置（估计不行，以前这种情况导出都把你选择的目录当根目录，忽略了上级目录）

**Comment by KellyHwong** [comment]
aria2c -c -s10 -k1M -x16 --enable-rpc=false -o **"deep1folderA/file1.txt"** --header "User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36" --header "Referer: https://pan.baidu.com/disk/home" --header "Cookie: BDUSS=hqMW1YMHQ0VTFWVGRlZFh4ZzV0Wm1BbDQyUEc2T0ZGTEptMXowZS1ZYS1yeDliQUFBQUFBJCQAAAAAAAAAAAEAAAB10Kghb25seW15Zmxvd2VyAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAL4i-Fq-IvhaU1; pcsett=1526298744-fc4bf1a509af0996b5ac91ec7c64b5dd" "https://pcs.baidu.com/rest/2.0/pcs/file?method=download&app_id=250528&path=%2Fdeep1folderA%2Ffile1.txt"
aria2c -c -s10 -k1M -x16 --enable-rpc=false -o **"deep1folderA/deep2folderB/deep3folderA/file3.txt"** --header "User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36" --header "Referer: https://pan.baidu.com/disk/home" --header "Cookie: BDUSS=hqMW1YMHQ0VTFWVGRlZFh4ZzV0Wm1BbDQyUEc2T0ZGTEptMXowZS1ZYS1yeDliQUFBQUFBJCQAAAAAAAAAAAEAAAB10Kghb25seW15Zmxvd2VyAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAL4i-Fq-IvhaU1; pcsett=1526298744-fc4bf1a509af0996b5ac91ec7c64b5dd" "https://pcs.baidu.com/rest/2.0/pcs/file?method=download&app_id=250528&path=%2Fdeep1folderA%2Fdeep2folderB%2Fdeep3folderA%2Ffile3.txt"
aria2c -c -s10 -k1M -x16 --enable-rpc=false -o **"deep1folderA/deep2folderA/file2.txt"** --header "User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36" --header "Referer: https://pan.baidu.com/disk/home" --header "Cookie: BDUSS=hqMW1YMHQ0VTFWVGRlZFh4ZzV0Wm1BbDQyUEc2T0ZGTEptMXowZS1ZYS1yeDliQUFBQUFBJCQAAAAAAAAAAAEAAAB10Kghb25seW15Zmxvd2VyAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAL4i-Fq-IvhaU1; pcsett=1526298744-fc4bf1a509af0996b5ac91ec7c64b5dd" "https://pcs.baidu.com/rest/2.0/pcs/file?method=download&app_id=250528&path=%2Fdeep1folderA%2Fdeep2folderA%2Ffile2.txt"
这是用文本导出的输出
![image](https://user-images.githubusercontent.com/5453534/39967078-391ceb72-56e8-11e8-98e8-411a3ceb32d8.png)

其中-o参数就是文件保存到本地的路经（相对于你aria2c的Download 根目录，在aria2.conf中设置的，比如我的是dir=C:\Users\kellyhwong\Downloads）
如果你还是有问题，建议用这种方法测试一下。
另外，在非根目录获取完整目录的问题，我觉得可以新开个issue，说不定有人有这个需求，想保证云端和本地端目录的一致性@acgotokiu

**Comment by acgotaku** [comment]
非根目录 也可以获取完整目录啊 有啥需求？ @KellyHwong

**Comment by KellyHwong** [comment]
そうか、ありがとう

**Comment by GammaPi** [comment]
@fengbrute @acgotaku @KellyHwong 
我遇到了相同的问题，实际上原因是因为Issue主和我一样，用了：
https://hub.docker.com/r/xujinkai/aria2-with-webui/
这个docker,它里面有一个onComplete.sh脚本，会把文件夹中的文件全部拷贝出来666
将这个脚本注释掉问题就解决啦。

**Comment by Better-Shu** [comment]
@GammPi,
onComplete.sh，这个该怎么注释掉呢？
我也遇到和issue主同样的问题啊
