### ISSUE TITLE
在从百度盘下载文件时，提示“用户名和密码验证失败”，请帮忙确认一下原因

### ISSUE THREAD

**Issue by songjianxun** [acgotaku/BaiduExporter#59]
使用的配置文件如下：
root@OpenWrt:~# cat aria2.conf
dir=/mnt
file-allocation=trunc
continue=true
max-concurrent-downloads=1
max-connection-per-server=5
min-split-size=10M
split=5
disable-ipv6=true
input-file=/mnt/aria2.session
save-session=/mnt/aria2.session
enable-rpc=true
rpc-allow-origin-all=true
rpc-listen-all=true

没有配置用户名和密码，也没有使用token.
请帮忙看下是何原因，多谢!

**Comment by halfu** [comment]
file-allocation=trunc 有误，但不是这个原因

确定下有没有启用SSL

最后，启用debug 模式更容易找出原因。

**Comment by acgotaku** [comment]
@songjianxun  原因很简单 你下载的是非法资源 例如AV 被 替换成 8秒教育片啦  QAQ

**Comment by songjianxun** [comment]
@acgotaku，确实如你所说，是敏感资源。这样我也放心了，原来以为是工具出问题了呢，谢谢秋水^_^
