### ISSUE TITLE
早上8点后下载速度 10M/S 变1M/S

### ISSUE THREAD

**Issue by zuiyixifeng2006** [acgotaku/BaiduExporter#590]
发起 Issue 时，请提供：

1. 您下载的内容地址
aria2c -c -s10 -k1M -x16 --enable-rpc=false -o "cn_windows_10_business_editions_version_1803_updated_march_2018_x64_dvd_12063730.iso" --header "User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36" --header "Referer: https://pan.baidu.com/disk/home" --header "Cookie: pcsett=1525564607-c9e05ad91d860e5492bd2f41a2d47163" "https://d.pcs.baidu.com/file/7233b26208aff2444a60f21b09f5de3f?fid=3831464433-250528-1001509247267578&dstime=1525478210&rt=sh&sign=FDtAERVY-DCb740ccc5511e5e8fedcff06b081203-Ot%2Fuy4lQpUWNLeJZU%2F42yvVXyc0%3D&expires=8h&chkv=1&chkbd=0&chkpc=et&dp-logid=8648197531334981236&dp-callid=0&r=133253842"
2. 插件版本号，浏览器版本号，系统版本号
1.0.2(Commits on May 3, 2018)   Chrome66.0.3359.139  win7
3. 列举出现问题的详细步骤
疑问：大约过了早点上8点，下载速度变化剧烈。源端口按时间段限速么？
          很久前发现这个问题了，所以需要下载个别大文件，就刻意定到早上8点前 下载。

3.1 修改aria2 参数，命令行下载 
aria2c --dir=E:\Downloads --file-allocation=none -c -x5 -s10 -k1M -o "    （此处同上述1内容）

3.2 大约 7：55 后开始
一阶段 速度到带宽满值
![2](https://user-images.githubusercontent.com/16421078/39658062-8ce684b4-5041-11e8-8ab0-3028140a437d.JPG)

二阶段 变化时间约 08：04  速度〈1M
![3](https://user-images.githubusercontent.com/16421078/39658100-f0ff76a4-5041-11e8-8057-fa92964e23ff.JPG)

最后结束   08：36  
![4](https://user-images.githubusercontent.com/16421078/39658105-04de4ac4-5042-11e8-935d-01b31e9f2f7d.JPG)

**Comment by acgotaku** [comment]
速度原因不是本插件的 功能范围
