### ISSUE TITLE
baiduExporter能做一個edge的版本嗎

### ISSUE THREAD

**Issue by hanna518** [acgotaku/BaiduExporter#592]
下載在chrome試用，非常好用。感謝分享。
自己試著用Microsoft Edge Extension Convertor ToolKit移植到edge上不成功。大神有空的話能否幫忙做一個edge上用的。感謝。

**Comment by acgotaku** [comment]
有一个edge分支 你自己下载用啊

**Comment by acgotaku** [comment]
https://github.com/acgotaku/BaiduExporter/tree/edge
