### ISSUE TITLE
chrome的百度网盘助手插件无法启动

### ISSUE THREAD

**Issue by janusdai** [acgotaku/BaiduExporter#593]
![image](https://user-images.githubusercontent.com/13866037/40126450-efe318bc-595f-11e8-88c3-b70f16077c77.png)
已经选择了开发者模式，还是这样如何是好

**Comment by acgotaku** [comment]
那你可以使用 release文件夹 开发者模式载入

**Comment by im0qianqian** [comment]
新版本的 Chrome 已经禁止这样的形式添加扩展了，你可以解压到本地，然后从文件夹添加
