### ISSUE TITLE
关于执行ARIA配置中的on-download-complete

### ISSUE THREAD

**Issue by gu970214** [acgotaku/BaiduExporter#600]
你好，您开发的插件十分有用。但是在使用过程中我发现以下问题：
已经在ARIA2c的配置文件中添加了下载完成后执行某个sh文件，配合WEBUI使用时完美运行，但配合该插件使用时发现下载完成后不会执行该文件。请问作者有没有什么解决方法？或者是我本身设置上存在一些问题。
谢谢！

**Comment by acgotaku** [comment]
这应该明显是 aria2c的问题才对啊 我插件也没这么牛逼的功能啊

**Comment by gu970214** [comment]
那请问从webui导入下载文件和从你的插件导入下载文件，指令上有什么区别呢？

**Comment by LynAi** [comment]
百度现在不支持大文件的浏览器直接下载呀，他会直接跳客户端下载，所以要用这个插件来抓链接。小文件的话，确实可以不用这个插件，让aria直接拦截所有浏览器的下载就行了。

**Comment by LynAi** [comment]
> 那请问从webui导入下载文件和从你的插件导入下载文件，指令上有什么区别呢？

百度现在不支持大文件的浏览器直接下载呀，他会直接跳客户端下载，所以要用这个插件来抓链接。小文件的话，确实可以不用这个插件，让aria直接拦截所有浏览器的下载就行了。 @gu970214

**Comment by ODtian** [comment]
巧了 我这边可以 使用oneindex上传到OneDrive
