### ISSUE TITLE
网盘勾选文件后，上方没有出现导出下载按钮

### ISSUE THREAD

**Issue by rr4e** [acgotaku/BaiduExporter#601]
1. 您下载的内容地址https://github.com/acgotaku/BaiduExporter/archive/v0.8.5.zip
2. 插件版本号v0.8.5，浏览器版本号67.0.3396.87（正式版本） （64 位），系统版本号dediban9
3. 列举出现问题的详细步骤
安装插件后，打开百度云盘，勾选文件，上方没有出现导出下载按钮

**Comment by acgotaku** [comment]
最新版本都是1.02了。。。 能不能看看readme啊

**Comment by rr4e** [comment]
恩可以了...嘿嘿好羞愧呀...总之爱死你了

2018-06-17 22:16 GMT+08:00 雪月秋水 <notifications@github.com>:
