### ISSUE TITLE
谷歌浏览器选择要下载的文件后“导出下载”按钮消失了

### ISSUE THREAD

**Issue by liujieyuu** [acgotaku/BaiduExporter#602]
Google Chrome 已是最新版本
版本 67.0.3396.87（正式版本） （64 位）
Aria2 1.33.1
百度网盘加载完成后，提示“初始化完毕”，然后选中要下载的文件后“导出下载”按钮消失了，不能进行后续下载了。

**Comment by liujieyuu** [comment]
网盘助手版本号：0.8.5

**Comment by twinkle77** [comment]
同问。

**Comment by liujieyuu** [comment]
@twinkle77 我还以为是解决问题的呢，结果是同问😄

**Comment by liujieyuu** [comment]
找到个方案》（如果提示请先勾选需要下载的文件，勾选后导出下载按钮不见了的话；刷新浏览器，在页面尚未加载完时勾选文件或者文件夹，浏览器加载完以后，文件还会是勾选状态，而导出下载按钮不会消失，此时问题解决，可进行下一步)。但是这个方案太鸡肋了，不知道有没有 别的方案

**Comment by twinkle77** [comment]
进入谷歌控制台将网速限制为slow 3g网络，解决“多选”问题。
感谢 @liujieyuu

**Comment by acgotaku** [comment]
@liujieyuu https://github.com/acgotaku/BaiduExporter/blob/master/BaiduExporter.crx 
这不就是
