### ISSUE TITLE
下载过程中随机出现download was unsuccessful

### ISSUE THREAD

**Issue by Fengyao115** [acgotaku/BaiduExporter#603]
插件版本：1.0.2
Aria2版本：1.33.1
使用平台：群晖DS918+
问题描述：导入百度云任务后，下载过程中会出现下载失败的现象，提示download was unsuccessful，但是重启任务会继续下载，失败概率随机

**Comment by acgotaku** [comment]
这个问题早就 有了 但是原因一直未知 所以没法解决
猜测是百度云服务器主动拒绝连接

**Comment by sym233** [comment]
我现在也遇到了这个问题，
下载过程中会出现HTTP response header was bad or unexpected。
点重新下载会继续下载一段时间，大约是十几秒，然后又出现上述情况。
一只盯着下载点重启倒是能下完……
