### ISSUE TITLE
能把aria2c文件夹里面的conf文件更新下吗，rpc模式下载速度远低于导出文本模式速度

### ISSUE THREAD

**Issue by aiwonanjing** [acgotaku/BaiduExporter#604]
我下载的是百度云的资源，插件版本号1.2，Chrome 69.0.3464.0，win10 1709，如果直接rpc下载，单文件50kb/s，加一块也很可怜，文本导出模式，单文件能达到600kb/s（我不是会员很满足了），所以希望能把rpc部分修订下。

**Comment by acgotaku** [comment]
conf文件仅仅是个模板  想修改的话 自己下载随便修改啊。。。

**Comment by WeiZhou2372** [comment]
> 我下载的是百度云的资源，插件版本号1.2，Chrome 69.0.3464.0，win10 1709，如果直接rpc下载，单文件50kb/s，加一块也很可怜，文本导出模式，单文件能达到600kb/s（我不是会员很满足了），所以希望能把rpc部分修订下。

想知道相应的怎么修改conf, 目前刚开始使用这个插件, 都是直接rpc, 确实很慢, 还以为都是这样.

 文本导出的话, 我的aria2实际是在别的机器上运行的, 单纯只是复制下载链接的话会失败. 如果每次需要ssh进去操作还是很麻烦.

如果能够通过修改conf直接在webUI上操作完成的话那就太好了. 请不吝赐教

**Comment by acgotaku** [comment]
aria2c 的配置 我也没有详细研究过 默认的对我来说够用了 @WeiZhou2372
