### ISSUE TITLE
点击rpc下载后，先提示下载成功，2秒后提示下载失败

### ISSUE THREAD

**Issue by liangxyz** [acgotaku/BaiduExporter#605]
请确保以下几点：

1. 已经阅读过README
2. 尝试安装最新版本插件
3. 尝试清空浏览器缓存
4. 尝试卸载插件后重新安装

发起 Issue 时，请提供：

1. 您下载的内容地址
2. 插件版本号，浏览器版本号，系统版本号 
插件版本0.32  浏览器 百分浏览器 3.4.3.39  系统win10 1804
3. 列举出现问题的详细步骤
点击rpc下载，浏览器提示下载成功，2秒以后又提示下载失败
进入arica2的webui界面，发现下载成功
4. 描述能否复现问题
每次都可以复现
----------

**不符合上述条件的Issue将被无理由关闭**

**Comment by acgotaku** [comment]
不详细描述下么？ 所有文件都这样？

**Comment by liangxyz** [comment]
你好，我的115所有文件都这样。
具体就是点击rpc下载，然后弹出提示，下载成功，1秒以后，紧接着就弹出提示下载失败，是不是没有开启aria2c。
然后我打开webui，发现下载任务正常添加

**Comment by liangxyz** [comment]
抱歉，我没看见这是百度盘，我用的是115，不好意思

**Comment by acgotaku** [comment]
这里是 BaiduExporter。。。。
