### ISSUE TITLE
无法选中文件后导出下载

### ISSUE THREAD

**Issue by yichaosun** [acgotaku/BaiduExporter#606]
发起 Issue 时，请提供：

1. 您下载的内容地址
https://pan.baidu.com/s/1WpN4x5BGqpecKtnhKNC7MA
2. 插件版本号，浏览器版本号，系统版本号
插件：0.85
Chrome：版本 67.0.3396.99（正式版本） （64 位）
系统：MacOS 10.13.5 (17F77)
3. 列举出现问题的详细步骤
多次刷新，有时会显示初始化成功，但是看不到导出下载按钮
4. 描述能否复现问题
本人这边是重复的

**Comment by yichaosun** [comment]
网盘其他的分享内容，效果一样，没有生成导出下载按钮

**Comment by acgotaku** [comment]
https://github.com/acgotaku/BaiduExporter/blob/master/BaiduExporter.crx

请使用最新的1.02版本
