### ISSUE TITLE
更新了0.3.6版本以后，百度盘页面的设置还是0.1.0怎么办

### ISSUE THREAD

**Issue by kidd0331** [acgotaku/BaiduExporter#61]
![1](https://cloud.githubusercontent.com/assets/13634259/9051780/19d165ba-3a92-11e5-92a8-8253d5529d2f.png)
浏览器是7.5版本的360极速，卸载了老的0.3.0版本，清空了缓存，还是老版本
请问怎么办？

**Comment by acgotaku** [comment]
@kidd0331 你用chrome不就好了

**Comment by kidd0331** [comment]
![2](https://cloud.githubusercontent.com/assets/13634259/9051891/92b97b60-3a93-11e5-9332-8ce7b50baba0.png)

找到原因了，是这个插件的原因
不过禁用了以后，你的插件载入不了了……
chrome用起来不如这个顺手，是兼容问题？

**Comment by acgotaku** [comment]
@kidd0331 可能 360用的chrome版本太低 导致API不兼容? 

你 F12看看有没有报错

**Comment by kidd0331** [comment]
![3](https://cloud.githubusercontent.com/assets/13634259/9052180/05730e52-3a97-11e5-882b-87cde099570d.png)
目前7.5版的360内核是30.0.1599.101
F12有2个错误，看上去是因为网络不好的关系？

**Comment by acgotaku** [comment]
@kidd0331 扩展整个加载不出来? 你看看 Sources页面的 content script有没有扩展

**Comment by kidd0331** [comment]
![4](https://cloud.githubusercontent.com/assets/13634259/9052459/3e9fccbc-3a9a-11e5-8ef0-0579f6696177.png)
看不懂，只能整张截给你了

**Comment by acgotaku** [comment]
@kidd0331 这个显示是正常的

**Comment by acgotaku** [comment]
@kidd0331 你还是把 7.5版本的浏览器的下载链接给我算了...

**Comment by kidd0331** [comment]
7.5的官网似乎已经下不到了，我把自己用的安装文件传网盘把
http://pan.baidu.com/s/1kTkZAir

**Comment by acgotaku** [comment]
@kidd0331 260不支持 Promise方法 所以无法运行 建议还是更换浏览器 或升级到最新版

**Comment by kidd0331** [comment]
7.5后面的版本不好用，只能放弃了
谢谢acgotaku，辛苦了
