### ISSUE TITLE
错误,请查看是否开启Aria2

### ISSUE THREAD

**Issue by hsdchenliyang** [acgotaku/BaiduExporter#610]
一、内容无关
二、插件1.0.2   浏览器 Chromium 68.0.3440.75（正式版本）系统 Ubuntu 16.04 （64 位） aria2  1.19
三、点击“测试连接，成功显示版本号。返回“错误,请查看是否开启Aria2”。 百度云点击aria2 prc 提示下载失败 是不是没有开启aria2 
四、看了相同的issues 好像都不是相同的问题 我觉得可能是配置问题  问一下不太明白的问题（小白 别见怪哈）
1. 终端已经运行aria2c --conf-path=<PATH> 
2. aria2.conf 配置见下：
3、我用的是在线版     `https://ziahamza.github.io/webui-aria2/`   
请问百度云下载按钮的设置 以及 在线版网页的设置 各需要怎么设  （根据教程  在设置里面修改下RPC PATH为 http://localhost:6800/jsonrpc   ，我把localhost改成我自己的ip  在两个地方都设置了 也不行）

`#用户名
#rpc-user=user
#密码
#rpc-passwd=passwd
#设置加密的密钥
#rpc-secret=secret
#允许rpc
enable-rpc=true
#允许所有来源, web界面跨域权限需要
rpc-allow-origin-all=true
#是否启用https加密，启用之后要设置公钥,私钥的文件路径
#rpc-secure=true
#启用加密设置公钥
#rpc-certificate=/home/name/.config/aria2/example.crt
#启用加密设置私钥
#rpc-private-key=/home/name/.config/aria2/example.key
#允许外部访问，false的话只监听本地端口
rpc-listen-all=true
#RPC端口, 仅当默认端口被占用时修改
#rpc-listen-port=6800
#最大同时下载数(任务数), 路由建议值: 3
max-concurrent-downloads=5
#断点续传
continue=true
#同服务器连接数
max-connection-per-server=5
#最小文件分片大小, 下载线程数上限取决于能分出多少片, 对于小文件重要
min-split-size=10M
#单文件最大线程数, 路由建议值: 5
split=10
#下载速度限制
max-overall-download-limit=0
#单文件速度限制
max-download-limit=0
#上传速度限制
max-overall-upload-limit=0
#单文件速度限制
max-upload-limit=0
#断开速度过慢的连接
#lowest-speed-limit=0
#验证用，需要1.16.1之后的release版本
#referer=*
#文件保存路径, 默认为当前启动位置
dir=/home/leon/下载
#文件缓存, 使用内置的文件缓存, 如果你不相信Linux内核文件缓存和磁盘内置缓存时使用, 需要1.16及以上版本
#disk-cache=0
#另一种Linux文件缓存方式, 使用前确保您使用的内核支持此选项, 需要1.15及以上版本(?)
#enable-mmap=true
#文件预分配, 能有效降低文件碎片, 提高磁盘性能. 缺点是预分配时间较长
#所需时间 none < falloc ? trunc << prealloc, falloc和trunc需要文件系统和内核支持
file-allocation=prealloc
#不进行证书校验
check-certificate=false``

**Comment by acgotaku** [comment]
http://binux.github.io/yaaw/demo/

你用这个输入你的 RPC PATH试试 看看能不能正常显示 aria2c的版本号

**Comment by hsdchenliyang** [comment]
是百度云aria2 rpc 那一栏吗   试了还是提示 “错误 请查看是否开启aria2”

**Comment by Mr-win7** [comment]
> http://binux.github.io/yaaw/demo/
> 
> 你用这个输入你的 RPC PATH试试 看看能不能正常显示 aria2c的版本号

我遇到了类似的问题，提示我错误没开aria2，但是用这个web ui和其他的web ui用同样的rpc path 连接都可以正确显示，我换了wss https 都不行。也不知道怎么看报错。
插件1.0.2 chrome 68.0.3440.106 本机系统 Windows 10 1803 rpc 系统 Ubuntu 17.10
wss://token:(保密)@rpc服务器地址:443/jsonrpc
https://token:(保密)@rpc服务器地址:443/jsonrpc
均无法被识别
但是 http://localhost:6800/jsonrpc 可工作
以上rpc path均可在其他web ui界面工作
稳定复现

**Comment by Voleking** [comment]
same issue

**Comment by MycenaeanGreece** [comment]
> http://binux.github.io/yaaw/demo/
> 
> 你用这个输入你的 RPC PATH试试 看看能不能正常显示 aria2c的版本号

同样的问题，使用chrome浏览器无法正常使用。但是使用edge浏览器就可以

**Comment by Mr-win7** [comment]
> @Mr-win7 我并没有测试过 https 请确定你有合法的证书。 http的连接肯定是可以的

这两个路径在 aria2Ng 和 aria2 webui 还有 yaaw 里都可以正常工作。https 证书是 letsencrypt 签发的应该没有问题？我没用 aria2 本身的 ssl 鉴权，是用 nginx 把 https 请求代理成 http 处理的。aria2 本身还是工作在 http 的。

然后我刚刚尝试直接暴露了 aria2 的工作端口然后用 http 重试了，依然无法工作。直接用 http 的这个路径在其他的 web ui 里依然可以正常工作。

请问能不能查看日志呢？我用开发者工具看不到报错，插件本身好像也没信息提示。

会不会和 aria2 逐渐弃用地址形式的请求有关？但是地址在其他的 web ui 里还是能工作的。

**Comment by yunweiyuan** [comment]
http连接到局域网内rpc，得到“错误,请查看是否开启Aria2”。但Aria2 WebUI可以连接成功。

**Comment by Neulana** [comment]
遇到同样的问题，解决方案：去掉认证，即不要设置密码**和**token，就不会报错了，亲测

**Comment by Neulana** [comment]
遇到同样的问题，解决方案：去掉认证，即不要设置密码**和**token，就不会报错了，亲测

**Comment by xczh** [comment]
As of 1.18.4, in addition to HTTP basic authorization, aria2 provides RPC method-level authorization. In a future release, HTTP basic authorization will be removed and RPC method-level authorization will become mandatory.

[官方文档](https://aria2.github.io/manual/en/html/aria2c.html#rpc-authorization-secret-token)

官方已经说了，HTTP Basic认证方式在新版本里被移除，以后都使用method层面的认证。因此token:secret这种认证将不会被接受。作者更新新版可以解决这个问题。

**Comment by Mr-win7** [comment]
> As of 1.18.4, in addition to HTTP basic authorization, aria2 provides RPC method-level authorization. In a future release, HTTP basic authorization will be removed and RPC method-level authorization will become mandatory.
> 
> [官方文档](https://aria2.github.io/manual/en/html/aria2c.html#rpc-authorization-secret-token)
> 
> 官方已经说了，HTTP Basic认证方式在新版本里被移除，以后都使用method层面的认证。因此token:secret这种认证将不会被接受。作者更新新版可以解决这个问题。

原来是已经移除了。。我还以为只是desperated这种
@acgotaku 大佬能麻烦更新一下认证的逻辑么

**Comment by acgotaku** [comment]
我没必要更新认证逻辑，因为我要兼容老版本的 Aria2c。是你需要根据自己的版本 选择合适的认证方式而已！

**Comment by xinqiu** [comment]
> http连接到局域网内rpc，得到“错误,请查看是否开启Aria2”。但Aria2 WebUI可以连接成功。

同样问题，localhost可以创建下载任务，局域网另一台电脑使用rpc就不能创建下载任务，也是 “错误,请查看是否开启Aria2”，但Aria2 WebUI可以连接

**Comment by sevenwong** [comment]
> As of 1.18.4, in addition to HTTP basic authorization, aria2 provides RPC method-level authorization. In a future release, HTTP basic authorization will be removed and RPC method-level authorization will become mandatory.
> 
> [官方文档](https://aria2.github.io/manual/en/html/aria2c.html#rpc-authorization-secret-token)
> 
> 官方已经说了，HTTP Basic认证方式在新版本里被移除，以后都使用method层面的认证。因此token:secret这种认证将不会被接受。作者更新新版可以解决这个问题。

你理解反了，所谓method认真方式恰恰指的是token:secret，这种方式token会被添加到RPC的请求方法参数里面去，而HTTP Basic认证方式，指的是rpc-user rpc-passwd 这种方式，这种方式将来会被删除，token方式将被强制使用。
