### ISSUE TITLE
IDM下载几乎没速度

### ISSUE THREAD

**Issue by ninosweet** [acgotaku/BaiduExporter#611]
昨天想下载300mb+的视频，结果IDM和aria2c下载大文件突然没有速度了，小文件还是正常。之前都是接近满速，这几天开始最高也只有50+KB。
插件/浏览器(火狐)用的都是最新版本，aria2c是1.33.1。

**Comment by acgotaku** [comment]
主要是我IDM试用到期了。。。 不太好测试。。。

**Comment by hy345** [comment]
对最近很多下载器都GG了 原来都很快的 现在都一个连接只能5kbps了……

**Comment by acgotaku** [comment]
下载速度这个问题 说了 很多遍了  只能自己充钱解决
