### ISSUE TITLE
百度网盘线程限制问题，建议增加延迟推送功能

### ISSUE THREAD

**Issue by carloswear** [acgotaku/BaiduExporter#612]
下载的内容地址：https://pan.baidu.com/s/1x_w2FD7jT50S6KMcyFycHA
插件版本号，浏览器版本号，系统版本号：Version: 1.0.2 + Chrome 67.0.3396.99 (Official Build) (64-bit) + Linux OSMC 4.14.34-4
列举出现问题的详细步骤
1，推送整个文件夹的资源到aria2c下载，除去最开始的2-3个文件之外，其他的文件连接数会从16迅速下降到1，猜测是因为同时推送过多任务，百度会强制断开进程
2，我目前的解决办法如下
A，文件少的话一个一个推送，线程数没有被强制断开，均为8-14左右，速度正常
B，批量推送之后，针对连接数为1的资源使用使用YAAW重启任务，速度正常

猜测是请求的速度过快，能否加入延迟功能？

----------

**不符合上述条件的Issue将被无理由关闭**

**Comment by carloswear** [comment]
已通过强制增加线程数解决该问题，打扰了。

**Comment by zhangsmallchi** [comment]
请问您是如何强制增加的呢 我每个任务的线程数一直只有1或者2 实在少得可怜 总速度不会超过400kb

**Comment by zhangsmallchi** [comment]
感谢你的帮助 我在配置文件中提高线程数到16 已经有所改善 并且申请到线程数应该只是10而已 这是百度的限制吧

**Comment by carloswear** [comment]
我重新编译刚刚使用的时候，测试同时下载3个文件，线程数128每个。结果是线程一路掉，最后是30线程没文件。最近直接降到了10个线程每个文件。相比之前速度有些提升~目前是最大45线程，单线程15，有时候掉，有时候不掉~
另外把文件分享出去然后在推送，速度似乎会快些。你可以试试 @zhangsmallchi
