### ISSUE TITLE
插件设置里面的VIP选项

### ISSUE THREAD

**Issue by superamd** [acgotaku/BaiduExporter#616]
本人是百度会员,为什么插件设置里面的VIP选项会没有的?我记得以前是有的...

**Comment by superamd** [comment]
是需要满足什么条件才可以开启这个选项?

**Comment by acgotaku** [comment]
因为不需要了  API统一换掉了

**Comment by superamd** [comment]
但是有这个选项的 能达到满速 要不然最高只能7M/s 昨天下午离线下载时抽风突然冒出这个选项 晚上又没了

**Comment by acgotaku** [comment]
你可以使用 bak分支的版本 那个是带VIP选项的 目前这个版本测试也是可以满速的

**Comment by lonelykid** [comment]
vip获取的d.pcs链接可以满速，普通版的pcs链接限速非常严重，哪怕是svip
