### ISSUE TITLE
百度网盘，没有速度，速度被限制在100kb以内

### ISSUE THREAD

**Issue by wdl214311131** [acgotaku/BaiduExporter#617]
请确保以下几点：

1. 已经阅读过README
2. 尝试安装最新版本插件
3. 尝试清空浏览器缓存
4. 尝试卸载插件后重新安装

发起 Issue 时，请提供：

1. 您下载的内容地址
2. 插件版本号，浏览器版本号，系统版本号
3. 列举出现问题的详细步骤
4. 描述能否复现问题

----------
用过大大的115插件，因为115翻车了，所以现在用的大大的百度网盘插件，群晖和aria2都没有变，下载115就是满速，但是下载百度网盘就被限速在100kb以内，不知道是不是百度有什么限制，请大大解决一下，谢谢！

**不符合上述条件的Issue将被无理由关闭**

**Comment by luoyeshu** [comment]
我遇到的情况是有些文件可以满速,有些文件速度被限制在100KB左右.
另外:尝试Readme选项时发现有歧义:aria2 版本大于1.18.4,那也就大于1.15.2,那么我到底该怎么设置 Recommended Settings?
总之3种Recommended Settings我都试过了,被限速的部分文件还是被限速.
我用的是最新的Aria2 1.33.1,助手1.0.2.
有同样情况的朋友吗?

**Comment by acgotaku** [comment]
百度网盘是服务器 限速 不充钱 很难解决

如果是开发者 可以尝试使用 dev分支版本
