### ISSUE TITLE
Chrome 32 無法導出檔案

### ISSUE THREAD

**Issue by Laputa-Skywalker** [acgotaku/BaiduExporter#62]
RT

**Comment by Laputa-Skywalker** [comment]
chrome 沒顯示導出選項，0.3.9的BUG

**Comment by Laputa-Skywalker** [comment]
0.3.8沒問題，請提供舊版下載的crx

**Comment by acgotaku** [comment]
@Laputa-Skywalker  0.3.8 版本我好像没有保留CRX  0.3.9有什么 BUG?

**Comment by Laputa-Skywalker** [comment]
今早測試過
Firefox 28 不行
http://i.imgur.com/dv4g6zB.png

**Comment by Laputa-Skywalker** [comment]
至於chrome
如果改過host表，也是會無法顯示導出下載按鈕

**Comment by acgotaku** [comment]
@Laputa-Skywalker  hosts ? 你修改了什么?
