### ISSUE TITLE
按下"導出本文"後，框框沒有出現網址 (XDM無法使用了...)

### ISSUE THREAD

**Issue by iuf64jj** [acgotaku/BaiduExporter#620]
Chrome 版本 69.0.3497.100 (64 位元)
BaiduExporter 1.02
如題，按下導出本文、打完驗證碼後，框框沒有出現網址
這該怎辦= =??
![default](https://user-images.githubusercontent.com/44198862/47023906-4900ff80-d193-11e8-9fc0-a8080e88791e.PNG)

2018/10/17更新
剛剛無聊測試了一下
這是登入百度前的樣子，無法顯示網址...
![0](https://user-images.githubusercontent.com/44198862/47087028-8d50d600-d24d-11e8-8160-443b7f4e490e.PNG)
這是登入後的樣子，網址居然跑出來了= =??，複製網址後貼上XDM確實可正常下載了^^
![1](https://user-images.githubusercontent.com/44198862/47087062-a8bbe100-d24d-11e8-9beb-b314e77a3d30.PNG)
登入請用這裡登，因為點右上角的登入會沒反應 https://passport.baidu.com/v2/?login
![00](https://user-images.githubusercontent.com/44198862/47087253-12d48600-d24e-11e8-85c6-ebf1549a6a05.PNG)

**Comment by Usagi2018** [comment]
我也有這個問題
應該是百度修改了代碼

**Comment by alfredmeow** [comment]
同上,要登入才能,百度究竟修改了甚麼代碼...

**Comment by noark9** [comment]
同样问题，前几天只是偶尔导出不了，昨天晚上开始，完全无法导出下载了

**Comment by G810704** [comment]
百度换了接口，现在只有速盘修复了免登录下载，等acgotaku修复吧

**Comment by ijayden-lung** [comment]
看来不止我一个人出现了问题

**Comment by taihe** [comment]
百度升级了系统，这个插件失效了。

**Comment by iuf64jj** [comment]
> 同上,要登入才能,百度究竟修改了甚麼代碼...
> 题外話暫時百度好像推行不登錄不能下載的限制(傳聞已久)，而小型文件亦須經百度客户端下載....
> 大部份市面上分享盤鏈接皆已失效，皆須登錄後才能使用腳本,但這麼做是否有被拉黑的風險就不清楚

現在好像真的要登入才能用腳本，不管大小文件都能用腳本

**Comment by G810704** [comment]
登录下载会导致账号限速

**Comment by alfredmeow** [comment]
把標題改了吧, 這樣聽起上來這個問題已被解決， 應該改成 ，可以登錄下載但問題仍未解決……

**Comment by SaberAlexander** [comment]
是的，同样的问题

**Comment by acgotaku** [comment]
我已经知道了 抽空看一下

**Comment by acgotaku** [comment]
百度貌似封了 匿名下载的接口 暂时没有好的对应方法

**Comment by user1121114685** [comment]
@acgotaku 大佬，看到你的回复我就安心了。期待大佬更新

**Comment by Icemic** [comment]
连Mac客户端都挂了，百度疯起来连自己人都打……

**Comment by kliyes** [comment]
弄了半天，以为是aria配置问题

**Comment by truelies1** [comment]
登录后,可以得到连接, 但好多连接都是403 forbidden错误,解释不出文件名的

**Comment by diggerdu** [comment]
> 登录后,可以得到连接, 但IDM上好多连接都是403 forbidden错误,解释不出文件名的
你账号的下载限额用完了 
@truelies1

**Comment by RickyXwang** [comment]
@truelies1
尝试导出为IDM文件，然后再用IDM导入试试，这样应该能带上需要的cookies

**Comment by ericworks** [comment]
@truelies1 @diggerdu @noark9 
Aria2和IDM现在需要在header里面加上BDUSS的Cookie才能下载了，否则会403
reference: https://www.cnblogs.com/aucy/p/9567375.html

**Comment by HashLiver** [comment]
测试了一下，备用帐号在很久没用的情况下，大约累计下载了500MB文件后就会限速，达到1GB后就直接403，但是正在下载的文件还是会继续下载。（如果一开始就下载个4-5GB单文件就会持续满速下载直到结束，再下载其它的就返回403）

**Comment by holoto** [comment]
文件放到单独文件夹下 然后导出文件夹 下载 成功
