### ISSUE TITLE
chrome 无法添加扩展

### ISSUE THREAD

**Issue by hufeng903** [acgotaku/BaiduExporter#621]
chrome 版本是70.0.3538.67,下载最新的master文件,打开拉扩展的开发者模式
1. 直接拉.crx 文件到浏览器里面，直接提示：无法从该网站添加应用，扩展程序，和用户脚本
2. 浏览添加：
未能成功加载扩展程序
文件
~/下载/BaiduExporter-master/chrome
错误
无法加载扩展程序图标“img/logo16.png”。
无法加载清单。

**Comment by JasonKhew96** [comment]
@hufeng903 `chrome/release` 文件夹

**Comment by hufeng903** [comment]
@JasonKhew96 可以了，谢谢。
