### ISSUE TITLE
Google把插件强制禁用了

### ISSUE THREAD

**Issue by qq12157138** [acgotaku/BaiduExporter#622]
<img width="405" alt="image" src="https://user-images.githubusercontent.com/15812485/47492510-c4dc0580-d87f-11e8-98f9-6aec7e648f48.png">
开发者模式好像也不行了。

**Comment by acgotaku** [comment]
文件夹载入也不行？

**Comment by CoderSimonWong** [comment]
文件夹载入可以，只是感觉不方便，有点强迫症

**Comment by CoderSimonWong** [comment]
这插件不能上线谷歌应用商店吗？

**Comment by XinoAssassin** [comment]
你参考一下这个吧https://hencolle.com/2016/10/16/baidu_exporter/

**Comment by lyzhyun** [comment]
无法使用，图标是灰色的，是不是谷歌更新69版本不能用？

**Comment by XinoAssassin** [comment]
@lyzhyun 参考https://hencolle.com/2016/10/16/baidu_exporter/ 加白名单

**Comment by lyzhyun** [comment]
![image](https://user-images.githubusercontent.com/18752249/47789370-5ac7d280-dd4f-11e8-9fbd-fc883b9ef932.png)
已经加入白名单，仍然无法使用

**Comment by XinoAssassin** [comment]
@lyzhyun 自己检查一下哪里出了纰漏，教程没有问题，与 chrome 版本无关。

**Comment by XinoAssassin** [comment]
@lyzhyun 我突然发现你加入白名单的ID是错误的，如果用了repo中打包好的crx，应该是跟1L的插件ID一致的。

**Comment by hasa-ki** [comment]
Chrome设置里面关掉安全浏览就行

**Comment by shao222** [comment]
插件 1.0.2 ，Chrome 71.0.3578.20
经测试，添加白名单方法是有效的。

先拖入crx 安装插件，无法启动，得到id，添加白名单。
我是这么操作的，仅供参考。

**Comment by qq12157138** [comment]
我参考了https://www.cnblogs.com/tinych/p/6703863.html 解决的问题。

**Comment by acgotaku** [comment]
@qq12157138 @CoderSimonWong  被谷歌下架过一次 所以不可能上架的

**Comment by EasterFan** [comment]
ubuntu16.04 + chrome  70.0.3538.77（正式版本） （64 位）+ BaiduExporter v0.8.5
![image](https://user-images.githubusercontent.com/28798206/48705537-5b5bd680-ec34-11e8-90a1-b669d1ec8a04.png)
windows上面白名单可以用，参考 [https://hencolle.com/2016/10/16/baidu_exporter/](https://hencolle.com/2016/10/16/baidu_exporter/)，作者给出了 Windows 和 MacOS 的解决方法，
可是 ubuntu 下 **com.google.Chrome.mobileconfig** 这个文件双击执行不了～加白名单失败～
![image](https://user-images.githubusercontent.com/28798206/48705920-8a267c80-ec35-11e8-85a3-5476390bc141.png)
等12月Chrome升级到 71 版本后，就很怕 ubuntu 的 chrome下第三方插件都要失了效 :cry: 
![image](https://user-images.githubusercontent.com/28798206/48705469-2cddfb80-ec34-11e8-9773-a440fdd9e04d.png)

**Comment by jlllweco** [comment]
我按照 https://juejin.im/post/5b3b29c8e51d451962727637
这个教程里 `配置强制安装的扩展程序的列表` 还是不行，百度云这个插件就是不能被Chrome加载。有人能知道可怎么办嘛~

**Comment by hasa-ki** [comment]
@jlllweco 设置 > 高级 > 安全浏览，关闭试试

**Comment by jlllweco** [comment]
> @jlllweco 设置 > 高级 > 安全浏览，关闭试试

还是不行呀。。。`配置强制安装的扩展程序的列表`了，安全浏览也关了，这个插件还是用不了。
还有其他办法用百度云吗
