### ISSUE TITLE
使用谷歌匿名打开网盘账号后，文件无法下载

### ISSUE THREAD

**Issue by bashang03** [acgotaku/BaiduExporter#625]
点击ARIA2 RPC之后可以到处到Aria2，但是瞬间显示下载失败，如果是正常谷歌浏览器（非匿名）模式打开不存在这个问题

**Comment by holoto** [comment]
百度网盘改了 现在下载文件需要登录账号了

**Comment by bbq191** [comment]
> 百度网盘改了 现在下载文件需要登录账号了

问题是怎么破。

**Comment by holoto** [comment]
> > 百度网盘改了 现在下载文件需要登录账号了
> 
> 问题是怎么破。

登录账号下载啊  我这边速度只有200k
要下载的文件非常多的话 推荐去淘宝买 云盘VIP账号吧
天卡1块左右 
月卡5快左右

**Comment by miqueen** [comment]
> > 百度网盘改了现在下载文件需要登录账号了
> 
> 问题是怎么破。

我有个号已经被限速了，就拿那个号登，索链接。

**Comment by feilangsfw** [comment]
> 点击ARIA2 RPC之后可以到处到Aria2，但是瞬间显示下载失败，如果是正常谷歌浏览器（非匿名）模式打开不存在这个问题

我没有开匿名，登陆状态下导出到aria2，也是瞬间被取消，估计百度改接口了？
  -> [HttpSkipResponseCommand.cc:239] errorCode=22 The response status is not s
uccessful. status=403

**Comment by hongzai1994** [comment]
我也遇到类似问题，登陆百度盘点击导出下载瞬间失败。但只存在于个别文件，换别的文件下载正常

**Comment by gokuweb** [comment]
> > 点击ARIA2 RPC之后可以到处到Aria2，但是瞬间显示下载失败，如果是正常谷歌浏览器（非匿名）模式打开不存在这个问题
> 
> 我没有开匿名，登陆状态下导出到aria2，也是瞬间被取消，估计百度改接口了？
> -> [HttpSkipResponseCommand.cc:239] errorCode=22 The response status is not s
> uccessful. status=403

登录之后刷新一下百度盘的页面，现实初始化成功，再导出到rpc，就可以在http://aria2c.com/ 看到成功下载中了吧。没等录的话会报你那个错
