### ISSUE TITLE
官方支持的火狐扩展？

### ISSUE THREAD

**Issue by lilydjwg** [acgotaku/BaiduExporter#626]
目前我在[这里](https://addons.mozilla.org/firefox/addon/baidu-pan-exporter/)看到有人上传了一份用于火狐的版本，但是已经很久没更新了，作者也没有留下联系方式。这里有个 issue 里也有一些个人在尝试，但是让每个用户都去上传一份自己用，太浪费人力了。所以要不要官方支持一个火狐扩展，然后大家都使用？

如果你支持的话，我可以 fork 该仓库并维护一个火狐扩展版，并且使用独立的 issues 用于管理。

**Comment by shellexy** [comment]
啊，咱觉得反正都是 webextension 格式，雪依依让她通用 firefox 就好啦就不分仓库啦，
秋水酱觉得怎么样呀

**Comment by acgotaku** [comment]
我自己曾经发布过一个 火狐版本的  但是被百度举报了。。。 就没有再上架
如果有人愿意传一份在火狐商店当然最好了，现在都支持 webextension了 我测试过 FF上也是能用的

**Comment by lilydjwg** [comment]
会被举报啊，那这个仓库为什么就幸免了呢？如果是政策不一样的话，那能不能在 github 上放 xpi 呢？

**Comment by acgotaku** [comment]
@lilydjwg 估计百度举报过吧  但是Github没鸟他 Chrome的也是被举报下架的。。。 XPI应该是可以放的。
不过现在还没有一键打包脚本。。。

**Comment by yijinbandouya** [comment]
~~~~(>_<)~~~~，求作者大大私发一份firefox的可好？

**Comment by yijinbandouya** [comment]
13029863581@163.com

**Comment by lilydjwg** [comment]
别要了，拿到链接之后 403 错误。另外不支持 container。
