### ISSUE TITLE
百度网盘下载是不是被限速了？

### ISSUE THREAD

**Issue by sevenfxx** [acgotaku/BaiduExporter#63]
单文件下载速度最快只能到300KB左右，如果同时下载两个，单文件还是这么多，总速度X2

**Comment by XhstormR** [comment]
一个连接最大300KB/S，所以要多线程下载

**Comment by XhstormR** [comment]
一个链接最大300KB/S，所以要多线程下载。

**Comment by acgotaku** [comment]
@sevenfxx 顺便看看 UA是不是最新的

**Comment by sevenfxx** [comment]
请问怎么设置多线程呢？
ARIA2版本为： 1.18.7，用的http://github.com/ziahamza/webui-aria2  这里的WEBUI，max-connection-per-server设置的是5，迅雷导出来下载都是5个线程，但百度只有1个线程。
UA如下：
netdisk;4.4.0.6;PC;PC-Windows;6.2.9200;WindowsBaiduYunGuanJia

**Comment by acgotaku** [comment]
@sevenfxx  netdisk;5.2.7;PC;PC-Windows;6.2.9200;WindowsBaiduYunGuanJia

确实改换 UA了

**Comment by sevenfxx** [comment]
@acgotaku 谢谢，确实是UA变了，更新了UA，下载可以接近3MB/s 了。最高好像只支持4个线程。

**Comment by acgotaku** [comment]
@sevenfxx 那你可以关掉这个 issue了
