### ISSUE TITLE
失效了，之前用的好好的

### ISSUE THREAD

**Issue by hahaapi** [acgotaku/BaiduExporter#630]
好像从昨天开始吧，导入不到aria2下载了

HTTP 返回头无效或无法识别.
https://d.pcs.baidu.com/file/eb909147180d4c635b42e8afa4986172?fid=2561082726-250528-321178293571318&rt=pr&sign=FDtAERVCY-DCb740ccc5511e5e8fedcff06b081203-5OMwnE5cuwOewgIFsSvqBPObb6I%3D&expires=8h&chkv=1&chkbd=1&chkpc=et&dp-logid=7757187940448090021&dp-callid=0&dstime=1543633777&r=318888799

**Comment by chengjianhao** [comment]
希望作者看看，error HTTP response header was bad or unexpected

**Comment by chengjianhao** [comment]
@hahaapi  能加个qq聊聊吗，配置上好像有个问题，想问问你，qq：1584900157

**Comment by GongChuanZan** [comment]
我的导入之后也全部失败，没一个下载成功的，该更新了。

**Comment by chengjianhao** [comment]
@acgotaku

**Comment by chengjianhao** [comment]
@acgotaku ，应该就是这个问题，https://github.com/acgotaku/BaiduExporter/issues/547

**Comment by CoCo269** [comment]
@acgotaku 遇到同样的问题
同样的扩展版本+同样的资源链接在 Chrome 上可行，在 Firefox 上则报错（错误信息与题主一致）

**Comment by hahaapi** [comment]
链接: https://pan.baidu.com/s/1i1k0GXfDt_IB2LxkHiEl9g 提取码: xs5e 复制这段内容后打开百度网盘手机App，操作更方便哦

作者可以试一下这几个能不能导出到aria2下载

**Comment by hahaapi** [comment]
> 我这边 测试 没问题的 你是自己网盘下载 还是分享下载？

链接: https://pan.baidu.com/s/1i1k0GXfDt_IB2LxkHiEl9g 提取码: xs5e 复制这段内容后打开百度网盘手机App，操作更方便哦

作者可以试一下这几个能不能导出到aria2下载

**Comment by rudeigerc** [comment]
用开发者工具看一下 Cookie 把 Cookie 全部复制进 Header 里就好了

**Comment by hahaapi** [comment]
> 用开发者工具看一下 Cookie 把 Cookie 全部复制进 Header 里就好了

工发者工具怎么看？CHROME，只会网址栏前面，点击，然后一个一个COOKIE复制

**Comment by chengjianhao** [comment]
看下#547里面的，用开发者工具查看home的包

**Comment by rudeigerc** [comment]
@hahaapi 在 Network 里选那个链接然后看 Request Headers 里的

**Comment by hahaapi** [comment]
> @hahaapi 在 Network 里选那个链接然后看 Request Headers 里的

添加了COOKIE还是不行，你试下新资源看看
链接: https://pan.baidu.com/s/1i1k0GXfDt_IB2LxkHiEl9g 提取码: xs5e

**Comment by rudeigerc** [comment]
@hahaapi 你发的那个链接我这边也可以，你确定登录了吗？

**Comment by wutao667** [comment]
同样的问题，有些资源可以，有些不行，有些开始可以后面就不行，不稳定

**Comment by hahaapi** [comment]
> @hahaapi 你发的那个链接我这边也可以，你确定登录了吗？

所以我就没搞懂呀，之前好好的，一直正常使用，就这几天没法下载了

**Comment by offwalk** [comment]
@brianpow
海外手機號如何註冊百度賬號？
https://www.zhihu.com/question/271825408

**Comment by chengjianhao** [comment]
@KwToPA 我的现在稳定了，在HEADER里面加了 BAIDU，还有BDUSS 两个的信息，好像可以用了

**Comment by chengjianhao** [comment]
@KwToPA 但是下载的速度还是得看资源，有些只能10个线程下载，有些16的线程，10线程的经常会掉到10kb，然后又恢复到几百kb，这样子

**Comment by chengjianhao** [comment]
有些资源还是不能下载

**Comment by KwToPA** [comment]
> 有些资源还是不能下载

我有cookies，BAIDUID=hidden:FG=1; PANWEB=1; BDUSS=hidden; STOKEN=hidden; SCRC=hidden; cflag=hidden; PANPSC=hidden

referer https://pan.baidu.com/disk/home
User-agent netdisk;5.3.4.5;PC;PC-Windows;5.1.2600;WindowsBaiduYunGuanJia

你User-agent  什么？
---
我在vps上开n线程都无效,n大于等于1

在本地若按ctrl+c中止后，无法再次下载该url。

本地正常下载，也只有几百k或者1-2M的文件能下

**Comment by chengjianhao** [comment]
@KwToPA netdisk;5.2.6;PC;PC-Windows;6.2.9200;WindowsBaiduYunGuanJia

**Comment by KwToPA** [comment]
aria2c -c -s100 -k1M -x100 --enable-rpc=false 

--header "User-Agent: netdisk;5.3.4.5;PC;PC-Windows;5.1.2600;WindowsBaiduYunGuanJia" 

--header "Referer: https://pan.baidu.com/disk/home" 

--header "Cookie: BDUSS=hidden; pcsett=hidden" 

--header "BAIDUID=hidden:FG=1; PANWEB=1; BDUSS=hidden; STOKEN=hidden; SCRC=hidden; cflag=hidden; PANPSC=hidden" "hidden"

**Comment by kelvinsiuzzz** [comment]
只要一download, 任務便直接顯示失敗了...

**Comment by AurevoirXavier** [comment]
重新登录 可能刷新一下身份

**Comment by KwToPA** [comment]
@AurevoirXavier
 我重新登录过，换过vps，都无效。 偶尔本地下载也失败。

**Comment by xorxorxorxor** [comment]
> @AurevoirXavier
> 我重新登录过，换过vps，都无效。 偶尔本地下载也失败。

我这边也是，看来是百度做了新的限制了，本地对于大文件下载中间肯定会中断，希望有大神能给出解决办法啊，要不只能使用百度管家下载了，不爽

**Comment by rilyuuj** [comment]
> > aria2c -c -s100 -k1M -x100 --enable-rpc=false
> > --header "User-Agent: netdisk;5.3.4.5;PC;PC-Windows;5.1.2600;WindowsBaiduYunGuanJia"
> > --header "Referer: https://pan.baidu.com/disk/home"
> > --header "Cookie: BDUSS=hidden; pcsett=hidden"
> > --header "BAIDUID=hidden:FG=1; PANWEB=1; BDUSS=hidden; STOKEN=hidden; SCRC=hidden; cflag=hidden; PANPSC=hidden" "hidden"
> 
> 按照这个格式确实可以下载了，不过cookie是会刷新和过期的，这个方法只是权宜之计啊

我也是今天失效了，重新抓取下cookie就好了，看了下除了BAIDUID全变了，难道是自然年的缘故？

**Comment by oliwill** [comment]
Aria2 1.33.1
Aria2GUI  1.4 (1)
Google Chrome 71.0.3578.98
MacOS Mojave 10.14.2
在网盘页和分享页下载都报 error。在 headers 添加 cookie 一样报 error。

**Comment by AshtonCoop** [comment]
能否介绍下如何加header?(对技术一块不怎么懂)
最近下载百度盘全部都直接挂掉.无法下载任何东西.
感谢

**Comment by KwToPA** [comment]
@AshtonCoop  可以看这个 https://github.com/acgotaku/BaiduExporter/issues/547#issuecomment-357942255

**Comment by pright** [comment]
我这里的表现是文件大小有限制了，小于30MB（实际临界值不确定）的文件都可以正常下载，超过的都是立刻失败。

**Comment by shisaq** [comment]
我也遇到了这个问题，在下载一个2G的文件时，通过百度云管家网页端 + Baiduexporter 插件导出到 Aria2 后，在 Aria2 中直接把任务跳转到了 “Other Tasks”，任务失败，错误信息为 “HTTP response header was bad or unexpected”。

也尝试了在导出设置中，手动添加header的方法，但仍然不管用。最终我**给百度信仰充值**了一把，这次可以正常下载了...

**Comment by yuyuyuer** [comment]
我也遇到同样问题了，开始以为是每天限流，结果第二天仍然无法正常下载，请问有解决办法吗

**Comment by mailbyms** [comment]
是的，不能用了。

**Comment by waeshang** [comment]
现在下载百度云的工具aria2c 换成了axel, 飞一般的速度又回来了!!太棒了, 实在太感谢作者了! 希望大多数受到百度云无理限速的小伙伴们也能看见这条消息.

**Comment by rilyuuj** [comment]
现在只能保存到自己网盘后下载了，大家有这样的情况吗？ cookie什么都换过了

**Comment by acgotaku** [comment]
@rilyuuj  目前来说 保存到自己网盘是最稳妥的办法了，未登录 已经无法下载了
