### ISSUE TITLE
只要一download, 任務便直接顯示失敗了...

### ISSUE THREAD

**Issue by kelvinsiuzzz** [acgotaku/BaiduExporter#631]
只要一download, 任務便直接顯示失敗了...
設定沒有改變過, 以前也沒有問題的...
![image](https://user-images.githubusercontent.com/31714899/49978453-9e843d80-ff85-11e8-97dd-11d37cf1c707.png)

**Comment by shuncox** [comment]
同样的问题，应该是同样的客户端

**Comment by AurevoirXavier** [comment]
重新登录 可能是身份过期

**Comment by JairWx** [comment]
把资源分享出去，然后再分享页点击导出下载就可以了

**Comment by acgotaku** [comment]
你这描述的不明不白。。。 是自己网盘下载 还是分享页面下载？

**Comment by YxY-CHN** [comment]
我测试了一下，目前我这里不管是自己网盘，分享，换号，无痕基本都失败。
提示貌似是：403
Aria2版本是：1.19
errorCode=22

**Comment by flytigerboy** [comment]
自己网盘下载，也一点击就出现错误，无法下载，状态提示403啊，说HTTP头无效或无法识别

**Comment by wanz4** [comment]
我也有这个问题，用的是mac版本，之前一直用的没问题，现在下载自己网盘里的东西，在active task里面显示了2秒后自动跳到other task里面并且显示"X 0 kb" 就是下载失败，但是没有任何失败状态提示说403，HTTP头无效或无法识别这些，就直接失败了。。。。

**Comment by rogeryan** [comment]
> 1.把资源分享出去，然后在分享页点击导出下载就可以了,但是被限速了
> 2.用小号接收分享的东西，再分享，再下载可以避免被封速

这个办法经我测试是可以使用的。由此推断出百度网盘限制了每个账号每日的下载量，例如3G，如果超出后再下就会收到403被拒绝的错误。所以可以注册多个小号来下载，或者等第二天接着下载。但这仅适用于多个小文件的情况，例如每个文件1G，如果是单个文件特别大，例如5G以下，则很有可能中途被断开，那就白下了。

**Comment by yuyuyuer** [comment]
> > 1.把资源分享出去，然后在分享页点击导出下载就可以了,但是被限速了
> > 2.用小号接收分享的东西，再分享，再下载可以避免被封速
> 
> 这个办法经我测试是可以使用的。由此推断出百度网盘限制了每个账号每日的下载量，例如3G，如果超出后再下就会收到403被拒绝的错误。所以可以注册多个小号来下载，或者等第二天接着下载。但这仅适用于多个小文件的情况，例如每个文件1G，如果是单个文件特别大，例如5G以下，则很有可能中途被断开，那就白下了。

限速好厉害，按你说的方法，等第二天下载，依旧只有30k速度

**Comment by lyk248** [comment]
我是下载5.3M的照片可以正常下载，但是几百兆的视频就会下载失败，上G的也是，直接报错。
  -> [HttpSkipResponseCommand.cc:240] errorCode=22 The response status is not successful. status=403

**Comment by acgotaku** [comment]
@lyk248  errorCode=22 The response status is not successful. status=403

这个错误 目前无解。。。
