### ISSUE TITLE
大姐 百度网盘助手 1.0.2 失效了啊

### ISSUE THREAD

**Issue by rr4e** [acgotaku/BaiduExporter#632]
2018-12-16 14：00
我在linux下载百度云大文件都不知道该怎么下啊

**Comment by rr4e** [comment]
哦 可以了
原来我重装系统
直接cp了你的配置文件
    #文件保存路径, 默认为当前启动位置
    dir=/home/acgotaku/Downloads
压根就没有a目录
我普通用户也没权限创建
su mkdir chown后问题解决
插件依然有效
抱歉... ...

**Comment by holoto** [comment]
哈哈哈 你看人家头像女性化就叫人家大姐
