### ISSUE TITLE
导出 获取不到下载地址 是百度网盘更新了吗

### ISSUE THREAD

**Issue by HaimmingYu** [acgotaku/BaiduExporter#634]
请确保以下几点：

1. 已经阅读过README
2. 尝试安装最新版本插件
3. 尝试清空浏览器缓存
4. 尝试卸载插件后重新安装

发起 Issue 时，请提供：
导出 获取不到下载地址 是百度网盘更新了吗
1. 您下载的内容地址
chrome
2. 插件版本号，浏览器版本号，系统版本号
1.0.2  浏览器 版本 71.0.3578.98（正式版本） （64 位） 系统 10.13.6 (17G65)
3. 列举出现问题的详细步骤
下载文件 
：https://pan.baidu.com/s/1U6AA3AgGIqpTx-l-I9XSXw

密码：0ahd
无法导出到ARIA2
4. 描述能否复现问题

----------

**不符合上述条件的Issue将被无理由关闭**

**Comment by HaimmingYu** [comment]
退出ARIA2 GUI  在登录 又可以了

**Comment by acgotaku** [comment]
又可以的情况 你倒是 关闭 issue啊
