### ISSUE TITLE
谷歌、火狐浏览器插件初始化失败

### ISSUE THREAD

**Issue by kukuhuihao** [acgotaku/BaiduExporter#635]
在登录百度云之后，“导出下载”的按钮不出现。当显示“初始化成功”的时候才能出现。

1、尝试过清空缓存，重装google chrome，重装插件，更换过火狐流览器
2、系统： mac os 10.14

**Comment by ShirleyMatrix** [comment]
+1 并且在自己的网盘界面点击勾选文件后导出按钮会消失

**Comment by acgotaku** [comment]
当加载成功的时候才会显示初始化成功啊。。。

有时候因为网络原因确实会加载失败啊。。
