### ISSUE TITLE
下载文件名不全的问题

### ISSUE THREAD

**Issue by Leeiio** [acgotaku/BaiduExporter#638]
下载的文件名从某天开始突然变成只剩文件格式后缀，或者文件名不全，只剩下了部分的文件名，难道大家都没有遇到么？
是最新版的chrome插件

**Comment by lautis0503** [comment]
印象中，分享页面导出文件名不全，存入网盘后导出文件名完整

**Comment by acgotaku** [comment]
这个问题确实存在 我最近修复下

**Comment by agalwood** [comment]
@acgotaku 昨天我修理这个问题的时候看到 item 数据里有 `server_filename`，是出于什么原因不使用 `server_filename` 而使用 `path.substr` 的呢？

https://github.com/agalwood/BaiduExporter/commit/4403745782733d13477e0aad01f51686334ee65e

**Comment by acgotaku** [comment]
@agalwood  因为针对文件夹下载 需要保留 文件夹结构

**Comment by agalwood** [comment]
嗯，发现了，我那样处理之后，又有用户给我提了 [issue](https://github.com/agalwood/Motrix/issues/76)

那天查问题记录的一些数据，希望方便你处理
```
// share.js
console.log(window.yunData.PATH)
// /sharelink3021310168-128697639101915/同济高等数学 第六版 上册 同济大学数学系.pdf
console.log(prefix)
// 37
console.log(item.path)
// /pdf电子书/同济高等数学 第六版 上册 同济大学数学系.pdf
```

**Comment by acgotaku** [comment]
目前不好拿到用户所在的文件夹层级 目前只能从根节点下载 这样用户也会很困扰。。。

**Comment by acgotaku** [comment]
@agalwood  https://motrix.app/  话说你这个 504 了

**Comment by agalwood** [comment]
@acgotaku 我看看，难道今天又不太平了么，昨天下午被 DDoS 了

**Comment by agalwood** [comment]
@acgotaku 重启了一把服务器，暂时恢复了

**Comment by agalwood** [comment]
@acgotaku 去阿里云看了一下，的确又被 DDoS 了，昨天小身板的服务器一下子承受了 420000 Kbps 的流量攻击

**Comment by acgotaku** [comment]
那就上 CDN @agalwood

**Comment by KANGOD** [comment]
@Leeiio 请问您遇到的是所有文件名都有问题嘛？还是说出现问题的文件名都有一些什么相同的特点？

@acgotaku 我也遇到了类似的问题，文件名形如 _log_2019_02_22_16_34_35[1].tgz_，最终 “导出下载 -> 文本导出” 的命令行里是 `-o "1].tgz"`，只截取了 `[` 后面的部分。
我最初用的版本是 1.0.2 307d94f16404fe16aca5082fdffb576d868c62a4，发布这条评论之前又测试了一下目前最新的 master HEAD 1.0.2 7723f32bf7ac3ca7099f69968cc202eb819a1291，都有这个问题。

**Comment by Leeiio** [comment]
@KANGOD 基本都有问题吧，耐心等等吧，作者在修复中了

**Comment by xzing** [comment]
等的好焦急哦，还没好么

**Comment by acgotaku** [comment]
服务器返回的数据 有差异 所以还没特别好的解决方案 你可以选择保存自己网盘再下载啊 @xzing

**Comment by xzing** [comment]
> 服务器返回的数据 有差异 所以还没特别好的解决方案 你可以选择保存自己网盘再下载啊 @xzing

保存到自己网盘下之后，基本上下一个失败一个。感觉进了百度黑名单

**Comment by acgotaku** [comment]
修复了 这个问题 但是对于分享的是一个文件夹 只能保留完整路径

**Comment by fancecilia** [comment]
請問文件名不全的問題已經修复了嗎？
我的不但文件名不全，連下載的檔案也從沒顯示在電腦任何一個位置中（但aria2顯示下載完成）
不知道這兩個問題是不是有關聯的。。
求大神解答應該怎麼辦！

**Comment by acgotaku** [comment]
@fancecilia 你先文本导出 看看文件的路径 很多时候是你自己的NAS设定有问题
但都跑这里来问 问题。。。
