### ISSUE TITLE
不支持secret token

### ISSUE THREAD

**Issue by slime7** [acgotaku/BaiduExporter#64]
没法填secret token，无法跟RPC通信

**Comment by acgotaku** [comment]
Recommend: Set --rpc-secret= if you are using aria2 1.18.4(or higher) with 'JSON-RPC PATH' like http://token:secret@hostname:port/jsonrpc

@slime7 怎么不能填!

**Comment by slime7** [comment]
token带@的怎么填？htmlencode吗？

**Comment by acgotaku** [comment]
@slime7 你一定要设置这么奇葩的 token ?!

**Comment by slime7** [comment]
token发是发出去了，然而还是返回500，我自己再看一下
![2](https://cloud.githubusercontent.com/assets/8674371/9248426/b9442f22-41f6-11e5-9dfb-6660771f7fca.gif)
