### ISSUE TITLE
导出的文件夹下载，没有建立相应的文件夹，里面所有的文件都下载到根目录了

### ISSUE THREAD

**Issue by YYK19911212** [acgotaku/BaiduExporter#642]
测试了Windows、Linux两个平台的aria2都出现此问题， 相同环境下使用115网盘的导出下载可以正常建立目录， 望大佬能修复下

**Comment by acgotaku** [comment]
分享页面的 下载  已经有人说了 目前还没啥好的解决方案。。。

**Comment by smithyj** [comment]
1.0.2版本呢？

**Comment by acgotaku** [comment]
好了 好了 修复了 不过对于单文件夹 只能保留完整路径
