### ISSUE TITLE
错误,请查看是否开启Aria2~

### ISSUE THREAD

**Issue by bjznl** [acgotaku/BaiduExporter#644]
请确保以下几点：

1. 已经阅读过README
2. 尝试安装最新版本插件
3. 尝试清空浏览器缓存
4. 尝试卸载插件后重新安装

发起 Issue 时，请提供：

1. 您下载的内容地址https://pan.baidu.com/s/1hdIDD7IdRIepaBMantuEnQ
2. 插件版本号1.02，浏览器版本号72.0.3626.96，系统版本号win7 sp1
3. 在设置里添加rpc地址，测试连接提示错误,请查看是否开启Aria2
4. 用http://token:secret@hostname:port/jsonrpc  可以在    http://binux.github.io/yaaw/demo/    获得版本号。

**Comment by acgotaku** [comment]
链接不存在
