### ISSUE TITLE
出现掉速问题

### ISSUE THREAD

**Issue by marcosteam** [acgotaku/BaiduExporter#647]
请确保以下几点：

已经阅读过README，并按照说明设置
插件版本为最新
浏览器缓存已清空
已重装过插件

发起 Issue 时，请提供：

下载内容：https://pan.baidu.com/s/1GZmjYejMcXjwPZ4zSUn_cQ 提取码: 4g9m
插件版本：1.0.2，浏览器版本：Cent browser (Chromium 72.0.3626.121) ，系统版本：Windows 10 1803
问题：已登陆百度网盘会员，可以开始下载，但是速度会从1-2M/s掉速至10k/s左右。多次下载问题复现严重

----------

**不符合上述条件的Issue将被无理由关闭**

**Comment by marcosteam** [comment]
出现掉速的截图：
![2019-3-30 15-1-4.png](https://i.loli.net/2019/03/30/5c9f143f62a73.png)

**Comment by acgotaku** [comment]
掉速问题 目前不属于 本插件的处理范围，想提高速度请充值会员
