### ISSUE TITLE
master分支的crx无法安装

### ISSUE THREAD

**Issue by 2997215859** [acgotaku/BaiduExporter#648]
请确保以下几点：

1. 已经阅读过README
2. 尝试安装最新版本插件
3. 尝试清空浏览器缓存
4. 尝试卸载插件后重新安装

发起 Issue 时，请提供：

1. 您下载的内容地址
2. 插件版本号，浏览器版本号，系统版本号
3. 列举出现问题的详细步骤
4. 描述能否复现问题

----------

**不符合上述条件的Issue将被无理由关闭**

master分支的crx无法安装

插件版本号：master
浏览器版本号：google chrome 73.0.3683.86 (正式版本) （64 位）
系统版本：ubuntu 16.04

**Comment by 2997215859** [comment]
拖到chrome://extensions这个页面，提示程序包: CRC_HEADER_INVALID。
![image](https://user-images.githubusercontent.com/13400243/55371685-a9adaa00-5531-11e9-8f2a-e58d2dce8f35.png)

**Comment by RecluseWind** [comment]
chrome73版已经禁止本地安装了，解决办法要么降级到72，要么把crx文件改后缀zip，然后解压加载。

**Comment by lucky9322** [comment]
> chrome73版已经禁止本地安装了，解决办法要么降级到72，要么把crx文件改后缀zip，然后解压加载。

在讲crx文件改为zip后进行解压时  提示the file is broken
![image](https://user-images.githubusercontent.com/11935073/55533557-39935580-56e4-11e9-8d3e-162da384abf4.png)

**Comment by acgotaku** [comment]
那就直接开发者 模式 载入 release文件夹
