### ISSUE TITLE
提示header error

### ISSUE THREAD

**Issue by weakiwi** [acgotaku/BaiduExporter#65]
偶尔放在后台下，下到百分之六七十就没速度了。提示请求头错误，自己删掉referer和ua以后直接就下都下不了了。换成浏览器的ua还是一样的问题。

**Comment by acgotaku** [comment]
@weakiwi 可以给个截图看看么? ua必须使用 netdisk那个的

**Comment by weakiwi** [comment]
![][1]



  [1]: http://ww2.sinaimg.cn/large/68566be7gw1evenjij1bcj211z0hj46v.jpg

**Comment by acgotaku** [comment]
@weakiwi 可能是时间长了 下载链接失效 重新导出RPC下载 即可

**Comment by weakiwi** [comment]
@acgotaku 他们说貌似度盘现在开始从服务端限制连接线程和流量了。或许可以尝试下几个ua换着用？

**Comment by acgotaku** [comment]
@weakiwi 你确定 ? 我现在用着感觉速度还可以 ua还是推荐百度管家的 netdisk
