### ISSUE TITLE
请求支持自定义COOIES

### ISSUE THREAD

**Issue by zx1425819914** [acgotaku/BaiduExporter#652]
只有BDUSS一个值不够     需要自定义cooies就可以下载百度网盘里的文件  因为有的文件无法分享

**Comment by acgotaku** [comment]
本身就可以自定义 Headers 当然也包含cookies

**Comment by zx1425819914** [comment]
可是吧 我要的那些值是这样的 cookie: BIDUPSID=58BD0ADDF7FB8B8B9D6C621EB0531619; PSTM=1547795466; BAIDUID=3558AB7EB05814E493471B96B883C6BF:FG=1; BDUSS=EtVm9ITURQWllSdVM0bjNTZnlZQ3oyam1HS1pvcjY2bUxGclJSNEFPWGFCdUZjRUFBQUFBJCQAAAAAAAAAAAEAAADnuiPPMTMwKioqKioqMDEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAANp5uVzaeblcMG; delPer=0; PSINO=2; H_PS_PSSID=; BDORZ=FFFB88E999055A3F8A630C64834BD6D0; cflag=13%3A3; pcsett=1555746823-6edf48341e1183f5de4d1fd58af7415c; STOKEN=9f6af47ffd16cf7e35cc2afd4998cfaff83f045cdb821abec01c8d645fa408a2
我没看到自定义cookies 所以希望添加


------------------ 原始邮件 ------------------
发件人: "雪月秋水"<notifications@github.com>;
发送时间: 2019年4月19日(星期五) 晚上9:55
收件人: "acgotaku/BaiduExporter"<BaiduExporter@noreply.github.com>;
抄送: "徒然."<1425819914@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [acgotaku/BaiduExporter] 请求支持自定义COOIES (#652)




本身就可以自定义 Headers 当然也包含cookies

**Comment by acgotaku** [comment]
@zx1425819914 说明你没有相关的网络知识  请好好学习 我不会添加
