### ISSUE TITLE
该工具今天失效了

### ISSUE THREAD

**Issue by xiangliu886** [acgotaku/BaiduExporter#654]
请确保以下几点：

1. 已经阅读过README
2. 尝试安装最新版本插件
3. 尝试清空浏览器缓存
4. 尝试卸载插件后重新安装

发起 Issue 时，请提供：

1. 您下载的内容地址
2. 插件版本号，浏览器版本号，系统版本号
3. 列举出现问题的详细步骤
4. 描述能否复现问题

----------

**不符合上述条件的Issue将被无理由关闭**
前天使用您的工具下载大文件，可以正常使用，但是今天已经不能使用了，导致大文件续传到99.5%后不能下载了，麻烦大神帮忙查一下。
![UcSTAR20190426162100](https://user-images.githubusercontent.com/7287375/56793840-7663ef80-683f-11e9-8ea5-3b9addf304d4.jpg)

**Comment by xiangliu886** [comment]
无效的IDM文件 *.ef2 的内容如下：

<
https://d.pcs.baidu.com/file/12740e3ad56895b88bad1e3b29930008?fid=3476936326-250528-912503237719618&dstime=1556267226&rt=sh&sign=FDtAERVY-DCb740ccc5511e5e8fedcff06b081203-u1BsMcuq2s%2BXh0tG01T%2F4uDOec4%3D&expires=8h&chkv=1&chkbd=0&chkpc=et&dp-logid=2683073055882780670&dp-callid=0&shareid=867648421&r=707307536
user-agent: netdisk;6.0.0.12;PC;PC-Windows;10.0.16299;WindowsBaiduYunGuanJia
referer: https://pan.baidu.com/disk/home
cookie: BDUSS=XF2YXBrVFAtanc4UDB-d2NGcGdkWHItaW5JQ0FiYVQyaHBGbG1Mek9jeW1RdXBjRVFBQUFBJCQAAAAAAAAAAAEAAADqlJw5tLrH77fJzcMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAKa1wlymtcJcY; pcsett=1556353612-1a185bf6ea74fae2f5a47b52621e0070
>

**Comment by acgotaku** [comment]
IDM 由于我没有购买 所以现在暂时无法测试 但是Aria2c是可以使用的

**Comment by gitterliu** [comment]
@xiangliu886 兄弟别把自己的cookie发出来啊

**Comment by xiangliu886** [comment]
谢谢解答
