### ISSUE TITLE
ubuntu chrome crx 无法安装， 报错CRX_HEADER_INVALID

### ISSUE THREAD

**Issue by chuan000** [acgotaku/BaiduExporter#657]
请确保以下几点：

1. 已经阅读过README
2. 尝试安装最新版本插件
3. 尝试清空浏览器缓存
4. 尝试卸载插件后重新安装

发起 Issue 时，请提供：

1. 您下载的内容地址
2. 插件版本号，浏览器版本号，系统版本号
3. 列举出现问题的详细步骤
4. 描述能否复现问题

----------

**不符合上述条件的Issue将被无理由关闭**

**Comment by acgotaku** [comment]
CRX无法安装 请使用 开发者模式 载入 Release文件夹

**Comment by DailyShana** [comment]
@acgotaku 经测试，使用最新版chrome（v73以后）打包crx可以避免这个问题，希望更新一下

**Comment by jastdogit** [comment]
v74还是有无法安装crx呀 💔

**Comment by zazaluMonster** [comment]
如果你是v74版本，可以尝试操作
1.将crx文件改为zip文件
2.解压后得到本体文件夹BaiduExporter/
3.打开chrome，选择"加载已解压的扩展文件"(英文为"load unpacked")
4.在弹出的对话框中选中BaiduExporter/，点击确认

应该安装成功了

**Comment by AlexaraWu** [comment]
@acgotaku Chrome 从 v73 开始只支持 CRX3 格式的扩展，不再支持原来 CRX2 格式的扩展，用新版的 Chrome 打包可以解决这个问题。

**Comment by DailyShana** [comment]
> @acgotaku Chrome 从 v73 开始只支持 CRX3 格式的扩展，不再支持原来 CRX2 格式的扩展，用新版的 Chrome 打包可以解决这个问题。

参见https://bugs.chromium.org/p/chromium/issues/detail?id=941356#c13
