### ISSUE TITLE
火狐百度网盘助手1.01用不了

### ISSUE THREAD

**Issue by wakupman** [acgotaku/BaiduExporter#659]
请确保以下几点：

1. 已经阅读过README
2. 尝试安装最新版本插件
3. 尝试清空浏览器缓存
4. 尝试卸载插件后重新安装

发起 Issue 时，请提供：

1. 您下载的内容地址
2. 插件版本号，浏览器版本号，系统版本号
3. 列举出现问题的详细步骤
4. 描述能否复现问题

----------

**不符合上述条件的Issue将被无理由关闭**

已完成操作

已经阅读过README
尝试安装最新版本插件
尝试清空浏览器缓存
尝试卸载插件后重新安装

发起 Issue 时，请提供：
1.下载的内容地址 
` https://pcs.baidu.com/rest/2.0/pcs/file?method=download&app_id=250528&path=%2F%E6%88%91%E7%9A%84%E8%B5%84%E6%BA%90%2F5T%2F1%2F%E6%BC%AB%E7%94%BB%E4%B9%A6(%E6%97%A5%E6%BC%AB%20%E5%9B%BD%E6%BC%AB%20%E7%BE%8E%E6%BC%AB%20%E6%B8%AF%E5%8F%B0%E6%BC%AB)%2F%E9%A6%99%E6%B8%AF%E5%8F%B0%E6%B9%BE%E6%BC%AB%E7%94%BB%2F%E3%80%90%E5%B7%B2%E5%AE%8C%E7%BB%93%E3%80%91%E9%AD%94%E5%9F%9F%E6%88%98%E5%A3%AB%5B%E7%B1%B3%E5%A5%87%5D%5B%E8%B0%81%E5%9C%A8%E4%B9%8E%E7%89%88%5D%2F%E9%AD%94%E5%9F%9F%E6%88%98%E5%A3%AB01%E5%8D%B7.zip`

2.插件版本号:火狐百度网盘助手1.01
   浏览器版本号:火狐60.2.2esr
   系统版本号:centos7.6.1810

3.出现问题的详细步骤:
   1)直接用aria2 rpc导出失败
   
![image](https://user-images.githubusercontent.com/6198568/57519814-c3bb8300-734e-11e9-88a6-79ead1603cbb.png)

   2)用导出文本到linux中跑命令行
```
aria2c -c -s10 -k1M -x16 --enable-rpc=false -o "【已完结】魔域战士[米奇][谁在乎版]/魔域战士01卷.zip" 
--header "User-Agent: User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:60.0) Gecko/20100101 Firefox/60.0" 
--header "Referer: https://pan.baidu.com/disk/home" 
--header "Cookie: BDUSS=hidden; pcsett=hidden"
 "https://pcs.baidu.com/rest/2.0/pcs/file?method=download&app_id=250528&path=%2F%E6%88%91%E7%9A%84%E8%B5%84%E6%BA%90%2F5T%2F1%2F%E6%BC%AB%E7%94%BB%E4%B9%A6(%E6%97%A5%E6%BC%AB%20%E5%9B%BD%E6%BC%AB%20%E7%BE%8E%E6%BC%AB%20%E6%B8%AF%E5%8F%B0%E6%BC%AB)%2F%E9%A6%99%E6%B8%AF%E5%8F%B0%E6%B9%BE%E6%BC%AB%E7%94%BB%2F%E3%80%90%E5%B7%B2%E5%AE%8C%E7%BB%93%E3%80%91%E9%AD%94%E5%9F%9F%E6%88%98%E5%A3%AB%5B%E7%B1%B3%E5%A5%87%5D%5B%E8%B0%81%E5%9C%A8%E4%B9%8E%E7%89%88%5D%2F%E9%AD%94%E5%9F%9F%E6%88%98%E5%A3%AB01%E5%8D%B7.zip"
```
也失败
![image](https://user-images.githubusercontent.com/6198568/57520063-59efa900-734f-11e9-80d6-5c30af848757.png)

   3)上个月的时候可以下，但是这个月就不行了

**Comment by acgotaku** [comment]
最新版本都  1.0.3了 老版本当然用不了

**Comment by MorosithIi** [comment]
> 最新版本都 1.0.3了 老版本当然用不了

你好 然而我在firefox developer 版用addons装的话就是1.01版本。请问可以更新一下addons吗
