### ISSUE TITLE
0.3.9版本经常导出失败，只提示获取文件信息成功，退回0.3.5正常。

### ISSUE THREAD

**Issue by giveup** [acgotaku/BaiduExporter#66]
firefox 42.0a2 (2015-08-18)

**Comment by XhstormR** [comment]
最新版本为`0.4.0`

**Comment by acgotaku** [comment]
@giveup 你是导出文件夹 还是单个文件? 错误的频率是多少?

**Comment by giveup** [comment]
基本上，文件和文件夹一样。第一次导出会成功，接下来的都是获取文件信息成功。没有下载成功的提示。
https://raw.githubusercontent.com/acgotaku/BaiduExporter/master/firefox/baidu-exporter.xpi 这个地址就是0.3.9的
看了下控制台，有这样的日志：
/       home:273:17
TypeError: file[i].path is undefined      home:797:56

**Comment by acgotaku** [comment]
@giveup 是导出下载的问题 还是 导出RPC的问题? 还是都有问题?

**Comment by giveup** [comment]
@acgotaku 抱歉，没有详细说明。导出下载和导出RPC都一样，都是提示获取文件信息成功。
已经尝试重置插件了，问题依旧。

**Comment by acgotaku** [comment]
@giveup 导出所有文件都是这样么? firefox版本多少? 这个BUG我没得成功复现...

**Comment by giveup** [comment]
@acgotaku 开发者版本（42.0a2 (2015-08-25)）
现在是导出所有文件都只提示获取文件信息成功。不能下载。也就是我只有第一次才能下载，之后无论导出什么文件，都不能下载。已经尝试重启浏览器。按照经验。只能是明天才有第一次能下载（昨天遇到这情况没理他，今天的第一次下载就成功，接着就是一直失败）

**Comment by acgotaku** [comment]
@giveup 这太奇怪了....  我这边一点问题都没有....   你可以看看网络面板
把 http://pan.baidu.com/api/filemetas  开头的请求的 完整链接发给我么??

**Comment by giveup** [comment]
http://pan.baidu.com/api/filemetas?target=["/ALC1150_Patch.txt"]&dlink=1&bdstoken=fbd6b74499b6e051dcc8d190d586f442&channel=chunlei&clienttype=0&web=1

打开后提示如下：{"errno":12,"info":[{"errno":-9}],"request_id":8971927733368184642}

http://pan.baidu.com/api/filemetas?target=[%22/ALC889_Patch.txt%22]&dlink=1&bdstoken=fbd6b74499b6e051dcc8d190d586f442&channel=chunlei&clienttype=0&web=1

提示：{"errno":12,"info":[{"errno":-9}],"request_id":8971937003952900125}

**Comment by acgotaku** [comment]
@giveup URL编码出问题了? 返回的数据明显不对 

http://pan.baidu.com/api/filemetas?target=%5b%22%2fALC1150_Patch.txt%22%5d&dlink=1&bdstoken=fbd6b74499b6e051dcc8d190d586f442&channel=chunlei&clienttype=0&web=1

你换这个试试?
