### ISSUE TITLE
选中文件后，「导出下载」按钮消失

### ISSUE THREAD

**Issue by Wei-Xia** [acgotaku/BaiduExporter#660]
请确保以下几点：

1. 已经阅读过README
2. 尝试安装最新版本插件
3. 尝试清空浏览器缓存
4. 尝试卸载插件后重新安装

发起 Issue 时，请提供：

1. 您下载的内容地址
2. 插件版本号，浏览器版本号，系统版本号
3. 列举出现问题的详细步骤
4. 描述能否复现问题

--------------------------
使用 Chrome 74.0.3729.131 和 Firefox 66.0.5.
插件版本号： v0.8.5

打开百度网盘后，可以正常载入插入，显示「导出下载」按钮，但选中文件后，「导出下载」按钮消失，在 DOM 中也搜不该改按钮的 element。

见视频：

![Screen Recording 2019-05-12 at 11 45 48](https://user-images.githubusercontent.com/9309906/57584694-4148d580-74ac-11e9-94de-b9bb568f512c.gif)

**Comment by acgotaku** [comment]
最新版本都 1.0.3了……

**Comment by Wei-Xia** [comment]
> 最新版本都 1.0.3 了……

在 release （https://github.com/acgotaku/BaiduExporter/releases） 里最新的不是 0.8.5 吗？

**Comment by acgotaku** [comment]
谷歌商店最后的一个Release提供CRX下载，但以后再也不会更新。

需要使用最新版本请自行Github开发者模式载入。


我这不写的清清楚楚！ 老版本肯定有问题啊，要不然我为啥会更新？

**Comment by Wei-Xia** [comment]
@acgotaku  sorry... 明白了，谢谢！

**Comment by acgotaku** [comment]
@Wei-Xia 差点被你气死。。。

**Comment by Wei-Xia** [comment]
@acgotaku  不好意思，习惯去看 release！ 谢谢啦！
