### ISSUE TITLE
没有导出下载选项

### ISSUE THREAD

**Issue by daxinnan** [acgotaku/BaiduExporter#661]
我是在Ubuntu下apt安装的aria2 1.33.1版本，之前在命令行下使用`aria2c --conf-path=~/.aria2/aria2.conf -i xxx.txt`成功批量下载了挺多数据了。
保证在使用网盘助手的时候在终端已经启用了。
使用yaaw测试下载一个png文件也成功了，但是在我的网盘里没有导出下载按钮。

1. 您下载的内容地址 `git clone https://github.com/acgotaku/BaiduExporter.git`
2. 插件版本号 `1.0.3`，浏览器版本号 `Google Chrome版本 74.0.3729.131（正式版本） （64 位）`，
   系统版本号 `Ubuntu 18.04.2 LTS`
3. 列举出现问题的详细步骤
 我昨天git clone的最新版，然后导入release文件夹后在网盘里没有看到`导出下载`选项。
 今天清理了浏览器缓存重新git clone的这个插件并安装，也没有找到。
4. 描述能否复现问题 
![image](https://user-images.githubusercontent.com/26436171/57822811-c3483f80-77c7-11e9-92c6-16fc20711c76.png)

请确保以下几点：

1. 已经阅读过README
2. 尝试安装最新版本插件
3. 尝试清空浏览器缓存
4. 尝试卸载插件后重新安装

发起 Issue 时，请提供：

1. 您下载的内容地址
2. 插件版本号，浏览器版本号，系统版本号
3. 列举出现问题的详细步骤
4. 描述能否复现问题

----------

**不符合上述条件的Issue将被无理由关闭**

**Comment by acgotaku** [comment]
确定装的最新版？ 不是装的其他插件 导致冲突了？

**Comment by acgotaku** [comment]
网址你的隐藏了 我又怎么知道你加载的网址对不对？

**Comment by daxinnan** [comment]
> 网址你的隐藏了 我又怎么知道你加载的网址对不对？

确定装的最新版
![image](https://user-images.githubusercontent.com/26436171/57910902-f0c0e600-78b8-11e9-8d8c-995dbb507ebd.png)
![image](https://user-images.githubusercontent.com/26436171/57910928-06cea680-78b9-11e9-9609-182701b98c1d.png)

**Comment by acgotaku** [comment]
你禁用其他插件试试？

**Comment by DailyShana** [comment]
ex-百度云盘明显有冲突

**Comment by daxinnan** [comment]
> ex-百度云盘明显有冲突

emmm, 我要把油猴里所有插件都在禁了才有效果，然后下载速度并不是很快，网盘里的文件速度大概都在50k左右，所以就没再用了。

**Comment by acgotaku** [comment]
不充钱怎么能变强，插件只是导出。不是破解限速

**Comment by daxinnan** [comment]
> 不充钱怎么能变强，插件只是导出。不是破解限速
是我表达有误，是aria2没有带来这么快的提速，因为在ubuntu上用，可替代的选择并不多，偶尔在命令行用用顶一顶
