### ISSUE TITLE
速度只有100K左右

### ISSUE THREAD

**Issue by hongzai1994** [acgotaku/BaiduExporter#663]
请确保以下几点：

1. 已经阅读过README
2. 尝试安装最新版本插件
3. 尝试清空浏览器缓存
4. 尝试卸载插件后重新安装

发起 Issue 时，请提供：

1. 您下载的内容地址
2. 插件版本号，浏览器版本号，系统版本号
3. 列举出现问题的详细步骤
4. 描述能否复现问题

----------

**不符合上述条件的Issue将被无理由关闭**

**Comment by hongzai1994** [comment]
无论下载什么内容速度只有100K。
插件1.03
浏览器chrome Version 74.0.3729.157 (Official Build) (64-bit)
macOS 10.14.5

**Comment by acgotaku** [comment]
插件的功能只是导出，不是破解限速。
