### ISSUE TITLE
停用插件提示

### ISSUE THREAD

**Issue by RicardoKlose** [acgotaku/BaiduExporter#666]
1. 您下载的内容地址
无

2. 插件版本号，浏览器版本号，系统版本号
插件版本 1.0.3
浏览器版本 chrome 75.0.3770.100
系统版本 windows 10 1903

3. 列举出现问题的详细步骤
由于是使用开发者模式加载已解压插件，每次打开浏览器都会有停用插件提示，之前使用README.md中tips内页面下的策略文件可以解决，上次重新安装插件后插件id似乎已经变了，在白名单内添加新的id也不能阻止弹出停用提示了。并且tips内的页面现在已经无法访问了，貌似是域名无法解析了。

4. 描述能否复现问题
可以

麻烦大神看看

**Comment by acgotaku** [comment]
我记得是组策略的问题，你搜搜 看看有没有类似的文章

**Comment by RicardoKlose** [comment]
> 我记得是组策略的问题，你搜搜 看看有没有类似的文章

我到 [https://support.google.com/chrome/a/answer/187202](https://support.google.com/chrome/a/answer/187202?hl=zh-Hans) 这里下载了最新的策略文件，也重新设置了一下白名单，貌似还是不行。。不知道是不是chrome版本的问题

**Comment by HugoYip** [comment]
可以安装到chrome里面但是无法启用，目前正在尝试chromium

**Comment by acgotaku** [comment]
使用开发者模式就好了
