### ISSUE TITLE
迄今为止，下载速度最快的还是0.9.7

### ISSUE THREAD

**Issue by HenXian** [acgotaku/BaiduExporter#668]
发现新版本从1.0.0开始，百度下载速度都比不上0.9.7版本
PS：我是vip会员。

所以，我迄今还在用0.9.7版本的chrome插件。

请问大侠是否考虑过这个问题？ 有没有办法是最新版也能达到0.9.7 百度vip会员下载速度？

**Comment by acgotaku** [comment]
对 升级之后去掉了一个 API接口，之前找人测试过接口。选了一个快的。

难道选错了？

**Comment by HenXian** [comment]
我实际测试的结果，认为选错了。
能出一个新版本 改回之前的API 接口吗？
或者告知我如何修改源代码

**Comment by acgotaku** [comment]
你可以把下载 快的 下载链接 贴出来 我看看格式么？

慢的也贴出来 这样我也好改进

**Comment by HenXian** [comment]
aria2c -c -s10 -k1M -x16 --enable-rpc=false -o "软件/ubuntu-18.04.3-live-server-amd64.iso" --header "User-Agent: netdisk;5.3.4.5;PC;PC-Windows;5.1.2600;WindowsBaiduYunGuanJia" --header "Referer: http://pan.baidu.com/disk/home" --header "Cookie: BDUSS=EpRVVY0MmcteVpuWlgtblpVTnZ1bEdFVmlHWWRweXBvYnNhaGxKSEhaNmR6MXhkSVFBQUFBJCQAAAAAAAAAAAEAAACH1uo2eHVld3k3MAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAJ1CNV2dQjVdV; pcsett=1567819459-f264a0ec53c0928da896c50f38b98e18" "https://d.pcs.baidu.com/file/c038a031a2b638f8e89d897119f1b7bb?fid=3593652533-250528-607181685565460&rt=pr&sign=FDtAERVCY-DCb740ccc5511e5e8fedcff06b081203-uQeSceopIKjvWl9ww4RuAPWKz1Q%3D&expires=8h&chkv=1&chkbd=1&chkpc=et&dp-logid=5761004685632036789&dp-callid=0&dstime=1567733414&r=655090697"

aria2c -c -s10 -k1M -x16 --enable-rpc=false -o "软件/ubuntu-18.04.3-live-server-amd64.iso" --header "User-Agent: netdisk;6.0.0.12;PC;PC-Windows;10.0.16299;WindowsBaiduYunGuanJia" --header "Referer: https://pan.baidu.com/disk/home" --header "Cookie: BDUSS=EpRVVY0MmcteVpuWlgtblpVTnZ1bEdFVmlHWWRweXBvYnNhaGxKSEhaNmR6MXhkSVFBQUFBJCQAAAAAAAAAAAEAAACH1uo2eHVld3k3MAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAJ1CNV2dQjVdV; pcsett=1567819459-f264a0ec53c0928da896c50f38b98e18" "https://pcs.baidu.com/rest/2.0/pcs/file?method=download&app_id=250528&path=%2F%E8%BD%AF%E4%BB%B6%2Fubuntu-18.04.3-live-server-amd64.iso"

第一个是 0.9.7 生成的下载连接，速度最快可以达到15M左右（我家用的是500M 带宽）
第二个是1.0.3生成的下载连接，速度大概稳定250k以内

**Comment by skywoodlin** [comment]
最近两个星期， 下载的速度变慢了， 下载出错的文件也变多了， 大部分(80%?)都提示“http response header was bad or unexpected”,  即使是成功的下载很慢（总速大概是500k左右， 以前都可以达到满速12M， 百兆宽带）， 正在纳闷为什么呢。。。现在版本是1.0.3， 之前的没有注意， 不知道是不是同一个问题

**Comment by acgotaku** [comment]
非会员 测试  没啥区别 都是下不 下来。。。

**Comment by xxzx01** [comment]
@skywoodlin 你说的原因是百度限制，前段时间下载都出错，基本不能下载。但最近又开放了，每个账户线程5个，每个线程200k

**Comment by HenXian** [comment]
1.0.3版本无法下载，0.9.7版本可以下载是一个问题。下载速度没0.9.7快是第二个问题。两个问题都存在。

**Comment by acgotaku** [comment]
会员的情况是一个慢 一个快 但非会员 都是很慢 而且经常下载失败

**Comment by HenXian** [comment]
> 会员的情况是一个慢 一个快 但非会员 都是很慢 而且经常下载失败

大神，0.9.7 版，有没有已知bug或者可以做优化的可能？
如果有，请在这个版本的API基础上更新一下吧，（虽然0.9.7用到现在，对我来说一直很稳定高效）

**Comment by acgotaku** [comment]
本来就没有bug，而且我现在非会员 没法测试 就不乱改了
