### ISSUE TITLE
rpc 保存问题

### ISSUE THREAD

**Issue by opalhair** [acgotaku/BaiduExporter#67]
请问在百度云里面设置 rpc 后，
如果重新启动 chrome，
rpc 设置就会重置，
必须要每次都重新设置，
是我个人的问题吗？
我用的是 token:secret 的方法。

**Comment by acgotaku** [comment]
@opalhair 重启浏览器正常来说 RPC设置不会重置的 你试试修改其它设置是否也会重置呢?

**Comment by opalhair** [comment]
不知道什么原因，重启浏览器就重置 http://localhost:6800/jsonrpc ，
系统是：ubuntu
会不会跟操作系统有关？

**Comment by acgotaku** [comment]
@opalhair 用的浏览器是 chrome还是 FF?

**Comment by opalhair** [comment]
找到原因了，是在 ubuntu 里不能保存，在 windows 没问题。
