### ISSUE TITLE
百度盘插件ARIA2下载失败

### ISSUE THREAD

**Issue by chenyz1984** [acgotaku/BaiduExporter#670]
请确保以下几点：
1. 已经阅读过README
2. 尝试安装最新版本插件
3. 尝试清空浏览器缓存
4. 尝试卸载插件后重新安装

发起 Issue 时，请提供：

1. 您下载的内容地址
https://d.pcs.baidu.com/file/8ab1967f5ae992c4266db6b1992346b4?fid=120703189-250528-634662993829072&dstime=1573031229&rt=sh&sign=FDtAERVY-DCb740ccc5511e5e8fedcff06b081203-EmnHrJpslEgm7Zs4Oo3hUyMFMiI%3D&expires=8h&chkv=1&chkbd=0&chkpc=et&dp-logid=7183125883040391730&dp-callid=0&shareid=2164132386&r=453890178
2. 插件版本号，浏览器版本号，系统版本号
插件版本：1.0.1
浏览器版本：火狐70.0.1 (64 位)
系统版本：ARIA2版本为1.34.0
操作系统版本：Win7旗舰版
3. 列举出现问题的详细步骤
通过插件生成的链接地址，添加到ARIA2中，下载失败。
直接在插件中设置ARIA2，测试链接也无法成功。但是ARIA2本身的功能是正常的。
4. 描述能否复现问题：能
----------

**不符合上述条件的Issue将被无理由关闭**

**Comment by John-Smith-SG** [comment]
https://greasyfork.org/en/scripts/378301-%E7%BD%91%E7%9B%98%E5%8A%A9%E6%89%8B
https://chrome.google.com/webstore/detail/aria2-manager/lbfekjdfefiipnbkpgldhicajcoldcmb
目前这两个配合起来能满速，chrome扩展要手动设置右键调用，脚本可以改应用ID为778750

**Comment by yukiloh** [comment]
> https://greasyfork.org/en/scripts/378301-%E7%BD%91%E7%9B%98%E5%8A%A9%E6%89%8B
> https://chrome.google.com/webstore/detail/aria2-manager/lbfekjdfefiipnbkpgldhicajcoldcmb
> 目前这两个配合起来能满速，chrome扩展要手动设置右键调用，脚本可以改应用ID为778750

请问最后的ID是什么意思？貌似有许多备选

**Comment by v2ray233** [comment]
我在安卓手机上可以满速下载

**Comment by acgotaku** [comment]
火狐已经停止维护，请看 README 现在版本已经 1.0.4了
