### ISSUE TITLE
disabled by google

### ISSUE THREAD

**Issue by dave-yxw** [acgotaku/BaiduExporter#673]
请确保以下几点：

1. 已经阅读过README
2. 尝试安装最新版本插件
3. 尝试清空浏览器缓存
4. 尝试卸载插件后重新安装

发起 Issue 时，请提供：

1. 您下载的内容地址
2. 插件版本号，浏览器版本号，系统版本号
百度网盘助手1.0.3， chrome 76.0.3809.132（正式版本） （64 位），win 7
3. 列举出现问题的详细步骤
按git:/readme的步骤安装crx插件。然后不能开启，原因是该插件未在chrome 商店发布。
https://support.google.com/chrome_webstore/answer/2811969?visit_id=637091376379910777-1042326179&p=ui_remove_non_cws_extensions&hl=zh-Hans&rd=2

4. 描述能否复现问题
能
----------

**不符合上述条件的Issue将被无理由关闭**

**Comment by acgotaku** [comment]
可以使用 开发者模式 载入 Release文件夹下的插件
