### ISSUE TITLE
关于使用aria2和导出插件的一些问题

### ISSUE THREAD

**Issue by hangitfan** [acgotaku/BaiduExporter#69]
今天抽空完成了试用下载了百度云里的东东,有几个问题想请教下po主,如果有问题不太了解可以不用答复,多少也是配置使用成功了:
最重要的一个,为什么火狐的xpi下载安装后,百度界面上看不到按钮,我换了谷歌就可以...主力是火狐34.0.5,谷歌是36,不过两个都是portable的项目....最后是在谷歌下导出的任务,别人有这样的问题吗?
1.aria2是基于什么原理可以达到比较高的下载速度?是因为UA伪装成百度管家吗?
2.这个项目主页上的usage好像没有什么用,我一开始使用不了以为这个少了做这个操作,但实在想不到windows下面这个要怎么跑,最后也没有用到   是不是拿掉好一点啊?- -,
3.项目主页上install部分的火狐xpi安装后在插件管理中心看到的版本是0.3.9,但是在release下面火狐的最新xpi安装后是0.3.5的...这两个有区别吗?
4.在yaaw,插件和配置文件里都有一些公有配置,比如user agent,下载路径,导出的时候生效的优先级是怎么样的?

最后多谢po主的分享,希望未来有更多实用的功能加入,比如复制链接,集成管理界面的功能..............

**Comment by acgotaku** [comment]
@hangitfan 这个项目主要用在谷歌浏览器  FF是移植过去的 所以优先级不是很高

aria2c的下载速度快是因为伪装UA 和 aria2c这个软件本身专注于下载 

所以能达到较高的速度
2. aria2c主要用于 linux或者mac上的使用 win下也可以的 具体看这个: http://bbs.kafan.cn/thread-1686205-1-1.html

3. 最新版一般不是很稳定 一段时间没有人反馈 BUG 我才会在  release上进行更新

4.优先级应该是  百度网盘的最高

这个软件只专注导出下载功能 并不打算集成其它管理界面 UNIX哲学 专注做好一件事

具体看投票 :  https://plus.google.com/u/0/+%E9%9B%AA%E6%9C%88%E7%A7%8B%E6%B0%B4%E9%85%B1/posts/5UWu8hzH864

**Comment by hangitfan** [comment]
@acgotaku 嗯,kafan那个帖子我也学习了下,后来从其他地方找了带入口的软件包来用的:http://aria2c.com/usage.html
火狐的问题也有可能是我版本的锅,以后有更新了再试试
总之这些都是一些小问题,最终都可以无视:)
