### ISSUE TITLE
插件安装失败（开发者模式）。报错：未能成功加载扩展程序 ；文件 D:\······\······\······\BaiduExporter 错误；清单文件缺失或不可读取，无法加载清单。

### ISSUE THREAD

**Issue by Hugo342523** [acgotaku/BaiduExporter#692]
请确保以下几点：

1. 已经阅读过README
2. 尝试安装最新版本插件
3. 尝试清空浏览器缓存
4. 尝试卸载插件后重新安装

发起 Issue 时，请提供：

1. 您下载的内容地址
2. 插件版本号，浏览器版本号，系统版本号
3. 列举出现问题的详细步骤
4. 描述能否复现问题

----------

**不符合上述条件的Issue将被无理由关闭**

**Comment by acgotaku** [comment]
....请使用Release文件夹

**Comment by lingzhuxin** [comment]
> ....请使用Release文件夹

所以这个版本一直是1.0.4没有变的吗？只是看到了crx更新了又不能直接托进去安装，就很尴尬

**Comment by acgotaku** [comment]
对， 没有升级版本号的必要。 不过现在百度封了大文件下载 所以插件已经没啥用处了
