### ISSUE TITLE
设置了 rpc-secret 之后无法使用 rpc 功能

### ISSUE THREAD

**Issue by pandarison** [acgotaku/BaiduExporter#70]
aria2 version 1.18.8

aria2c --enable-rpc --rpc-listen-all --rpc-secret=xxxx --save-session=/xx/.aria2/session.txt --input-file=/xx/.aria2/session.txt -x16 -s16 -k10M --dir=/var/xxx

设置中地址填的 http://token:xxxx@192.168.0.xxx:6800/jsonrpc

也尝试过设置 --rpc-user  --rpc-passwd 组合, 也无法使用，显示“下载失败，是不是没有开启aria2”

**Comment by pandarison** [comment]
参考了 #44 
发现必须添加 --rpc-allow-origin-all=true 才可以. 好奇怪的问题, 某个 web ui 不加这个选项也是可以使用的.

**Comment by acgotaku** [comment]
@pandarison 这个参数是决定 aria2c 的功能的吧 和 web ui 应该没关系才对

**Comment by pandarison** [comment]
按理说如果没有加那个参数时 web UI 能添加下载任务，那么本插件应该也能才对。也许这个参数限制了 identity@host 这种验证方式的origin，建议在readme中加提醒一下这个参数

**Comment by acgotaku** [comment]
@pandarison 应该说 web ui 里面的 origin是 空 或者本地  但是 这个插件 浏览器可能会自动加上 origin

**Comment by slime7** [comment]
学到了，我上次也是参数都传过去了但是服务器返回500，后来就放弃了
