### ISSUE TITLE
chrome dev不出现导出下载按钮

### ISSUE THREAD

**Issue by cuijingqi** [acgotaku/BaiduExporter#700]
为了躲避打开时的"请使用........."弹框,我尝试了chrome dev,如此问题得到了解决,进入页面时提示初始化成功,但是不再出现导出下载相关按钮,win1903,我仅仅通过开发者加载chrome文件夹,是否是我做错了那里.

**Comment by cuijingqi** [comment]
boot.js?t=1578364180271:1 Service worker active
nj.baidupcs.com/monitor.jpg?xcode=1a81b0bbd448fc36f65202d7e8f159404c932f26aaa77f9c&t=15790086311579008632009:1 GET https://nj.baidupcs.com/monitor.jpg?xcode=1a81b0bbd448fc36f65202d7e8f159404c932f26aaa77f9c&t=15790086311579008632009 net::ERR_NAME_NOT_RESOLVED
Image (async)
o._startTesting @ pcsDownloadUtil.js?t=1578364180271:1
n.onload @ pcsDownloadUtil.js?t=1578364180271:1
load (async)
o._startTesting @ pcsDownloadUtil.js?t=1578364180271:1
success @ pcsDownloadUtil.js?t=1578364180271:1
l @ base.js:4
fireWith @ base.js:4
r @ base.js:5
t.onload.t.onreadystatechange @ base.js:5
load (async)
send @ base.js:5
ajax @ base.js:5
o._getHostList @ pcsDownloadUtil.js?t=1578364180271:1
o.initPcsDownloadCdnConnectivity @ pcsDownloadUtil.js?t=1578364180271:1
(anonymous) @ boot.js?t=1578364180271:1
(anonymous) @ boot.js?t=1578364180271:1
c @ mod.js?t=1578364180271:1
define @ mod.js?t=1578364180271:1
(anonymous) @ pcsDownloadUtil.js?t=1578364180271:1
mod.js?t=1578364180271:1 Uncaught Error: Cannot find module `common:widget/moveSaveDialog/moveSaveDialog.js`
    at require (mod.js?t=1578364180271:1)
    at convert.js:307
    at convert.js:347
    at convert.js:348


我发现这个,是否是有关联

**Comment by cuijingqi** [comment]
d

**Comment by acgotaku** [comment]
请加载 release 文件夹。。。
