### ISSUE TITLE
如果有百度会员，有没有办法让aria2加速呢？

### ISSUE THREAD

**Issue by lifangquan** [acgotaku/BaiduExporter#704]
下载的内容地址
https://pcs.baidu.com/rest/2.0/pcs/file?method=download&app_id=250528&path=%2FThe.Locked.Room.2014.1080p.BluRay.x264-WiKi%2FThe.Locked.Room.2014.1080p.BluRay.x264-WiKi.mkv
插件版本号
1.0.4
浏览器版本号
79.0.3945.130
系统版本号
Win10家庭中文版 1909
 列举出现问题的详细步骤
正常下载
描述能否复现问题
下载速度较慢，有会员的话，能不能在插件里用上？

**Comment by acgotaku** [comment]
速度应该有提升 但是线程是有限制的
