### ISSUE TITLE
0.4.1版本处理文件名中特殊字符出现错误

### ISSUE THREAD

**Issue by ProjectAmber** [acgotaku/BaiduExporter#71]
以debian-7.8.0-amd64-netinst.iso为例，生成的下载链接为：
aria2c -c -s10 -k1M -x10 -o debian\\-7\\.8\\.0\\-amd64\\-netinst\\.iso（略）

Windows平台下的aria2c会错误的建立一系列文件夹：
C:\Users\***\Downloads\debian\\-7\\.8\\.0\\-amd64\\-netinst\\.iso。

之前版本没有这个问题，非常好用，麻烦您抽空看下。

**Comment by acgotaku** [comment]
@ZachCheung  貌似这个转义正好是Win下面的文件夹符号...
