### ISSUE TITLE
1.0.4版本， 反而比1.0 .2 版本下载速度慢。

### ISSUE THREAD

**Issue by hawkinchina** [acgotaku/BaiduExporter#727]
1.0.4版本， 反而比1.0 .2 版本下载速度慢。 
1.04版本，测试了一下， 反而比chrome直接下载还慢。。

**Comment by acgotaku** [comment]
1.0.2 和 1.0.4 都是用的同一个API啊

**Comment by hawkinchina** [comment]
我在macos上实际测试的结果。。正常chrome下载70多k， 如果用1.0.4的话，下载29k左右， 换成1.02.下载的话，120k左右。。 这个是实际测试的情况呀，：）， 所有我就用回了1.0.2了。。

**Comment by hawkinchina** [comment]
感觉难以理解呀。。

**Comment by BeiBe1** [comment]
我的也是更新到最新版以后 速度变慢了，以前慢速度现在都是几十k，不知道是资源的问题还是什么其他的问题。
