### ISSUE TITLE
虽然在这里提不是很合适,但实在找不到地方了..求 360云盘 支持...

### ISSUE THREAD

**Issue by tofuliang** [acgotaku/BaiduExporter#73]

**Comment by acgotaku** [comment]
........   我不用360云盘啊.....

**Comment by cwbsw** [comment]
@tofuliang 360云盘没有限速的样子，直接浏览器可以多线程，只不过不能批量下载。

**Comment by tofuliang** [comment]
就是想要批量下载....

cwbsw <notifications@github.com>于2015年10月5日周一 下午12:13写道：

**Comment by acgotaku** [comment]
暂时没有这个开发的计划....
