### ISSUE TITLE
最新版无法插入到Chrome，Chrome版本为 80.0.3987.149

### ISSUE THREAD

**Issue by BeiBe1** [acgotaku/BaiduExporter#734]
https://github.com/acgotaku/BaiduExporter/tree/master 下载的最新版本，把原来的插件直接删了，按照步骤再添加新的就会显示 无法为内容脚本加载 JavaScript“js/start.js”。

**Comment by acgotaku** [comment]
你是载入的 release文件夹么？

**Comment by UVJkiNTQ** [comment]
同样的问题。
![sc](https://user-images.githubusercontent.com/12570945/77243207-8c8e5180-6c42-11ea-84ea-7439301af18e.png)

**Comment by BeiBe1** [comment]
> 你是载入的 release文件夹么？

是的

**Comment by BeiBe1** [comment]
> 你是载入的 release文件夹么？

直接拉crx和加载文件夹都是同样的报错。

**Comment by UVJkiNTQ** [comment]
Same error.
![sc](https://user-images.githubusercontent.com/12570945/77243460-2d7e0c00-6c45-11ea-9058-bdb7120dc999.png)

**Comment by acgotaku** [comment]
已解决，请再拉下 最新代码

**Comment by BeiBe1** [comment]
谢了，我去试试

**Comment by BeiBe1** [comment]
> 已解决，请再拉下 最新代码

已经可以载入插件了
