### ISSUE TITLE
Speed Limit

### ISSUE THREAD

**Issue by typcn** [acgotaku/BaiduExporter#74]
Baidu seems limited download speed at 200KB/s

**Comment by acgotaku** [comment]
you sure? Please check your UA is latest.

**Comment by typcn** [comment]
Oh , just change user-agent from 5.2.x to 5.3.x

**Comment by acgotaku** [comment]
@typcn resolved?

**Comment by typcn** [comment]
Yes , about 2.5MB/S
![image](https://cloud.githubusercontent.com/assets/8022103/10016056/cf4a0fd8-6156-11e5-95f1-1ff6c1e999c9.png)
