### ISSUE TITLE
文件夹打包下载速度会很慢

### ISSUE THREAD

**Issue by nujabse** [acgotaku/BaiduExporter#75]
勾选“导出设置”中的“文件夹打包下载”之后，批量下载多个文件成一个zip文件，速度会很慢，尝试了修改UA也不行。

**Comment by acgotaku** [comment]
@nujabse 这个功能基本残废了  是百度自己服务器的问题 无法修复 目前还是选择非打包下载

**Comment by nujabse** [comment]
感谢提醒！
