### ISSUE TITLE
给context menu加入开关选项

### ISSUE THREAD

**Issue by jimmyxu** [acgotaku/BaiduExporter#77]
并不是很想在任何链接上都看到ARIA2 RPC……

**Comment by acgotaku** [comment]
好的 等我更新~

**Comment by e788b1** [comment]
[chrome-aria2-integration](https://github.com/robbielj/chrome-aria2-integration)

**Comment by acgotaku** [comment]
@jimmyxu 已更新

**Comment by jimmyxu** [comment]
赞/
