### ISSUE TITLE
有计划支持 Safari 吗

### ISSUE THREAD

**Issue by cloverstd** [acgotaku/BaiduExporter#78]

**Comment by acgotaku** [comment]
@Cee 出来~

**Comment by cloverstd** [comment]
@acgotaku 
我正在以 Chrome 版的为基础，尝试改到 Safari 能用，努力 ing。

最近把主力浏览器换到了 Safari

**Comment by Cee** [comment]
@cloverstd I'm working now.
If you can get the cookie pool, and this will support Safari.

**Comment by cloverstd** [comment]
@Cee Safari 是没办法像 `chrome.cookies` 一样获取目标页面的`Cookies`吗

**Comment by acgotaku** [comment]
@Cee  @cloverstd 我忘了说 最新的 API 貌似不用 cookies就可以下载喽

**Comment by Cee** [comment]
@acgotaku 好我下午看一下～
