### ISSUE TITLE
提交 Firefox 插件到 AMO 以通过签名验证

### ISSUE THREAD

**Issue by CzBiX** [acgotaku/BaiduExporter#79]
Firefox 将要实行强制签名校验，参考 [Mozilla Wiki](https://wiki.mozilla.org/Add-ons/Extension_Signing)。

> Firefox 40-42: Firefox warns about signatures but doesn't enforce them.
> Firefox 43: Firefox will have a preference that allows signature enforcement to be disabled (xpinstall.signatures.required in about:config).
> Firefox 44: Release and Beta versions of Firefox will not allow unsigned extensions to be installed, with no override.

建议提交到 AMO 以通过签名验证，还能提供自动升级的功能。

**Comment by acgotaku** [comment]
@CzBiX 这个我知道的 但是FF说我的代码不规范 他们那套扩展开发机制 实在是不能忍
然后就把我的下架了....
