### ISSUE TITLE
能否得到前辈推荐？

### ISSUE THREAD

**Issue by sunzhaoyang** [acgotaku/BaiduExporter#80]
你好~我之前在用BaiduExporter下载的时候，经常会遇到百度链接失效的问题。所以写了个工具来自动刷新。能否得到前辈推荐？
https://github.com/sunzhaoyang/BaiduAria2Resume

**Comment by acgotaku** [comment]
@sunzhaoyang 是金子就一定会发光啊～  别人要是有需求的话 就介绍下是了

**Comment by sunzhaoyang** [comment]
多谢啦~
