### ISSUE TITLE
批量转存产生大量重名空文件夹

### ISSUE THREAD

**Issue by Explorare** [acgotaku/BaiduExporter#82]
在 4503300fd21cc34fc0165d2cef5c26c80dc936e2 的改动后出现了此问题。

批量转存 [此资源](http://yun.baidu.com/share/link?shareid=2981703177&uk=2214641459) 会出现 `获取List失败` 的问题，转存目录下回产生大量重名的文件夹。

已设定 `time=1000`，并保存重新加载，但看来没有生效。

另外顺便给测试账号领一下 [这个](http://yun.baidu.com/1t) 福利吧，我手边没有智能机。

**Comment by acgotaku** [comment]
你这个 没有主目录就麻烦了 会导致在 一级目录下产生大量目录

**Comment by Explorare** [comment]
那能否默认 `转存目录` 为某个特定目录呢？比如新建一个`BaiduExporter`目录。

**Comment by acgotaku** [comment]
@Explorare 这个代码 太乱了 最近在考虑重构....

**Comment by Explorare** [comment]
噫，兹瓷

**Comment by Cee** [comment]
@acgotaku 不能更加兹瓷了...

**Comment by acgotaku** [comment]
@Explorare 重构结束你 你试用下 我这边测试多了就让我 输入验证码了....

**Comment by Explorare** [comment]
了解

**Comment by Explorare** [comment]
运行 2s 之后就开始弹出验证窗口了，能否默认将操作时间间隔设定为 10s 以规避检测呢？

**Comment by acgotaku** [comment]
@Explorare 你可以先手动设置成 10s尝试下效果啊 如果10s一次请求的话 那你这转存大量文件也太花时间了

**Comment by Explorare** [comment]
或者说，如果这个插件能够捕获验证窗口，记录保存成功和失败的任务，一段时间后自动重试继续转存，只要能完成转存，慢一些也无所谓。

**Comment by acgotaku** [comment]
@Explorare  这个验证码 我实在是难搞啊 出了验证码 不知道得等多久

**Comment by Explorare** [comment]
那或者用 OCR 模块直接填入算了，这个验证码并没有什么干扰

**Comment by acgotaku** [comment]
@Explorare  OCR模块 js实现的我还没找到...

**Comment by acgotaku** [comment]
@Explorare 而且不能保证100%识别 要不然就是死循环

**Comment by Explorare** [comment]
唔，看来最好的方法还是直接一键下载再转存？

**Comment by acgotaku** [comment]
@Explorare 它这个验证码 导致我根本没法进行大量测试 所以很难搞

**Comment by Explorare** [comment]
万恶的百度啊

**Comment by acgotaku** [comment]
@Explorare 我现在能做到也就这样了  现在可以多次转存了 重复的不会生成多余文件夹和多次保存

**Comment by Explorare** [comment]
那么如果我转存时遇到验证码，过了一会重新转存时，之前已经保存过的文件是否会重新计数然后触发验证呢？

**Comment by acgotaku** [comment]
验证码触发是因为你请求频繁 不是固定文件触发的

**Comment by Explorare** [comment]
不知道百度对频繁的定义是什么，一定时间内的操作数？还是每次操作间隔的时间呢？

**Comment by acgotaku** [comment]
我也不知道啊.....

**Comment by Explorare** [comment]
总之多谢了，我再去试试合适的时间间隔。

**Comment by acgotaku** [comment]
我去写作业了....连续写了3天这个代码 作业要 deadline了  (bgm38)

**Comment by Explorare** [comment]
辛苦了

**Comment by XhstormR** [comment]
貌似是频繁下载同一个文件超过一定次数后就会触发验证码。

**Comment by acgotaku** [comment]
@XhstormR 不是吧 我现在下载任何分享文件都要验证码...

**Comment by XhstormR** [comment]
@acgotaku 触发之后就会下载任何分享文件都要验证码。。。

**Comment by acgotaku** [comment]
@XhstormR 触发之前我也只不过是遍历文件夹而已... 应该没重复才对

**Comment by acgotaku** [comment]
@Explorare 新版本更新了 不会触发 验证码了 但是5千次请求 还是有10-20次失败...

**Comment by Explorare** [comment]
Wow, amazing! 明天我测试一下。
