### ISSUE TITLE
现在百度云封杀很厉害，能不能提供一个新的Useragent，或许能破解下载速度。

### ISSUE THREAD

**Issue by Chigogo** [acgotaku/BaiduExporter#84]
默认的速度是几kB/s，太慢了。求新的Useragent 设置~~

**Comment by giveup** [comment]
似乎没用，已经不单单靠ua限速了。
http://pan.baidu.com/download#pan 这里是百度云客户端，可以自己随便下载东西然后用Wireshark嗅探流量。

**Comment by acgotaku** [comment]
@Chigogo  netdisk;5.3.4;PC;PC-Windows;6.2.9200;WindowsBaiduYunGuanJia

这个可以达到 400k的样子 你试试 新版本已经更新了

**Comment by Chigogo** [comment]
@acgotaku 感谢作者大大~~么么哒

**Comment by Chigogo** [comment]
@acgotaku 这个agent 也失效了。百度云估计以后不能好好玩耍了。作者大大现在还用这个下载吗？

**Comment by acgotaku** [comment]
@Chigogo 我用着还凑合吧 现在国内环境水深火热啊....

**Comment by Chigogo** [comment]
@acgotaku 你在歪过吗？

**Comment by acgotaku** [comment]
@Chigogo yes

**Comment by Chigogo** [comment]
@acgotaku 我俩网络环境不一样，估计国外流量没国内凶猛，所以百度云暂时没封闭歪过IP，另外一个，你用的OS X还是Windows啊？

PS：作者大大什么专业的？

**Comment by acgotaku** [comment]
@Chigogo 我用的 ArchLinux 计算机专业啊 很明显

**Comment by Chigogo** [comment]
百度自家的云同步盘，能到达200k左右的速度~~

果然高级……美帝？求加社交帐号~

**Comment by acgotaku** [comment]
@Chigogo 不在美国 在日本.... https://twitter.com/acgotaku311

**Comment by acgotaku** [comment]
@Chigogo 自己网盘确实限速了 但是 共享的文件还是没限速 具体细节还有待研究

**Comment by Chigogo** [comment]
没事啦，基本放弃百度了。115还行的。

**Comment by acgotaku** [comment]
@Chigogo 哈哈哈 限速我已经突破了  我基本放弃115了...

**Comment by Chigogo** [comment]
@acgotaku 来来来，分享一下经验

**Comment by acgotaku** [comment]
@Chigogo 我就是抓包看看新的UA是啥就完事了

**Comment by Chigogo** [comment]
@acgotaku 楼主大大敢不敢在插件里面加一个功能，就更新的UA，会被Chrome 插件自动获取。哈哈哈你的更新，惠及天下~

**Comment by acgotaku** [comment]
@Chigogo 重置一下也没啥 自动更新懒得搞了 你只要不保存 默认永远都是最新的配置

**Comment by Chigogo** [comment]
@acgotaku 你已经加入这个设定啦？。。。插件会自动使用最新的Agent？

**Comment by acgotaku** [comment]
@Chigogo 只要你使用的全部是默认设置就会自动更新 如果保存了 不好替换

**Comment by Chigogo** [comment]
懂了。不过我保存过一次…………重置了

**Comment by Chigogo** [comment]
@acgotaku 考虑写一个TamperMonkey 的脚本吗？

**Comment by acgotaku** [comment]
@Chigogo 不考虑 这个插件一开始写的时候就只是脚本 后来脚本满足不了需求才变成扩展的

**Comment by Chigogo** [comment]
@acgotaku Thanks
