### ISSUE TITLE
Safari版无法导出下载，只提示获取文件信息成功。

### ISSUE THREAD

**Issue by giveup** [acgotaku/BaiduExporter#85]
查看console，有如下错误：
TypeError: undefined is not an object (evaluating 'safari.self.tab.dispatchMessage')
send_focus
（匿名函数）

86TypeError: undefined is not an object (evaluating 'file[i].path.slice')
（匿名函数）home:796:85
dall_730f316.js:2:14680
fireWithall_730f316.js:2:15435
fireall_730f316.js:2:15481
onreadystatechangehome:39
－－－
其实firefox也有这个问题，之前#66 也说过了，后面我给忘了没有继续反馈...

**Comment by acgotaku** [comment]
@Cee Safari不是我开发的...  Firefox因为官方不支持非签名应用  开发停滞中....

**Comment by Cee** [comment]
@giveup 能给出具体下载了什么问题吗？

**Comment by giveup** [comment]
@Cee 无法导出下载，任意文件都是。只提示获取文件信息成功。

**Comment by Cee** [comment]
@giveup 具体的 Safari Version 和你装的插件列表。

**Comment by giveup** [comment]
@Cee 
Safari版本 9.0.1 (11601.2.7.2)
lastpass
clicktopluginchina
tampermonkey
ublock
imagus
baiduexporter

**Comment by Cee** [comment]
@giveup 能试着先把其他的禁用后看一下能否解决问题？

**Comment by giveup** [comment]
@Cee 还是无法下载。
错误日至：
TypeError: undefined is not an object (evaluating 'file[i].path.slice')
（匿名函数）home:796:85
dall_730f316.js:2:14680
fireWithall_730f316.js:2:15435
fireall_730f316.js:2:15481
onreadystatechangehome:39

**Comment by giveup** [comment]
@Cee 同学，还修吗...?

**Comment by Cee** [comment]
@giveup 我这边无法复现该问题...

**Comment by acgotaku** [comment]
@giveup 先用Chrome版本吧!

**Comment by giveup** [comment]
@Cee  0.53版可以导出，但是只能在全部文件分类下导出，其他分类下导出提示获取File失败!。
TypeError: undefined is not an object (evaluating 'file[i].path.slice')
column: 77
line: 135
message: "undefined is not an object (evaluating 'file[i].path.slice')"
sourceURL: "safari-extension://moe.Cee.BaiduExporter-BJJYLFU3B7/786ed60/home.js"
stack: "safari-extension://moe.Cee.BaiduExporter-BJJYLFU3B7/786ed60/home.js:135:77↵promiseReactionJob@[native code]"
“TypeError”原型

**Comment by Cee** [comment]
@giveup 主要是给了问题之后...能给个具体的地址我看一下吗？

**Comment by giveup** [comment]
@Cee 没有特定针对哪个地址的下载，是其他分类下（如视频）全都不能下载。

**Comment by acgotaku** [comment]
@giveup 这个功能是多余的 不支持 未来也不打算支持 只支持 全部文件夹下载 不支持分类下的下载
