### ISSUE TITLE
chrome连接不上

### ISSUE THREAD

**Issue by big-F** [acgotaku/BaiduExporter#859]
在其他Issues看过这个问题，但是没找到解决方法。

RPC地址为 http://token:333@localhost:6800/jsonrpc
http://binux.github.io/yaaw/demo/ 这里可以连接的上

开发者模式的背景页里，看到参数
{"jsonrpc":"2.0","method":"aria2.getVersion","id":1,"params":[]}
params这里为空，应该是导致连接不上的原因，请教如何解决？
chrome 85.0.4183.121 BaiduExporter 1.0.2到1.0.4都一样的问题

**Comment by big-F** [comment]
已经关闭所有chrome拓展，测试也不行

**Comment by acgotaku** [comment]
https://github.com/acgotaku/BaiduExporter/blob/master/BaiduExporter.crx

连不上 就用别的吧， 这个项目基本没法用了
