### ISSUE TITLE
在部分分享页面“获取List失败”

### ISSUE THREAD

**Issue by AlwaysWithYou** [acgotaku/BaiduExporter#86]
我在[这个分享页面](http://yun.baidu.com/share/link?shareid=3093046825&uk=1343982186&third=0&dir=%2F%E7%94%9F%E7%90%86%E5%AD%A6%E5%AE%9E%E9%AA%8C%2FPowerLAB%20Install(Ch)%2FLabChart%207.3.3&page=1&adapt=pc&from=wapforcetoweb#path=%252F%25E7%2594%259F%25E7%2590%2586%25E5%25AD%25A6%25E5%25AE%259E%25E9%25AA%258C&render-type=list-view)勾选文件夹之后点击“导出下载”会出现“获取List失败”，但同页面的图片不会，试了一下在别的分享里勾选文件夹，也没有发现出现同样状况的，Chrome 和 Firefox 中都是如此。

还有像在[这种分享页面](http://yun.baidu.com/pcloud/album/info?uk=2369412280&album_id=1170534193581907605)选中文件后不会出现”导出下载“按钮。

另外，我看到在别的 issue 中有提到Firefox版暂停开发……目前不加签名只会被提示未被验证，仍然可以继续使用，而且有些用户是用第三方编译的比如 pcxFirefox，去除了签名验证，所以还是非常希望 Firefox 版能够继续开发！谢谢！！

**Comment by acgotaku** [comment]
@AlwaysWithYou 最近我会重构整个扩展的...

**Comment by AlwaysWithYou** [comment]
@acgotaku 好吧……期待新版的到来！

**Comment by acgotaku** [comment]
@AlwaysWithYou 获取失败的情况 新版本应该不会有了  还有那个分享页面用的是完全不同的API
并且不 常见 最近没有添加这个的计划 要是经常有需要的话 我再考虑加上

**Comment by AlwaysWithYou** [comment]
@acgotaku 虽然我觉得这种分享的页面也不少…不过没时间就算了，有时间加上的话当然更好啦。这个扩展已经给我带来了极大的方便！加不加都非常感谢！！：）

**Comment by acgotaku** [comment]
@AlwaysWithYou  0.5.5版本已经更新了! 支持了! 快试用 反馈BUG!

**Comment by AlwaysWithYou** [comment]
@acgotaku 好的，现在使用最新版还没发现有什么问题，遇到后会来反馈的

**Comment by acgotaku** [comment]
@AlwaysWithYou  那你倒是关了 这个 issue啊!
