### ISSUE TITLE
无法下载，报错“还没获取到cookies哦，请稍等”，chrome下插件管理界面显示插件Error

### ISSUE THREAD

**Issue by linxucc** [acgotaku/BaiduExporter#864]
无法下载，一直提示“还没获取到cookies哦，请稍等”。

chrome的插件管理界面里显示Error，点开后显示

Access to fetch at 'https://passport.baidu.com/v3/login/api/auth/?tpl=tb&jump=&return_type=3&u=https%3A%2F%2Ftieba.baidu.com%2Findex.html' (redirected from 'https://tieba.baidu.com/') from origin 'chrome-extension://xxxxxxxxx' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

不知是否有关，大佬有空还请修复，感谢～～

**Comment by acgotaku** [comment]
别用 SVIP模式

**Comment by agateriver** [comment]
不用SVIP也报错

**Comment by linxucc** [comment]
对，如楼上，因为不是svip所以没有启用这个也报错

**Comment by g6ai** [comment]
同样问题，在更新了Chrome之后出现。我是SVIP，试了开启或关闭SVIP选项，以及在headers里添加cookies，均无法解决

**Comment by linxucc** [comment]
再补充一下，我用Firefox也是一样的情况……

**Comment by acgotaku** [comment]
可能是更新了 cookie规则 我看看吧

**Comment by acgotaku** [comment]
开启这个 chrome://flags/#cors-for-content-scripts

**Comment by acgotaku** [comment]
https://www.chromium.org/Home/chromium-security/extension-content-script-fetches

**Comment by g6ai** [comment]
感谢更新！我把 chrome://flags/#cors-for-content-scripts 设置成了Disabled，使用昨天的更新能把下载任务加到aria2 rpc了，但是会报错HTTP response header was bad or unexpected。试了不同文件，有时候在下载很小的文件的时候能成功，大部分文件会报错。

**Comment by acgotaku** [comment]
@g6ai 设置成 enbale 才能使用 SVIP模式， 不过这个模式目前需要定制版的 aria2c 所以一般人还是不要用了

**Comment by linxucc** [comment]
感谢大佬！大佬威武。。。
