### ISSUE TITLE
右键下载没有了  

### ISSUE THREAD

**Issue by maltose1993** [acgotaku/BaiduExporter#87]
今天更新后右键下载没有了 设置界面测试是否连上的也没有了

**Comment by gnwzkd** [comment]
右键添加任务推荐Aria2c Integration扩展，能够捕捉请求，替代Chrome自带下载。

**Comment by acgotaku** [comment]
@maltose1993 那个功能删掉了 想要的话 换这个 https://chrome.google.com/webstore/detail/yaaw-for-chrome/dennnbdlpgjgbcjfgaohdahloollfgoc

**Comment by acgotaku** [comment]
@gnwzkd 这个捕捉请求并不能阻止默认的下载啊 不方便...

**Comment by gnwzkd** [comment]
@acgotaku 直接点保存并不会触发默认下载，不能阻止的只是路径窗口，把下载询问位置关了就可以了。不过百度网盘的下载就算捕捉了也下不到，正好和菊苣的百度网盘~~触手~~助手互补，还是异常方便的。

**Comment by acgotaku** [comment]
@gnwzkd 开玩笑! 我的扩展是完美的! 马上就把这个功能加到我的 yaaw for chrome上!

**Comment by XhstormR** [comment]
@acgotaku ......666

**Comment by gnwzkd** [comment]
@acgotaku ✌(´◓ｑ◔｀)✌
