### ISSUE TITLE
无法向本地以外的Aria2 RPC添加任务

### ISSUE THREAD

**Issue by gnwzkd** [acgotaku/BaiduExporter#88]
Chrome版更新0.4.8后，RPC地址那个设置项似乎失效了，即便设为localhost以外的地址，也只会向本地运行的客户端发送任务，同时打开YAAW能够看到路由器10.2.2.1上的aria2状态和添加任务。

**Comment by acgotaku** [comment]
@gnwzkd 这个bug会在下次更新修复

**Comment by gnwzkd** [comment]
@acgotaku 辛苦了！
