### ISSUE TITLE
火狐版插件能否更新最新版？

### ISSUE THREAD

**Issue by ckz1211** [acgotaku/BaiduExporter#89]
火狐插件还停留在三个月前的0.4.2，能否更新到最新版？
另外，再报告火狐插件里的一个BUG，导出下载时，“存为XXX文件”对应的链接是data:text/plain;charset=utf-8,……
这类链接，在Chrome下点击能直接弹出另存为对话框，但在 FF下点击，却无法弹出文件保存对话框，而是直接在网页里显示文本内容……

**Comment by acgotaku** [comment]
@ckz1211 因为最近更新的功能都是基于 Chrome的API实现的 火狐却是滞后了好多 近期会更新的

**Comment by ckz1211** [comment]
@acgotaku   批量导出文件夹内地址，这个问题很严重啊，一定次数后会触发百度的验证码。这之后，不论是下哪一个百度盘链接，弹出验证码几率都是100%（除非下自己网盘），这现象等了一晚上都没好。还好我是PPPOE拨号上网，重启路由换个IP后就没验证码了。不过，如果有人是固定IP，我估计他就悲剧了，一整晚下百度网盘都得输验证码……

**Comment by acgotaku** [comment]
@ckz1211 遇到这种情况 你先保存到自己网盘再下载啊  或者 在设置里面加大 请求间隔的延迟

**Comment by ckz1211** [comment]
@acgotaku   我目前在火狐上用这个脚本 https://greasyfork.org/en/scripts/13434
也就是优先访问WAP版界面。这是因为我听说WAP版不限速，不过实际用过后，感觉和PC版界面也没多大区别？
请问你研究过WAP版和PC版区别么？是否WAP版得到的链接下载速度更快？

**Comment by acgotaku** [comment]
@ckz1211 没研究过 理论上应该没区别

**Comment by acgotaku** [comment]
@ckz1211 限速已经突破了 请重置插件

**Comment by kenlo88** [comment]
android版火狐安裝不上，用github extrnsion installer 強行安裝卻不能运作

**Comment by acgotaku** [comment]
@kenlo88 装上也不能用啊 手机版的网页界面都不一样 我也没做过调试 能用就怪了。。

**Comment by 87848180** [comment]
现在aria  下载 只有5kb  能否更新一下 大神！！

**Comment by 87848180** [comment]
firefox 版本的 忘了说了

**Comment by acgotaku** [comment]
@ckz1211 更新了!!!
