### ISSUE TITLE
更新到 0.4.9 或 0.5.0 后 aria2 导出下载连接为空

### ISSUE THREAD

**Issue by scarletsky** [acgotaku/BaiduExporter#90]
![248fdc53-8967-4d86-943a-dc0b6655951e](https://cloud.githubusercontent.com/assets/2386165/10939011/7547c1f6-8339-11e5-856b-22aa2033aaeb.png)

测试环境：
OS X 10.11
Chrome 46
插件版本 0.4.9 / 0.5.0

不知道是不是个案。

**Comment by acgotaku** [comment]
@scarletsky 新版本架构更新了 可能有点问题 话说这个网盘链接给我测试测试啊

**Comment by scarletsky** [comment]
@acgotaku 我试了好几个都是这样的
http://pan.baidu.com/s/1HmAGu
http://pan.baidu.com/s/1o6w5wme

**Comment by acgotaku** [comment]
@scarletsky 单个文件忘记测试了 我这就测试更新

**Comment by acgotaku** [comment]
@scarletsky 修复了 等推送

**Comment by scarletsky** [comment]
@acgotaku  菊苣太厉害拉~ :smiley:
