### ISSUE TITLE
有谁知道 PC端 Chrome 访问 WAP 版百毒云 的方法吗？

### ISSUE THREAD

**Issue by XhstormR** [acgotaku/BaiduExporter#93]
````
改 UA = Mozilla/5.0 (Linux; Android 5.1.1; Nexus 6 Build/LYZ28E) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/44.0.2403.20 Mobile Safari/537.36 
再访问 http://pan.baidu.com/disk/home 即可。 
Chrome 46.0.2490.71 (正式版本) （64 位）亲测。
````
这上面这个方法以前可行，现在失效了。

**Comment by XhstormR** [comment]
现在用 http://pan.baidu.com/disk/home or http://pan.baidu.com/wap/home 访问，都强制跳转到PC版，网址后缀 http://pan.baidu.com/disk/home?adapt=pc&fr=ftw 。

**Comment by XhstormR** [comment]
现在用 http://pan.baidu.com/disk/home or http://pan.baidu.com/wap/home 访问，都强制跳转到PC版，网址后缀 http://pan.baidu.com/disk/home?adapt=pc&fr=ftw 。

**Comment by acgotaku** [comment]
@XhstormR 我用 Chrome就没有自动跳转啊 话说你这乱开 issue啊 这个 issue除了我 谁能看到啊 ==

这又不是社交网络....

**Comment by Cee** [comment]
Chrome 调试模式。

**Comment by XhstormR** [comment]
@Cee 没用啊

**Comment by acgotaku** [comment]
@XhstormR  我已经测试了 手机版 和PC版 下载链接一样的 别折腾了

**Comment by acgotaku** [comment]
@XhstormR 好了好了 最新版突破限速了 这下真的不用折腾了  赶紧重置软件设置 体验吧

**Comment by XhstormR** [comment]
@acgotaku 非常感谢 thx a lot！
