### ISSUE TITLE
希望加回测试 aria2 rpc 连通的功能

### ISSUE THREAD

**Issue by XIAZY** [acgotaku/BaiduExporter#94]
这个功能很好用啊，改 IP 的时候还可以看看服务器是否通了。
希望能够添加回来。
~~最近每天都更新是为啥呢~~

**Comment by acgotaku** [comment]
@XIAZY 关键是现在多 RPC地址 测试的地方没法选 所以删了

**Comment by ShaoXinSen** [comment]
为啥现在导出RPC失败? aria2 rpc是开了的

**Comment by acgotaku** [comment]
@ShaoXinSen　你是不是开了其它插件禁止 JS执行之类的了

**Comment by XIAZY** [comment]
我倒是觉得可以加一个 checkbox 之类的东西来选择一个 aria2 rpc 服务器来测试连通性，应该会方便一些

发自我的 iPad

**Comment by acgotaku** [comment]
@XIAZY 设置菜单太小 再加东西 放不下了啊
