### ISSUE TITLE
能不能把下载连接直接显示在提示框内啊，大神！

### ISSUE THREAD

**Issue by lsnmx** [acgotaku/BaiduExporter#95]
能不能把下载连接直接显示在提示框内啊，大神！
@acgotaku 
@Cee

**Comment by acgotaku** [comment]
@lsnmx 你点导出下载 不是有下载链接的么！

**Comment by lsnmx** [comment]
@acgotaku 哪个连接不能下载啊，好吧这个连接能不能直接像保存下去连接哪样，是http:// 开头啊，这样直接得到到各种下载软件都可以
aria2c -c -s10 -k1M -x10 -o "com.telltalegames.borderlands100_muzhiwan.com-V4_2-JS-JG-Adreno-V1.74.gpk" --header "User-Agent: netdisk;5.3.4.5;PC;PC-Windows;5.1.2600;WindowsBaiduYunGuanJia"  --header "Referer: http://pan.baidu.com/disk/home"  --header "Cookie: BDUSS=HJDRDUyUmV6bUFKdFdwak81UjlSV2lzaEw5RHlaMUs2R3c5Q3QzQkpZUWF3RkpXQVFBQUFBJCQAAAAAAAAAAAEAAACH6302xPvDykxzbm14AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABozK1YaMytWc;BAIDUID=C17DFAFB752C0160A86D3CF6F3F2BF44:FG=1"  "http://d.pcs.baidu.com/file/16d2baf971ebc5e5dc6055dd2707f944?fid=3945974178-250528-380198611621065&time=1447057040&rt=pr&sign=FDTAER-DCb740ccc5511e5e8fedcff06b081203-DE7bQHdV7zrDGhrOqK5ZS7dOy7M%3d&expires=8h&chkbd=0&chkv=0&dp-logid=7251901931629787221&dp-callid=0&r=962807025"

**Comment by acgotaku** [comment]
@lsnmx 点一下保存会死啊! 能这么懒我也是醉了 还有 保存了也没用 默认的下载链接是限速的

不带下载参数的下载 顶多就 200K
