### ISSUE TITLE
希望在设置中增加代理设置

### ISSUE THREAD

**Issue by bill9109** [acgotaku/BaiduExporter#98]
现在用代理下载还得手动添加，略麻烦，谢谢。

**Comment by acgotaku** [comment]
@bill9109 啥意思？ 你这样说的不明不白 我很困扰啊

**Comment by bill9109** [comment]
非RPC模式，在插件的设置页面没法设置代理，只能在导出的命令里手动输入代理设置。
RPC模式下下载速度不如命令行，不知道为什么…

**Comment by acgotaku** [comment]
@bill9109 你能举个例子么? 代理设置具体加了什么参数?

**Comment by XhstormR** [comment]
aria2c --all-proxy="10.34.3.71:808" http://www.baidu.com/?

**Comment by bill9109** [comment]
--all-proxy="127.0.0.1:8118" 这种

**Comment by acgotaku** [comment]
@bill9109 这种需求不是很大 你还是自己手动加吧
