### ISSUE TITLE
貌似现在用不了

### ISSUE THREAD

**Issue by leitwolf** [acgotaku/BaiduExporter#99]
好像今天百度云更新了，下载的选项都不出来了。
firefox42.

**Comment by luokar** [comment]
看来不只是我一个，chrome 47.0.2526.73 m

**Comment by luokar** [comment]
看来百度只是试试水温，界面又改回来了。

**Comment by acgotaku** [comment]
@leitwolf FF好久没更新了 暂时先用 Chrome版本 最近有点忙 没跟进更新...

**Comment by leitwolf** [comment]
又可以了，果然是试水温而已

**Comment by Chu2koi** [comment]
FF版本还是可以用的

**Comment by acgotaku** [comment]
@Chu2koi 但是你得手动更新 UA

**Comment by Chu2koi** [comment]
@acgotaku 我没更新过UA啊，直接安装就能用了- -

**Comment by dknc** [comment]
Chrome Version 46.0.2490.86 (64-bit) Mac version 还是有问题，没法初始化，生成导出下载的菜单

**Comment by acgotaku** [comment]
@dknc Mac版本我现在没有测试环境 抱歉。。。 但是这个和平台应该没多大关系吧？
你可以 按 F12看看控制台有没有什么错误输出

**Comment by Earthson** [comment]
![image](https://cloud.githubusercontent.com/assets/1193039/11707880/568f776e-9f44-11e5-9700-1dfbcc2e28b5.png)

不知道这个报错是不是？

**Comment by acgotaku** [comment]
@Earthson 这个不是我插件的ID 你检查检查是不是插件冲突？

**Comment by Earthson** [comment]
我把别的插件都禁用了，没这个错误，但是还是不能用Orz。我昨天还用得好好的，今天就不行了

![image](https://cloud.githubusercontent.com/assets/1193039/11708005/87a10bdc-9f45-11e5-8dc0-6b522ea9a74b.png)

**Comment by acgotaku** [comment]
@Earthson 我只看见正常的 输出log 没看见错误的啊 囧

**Comment by pepsing** [comment]
![7ed64f32-533d-47a2-9224-fd5140635a56](https://cloud.githubusercontent.com/assets/7865992/11709533/5f426902-9f53-11e5-8378-c48eca857c11.jpg)
chrome 47 有报错

**Comment by Cee** [comment]
@pepsing 是否屏蔽了百度的 toast.js？

**Comment by leitwolf** [comment]
今天又改版，菜单出不来了。。。

**Comment by jiayiming** [comment]
今天确实乙烷了

**Comment by acgotaku** [comment]
等更新!

**Comment by zhurui1008** [comment]
分享－>链接－>私密链接
然后进入自己的分享页就可以导出下载了

**Comment by leitwolf** [comment]
@zhurui1008 目前也是这样用，不过不方便。

**Comment by acgotaku** [comment]
@leitwolf 总得等我写出来新版本吧!!!

**Comment by leitwolf** [comment]
@acgotaku 嗯，知道了，谢谢。我其实不是在催，在跟大家聊聊:)

**Comment by zhurui1008** [comment]
你是有多寂寞啊。。。

**Comment by acgotaku** [comment]
我的邮箱都被轰炸了....

**Comment by zhurui1008** [comment]
作者君，有几个问题想请教你。。。
我是OS X平台（10.11 EI Capitan）的，FF的插件点导出到aria2显示成功，但是aria2里面没有新添加的任务。FF版地址如果不改成ws://localhost:6800/jsonrpc 点插件的导出到aria2 显示失败。改了的话现实添加成功，但aria2里并没有新任务。。何解？

然后下载了safari的插件，结果safari导入－>点信任，插件并没有安装。。所以现在换成了chrome beta了。

**Comment by acgotaku** [comment]
@zhurui1008 FF版年久失修 等我 更新好这个大更新 想好完美的重构方案 再去修那个... 现在只能确保 Chrome没问题  Safari是有 @Cee 移植的 具体的事情我不清楚

**Comment by zhurui1008** [comment]
好的，谢谢作者君。我去视奸 @Cee 去。。

**Comment by acgotaku** [comment]
@leitwolf 更新了!  赶紧体验吧!

**Comment by leitwolf** [comment]
哇，很神速啊，厉害

**Comment by acgotaku** [comment]
跟百度网盘斗智斗勇 经验丰富!

**Comment by leitwolf** [comment]
额，我用的是FF。。。

**Comment by acgotaku** [comment]
@leitwolf  FF更新遥遥无期  还是换Chrome吧

**Comment by leitwolf** [comment]
过几天改用win10笔记本作主力机，到时再换了。。。
目前还是用 私密链接 过渡过渡。。。

**Comment by gz0007** [comment]
果然够隐蔽啊@zhurui1008

**Comment by liyiecho** [comment]
chrome 47.0.2526.80，昨晚0.5.5还能正常显示选项的，今天0.5.6居然不能显示选项了。。。不知道是不是我一个人这样

**Comment by acgotaku** [comment]
@liyiecho 百度新界面升级 貌似还没全面铺开 老界面请下载旧版本 https://github.com/acgotaku/BaiduExporter/releases/tag/v0.5.5

**Comment by liyiecho** [comment]
@acgotaku 囧，退出帐号后重新登录，可以正常显示了，不知道百度抽什么风了

**Comment by Cee** [comment]
Safari 近日更新。

**Comment by yujiangshui** [comment]
现在我的 chrome 也直接没有按钮展示了，之前还好好的。看来最近真的改版了。

**Comment by 15cm** [comment]
我这目前还是老界面，降回0.5.5可以使用。

**Comment by acgotaku** [comment]
@15cm 机智!

**Comment by 15cm** [comment]
@acgotaku 回滚没多久又看到了秋水酱的更新提示。只好重新打包crx，暂且把自动更新去掉了233 （百度你要升级就麻利点啊（＞д＜）

**Comment by acgotaku** [comment]
我已经把老的crx放到 release了  下载就能用了~  @15cm 

https://github.com/acgotaku/BaiduExporter/releases/tag/v0.5.5

**Comment by acgotaku** [comment]
@15cm 你是说 谷歌的自动升级啊! 那个只能强行改版本号了吧....

**Comment by yujiangshui** [comment]
更新新版之后，功能可用，强烈感谢 @acgotaku

**Comment by 15cm** [comment]
@acgotaku 我是把update_url去掉了...原来改个版本号也能蒙骗过去呀

**Comment by acgotaku** [comment]
@yujiangshui 喜欢就点个赞啦~  

@15cm 我只是这样猜测的 不知道对不对 我都是开发者模式加载对应版本的插件源码使用的

**Comment by 15cm** [comment]
@acgotaku 感觉应该都可以吧，不知道谷歌检查更新的机制。反正去掉update_url的方法有效。不过估计过不了多久百度更新到我这的时候又得用0.5.6了。
秋水酱加油更(liao)新(mei)，我可是会继续安利这个项目的哦~

**Comment by shikkoku** [comment]
0.5.7 无法载入插件。没有初始化成功提示。

**Comment by acgotaku** [comment]
@shikkoku 可以 F12下看看 有没有什么异常输出么?

**Comment by shikkoku** [comment]
all_15fd3a0.js:5 GET http://127.0.0.1:10000/guanjia?method=GetVersion&bdstoken=ff2950fc37bf54f81139172372e31b77&channel=chunlei&clienttype=0&web=1&app_id=250528 net::ERR_CONNECTION_REFUSEDsend @ all_15fd3a0.js:5O.extend.ajax @ all_15fd3a0.js:5O.(anonymous function) @ all_15fd3a0.js:5(anonymous function) @ ??clouddisk-ui-cdn/js/prevent-contextmenu_c61bb4b.js,clouddisk-ui-cdn/pkg/activity-disk-home_a7950c…:3c.util.checkLocalServer @ ??clouddisk-ui-cdn/js/prevent-contextmenu_c61bb4b.js,clouddisk-ui-cdn/pkg/activity-disk-home_a7950c…:3c.util.init @ ??clouddisk-ui-cdn/js/prevent-contextmenu_c61bb4b.js,clouddisk-ui-cdn/pkg/activity-disk-home_a7950c…:3(anonymous function) @ ??clouddisk-ui-cdn/js/prevent-contextmenu_c61bb4b.js,clouddisk-ui-cdn/pkg/activity-disk-home_a7950c…:3t @ all_15fd3a0.js:1(anonymous function) @ home:964(anonymous function) @ home:965
all_15fd3a0.js:5 GET http://127.0.0.1:10001/guanjia?method=GetVersion&bdstoken=ff2950fc37bf54f81139172372e31b77&channel=chunlei&clienttype=0&web=1&app_id=250528 net::ERR_CONNECTION_REFUSEDsend @ all_15fd3a0.js:5O.extend.ajax @ all_15fd3a0.js:5O.(anonymous function) @ all_15fd3a0.js:5(anonymous function) @ ??clouddisk-ui-cdn/js/prevent-contextmenu_c61bb4b.js,clouddisk-ui-cdn/pkg/activity-disk-home_a7950c…:3c.util.checkLocalServer @ ??clouddisk-ui-cdn/js/prevent-contextmenu_c61bb4b.js,clouddisk-ui-cdn/pkg/activity-disk-home_a7950c…:3c.util.init @ ??clouddisk-ui-cdn/js/prevent-contextmenu_c61bb4b.js,clouddisk-ui-cdn/pkg/activity-disk-home_a7950c…:3(anonymous function) @ ??clouddisk-ui-cdn/js/prevent-contextmenu_c61bb4b.js,clouddisk-ui-cdn/pkg/activity-disk-home_a7950c…:3t @ all_15fd3a0.js:1(anonymous function) @ home:964(anonymous function) @ home:965
all_15fd3a0.js:5 GET http://127.0.0.1:10002/guanjia?method=GetVersion&bdstoken=ff2950fc37bf54f81139172372e31b77&channel=chunlei&clienttype=0&web=1&app_id=250528 net::ERR_CONNECTION_REFUSEDsend @ all_15fd3a0.js:5O.extend.ajax @ all_15fd3a0.js:5O.(anonymous function) @ all_15fd3a0.js:5(anonymous function) @ ??clouddisk-ui-cdn/js/prevent-contextmenu_c61bb4b.js,clouddisk-ui-cdn/pkg/activity-disk-home_a7950c…:3c.util.checkLocalServer @ ??clouddisk-ui-cdn/js/prevent-contextmenu_c61bb4b.js,clouddisk-ui-cdn/pkg/activity-disk-home_a7950c…:3c.util.init @ ??clouddisk-ui-cdn/js/prevent-contextmenu_c61bb4b.js,clouddisk-ui-cdn/pkg/activity-disk-home_a7950c…:3(anonymous function) @ ??clouddisk-ui-cdn/js/prevent-contextmenu_c61bb4b.js,clouddisk-ui-cdn/pkg/activity-disk-home_a7950c…:3t @ all_15fd3a0.js:1(anonymous function) @ home:964(anonymous function) @ home:965
all_15fd3a0.js:5 GET http://127.0.0.1:10003/guanjia?method=GetVersion&bdstoken=ff2950fc37bf54f81139172372e31b77&channel=chunlei&clienttype=0&web=1&app_id=250528 net::ERR_CONNECTION_REFUSEDsend @ all_15fd3a0.js:5O.extend.ajax @ all_15fd3a0.js:5O.(anonymous function) @ all_15fd3a0.js:5(anonymous function) @ ??clouddisk-ui-cdn/js/prevent-contextmenu_c61bb4b.js,clouddisk-ui-cdn/pkg/activity-disk-home_a7950c…:3c.util.checkLocalServer @ ??clouddisk-ui-cdn/js/prevent-contextmenu_c61bb4b.js,clouddisk-ui-cdn/pkg/activity-disk-home_a7950c…:3c.util.init @ ??clouddisk-ui-cdn/js/prevent-contextmenu_c61bb4b.js,clouddisk-ui-cdn/pkg/activity-disk-home_a7950c…:3(anonymous function) @ ??clouddisk-ui-cdn/js/prevent-contextmenu_c61bb4b.js,clouddisk-ui-cdn/pkg/activity-disk-home_a7950c…:3t @ all_15fd3a0.js:1(anonymous function) @ home:964(anonymous function) @ home:965
all_15fd3a0.js:5 GET http://127.0.0.1:10004/guanjia?method=GetVersion&bdstoken=ff2950fc37bf54f81139172372e31b77&channel=chunlei&clienttype=0&web=1&app_id=250528 net::ERR_CONNECTION_REFUSEDsend @ all_15fd3a0.js:5O.extend.ajax @ all_15fd3a0.js:5O.(anonymous function) @ all_15fd3a0.js:5(anonymous function) @ ??clouddisk-ui-cdn/js/prevent-contextmenu_c61bb4b.js,clouddisk-ui-cdn/pkg/activity-disk-home_a7950c…:3c.util.checkLocalServer @ ??clouddisk-ui-cdn/js/prevent-contextmenu_c61bb4b.js,clouddisk-ui-cdn/pkg/activity-disk-home_a7950c…:3c.util.init @ ??clouddisk-ui-cdn/js/prevent-contextmenu_c61bb4b.js,clouddisk-ui-cdn/pkg/activity-disk-home_a7950c…:3(anonymous function) @ ??clouddisk-ui-cdn/js/prevent-contextmenu_c61bb4b.js,clouddisk-ui-cdn/pkg/activity-disk-home_a7950c…:3t @ all_15fd3a0.js:1(anonymous function) @ home:964(anonymous function) @ home:965
all_15fd3a0.js:5 GET http://127.0.0.1:10005/guanjia?method=GetVersion&bdstoken=ff2950fc37bf54f81139172372e31b77&channel=chunlei&clienttype=0&web=1&app_id=250528 net::ERR_CONNECTION_REFUSEDsend @ all_15fd3a0.js:5O.extend.ajax @ all_15fd3a0.js:5O.(anonymous function) @ all_15fd3a0.js:5(anonymous function) @ ??clouddisk-ui-cdn/js/prevent-contextmenu_c61bb4b.js,clouddisk-ui-cdn/pkg/activity-disk-home_a7950c…:3c.util.checkLocalServer @ ??clouddisk-ui-cdn/js/prevent-contextmenu_c61bb4b.js,clouddisk-ui-cdn/pkg/activity-disk-home_a7950c…:3c.util.init @ ??clouddisk-ui-cdn/js/prevent-contextmenu_c61bb4b.js,clouddisk-ui-cdn/pkg/activity-disk-home_a7950c…:3(anonymous function) @ ??clouddisk-ui-cdn/js/prevent-contextmenu_c61bb4b.js,clouddisk-ui-cdn/pkg/activity-disk-home_a7950c…:3t @ all_15fd3a0.js:1(anonymous function) @ home:964(anonymous function) @ home:965
all_15fd3a0.js:5 GET http://127.0.0.1:10006/guanjia?method=GetVersion&bdstoken=ff2950fc37bf54f81139172372e31b77&channel=chunlei&clienttype=0&web=1&app_id=250528 net::ERR_CONNECTION_REFUSEDsend @ all_15fd3a0.js:5O.extend.ajax @ all_15fd3a0.js:5O.(anonymous function) @ all_15fd3a0.js:5(anonymous function) @ ??clouddisk-ui-cdn/js/prevent-contextmenu_c61bb4b.js,clouddisk-ui-cdn/pkg/activity-disk-home_a7950c…:3c.util.checkLocalServer @ ??clouddisk-ui-cdn/js/prevent-contextmenu_c61bb4b.js,clouddisk-ui-cdn/pkg/activity-disk-home_a7950c…:3c.util.init @ ??clouddisk-ui-cdn/js/prevent-contextmenu_c61bb4b.js,clouddisk-ui-cdn/pkg/activity-disk-home_a7950c…:3(anonymous function) @ ??clouddisk-ui-cdn/js/prevent-contextmenu_c61bb4b.js,clouddisk-ui-cdn/pkg/activity-disk-home_a7950c…:3t @ all_15fd3a0.js:1(anonymous function) @ home:964(anonymous function) @ home:965
all_15fd3a0.js:5 GET http://127.0.0.1:10009/guanjia?method=GetVersion&bdstoken=ff2950fc37bf54f81139172372e31b77&channel=chunlei&clienttype=0&web=1&app_id=250528 net::ERR_CONNECTION_REFUSEDsend @ all_15fd3a0.js:5O.extend.ajax @ all_15fd3a0.js:5O.(anonymous function) @ all_15fd3a0.js:5(anonymous function) @ ??clouddisk-ui-cdn/js/prevent-contextmenu_c61bb4b.js,clouddisk-ui-cdn/pkg/activity-disk-home_a7950c…:3c.util.checkLocalServer @ ??clouddisk-ui-cdn/js/prevent-contextmenu_c61bb4b.js,clouddisk-ui-cdn/pkg/activity-disk-home_a7950c…:3c.util.init @ ??clouddisk-ui-cdn/js/prevent-contextmenu_c61bb4b.js,clouddisk-ui-cdn/pkg/activity-disk-home_a7950c…:3(anonymous function) @ ??clouddisk-ui-cdn/js/prevent-contextmenu_c61bb4b.js,clouddisk-ui-cdn/pkg/activity-disk-home_a7950c…:3t @ all_15fd3a0.js:1(anonymous function) @ home:964(anonymous function) @ home:965
all_15fd3a0.js:5 GET http://127.0.0.1:10008/guanjia?method=GetVersion&bdstoken=ff2950fc37bf54f81139172372e31b77&channel=chunlei&clienttype=0&web=1&app_id=250528 net::ERR_CONNECTION_REFUSEDsend @ all_15fd3a0.js:5O.extend.ajax @ all_15fd3a0.js:5O.(anonymous function) @ all_15fd3a0.js:5(anonymous function) @ ??clouddisk-ui-cdn/js/prevent-contextmenu_c61bb4b.js,clouddisk-ui-cdn/pkg/activity-disk-home_a7950c…:3c.util.checkLocalServer @ ??clouddisk-ui-cdn/js/prevent-contextmenu_c61bb4b.js,clouddisk-ui-cdn/pkg/activity-disk-home_a7950c…:3c.util.init @ ??clouddisk-ui-cdn/js/prevent-contextmenu_c61bb4b.js,clouddisk-ui-cdn/pkg/activity-disk-home_a7950c…:3(anonymous function) @ ??clouddisk-ui-cdn/js/prevent-contextmenu_c61bb4b.js,clouddisk-ui-cdn/pkg/activity-disk-home_a7950c…:3t @ all_15fd3a0.js:1(anonymous function) @ home:964(anonymous function) @ home:965
all_15fd3a0.js:5 GET http://127.0.0.1:10007/guanjia?method=GetVersion&bdstoken=ff2950fc37bf54f81139172372e31b77&channel=chunlei&clienttype=0&web=1&app_id=250528 net::ERR_CONNECTION_REFUSEDsend @ all_15fd3a0.js:5O.extend.ajax @ all_15fd3a0.js:5O.(anonymous function) @ all_15fd3a0.js:5(anonymous function) @ ??clouddisk-ui-cdn/js/prevent-contextmenu_c61bb4b.js,clouddisk-ui-cdn/pkg/activity-disk-home_a7950c…:3c.util.checkLocalServer @ ??clouddisk-ui-cdn/js/prevent-contextmenu_c61bb4b.js,clouddisk-ui-cdn/pkg/activity-disk-home_a7950c…:3c.util.init @ ??clouddisk-ui-cdn/js/prevent-contextmenu_c61bb4b.js,clouddisk-ui-cdn/pkg/activity-disk-home_a7950c…:3(anonymous function) @ ??clouddisk-ui-cdn/js/prevent-contextmenu_c61bb4b.js,clouddisk-ui-cdn/pkg/activity-disk-home_a7950c…:3t @ all_15fd3a0.js:1(anonymous function) @ home:964(anonymous function) @ home:965
qd.cache.baidupcs.com/monitor.jpg?xcode=1a81b0bbd448fc36f65202d7e8f159404c932f26aaa77f9c&t=14499813941449981422065:1 GET http://qd.cache.baidupcs.com/monitor.jpg?xcode=1a81b0bbd448fc36f65202d7e8f159404c932f26aaa77f9c&t=14499813941449981422065 net::ERR_CONNECTION_TIMED_OUT
nj.cache.baidupcs.com/monitor.jpg?xcode=1a81b0bbd448fc36f65202d7e8f159404c932f26aaa77f9c&t=14499813941449981452429:1 GET http://nj.cache.baidupcs.com/monitor.jpg?xcode=1a81b0bbd448fc36f65202d7e8f159404c932f26aaa77f9c&t=14499813941449981452429 net::ERR_NAME_NOT_RESOLVED
all_15fd3a0.js:1 Uncaught Error: Cannot find module `disk-system:widget/context/context.js`

**Comment by acgotaku** [comment]
@shikkoku 你这发的什么鬼 截图就行 没有排版 鬼看的懂啊...... 而且这都是百度自己的报错 和我插件没关系...

**Comment by shikkoku** [comment]
![snip_20151213124156](https://cloud.githubusercontent.com/assets/4697177/11765539/e08aa868-a196-11e5-8dff-2a5550823335.jpg)
这个也是？反正不知道为什么按钮加载不出来。

**Comment by acgotaku** [comment]
@shikkoku 这个错误就说明你得下载 0.5.5版本 
https://github.com/acgotaku/BaiduExporter/releases/tag/v0.5.5  这句话这个帖子里我都说了 3遍了吧...

**Comment by shikkoku** [comment]
0.5.5确实正常，然而到底是什么原因……

**Comment by acgotaku** [comment]
@shikkoku 我不都解释了....部分用户收到了新界面的推送 老用户没有收到 就只能用旧版 你就不能耐心的看完这整个帖子?!

**Comment by leitwolf** [comment]
我今天用了QQ浏览器，下的是0.5.7版本，发现选项没出来，然后查看控制台，发现好玩的东西哈哈。
![Uploading 1.png…]()

**Comment by only-a-big-K** [comment]
still waiting on safari

**Comment by Laputa-Skywalker** [comment]
版本 0.5.7 無法保存設置
請修正 (按N次也沒反應)

**Comment by acgotaku** [comment]
@Laputa-Skywalker 请问你Chrome浏览器登录用户了么？

**Comment by Laputa-Skywalker** [comment]
有的，按了也是沒反應
刪了重裝也解決不了

**Comment by acgotaku** [comment]
@Laputa-Skywalker 设置界面左上角没提示？ 那你打开 f12 console 给我看看截图

**Comment by Laputa-Skywalker** [comment]
event.returnValue is deprecated. Please use the standard event.preventDefault() instead.
Failed to execute 'write' on 'Document': It isn't possible to write into a document from an asynchronously-loaded external script unless it is explicitly opened. home:1
Failed to load resource: net::ERR_CONNECTION_REFUSED http://127.0.0.1:10000/guanjia?method=GetVersion&bdstoken=b103211947773a9d721078b7ef3853eb&channel=chunlei&clienttype=0&web=1&app_id=250528
Failed to load resource: net::ERR_CONNECTION_REFUSED http://127.0.0.1:10001/guanjia?method=GetVersion&bdstoken=b103211947773a9d721078b7ef3853eb&channel=chunlei&clienttype=0&web=1&app_id=250528
Uncaught TypeError: undefined is not a function connect.js:12
Uncaught Error: Invalid arguments to connect. VM28 extensions::runtime:141
Failed to load resource: net::ERR_CONNECTION_REFUSED http://127.0.0.1:10002/guanjia?method=GetVersion&bdstoken=b103211947773a9d721078b7ef3853eb&channel=chunlei&clienttype=0&web=1&app_id=250528
Failed to load resource: net::ERR_CONNECTION_REFUSED http://127.0.0.1:10003/guanjia?method=GetVersion&bdstoken=b103211947773a9d721078b7ef3853eb&channel=chunlei&clienttype=0&web=1&app_id=250528
Failed to load resource: net::ERR_CONNECTION_REFUSED http://127.0.0.1:10004/guanjia?method=GetVersion&bdstoken=b103211947773a9d721078b7ef3853eb&channel=chunlei&clienttype=0&web=1&app_id=250528
Failed to load resource: net::ERR_CONNECTION_REFUSED http://127.0.0.1:10005/guanjia?method=GetVersion&bdstoken=b103211947773a9d721078b7ef3853eb&channel=chunlei&clienttype=0&web=1&app_id=250528
Failed to load resource: net::ERR_CONNECTION_REFUSED http://127.0.0.1:10006/guanjia?method=GetVersion&bdstoken=b103211947773a9d721078b7ef3853eb&channel=chunlei&clienttype=0&web=1&app_id=250528
Failed to load resource: net::ERR_CONNECTION_REFUSED http://127.0.0.1:10007/guanjia?method=GetVersion&bdstoken=b103211947773a9d721078b7ef3853eb&channel=chunlei&clienttype=0&web=1&app_id=250528
Failed to load resource: net::ERR_CONNECTION_REFUSED http://127.0.0.1:10008/guanjia?method=GetVersion&bdstoken=b103211947773a9d721078b7ef3853eb&channel=chunlei&clienttype=0&web=1&app_id=250528
Failed to load resource: net::ERR_CONNECTION_REFUSED http://127.0.0.1:10009/guanjia?method=GetVersion&bdstoken=b103211947773a9d721078b7ef3853eb&channel=chunlei&clienttype=0&web=1&app_id=250528
Failed to load resource: net::ERR_CONNECTION_TIMED_OUT http://qd.cache.baidupcs.com/monitor.jpg?xcode=1a81b0bbd448fc36f65202d7e8f159404c932f26aaa77f9c&t=14501588631450158938756
Failed to load resource: net::ERR_NAME_NOT_RESOLVED http://nj.cache.baidupcs.com/monitor.jpg?xcode=1a81b0bbd448fc36f65202d7e8f159404c932f26aaa77f9c&t=14501588631450158948287
5
Uncaught Error: Invalid arguments to connect. VM28 extensions::runtime:141
2
Uncaught Error: Invalid arguments to connect.

**Comment by acgotaku** [comment]
@Laputa-Skywalker 都说了 截图 你这个格式 看着就头大。。。

**Comment by Laputa-Skywalker** [comment]
http://i.imgur.com/YaU8WWQ.png

**Comment by acgotaku** [comment]
@Laputa-Skywalker 你这个是Chrome浏览器？ 版本号多少？

**Comment by Laputa-Skywalker** [comment]
我本身用mychrome + chrome免安裝版 版本 34.0.1847.137 dev-m
WinXP SP3

**Comment by acgotaku** [comment]
@Laputa-Skywalker 我觉得就是非官方版导致 API不能正常使用的原因 你可以把最后两个错误展开么？

**Comment by Laputa-Skywalker** [comment]
都是portable版，最新版反而會拖慢XP系統所以不更新了，之前是用更古老的32.0.1700.107免裝版

http://i.imgur.com/AeNbLA1.png

**Comment by acgotaku** [comment]
@Laputa-Skywalker 但真的是 API的原因。。。 无法正常使用也没办法 ==

**Comment by Laputa-Skywalker** [comment]
之前0.5.5還是好好的使用中，更新到0.5.7就出問題了
裝回0.5.5就不給我顯示 = =

**Comment by acgotaku** [comment]
@Laputa-Skywalker 因为你界面换 新 UI了吧 我这次加了 同步配置数据的新功能 API比较新 。。。

**Comment by Laputa-Skywalker** [comment]
我不覺得跟免安裝版有關係，而且免安裝版只是去掉谷歌的自動更新

**Comment by Laputa-Skywalker** [comment]
chrome更新愈後版本就愈改愈慢，難道你不可以弄成兼容舊版嗎

**Comment by acgotaku** [comment]
@Laputa-Skywalker 那你觉得是什么问题？ 我代码有问题？ 新版本有新版本的好处啊  == 新的API 使用更方便

**Comment by Laputa-Skywalker** [comment]
我用新版的速度還不如舊版，難道你沒用XP?

**Comment by acgotaku** [comment]
@Laputa-Skywalker 我用的 win 10   
https://github.com/acgotaku/BaiduExporter/releases/tag/v0.5.6

这是 0.5.6的版本 你用这个应该没问题

**Comment by joyfun** [comment]
貌似有bug     
    var newVersion = typeof manifest == "object" ? true : false;
这个判断 newVersion应该一直是true呀

**Comment by acgotaku** [comment]
@joyfun 老版本的 UI会返回  false的 因为压根没这个变量

**Comment by Laputa-Skywalker** [comment]
感謝 0.5.6 能用

**Comment by joyfun** [comment]
但是实际使用的时候会出错 比如 aria2没开 点下载 本来会提示报错的 但是 走的是新ui分之 Toast没初始化 
控制台会报错 页面没任何提示

**Comment by Laputa-Skywalker** [comment]
我建議是把0.5.7下架的，我覺得新的API問題太多了，不支援Chrome40以下的版本

**Comment by Laputa-Skywalker** [comment]
我試過用Chrome 39也不能正常用，那根本和舊版沒太大關係了

**Comment by acgotaku** [comment]
@Laputa-Skywalker 时代潮流是更新的 你建议也没用 我不能因为你一个人而去妥协

**Comment by acgotaku** [comment]
@joyfun 能截图看看么 我怎么触发不了这个  BUG

**Comment by Laputa-Skywalker** [comment]
@acgotaku 0.5.6 能用還好 是XP系統比較麻煩點 之後可能改回用安裝版

**Comment by acgotaku** [comment]
@Laputa-Skywalker 连微软都不支持Xp了 我怎么可能有那心思支持老版本

**Comment by Laputa-Skywalker** [comment]
@acgotaku 雙核機用w7比xp更慢 我新買的i7都直接w7了 (反正不喜歡w10，不能裝XP Mode

**Comment by leitwolf** [comment]
win10版本10586.29
chrome版本 47.0.2526.80 m (64-bit)
版本 0.5.8 和 0.5.7
可出现菜单，也可设置，但点下载之后，只出现“获取文件信息成功”，之后就没了，最终也没有成功。
记得以前成功的时候还有一个提示信息的。

**Comment by joyfun** [comment]
重现步骤 关掉aria2c 然后点导出下载
![image](https://cloud.githubusercontent.com/assets/470369/11805996/f4edeb8e-a34a-11e5-9519-2915c75c2152.png)
具体出错的代码在  core.js
   if(newVersion){
                var Toast = require("disk-system:widget/context/context.js").instanceForSystem;
                Toast.ui.tip({
                    mode: type,
                    msg: msg
                }); 
            }else{
              
 楼上 @leitwolf 说的貌似是一个bug

**Comment by acgotaku** [comment]
@joyfun 这个我知道了 会修复的

**Comment by acgotaku** [comment]
@joyfun 已更新

**Comment by joyfun** [comment]
测试没问题

**Comment by leitwolf** [comment]
我那个问题还在，0.5.9
貌似是取不到下载地址。
有个信息是在home.js的136行，第一个参数是：
"http://d.pcs.baidu.com/file/5cced3f4070998deef34c802d10d9622?fid=2033501217-250528-572445007439718&time=1450184791&rt=pr&sign=FDTAER-DCb740ccc5511e5e8fedcff06b081203-YSjWCbWb36Whu%2bVD%2beBpELIBCzQ%3d&expires=8h&chkbd=0&chkv=0&dp-logid=8091501140942719285&dp-callid=0&r=995039015"

**Comment by acgotaku** [comment]
@leitwolf 136行是输出 LOG 你这个问题还是截图比较好...

**Comment by leitwolf** [comment]
应该是得到下载路径了，好像是发送到aria2不成功，我仔细比对了chrome和qq浏览器的设置信息，是一样的，但就是chrome的不成功，真是奇怪了。

**Comment by snhun** [comment]
FF，弱弱的看你们聊天

**Comment by acgotaku** [comment]
@leitwolf 让我看看截图啊 这样描述我也不知道原因啊 QAQ

**Comment by tafolu** [comment]
装了Safari扩展，一开始有用，后来用了 chrome扩展，Safari扩展失效了，按钮不出现了，chrome 还是没问题可以用，请问下 ，Safari和Chrome这2个扩展不能共存吗，还是有冲突啊，还是Safari扩展的问题，谢谢

**Comment by acgotaku** [comment]
@tafolu 你这逻辑不对啊 这俩浏览器哪来的冲突啊 只不过Safari没及时更新而已

**Comment by tafolu** [comment]
@acgotaku 嗯，我觉得也是，重装了好几次Safari扩展了，还是跳不出来，郁闷啊，早上安装后还行的呢，不知道怎么回事！！5555

**Comment by acgotaku** [comment]
@tafolu 你没发现你网盘的UI稍微变了 百度升级了 你得等Safari插件升级 Safari的作者最近生病了 你先用Chrome凑合着用行不

**Comment by tafolu** [comment]
@acgotaku  谢谢答复，更新下问题，原来Safari下别人的网盘下能跳出按钮，就是自己的网盘跳不出按钮，Chrome都行，完美！谢谢！

**Comment by acgotaku** [comment]
@tafolu 那是因为就 自己网盘那个页面更新了!

**Comment by tafolu** [comment]
@acgotaku  嗯，好的，那只能静等Cee移植更新了，谢谢

**Comment by chenshifei** [comment]
我这里也一样是点击之后卡在获取文件信息成功，没法发送到远程 aria2 上。用的是 OSX 10.11.2 ＋  Chrome 48，附上控制台截图，也许和 @leitwolf 的情况一样。

<img width="482" alt="2015-12-16 10 35 54" src="https://cloud.githubusercontent.com/assets/1863220/11843776/5cb25542-a446-11e5-8d13-3935bda176f9.png">

**Comment by lhmtnb** [comment]
Safari version 9.0.2 (11601.3.9) 在百度云主界面不能看到导出的按键，看了下面讨论貌似退出重新登录能有，然而测试也不能使用。最后使用 @zhurui1008 的方法，创建私密链接页面可以使用。

**Comment by acgotaku** [comment]
@chenshifei 你这个报错是这个插件的好么!!!
https://chrome.google.com/webstore/detail/evernote-web-clipper/pioclpoplcdbaefihamjohnefbikjilc?hl=en

怎么都怪到我头上来.... 你把这个插件禁用试试?

**Comment by Cee** [comment]
Hey all. Release v0.5.9!
